Gazebo Msgs: CameraLens Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
CameraLens Class Reference
#include <camera_lens.pb.h>
Public Member Functions
CameraLens ()
CameraLens (const CameraLens &from)
virtual ~CameraLens ()
size_t ByteSizeLong () const final
double c1 () const
double c2 () const
double c3 () const
void Clear () final
void clear_c1 ()
void clear_c2 ()
void clear_c3 ()
void clear_cutoff_angle ()
void clear_env_texture_size ()
void clear_f ()
void clear_fun ()
void clear_header ()
void clear_hfov ()
void clear_scale_to_hfov ()
void clear_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const CameraLens &from)
double cutoff_angle () const
::google::protobuf::int32 env_texture_size () const
double f () const
const ::std::string & fun () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
double hfov () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const CameraLens &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_fun ()
::gz::msgs::Header * mutable_header ()
::std::string * mutable_type ()
CameraLens * New () const final
CameraLens * New (::google::protobuf::Arena *arena) const final
CameraLens & operator= (const CameraLens &from)
::std::string * release_fun ()
::gz::msgs::Header * release_header ()
::std::string * release_type ()
bool scale_to_hfov () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_fun (::std::string *fun)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_type (::std::string *type)
void set_c1 (double value)
void set_c2 (double value)
void set_c3 (double value)
void set_cutoff_angle (double value)
void set_env_texture_size (::google::protobuf::int32 value)
void set_f (double value)
void set_fun (const ::std::string &value)
void set_fun (const char *value)
void set_fun (const char *value, size_t size)
void set_hfov (double value)
void set_scale_to_hfov (bool value)
void set_type (const ::std::string &value)
void set_type (const char *value)
void set_type (const char *value, size_t size)
void Swap (CameraLens *other)
const ::std::string & type () const
Static Public Member Functions
static const CameraLens & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const CameraLens * internal_default_instance ()
Static Public Attributes
static const int kC1FieldNumber = 3
static const int kC2FieldNumber = 4
static const int kC3FieldNumber = 5
static const int kCutoffAngleFieldNumber = 9
static const int kEnvTextureSizeFieldNumber = 11
static const int kFFieldNumber = 6
static const int kFunFieldNumber = 7
static const int kHeaderFieldNumber = 1
static const int kHfovFieldNumber = 10
static constexpr int kIndexInFileMessages
static const int kScaleToHfovFieldNumber = 8
static const int kTypeFieldNumber = 2
Constructor & Destructor Documentation
CameraLens() [1/2]
CameraLens ()
~CameraLens()
virtual ~CameraLens () virtual
CameraLens() [2/2]
CameraLens (const CameraLens & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
c1()
double c1 () const inline
c2()
double c2 () const inline
c3()
double c3 () const inline
Clear()
void Clear () final
clear_c1()
void clear_c1 () inline
clear_c2()
void clear_c2 () inline
clear_c3()
void clear_c3 () inline
clear_cutoff_angle()
void clear_cutoff_angle () inline
clear_env_texture_size()
void clear_env_texture_size () inline
clear_f()
void clear_f () inline
clear_fun()
void clear_fun () inline
clear_header()
void clear_header ()
clear_hfov()
void clear_hfov () inline
clear_scale_to_hfov()
void clear_scale_to_hfov () inline
clear_type()
void clear_type () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const CameraLens & from)
cutoff_angle()
double cutoff_angle () const inline
default_instance()
static const CameraLens& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
env_texture_size()
google::protobuf::int32 env_texture_size () const inline
f()
double f () const inline
fun()
const ::std::string & fun () const inline
Referenced by CameraLens::set_allocated_fun().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References CameraLens::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by CameraLens::set_allocated_header().
hfov()
double hfov () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const CameraLens* internal_default_instance () inline static
References gz::msgs::_CameraLens_default_instance_.
Referenced by CameraLens::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const CameraLens & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_fun()
std::string * mutable_fun () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_type()
std::string * mutable_type () inline
New() [1/2]
CameraLens* New () const inline final
New() [2/2]
CameraLens* New (::google::protobuf::Arena * arena) const inline final
operator=()
CameraLens& operator= (const CameraLens & from) inline
release_fun()
std::string * release_fun () inline
release_header()
gz::msgs::Header * release_header () inline
release_type()
std::string * release_type () inline
scale_to_hfov()
bool scale_to_hfov () const inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_fun()
void set_allocated_fun (::std::string * fun) inline
References CameraLens::fun().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References CameraLens::header().
set_allocated_type()
void set_allocated_type (::std::string * type) inline
References CameraLens::type().
set_c1()
void set_c1 (double value) inline
set_c2()
void set_c2 (double value) inline
set_c3()
void set_c3 (double value) inline
set_cutoff_angle()
void set_cutoff_angle (double value) inline
set_env_texture_size()
void set_env_texture_size (::google::protobuf::int32 value) inline
set_f()
void set_f (double value) inline
set_fun() [1/3]
void set_fun (const ::std::string & value) inline
set_fun() [2/3]
void set_fun (const char * value) inline
set_fun() [3/3]
void set_fun (const char * value, size_t size) inline
set_hfov()
void set_hfov (double value) inline
set_scale_to_hfov()
void set_scale_to_hfov (bool value) inline
set_type() [1/3]
void set_type (const ::std::string & value) inline
set_type() [2/3]
void set_type (const char * value) inline
set_type() [3/3]
void set_type (const char * value, size_t size) inline
Swap()
void Swap (CameraLens * other)
type()
const ::std::string & type () const inline
Referenced by CameraLens::set_allocated_type().
Member Data Documentation
kC1FieldNumber
const int kC1FieldNumber = 3 static
kC2FieldNumber
const int kC2FieldNumber = 4 static
kC3FieldNumber
const int kC3FieldNumber = 5 static
kCutoffAngleFieldNumber
const int kCutoffAngleFieldNumber = 9 static
kEnvTextureSizeFieldNumber
const int kEnvTextureSizeFieldNumber = 11 static
kFFieldNumber
const int kFFieldNumber = 6 static
kFunFieldNumber
const int kFunFieldNumber = 7 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHfovFieldNumber
const int kHfovFieldNumber = 10 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kScaleToHfovFieldNumber
const int kScaleToHfovFieldNumber = 8 static
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
The documentation for this class was generated from the following file:
camera_lens.pb.h