Gazebo Msgs: Lens Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Lens Class Reference
#include <lens.pb.h>
Public Types
typedef Lens_FunctionType FunctionType
typedef Lens_Type Type
Public Member Functions
Lens ()
Lens (const Lens &from)
virtual ~Lens ()
size_t ByteSizeLong () const final
double c1 () const
double c2 () const
double c3 () const
void Clear () final
void clear_c1 ()
void clear_c2 ()
void clear_c3 ()
void clear_cutoff_angle ()
void clear_environment_texture_size ()
void clear_focal_length ()
void clear_function_type ()
void clear_intrinsics_cx ()
void clear_intrinsics_cy ()
void clear_intrinsics_fx ()
void clear_intrinsics_fy ()
void clear_intrinsics_skew ()
void clear_scale_to_hfov ()
void clear_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Lens &from)
double cutoff_angle () const
::google::protobuf::int32 environment_texture_size () const
double focal_length () const
::gz::msgs::Lens_FunctionType function_type () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
double intrinsics_cx () const
double intrinsics_cy () const
double intrinsics_fx () const
double intrinsics_fy () const
double intrinsics_skew () const
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Lens &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
Lens * New () const final
Lens * New (::google::protobuf::Arena *arena) const final
Lens & operator= (const Lens &from)
bool scale_to_hfov () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_c1 (double value)
void set_c2 (double value)
void set_c3 (double value)
void set_cutoff_angle (double value)
void set_environment_texture_size (::google::protobuf::int32 value)
void set_focal_length (double value)
void set_function_type (::gz::msgs::Lens_FunctionType value)
void set_intrinsics_cx (double value)
void set_intrinsics_cy (double value)
void set_intrinsics_fx (double value)
void set_intrinsics_fy (double value)
void set_intrinsics_skew (double value)
void set_scale_to_hfov (bool value)
void set_type (::gz::msgs::Lens_Type value)
void Swap (Lens *other)
::gz::msgs::Lens_Type type () const
Static Public Member Functions
static const Lens & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const ::google::protobuf::EnumDescriptor * FunctionType_descriptor ()
static bool FunctionType_IsValid (int value)
static const ::std::string & FunctionType_Name (FunctionType value)
static bool FunctionType_Parse (const ::std::string &name, FunctionType *value)
static void InitAsDefaultInstance ()
static const Lens * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type CUSTOM
static const Type EQUIDISTANT
static const Type EQUISOLID_ANGLE
static const FunctionType FUNCTION_NOT_SPECIFIED
static const int FunctionType_ARRAYSIZE
static const FunctionType FunctionType_MAX
static const FunctionType FunctionType_MIN
static const Type GNOMONICAL
static const FunctionType ID
static const int kC1FieldNumber = 3
static const int kC2FieldNumber = 4
static const int kC3FieldNumber = 5
static const int kCutoffAngleFieldNumber = 8
static const int kEnvironmentTextureSizeFieldNumber = 9
static const int kFocalLengthFieldNumber = 6
static const int kFunctionTypeFieldNumber = 7
static constexpr int kIndexInFileMessages
static const int kIntrinsicsCxFieldNumber = 12
static const int kIntrinsicsCyFieldNumber = 13
static const int kIntrinsicsFxFieldNumber = 10
static const int kIntrinsicsFyFieldNumber = 11
static const int kIntrinsicsSkewFieldNumber = 14
static const int kScaleToHfovFieldNumber = 2
static const int kTypeFieldNumber = 1
static const Type ORTHOGRAPHIC
static const FunctionType SIN
static const Type STEREOGRAPHIC
static const FunctionType TAN
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
static const Type TYPE_NOT_SPECIFIED
Member Typedef Documentation
FunctionType
typedef Lens_FunctionType FunctionType
Type
typedef Lens_Type Type
Constructor & Destructor Documentation
Lens() [1/2]
Lens ()
~Lens()
virtual ~Lens () virtual
Lens() [2/2]
Lens (const Lens & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
c1()
double c1 () const inline
c2()
double c2 () const inline
c3()
double c3 () const inline
Clear()
void Clear () final
clear_c1()
void clear_c1 () inline
clear_c2()
void clear_c2 () inline
clear_c3()
void clear_c3 () inline
clear_cutoff_angle()
void clear_cutoff_angle () inline
clear_environment_texture_size()
void clear_environment_texture_size () inline
clear_focal_length()
void clear_focal_length () inline
clear_function_type()
void clear_function_type () inline
clear_intrinsics_cx()
void clear_intrinsics_cx () inline
clear_intrinsics_cy()
void clear_intrinsics_cy () inline
clear_intrinsics_fx()
void clear_intrinsics_fx () inline
clear_intrinsics_fy()
void clear_intrinsics_fy () inline
clear_intrinsics_skew()
void clear_intrinsics_skew () inline
clear_scale_to_hfov()
void clear_scale_to_hfov () inline
clear_type()
void clear_type () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Lens & from)
cutoff_angle()
double cutoff_angle () const inline
default_instance()
static const Lens& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
environment_texture_size()
google::protobuf::int32 environment_texture_size () const inline
focal_length()
double focal_length () const inline
function_type()
gz::msgs::Lens_FunctionType function_type () const inline
FunctionType_descriptor()
static const ::google::protobuf::EnumDescriptor* FunctionType_descriptor () inline static
References gz::msgs::Lens_FunctionType_descriptor().
FunctionType_IsValid()
static bool FunctionType_IsValid (int value) inline static
References gz::msgs::Lens_FunctionType_IsValid().
FunctionType_Name()
static const ::std::string& FunctionType_Name (FunctionType value) inline static
References gz::msgs::Lens_FunctionType_Name().
FunctionType_Parse()
static bool FunctionType_Parse (const ::std::string & name, FunctionType * value) inline static
References gz::msgs::Lens_FunctionType_Parse().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Lens* internal_default_instance () inline static
References gz::msgs::_Lens_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
intrinsics_cx()
double intrinsics_cx () const inline
intrinsics_cy()
double intrinsics_cy () const inline
intrinsics_fx()
double intrinsics_fx () const inline
intrinsics_fy()
double intrinsics_fy () const inline
intrinsics_skew()
double intrinsics_skew () const inline
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Lens & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
New() [1/2]
Lens* New () const inline final
New() [2/2]
Lens* New (::google::protobuf::Arena * arena) const inline final
operator=()
Lens& operator= (const Lens & from) inline
scale_to_hfov()
bool scale_to_hfov () const inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_c1()
void set_c1 (double value) inline
set_c2()
void set_c2 (double value) inline
set_c3()
void set_c3 (double value) inline
set_cutoff_angle()
void set_cutoff_angle (double value) inline
set_environment_texture_size()
void set_environment_texture_size (::google::protobuf::int32 value) inline
set_focal_length()
void set_focal_length (double value) inline
set_function_type()
void set_function_type (::gz::msgs::Lens_FunctionType value) inline
set_intrinsics_cx()
void set_intrinsics_cx (double value) inline
set_intrinsics_cy()
void set_intrinsics_cy (double value) inline
set_intrinsics_fx()
void set_intrinsics_fx (double value) inline
set_intrinsics_fy()
void set_intrinsics_fy (double value) inline
set_intrinsics_skew()
void set_intrinsics_skew (double value) inline
set_scale_to_hfov()
void set_scale_to_hfov (bool value) inline
set_type()
void set_type (::gz::msgs::Lens_Type value) inline
Swap()
void Swap (Lens * other)
type()
gz::msgs::Lens_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References gz::msgs::Lens_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References gz::msgs::Lens_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References gz::msgs::Lens_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References gz::msgs::Lens_Type_Parse().
Member Data Documentation
CUSTOM
const Type CUSTOM static
Initial value:
=
    Lens_Type_CUSTOM
EQUIDISTANT
const Type EQUIDISTANT static
Initial value:
=
    Lens_Type_EQUIDISTANT
EQUISOLID_ANGLE
const Type EQUISOLID_ANGLE static
Initial value:
=
    Lens_Type_EQUISOLID_ANGLE
FUNCTION_NOT_SPECIFIED
const FunctionType FUNCTION_NOT_SPECIFIED static
Initial value:
=
    Lens_FunctionType_FUNCTION_NOT_SPECIFIED
FunctionType_ARRAYSIZE
const int FunctionType_ARRAYSIZE static
Initial value:
=
    Lens_FunctionType_FunctionType_ARRAYSIZE
FunctionType_MAX
const FunctionType FunctionType_MAX static
Initial value:
=
    Lens_FunctionType_FunctionType_MAX
FunctionType_MIN
const FunctionType FunctionType_MIN static
Initial value:
=
    Lens_FunctionType_FunctionType_MIN
GNOMONICAL
const Type GNOMONICAL static
Initial value:
=
    Lens_Type_GNOMONICAL
ID
const FunctionType ID static
Initial value:
=
    Lens_FunctionType_ID
kC1FieldNumber
const int kC1FieldNumber = 3 static
kC2FieldNumber
const int kC2FieldNumber = 4 static
kC3FieldNumber
const int kC3FieldNumber = 5 static
kCutoffAngleFieldNumber
const int kCutoffAngleFieldNumber = 8 static
kEnvironmentTextureSizeFieldNumber
const int kEnvironmentTextureSizeFieldNumber = 9 static
kFocalLengthFieldNumber
const int kFocalLengthFieldNumber = 6 static
kFunctionTypeFieldNumber
const int kFunctionTypeFieldNumber = 7 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kIntrinsicsCxFieldNumber
const int kIntrinsicsCxFieldNumber = 12 static
kIntrinsicsCyFieldNumber
const int kIntrinsicsCyFieldNumber = 13 static
kIntrinsicsFxFieldNumber
const int kIntrinsicsFxFieldNumber = 10 static
kIntrinsicsFyFieldNumber
const int kIntrinsicsFyFieldNumber = 11 static
kIntrinsicsSkewFieldNumber
const int kIntrinsicsSkewFieldNumber = 14 static
kScaleToHfovFieldNumber
const int kScaleToHfovFieldNumber = 2 static
kTypeFieldNumber
const int kTypeFieldNumber = 1 static
ORTHOGRAPHIC
const Type ORTHOGRAPHIC static
Initial value:
=
    Lens_Type_ORTHOGRAPHIC
SIN
const FunctionType SIN static
Initial value:
=
    Lens_FunctionType_SIN
STEREOGRAPHIC
const Type STEREOGRAPHIC static
Initial value:
=
    Lens_Type_STEREOGRAPHIC
TAN
const FunctionType TAN static
Initial value:
=
    Lens_FunctionType_TAN
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    Lens_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    Lens_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    Lens_Type_Type_MIN
TYPE_NOT_SPECIFIED
const Type TYPE_NOT_SPECIFIED static
Initial value:
=
    Lens_Type_TYPE_NOT_SPECIFIED
The documentation for this class was generated from the following file:
lens.pb.h