Gazebo Msgs: DataLoadPathOptions Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
DataLoadPathOptions Class Reference
#include <data_load_options.pb.h>
Public Types
typedef DataLoadPathOptions_DataAngularUnits DataAngularUnits
Public Member Functions
DataLoadPathOptions ()
DataLoadPathOptions (const DataLoadPathOptions &from)
virtual ~DataLoadPathOptions ()
size_t ByteSizeLong () const final
void Clear () final
void clear_coordinate_type ()
void clear_path ()
void clear_static_time ()
void clear_time ()
void clear_units ()
void clear_x ()
void clear_y ()
void clear_z ()
::gz::msgs::SphericalCoordinatesType coordinate_type () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const DataLoadPathOptions &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const DataLoadPathOptions &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_path ()
::std::string * mutable_time ()
::std::string * mutable_x ()
::std::string * mutable_y ()
::std::string * mutable_z ()
DataLoadPathOptions * New () const final
DataLoadPathOptions * New (::google::protobuf::Arena *arena) const final
DataLoadPathOptions & operator= (const DataLoadPathOptions &from)
const ::std::string & path () const
::std::string * release_path ()
::std::string * release_time ()
::std::string * release_x ()
::std::string * release_y ()
::std::string * release_z ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_path (::std::string *path)
void set_allocated_time (::std::string *time)
void set_allocated_x (::std::string *x)
void set_allocated_y (::std::string *y)
void set_allocated_z (::std::string *z)
void set_coordinate_type (::gz::msgs::SphericalCoordinatesType value)
void set_path (const ::std::string &value)
void set_path (const char *value)
void set_path (const char *value, size_t size)
void set_static_time (bool value)
void set_time (const ::std::string &value)
void set_time (const char *value)
void set_time (const char *value, size_t size)
void set_units (::gz::msgs::DataLoadPathOptions_DataAngularUnits value)
void set_x (const ::std::string &value)
void set_x (const char *value)
void set_x (const char *value, size_t size)
void set_y (const ::std::string &value)
void set_y (const char *value)
void set_y (const char *value, size_t size)
void set_z (const ::std::string &value)
void set_z (const char *value)
void set_z (const char *value, size_t size)
bool static_time () const
void Swap (DataLoadPathOptions *other)
const ::std::string & time () const
::gz::msgs::DataLoadPathOptions_DataAngularUnits units () const
const ::std::string & x () const
const ::std::string & y () const
const ::std::string & z () const
Static Public Member Functions
static const ::google::protobuf::EnumDescriptor * DataAngularUnits_descriptor ()
static bool DataAngularUnits_IsValid (int value)
static const ::std::string & DataAngularUnits_Name (DataAngularUnits value)
static bool DataAngularUnits_Parse (const ::std::string &name, DataAngularUnits *value)
static const DataLoadPathOptions & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const DataLoadPathOptions * internal_default_instance ()
Static Public Attributes
static const int DataAngularUnits_ARRAYSIZE
static const DataAngularUnits DataAngularUnits_MAX
static const DataAngularUnits DataAngularUnits_MIN
static const DataAngularUnits DEGREES
static const int kCoordinateTypeFieldNumber = 8
static constexpr int kIndexInFileMessages
static const int kPathFieldNumber = 1
static const int kStaticTimeFieldNumber = 3
static const int kTimeFieldNumber = 2
static const int kUnitsFieldNumber = 7
static const int kXFieldNumber = 4
static const int kYFieldNumber = 5
static const int kZFieldNumber = 6
static const DataAngularUnits RADIANS
Member Typedef Documentation
DataAngularUnits
typedef DataLoadPathOptions_DataAngularUnits DataAngularUnits
Constructor & Destructor Documentation
DataLoadPathOptions() [1/2]
DataLoadPathOptions ()
~DataLoadPathOptions()
virtual ~DataLoadPathOptions () virtual
DataLoadPathOptions() [2/2]
DataLoadPathOptions (const DataLoadPathOptions & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_coordinate_type()
void clear_coordinate_type () inline
clear_path()
void clear_path () inline
clear_static_time()
void clear_static_time () inline
clear_time()
void clear_time () inline
clear_units()
void clear_units () inline
clear_x()
void clear_x () inline
clear_y()
void clear_y () inline
clear_z()
void clear_z () inline
coordinate_type()
gz::msgs::SphericalCoordinatesType coordinate_type () const inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const DataLoadPathOptions & from)
DataAngularUnits_descriptor()
static const ::google::protobuf::EnumDescriptor* DataAngularUnits_descriptor () inline static
References gz::msgs::DataLoadPathOptions_DataAngularUnits_descriptor().
DataAngularUnits_IsValid()
static bool DataAngularUnits_IsValid (int value) inline static
References gz::msgs::DataLoadPathOptions_DataAngularUnits_IsValid().
DataAngularUnits_Name()
static const ::std::string& DataAngularUnits_Name (DataAngularUnits value) inline static
References gz::msgs::DataLoadPathOptions_DataAngularUnits_Name().
DataAngularUnits_Parse()
static bool DataAngularUnits_Parse (const ::std::string & name, DataAngularUnits * value) inline static
References gz::msgs::DataLoadPathOptions_DataAngularUnits_Parse().
default_instance()
static const DataLoadPathOptions& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const DataLoadPathOptions* internal_default_instance () inline static
References gz::msgs::_DataLoadPathOptions_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const DataLoadPathOptions & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_path()
std::string * mutable_path () inline
mutable_time()
std::string * mutable_time () inline
mutable_x()
std::string * mutable_x () inline
mutable_y()
std::string * mutable_y () inline
mutable_z()
std::string * mutable_z () inline
New() [1/2]
DataLoadPathOptions* New () const inline final
New() [2/2]
DataLoadPathOptions* New (::google::protobuf::Arena * arena) const inline final
operator=()
DataLoadPathOptions& operator= (const DataLoadPathOptions & from) inline
path()
const ::std::string & path () const inline
Referenced by DataLoadPathOptions::set_allocated_path().
release_path()
std::string * release_path () inline
release_time()
std::string * release_time () inline
release_x()
std::string * release_x () inline
release_y()
std::string * release_y () inline
release_z()
std::string * release_z () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_path()
void set_allocated_path (::std::string * path) inline
References DataLoadPathOptions::path().
set_allocated_time()
void set_allocated_time (::std::string * time) inline
References DataLoadPathOptions::time().
set_allocated_x()
void set_allocated_x (::std::string * x) inline
References DataLoadPathOptions::x().
set_allocated_y()
void set_allocated_y (::std::string * y) inline
References DataLoadPathOptions::y().
set_allocated_z()
void set_allocated_z (::std::string * z) inline
References DataLoadPathOptions::z().
set_coordinate_type()
void set_coordinate_type (::gz::msgs::SphericalCoordinatesType value) inline
set_path() [1/3]
void set_path (const ::std::string & value) inline
set_path() [2/3]
void set_path (const char * value) inline
set_path() [3/3]
void set_path (const char * value, size_t size) inline
set_static_time()
void set_static_time (bool value) inline
set_time() [1/3]
void set_time (const ::std::string & value) inline
set_time() [2/3]
void set_time (const char * value) inline
set_time() [3/3]
void set_time (const char * value, size_t size) inline
set_units()
void set_units (::gz::msgs::DataLoadPathOptions_DataAngularUnits value) inline
set_x() [1/3]
void set_x (const ::std::string & value) inline
set_x() [2/3]
void set_x (const char * value) inline
set_x() [3/3]
void set_x (const char * value, size_t size) inline
set_y() [1/3]
void set_y (const ::std::string & value) inline
set_y() [2/3]
void set_y (const char * value) inline
set_y() [3/3]
void set_y (const char * value, size_t size) inline
set_z() [1/3]
void set_z (const ::std::string & value) inline
set_z() [2/3]
void set_z (const char * value) inline
set_z() [3/3]
void set_z (const char * value, size_t size) inline
static_time()
bool static_time () const inline
Swap()
void Swap (DataLoadPathOptions * other)
time()
const ::std::string & time () const inline
Referenced by DataLoadPathOptions::set_allocated_time().
units()
gz::msgs::DataLoadPathOptions_DataAngularUnits units () const inline
x()
const ::std::string & x () const inline
Referenced by DataLoadPathOptions::set_allocated_x().
y()
const ::std::string & y () const inline
Referenced by DataLoadPathOptions::set_allocated_y().
z()
const ::std::string & z () const inline
Referenced by DataLoadPathOptions::set_allocated_z().
Member Data Documentation
DataAngularUnits_ARRAYSIZE
const int DataAngularUnits_ARRAYSIZE static
Initial value:
=
    DataLoadPathOptions_DataAngularUnits_DataAngularUnits_ARRAYSIZE
DataAngularUnits_MAX
const DataAngularUnits DataAngularUnits_MAX static
Initial value:
=
    DataLoadPathOptions_DataAngularUnits_DataAngularUnits_MAX
DataAngularUnits_MIN
const DataAngularUnits DataAngularUnits_MIN static
Initial value:
=
    DataLoadPathOptions_DataAngularUnits_DataAngularUnits_MIN
DEGREES
const DataAngularUnits DEGREES static
Initial value:
=
    DataLoadPathOptions_DataAngularUnits_DEGREES
kCoordinateTypeFieldNumber
const int kCoordinateTypeFieldNumber = 8 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kPathFieldNumber
const int kPathFieldNumber = 1 static
kStaticTimeFieldNumber
const int kStaticTimeFieldNumber = 3 static
kTimeFieldNumber
const int kTimeFieldNumber = 2 static
kUnitsFieldNumber
const int kUnitsFieldNumber = 7 static
kXFieldNumber
const int kXFieldNumber = 4 static
kYFieldNumber
const int kYFieldNumber = 5 static
kZFieldNumber
const int kZFieldNumber = 6 static
RADIANS
const DataAngularUnits RADIANS static
Initial value:
=
    DataLoadPathOptions_DataAngularUnits_RADIANS
The documentation for this class was generated from the following file:
data_load_options.pb.h