Gazebo Msgs: Sonar Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Sonar Class Reference
#include <sonar.pb.h>
Public Member Functions
Sonar ()
Sonar (const Sonar &from)
virtual ~Sonar ()
size_t ByteSizeLong () const final
void Clear () final
void clear_contact ()
void clear_frame ()
void clear_geometry ()
void clear_header ()
void clear_radius ()
void clear_range ()
void clear_range_max ()
void clear_range_min ()
void clear_world_pose ()
const ::gz::msgs::Vector3d & contact () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Sonar &from)
const ::std::string & frame () const
const ::std::string & geometry () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_contact () const
bool has_header () const
bool has_world_pose () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Sonar &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Vector3d * mutable_contact ()
::std::string * mutable_frame ()
::std::string * mutable_geometry ()
::gz::msgs::Header * mutable_header ()
::gz::msgs::Pose * mutable_world_pose ()
Sonar * New () const final
Sonar * New (::google::protobuf::Arena *arena) const final
Sonar & operator= (const Sonar &from)
double radius () const
double range () const
double range_max () const
double range_min () const
::gz::msgs::Vector3d * release_contact ()
::std::string * release_frame ()
::std::string * release_geometry ()
::gz::msgs::Header * release_header ()
::gz::msgs::Pose * release_world_pose ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_contact (::gz::msgs::Vector3d *contact)
void set_allocated_frame (::std::string *frame)
void set_allocated_geometry (::std::string *geometry)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_world_pose (::gz::msgs::Pose *world_pose)
void set_frame (const ::std::string &value)
void set_frame (const char *value)
void set_frame (const char *value, size_t size)
void set_geometry (const ::std::string &value)
void set_geometry (const char *value)
void set_geometry (const char *value, size_t size)
void set_radius (double value)
void set_range (double value)
void set_range_max (double value)
void set_range_min (double value)
void Swap (Sonar *other)
const ::gz::msgs::Pose & world_pose () const
Static Public Member Functions
static const Sonar & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Sonar * internal_default_instance ()
Static Public Attributes
static const int kContactFieldNumber = 9
static const int kFrameFieldNumber = 2
static const int kGeometryFieldNumber = 8
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kRadiusFieldNumber = 6
static const int kRangeFieldNumber = 7
static const int kRangeMaxFieldNumber = 5
static const int kRangeMinFieldNumber = 4
static const int kWorldPoseFieldNumber = 3
Constructor & Destructor Documentation
Sonar() [1/2]
Sonar ()
~Sonar()
virtual ~Sonar () virtual
Sonar() [2/2]
Sonar (const Sonar & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_contact()
void clear_contact ()
clear_frame()
void clear_frame () inline
clear_geometry()
void clear_geometry () inline
clear_header()
void clear_header ()
clear_radius()
void clear_radius () inline
clear_range()
void clear_range () inline
clear_range_max()
void clear_range_max () inline
clear_range_min()
void clear_range_min () inline
clear_world_pose()
void clear_world_pose ()
contact()
const ::gz::msgs::Vector3d & contact () const inline
References gz::msgs::_Vector3d_default_instance_.
Referenced by Sonar::set_allocated_contact().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Sonar & from)
default_instance()
static const Sonar& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
frame()
const ::std::string & frame () const inline
Referenced by Sonar::set_allocated_frame().
geometry()
const ::std::string & geometry () const inline
Referenced by Sonar::set_allocated_geometry().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_contact()
bool has_contact () const inline
References Sonar::internal_default_instance().
has_header()
bool has_header () const inline
References Sonar::internal_default_instance().
has_world_pose()
bool has_world_pose () const inline
References Sonar::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by Sonar::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Sonar* internal_default_instance () inline static
References gz::msgs::_Sonar_default_instance_.
Referenced by Sonar::has_contact(), Sonar::has_header(), and Sonar::has_world_pose().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Sonar & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_contact()
gz::msgs::Vector3d * mutable_contact () inline
mutable_frame()
std::string * mutable_frame () inline
mutable_geometry()
std::string * mutable_geometry () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_world_pose()
gz::msgs::Pose * mutable_world_pose () inline
New() [1/2]
Sonar* New () const inline final
New() [2/2]
Sonar* New (::google::protobuf::Arena * arena) const inline final
operator=()
Sonar& operator= (const Sonar & from) inline
radius()
double radius () const inline
range()
double range () const inline
range_max()
double range_max () const inline
range_min()
double range_min () const inline
release_contact()
gz::msgs::Vector3d * release_contact () inline
release_frame()
std::string * release_frame () inline
release_geometry()
std::string * release_geometry () inline
release_header()
gz::msgs::Header * release_header () inline
release_world_pose()
gz::msgs::Pose * release_world_pose () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_contact()
void set_allocated_contact (::gz::msgs::Vector3d * contact) inline
References Sonar::contact().
set_allocated_frame()
void set_allocated_frame (::std::string * frame) inline
References Sonar::frame().
set_allocated_geometry()
void set_allocated_geometry (::std::string * geometry) inline
References Sonar::geometry().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References Sonar::header().
set_allocated_world_pose()
void set_allocated_world_pose (::gz::msgs::Pose * world_pose) inline
References Sonar::world_pose().
set_frame() [1/3]
void set_frame (const ::std::string & value) inline
set_frame() [2/3]
void set_frame (const char * value) inline
set_frame() [3/3]
void set_frame (const char * value, size_t size) inline
set_geometry() [1/3]
void set_geometry (const ::std::string & value) inline
set_geometry() [2/3]
void set_geometry (const char * value) inline
set_geometry() [3/3]
void set_geometry (const char * value, size_t size) inline
set_radius()
void set_radius (double value) inline
set_range()
void set_range (double value) inline
set_range_max()
void set_range_max (double value) inline
set_range_min()
void set_range_min (double value) inline
Swap()
void Swap (Sonar * other)
world_pose()
const ::gz::msgs::Pose & world_pose () const inline
References gz::msgs::_Pose_default_instance_.
Referenced by Sonar::set_allocated_world_pose().
Member Data Documentation
kContactFieldNumber
const int kContactFieldNumber = 9 static
kFrameFieldNumber
const int kFrameFieldNumber = 2 static
kGeometryFieldNumber
const int kGeometryFieldNumber = 8 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kRadiusFieldNumber
const int kRadiusFieldNumber = 6 static
kRangeFieldNumber
const int kRangeFieldNumber = 7 static
kRangeMaxFieldNumber
const int kRangeMaxFieldNumber = 5 static
kRangeMinFieldNumber
const int kRangeMinFieldNumber = 4 static
kWorldPoseFieldNumber
const int kWorldPoseFieldNumber = 3 static
The documentation for this class was generated from the following file:
sonar.pb.h