Gazebo Msgs: FuelMetadata_Compatibility Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
FuelMetadata_Compatibility Class Reference
#include <fuel_metadata.pb.h>
Public Types
enum VersionTypeCase { kVersion = 2, kVersionRange = 3, VERSION_TYPE_NOT_SET = 0 }
Public Member Functions
FuelMetadata_Compatibility ()
FuelMetadata_Compatibility (const FuelMetadata_Compatibility &from)
virtual ~FuelMetadata_Compatibility ()
size_t ByteSizeLong () const final
void Clear () final
void clear_name ()
void clear_version ()
void clear_version_range ()
void clear_version_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const FuelMetadata_Compatibility &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_version () const
bool has_version_range () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const FuelMetadata_Compatibility &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_name ()
::gz::msgs::Version * mutable_version ()
::gz::msgs::VersionRange * mutable_version_range ()
const ::std::string & name () const
FuelMetadata_Compatibility * New () const final
FuelMetadata_Compatibility * New (::google::protobuf::Arena *arena) const final
FuelMetadata_Compatibility & operator= (const FuelMetadata_Compatibility &from)
::std::string * release_name ()
::gz::msgs::Version * release_version ()
::gz::msgs::VersionRange * release_version_range ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_name (::std::string *name)
void set_allocated_version (::gz::msgs::Version *version)
void set_allocated_version_range (::gz::msgs::VersionRange *version_range)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void Swap (FuelMetadata_Compatibility *other)
const ::gz::msgs::Version & version () const
const ::gz::msgs::VersionRange & version_range () const
VersionTypeCase version_type_case () const
Static Public Member Functions
static const FuelMetadata_Compatibility & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const FuelMetadata_Compatibility * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 1
static const int kVersionFieldNumber = 2
static const int kVersionRangeFieldNumber = 3
Member Enumeration Documentation
VersionTypeCase
enum VersionTypeCase
Enumerator
kVersion
kVersionRange
VERSION_TYPE_NOT_SET
Constructor & Destructor Documentation
FuelMetadata_Compatibility() [1/2]
FuelMetadata_Compatibility ()
~FuelMetadata_Compatibility()
virtual ~FuelMetadata_Compatibility () virtual
FuelMetadata_Compatibility() [2/2]
FuelMetadata_Compatibility (const FuelMetadata_Compatibility & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_name()
void clear_name () inline
clear_version()
void clear_version ()
clear_version_range()
void clear_version_range ()
clear_version_type()
void clear_version_type ()
Referenced by FuelMetadata_Compatibility::mutable_version(), and FuelMetadata_Compatibility::mutable_version_range().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const FuelMetadata_Compatibility & from)
default_instance()
static const FuelMetadata_Compatibility& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_version()
bool has_version () const inline
References FuelMetadata_Compatibility::kVersion, and FuelMetadata_Compatibility::version_type_case().
Referenced by FuelMetadata_Compatibility::mutable_version(), FuelMetadata_Compatibility::release_version(), and FuelMetadata_Compatibility::version().
has_version_range()
bool has_version_range () const inline
References FuelMetadata_Compatibility::kVersionRange, and FuelMetadata_Compatibility::version_type_case().
Referenced by FuelMetadata_Compatibility::mutable_version_range(), FuelMetadata_Compatibility::release_version_range(), and FuelMetadata_Compatibility::version_range().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const FuelMetadata_Compatibility* internal_default_instance () inline static
References gz::msgs::_FuelMetadata_Compatibility_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const FuelMetadata_Compatibility & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_name()
std::string * mutable_name () inline
mutable_version()
gz::msgs::Version * mutable_version () inline
References FuelMetadata_Compatibility::clear_version_type(), and FuelMetadata_Compatibility::has_version().
mutable_version_range()
gz::msgs::VersionRange * mutable_version_range () inline
References FuelMetadata_Compatibility::clear_version_type(), and FuelMetadata_Compatibility::has_version_range().
name()
const ::std::string & name () const inline
Referenced by FuelMetadata_Compatibility::set_allocated_name().
New() [1/2]
FuelMetadata_Compatibility* New () const inline final
New() [2/2]
FuelMetadata_Compatibility* New (::google::protobuf::Arena * arena) const inline final
operator=()
FuelMetadata_Compatibility& operator= (const FuelMetadata_Compatibility & from) inline
release_name()
std::string * release_name () inline
release_version()
gz::msgs::Version * release_version () inline
References FuelMetadata_Compatibility::has_version().
release_version_range()
gz::msgs::VersionRange * release_version_range () inline
References FuelMetadata_Compatibility::has_version_range().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References FuelMetadata_Compatibility::name().
set_allocated_version()
void set_allocated_version (::gz::msgs::Version * version)
set_allocated_version_range()
void set_allocated_version_range (::gz::msgs::VersionRange * version_range)
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
Swap()
void Swap (FuelMetadata_Compatibility * other)
version()
const ::gz::msgs::Version & version () const inline
References gz::msgs::_Version_default_instance_, and FuelMetadata_Compatibility::has_version().
version_range()
const ::gz::msgs::VersionRange & version_range () const inline
References gz::msgs::_VersionRange_default_instance_, and FuelMetadata_Compatibility::has_version_range().
version_type_case()
FuelMetadata_Compatibility::VersionTypeCase version_type_case () const inline
Referenced by FuelMetadata_Compatibility::has_version(), and FuelMetadata_Compatibility::has_version_range().
Member Data Documentation
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    5
kNameFieldNumber
const int kNameFieldNumber = 1 static
kVersionFieldNumber
const int kVersionFieldNumber = 2 static
kVersionRangeFieldNumber
const int kVersionRangeFieldNumber = 3 static
The documentation for this class was generated from the following file:
fuel_metadata.pb.h