Gazebo Msgs: Request Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Request Class Reference
#include <request.pb.h>
Public Member Functions
Request ()
Request (const Request &from)
virtual ~Request ()
size_t ByteSizeLong () const final
void Clear () final
void clear_data ()
void clear_dbl_data ()
void clear_header ()
void clear_id ()
void clear_request ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Request &from)
const ::std::string & data () const
double dbl_data () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::int32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Request &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_data ()
::gz::msgs::Header * mutable_header ()
::std::string * mutable_request ()
Request * New () const final
Request * New (::google::protobuf::Arena *arena) const final
Request & operator= (const Request &from)
::std::string * release_data ()
::gz::msgs::Header * release_header ()
::std::string * release_request ()
const ::std::string & request () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_data (::std::string *data)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_request (::std::string *request)
void set_data (const ::std::string &value)
void set_data (const char *value)
void set_data (const char *value, size_t size)
void set_dbl_data (double value)
void set_id (::google::protobuf::int32 value)
void set_request (const ::std::string &value)
void set_request (const char *value)
void set_request (const char *value, size_t size)
void Swap (Request *other)
Static Public Member Functions
static const Request & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Request * internal_default_instance ()
Static Public Attributes
static const int kDataFieldNumber = 4
static const int kDblDataFieldNumber = 5
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kRequestFieldNumber = 3
Constructor & Destructor Documentation
Request() [1/2]
Request ()
~Request()
virtual ~Request () virtual
Request() [2/2]
Request (const Request & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_data()
void clear_data () inline
clear_dbl_data()
void clear_dbl_data () inline
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_request()
void clear_request () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Request & from)
data()
const ::std::string & data () const inline
Referenced by Request::set_allocated_data().
dbl_data()
double dbl_data () const inline
default_instance()
static const Request& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Request::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by Request::set_allocated_header().
id()
google::protobuf::int32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Request* internal_default_instance () inline static
References gz::msgs::_Request_default_instance_.
Referenced by Request::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Request & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_data()
std::string * mutable_data () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_request()
std::string * mutable_request () inline
New() [1/2]
Request* New () const inline final
New() [2/2]
Request* New (::google::protobuf::Arena * arena) const inline final
operator=()
Request& operator= (const Request & from) inline
release_data()
std::string * release_data () inline
release_header()
gz::msgs::Header * release_header () inline
release_request()
std::string * release_request () inline
request()
const ::std::string & request () const inline
Referenced by Request::set_allocated_request().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_data()
void set_allocated_data (::std::string * data) inline
References Request::data().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References Request::header().
set_allocated_request()
void set_allocated_request (::std::string * request) inline
References Request::request().
set_data() [1/3]
void set_data (const ::std::string & value) inline
set_data() [2/3]
void set_data (const char * value) inline
set_data() [3/3]
void set_data (const char * value, size_t size) inline
set_dbl_data()
void set_dbl_data (double value) inline
set_id()
void set_id (::google::protobuf::int32 value) inline
set_request() [1/3]
void set_request (const ::std::string & value) inline
set_request() [2/3]
void set_request (const char * value) inline
set_request() [3/3]
void set_request (const char * value, size_t size) inline
Swap()
void Swap (Request * other)
Member Data Documentation
kDataFieldNumber
const int kDataFieldNumber = 4 static
kDblDataFieldNumber
const int kDblDataFieldNumber = 5 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kRequestFieldNumber
const int kRequestFieldNumber = 3 static
The documentation for this class was generated from the following file:
request.pb.h