Gazebo Msgs: DVLVelocityTracking Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
DVLVelocityTracking Class Reference
#include <dvl_velocity_tracking.pb.h>
Public Types
typedef DVLVelocityTracking_DVLType DVLType
Public Member Functions
DVLVelocityTracking ()
DVLVelocityTracking (const DVLVelocityTracking &from)
virtual ~DVLVelocityTracking ()
::gz::msgs::DVLBeamState * add_beams ()
const ::google::protobuf::RepeatedPtrField< ::gz::msgs::DVLBeamState > & beams () const
const ::gz::msgs::DVLBeamState & beams (int index) const
int beams_size () const
size_t ByteSizeLong () const final
void Clear () final
void clear_beams ()
void clear_header ()
void clear_status ()
void clear_target ()
void clear_type ()
void clear_velocity ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const DVLVelocityTracking &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_target () const
bool has_velocity () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const DVLVelocityTracking &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::google::protobuf::RepeatedPtrField< ::gz::msgs::DVLBeamState > * mutable_beams ()
::gz::msgs::DVLBeamState * mutable_beams (int index)
::gz::msgs::Header * mutable_header ()
::gz::msgs::DVLTrackingTarget * mutable_target ()
::gz::msgs::DVLKinematicEstimate * mutable_velocity ()
DVLVelocityTracking * New () const final
DVLVelocityTracking * New (::google::protobuf::Arena *arena) const final
DVLVelocityTracking & operator= (const DVLVelocityTracking &from)
::gz::msgs::Header * release_header ()
::gz::msgs::DVLTrackingTarget * release_target ()
::gz::msgs::DVLKinematicEstimate * release_velocity ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_target (::gz::msgs::DVLTrackingTarget *target)
void set_allocated_velocity (::gz::msgs::DVLKinematicEstimate *velocity)
void set_status (::google::protobuf::int32 value)
void set_type (::gz::msgs::DVLVelocityTracking_DVLType value)
::google::protobuf::int32 status () const
void Swap (DVLVelocityTracking *other)
const ::gz::msgs::DVLTrackingTarget & target () const
::gz::msgs::DVLVelocityTracking_DVLType type () const
const ::gz::msgs::DVLKinematicEstimate & velocity () const
Static Public Member Functions
static const DVLVelocityTracking & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const ::google::protobuf::EnumDescriptor * DVLType_descriptor ()
static bool DVLType_IsValid (int value)
static const ::std::string & DVLType_Name (DVLType value)
static bool DVLType_Parse (const ::std::string &name, DVLType *value)
static void InitAsDefaultInstance ()
static const DVLVelocityTracking * internal_default_instance ()
Static Public Attributes
static const DVLType DVL_TYPE_PHASED_ARRAY
static const DVLType DVL_TYPE_PISTON
static const DVLType DVL_TYPE_UNSPECIFIED
static const int DVLType_ARRAYSIZE
static const DVLType DVLType_MAX
static const DVLType DVLType_MIN
static const int kBeamsFieldNumber = 5
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kStatusFieldNumber = 6
static const int kTargetFieldNumber = 3
static const int kTypeFieldNumber = 2
static const int kVelocityFieldNumber = 4
Member Typedef Documentation
DVLType
typedef DVLVelocityTracking_DVLType DVLType
Constructor & Destructor Documentation
DVLVelocityTracking() [1/2]
DVLVelocityTracking ()
~DVLVelocityTracking()
virtual ~DVLVelocityTracking () virtual
DVLVelocityTracking() [2/2]
DVLVelocityTracking (const DVLVelocityTracking & from)
Member Function Documentation
add_beams()
gz::msgs::DVLBeamState * add_beams () inline
beams() [1/2]
const ::google::protobuf::RepeatedPtrField<::gz::msgs::DVLBeamState > & beams () const inline
beams() [2/2]
const ::gz::msgs::DVLBeamState & beams (int index) const inline
beams_size()
int beams_size () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_beams()
void clear_beams ()
clear_header()
void clear_header ()
clear_status()
void clear_status () inline
clear_target()
void clear_target ()
clear_type()
void clear_type () inline
clear_velocity()
void clear_velocity ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const DVLVelocityTracking & from)
default_instance()
static const DVLVelocityTracking& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
DVLType_descriptor()
static const ::google::protobuf::EnumDescriptor* DVLType_descriptor () inline static
References gz::msgs::DVLVelocityTracking_DVLType_descriptor().
DVLType_IsValid()
static bool DVLType_IsValid (int value) inline static
References gz::msgs::DVLVelocityTracking_DVLType_IsValid().
DVLType_Name()
static const ::std::string& DVLType_Name (DVLType value) inline static
References gz::msgs::DVLVelocityTracking_DVLType_Name().
DVLType_Parse()
static bool DVLType_Parse (const ::std::string & name, DVLType * value) inline static
References gz::msgs::DVLVelocityTracking_DVLType_Parse().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References DVLVelocityTracking::internal_default_instance().
has_target()
bool has_target () const inline
References DVLVelocityTracking::internal_default_instance().
has_velocity()
bool has_velocity () const inline
References DVLVelocityTracking::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by DVLVelocityTracking::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const DVLVelocityTracking* internal_default_instance () inline static
References gz::msgs::_DVLVelocityTracking_default_instance_.
Referenced by DVLVelocityTracking::has_header(), DVLVelocityTracking::has_target(), and DVLVelocityTracking::has_velocity().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const DVLVelocityTracking & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_beams() [1/2]
google::protobuf::RepeatedPtrField<::gz::msgs::DVLBeamState > * mutable_beams () inline
mutable_beams() [2/2]
gz::msgs::DVLBeamState * mutable_beams (int index) inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_target()
gz::msgs::DVLTrackingTarget * mutable_target () inline
mutable_velocity()
gz::msgs::DVLKinematicEstimate * mutable_velocity () inline
New() [1/2]
DVLVelocityTracking* New () const inline final
New() [2/2]
DVLVelocityTracking* New (::google::protobuf::Arena * arena) const inline final
operator=()
DVLVelocityTracking& operator= (const DVLVelocityTracking & from) inline
release_header()
gz::msgs::Header * release_header () inline
release_target()
gz::msgs::DVLTrackingTarget * release_target () inline
release_velocity()
gz::msgs::DVLKinematicEstimate * release_velocity () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References DVLVelocityTracking::header().
set_allocated_target()
void set_allocated_target (::gz::msgs::DVLTrackingTarget * target) inline
References DVLVelocityTracking::target().
set_allocated_velocity()
void set_allocated_velocity (::gz::msgs::DVLKinematicEstimate * velocity) inline
References DVLVelocityTracking::velocity().
set_status()
void set_status (::google::protobuf::int32 value) inline
set_type()
void set_type (::gz::msgs::DVLVelocityTracking_DVLType value) inline
status()
google::protobuf::int32 status () const inline
Swap()
void Swap (DVLVelocityTracking * other)
target()
const ::gz::msgs::DVLTrackingTarget & target () const inline
References gz::msgs::_DVLTrackingTarget_default_instance_.
Referenced by DVLVelocityTracking::set_allocated_target().
type()
gz::msgs::DVLVelocityTracking_DVLType type () const inline
velocity()
const ::gz::msgs::DVLKinematicEstimate & velocity () const inline
References gz::msgs::_DVLKinematicEstimate_default_instance_.
Referenced by DVLVelocityTracking::set_allocated_velocity().
Member Data Documentation
DVL_TYPE_PHASED_ARRAY
const DVLType DVL_TYPE_PHASED_ARRAY static
Initial value:
=
    DVLVelocityTracking_DVLType_DVL_TYPE_PHASED_ARRAY
DVL_TYPE_PISTON
const DVLType DVL_TYPE_PISTON static
Initial value:
=
    DVLVelocityTracking_DVLType_DVL_TYPE_PISTON
DVL_TYPE_UNSPECIFIED
const DVLType DVL_TYPE_UNSPECIFIED static
Initial value:
=
    DVLVelocityTracking_DVLType_DVL_TYPE_UNSPECIFIED
DVLType_ARRAYSIZE
const int DVLType_ARRAYSIZE static
Initial value:
=
    DVLVelocityTracking_DVLType_DVLType_ARRAYSIZE
DVLType_MAX
const DVLType DVLType_MAX static
Initial value:
=
    DVLVelocityTracking_DVLType_DVLType_MAX
DVLType_MIN
const DVLType DVLType_MIN static
Initial value:
=
    DVLVelocityTracking_DVLType_DVLType_MIN
kBeamsFieldNumber
const int kBeamsFieldNumber = 5 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kStatusFieldNumber
const int kStatusFieldNumber = 6 static
kTargetFieldNumber
const int kTargetFieldNumber = 3 static
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
kVelocityFieldNumber
const int kVelocityFieldNumber = 4 static
The documentation for this class was generated from the following file:
dvl_velocity_tracking.pb.h