Gazebo Msgs: CameraCmd Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
CameraCmd Class Reference
#include <camera_cmd.pb.h>
Public Member Functions
CameraCmd ()
CameraCmd (const CameraCmd &from)
virtual ~CameraCmd ()
size_t ByteSizeLong () const final
void Clear () final
void clear_follow_model ()
void clear_header ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const CameraCmd &from)
const ::std::string & follow_model () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const CameraCmd &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_follow_model ()
::gz::msgs::Header * mutable_header ()
CameraCmd * New () const final
CameraCmd * New (::google::protobuf::Arena *arena) const final
CameraCmd & operator= (const CameraCmd &from)
::std::string * release_follow_model ()
::gz::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_follow_model (::std::string *follow_model)
void set_allocated_header (::gz::msgs::Header *header)
void set_follow_model (const ::std::string &value)
void set_follow_model (const char *value)
void set_follow_model (const char *value, size_t size)
void Swap (CameraCmd *other)
Static Public Member Functions
static const CameraCmd & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const CameraCmd * internal_default_instance ()
Static Public Attributes
static const int kFollowModelFieldNumber = 2
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
Constructor & Destructor Documentation
CameraCmd() [1/2]
CameraCmd ()
~CameraCmd()
virtual ~CameraCmd () virtual
CameraCmd() [2/2]
CameraCmd (const CameraCmd & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_follow_model()
void clear_follow_model () inline
clear_header()
void clear_header ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const CameraCmd & from)
default_instance()
static const CameraCmd& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
follow_model()
const ::std::string & follow_model () const inline
Referenced by CameraCmd::set_allocated_follow_model().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References CameraCmd::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by CameraCmd::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const CameraCmd* internal_default_instance () inline static
References gz::msgs::_CameraCmd_default_instance_.
Referenced by CameraCmd::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const CameraCmd & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_follow_model()
std::string * mutable_follow_model () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
New() [1/2]
CameraCmd* New () const inline final
New() [2/2]
CameraCmd* New (::google::protobuf::Arena * arena) const inline final
operator=()
CameraCmd& operator= (const CameraCmd & from) inline
release_follow_model()
std::string * release_follow_model () inline
release_header()
gz::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_follow_model()
void set_allocated_follow_model (::std::string * follow_model) inline
References CameraCmd::follow_model().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References CameraCmd::header().
set_follow_model() [1/3]
void set_follow_model (const ::std::string & value) inline
set_follow_model() [2/3]
void set_follow_model (const char * value) inline
set_follow_model() [3/3]
void set_follow_model (const char * value, size_t size) inline
Swap()
void Swap (CameraCmd * other)
Member Data Documentation
kFollowModelFieldNumber
const int kFollowModelFieldNumber = 2 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
The documentation for this class was generated from the following file:
camera_cmd.pb.h