Gazebo Msgs: WebRequest Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
WebRequest Class Reference
#include <web_request.pb.h>
Public Member Functions
WebRequest ()
WebRequest (const WebRequest &from)
virtual ~WebRequest ()
size_t ByteSizeLong () const final
void Clear () final
void clear_compression ()
void clear_header ()
void clear_hz ()
void clear_msg_type ()
void clear_operation ()
void clear_topic ()
const ::std::string & compression () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const WebRequest &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
double hz () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const WebRequest &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::std::string & msg_type () const
::std::string * mutable_compression ()
::gz::msgs::Header * mutable_header ()
::std::string * mutable_msg_type ()
::std::string * mutable_operation ()
::std::string * mutable_topic ()
WebRequest * New () const final
WebRequest * New (::google::protobuf::Arena *arena) const final
const ::std::string & operation () const
WebRequest & operator= (const WebRequest &from)
::std::string * release_compression ()
::gz::msgs::Header * release_header ()
::std::string * release_msg_type ()
::std::string * release_operation ()
::std::string * release_topic ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_compression (::std::string *compression)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_msg_type (::std::string *msg_type)
void set_allocated_operation (::std::string *operation)
void set_allocated_topic (::std::string *topic)
void set_compression (const ::std::string &value)
void set_compression (const char *value)
void set_compression (const char *value, size_t size)
void set_hz (double value)
void set_msg_type (const ::std::string &value)
void set_msg_type (const char *value)
void set_msg_type (const char *value, size_t size)
void set_operation (const ::std::string &value)
void set_operation (const char *value)
void set_operation (const char *value, size_t size)
void set_topic (const ::std::string &value)
void set_topic (const char *value)
void set_topic (const char *value, size_t size)
void Swap (WebRequest *other)
const ::std::string & topic () const
Static Public Member Functions
static const WebRequest & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const WebRequest * internal_default_instance ()
Static Public Attributes
static const int kCompressionFieldNumber = 5
static const int kHeaderFieldNumber = 1
static const int kHzFieldNumber = 6
static constexpr int kIndexInFileMessages
static const int kMsgTypeFieldNumber = 4
static const int kOperationFieldNumber = 2
static const int kTopicFieldNumber = 3
Constructor & Destructor Documentation
WebRequest() [1/2]
WebRequest ()
~WebRequest()
virtual ~WebRequest () virtual
WebRequest() [2/2]
WebRequest (const WebRequest & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_compression()
void clear_compression () inline
clear_header()
void clear_header ()
clear_hz()
void clear_hz () inline
clear_msg_type()
void clear_msg_type () inline
clear_operation()
void clear_operation () inline
clear_topic()
void clear_topic () inline
compression()
const ::std::string & compression () const inline
Referenced by WebRequest::set_allocated_compression().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const WebRequest & from)
default_instance()
static const WebRequest& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References WebRequest::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by WebRequest::set_allocated_header().
hz()
double hz () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const WebRequest* internal_default_instance () inline static
References gz::msgs::_WebRequest_default_instance_.
Referenced by WebRequest::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const WebRequest & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
msg_type()
const ::std::string & msg_type () const inline
Referenced by WebRequest::set_allocated_msg_type().
mutable_compression()
std::string * mutable_compression () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_msg_type()
std::string * mutable_msg_type () inline
mutable_operation()
std::string * mutable_operation () inline
mutable_topic()
std::string * mutable_topic () inline
New() [1/2]
WebRequest* New () const inline final
New() [2/2]
WebRequest* New (::google::protobuf::Arena * arena) const inline final
operation()
const ::std::string & operation () const inline
Referenced by WebRequest::set_allocated_operation().
operator=()
WebRequest& operator= (const WebRequest & from) inline
release_compression()
std::string * release_compression () inline
release_header()
gz::msgs::Header * release_header () inline
release_msg_type()
std::string * release_msg_type () inline
release_operation()
std::string * release_operation () inline
release_topic()
std::string * release_topic () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_compression()
void set_allocated_compression (::std::string * compression) inline
References WebRequest::compression().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References WebRequest::header().
set_allocated_msg_type()
void set_allocated_msg_type (::std::string * msg_type) inline
References WebRequest::msg_type().
set_allocated_operation()
void set_allocated_operation (::std::string * operation) inline
References WebRequest::operation().
set_allocated_topic()
void set_allocated_topic (::std::string * topic) inline
References WebRequest::topic().
set_compression() [1/3]
void set_compression (const ::std::string & value) inline
set_compression() [2/3]
void set_compression (const char * value) inline
set_compression() [3/3]
void set_compression (const char * value, size_t size) inline
set_hz()
void set_hz (double value) inline
set_msg_type() [1/3]
void set_msg_type (const ::std::string & value) inline
set_msg_type() [2/3]
void set_msg_type (const char * value) inline
set_msg_type() [3/3]
void set_msg_type (const char * value, size_t size) inline
set_operation() [1/3]
void set_operation (const ::std::string & value) inline
set_operation() [2/3]
void set_operation (const char * value) inline
set_operation() [3/3]
void set_operation (const char * value, size_t size) inline
set_topic() [1/3]
void set_topic (const ::std::string & value) inline
set_topic() [2/3]
void set_topic (const char * value) inline
set_topic() [3/3]
void set_topic (const char * value, size_t size) inline
Swap()
void Swap (WebRequest * other)
topic()
const ::std::string & topic () const inline
Referenced by WebRequest::set_allocated_topic().
Member Data Documentation
kCompressionFieldNumber
const int kCompressionFieldNumber = 5 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHzFieldNumber
const int kHzFieldNumber = 6 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kMsgTypeFieldNumber
const int kMsgTypeFieldNumber = 4 static
kOperationFieldNumber
const int kOperationFieldNumber = 2 static
kTopicFieldNumber
const int kTopicFieldNumber = 3 static
The documentation for this class was generated from the following file:
web_request.pb.h