Gazebo Msgs: Material_PBR Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Material_PBR Class Reference
#include <material.pb.h>
Public Types
typedef Material_PBR_WorkflowType WorkflowType
Public Member Functions
Material_PBR ()
Material_PBR (const Material_PBR &from)
virtual ~Material_PBR ()
const ::std::string & albedo_map () const
const ::std::string & ambient_occlusion_map () const
size_t ByteSizeLong () const final
void Clear () final
void clear_albedo_map ()
void clear_ambient_occlusion_map ()
void clear_emissive_map ()
void clear_environment_map ()
void clear_glossiness ()
void clear_glossiness_map ()
void clear_light_map ()
void clear_light_map_texcoord_set ()
void clear_metalness ()
void clear_metalness_map ()
void clear_normal_map ()
void clear_roughness ()
void clear_roughness_map ()
void clear_specular_map ()
void clear_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Material_PBR &from)
const ::std::string & emissive_map () const
const ::std::string & environment_map () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
double glossiness () const
const ::std::string & glossiness_map () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::std::string & light_map () const
::google::protobuf::uint32 light_map_texcoord_set () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Material_PBR &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
double metalness () const
const ::std::string & metalness_map () const
::std::string * mutable_albedo_map ()
::std::string * mutable_ambient_occlusion_map ()
::std::string * mutable_emissive_map ()
::std::string * mutable_environment_map ()
::std::string * mutable_glossiness_map ()
::std::string * mutable_light_map ()
::std::string * mutable_metalness_map ()
::std::string * mutable_normal_map ()
::std::string * mutable_roughness_map ()
::std::string * mutable_specular_map ()
Material_PBR * New () const final
Material_PBR * New (::google::protobuf::Arena *arena) const final
const ::std::string & normal_map () const
Material_PBR & operator= (const Material_PBR &from)
::std::string * release_albedo_map ()
::std::string * release_ambient_occlusion_map ()
::std::string * release_emissive_map ()
::std::string * release_environment_map ()
::std::string * release_glossiness_map ()
::std::string * release_light_map ()
::std::string * release_metalness_map ()
::std::string * release_normal_map ()
::std::string * release_roughness_map ()
::std::string * release_specular_map ()
double roughness () const
const ::std::string & roughness_map () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_albedo_map (const ::std::string &value)
void set_albedo_map (const char *value)
void set_albedo_map (const char *value, size_t size)
void set_allocated_albedo_map (::std::string *albedo_map)
void set_allocated_ambient_occlusion_map (::std::string *ambient_occlusion_map)
void set_allocated_emissive_map (::std::string *emissive_map)
void set_allocated_environment_map (::std::string *environment_map)
void set_allocated_glossiness_map (::std::string *glossiness_map)
void set_allocated_light_map (::std::string *light_map)
void set_allocated_metalness_map (::std::string *metalness_map)
void set_allocated_normal_map (::std::string *normal_map)
void set_allocated_roughness_map (::std::string *roughness_map)
void set_allocated_specular_map (::std::string *specular_map)
void set_ambient_occlusion_map (const ::std::string &value)
void set_ambient_occlusion_map (const char *value)
void set_ambient_occlusion_map (const char *value, size_t size)
void set_emissive_map (const ::std::string &value)
void set_emissive_map (const char *value)
void set_emissive_map (const char *value, size_t size)
void set_environment_map (const ::std::string &value)
void set_environment_map (const char *value)
void set_environment_map (const char *value, size_t size)
void set_glossiness (double value)
void set_glossiness_map (const ::std::string &value)
void set_glossiness_map (const char *value)
void set_glossiness_map (const char *value, size_t size)
void set_light_map (const ::std::string &value)
void set_light_map (const char *value)
void set_light_map (const char *value, size_t size)
void set_light_map_texcoord_set (::google::protobuf::uint32 value)
void set_metalness (double value)
void set_metalness_map (const ::std::string &value)
void set_metalness_map (const char *value)
void set_metalness_map (const char *value, size_t size)
void set_normal_map (const ::std::string &value)
void set_normal_map (const char *value)
void set_normal_map (const char *value, size_t size)
void set_roughness (double value)
void set_roughness_map (const ::std::string &value)
void set_roughness_map (const char *value)
void set_roughness_map (const char *value, size_t size)
void set_specular_map (const ::std::string &value)
void set_specular_map (const char *value)
void set_specular_map (const char *value, size_t size)
void set_type (::gz::msgs::Material_PBR_WorkflowType value)
const ::std::string & specular_map () const
void Swap (Material_PBR *other)
::gz::msgs::Material_PBR_WorkflowType type () const
Static Public Member Functions
static const Material_PBR & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Material_PBR * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * WorkflowType_descriptor ()
static bool WorkflowType_IsValid (int value)
static const ::std::string & WorkflowType_Name (WorkflowType value)
static bool WorkflowType_Parse (const ::std::string &name, WorkflowType *value)
Static Public Attributes
static const int kAlbedoMapFieldNumber = 2
static const int kAmbientOcclusionMapFieldNumber = 12
static const int kEmissiveMapFieldNumber = 13
static const int kEnvironmentMapFieldNumber = 11
static const int kGlossinessFieldNumber = 8
static const int kGlossinessMapFieldNumber = 9
static constexpr int kIndexInFileMessages
static const int kLightMapFieldNumber = 14
static const int kLightMapTexcoordSetFieldNumber = 15
static const int kMetalnessFieldNumber = 4
static const int kMetalnessMapFieldNumber = 5
static const int kNormalMapFieldNumber = 3
static const int kRoughnessFieldNumber = 6
static const int kRoughnessMapFieldNumber = 7
static const int kSpecularMapFieldNumber = 10
static const int kTypeFieldNumber = 1
static const WorkflowType METAL
static const WorkflowType NONE
static const WorkflowType SPECULAR
static const int WorkflowType_ARRAYSIZE
static const WorkflowType WorkflowType_MAX
static const WorkflowType WorkflowType_MIN
Member Typedef Documentation
WorkflowType
typedef Material_PBR_WorkflowType WorkflowType
Constructor & Destructor Documentation
Material_PBR() [1/2]
Material_PBR ()
~Material_PBR()
virtual ~Material_PBR () virtual
Material_PBR() [2/2]
Material_PBR (const Material_PBR & from)
Member Function Documentation
albedo_map()
const ::std::string & albedo_map () const inline
Referenced by Material_PBR::set_allocated_albedo_map().
ambient_occlusion_map()
const ::std::string & ambient_occlusion_map () const inline
Referenced by Material_PBR::set_allocated_ambient_occlusion_map().
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_albedo_map()
void clear_albedo_map () inline
clear_ambient_occlusion_map()
void clear_ambient_occlusion_map () inline
clear_emissive_map()
void clear_emissive_map () inline
clear_environment_map()
void clear_environment_map () inline
clear_glossiness()
void clear_glossiness () inline
clear_glossiness_map()
void clear_glossiness_map () inline
clear_light_map()
void clear_light_map () inline
clear_light_map_texcoord_set()
void clear_light_map_texcoord_set () inline
clear_metalness()
void clear_metalness () inline
clear_metalness_map()
void clear_metalness_map () inline
clear_normal_map()
void clear_normal_map () inline
clear_roughness()
void clear_roughness () inline
clear_roughness_map()
void clear_roughness_map () inline
clear_specular_map()
void clear_specular_map () inline
clear_type()
void clear_type () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Material_PBR & from)
default_instance()
static const Material_PBR& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
emissive_map()
const ::std::string & emissive_map () const inline
Referenced by Material_PBR::set_allocated_emissive_map().
environment_map()
const ::std::string & environment_map () const inline
Referenced by Material_PBR::set_allocated_environment_map().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
glossiness()
double glossiness () const inline
glossiness_map()
const ::std::string & glossiness_map () const inline
Referenced by Material_PBR::set_allocated_glossiness_map().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Material_PBR* internal_default_instance () inline static
References gz::msgs::_Material_PBR_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
light_map()
const ::std::string & light_map () const inline
Referenced by Material_PBR::set_allocated_light_map().
light_map_texcoord_set()
google::protobuf::uint32 light_map_texcoord_set () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Material_PBR & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
metalness()
double metalness () const inline
metalness_map()
const ::std::string & metalness_map () const inline
Referenced by Material_PBR::set_allocated_metalness_map().
mutable_albedo_map()
std::string * mutable_albedo_map () inline
mutable_ambient_occlusion_map()
std::string * mutable_ambient_occlusion_map () inline
mutable_emissive_map()
std::string * mutable_emissive_map () inline
mutable_environment_map()
std::string * mutable_environment_map () inline
mutable_glossiness_map()
std::string * mutable_glossiness_map () inline
mutable_light_map()
std::string * mutable_light_map () inline
mutable_metalness_map()
std::string * mutable_metalness_map () inline
mutable_normal_map()
std::string * mutable_normal_map () inline
mutable_roughness_map()
std::string * mutable_roughness_map () inline
mutable_specular_map()
std::string * mutable_specular_map () inline
New() [1/2]
Material_PBR* New () const inline final
New() [2/2]
Material_PBR* New (::google::protobuf::Arena * arena) const inline final
normal_map()
const ::std::string & normal_map () const inline
Referenced by Material_PBR::set_allocated_normal_map().
operator=()
Material_PBR& operator= (const Material_PBR & from) inline
release_albedo_map()
std::string * release_albedo_map () inline
release_ambient_occlusion_map()
std::string * release_ambient_occlusion_map () inline
release_emissive_map()
std::string * release_emissive_map () inline
release_environment_map()
std::string * release_environment_map () inline
release_glossiness_map()
std::string * release_glossiness_map () inline
release_light_map()
std::string * release_light_map () inline
release_metalness_map()
std::string * release_metalness_map () inline
release_normal_map()
std::string * release_normal_map () inline
release_roughness_map()
std::string * release_roughness_map () inline
release_specular_map()
std::string * release_specular_map () inline
roughness()
double roughness () const inline
roughness_map()
const ::std::string & roughness_map () const inline
Referenced by Material_PBR::set_allocated_roughness_map().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_albedo_map() [1/3]
void set_albedo_map (const ::std::string & value) inline
set_albedo_map() [2/3]
void set_albedo_map (const char * value) inline
set_albedo_map() [3/3]
void set_albedo_map (const char * value, size_t size) inline
set_allocated_albedo_map()
void set_allocated_albedo_map (::std::string * albedo_map) inline
References Material_PBR::albedo_map().
set_allocated_ambient_occlusion_map()
void set_allocated_ambient_occlusion_map (::std::string * ambient_occlusion_map) inline
References Material_PBR::ambient_occlusion_map().
set_allocated_emissive_map()
void set_allocated_emissive_map (::std::string * emissive_map) inline
References Material_PBR::emissive_map().
set_allocated_environment_map()
void set_allocated_environment_map (::std::string * environment_map) inline
References Material_PBR::environment_map().
set_allocated_glossiness_map()
void set_allocated_glossiness_map (::std::string * glossiness_map) inline
References Material_PBR::glossiness_map().
set_allocated_light_map()
void set_allocated_light_map (::std::string * light_map) inline
References Material_PBR::light_map().
set_allocated_metalness_map()
void set_allocated_metalness_map (::std::string * metalness_map) inline
References Material_PBR::metalness_map().
set_allocated_normal_map()
void set_allocated_normal_map (::std::string * normal_map) inline
References Material_PBR::normal_map().
set_allocated_roughness_map()
void set_allocated_roughness_map (::std::string * roughness_map) inline
References Material_PBR::roughness_map().
set_allocated_specular_map()
void set_allocated_specular_map (::std::string * specular_map) inline
References Material_PBR::specular_map().
set_ambient_occlusion_map() [1/3]
void set_ambient_occlusion_map (const ::std::string & value) inline
set_ambient_occlusion_map() [2/3]
void set_ambient_occlusion_map (const char * value) inline
set_ambient_occlusion_map() [3/3]
void set_ambient_occlusion_map (const char * value, size_t size) inline
set_emissive_map() [1/3]
void set_emissive_map (const ::std::string & value) inline
set_emissive_map() [2/3]
void set_emissive_map (const char * value) inline
set_emissive_map() [3/3]
void set_emissive_map (const char * value, size_t size) inline
set_environment_map() [1/3]
void set_environment_map (const ::std::string & value) inline
set_environment_map() [2/3]
void set_environment_map (const char * value) inline
set_environment_map() [3/3]
void set_environment_map (const char * value, size_t size) inline
set_glossiness()
void set_glossiness (double value) inline
set_glossiness_map() [1/3]
void set_glossiness_map (const ::std::string & value) inline
set_glossiness_map() [2/3]
void set_glossiness_map (const char * value) inline
set_glossiness_map() [3/3]
void set_glossiness_map (const char * value, size_t size) inline
set_light_map() [1/3]
void set_light_map (const ::std::string & value) inline
set_light_map() [2/3]
void set_light_map (const char * value) inline
set_light_map() [3/3]
void set_light_map (const char * value, size_t size) inline
set_light_map_texcoord_set()
void set_light_map_texcoord_set (::google::protobuf::uint32 value) inline
set_metalness()
void set_metalness (double value) inline
set_metalness_map() [1/3]
void set_metalness_map (const ::std::string & value) inline
set_metalness_map() [2/3]
void set_metalness_map (const char * value) inline
set_metalness_map() [3/3]
void set_metalness_map (const char * value, size_t size) inline
set_normal_map() [1/3]
void set_normal_map (const ::std::string & value) inline
set_normal_map() [2/3]
void set_normal_map (const char * value) inline
set_normal_map() [3/3]
void set_normal_map (const char * value, size_t size) inline
set_roughness()
void set_roughness (double value) inline
set_roughness_map() [1/3]
void set_roughness_map (const ::std::string & value) inline
set_roughness_map() [2/3]
void set_roughness_map (const char * value) inline
set_roughness_map() [3/3]
void set_roughness_map (const char * value, size_t size) inline
set_specular_map() [1/3]
void set_specular_map (const ::std::string & value) inline
set_specular_map() [2/3]
void set_specular_map (const char * value) inline
set_specular_map() [3/3]
void set_specular_map (const char * value, size_t size) inline
set_type()
void set_type (::gz::msgs::Material_PBR_WorkflowType value) inline
specular_map()
const ::std::string & specular_map () const inline
Referenced by Material_PBR::set_allocated_specular_map().
Swap()
void Swap (Material_PBR * other)
type()
gz::msgs::Material_PBR_WorkflowType type () const inline
WorkflowType_descriptor()
static const ::google::protobuf::EnumDescriptor* WorkflowType_descriptor () inline static
References gz::msgs::Material_PBR_WorkflowType_descriptor().
WorkflowType_IsValid()
static bool WorkflowType_IsValid (int value) inline static
References gz::msgs::Material_PBR_WorkflowType_IsValid().
WorkflowType_Name()
static const ::std::string& WorkflowType_Name (WorkflowType value) inline static
References gz::msgs::Material_PBR_WorkflowType_Name().
WorkflowType_Parse()
static bool WorkflowType_Parse (const ::std::string & name, WorkflowType * value) inline static
References gz::msgs::Material_PBR_WorkflowType_Parse().
Member Data Documentation
kAlbedoMapFieldNumber
const int kAlbedoMapFieldNumber = 2 static
kAmbientOcclusionMapFieldNumber
const int kAmbientOcclusionMapFieldNumber = 12 static
kEmissiveMapFieldNumber
const int kEmissiveMapFieldNumber = 13 static
kEnvironmentMapFieldNumber
const int kEnvironmentMapFieldNumber = 11 static
kGlossinessFieldNumber
const int kGlossinessFieldNumber = 8 static
kGlossinessMapFieldNumber
const int kGlossinessMapFieldNumber = 9 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    1
kLightMapFieldNumber
const int kLightMapFieldNumber = 14 static
kLightMapTexcoordSetFieldNumber
const int kLightMapTexcoordSetFieldNumber = 15 static
kMetalnessFieldNumber
const int kMetalnessFieldNumber = 4 static
kMetalnessMapFieldNumber
const int kMetalnessMapFieldNumber = 5 static
kNormalMapFieldNumber
const int kNormalMapFieldNumber = 3 static
kRoughnessFieldNumber
const int kRoughnessFieldNumber = 6 static
kRoughnessMapFieldNumber
const int kRoughnessMapFieldNumber = 7 static
kSpecularMapFieldNumber
const int kSpecularMapFieldNumber = 10 static
kTypeFieldNumber
const int kTypeFieldNumber = 1 static
METAL
const WorkflowType METAL static
Initial value:
=
    Material_PBR_WorkflowType_METAL
NONE
const WorkflowType NONE static
Initial value:
=
    Material_PBR_WorkflowType_NONE
SPECULAR
const WorkflowType SPECULAR static
Initial value:
=
    Material_PBR_WorkflowType_SPECULAR
WorkflowType_ARRAYSIZE
const int WorkflowType_ARRAYSIZE static
Initial value:
=
    Material_PBR_WorkflowType_WorkflowType_ARRAYSIZE
WorkflowType_MAX
const WorkflowType WorkflowType_MAX static
Initial value:
=
    Material_PBR_WorkflowType_WorkflowType_MAX
WorkflowType_MIN
const WorkflowType WorkflowType_MIN static
Initial value:
=
    Material_PBR_WorkflowType_WorkflowType_MIN
The documentation for this class was generated from the following file:
material.pb.h