Gazebo Msgs: Image Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Image Class Reference
#include <image.pb.h>
Public Member Functions
Image ()
Image (const Image &from)
virtual ~Image ()
size_t ByteSizeLong () const final
void Clear () final
void clear_data ()
void clear_header ()
void clear_height ()
void clear_pixel_format_type ()
void clear_step ()
void clear_width ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Image &from)
const ::std::string & data () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint32 height () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Image &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_data ()
::gz::msgs::Header * mutable_header ()
Image * New () const final
Image * New (::google::protobuf::Arena *arena) const final
Image & operator= (const Image &from)
::gz::msgs::PixelFormatType pixel_format_type () const
::std::string * release_data ()
::gz::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_data (::std::string *data)
void set_allocated_header (::gz::msgs::Header *header)
void set_data (const ::std::string &value)
void set_data (const char *value)
void set_data (const void *value, size_t size)
void set_height (::google::protobuf::uint32 value)
void set_pixel_format_type (::gz::msgs::PixelFormatType value)
void set_step (::google::protobuf::uint32 value)
void set_width (::google::protobuf::uint32 value)
::google::protobuf::uint32 step () const
void Swap (Image *other)
::google::protobuf::uint32 width () const
Static Public Member Functions
static const Image & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Image * internal_default_instance ()
Static Public Attributes
static const int kDataFieldNumber = 5
static const int kHeaderFieldNumber = 1
static const int kHeightFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kPixelFormatTypeFieldNumber = 6
static const int kStepFieldNumber = 4
static const int kWidthFieldNumber = 2
Constructor & Destructor Documentation
Image() [1/2]
Image ()
~Image()
virtual ~Image () virtual
Image() [2/2]
Image (const Image & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_data()
void clear_data () inline
clear_header()
void clear_header ()
clear_height()
void clear_height () inline
clear_pixel_format_type()
void clear_pixel_format_type () inline
clear_step()
void clear_step () inline
clear_width()
void clear_width () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Image & from)
data()
const ::std::string & data () const inline
Referenced by Image::set_allocated_data().
default_instance()
static const Image& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Image::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by Image::set_allocated_header().
height()
google::protobuf::uint32 height () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Image* internal_default_instance () inline static
References gz::msgs::_Image_default_instance_.
Referenced by Image::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Image & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_data()
std::string * mutable_data () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
New() [1/2]
Image* New () const inline final
New() [2/2]
Image* New (::google::protobuf::Arena * arena) const inline final
operator=()
Image& operator= (const Image & from) inline
pixel_format_type()
gz::msgs::PixelFormatType pixel_format_type () const inline
release_data()
std::string * release_data () inline
release_header()
gz::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_data()
void set_allocated_data (::std::string * data) inline
References Image::data().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References Image::header().
set_data() [1/3]
void set_data (const ::std::string & value) inline
set_data() [2/3]
void set_data (const char * value) inline
set_data() [3/3]
void set_data (const void * value, size_t size) inline
set_height()
void set_height (::google::protobuf::uint32 value) inline
set_pixel_format_type()
void set_pixel_format_type (::gz::msgs::PixelFormatType value) inline
set_step()
void set_step (::google::protobuf::uint32 value) inline
set_width()
void set_width (::google::protobuf::uint32 value) inline
step()
google::protobuf::uint32 step () const inline
Swap()
void Swap (Image * other)
width()
google::protobuf::uint32 width () const inline
Member Data Documentation
kDataFieldNumber
const int kDataFieldNumber = 5 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHeightFieldNumber
const int kHeightFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kPixelFormatTypeFieldNumber
const int kPixelFormatTypeFieldNumber = 6 static
kStepFieldNumber
const int kStepFieldNumber = 4 static
kWidthFieldNumber
const int kWidthFieldNumber = 2 static
The documentation for this class was generated from the following file:
image.pb.h