Gazebo Msgs: Visual Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Visual Class Reference
#include <visual.pb.h>
Public Types
typedef Visual_Meta Meta
typedef Visual_Type Type
Public Member Functions
Visual ()
Visual (const Visual &from)
virtual ~Visual ()
::gz::msgs::Plugin * add_plugin ()
size_t ByteSizeLong () const final
bool cast_shadows () const
void Clear () final
void clear_cast_shadows ()
void clear_delete_me ()
void clear_geometry ()
void clear_header ()
void clear_id ()
void clear_is_static ()
void clear_laser_retro ()
void clear_material ()
void clear_meta ()
void clear_name ()
void clear_parent_id ()
void clear_parent_name ()
void clear_plugin ()
void clear_pose ()
void clear_scale ()
void clear_transparency ()
void clear_type ()
void clear_visible ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Visual &from)
bool delete_me () const
const ::gz::msgs::Geometry & geometry () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_geometry () const
bool has_header () const
bool has_material () const
bool has_meta () const
bool has_pose () const
bool has_scale () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool is_static () const
bool IsInitialized () const final
double laser_retro () const
const ::gz::msgs::Material & material () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Visual &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::gz::msgs::Visual_Meta & meta () const
::gz::msgs::Geometry * mutable_geometry ()
::gz::msgs::Header * mutable_header ()
::gz::msgs::Material * mutable_material ()
::gz::msgs::Visual_Meta * mutable_meta ()
::std::string * mutable_name ()
::std::string * mutable_parent_name ()
::google::protobuf::RepeatedPtrField< ::gz::msgs::Plugin > * mutable_plugin ()
::gz::msgs::Plugin * mutable_plugin (int index)
::gz::msgs::Pose * mutable_pose ()
::gz::msgs::Vector3d * mutable_scale ()
const ::std::string & name () const
Visual * New () const final
Visual * New (::google::protobuf::Arena *arena) const final
Visual & operator= (const Visual &from)
::google::protobuf::uint32 parent_id () const
const ::std::string & parent_name () const
const ::google::protobuf::RepeatedPtrField< ::gz::msgs::Plugin > & plugin () const
const ::gz::msgs::Plugin & plugin (int index) const
int plugin_size () const
const ::gz::msgs::Pose & pose () const
::gz::msgs::Geometry * release_geometry ()
::gz::msgs::Header * release_header ()
::gz::msgs::Material * release_material ()
::gz::msgs::Visual_Meta * release_meta ()
::std::string * release_name ()
::std::string * release_parent_name ()
::gz::msgs::Pose * release_pose ()
::gz::msgs::Vector3d * release_scale ()
const ::gz::msgs::Vector3d & scale () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_geometry (::gz::msgs::Geometry *geometry)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_material (::gz::msgs::Material *material)
void set_allocated_meta (::gz::msgs::Visual_Meta *meta)
void set_allocated_name (::std::string *name)
void set_allocated_parent_name (::std::string *parent_name)
void set_allocated_pose (::gz::msgs::Pose *pose)
void set_allocated_scale (::gz::msgs::Vector3d *scale)
void set_cast_shadows (bool value)
void set_delete_me (bool value)
void set_id (::google::protobuf::uint32 value)
void set_is_static (bool value)
void set_laser_retro (double value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_parent_id (::google::protobuf::uint32 value)
void set_parent_name (const ::std::string &value)
void set_parent_name (const char *value)
void set_parent_name (const char *value, size_t size)
void set_transparency (double value)
void set_type (::gz::msgs::Visual_Type value)
void set_visible (bool value)
void Swap (Visual *other)
double transparency () const
::gz::msgs::Visual_Type type () const
bool visible () const
Static Public Member Functions
static const Visual & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Visual * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type COLLISION
static const Type ENTITY
static const Type GUI
static const int kCastShadowsFieldNumber = 6
static const int kDeleteMeFieldNumber = 13
static const int kGeometryFieldNumber = 10
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kIsStaticFieldNumber = 14
static const int kLaserRetroFieldNumber = 8
static const int kMaterialFieldNumber = 11
static const int kMetaFieldNumber = 17
static const int kNameFieldNumber = 2
static const int kParentIdFieldNumber = 5
static const int kParentNameFieldNumber = 4
static const int kPluginFieldNumber = 15
static const int kPoseFieldNumber = 9
static const int kScaleFieldNumber = 16
static const int kTransparencyFieldNumber = 7
static const int kTypeFieldNumber = 18
static const int kVisibleFieldNumber = 12
static const Type LINK
static const Type MODEL
static const Type PHYSICS
static const Type SENSOR
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
static const Type VISUAL
Member Typedef Documentation
Meta
typedef Visual_Meta Meta
Type
typedef Visual_Type Type
Constructor & Destructor Documentation
Visual() [1/2]
Visual ()
~Visual()
virtual ~Visual () virtual
Visual() [2/2]
Visual (const Visual & from)
Member Function Documentation
add_plugin()
gz::msgs::Plugin * add_plugin () inline
ByteSizeLong()
size_t ByteSizeLong () const final
cast_shadows()
bool cast_shadows () const inline
Clear()
void Clear () final
clear_cast_shadows()
void clear_cast_shadows () inline
clear_delete_me()
void clear_delete_me () inline
clear_geometry()
void clear_geometry ()
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_is_static()
void clear_is_static () inline
clear_laser_retro()
void clear_laser_retro () inline
clear_material()
void clear_material ()
clear_meta()
void clear_meta () inline
clear_name()
void clear_name () inline
clear_parent_id()
void clear_parent_id () inline
clear_parent_name()
void clear_parent_name () inline
clear_plugin()
void clear_plugin ()
clear_pose()
void clear_pose ()
clear_scale()
void clear_scale ()
clear_transparency()
void clear_transparency () inline
clear_type()
void clear_type () inline
clear_visible()
void clear_visible () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Visual & from)
default_instance()
static const Visual& default_instance () static
delete_me()
bool delete_me () const inline
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
geometry()
const ::gz::msgs::Geometry & geometry () const inline
References gz::msgs::_Geometry_default_instance_.
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_geometry()
bool has_geometry () const inline
has_header()
bool has_header () const inline
has_material()
bool has_material () const inline
has_meta()
bool has_meta () const inline
has_pose()
bool has_pose () const inline
has_scale()
bool has_scale () const inline
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Visual* internal_default_instance () inline static
References gz::msgs::_Visual_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
is_static()
bool is_static () const inline
IsInitialized()
bool IsInitialized () const final
laser_retro()
double laser_retro () const inline
material()
const ::gz::msgs::Material & material () const inline
References gz::msgs::_Material_default_instance_.
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Visual & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
meta()
const ::gz::msgs::Visual_Meta & meta () const inline
References gz::msgs::_Visual_Meta_default_instance_.
mutable_geometry()
gz::msgs::Geometry * mutable_geometry () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_material()
gz::msgs::Material * mutable_material () inline
mutable_meta()
gz::msgs::Visual_Meta * mutable_meta () inline
mutable_name()
std::string * mutable_name () inline
mutable_parent_name()
std::string * mutable_parent_name () inline
mutable_plugin() [1/2]
google::protobuf::RepeatedPtrField<::gz::msgs::Plugin > * mutable_plugin () inline
mutable_plugin() [2/2]
gz::msgs::Plugin * mutable_plugin (int index) inline
mutable_pose()
gz::msgs::Pose * mutable_pose () inline
mutable_scale()
gz::msgs::Vector3d * mutable_scale () inline
name()
const ::std::string & name () const inline
New() [1/2]
Visual* New () const inline final
New() [2/2]
Visual* New (::google::protobuf::Arena * arena) const inline final
operator=()
Visual& operator= (const Visual & from) inline
parent_id()
google::protobuf::uint32 parent_id () const inline
parent_name()
const ::std::string & parent_name () const inline
plugin() [1/2]
const ::google::protobuf::RepeatedPtrField<::gz::msgs::Plugin > & plugin () const inline
plugin() [2/2]
const ::gz::msgs::Plugin & plugin (int index) const inline
plugin_size()
int plugin_size () const inline
pose()
const ::gz::msgs::Pose & pose () const inline
References gz::msgs::_Pose_default_instance_.
release_geometry()
gz::msgs::Geometry * release_geometry () inline
release_header()
gz::msgs::Header * release_header () inline
release_material()
gz::msgs::Material * release_material () inline
release_meta()
gz::msgs::Visual_Meta * release_meta () inline
release_name()
std::string * release_name () inline
release_parent_name()
std::string * release_parent_name () inline
release_pose()
gz::msgs::Pose * release_pose () inline
release_scale()
gz::msgs::Vector3d * release_scale () inline
scale()
const ::gz::msgs::Vector3d & scale () const inline
References gz::msgs::_Vector3d_default_instance_.
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_geometry()
void set_allocated_geometry (::gz::msgs::Geometry * geometry) inline
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
set_allocated_material()
void set_allocated_material (::gz::msgs::Material * material) inline
set_allocated_meta()
void set_allocated_meta (::gz::msgs::Visual_Meta * meta) inline
set_allocated_name()
void set_allocated_name (::std::string * name) inline
set_allocated_parent_name()
void set_allocated_parent_name (::std::string * parent_name) inline
set_allocated_pose()
void set_allocated_pose (::gz::msgs::Pose * pose) inline
set_allocated_scale()
void set_allocated_scale (::gz::msgs::Vector3d * scale) inline
set_cast_shadows()
void set_cast_shadows (bool value) inline
set_delete_me()
void set_delete_me (bool value) inline
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_is_static()
void set_is_static (bool value) inline
set_laser_retro()
void set_laser_retro (double value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_parent_id()
void set_parent_id (::google::protobuf::uint32 value) inline
set_parent_name() [1/3]
void set_parent_name (const ::std::string & value) inline
set_parent_name() [2/3]
void set_parent_name (const char * value) inline
set_parent_name() [3/3]
void set_parent_name (const char * value, size_t size) inline
set_transparency()
void set_transparency (double value) inline
set_type()
void set_type (::gz::msgs::Visual_Type value) inline
set_visible()
void set_visible (bool value) inline
Swap()
void Swap (Visual * other)
transparency()
double transparency () const inline
type()
gz::msgs::Visual_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References gz::msgs::Visual_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References gz::msgs::Visual_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References gz::msgs::Visual_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References gz::msgs::Visual_Type_Parse().
visible()
bool visible () const inline
Member Data Documentation
COLLISION
const Type COLLISION static
Initial value:
=
    Visual_Type_COLLISION
ENTITY
const Type ENTITY static
Initial value:
=
    Visual_Type_ENTITY
GUI
const Type GUI static
Initial value:
=
    Visual_Type_GUI
kCastShadowsFieldNumber
const int kCastShadowsFieldNumber = 6 static
kDeleteMeFieldNumber
const int kDeleteMeFieldNumber = 13 static
kGeometryFieldNumber
const int kGeometryFieldNumber = 10 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    1
kIsStaticFieldNumber
const int kIsStaticFieldNumber = 14 static
kLaserRetroFieldNumber
const int kLaserRetroFieldNumber = 8 static
kMaterialFieldNumber
const int kMaterialFieldNumber = 11 static
kMetaFieldNumber
const int kMetaFieldNumber = 17 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
kParentIdFieldNumber
const int kParentIdFieldNumber = 5 static
kParentNameFieldNumber
const int kParentNameFieldNumber = 4 static
kPluginFieldNumber
const int kPluginFieldNumber = 15 static
kPoseFieldNumber
const int kPoseFieldNumber = 9 static
kScaleFieldNumber
const int kScaleFieldNumber = 16 static
kTransparencyFieldNumber
const int kTransparencyFieldNumber = 7 static
kTypeFieldNumber
const int kTypeFieldNumber = 18 static
kVisibleFieldNumber
const int kVisibleFieldNumber = 12 static
LINK
const Type LINK static
Initial value:
=
    Visual_Type_LINK
MODEL
const Type MODEL static
Initial value:
=
    Visual_Type_MODEL
PHYSICS
const Type PHYSICS static
Initial value:
=
    Visual_Type_PHYSICS
SENSOR
const Type SENSOR static
Initial value:
=
    Visual_Type_SENSOR
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    Visual_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    Visual_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    Visual_Type_Type_MIN
VISUAL
const Type VISUAL static
Initial value:
=
    Visual_Type_VISUAL
The documentation for this class was generated from the following file:
visual.pb.h