Gazebo Msgs: Statistic Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Statistic Class Reference
#include <statistic.pb.h>
Public Types
typedef Statistic_DataType DataType
Public Member Functions
Statistic ()
Statistic (const Statistic &from)
virtual ~Statistic ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_name ()
void clear_type ()
void clear_value ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Statistic &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Statistic &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Header * mutable_header ()
::std::string * mutable_name ()
const ::std::string & name () const
Statistic * New () const final
Statistic * New (::google::protobuf::Arena *arena) const final
Statistic & operator= (const Statistic &from)
::gz::msgs::Header * release_header ()
::std::string * release_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_type (::gz::msgs::Statistic_DataType value)
void set_value (double value)
void Swap (Statistic *other)
::gz::msgs::Statistic_DataType type () const
double value () const
Static Public Member Functions
static const ::google::protobuf::EnumDescriptor * DataType_descriptor ()
static bool DataType_IsValid (int value)
static const ::std::string & DataType_Name (DataType value)
static bool DataType_Parse (const ::std::string &name, DataType *value)
static const Statistic & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Statistic * internal_default_instance ()
Static Public Attributes
static const DataType AVERAGE
static const int DataType_ARRAYSIZE
static const DataType DataType_MAX
static const DataType DataType_MIN
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 3
static const int kTypeFieldNumber = 2
static const int kValueFieldNumber = 4
static const DataType MAX_ABS_VALUE
static const DataType MAXIMUM
static const DataType MINIMUM
static const DataType ROOT_MEAN_SQUARE
static const DataType SAMPLE_COUNT
static const DataType STDDEV
static const DataType UNINITIALIZED
static const DataType VARIANCE
Member Typedef Documentation
DataType
typedef Statistic_DataType DataType
Constructor & Destructor Documentation
Statistic() [1/2]
Statistic ()
~Statistic()
virtual ~Statistic () virtual
Statistic() [2/2]
Statistic (const Statistic & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_name()
void clear_name () inline
clear_type()
void clear_type () inline
clear_value()
void clear_value () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Statistic & from)
DataType_descriptor()
static const ::google::protobuf::EnumDescriptor* DataType_descriptor () inline static
References gz::msgs::Statistic_DataType_descriptor().
DataType_IsValid()
static bool DataType_IsValid (int value) inline static
References gz::msgs::Statistic_DataType_IsValid().
DataType_Name()
static const ::std::string& DataType_Name (DataType value) inline static
References gz::msgs::Statistic_DataType_Name().
DataType_Parse()
static bool DataType_Parse (const ::std::string & name, DataType * value) inline static
References gz::msgs::Statistic_DataType_Parse().
default_instance()
static const Statistic& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Statistic::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by Statistic::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Statistic* internal_default_instance () inline static
References gz::msgs::_Statistic_default_instance_.
Referenced by Statistic::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Statistic & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
name()
const ::std::string & name () const inline
Referenced by Statistic::set_allocated_name().
New() [1/2]
Statistic* New () const inline final
New() [2/2]
Statistic* New (::google::protobuf::Arena * arena) const inline final
operator=()
Statistic& operator= (const Statistic & from) inline
release_header()
gz::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References Statistic::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Statistic::name().
set_name() [1/3]
void set_name (const ::std::string & value) inline
References Statistic::value().
set_name() [2/3]
void set_name (const char * value) inline
References Statistic::value().
set_name() [3/3]
void set_name (const char * value, size_t size) inline
References Statistic::value().
set_type()
void set_type (::gz::msgs::Statistic_DataType value) inline
References Statistic::value().
set_value()
void set_value (double value) inline
References Statistic::value().
Swap()
void Swap (Statistic * other)
type()
gz::msgs::Statistic_DataType type () const inline
value()
double value () const inline
Referenced by Statistic::set_name(), Statistic::set_type(), and Statistic::set_value().
Member Data Documentation
AVERAGE
const DataType AVERAGE static
Initial value:
=
    Statistic_DataType_AVERAGE
DataType_ARRAYSIZE
const int DataType_ARRAYSIZE static
Initial value:
=
    Statistic_DataType_DataType_ARRAYSIZE
DataType_MAX
const DataType DataType_MAX static
Initial value:
=
    Statistic_DataType_DataType_MAX
DataType_MIN
const DataType DataType_MIN static
Initial value:
=
    Statistic_DataType_DataType_MIN
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 3 static
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
kValueFieldNumber
const int kValueFieldNumber = 4 static
MAX_ABS_VALUE
const DataType MAX_ABS_VALUE static
Initial value:
=
    Statistic_DataType_MAX_ABS_VALUE
MAXIMUM
const DataType MAXIMUM static
Initial value:
=
    Statistic_DataType_MAXIMUM
MINIMUM
const DataType MINIMUM static
Initial value:
=
    Statistic_DataType_MINIMUM
ROOT_MEAN_SQUARE
const DataType ROOT_MEAN_SQUARE static
Initial value:
=
    Statistic_DataType_ROOT_MEAN_SQUARE
SAMPLE_COUNT
const DataType SAMPLE_COUNT static
Initial value:
=
    Statistic_DataType_SAMPLE_COUNT
STDDEV
const DataType STDDEV static
Initial value:
=
    Statistic_DataType_STDDEV
UNINITIALIZED
const DataType UNINITIALIZED static
Initial value:
=
    Statistic_DataType_UNINITIALIZED
VARIANCE
const DataType VARIANCE static
Initial value:
=
    Statistic_DataType_VARIANCE
The documentation for this class was generated from the following file:
statistic.pb.h