Gazebo Msgs: SphericalCoordinates Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
SphericalCoordinates Class Reference
#include <spherical_coordinates.pb.h>
Public Types
typedef SphericalCoordinates_SurfaceModel SurfaceModel
Public Member Functions
SphericalCoordinates ()
SphericalCoordinates (const SphericalCoordinates &from)
virtual ~SphericalCoordinates ()
size_t ByteSizeLong () const final
void Clear () final
void clear_elevation ()
void clear_entity ()
void clear_header ()
void clear_heading_deg ()
void clear_latitude_deg ()
void clear_longitude_deg ()
void clear_surface_axis_equatorial ()
void clear_surface_axis_polar ()
void clear_surface_model ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SphericalCoordinates &from)
double elevation () const
const ::gz::msgs::Entity & entity () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_entity () const
bool has_header () const
const ::gz::msgs::Header & header () const
double heading_deg () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
double latitude_deg () const
double longitude_deg () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const SphericalCoordinates &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Entity * mutable_entity ()
::gz::msgs::Header * mutable_header ()
SphericalCoordinates * New () const final
SphericalCoordinates * New (::google::protobuf::Arena *arena) const final
SphericalCoordinates & operator= (const SphericalCoordinates &from)
::gz::msgs::Entity * release_entity ()
::gz::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_entity (::gz::msgs::Entity *entity)
void set_allocated_header (::gz::msgs::Header *header)
void set_elevation (double value)
void set_heading_deg (double value)
void set_latitude_deg (double value)
void set_longitude_deg (double value)
void set_surface_axis_equatorial (double value)
void set_surface_axis_polar (double value)
void set_surface_model (::gz::msgs::SphericalCoordinates_SurfaceModel value)
double surface_axis_equatorial () const
double surface_axis_polar () const
::gz::msgs::SphericalCoordinates_SurfaceModel surface_model () const
void Swap (SphericalCoordinates *other)
Static Public Member Functions
static const SphericalCoordinates & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const SphericalCoordinates * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * SurfaceModel_descriptor ()
static bool SurfaceModel_IsValid (int value)
static const ::std::string & SurfaceModel_Name (SurfaceModel value)
static bool SurfaceModel_Parse (const ::std::string &name, SurfaceModel *value)
Static Public Attributes
static const SurfaceModel CUSTOM_SURFACE
static const SurfaceModel EARTH_WGS84
static const int kElevationFieldNumber = 5
static const int kEntityFieldNumber = 7
static const int kHeaderFieldNumber = 1
static const int kHeadingDegFieldNumber = 6
static constexpr int kIndexInFileMessages
static const int kLatitudeDegFieldNumber = 3
static const int kLongitudeDegFieldNumber = 4
static const int kSurfaceAxisEquatorialFieldNumber = 8
static const int kSurfaceAxisPolarFieldNumber = 9
static const int kSurfaceModelFieldNumber = 2
static const SurfaceModel MOON_SCS
static const int SurfaceModel_ARRAYSIZE
static const SurfaceModel SurfaceModel_MAX
static const SurfaceModel SurfaceModel_MIN
Member Typedef Documentation
SurfaceModel
typedef SphericalCoordinates_SurfaceModel SurfaceModel
Constructor & Destructor Documentation
SphericalCoordinates() [1/2]
SphericalCoordinates ()
~SphericalCoordinates()
virtual ~SphericalCoordinates () virtual
SphericalCoordinates() [2/2]
SphericalCoordinates (const SphericalCoordinates & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_elevation()
void clear_elevation () inline
clear_entity()
void clear_entity ()
clear_header()
void clear_header ()
clear_heading_deg()
void clear_heading_deg () inline
clear_latitude_deg()
void clear_latitude_deg () inline
clear_longitude_deg()
void clear_longitude_deg () inline
clear_surface_axis_equatorial()
void clear_surface_axis_equatorial () inline
clear_surface_axis_polar()
void clear_surface_axis_polar () inline
clear_surface_model()
void clear_surface_model () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const SphericalCoordinates & from)
default_instance()
static const SphericalCoordinates& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
elevation()
double elevation () const inline
entity()
const ::gz::msgs::Entity & entity () const inline
References gz::msgs::_Entity_default_instance_.
Referenced by SphericalCoordinates::set_allocated_entity().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_entity()
bool has_entity () const inline
References SphericalCoordinates::internal_default_instance().
has_header()
bool has_header () const inline
References SphericalCoordinates::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by SphericalCoordinates::set_allocated_header().
heading_deg()
double heading_deg () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const SphericalCoordinates* internal_default_instance () inline static
References gz::msgs::_SphericalCoordinates_default_instance_.
Referenced by SphericalCoordinates::has_entity(), and SphericalCoordinates::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
latitude_deg()
double latitude_deg () const inline
longitude_deg()
double longitude_deg () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const SphericalCoordinates & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_entity()
gz::msgs::Entity * mutable_entity () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
New() [1/2]
SphericalCoordinates* New () const inline final
New() [2/2]
SphericalCoordinates* New (::google::protobuf::Arena * arena) const inline final
operator=()
SphericalCoordinates& operator= (const SphericalCoordinates & from) inline
release_entity()
gz::msgs::Entity * release_entity () inline
release_header()
gz::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_entity()
void set_allocated_entity (::gz::msgs::Entity * entity) inline
References SphericalCoordinates::entity().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References SphericalCoordinates::header().
set_elevation()
void set_elevation (double value) inline
set_heading_deg()
void set_heading_deg (double value) inline
set_latitude_deg()
void set_latitude_deg (double value) inline
set_longitude_deg()
void set_longitude_deg (double value) inline
set_surface_axis_equatorial()
void set_surface_axis_equatorial (double value) inline
set_surface_axis_polar()
void set_surface_axis_polar (double value) inline
set_surface_model()
void set_surface_model (::gz::msgs::SphericalCoordinates_SurfaceModel value) inline
surface_axis_equatorial()
double surface_axis_equatorial () const inline
surface_axis_polar()
double surface_axis_polar () const inline
surface_model()
gz::msgs::SphericalCoordinates_SurfaceModel surface_model () const inline
SurfaceModel_descriptor()
static const ::google::protobuf::EnumDescriptor* SurfaceModel_descriptor () inline static
References gz::msgs::SphericalCoordinates_SurfaceModel_descriptor().
SurfaceModel_IsValid()
static bool SurfaceModel_IsValid (int value) inline static
References gz::msgs::SphericalCoordinates_SurfaceModel_IsValid().
SurfaceModel_Name()
static const ::std::string& SurfaceModel_Name (SurfaceModel value) inline static
References gz::msgs::SphericalCoordinates_SurfaceModel_Name().
SurfaceModel_Parse()
static bool SurfaceModel_Parse (const ::std::string & name, SurfaceModel * value) inline static
References gz::msgs::SphericalCoordinates_SurfaceModel_Parse().
Swap()
void Swap (SphericalCoordinates * other)
Member Data Documentation
CUSTOM_SURFACE
const SurfaceModel CUSTOM_SURFACE static
Initial value:
=
    SphericalCoordinates_SurfaceModel_CUSTOM_SURFACE
EARTH_WGS84
const SurfaceModel EARTH_WGS84 static
Initial value:
=
    SphericalCoordinates_SurfaceModel_EARTH_WGS84
kElevationFieldNumber
const int kElevationFieldNumber = 5 static
kEntityFieldNumber
const int kEntityFieldNumber = 7 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHeadingDegFieldNumber
const int kHeadingDegFieldNumber = 6 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLatitudeDegFieldNumber
const int kLatitudeDegFieldNumber = 3 static
kLongitudeDegFieldNumber
const int kLongitudeDegFieldNumber = 4 static
kSurfaceAxisEquatorialFieldNumber
const int kSurfaceAxisEquatorialFieldNumber = 8 static
kSurfaceAxisPolarFieldNumber
const int kSurfaceAxisPolarFieldNumber = 9 static
kSurfaceModelFieldNumber
const int kSurfaceModelFieldNumber = 2 static
MOON_SCS
const SurfaceModel MOON_SCS static
Initial value:
=
    SphericalCoordinates_SurfaceModel_MOON_SCS
SurfaceModel_ARRAYSIZE
const int SurfaceModel_ARRAYSIZE static
Initial value:
=
    SphericalCoordinates_SurfaceModel_SurfaceModel_ARRAYSIZE
SurfaceModel_MAX
const SurfaceModel SurfaceModel_MAX static
Initial value:
=
    SphericalCoordinates_SurfaceModel_SurfaceModel_MAX
SurfaceModel_MIN
const SurfaceModel SurfaceModel_MIN static
Initial value:
=
    SphericalCoordinates_SurfaceModel_SurfaceModel_MIN
The documentation for this class was generated from the following file:
spherical_coordinates.pb.h