Gazebo Msgs: DVLTrackingTarget Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
DVLTrackingTarget Class Reference
#include <dvl_tracking_target.pb.h>
Public Types
typedef DVLTrackingTarget_TargetType TargetType
Public Member Functions
DVLTrackingTarget ()
DVLTrackingTarget (const DVLTrackingTarget &from)
virtual ~DVLTrackingTarget ()
size_t ByteSizeLong () const final
void Clear () final
void clear_position ()
void clear_range ()
void clear_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const DVLTrackingTarget &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_position () const
bool has_range () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const DVLTrackingTarget &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::DVLKinematicEstimate * mutable_position ()
::gz::msgs::DVLRangeEstimate * mutable_range ()
DVLTrackingTarget * New () const final
DVLTrackingTarget * New (::google::protobuf::Arena *arena) const final
DVLTrackingTarget & operator= (const DVLTrackingTarget &from)
const ::gz::msgs::DVLKinematicEstimate & position () const
const ::gz::msgs::DVLRangeEstimate & range () const
::gz::msgs::DVLKinematicEstimate * release_position ()
::gz::msgs::DVLRangeEstimate * release_range ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_position (::gz::msgs::DVLKinematicEstimate *position)
void set_allocated_range (::gz::msgs::DVLRangeEstimate *range)
void set_type (::gz::msgs::DVLTrackingTarget_TargetType value)
void Swap (DVLTrackingTarget *other)
::gz::msgs::DVLTrackingTarget_TargetType type () const
Static Public Member Functions
static const DVLTrackingTarget & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const DVLTrackingTarget * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * TargetType_descriptor ()
static bool TargetType_IsValid (int value)
static const ::std::string & TargetType_Name (TargetType value)
static bool TargetType_Parse (const ::std::string &name, TargetType *value)
Static Public Attributes
static const TargetType DVL_TARGET_BOTTOM
static const TargetType DVL_TARGET_UNSPECIFIED
static const TargetType DVL_TARGET_WATER_MASS
static constexpr int kIndexInFileMessages
static const int kPositionFieldNumber = 3
static const int kRangeFieldNumber = 2
static const int kTypeFieldNumber = 1
static const int TargetType_ARRAYSIZE
static const TargetType TargetType_MAX
static const TargetType TargetType_MIN
Member Typedef Documentation
TargetType
typedef DVLTrackingTarget_TargetType TargetType
Constructor & Destructor Documentation
DVLTrackingTarget() [1/2]
DVLTrackingTarget ()
~DVLTrackingTarget()
virtual ~DVLTrackingTarget () virtual
DVLTrackingTarget() [2/2]
DVLTrackingTarget (const DVLTrackingTarget & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_position()
void clear_position ()
clear_range()
void clear_range ()
clear_type()
void clear_type () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const DVLTrackingTarget & from)
default_instance()
static const DVLTrackingTarget& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_position()
bool has_position () const inline
References DVLTrackingTarget::internal_default_instance().
has_range()
bool has_range () const inline
References DVLTrackingTarget::internal_default_instance().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const DVLTrackingTarget* internal_default_instance () inline static
References gz::msgs::_DVLTrackingTarget_default_instance_.
Referenced by DVLTrackingTarget::has_position(), and DVLTrackingTarget::has_range().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const DVLTrackingTarget & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_position()
gz::msgs::DVLKinematicEstimate * mutable_position () inline
mutable_range()
gz::msgs::DVLRangeEstimate * mutable_range () inline
New() [1/2]
DVLTrackingTarget* New () const inline final
New() [2/2]
DVLTrackingTarget* New (::google::protobuf::Arena * arena) const inline final
operator=()
DVLTrackingTarget& operator= (const DVLTrackingTarget & from) inline
position()
const ::gz::msgs::DVLKinematicEstimate & position () const inline
References gz::msgs::_DVLKinematicEstimate_default_instance_.
Referenced by DVLTrackingTarget::set_allocated_position().
range()
const ::gz::msgs::DVLRangeEstimate & range () const inline
References gz::msgs::_DVLRangeEstimate_default_instance_.
Referenced by DVLTrackingTarget::set_allocated_range().
release_position()
gz::msgs::DVLKinematicEstimate * release_position () inline
release_range()
gz::msgs::DVLRangeEstimate * release_range () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_position()
void set_allocated_position (::gz::msgs::DVLKinematicEstimate * position) inline
References DVLTrackingTarget::position().
set_allocated_range()
void set_allocated_range (::gz::msgs::DVLRangeEstimate * range) inline
References DVLTrackingTarget::range().
set_type()
void set_type (::gz::msgs::DVLTrackingTarget_TargetType value) inline
Swap()
void Swap (DVLTrackingTarget * other)
TargetType_descriptor()
static const ::google::protobuf::EnumDescriptor* TargetType_descriptor () inline static
References gz::msgs::DVLTrackingTarget_TargetType_descriptor().
TargetType_IsValid()
static bool TargetType_IsValid (int value) inline static
References gz::msgs::DVLTrackingTarget_TargetType_IsValid().
TargetType_Name()
static const ::std::string& TargetType_Name (TargetType value) inline static
References gz::msgs::DVLTrackingTarget_TargetType_Name().
TargetType_Parse()
static bool TargetType_Parse (const ::std::string & name, TargetType * value) inline static
References gz::msgs::DVLTrackingTarget_TargetType_Parse().
type()
gz::msgs::DVLTrackingTarget_TargetType type () const inline
Member Data Documentation
DVL_TARGET_BOTTOM
const TargetType DVL_TARGET_BOTTOM static
Initial value:
=
    DVLTrackingTarget_TargetType_DVL_TARGET_BOTTOM
DVL_TARGET_UNSPECIFIED
const TargetType DVL_TARGET_UNSPECIFIED static
Initial value:
=
    DVLTrackingTarget_TargetType_DVL_TARGET_UNSPECIFIED
DVL_TARGET_WATER_MASS
const TargetType DVL_TARGET_WATER_MASS static
Initial value:
=
    DVLTrackingTarget_TargetType_DVL_TARGET_WATER_MASS
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kPositionFieldNumber
const int kPositionFieldNumber = 3 static
kRangeFieldNumber
const int kRangeFieldNumber = 2 static
kTypeFieldNumber
const int kTypeFieldNumber = 1 static
TargetType_ARRAYSIZE
const int TargetType_ARRAYSIZE static
Initial value:
=
    DVLTrackingTarget_TargetType_TargetType_ARRAYSIZE
TargetType_MAX
const TargetType TargetType_MAX static
Initial value:
=
    DVLTrackingTarget_TargetType_TargetType_MAX
TargetType_MIN
const TargetType TargetType_MIN static
Initial value:
=
    DVLTrackingTarget_TargetType_TargetType_MIN
The documentation for this class was generated from the following file:
dvl_tracking_target.pb.h