Gazebo Msgs: RestLogout Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
RestLogout Class Reference
#include <rest_logout.pb.h>
Public Member Functions
RestLogout ()
RestLogout (const RestLogout &from)
virtual ~RestLogout ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_id ()
void clear_url ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const RestLogout &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const RestLogout &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Header * mutable_header ()
::std::string * mutable_url ()
RestLogout * New () const final
RestLogout * New (::google::protobuf::Arena *arena) const final
RestLogout & operator= (const RestLogout &from)
::gz::msgs::Header * release_header ()
::std::string * release_url ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_url (::std::string *url)
void set_id (::google::protobuf::uint32 value)
void set_url (const ::std::string &value)
void set_url (const char *value)
void set_url (const char *value, size_t size)
void Swap (RestLogout *other)
const ::std::string & url () const
Static Public Member Functions
static const RestLogout & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const RestLogout * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kUrlFieldNumber = 3
Constructor & Destructor Documentation
RestLogout() [1/2]
RestLogout ()
~RestLogout()
virtual ~RestLogout () virtual
RestLogout() [2/2]
RestLogout (const RestLogout & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_url()
void clear_url () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const RestLogout & from)
default_instance()
static const RestLogout& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References RestLogout::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by RestLogout::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const RestLogout* internal_default_instance () inline static
References gz::msgs::_RestLogout_default_instance_.
Referenced by RestLogout::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const RestLogout & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_url()
std::string * mutable_url () inline
New() [1/2]
RestLogout* New () const inline final
New() [2/2]
RestLogout* New (::google::protobuf::Arena * arena) const inline final
operator=()
RestLogout& operator= (const RestLogout & from) inline
release_header()
gz::msgs::Header * release_header () inline
release_url()
std::string * release_url () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References RestLogout::header().
set_allocated_url()
void set_allocated_url (::std::string * url) inline
References RestLogout::url().
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_url() [1/3]
void set_url (const ::std::string & value) inline
set_url() [2/3]
void set_url (const char * value) inline
set_url() [3/3]
void set_url (const char * value, size_t size) inline
Swap()
void Swap (RestLogout * other)
url()
const ::std::string & url () const inline
Referenced by RestLogout::set_allocated_url().
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kUrlFieldNumber
const int kUrlFieldNumber = 3 static
The documentation for this class was generated from the following file:
rest_logout.pb.h