Gazebo Msgs: NavSat Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
NavSat Class Reference
#include <navsat.pb.h>
Public Member Functions
NavSat ()
NavSat (const NavSat &from)
virtual ~NavSat ()
double altitude () const
size_t ByteSizeLong () const final
void Clear () final
void clear_altitude ()
void clear_frame_id ()
void clear_header ()
void clear_latitude_deg ()
void clear_longitude_deg ()
void clear_velocity_east ()
void clear_velocity_north ()
void clear_velocity_up ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const NavSat &from)
const ::std::string & frame_id () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
double latitude_deg () const
double longitude_deg () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const NavSat &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_frame_id ()
::gz::msgs::Header * mutable_header ()
NavSat * New () const final
NavSat * New (::google::protobuf::Arena *arena) const final
NavSat & operator= (const NavSat &from)
::std::string * release_frame_id ()
::gz::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_frame_id (::std::string *frame_id)
void set_allocated_header (::gz::msgs::Header *header)
void set_altitude (double value)
void set_frame_id (const ::std::string &value)
void set_frame_id (const char *value)
void set_frame_id (const char *value, size_t size)
void set_latitude_deg (double value)
void set_longitude_deg (double value)
void set_velocity_east (double value)
void set_velocity_north (double value)
void set_velocity_up (double value)
void Swap (NavSat *other)
double velocity_east () const
double velocity_north () const
double velocity_up () const
Static Public Member Functions
static const NavSat & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const NavSat * internal_default_instance ()
Static Public Attributes
static const int kAltitudeFieldNumber = 4
static const int kFrameIdFieldNumber = 8
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kLatitudeDegFieldNumber = 2
static const int kLongitudeDegFieldNumber = 3
static const int kVelocityEastFieldNumber = 5
static const int kVelocityNorthFieldNumber = 6
static const int kVelocityUpFieldNumber = 7
Constructor & Destructor Documentation
NavSat() [1/2]
NavSat ()
~NavSat()
virtual ~NavSat () virtual
NavSat() [2/2]
NavSat (const NavSat & from)
Member Function Documentation
altitude()
double altitude () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_altitude()
void clear_altitude () inline
clear_frame_id()
void clear_frame_id () inline
clear_header()
void clear_header ()
clear_latitude_deg()
void clear_latitude_deg () inline
clear_longitude_deg()
void clear_longitude_deg () inline
clear_velocity_east()
void clear_velocity_east () inline
clear_velocity_north()
void clear_velocity_north () inline
clear_velocity_up()
void clear_velocity_up () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const NavSat & from)
default_instance()
static const NavSat& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
frame_id()
const ::std::string & frame_id () const inline
Referenced by NavSat::set_allocated_frame_id().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References NavSat::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by NavSat::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const NavSat* internal_default_instance () inline static
References gz::msgs::_NavSat_default_instance_.
Referenced by NavSat::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
latitude_deg()
double latitude_deg () const inline
longitude_deg()
double longitude_deg () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const NavSat & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_frame_id()
std::string * mutable_frame_id () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
New() [1/2]
NavSat* New () const inline final
New() [2/2]
NavSat* New (::google::protobuf::Arena * arena) const inline final
operator=()
NavSat& operator= (const NavSat & from) inline
release_frame_id()
std::string * release_frame_id () inline
release_header()
gz::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_frame_id()
void set_allocated_frame_id (::std::string * frame_id) inline
References NavSat::frame_id().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References NavSat::header().
set_altitude()
void set_altitude (double value) inline
set_frame_id() [1/3]
void set_frame_id (const ::std::string & value) inline
set_frame_id() [2/3]
void set_frame_id (const char * value) inline
set_frame_id() [3/3]
void set_frame_id (const char * value, size_t size) inline
set_latitude_deg()
void set_latitude_deg (double value) inline
set_longitude_deg()
void set_longitude_deg (double value) inline
set_velocity_east()
void set_velocity_east (double value) inline
set_velocity_north()
void set_velocity_north (double value) inline
set_velocity_up()
void set_velocity_up (double value) inline
Swap()
void Swap (NavSat * other)
velocity_east()
double velocity_east () const inline
velocity_north()
double velocity_north () const inline
velocity_up()
double velocity_up () const inline
Member Data Documentation
kAltitudeFieldNumber
const int kAltitudeFieldNumber = 4 static
kFrameIdFieldNumber
const int kFrameIdFieldNumber = 8 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLatitudeDegFieldNumber
const int kLatitudeDegFieldNumber = 2 static
kLongitudeDegFieldNumber
const int kLongitudeDegFieldNumber = 3 static
kVelocityEastFieldNumber
const int kVelocityEastFieldNumber = 5 static
kVelocityNorthFieldNumber
const int kVelocityNorthFieldNumber = 6 static
kVelocityUpFieldNumber
const int kVelocityUpFieldNumber = 7 static
The documentation for this class was generated from the following file:
navsat.pb.h