Gazebo Msgs: CameraInfo_Distortion Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
CameraInfo_Distortion Class Reference
#include <camera_info.pb.h>
Public Types
typedef CameraInfo_Distortion_DistortionModelType DistortionModelType
Public Member Functions
CameraInfo_Distortion ()
CameraInfo_Distortion (const CameraInfo_Distortion &from)
virtual ~CameraInfo_Distortion ()
void add_k (double value)
size_t ByteSizeLong () const final
void Clear () final
void clear_k ()
void clear_model ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const CameraInfo_Distortion &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::google::protobuf::RepeatedField< double > & k () const
double k (int index) const
int k_size () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const CameraInfo_Distortion &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::CameraInfo_Distortion_DistortionModelType model () const
::google::protobuf::RepeatedField< double > * mutable_k ()
CameraInfo_Distortion * New () const final
CameraInfo_Distortion * New (::google::protobuf::Arena *arena) const final
CameraInfo_Distortion & operator= (const CameraInfo_Distortion &from)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_k (int index, double value)
void set_model (::gz::msgs::CameraInfo_Distortion_DistortionModelType value)
void Swap (CameraInfo_Distortion *other)
Static Public Member Functions
static const CameraInfo_Distortion & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const ::google::protobuf::EnumDescriptor * DistortionModelType_descriptor ()
static bool DistortionModelType_IsValid (int value)
static const ::std::string & DistortionModelType_Name (DistortionModelType value)
static bool DistortionModelType_Parse (const ::std::string &name, DistortionModelType *value)
static void InitAsDefaultInstance ()
static const CameraInfo_Distortion * internal_default_instance ()
Static Public Attributes
static const int DistortionModelType_ARRAYSIZE
static const DistortionModelType DistortionModelType_MAX
static const DistortionModelType DistortionModelType_MIN
static const DistortionModelType EQUIDISTANT
static constexpr int kIndexInFileMessages
static const int kKFieldNumber = 2
static const int kModelFieldNumber = 1
static const DistortionModelType PLUMB_BOB
static const DistortionModelType RATIONAL_POLYNOMIAL
Member Typedef Documentation
DistortionModelType
typedef CameraInfo_Distortion_DistortionModelType DistortionModelType
Constructor & Destructor Documentation
CameraInfo_Distortion() [1/2]
CameraInfo_Distortion ()
~CameraInfo_Distortion()
virtual ~CameraInfo_Distortion () virtual
CameraInfo_Distortion() [2/2]
CameraInfo_Distortion (const CameraInfo_Distortion & from)
Member Function Documentation
add_k()
void add_k (double value) inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_k()
void clear_k () inline
clear_model()
void clear_model () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const CameraInfo_Distortion & from)
default_instance()
static const CameraInfo_Distortion& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
DistortionModelType_descriptor()
static const ::google::protobuf::EnumDescriptor* DistortionModelType_descriptor () inline static
References gz::msgs::CameraInfo_Distortion_DistortionModelType_descriptor().
DistortionModelType_IsValid()
static bool DistortionModelType_IsValid (int value) inline static
References gz::msgs::CameraInfo_Distortion_DistortionModelType_IsValid().
DistortionModelType_Name()
static const ::std::string& DistortionModelType_Name (DistortionModelType value) inline static
References gz::msgs::CameraInfo_Distortion_DistortionModelType_Name().
DistortionModelType_Parse()
static bool DistortionModelType_Parse (const ::std::string & name, DistortionModelType * value) inline static
References gz::msgs::CameraInfo_Distortion_DistortionModelType_Parse().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const CameraInfo_Distortion* internal_default_instance () inline static
References gz::msgs::_CameraInfo_Distortion_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
k() [1/2]
const ::google::protobuf::RepeatedField< double > & k () const inline
k() [2/2]
double k (int index) const inline
k_size()
int k_size () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const CameraInfo_Distortion & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
model()
gz::msgs::CameraInfo_Distortion_DistortionModelType model () const inline
mutable_k()
google::protobuf::RepeatedField< double > * mutable_k () inline
New() [1/2]
CameraInfo_Distortion* New () const inline final
New() [2/2]
CameraInfo_Distortion* New (::google::protobuf::Arena * arena) const inline final
operator=()
CameraInfo_Distortion& operator= (const CameraInfo_Distortion & from) inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_k()
void set_k (int index, double value) inline
set_model()
void set_model (::gz::msgs::CameraInfo_Distortion_DistortionModelType value) inline
Swap()
void Swap (CameraInfo_Distortion * other)
Member Data Documentation
DistortionModelType_ARRAYSIZE
const int DistortionModelType_ARRAYSIZE static
Initial value:
=
    CameraInfo_Distortion_DistortionModelType_DistortionModelType_ARRAYSIZE
DistortionModelType_MAX
const DistortionModelType DistortionModelType_MAX static
Initial value:
=
    CameraInfo_Distortion_DistortionModelType_DistortionModelType_MAX
DistortionModelType_MIN
const DistortionModelType DistortionModelType_MIN static
Initial value:
=
    CameraInfo_Distortion_DistortionModelType_DistortionModelType_MIN
EQUIDISTANT
const DistortionModelType EQUIDISTANT static
Initial value:
=
    CameraInfo_Distortion_DistortionModelType_EQUIDISTANT
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kKFieldNumber
const int kKFieldNumber = 2 static
kModelFieldNumber
const int kModelFieldNumber = 1 static
PLUMB_BOB
const DistortionModelType PLUMB_BOB static
Initial value:
=
    CameraInfo_Distortion_DistortionModelType_PLUMB_BOB
RATIONAL_POLYNOMIAL
const DistortionModelType RATIONAL_POLYNOMIAL static
Initial value:
=
    CameraInfo_Distortion_DistortionModelType_RATIONAL_POLYNOMIAL
The documentation for this class was generated from the following file:
camera_info.pb.h