Gazebo Msgs: PerformanceSensorMetrics Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
PerformanceSensorMetrics Class Reference
#include <performance_sensor_metrics.pb.h>
Public Member Functions
PerformanceSensorMetrics ()
PerformanceSensorMetrics (const PerformanceSensorMetrics &from)
virtual ~PerformanceSensorMetrics ()
size_t ByteSizeLong () const final
void Clear () final
void clear_fps_optional ()
void clear_name ()
void clear_nominal_update_rate ()
void clear_real_update_rate ()
void clear_sim_update_rate ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const PerformanceSensorMetrics &from)
const ::gz::msgs::Double & fps_optional () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_fps_optional () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const PerformanceSensorMetrics &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Double * mutable_fps_optional ()
::std::string * mutable_name ()
const ::std::string & name () const
PerformanceSensorMetrics * New () const final
PerformanceSensorMetrics * New (::google::protobuf::Arena *arena) const final
double nominal_update_rate () const
PerformanceSensorMetrics & operator= (const PerformanceSensorMetrics &from)
double real_update_rate () const
::gz::msgs::Double * release_fps_optional ()
::std::string * release_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_fps_optional (::gz::msgs::Double *fps_optional)
void set_allocated_name (::std::string *name)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_nominal_update_rate (double value)
void set_real_update_rate (double value)
void set_sim_update_rate (double value)
double sim_update_rate () const
void Swap (PerformanceSensorMetrics *other)
Static Public Member Functions
static const PerformanceSensorMetrics & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const PerformanceSensorMetrics * internal_default_instance ()
Static Public Attributes
static const int kFpsOptionalFieldNumber = 5
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 1
static const int kNominalUpdateRateFieldNumber = 4
static const int kRealUpdateRateFieldNumber = 2
static const int kSimUpdateRateFieldNumber = 3
Constructor & Destructor Documentation
PerformanceSensorMetrics() [1/2]
PerformanceSensorMetrics ()
~PerformanceSensorMetrics()
virtual ~PerformanceSensorMetrics () virtual
PerformanceSensorMetrics() [2/2]
PerformanceSensorMetrics (const PerformanceSensorMetrics & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_fps_optional()
void clear_fps_optional ()
clear_name()
void clear_name () inline
clear_nominal_update_rate()
void clear_nominal_update_rate () inline
clear_real_update_rate()
void clear_real_update_rate () inline
clear_sim_update_rate()
void clear_sim_update_rate () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const PerformanceSensorMetrics & from)
default_instance()
static const PerformanceSensorMetrics& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
fps_optional()
const ::gz::msgs::Double & fps_optional () const inline
References gz::msgs::_Double_default_instance_.
Referenced by PerformanceSensorMetrics::set_allocated_fps_optional().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_fps_optional()
bool has_fps_optional () const inline
References PerformanceSensorMetrics::internal_default_instance().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const PerformanceSensorMetrics* internal_default_instance () inline static
References gz::msgs::_PerformanceSensorMetrics_default_instance_.
Referenced by PerformanceSensorMetrics::has_fps_optional().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const PerformanceSensorMetrics & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_fps_optional()
gz::msgs::Double * mutable_fps_optional () inline
mutable_name()
std::string * mutable_name () inline
name()
const ::std::string & name () const inline
Referenced by PerformanceSensorMetrics::set_allocated_name().
New() [1/2]
PerformanceSensorMetrics* New () const inline final
New() [2/2]
PerformanceSensorMetrics* New (::google::protobuf::Arena * arena) const inline final
nominal_update_rate()
double nominal_update_rate () const inline
operator=()
PerformanceSensorMetrics& operator= (const PerformanceSensorMetrics & from) inline
real_update_rate()
double real_update_rate () const inline
release_fps_optional()
gz::msgs::Double * release_fps_optional () inline
release_name()
std::string * release_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_fps_optional()
void set_allocated_fps_optional (::gz::msgs::Double * fps_optional) inline
References PerformanceSensorMetrics::fps_optional().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References PerformanceSensorMetrics::name().
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_nominal_update_rate()
void set_nominal_update_rate (double value) inline
set_real_update_rate()
void set_real_update_rate (double value) inline
set_sim_update_rate()
void set_sim_update_rate (double value) inline
sim_update_rate()
double sim_update_rate () const inline
Swap()
void Swap (PerformanceSensorMetrics * other)
Member Data Documentation
kFpsOptionalFieldNumber
const int kFpsOptionalFieldNumber = 5 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 1 static
kNominalUpdateRateFieldNumber
const int kNominalUpdateRateFieldNumber = 4 static
kRealUpdateRateFieldNumber
const int kRealUpdateRateFieldNumber = 2 static
kSimUpdateRateFieldNumber
const int kSimUpdateRateFieldNumber = 3 static
The documentation for this class was generated from the following file:
performance_sensor_metrics.pb.h