Gazebo Msgs: FuelMetadata Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
FuelMetadata Class Reference
#include <fuel_metadata.pb.h>
Public Types
typedef FuelMetadata_Categories Categories
typedef FuelMetadata_Compatibility Compatibility
typedef FuelMetadata_Contact Contact
typedef FuelMetadata_Dependency Dependency
typedef FuelMetadata_Legal Legal
typedef FuelMetadata_Model Model
enum ResourceTypeCase { kModel = 1, kWorld = 2, RESOURCE_TYPE_NOT_SET = 0 }
typedef FuelMetadata_World World
Public Member Functions
FuelMetadata ()
FuelMetadata (const FuelMetadata &from)
virtual ~FuelMetadata ()
::gz::msgs::FuelMetadata_Contact * add_authors ()
::gz::msgs::FuelMetadata_Compatibility * add_compatibilities ()
::gz::msgs::FuelMetadata_Dependency * add_dependencies ()
::std::string * add_tags ()
void add_tags (const ::std::string &value)
void add_tags (const char *value)
void add_tags (const char *value, size_t size)
const ::google::protobuf::Map< ::std::string, ::std::string > & annotations () const
int annotations_size () const
const ::google::protobuf::RepeatedPtrField< ::gz::msgs::FuelMetadata_Contact > & authors () const
const ::gz::msgs::FuelMetadata_Contact & authors (int index) const
int authors_size () const
size_t ByteSizeLong () const final
const ::gz::msgs::FuelMetadata_Categories & categories () const
void Clear () final
void clear_annotations ()
void clear_authors ()
void clear_categories ()
void clear_compatibilities ()
void clear_dependencies ()
void clear_description ()
void clear_legal ()
void clear_model ()
void clear_name ()
void clear_resource_type ()
void clear_tags ()
void clear_version ()
void clear_world ()
const ::google::protobuf::RepeatedPtrField< ::gz::msgs::FuelMetadata_Compatibility > & compatibilities () const
const ::gz::msgs::FuelMetadata_Compatibility & compatibilities (int index) const
int compatibilities_size () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const FuelMetadata &from)
const ::google::protobuf::RepeatedPtrField< ::gz::msgs::FuelMetadata_Dependency > & dependencies () const
const ::gz::msgs::FuelMetadata_Dependency & dependencies (int index) const
int dependencies_size () const
const ::std::string & description () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_categories () const
bool has_legal () const
bool has_model () const
bool has_world () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::gz::msgs::FuelMetadata_Legal & legal () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const FuelMetadata &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::gz::msgs::FuelMetadata_Model & model () const
::google::protobuf::Map< ::std::string, ::std::string > * mutable_annotations ()
::google::protobuf::RepeatedPtrField< ::gz::msgs::FuelMetadata_Contact > * mutable_authors ()
::gz::msgs::FuelMetadata_Contact * mutable_authors (int index)
::gz::msgs::FuelMetadata_Categories * mutable_categories ()
::google::protobuf::RepeatedPtrField< ::gz::msgs::FuelMetadata_Compatibility > * mutable_compatibilities ()
::gz::msgs::FuelMetadata_Compatibility * mutable_compatibilities (int index)
::google::protobuf::RepeatedPtrField< ::gz::msgs::FuelMetadata_Dependency > * mutable_dependencies ()
::gz::msgs::FuelMetadata_Dependency * mutable_dependencies (int index)
::std::string * mutable_description ()
::gz::msgs::FuelMetadata_Legal * mutable_legal ()
::gz::msgs::FuelMetadata_Model * mutable_model ()
::std::string * mutable_name ()
::google::protobuf::RepeatedPtrField< ::std::string > * mutable_tags ()
::std::string * mutable_tags (int index)
::gz::msgs::FuelMetadata_World * mutable_world ()
const ::std::string & name () const
FuelMetadata * New () const final
FuelMetadata * New (::google::protobuf::Arena *arena) const final
FuelMetadata & operator= (const FuelMetadata &from)
::gz::msgs::FuelMetadata_Categories * release_categories ()
::std::string * release_description ()
::gz::msgs::FuelMetadata_Legal * release_legal ()
::gz::msgs::FuelMetadata_Model * release_model ()
::std::string * release_name ()
::gz::msgs::FuelMetadata_World * release_world ()
ResourceTypeCase resource_type_case () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_categories (::gz::msgs::FuelMetadata_Categories *categories)
void set_allocated_description (::std::string *description)
void set_allocated_legal (::gz::msgs::FuelMetadata_Legal *legal)
void set_allocated_model (::gz::msgs::FuelMetadata_Model *model)
void set_allocated_name (::std::string *name)
void set_allocated_world (::gz::msgs::FuelMetadata_World *world)
void set_description (const ::std::string &value)
void set_description (const char *value)
void set_description (const char *value, size_t size)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_tags (int index, const ::std::string &value)
void set_tags (int index, const char *value)
void set_tags (int index, const char *value, size_t size)
void set_version (::google::protobuf::int32 value)
void Swap (FuelMetadata *other)
const ::google::protobuf::RepeatedPtrField< ::std::string > & tags () const
const ::std::string & tags (int index) const
int tags_size () const
::google::protobuf::int32 version () const
const ::gz::msgs::FuelMetadata_World & world () const
Static Public Member Functions
static const FuelMetadata & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const FuelMetadata * internal_default_instance ()
Static Public Attributes
static const int kAnnotationsFieldNumber = 9
static const int kAuthorsFieldNumber = 6
static const int kCategoriesFieldNumber = 12
static const int kCompatibilitiesFieldNumber = 11
static const int kDependenciesFieldNumber = 10
static const int kDescriptionFieldNumber = 4
static constexpr int kIndexInFileMessages
static const int kLegalFieldNumber = 7
static const int kModelFieldNumber = 1
static const int kNameFieldNumber = 3
static const int kTagsFieldNumber = 8
static const int kVersionFieldNumber = 5
static const int kWorldFieldNumber = 2
Member Typedef Documentation
Categories
typedef FuelMetadata_Categories Categories
Compatibility
typedef FuelMetadata_Compatibility Compatibility
Contact
typedef FuelMetadata_Contact Contact
Dependency
typedef FuelMetadata_Dependency Dependency
Legal
typedef FuelMetadata_Legal Legal
Model
typedef FuelMetadata_Model Model
World
typedef FuelMetadata_World World
Member Enumeration Documentation
ResourceTypeCase
enum ResourceTypeCase
Enumerator
kModel
kWorld
RESOURCE_TYPE_NOT_SET
Constructor & Destructor Documentation
FuelMetadata() [1/2]
FuelMetadata ()
~FuelMetadata()
virtual ~FuelMetadata () virtual
FuelMetadata() [2/2]
FuelMetadata (const FuelMetadata & from)
Member Function Documentation
add_authors()
gz::msgs::FuelMetadata_Contact * add_authors () inline
add_compatibilities()
gz::msgs::FuelMetadata_Compatibility * add_compatibilities () inline
add_dependencies()
gz::msgs::FuelMetadata_Dependency * add_dependencies () inline
add_tags() [1/4]
std::string * add_tags () inline
add_tags() [2/4]
void add_tags (const ::std::string & value) inline
add_tags() [3/4]
void add_tags (const char * value) inline
add_tags() [4/4]
void add_tags (const char * value, size_t size) inline
annotations()
const ::google::protobuf::Map<::std::string,::std::string > & annotations () const inline
annotations_size()
int annotations_size () const inline
authors() [1/2]
const ::google::protobuf::RepeatedPtrField<::gz::msgs::FuelMetadata_Contact > & authors () const inline
authors() [2/2]
const ::gz::msgs::FuelMetadata_Contact & authors (int index) const inline
authors_size()
int authors_size () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
categories()
const ::gz::msgs::FuelMetadata_Categories & categories () const inline
References gz::msgs::_FuelMetadata_Categories_default_instance_.
Referenced by FuelMetadata::set_allocated_categories().
Clear()
void Clear () final
clear_annotations()
void clear_annotations () inline
clear_authors()
void clear_authors () inline
clear_categories()
void clear_categories () inline
clear_compatibilities()
void clear_compatibilities () inline
clear_dependencies()
void clear_dependencies () inline
clear_description()
void clear_description () inline
clear_legal()
void clear_legal () inline
clear_model()
void clear_model () inline
References FuelMetadata::has_model().
clear_name()
void clear_name () inline
clear_resource_type()
void clear_resource_type ()
Referenced by FuelMetadata::mutable_model(), and FuelMetadata::mutable_world().
clear_tags()
void clear_tags () inline
clear_version()
void clear_version () inline
clear_world()
void clear_world () inline
References FuelMetadata::has_world().
compatibilities() [1/2]
const ::google::protobuf::RepeatedPtrField<::gz::msgs::FuelMetadata_Compatibility > & compatibilities () const inline
compatibilities() [2/2]
const ::gz::msgs::FuelMetadata_Compatibility & compatibilities (int index) const inline
compatibilities_size()
int compatibilities_size () const inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const FuelMetadata & from)
default_instance()
static const FuelMetadata& default_instance () static
dependencies() [1/2]
const ::google::protobuf::RepeatedPtrField<::gz::msgs::FuelMetadata_Dependency > & dependencies () const inline
dependencies() [2/2]
const ::gz::msgs::FuelMetadata_Dependency & dependencies (int index) const inline
dependencies_size()
int dependencies_size () const inline
description()
const ::std::string & description () const inline
Referenced by FuelMetadata::set_allocated_description().
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_categories()
bool has_categories () const inline
References FuelMetadata::internal_default_instance().
has_legal()
bool has_legal () const inline
References FuelMetadata::internal_default_instance().
has_model()
bool has_model () const inline
References FuelMetadata::kModel, and FuelMetadata::resource_type_case().
Referenced by FuelMetadata::clear_model(), FuelMetadata::model(), FuelMetadata::mutable_model(), and FuelMetadata::release_model().
has_world()
bool has_world () const inline
References FuelMetadata::kWorld, and FuelMetadata::resource_type_case().
Referenced by FuelMetadata::clear_world(), FuelMetadata::mutable_world(), FuelMetadata::release_world(), and FuelMetadata::world().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const FuelMetadata* internal_default_instance () inline static
References gz::msgs::_FuelMetadata_default_instance_.
Referenced by FuelMetadata::has_categories(), and FuelMetadata::has_legal().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
legal()
const ::gz::msgs::FuelMetadata_Legal & legal () const inline
References gz::msgs::_FuelMetadata_Legal_default_instance_.
Referenced by FuelMetadata::set_allocated_legal().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const FuelMetadata & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
model()
const ::gz::msgs::FuelMetadata_Model & model () const inline
References gz::msgs::_FuelMetadata_Model_default_instance_, and FuelMetadata::has_model().
mutable_annotations()
google::protobuf::Map<::std::string,::std::string > * mutable_annotations () inline
mutable_authors() [1/2]
google::protobuf::RepeatedPtrField<::gz::msgs::FuelMetadata_Contact > * mutable_authors () inline
mutable_authors() [2/2]
gz::msgs::FuelMetadata_Contact * mutable_authors (int index) inline
mutable_categories()
gz::msgs::FuelMetadata_Categories * mutable_categories () inline
mutable_compatibilities() [1/2]
google::protobuf::RepeatedPtrField<::gz::msgs::FuelMetadata_Compatibility > * mutable_compatibilities () inline
mutable_compatibilities() [2/2]
gz::msgs::FuelMetadata_Compatibility * mutable_compatibilities (int index) inline
mutable_dependencies() [1/2]
google::protobuf::RepeatedPtrField<::gz::msgs::FuelMetadata_Dependency > * mutable_dependencies () inline
mutable_dependencies() [2/2]
gz::msgs::FuelMetadata_Dependency * mutable_dependencies (int index) inline
mutable_description()
std::string * mutable_description () inline
mutable_legal()
gz::msgs::FuelMetadata_Legal * mutable_legal () inline
mutable_model()
gz::msgs::FuelMetadata_Model * mutable_model () inline
References FuelMetadata::clear_resource_type(), and FuelMetadata::has_model().
mutable_name()
std::string * mutable_name () inline
mutable_tags() [1/2]
google::protobuf::RepeatedPtrField<::std::string > * mutable_tags () inline
mutable_tags() [2/2]
std::string * mutable_tags (int index) inline
mutable_world()
gz::msgs::FuelMetadata_World * mutable_world () inline
References FuelMetadata::clear_resource_type(), and FuelMetadata::has_world().
name()
const ::std::string & name () const inline
Referenced by FuelMetadata::set_allocated_name().
New() [1/2]
FuelMetadata* New () const inline final
New() [2/2]
FuelMetadata* New (::google::protobuf::Arena * arena) const inline final
operator=()
FuelMetadata& operator= (const FuelMetadata & from) inline
release_categories()
gz::msgs::FuelMetadata_Categories * release_categories () inline
release_description()
std::string * release_description () inline
release_legal()
gz::msgs::FuelMetadata_Legal * release_legal () inline
release_model()
gz::msgs::FuelMetadata_Model * release_model () inline
References FuelMetadata::has_model().
release_name()
std::string * release_name () inline
release_world()
gz::msgs::FuelMetadata_World * release_world () inline
References FuelMetadata::has_world().
resource_type_case()
FuelMetadata::ResourceTypeCase resource_type_case () const inline
Referenced by FuelMetadata::has_model(), and FuelMetadata::has_world().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_categories()
void set_allocated_categories (::gz::msgs::FuelMetadata_Categories * categories) inline
References FuelMetadata::categories().
set_allocated_description()
void set_allocated_description (::std::string * description) inline
References FuelMetadata::description().
set_allocated_legal()
void set_allocated_legal (::gz::msgs::FuelMetadata_Legal * legal) inline
References FuelMetadata::legal().
set_allocated_model()
void set_allocated_model (::gz::msgs::FuelMetadata_Model * model)
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References FuelMetadata::name().
set_allocated_world()
void set_allocated_world (::gz::msgs::FuelMetadata_World * world)
set_description() [1/3]
void set_description (const ::std::string & value) inline
set_description() [2/3]
void set_description (const char * value) inline
set_description() [3/3]
void set_description (const char * value, size_t size) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_tags() [1/3]
void set_tags (int index, const ::std::string & value) inline
set_tags() [2/3]
void set_tags (int index, const char * value) inline
set_tags() [3/3]
void set_tags (int index, const char * value, size_t size) inline
set_version()
void set_version (::google::protobuf::int32 value) inline
Swap()
void Swap (FuelMetadata * other)
tags() [1/2]
const ::google::protobuf::RepeatedPtrField<::std::string > & tags () const inline
tags() [2/2]
const ::std::string & tags (int index) const inline
tags_size()
int tags_size () const inline
version()
google::protobuf::int32 version () const inline
world()
const ::gz::msgs::FuelMetadata_World & world () const inline
References gz::msgs::_FuelMetadata_World_default_instance_, and FuelMetadata::has_world().
Member Data Documentation
kAnnotationsFieldNumber
const int kAnnotationsFieldNumber = 9 static
kAuthorsFieldNumber
const int kAuthorsFieldNumber = 6 static
kCategoriesFieldNumber
const int kCategoriesFieldNumber = 12 static
kCompatibilitiesFieldNumber
const int kCompatibilitiesFieldNumber = 11 static
kDependenciesFieldNumber
const int kDependenciesFieldNumber = 10 static
kDescriptionFieldNumber
const int kDescriptionFieldNumber = 4 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    8
kLegalFieldNumber
const int kLegalFieldNumber = 7 static
kModelFieldNumber
const int kModelFieldNumber = 1 static
kNameFieldNumber
const int kNameFieldNumber = 3 static
kTagsFieldNumber
const int kTagsFieldNumber = 8 static
kVersionFieldNumber
const int kVersionFieldNumber = 5 static
kWorldFieldNumber
const int kWorldFieldNumber = 2 static
The documentation for this class was generated from the following file:
fuel_metadata.pb.h