Gazebo Msgs: Subscribe Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Subscribe Class Reference
#include <subscribe.pb.h>
Public Member Functions
Subscribe ()
Subscribe (const Subscribe &from)
virtual ~Subscribe ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_host ()
void clear_latching ()
void clear_msg_type ()
void clear_port ()
void clear_topic ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Subscribe &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
const ::std::string & host () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
bool latching () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Subscribe &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::std::string & msg_type () const
::gz::msgs::Header * mutable_header ()
::std::string * mutable_host ()
::std::string * mutable_msg_type ()
::std::string * mutable_topic ()
Subscribe * New () const final
Subscribe * New (::google::protobuf::Arena *arena) const final
Subscribe & operator= (const Subscribe &from)
::google::protobuf::uint32 port () const
::gz::msgs::Header * release_header ()
::std::string * release_host ()
::std::string * release_msg_type ()
::std::string * release_topic ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_host (::std::string *host)
void set_allocated_msg_type (::std::string *msg_type)
void set_allocated_topic (::std::string *topic)
void set_host (const ::std::string &value)
void set_host (const char *value)
void set_host (const char *value, size_t size)
void set_latching (bool value)
void set_msg_type (const ::std::string &value)
void set_msg_type (const char *value)
void set_msg_type (const char *value, size_t size)
void set_port (::google::protobuf::uint32 value)
void set_topic (const ::std::string &value)
void set_topic (const char *value)
void set_topic (const char *value, size_t size)
void Swap (Subscribe *other)
const ::std::string & topic () const
Static Public Member Functions
static const Subscribe & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Subscribe * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static const int kHostFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kLatchingFieldNumber = 6
static const int kMsgTypeFieldNumber = 5
static const int kPortFieldNumber = 4
static const int kTopicFieldNumber = 2
Constructor & Destructor Documentation
Subscribe() [1/2]
Subscribe ()
~Subscribe()
virtual ~Subscribe () virtual
Subscribe() [2/2]
Subscribe (const Subscribe & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_host()
void clear_host () inline
clear_latching()
void clear_latching () inline
clear_msg_type()
void clear_msg_type () inline
clear_port()
void clear_port () inline
clear_topic()
void clear_topic () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Subscribe & from)
default_instance()
static const Subscribe& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Subscribe::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by Subscribe::set_allocated_header().
host()
const ::std::string & host () const inline
Referenced by Subscribe::set_allocated_host().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Subscribe* internal_default_instance () inline static
References gz::msgs::_Subscribe_default_instance_.
Referenced by Subscribe::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
latching()
bool latching () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Subscribe & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
msg_type()
const ::std::string & msg_type () const inline
Referenced by Subscribe::set_allocated_msg_type().
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_host()
std::string * mutable_host () inline
mutable_msg_type()
std::string * mutable_msg_type () inline
mutable_topic()
std::string * mutable_topic () inline
New() [1/2]
Subscribe* New () const inline final
New() [2/2]
Subscribe* New (::google::protobuf::Arena * arena) const inline final
operator=()
Subscribe& operator= (const Subscribe & from) inline
port()
google::protobuf::uint32 port () const inline
release_header()
gz::msgs::Header * release_header () inline
release_host()
std::string * release_host () inline
release_msg_type()
std::string * release_msg_type () inline
release_topic()
std::string * release_topic () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References Subscribe::header().
set_allocated_host()
void set_allocated_host (::std::string * host) inline
References Subscribe::host().
set_allocated_msg_type()
void set_allocated_msg_type (::std::string * msg_type) inline
References Subscribe::msg_type().
set_allocated_topic()
void set_allocated_topic (::std::string * topic) inline
References Subscribe::topic().
set_host() [1/3]
void set_host (const ::std::string & value) inline
set_host() [2/3]
void set_host (const char * value) inline
set_host() [3/3]
void set_host (const char * value, size_t size) inline
set_latching()
void set_latching (bool value) inline
set_msg_type() [1/3]
void set_msg_type (const ::std::string & value) inline
set_msg_type() [2/3]
void set_msg_type (const char * value) inline
set_msg_type() [3/3]
void set_msg_type (const char * value, size_t size) inline
set_port()
void set_port (::google::protobuf::uint32 value) inline
set_topic() [1/3]
void set_topic (const ::std::string & value) inline
set_topic() [2/3]
void set_topic (const char * value) inline
set_topic() [3/3]
void set_topic (const char * value, size_t size) inline
Swap()
void Swap (Subscribe * other)
topic()
const ::std::string & topic () const inline
Referenced by Subscribe::set_allocated_topic().
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHostFieldNumber
const int kHostFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLatchingFieldNumber
const int kLatchingFieldNumber = 6 static
kMsgTypeFieldNumber
const int kMsgTypeFieldNumber = 5 static
kPortFieldNumber
const int kPortFieldNumber = 4 static
kTopicFieldNumber
const int kTopicFieldNumber = 2 static
The documentation for this class was generated from the following file:
subscribe.pb.h