Gazebo Msgs: ContactSensor Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
ContactSensor Class Reference
#include <contactsensor.pb.h>
Public Member Functions
ContactSensor ()
ContactSensor (const ContactSensor &from)
virtual ~ContactSensor ()
size_t ByteSizeLong () const final
void Clear () final
void clear_collision_name ()
void clear_header ()
const ::std::string & collision_name () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const ContactSensor &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ContactSensor &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_collision_name ()
::gz::msgs::Header * mutable_header ()
ContactSensor * New () const final
ContactSensor * New (::google::protobuf::Arena *arena) const final
ContactSensor & operator= (const ContactSensor &from)
::std::string * release_collision_name ()
::gz::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_collision_name (::std::string *collision_name)
void set_allocated_header (::gz::msgs::Header *header)
void set_collision_name (const ::std::string &value)
void set_collision_name (const char *value)
void set_collision_name (const char *value, size_t size)
void Swap (ContactSensor *other)
Static Public Member Functions
static const ContactSensor & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const ContactSensor * internal_default_instance ()
Static Public Attributes
static const int kCollisionNameFieldNumber = 2
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
Constructor & Destructor Documentation
ContactSensor() [1/2]
ContactSensor ()
~ContactSensor()
virtual ~ContactSensor () virtual
ContactSensor() [2/2]
ContactSensor (const ContactSensor & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_collision_name()
void clear_collision_name () inline
clear_header()
void clear_header ()
collision_name()
const ::std::string & collision_name () const inline
Referenced by ContactSensor::set_allocated_collision_name().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const ContactSensor & from)
default_instance()
static const ContactSensor& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References ContactSensor::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by ContactSensor::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const ContactSensor* internal_default_instance () inline static
References gz::msgs::_ContactSensor_default_instance_.
Referenced by ContactSensor::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const ContactSensor & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_collision_name()
std::string * mutable_collision_name () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
New() [1/2]
ContactSensor* New () const inline final
New() [2/2]
ContactSensor* New (::google::protobuf::Arena * arena) const inline final
operator=()
ContactSensor& operator= (const ContactSensor & from) inline
release_collision_name()
std::string * release_collision_name () inline
release_header()
gz::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_collision_name()
void set_allocated_collision_name (::std::string * collision_name) inline
References ContactSensor::collision_name().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References ContactSensor::header().
set_collision_name() [1/3]
void set_collision_name (const ::std::string & value) inline
set_collision_name() [2/3]
void set_collision_name (const char * value) inline
set_collision_name() [3/3]
void set_collision_name (const char * value, size_t size) inline
Swap()
void Swap (ContactSensor * other)
Member Data Documentation
kCollisionNameFieldNumber
const int kCollisionNameFieldNumber = 2 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
The documentation for this class was generated from the following file:
contactsensor.pb.h