Gazebo Msgs: CameraSensor Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
CameraSensor Class Reference
#include <camerasensor.pb.h>
Public Types
typedef CameraSensor_BoundingBoxType BoundingBoxType
typedef CameraSensor_SegmentationType SegmentationType
Public Member Functions
CameraSensor ()
CameraSensor (const CameraSensor &from)
virtual ~CameraSensor ()
::google::protobuf::int32 anti_aliasing () const
::gz::msgs::CameraSensor_BoundingBoxType bounding_box_type () const
size_t ByteSizeLong () const final
void Clear () final
void clear_anti_aliasing ()
void clear_bounding_box_type ()
void clear_depth_far_clip ()
void clear_depth_near_clip ()
void clear_distortion ()
void clear_far_clip ()
void clear_header ()
void clear_horizontal_fov ()
void clear_image_format ()
void clear_image_noise ()
void clear_image_size ()
void clear_is_depth_camera ()
void clear_lens ()
void clear_near_clip ()
void clear_pixel_format ()
void clear_save_enabled ()
void clear_save_path ()
void clear_segmentation_type ()
void clear_triggered ()
void clear_triggered_topic ()
void clear_visibility_mask ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const CameraSensor &from)
const ::gz::msgs::Double & depth_far_clip () const
const ::gz::msgs::Double & depth_near_clip () const
const ::gz::msgs::Distortion & distortion () const
double far_clip () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_depth_far_clip () const
bool has_depth_near_clip () const
bool has_distortion () const
bool has_header () const
bool has_image_noise () const
bool has_image_size () const
bool has_lens () const
const ::gz::msgs::Header & header () const
double horizontal_fov () const
const ::std::string & image_format () const
const ::gz::msgs::SensorNoise & image_noise () const
const ::gz::msgs::Vector2d & image_size () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool is_depth_camera () const
bool IsInitialized () const final
const ::gz::msgs::Lens & lens () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const CameraSensor &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Double * mutable_depth_far_clip ()
::gz::msgs::Double * mutable_depth_near_clip ()
::gz::msgs::Distortion * mutable_distortion ()
::gz::msgs::Header * mutable_header ()
::std::string * mutable_image_format ()
::gz::msgs::SensorNoise * mutable_image_noise ()
::gz::msgs::Vector2d * mutable_image_size ()
::gz::msgs::Lens * mutable_lens ()
::std::string * mutable_save_path ()
::std::string * mutable_triggered_topic ()
double near_clip () const
CameraSensor * New () const final
CameraSensor * New (::google::protobuf::Arena *arena) const final
CameraSensor & operator= (const CameraSensor &from)
::gz::msgs::PixelFormatType pixel_format () const
::gz::msgs::Double * release_depth_far_clip ()
::gz::msgs::Double * release_depth_near_clip ()
::gz::msgs::Distortion * release_distortion ()
::gz::msgs::Header * release_header ()
::std::string * release_image_format ()
::gz::msgs::SensorNoise * release_image_noise ()
::gz::msgs::Vector2d * release_image_size ()
::gz::msgs::Lens * release_lens ()
::std::string * release_save_path ()
::std::string * release_triggered_topic ()
bool save_enabled () const
const ::std::string & save_path () const
::gz::msgs::CameraSensor_SegmentationType segmentation_type () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_depth_far_clip (::gz::msgs::Double *depth_far_clip)
void set_allocated_depth_near_clip (::gz::msgs::Double *depth_near_clip)
void set_allocated_distortion (::gz::msgs::Distortion *distortion)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_image_format (::std::string *image_format)
void set_allocated_image_noise (::gz::msgs::SensorNoise *image_noise)
void set_allocated_image_size (::gz::msgs::Vector2d *image_size)
void set_allocated_lens (::gz::msgs::Lens *lens)
void set_allocated_save_path (::std::string *save_path)
void set_allocated_triggered_topic (::std::string *triggered_topic)
void set_anti_aliasing (::google::protobuf::int32 value)
void set_bounding_box_type (::gz::msgs::CameraSensor_BoundingBoxType value)
void set_far_clip (double value)
void set_horizontal_fov (double value)
void set_image_format (const ::std::string &value)
void set_image_format (const char *value)
void set_image_format (const char *value, size_t size)
void set_is_depth_camera (bool value)
void set_near_clip (double value)
void set_pixel_format (::gz::msgs::PixelFormatType value)
void set_save_enabled (bool value)
void set_save_path (const ::std::string &value)
void set_save_path (const char *value)
void set_save_path (const char *value, size_t size)
void set_segmentation_type (::gz::msgs::CameraSensor_SegmentationType value)
void set_triggered (bool value)
void set_triggered_topic (const ::std::string &value)
void set_triggered_topic (const char *value)
void set_triggered_topic (const char *value, size_t size)
void set_visibility_mask (::google::protobuf::uint32 value)
void Swap (CameraSensor *other)
bool triggered () const
const ::std::string & triggered_topic () const
::google::protobuf::uint32 visibility_mask () const
Static Public Member Functions
static const ::google::protobuf::EnumDescriptor * BoundingBoxType_descriptor ()
static bool BoundingBoxType_IsValid (int value)
static const ::std::string & BoundingBoxType_Name (BoundingBoxType value)
static bool BoundingBoxType_Parse (const ::std::string &name, BoundingBoxType *value)
static const CameraSensor & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const CameraSensor * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * SegmentationType_descriptor ()
static bool SegmentationType_IsValid (int value)
static const ::std::string & SegmentationType_Name (SegmentationType value)
static bool SegmentationType_Parse (const ::std::string &name, SegmentationType *value)
Static Public Attributes
static const int BoundingBoxType_ARRAYSIZE
static const BoundingBoxType BoundingBoxType_MAX
static const BoundingBoxType BoundingBoxType_MIN
static const BoundingBoxType BOX_3D
static const BoundingBoxType FULL_BOX_2D
static const int kAntiAliasingFieldNumber = 18
static const int kBoundingBoxTypeFieldNumber = 13
static const int kDepthFarClipFieldNumber = 12
static const int kDepthNearClipFieldNumber = 11
static const int kDistortionFieldNumber = 9
static const int kFarClipFieldNumber = 6
static const int kHeaderFieldNumber = 1
static const int kHorizontalFovFieldNumber = 2
static const int kImageFormatFieldNumber = 4
static const int kImageNoiseFieldNumber = 10
static const int kImageSizeFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kIsDepthCameraFieldNumber = 20
static const int kLensFieldNumber = 15
static const int kNearClipFieldNumber = 5
static const int kPixelFormatFieldNumber = 21
static const int kSaveEnabledFieldNumber = 7
static const int kSavePathFieldNumber = 8
static const int kSegmentationTypeFieldNumber = 14
static const int kTriggeredFieldNumber = 16
static const int kTriggeredTopicFieldNumber = 17
static const int kVisibilityMaskFieldNumber = 19
static const BoundingBoxType NO_BOUNDING_BOX
static const SegmentationType NO_SEGMENTATION
static const SegmentationType PANOPTIC
static const int SegmentationType_ARRAYSIZE
static const SegmentationType SegmentationType_MAX
static const SegmentationType SegmentationType_MIN
static const SegmentationType SEMANTIC
static const BoundingBoxType VISIBLE_BOX_2D
Member Typedef Documentation
BoundingBoxType
typedef CameraSensor_BoundingBoxType BoundingBoxType
SegmentationType
typedef CameraSensor_SegmentationType SegmentationType
Constructor & Destructor Documentation
CameraSensor() [1/2]
CameraSensor ()
~CameraSensor()
virtual ~CameraSensor () virtual
CameraSensor() [2/2]
CameraSensor (const CameraSensor & from)
Member Function Documentation
anti_aliasing()
google::protobuf::int32 anti_aliasing () const inline
bounding_box_type()
gz::msgs::CameraSensor_BoundingBoxType bounding_box_type () const inline
BoundingBoxType_descriptor()
static const ::google::protobuf::EnumDescriptor* BoundingBoxType_descriptor () inline static
References gz::msgs::CameraSensor_BoundingBoxType_descriptor().
BoundingBoxType_IsValid()
static bool BoundingBoxType_IsValid (int value) inline static
References gz::msgs::CameraSensor_BoundingBoxType_IsValid().
BoundingBoxType_Name()
static const ::std::string& BoundingBoxType_Name (BoundingBoxType value) inline static
References gz::msgs::CameraSensor_BoundingBoxType_Name().
BoundingBoxType_Parse()
static bool BoundingBoxType_Parse (const ::std::string & name, BoundingBoxType * value) inline static
References gz::msgs::CameraSensor_BoundingBoxType_Parse().
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_anti_aliasing()
void clear_anti_aliasing () inline
clear_bounding_box_type()
void clear_bounding_box_type () inline
clear_depth_far_clip()
void clear_depth_far_clip ()
clear_depth_near_clip()
void clear_depth_near_clip ()
clear_distortion()
void clear_distortion ()
clear_far_clip()
void clear_far_clip () inline
clear_header()
void clear_header ()
clear_horizontal_fov()
void clear_horizontal_fov () inline
clear_image_format()
void clear_image_format () inline
clear_image_noise()
void clear_image_noise ()
clear_image_size()
void clear_image_size ()
clear_is_depth_camera()
void clear_is_depth_camera () inline
clear_lens()
void clear_lens ()
clear_near_clip()
void clear_near_clip () inline
clear_pixel_format()
void clear_pixel_format () inline
clear_save_enabled()
void clear_save_enabled () inline
clear_save_path()
void clear_save_path () inline
clear_segmentation_type()
void clear_segmentation_type () inline
clear_triggered()
void clear_triggered () inline
clear_triggered_topic()
void clear_triggered_topic () inline
clear_visibility_mask()
void clear_visibility_mask () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const CameraSensor & from)
default_instance()
static const CameraSensor& default_instance () static
depth_far_clip()
const ::gz::msgs::Double & depth_far_clip () const inline
References gz::msgs::_Double_default_instance_.
Referenced by CameraSensor::set_allocated_depth_far_clip().
depth_near_clip()
const ::gz::msgs::Double & depth_near_clip () const inline
References gz::msgs::_Double_default_instance_.
Referenced by CameraSensor::set_allocated_depth_near_clip().
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
distortion()
const ::gz::msgs::Distortion & distortion () const inline
References gz::msgs::_Distortion_default_instance_.
Referenced by CameraSensor::set_allocated_distortion().
far_clip()
double far_clip () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_depth_far_clip()
bool has_depth_far_clip () const inline
References CameraSensor::internal_default_instance().
has_depth_near_clip()
bool has_depth_near_clip () const inline
References CameraSensor::internal_default_instance().
has_distortion()
bool has_distortion () const inline
References CameraSensor::internal_default_instance().
has_header()
bool has_header () const inline
References CameraSensor::internal_default_instance().
has_image_noise()
bool has_image_noise () const inline
References CameraSensor::internal_default_instance().
has_image_size()
bool has_image_size () const inline
References CameraSensor::internal_default_instance().
has_lens()
bool has_lens () const inline
References CameraSensor::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by CameraSensor::set_allocated_header().
horizontal_fov()
double horizontal_fov () const inline
image_format()
const ::std::string & image_format () const inline
Referenced by CameraSensor::set_allocated_image_format().
image_noise()
const ::gz::msgs::SensorNoise & image_noise () const inline
References gz::msgs::_SensorNoise_default_instance_.
Referenced by CameraSensor::set_allocated_image_noise().
image_size()
const ::gz::msgs::Vector2d & image_size () const inline
References gz::msgs::_Vector2d_default_instance_.
Referenced by CameraSensor::set_allocated_image_size().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const CameraSensor* internal_default_instance () inline static
References gz::msgs::_CameraSensor_default_instance_.
Referenced by CameraSensor::has_depth_far_clip(), CameraSensor::has_depth_near_clip(), CameraSensor::has_distortion(), CameraSensor::has_header(), CameraSensor::has_image_noise(), CameraSensor::has_image_size(), and CameraSensor::has_lens().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
is_depth_camera()
bool is_depth_camera () const inline
IsInitialized()
bool IsInitialized () const final
lens()
const ::gz::msgs::Lens & lens () const inline
References gz::msgs::_Lens_default_instance_.
Referenced by CameraSensor::set_allocated_lens().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const CameraSensor & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_depth_far_clip()
gz::msgs::Double * mutable_depth_far_clip () inline
mutable_depth_near_clip()
gz::msgs::Double * mutable_depth_near_clip () inline
mutable_distortion()
gz::msgs::Distortion * mutable_distortion () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_image_format()
std::string * mutable_image_format () inline
mutable_image_noise()
gz::msgs::SensorNoise * mutable_image_noise () inline
mutable_image_size()
gz::msgs::Vector2d * mutable_image_size () inline
mutable_lens()
gz::msgs::Lens * mutable_lens () inline
mutable_save_path()
std::string * mutable_save_path () inline
mutable_triggered_topic()
std::string * mutable_triggered_topic () inline
near_clip()
double near_clip () const inline
New() [1/2]
CameraSensor* New () const inline final
New() [2/2]
CameraSensor* New (::google::protobuf::Arena * arena) const inline final
operator=()
CameraSensor& operator= (const CameraSensor & from) inline
pixel_format()
gz::msgs::PixelFormatType pixel_format () const inline
release_depth_far_clip()
gz::msgs::Double * release_depth_far_clip () inline
release_depth_near_clip()
gz::msgs::Double * release_depth_near_clip () inline
release_distortion()
gz::msgs::Distortion * release_distortion () inline
release_header()
gz::msgs::Header * release_header () inline
release_image_format()
std::string * release_image_format () inline
release_image_noise()
gz::msgs::SensorNoise * release_image_noise () inline
release_image_size()
gz::msgs::Vector2d * release_image_size () inline
release_lens()
gz::msgs::Lens * release_lens () inline
release_save_path()
std::string * release_save_path () inline
release_triggered_topic()
std::string * release_triggered_topic () inline
save_enabled()
bool save_enabled () const inline
save_path()
const ::std::string & save_path () const inline
Referenced by CameraSensor::set_allocated_save_path().
segmentation_type()
gz::msgs::CameraSensor_SegmentationType segmentation_type () const inline
SegmentationType_descriptor()
static const ::google::protobuf::EnumDescriptor* SegmentationType_descriptor () inline static
References gz::msgs::CameraSensor_SegmentationType_descriptor().
SegmentationType_IsValid()
static bool SegmentationType_IsValid (int value) inline static
References gz::msgs::CameraSensor_SegmentationType_IsValid().
SegmentationType_Name()
static const ::std::string& SegmentationType_Name (SegmentationType value) inline static
References gz::msgs::CameraSensor_SegmentationType_Name().
SegmentationType_Parse()
static bool SegmentationType_Parse (const ::std::string & name, SegmentationType * value) inline static
References gz::msgs::CameraSensor_SegmentationType_Parse().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_depth_far_clip()
void set_allocated_depth_far_clip (::gz::msgs::Double * depth_far_clip) inline
References CameraSensor::depth_far_clip().
set_allocated_depth_near_clip()
void set_allocated_depth_near_clip (::gz::msgs::Double * depth_near_clip) inline
References CameraSensor::depth_near_clip().
set_allocated_distortion()
void set_allocated_distortion (::gz::msgs::Distortion * distortion) inline
References CameraSensor::distortion().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References CameraSensor::header().
set_allocated_image_format()
void set_allocated_image_format (::std::string * image_format) inline
References CameraSensor::image_format().
set_allocated_image_noise()
void set_allocated_image_noise (::gz::msgs::SensorNoise * image_noise) inline
References CameraSensor::image_noise().
set_allocated_image_size()
void set_allocated_image_size (::gz::msgs::Vector2d * image_size) inline
References CameraSensor::image_size().
set_allocated_lens()
void set_allocated_lens (::gz::msgs::Lens * lens) inline
References CameraSensor::lens().
set_allocated_save_path()
void set_allocated_save_path (::std::string * save_path) inline
References CameraSensor::save_path().
set_allocated_triggered_topic()
void set_allocated_triggered_topic (::std::string * triggered_topic) inline
References CameraSensor::triggered_topic().
set_anti_aliasing()
void set_anti_aliasing (::google::protobuf::int32 value) inline
set_bounding_box_type()
void set_bounding_box_type (::gz::msgs::CameraSensor_BoundingBoxType value) inline
set_far_clip()
void set_far_clip (double value) inline
set_horizontal_fov()
void set_horizontal_fov (double value) inline
set_image_format() [1/3]
void set_image_format (const ::std::string & value) inline
set_image_format() [2/3]
void set_image_format (const char * value) inline
set_image_format() [3/3]
void set_image_format (const char * value, size_t size) inline
set_is_depth_camera()
void set_is_depth_camera (bool value) inline
set_near_clip()
void set_near_clip (double value) inline
set_pixel_format()
void set_pixel_format (::gz::msgs::PixelFormatType value) inline
set_save_enabled()
void set_save_enabled (bool value) inline
set_save_path() [1/3]
void set_save_path (const ::std::string & value) inline
set_save_path() [2/3]
void set_save_path (const char * value) inline
set_save_path() [3/3]
void set_save_path (const char * value, size_t size) inline
set_segmentation_type()
void set_segmentation_type (::gz::msgs::CameraSensor_SegmentationType value) inline
set_triggered()
void set_triggered (bool value) inline
set_triggered_topic() [1/3]
void set_triggered_topic (const ::std::string & value) inline
set_triggered_topic() [2/3]
void set_triggered_topic (const char * value) inline
set_triggered_topic() [3/3]
void set_triggered_topic (const char * value, size_t size) inline
set_visibility_mask()
void set_visibility_mask (::google::protobuf::uint32 value) inline
Swap()
void Swap (CameraSensor * other)
triggered()
bool triggered () const inline
triggered_topic()
const ::std::string & triggered_topic () const inline
Referenced by CameraSensor::set_allocated_triggered_topic().
visibility_mask()
google::protobuf::uint32 visibility_mask () const inline
Member Data Documentation
BoundingBoxType_ARRAYSIZE
const int BoundingBoxType_ARRAYSIZE static
Initial value:
=
    CameraSensor_BoundingBoxType_BoundingBoxType_ARRAYSIZE
BoundingBoxType_MAX
const BoundingBoxType BoundingBoxType_MAX static
Initial value:
=
    CameraSensor_BoundingBoxType_BoundingBoxType_MAX
BoundingBoxType_MIN
const BoundingBoxType BoundingBoxType_MIN static
Initial value:
=
    CameraSensor_BoundingBoxType_BoundingBoxType_MIN
BOX_3D
const BoundingBoxType BOX_3D static
Initial value:
=
    CameraSensor_BoundingBoxType_BOX_3D
FULL_BOX_2D
const BoundingBoxType FULL_BOX_2D static
Initial value:
=
    CameraSensor_BoundingBoxType_FULL_BOX_2D
kAntiAliasingFieldNumber
const int kAntiAliasingFieldNumber = 18 static
kBoundingBoxTypeFieldNumber
const int kBoundingBoxTypeFieldNumber = 13 static
kDepthFarClipFieldNumber
const int kDepthFarClipFieldNumber = 12 static
kDepthNearClipFieldNumber
const int kDepthNearClipFieldNumber = 11 static
kDistortionFieldNumber
const int kDistortionFieldNumber = 9 static
kFarClipFieldNumber
const int kFarClipFieldNumber = 6 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHorizontalFovFieldNumber
const int kHorizontalFovFieldNumber = 2 static
kImageFormatFieldNumber
const int kImageFormatFieldNumber = 4 static
kImageNoiseFieldNumber
const int kImageNoiseFieldNumber = 10 static
kImageSizeFieldNumber
const int kImageSizeFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kIsDepthCameraFieldNumber
const int kIsDepthCameraFieldNumber = 20 static
kLensFieldNumber
const int kLensFieldNumber = 15 static
kNearClipFieldNumber
const int kNearClipFieldNumber = 5 static
kPixelFormatFieldNumber
const int kPixelFormatFieldNumber = 21 static
kSaveEnabledFieldNumber
const int kSaveEnabledFieldNumber = 7 static
kSavePathFieldNumber
const int kSavePathFieldNumber = 8 static
kSegmentationTypeFieldNumber
const int kSegmentationTypeFieldNumber = 14 static
kTriggeredFieldNumber
const int kTriggeredFieldNumber = 16 static
kTriggeredTopicFieldNumber
const int kTriggeredTopicFieldNumber = 17 static
kVisibilityMaskFieldNumber
const int kVisibilityMaskFieldNumber = 19 static
NO_BOUNDING_BOX
const BoundingBoxType NO_BOUNDING_BOX static
Initial value:
=
    CameraSensor_BoundingBoxType_NO_BOUNDING_BOX
NO_SEGMENTATION
const SegmentationType NO_SEGMENTATION static
Initial value:
=
    CameraSensor_SegmentationType_NO_SEGMENTATION
PANOPTIC
const SegmentationType PANOPTIC static
Initial value:
=
    CameraSensor_SegmentationType_PANOPTIC
SegmentationType_ARRAYSIZE
const int SegmentationType_ARRAYSIZE static
Initial value:
=
    CameraSensor_SegmentationType_SegmentationType_ARRAYSIZE
SegmentationType_MAX
const SegmentationType SegmentationType_MAX static
Initial value:
=
    CameraSensor_SegmentationType_SegmentationType_MAX
SegmentationType_MIN
const SegmentationType SegmentationType_MIN static
Initial value:
=
    CameraSensor_SegmentationType_SegmentationType_MIN
SEMANTIC
const SegmentationType SEMANTIC static
Initial value:
=
    CameraSensor_SegmentationType_SEMANTIC
VISIBLE_BOX_2D
const BoundingBoxType VISIBLE_BOX_2D static
Initial value:
=
    CameraSensor_BoundingBoxType_VISIBLE_BOX_2D
The documentation for this class was generated from the following file:
camerasensor.pb.h