Gazebo Msgs: PointCloudPacked Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
PointCloudPacked Class Reference
#include <pointcloud_packed.pb.h>
Public Types
typedef PointCloudPacked_Field Field
Public Member Functions
PointCloudPacked ()
PointCloudPacked (const PointCloudPacked &from)
virtual ~PointCloudPacked ()
::gz::msgs::PointCloudPacked_Field * add_field ()
size_t ByteSizeLong () const final
void Clear () final
void clear_data ()
void clear_field ()
void clear_header ()
void clear_height ()
void clear_is_bigendian ()
void clear_is_dense ()
void clear_point_step ()
void clear_row_step ()
void clear_width ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const PointCloudPacked &from)
const ::std::string & data () const
const ::google::protobuf::RepeatedPtrField< ::gz::msgs::PointCloudPacked_Field > & field () const
const ::gz::msgs::PointCloudPacked_Field & field (int index) const
int field_size () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint32 height () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool is_bigendian () const
bool is_dense () const
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const PointCloudPacked &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_data ()
::google::protobuf::RepeatedPtrField< ::gz::msgs::PointCloudPacked_Field > * mutable_field ()
::gz::msgs::PointCloudPacked_Field * mutable_field (int index)
::gz::msgs::Header * mutable_header ()
PointCloudPacked * New () const final
PointCloudPacked * New (::google::protobuf::Arena *arena) const final
PointCloudPacked & operator= (const PointCloudPacked &from)
::google::protobuf::uint32 point_step () const
::std::string * release_data ()
::gz::msgs::Header * release_header ()
::google::protobuf::uint32 row_step () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_data (::std::string *data)
void set_allocated_header (::gz::msgs::Header *header)
void set_data (const ::std::string &value)
void set_data (const char *value)
void set_data (const void *value, size_t size)
void set_height (::google::protobuf::uint32 value)
void set_is_bigendian (bool value)
void set_is_dense (bool value)
void set_point_step (::google::protobuf::uint32 value)
void set_row_step (::google::protobuf::uint32 value)
void set_width (::google::protobuf::uint32 value)
void Swap (PointCloudPacked *other)
::google::protobuf::uint32 width () const
Static Public Member Functions
static const PointCloudPacked & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const PointCloudPacked * internal_default_instance ()
Static Public Attributes
static const int kDataFieldNumber = 8
static const int kFieldFieldNumber = 2
static const int kHeaderFieldNumber = 1
static const int kHeightFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kIsBigendianFieldNumber = 5
static const int kIsDenseFieldNumber = 9
static const int kPointStepFieldNumber = 6
static const int kRowStepFieldNumber = 7
static const int kWidthFieldNumber = 4
Member Typedef Documentation
Field
typedef PointCloudPacked_Field Field
Constructor & Destructor Documentation
PointCloudPacked() [1/2]
PointCloudPacked ()
~PointCloudPacked()
virtual ~PointCloudPacked () virtual
PointCloudPacked() [2/2]
PointCloudPacked (const PointCloudPacked & from)
Member Function Documentation
add_field()
gz::msgs::PointCloudPacked_Field * add_field () inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_data()
void clear_data () inline
clear_field()
void clear_field () inline
clear_header()
void clear_header ()
clear_height()
void clear_height () inline
clear_is_bigendian()
void clear_is_bigendian () inline
clear_is_dense()
void clear_is_dense () inline
clear_point_step()
void clear_point_step () inline
clear_row_step()
void clear_row_step () inline
clear_width()
void clear_width () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const PointCloudPacked & from)
data()
const ::std::string & data () const inline
Referenced by PointCloudPacked::set_allocated_data().
default_instance()
static const PointCloudPacked& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
field() [1/2]
const ::google::protobuf::RepeatedPtrField<::gz::msgs::PointCloudPacked_Field > & field () const inline
field() [2/2]
const ::gz::msgs::PointCloudPacked_Field & field (int index) const inline
field_size()
int field_size () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References PointCloudPacked::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by PointCloudPacked::set_allocated_header().
height()
google::protobuf::uint32 height () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const PointCloudPacked* internal_default_instance () inline static
References gz::msgs::_PointCloudPacked_default_instance_.
Referenced by PointCloudPacked::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
is_bigendian()
bool is_bigendian () const inline
is_dense()
bool is_dense () const inline
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const PointCloudPacked & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_data()
std::string * mutable_data () inline
mutable_field() [1/2]
google::protobuf::RepeatedPtrField<::gz::msgs::PointCloudPacked_Field > * mutable_field () inline
mutable_field() [2/2]
gz::msgs::PointCloudPacked_Field * mutable_field (int index) inline
mutable_header()
gz::msgs::Header * mutable_header () inline
New() [1/2]
PointCloudPacked* New () const inline final
New() [2/2]
PointCloudPacked* New (::google::protobuf::Arena * arena) const inline final
operator=()
PointCloudPacked& operator= (const PointCloudPacked & from) inline
point_step()
google::protobuf::uint32 point_step () const inline
release_data()
std::string * release_data () inline
release_header()
gz::msgs::Header * release_header () inline
row_step()
google::protobuf::uint32 row_step () const inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_data()
void set_allocated_data (::std::string * data) inline
References PointCloudPacked::data().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References PointCloudPacked::header().
set_data() [1/3]
void set_data (const ::std::string & value) inline
set_data() [2/3]
void set_data (const char * value) inline
set_data() [3/3]
void set_data (const void * value, size_t size) inline
set_height()
void set_height (::google::protobuf::uint32 value) inline
set_is_bigendian()
void set_is_bigendian (bool value) inline
set_is_dense()
void set_is_dense (bool value) inline
set_point_step()
void set_point_step (::google::protobuf::uint32 value) inline
set_row_step()
void set_row_step (::google::protobuf::uint32 value) inline
set_width()
void set_width (::google::protobuf::uint32 value) inline
Swap()
void Swap (PointCloudPacked * other)
width()
google::protobuf::uint32 width () const inline
Member Data Documentation
kDataFieldNumber
const int kDataFieldNumber = 8 static
kFieldFieldNumber
const int kFieldFieldNumber = 2 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHeightFieldNumber
const int kHeightFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    1
kIsBigendianFieldNumber
const int kIsBigendianFieldNumber = 5 static
kIsDenseFieldNumber
const int kIsDenseFieldNumber = 9 static
kPointStepFieldNumber
const int kPointStepFieldNumber = 6 static
kRowStepFieldNumber
const int kRowStepFieldNumber = 7 static
kWidthFieldNumber
const int kWidthFieldNumber = 4 static
The documentation for this class was generated from the following file:
pointcloud_packed.pb.h