Gazebo Msgs: Light Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Light Class Reference
#include <light.pb.h>
Public Types
typedef Light_LightType LightType
Public Member Functions
Light ()
Light (const Light &from)
virtual ~Light ()
float attenuation_constant () const
float attenuation_linear () const
float attenuation_quadratic () const
size_t ByteSizeLong () const final
bool cast_shadows () const
void Clear () final
void clear_attenuation_constant ()
void clear_attenuation_linear ()
void clear_attenuation_quadratic ()
void clear_cast_shadows ()
void clear_diffuse ()
void clear_direction ()
void clear_header ()
void clear_id ()
void clear_intensity ()
void clear_is_light_off ()
void clear_name ()
void clear_parent_id ()
void clear_pose ()
void clear_range ()
void clear_specular ()
void clear_spot_falloff ()
void clear_spot_inner_angle ()
void clear_spot_outer_angle ()
void clear_type ()
void clear_visualize_visual ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Light &from)
const ::gz::msgs::Color & diffuse () const
const ::gz::msgs::Vector3d & direction () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_diffuse () const
bool has_direction () const
bool has_header () const
bool has_pose () const
bool has_specular () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint32 id () const
float intensity () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool is_light_off () const
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Light &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Color * mutable_diffuse ()
::gz::msgs::Vector3d * mutable_direction ()
::gz::msgs::Header * mutable_header ()
::std::string * mutable_name ()
::gz::msgs::Pose * mutable_pose ()
::gz::msgs::Color * mutable_specular ()
const ::std::string & name () const
Light * New () const final
Light * New (::google::protobuf::Arena *arena) const final
Light & operator= (const Light &from)
::google::protobuf::uint32 parent_id () const
const ::gz::msgs::Pose & pose () const
float range () const
::gz::msgs::Color * release_diffuse ()
::gz::msgs::Vector3d * release_direction ()
::gz::msgs::Header * release_header ()
::std::string * release_name ()
::gz::msgs::Pose * release_pose ()
::gz::msgs::Color * release_specular ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_diffuse (::gz::msgs::Color *diffuse)
void set_allocated_direction (::gz::msgs::Vector3d *direction)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_pose (::gz::msgs::Pose *pose)
void set_allocated_specular (::gz::msgs::Color *specular)
void set_attenuation_constant (float value)
void set_attenuation_linear (float value)
void set_attenuation_quadratic (float value)
void set_cast_shadows (bool value)
void set_id (::google::protobuf::uint32 value)
void set_intensity (float value)
void set_is_light_off (bool value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_parent_id (::google::protobuf::uint32 value)
void set_range (float value)
void set_spot_falloff (float value)
void set_spot_inner_angle (float value)
void set_spot_outer_angle (float value)
void set_type (::gz::msgs::Light_LightType value)
void set_visualize_visual (bool value)
const ::gz::msgs::Color & specular () const
float spot_falloff () const
float spot_inner_angle () const
float spot_outer_angle () const
void Swap (Light *other)
::gz::msgs::Light_LightType type () const
bool visualize_visual () const
Static Public Member Functions
static const Light & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Light * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * LightType_descriptor ()
static bool LightType_IsValid (int value)
static const ::std::string & LightType_Name (LightType value)
static bool LightType_Parse (const ::std::string &name, LightType *value)
Static Public Attributes
static const LightType DIRECTIONAL
static const int kAttenuationConstantFieldNumber = 7
static const int kAttenuationLinearFieldNumber = 8
static const int kAttenuationQuadraticFieldNumber = 9
static const int kCastShadowsFieldNumber = 12
static const int kDiffuseFieldNumber = 5
static const int kDirectionFieldNumber = 10
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 16
static constexpr int kIndexInFileMessages
static const int kIntensityFieldNumber = 18
static const int kIsLightOffFieldNumber = 19
static const int kNameFieldNumber = 2
static const int kParentIdFieldNumber = 17
static const int kPoseFieldNumber = 4
static const int kRangeFieldNumber = 11
static const int kSpecularFieldNumber = 6
static const int kSpotFalloffFieldNumber = 15
static const int kSpotInnerAngleFieldNumber = 13
static const int kSpotOuterAngleFieldNumber = 14
static const int kTypeFieldNumber = 3
static const int kVisualizeVisualFieldNumber = 20
static const int LightType_ARRAYSIZE
static const LightType LightType_MAX
static const LightType LightType_MIN
static const LightType POINT
static const LightType SPOT
Member Typedef Documentation
LightType
typedef Light_LightType LightType
Constructor & Destructor Documentation
Light() [1/2]
Light ()
~Light()
virtual ~Light () virtual
Light() [2/2]
Light (const Light & from)
Member Function Documentation
attenuation_constant()
float attenuation_constant () const inline
attenuation_linear()
float attenuation_linear () const inline
attenuation_quadratic()
float attenuation_quadratic () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
cast_shadows()
bool cast_shadows () const inline
Clear()
void Clear () final
clear_attenuation_constant()
void clear_attenuation_constant () inline
clear_attenuation_linear()
void clear_attenuation_linear () inline
clear_attenuation_quadratic()
void clear_attenuation_quadratic () inline
clear_cast_shadows()
void clear_cast_shadows () inline
clear_diffuse()
void clear_diffuse ()
clear_direction()
void clear_direction ()
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_intensity()
void clear_intensity () inline
clear_is_light_off()
void clear_is_light_off () inline
clear_name()
void clear_name () inline
clear_parent_id()
void clear_parent_id () inline
clear_pose()
void clear_pose ()
clear_range()
void clear_range () inline
clear_specular()
void clear_specular ()
clear_spot_falloff()
void clear_spot_falloff () inline
clear_spot_inner_angle()
void clear_spot_inner_angle () inline
clear_spot_outer_angle()
void clear_spot_outer_angle () inline
clear_type()
void clear_type () inline
clear_visualize_visual()
void clear_visualize_visual () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Light & from)
default_instance()
static const Light& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
diffuse()
const ::gz::msgs::Color & diffuse () const inline
References gz::msgs::_Color_default_instance_.
Referenced by Light::set_allocated_diffuse().
direction()
const ::gz::msgs::Vector3d & direction () const inline
References gz::msgs::_Vector3d_default_instance_.
Referenced by Light::set_allocated_direction().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_diffuse()
bool has_diffuse () const inline
References Light::internal_default_instance().
has_direction()
bool has_direction () const inline
References Light::internal_default_instance().
has_header()
bool has_header () const inline
References Light::internal_default_instance().
has_pose()
bool has_pose () const inline
References Light::internal_default_instance().
has_specular()
bool has_specular () const inline
References Light::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by Light::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
intensity()
float intensity () const inline
internal_default_instance()
static const Light* internal_default_instance () inline static
References gz::msgs::_Light_default_instance_.
Referenced by Light::has_diffuse(), Light::has_direction(), Light::has_header(), Light::has_pose(), and Light::has_specular().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
is_light_off()
bool is_light_off () const inline
IsInitialized()
bool IsInitialized () const final
LightType_descriptor()
static const ::google::protobuf::EnumDescriptor* LightType_descriptor () inline static
References gz::msgs::Light_LightType_descriptor().
LightType_IsValid()
static bool LightType_IsValid (int value) inline static
References gz::msgs::Light_LightType_IsValid().
LightType_Name()
static const ::std::string& LightType_Name (LightType value) inline static
References gz::msgs::Light_LightType_Name().
LightType_Parse()
static bool LightType_Parse (const ::std::string & name, LightType * value) inline static
References gz::msgs::Light_LightType_Parse().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Light & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_diffuse()
gz::msgs::Color * mutable_diffuse () inline
mutable_direction()
gz::msgs::Vector3d * mutable_direction () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
mutable_pose()
gz::msgs::Pose * mutable_pose () inline
mutable_specular()
gz::msgs::Color * mutable_specular () inline
name()
const ::std::string & name () const inline
Referenced by Light::set_allocated_name().
New() [1/2]
Light* New () const inline final
New() [2/2]
Light* New (::google::protobuf::Arena * arena) const inline final
operator=()
Light& operator= (const Light & from) inline
parent_id()
google::protobuf::uint32 parent_id () const inline
pose()
const ::gz::msgs::Pose & pose () const inline
References gz::msgs::_Pose_default_instance_.
Referenced by Light::set_allocated_pose().
range()
float range () const inline
release_diffuse()
gz::msgs::Color * release_diffuse () inline
release_direction()
gz::msgs::Vector3d * release_direction () inline
release_header()
gz::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_pose()
gz::msgs::Pose * release_pose () inline
release_specular()
gz::msgs::Color * release_specular () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_diffuse()
void set_allocated_diffuse (::gz::msgs::Color * diffuse) inline
References Light::diffuse().
set_allocated_direction()
void set_allocated_direction (::gz::msgs::Vector3d * direction) inline
References Light::direction().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References Light::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Light::name().
set_allocated_pose()
void set_allocated_pose (::gz::msgs::Pose * pose) inline
References Light::pose().
set_allocated_specular()
void set_allocated_specular (::gz::msgs::Color * specular) inline
References Light::specular().
set_attenuation_constant()
void set_attenuation_constant (float value) inline
set_attenuation_linear()
void set_attenuation_linear (float value) inline
set_attenuation_quadratic()
void set_attenuation_quadratic (float value) inline
set_cast_shadows()
void set_cast_shadows (bool value) inline
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_intensity()
void set_intensity (float value) inline
set_is_light_off()
void set_is_light_off (bool value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_parent_id()
void set_parent_id (::google::protobuf::uint32 value) inline
set_range()
void set_range (float value) inline
set_spot_falloff()
void set_spot_falloff (float value) inline
set_spot_inner_angle()
void set_spot_inner_angle (float value) inline
set_spot_outer_angle()
void set_spot_outer_angle (float value) inline
set_type()
void set_type (::gz::msgs::Light_LightType value) inline
set_visualize_visual()
void set_visualize_visual (bool value) inline
specular()
const ::gz::msgs::Color & specular () const inline
References gz::msgs::_Color_default_instance_.
Referenced by Light::set_allocated_specular().
spot_falloff()
float spot_falloff () const inline
spot_inner_angle()
float spot_inner_angle () const inline
spot_outer_angle()
float spot_outer_angle () const inline
Swap()
void Swap (Light * other)
type()
gz::msgs::Light_LightType type () const inline
visualize_visual()
bool visualize_visual () const inline
Member Data Documentation
DIRECTIONAL
const LightType DIRECTIONAL static
Initial value:
=
    Light_LightType_DIRECTIONAL
kAttenuationConstantFieldNumber
const int kAttenuationConstantFieldNumber = 7 static
kAttenuationLinearFieldNumber
const int kAttenuationLinearFieldNumber = 8 static
kAttenuationQuadraticFieldNumber
const int kAttenuationQuadraticFieldNumber = 9 static
kCastShadowsFieldNumber
const int kCastShadowsFieldNumber = 12 static
kDiffuseFieldNumber
const int kDiffuseFieldNumber = 5 static
kDirectionFieldNumber
const int kDirectionFieldNumber = 10 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 16 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kIntensityFieldNumber
const int kIntensityFieldNumber = 18 static
kIsLightOffFieldNumber
const int kIsLightOffFieldNumber = 19 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
kParentIdFieldNumber
const int kParentIdFieldNumber = 17 static
kPoseFieldNumber
const int kPoseFieldNumber = 4 static
kRangeFieldNumber
const int kRangeFieldNumber = 11 static
kSpecularFieldNumber
const int kSpecularFieldNumber = 6 static
kSpotFalloffFieldNumber
const int kSpotFalloffFieldNumber = 15 static
kSpotInnerAngleFieldNumber
const int kSpotInnerAngleFieldNumber = 13 static
kSpotOuterAngleFieldNumber
const int kSpotOuterAngleFieldNumber = 14 static
kTypeFieldNumber
const int kTypeFieldNumber = 3 static
kVisualizeVisualFieldNumber
const int kVisualizeVisualFieldNumber = 20 static
LightType_ARRAYSIZE
const int LightType_ARRAYSIZE static
Initial value:
=
    Light_LightType_LightType_ARRAYSIZE
LightType_MAX
const LightType LightType_MAX static
Initial value:
=
    Light_LightType_LightType_MAX
LightType_MIN
const LightType LightType_MIN static
Initial value:
=
    Light_LightType_LightType_MIN
POINT
const LightType POINT static
Initial value:
=
    Light_LightType_POINT
SPOT
const LightType SPOT static
Initial value:
=
    Light_LightType_SPOT
The documentation for this class was generated from the following file:
light.pb.h