Gazebo Msgs: Response Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Response Class Reference
#include <response.pb.h>
Public Member Functions
Response ()
Response (const Response &from)
virtual ~Response ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_id ()
void clear_request ()
void clear_response ()
void clear_serialized_data ()
void clear_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Response &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::int32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Response &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Header * mutable_header ()
::std::string * mutable_request ()
::std::string * mutable_response ()
::std::string * mutable_serialized_data ()
::std::string * mutable_type ()
Response * New () const final
Response * New (::google::protobuf::Arena *arena) const final
Response & operator= (const Response &from)
::gz::msgs::Header * release_header ()
::std::string * release_request ()
::std::string * release_response ()
::std::string * release_serialized_data ()
::std::string * release_type ()
const ::std::string & request () const
const ::std::string & response () const
const ::std::string & serialized_data () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_request (::std::string *request)
void set_allocated_response (::std::string *response)
void set_allocated_serialized_data (::std::string *serialized_data)
void set_allocated_type (::std::string *type)
void set_id (::google::protobuf::int32 value)
void set_request (const ::std::string &value)
void set_request (const char *value)
void set_request (const char *value, size_t size)
void set_response (const ::std::string &value)
void set_response (const char *value)
void set_response (const char *value, size_t size)
void set_serialized_data (const ::std::string &value)
void set_serialized_data (const char *value)
void set_serialized_data (const void *value, size_t size)
void set_type (const ::std::string &value)
void set_type (const char *value)
void set_type (const char *value, size_t size)
void Swap (Response *other)
const ::std::string & type () const
Static Public Member Functions
static const Response & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Response * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kRequestFieldNumber = 3
static const int kResponseFieldNumber = 4
static const int kSerializedDataFieldNumber = 6
static const int kTypeFieldNumber = 5
Constructor & Destructor Documentation
Response() [1/2]
Response ()
~Response()
virtual ~Response () virtual
Response() [2/2]
Response (const Response & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_request()
void clear_request () inline
clear_response()
void clear_response () inline
clear_serialized_data()
void clear_serialized_data () inline
clear_type()
void clear_type () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Response & from)
default_instance()
static const Response& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Response::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by Response::set_allocated_header().
id()
google::protobuf::int32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Response* internal_default_instance () inline static
References gz::msgs::_Response_default_instance_.
Referenced by Response::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Response & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_request()
std::string * mutable_request () inline
mutable_response()
std::string * mutable_response () inline
mutable_serialized_data()
std::string * mutable_serialized_data () inline
mutable_type()
std::string * mutable_type () inline
New() [1/2]
Response* New () const inline final
New() [2/2]
Response* New (::google::protobuf::Arena * arena) const inline final
operator=()
Response& operator= (const Response & from) inline
release_header()
gz::msgs::Header * release_header () inline
release_request()
std::string * release_request () inline
release_response()
std::string * release_response () inline
release_serialized_data()
std::string * release_serialized_data () inline
release_type()
std::string * release_type () inline
request()
const ::std::string & request () const inline
Referenced by Response::set_allocated_request().
response()
const ::std::string & response () const inline
Referenced by Response::set_allocated_response().
serialized_data()
const ::std::string & serialized_data () const inline
Referenced by Response::set_allocated_serialized_data().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References Response::header().
set_allocated_request()
void set_allocated_request (::std::string * request) inline
References Response::request().
set_allocated_response()
void set_allocated_response (::std::string * response) inline
References Response::response().
set_allocated_serialized_data()
void set_allocated_serialized_data (::std::string * serialized_data) inline
References Response::serialized_data().
set_allocated_type()
void set_allocated_type (::std::string * type) inline
References Response::type().
set_id()
void set_id (::google::protobuf::int32 value) inline
set_request() [1/3]
void set_request (const ::std::string & value) inline
set_request() [2/3]
void set_request (const char * value) inline
set_request() [3/3]
void set_request (const char * value, size_t size) inline
set_response() [1/3]
void set_response (const ::std::string & value) inline
set_response() [2/3]
void set_response (const char * value) inline
set_response() [3/3]
void set_response (const char * value, size_t size) inline
set_serialized_data() [1/3]
void set_serialized_data (const ::std::string & value) inline
set_serialized_data() [2/3]
void set_serialized_data (const char * value) inline
set_serialized_data() [3/3]
void set_serialized_data (const void * value, size_t size) inline
set_type() [1/3]
void set_type (const ::std::string & value) inline
set_type() [2/3]
void set_type (const char * value) inline
set_type() [3/3]
void set_type (const char * value, size_t size) inline
Swap()
void Swap (Response * other)
type()
const ::std::string & type () const inline
Referenced by Response::set_allocated_type().
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kRequestFieldNumber
const int kRequestFieldNumber = 3 static
kResponseFieldNumber
const int kResponseFieldNumber = 4 static
kSerializedDataFieldNumber
const int kSerializedDataFieldNumber = 6 static
kTypeFieldNumber
const int kTypeFieldNumber = 5 static
The documentation for this class was generated from the following file:
response.pb.h