Gazebo Msgs: LogStatus_LogFile Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
LogStatus_LogFile Class Reference
#include <log_status.pb.h>
Public Types
typedef LogStatus_LogFile_Units Units
Public Member Functions
LogStatus_LogFile ()
LogStatus_LogFile (const LogStatus_LogFile &from)
virtual ~LogStatus_LogFile ()
const ::std::string & base_path () const
size_t ByteSizeLong () const final
void Clear () final
void clear_base_path ()
void clear_full_path ()
void clear_record_resources ()
void clear_size ()
void clear_size_units ()
void clear_uri ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const LogStatus_LogFile &from)
const ::std::string & full_path () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const LogStatus_LogFile &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_base_path ()
::std::string * mutable_full_path ()
::std::string * mutable_uri ()
LogStatus_LogFile * New () const final
LogStatus_LogFile * New (::google::protobuf::Arena *arena) const final
LogStatus_LogFile & operator= (const LogStatus_LogFile &from)
bool record_resources () const
::std::string * release_base_path ()
::std::string * release_full_path ()
::std::string * release_uri ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_base_path (::std::string *base_path)
void set_allocated_full_path (::std::string *full_path)
void set_allocated_uri (::std::string *uri)
void set_base_path (const ::std::string &value)
void set_base_path (const char *value)
void set_base_path (const char *value, size_t size)
void set_full_path (const ::std::string &value)
void set_full_path (const char *value)
void set_full_path (const char *value, size_t size)
void set_record_resources (bool value)
void set_size (float value)
void set_size_units (::gz::msgs::LogStatus_LogFile_Units value)
void set_uri (const ::std::string &value)
void set_uri (const char *value)
void set_uri (const char *value, size_t size)
float size () const
::gz::msgs::LogStatus_LogFile_Units size_units () const
void Swap (LogStatus_LogFile *other)
const ::std::string & uri () const
Static Public Member Functions
static const LogStatus_LogFile & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const LogStatus_LogFile * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Units_descriptor ()
static bool Units_IsValid (int value)
static const ::std::string & Units_Name (Units value)
static bool Units_Parse (const ::std::string &name, Units *value)
Static Public Attributes
static const Units BYTES
static const Units G_BYTES
static const Units K_BYTES
static const int kBasePathFieldNumber = 2
static const int kFullPathFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kRecordResourcesFieldNumber = 6
static const int kSizeFieldNumber = 4
static const int kSizeUnitsFieldNumber = 5
static const int kUriFieldNumber = 1
static const Units M_BYTES
static const int Units_ARRAYSIZE
static const Units Units_MAX
static const Units Units_MIN
Member Typedef Documentation
Units
typedef LogStatus_LogFile_Units Units
Constructor & Destructor Documentation
LogStatus_LogFile() [1/2]
LogStatus_LogFile ()
~LogStatus_LogFile()
virtual ~LogStatus_LogFile () virtual
LogStatus_LogFile() [2/2]
LogStatus_LogFile (const LogStatus_LogFile & from)
Member Function Documentation
base_path()
const ::std::string & base_path () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_base_path()
void clear_base_path () inline
clear_full_path()
void clear_full_path () inline
clear_record_resources()
void clear_record_resources () inline
clear_size()
void clear_size () inline
clear_size_units()
void clear_size_units () inline
clear_uri()
void clear_uri () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const LogStatus_LogFile & from)
default_instance()
static const LogStatus_LogFile& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
full_path()
const ::std::string & full_path () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const LogStatus_LogFile* internal_default_instance () inline static
References gz::msgs::_LogStatus_LogFile_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const LogStatus_LogFile & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_base_path()
std::string * mutable_base_path () inline
mutable_full_path()
std::string * mutable_full_path () inline
mutable_uri()
std::string * mutable_uri () inline
New() [1/2]
LogStatus_LogFile* New () const inline final
New() [2/2]
LogStatus_LogFile* New (::google::protobuf::Arena * arena) const inline final
operator=()
LogStatus_LogFile& operator= (const LogStatus_LogFile & from) inline
record_resources()
bool record_resources () const inline
release_base_path()
std::string * release_base_path () inline
release_full_path()
std::string * release_full_path () inline
release_uri()
std::string * release_uri () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_base_path()
void set_allocated_base_path (::std::string * base_path) inline
set_allocated_full_path()
void set_allocated_full_path (::std::string * full_path) inline
set_allocated_uri()
void set_allocated_uri (::std::string * uri) inline
set_base_path() [1/3]
void set_base_path (const ::std::string & value) inline
set_base_path() [2/3]
void set_base_path (const char * value) inline
set_base_path() [3/3]
void set_base_path (const char * value, size_t size) inline
set_full_path() [1/3]
void set_full_path (const ::std::string & value) inline
set_full_path() [2/3]
void set_full_path (const char * value) inline
set_full_path() [3/3]
void set_full_path (const char * value, size_t size) inline
set_record_resources()
void set_record_resources (bool value) inline
set_size()
void set_size (float value) inline
set_size_units()
void set_size_units (::gz::msgs::LogStatus_LogFile_Units value) inline
set_uri() [1/3]
void set_uri (const ::std::string & value) inline
set_uri() [2/3]
void set_uri (const char * value) inline
set_uri() [3/3]
void set_uri (const char * value, size_t size) inline
size()
float size () const inline
size_units()
gz::msgs::LogStatus_LogFile_Units size_units () const inline
Swap()
void Swap (LogStatus_LogFile * other)
Units_descriptor()
static const ::google::protobuf::EnumDescriptor* Units_descriptor () inline static
References gz::msgs::LogStatus_LogFile_Units_descriptor().
Units_IsValid()
static bool Units_IsValid (int value) inline static
References gz::msgs::LogStatus_LogFile_Units_IsValid().
Units_Name()
static const ::std::string& Units_Name (Units value) inline static
References gz::msgs::LogStatus_LogFile_Units_Name().
Units_Parse()
static bool Units_Parse (const ::std::string & name, Units * value) inline static
References gz::msgs::LogStatus_LogFile_Units_Parse().
uri()
const ::std::string & uri () const inline
Member Data Documentation
BYTES
const Units BYTES static
Initial value:
=
    LogStatus_LogFile_Units_BYTES
G_BYTES
const Units G_BYTES static
Initial value:
=
    LogStatus_LogFile_Units_G_BYTES
K_BYTES
const Units K_BYTES static
Initial value:
=
    LogStatus_LogFile_Units_K_BYTES
kBasePathFieldNumber
const int kBasePathFieldNumber = 2 static
kFullPathFieldNumber
const int kFullPathFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kRecordResourcesFieldNumber
const int kRecordResourcesFieldNumber = 6 static
kSizeFieldNumber
const int kSizeFieldNumber = 4 static
kSizeUnitsFieldNumber
const int kSizeUnitsFieldNumber = 5 static
kUriFieldNumber
const int kUriFieldNumber = 1 static
M_BYTES
const Units M_BYTES static
Initial value:
=
    LogStatus_LogFile_Units_M_BYTES
Units_ARRAYSIZE
const int Units_ARRAYSIZE static
Initial value:
=
    LogStatus_LogFile_Units_Units_ARRAYSIZE
Units_MAX
const Units Units_MAX static
Initial value:
=
    LogStatus_LogFile_Units_Units_MAX
Units_MIN
const Units Units_MIN static
Initial value:
=
    LogStatus_LogFile_Units_Units_MIN
The documentation for this class was generated from the following file:
log_status.pb.h