Gazebo Msgs: MeshGeom Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
MeshGeom Class Reference
#include <meshgeom.pb.h>
Public Member Functions
MeshGeom ()
MeshGeom (const MeshGeom &from)
virtual ~MeshGeom ()
size_t ByteSizeLong () const final
bool center_submesh () const
void Clear () final
void clear_center_submesh ()
void clear_filename ()
void clear_header ()
void clear_scale ()
void clear_submesh ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const MeshGeom &from)
const ::std::string & filename () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_scale () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const MeshGeom &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_filename ()
::gz::msgs::Header * mutable_header ()
::gz::msgs::Vector3d * mutable_scale ()
::std::string * mutable_submesh ()
MeshGeom * New () const final
MeshGeom * New (::google::protobuf::Arena *arena) const final
MeshGeom & operator= (const MeshGeom &from)
::std::string * release_filename ()
::gz::msgs::Header * release_header ()
::gz::msgs::Vector3d * release_scale ()
::std::string * release_submesh ()
const ::gz::msgs::Vector3d & scale () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_filename (::std::string *filename)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_scale (::gz::msgs::Vector3d *scale)
void set_allocated_submesh (::std::string *submesh)
void set_center_submesh (bool value)
void set_filename (const ::std::string &value)
void set_filename (const char *value)
void set_filename (const char *value, size_t size)
void set_submesh (const ::std::string &value)
void set_submesh (const char *value)
void set_submesh (const char *value, size_t size)
const ::std::string & submesh () const
void Swap (MeshGeom *other)
Static Public Member Functions
static const MeshGeom & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const MeshGeom * internal_default_instance ()
Static Public Attributes
static const int kCenterSubmeshFieldNumber = 5
static const int kFilenameFieldNumber = 2
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kScaleFieldNumber = 3
static const int kSubmeshFieldNumber = 4
Constructor & Destructor Documentation
MeshGeom() [1/2]
MeshGeom ()
~MeshGeom()
virtual ~MeshGeom () virtual
MeshGeom() [2/2]
MeshGeom (const MeshGeom & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
center_submesh()
bool center_submesh () const inline
Clear()
void Clear () final
clear_center_submesh()
void clear_center_submesh () inline
clear_filename()
void clear_filename () inline
clear_header()
void clear_header ()
clear_scale()
void clear_scale ()
clear_submesh()
void clear_submesh () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const MeshGeom & from)
default_instance()
static const MeshGeom& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
filename()
const ::std::string & filename () const inline
Referenced by MeshGeom::set_allocated_filename().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References MeshGeom::internal_default_instance().
has_scale()
bool has_scale () const inline
References MeshGeom::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by MeshGeom::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const MeshGeom* internal_default_instance () inline static
References gz::msgs::_MeshGeom_default_instance_.
Referenced by MeshGeom::has_header(), and MeshGeom::has_scale().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const MeshGeom & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_filename()
std::string * mutable_filename () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_scale()
gz::msgs::Vector3d * mutable_scale () inline
mutable_submesh()
std::string * mutable_submesh () inline
New() [1/2]
MeshGeom* New () const inline final
New() [2/2]
MeshGeom* New (::google::protobuf::Arena * arena) const inline final
operator=()
MeshGeom& operator= (const MeshGeom & from) inline
release_filename()
std::string * release_filename () inline
release_header()
gz::msgs::Header * release_header () inline
release_scale()
gz::msgs::Vector3d * release_scale () inline
release_submesh()
std::string * release_submesh () inline
scale()
const ::gz::msgs::Vector3d & scale () const inline
References gz::msgs::_Vector3d_default_instance_.
Referenced by MeshGeom::set_allocated_scale().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_filename()
void set_allocated_filename (::std::string * filename) inline
References MeshGeom::filename().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References MeshGeom::header().
set_allocated_scale()
void set_allocated_scale (::gz::msgs::Vector3d * scale) inline
References MeshGeom::scale().
set_allocated_submesh()
void set_allocated_submesh (::std::string * submesh) inline
References MeshGeom::submesh().
set_center_submesh()
void set_center_submesh (bool value) inline
set_filename() [1/3]
void set_filename (const ::std::string & value) inline
set_filename() [2/3]
void set_filename (const char * value) inline
set_filename() [3/3]
void set_filename (const char * value, size_t size) inline
set_submesh() [1/3]
void set_submesh (const ::std::string & value) inline
set_submesh() [2/3]
void set_submesh (const char * value) inline
set_submesh() [3/3]
void set_submesh (const char * value, size_t size) inline
submesh()
const ::std::string & submesh () const inline
Referenced by MeshGeom::set_allocated_submesh().
Swap()
void Swap (MeshGeom * other)
Member Data Documentation
kCenterSubmeshFieldNumber
const int kCenterSubmeshFieldNumber = 5 static
kFilenameFieldNumber
const int kFilenameFieldNumber = 2 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kScaleFieldNumber
const int kScaleFieldNumber = 3 static
kSubmeshFieldNumber
const int kSubmeshFieldNumber = 4 static
The documentation for this class was generated from the following file:
meshgeom.pb.h