Gazebo Msgs: Plugin Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Plugin Class Reference
#include <plugin.pb.h>
Public Member Functions
Plugin ()
Plugin (const Plugin &from)
virtual ~Plugin ()
size_t ByteSizeLong () const final
void Clear () final
void clear_filename ()
void clear_header ()
void clear_innerxml ()
void clear_name ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Plugin &from)
const ::std::string & filename () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
const ::std::string & innerxml () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Plugin &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_filename ()
::gz::msgs::Header * mutable_header ()
::std::string * mutable_innerxml ()
::std::string * mutable_name ()
const ::std::string & name () const
Plugin * New () const final
Plugin * New (::google::protobuf::Arena *arena) const final
Plugin & operator= (const Plugin &from)
::std::string * release_filename ()
::gz::msgs::Header * release_header ()
::std::string * release_innerxml ()
::std::string * release_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_filename (::std::string *filename)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_innerxml (::std::string *innerxml)
void set_allocated_name (::std::string *name)
void set_filename (const ::std::string &value)
void set_filename (const char *value)
void set_filename (const char *value, size_t size)
void set_innerxml (const ::std::string &value)
void set_innerxml (const char *value)
void set_innerxml (const char *value, size_t size)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void Swap (Plugin *other)
Static Public Member Functions
static const Plugin & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Plugin * internal_default_instance ()
Static Public Attributes
static const int kFilenameFieldNumber = 3
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kInnerxmlFieldNumber = 4
static const int kNameFieldNumber = 2
Constructor & Destructor Documentation
Plugin() [1/2]
Plugin ()
~Plugin()
virtual ~Plugin () virtual
Plugin() [2/2]
Plugin (const Plugin & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_filename()
void clear_filename () inline
clear_header()
void clear_header ()
clear_innerxml()
void clear_innerxml () inline
clear_name()
void clear_name () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Plugin & from)
default_instance()
static const Plugin& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
filename()
const ::std::string & filename () const inline
Referenced by Plugin::set_allocated_filename().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Plugin::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by Plugin::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
innerxml()
const ::std::string & innerxml () const inline
Referenced by Plugin::set_allocated_innerxml().
internal_default_instance()
static const Plugin* internal_default_instance () inline static
References gz::msgs::_Plugin_default_instance_.
Referenced by Plugin::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Plugin & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_filename()
std::string * mutable_filename () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_innerxml()
std::string * mutable_innerxml () inline
mutable_name()
std::string * mutable_name () inline
name()
const ::std::string & name () const inline
Referenced by Plugin::set_allocated_name().
New() [1/2]
Plugin* New () const inline final
New() [2/2]
Plugin* New (::google::protobuf::Arena * arena) const inline final
operator=()
Plugin& operator= (const Plugin & from) inline
release_filename()
std::string * release_filename () inline
release_header()
gz::msgs::Header * release_header () inline
release_innerxml()
std::string * release_innerxml () inline
release_name()
std::string * release_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_filename()
void set_allocated_filename (::std::string * filename) inline
References Plugin::filename().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References Plugin::header().
set_allocated_innerxml()
void set_allocated_innerxml (::std::string * innerxml) inline
References Plugin::innerxml().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Plugin::name().
set_filename() [1/3]
void set_filename (const ::std::string & value) inline
set_filename() [2/3]
void set_filename (const char * value) inline
set_filename() [3/3]
void set_filename (const char * value, size_t size) inline
set_innerxml() [1/3]
void set_innerxml (const ::std::string & value) inline
set_innerxml() [2/3]
void set_innerxml (const char * value) inline
set_innerxml() [3/3]
void set_innerxml (const char * value, size_t size) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
Swap()
void Swap (Plugin * other)
Member Data Documentation
kFilenameFieldNumber
const int kFilenameFieldNumber = 3 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kInnerxmlFieldNumber
const int kInnerxmlFieldNumber = 4 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
The documentation for this class was generated from the following file:
plugin.pb.h