Gazebo Msgs: FuelMetadata_Contact Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
FuelMetadata_Contact Class Reference
#include <fuel_metadata.pb.h>
Public Member Functions
FuelMetadata_Contact ()
FuelMetadata_Contact (const FuelMetadata_Contact &from)
virtual ~FuelMetadata_Contact ()
size_t ByteSizeLong () const final
void Clear () final
void clear_email ()
void clear_name ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const FuelMetadata_Contact &from)
const ::std::string & email () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const FuelMetadata_Contact &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_email ()
::std::string * mutable_name ()
const ::std::string & name () const
FuelMetadata_Contact * New () const final
FuelMetadata_Contact * New (::google::protobuf::Arena *arena) const final
FuelMetadata_Contact & operator= (const FuelMetadata_Contact &from)
::std::string * release_email ()
::std::string * release_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_email (::std::string *email)
void set_allocated_name (::std::string *name)
void set_email (const ::std::string &value)
void set_email (const char *value)
void set_email (const char *value, size_t size)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void Swap (FuelMetadata_Contact *other)
Static Public Member Functions
static const FuelMetadata_Contact & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const FuelMetadata_Contact * internal_default_instance ()
Static Public Attributes
static const int kEmailFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 1
Constructor & Destructor Documentation
FuelMetadata_Contact() [1/2]
FuelMetadata_Contact ()
~FuelMetadata_Contact()
virtual ~FuelMetadata_Contact () virtual
FuelMetadata_Contact() [2/2]
FuelMetadata_Contact (const FuelMetadata_Contact & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_email()
void clear_email () inline
clear_name()
void clear_name () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const FuelMetadata_Contact & from)
default_instance()
static const FuelMetadata_Contact& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
email()
const ::std::string & email () const inline
Referenced by FuelMetadata_Contact::set_allocated_email().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const FuelMetadata_Contact* internal_default_instance () inline static
References gz::msgs::_FuelMetadata_Contact_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const FuelMetadata_Contact & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_email()
std::string * mutable_email () inline
mutable_name()
std::string * mutable_name () inline
name()
const ::std::string & name () const inline
Referenced by FuelMetadata_Contact::set_allocated_name().
New() [1/2]
FuelMetadata_Contact* New () const inline final
New() [2/2]
FuelMetadata_Contact* New (::google::protobuf::Arena * arena) const inline final
operator=()
FuelMetadata_Contact& operator= (const FuelMetadata_Contact & from) inline
release_email()
std::string * release_email () inline
release_name()
std::string * release_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_email()
void set_allocated_email (::std::string * email) inline
References FuelMetadata_Contact::email().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References FuelMetadata_Contact::name().
set_email() [1/3]
void set_email (const ::std::string & value) inline
set_email() [2/3]
void set_email (const char * value) inline
set_email() [3/3]
void set_email (const char * value, size_t size) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
Swap()
void Swap (FuelMetadata_Contact * other)
Member Data Documentation
kEmailFieldNumber
const int kEmailFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 1 static
The documentation for this class was generated from the following file:
fuel_metadata.pb.h