Gazebo Msgs: DVLKinematicEstimate Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
DVLKinematicEstimate Class Reference
#include <dvl_kinematic_estimate.pb.h>
Public Types
typedef DVLKinematicEstimate_ReferenceType ReferenceType
Public Member Functions
DVLKinematicEstimate ()
DVLKinematicEstimate (const DVLKinematicEstimate &from)
virtual ~DVLKinematicEstimate ()
void add_covariance (double value)
size_t ByteSizeLong () const final
void Clear () final
void clear_covariance ()
void clear_mean ()
void clear_reference ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const DVLKinematicEstimate &from)
const ::google::protobuf::RepeatedField< double > & covariance () const
double covariance (int index) const
int covariance_size () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_mean () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::gz::msgs::Vector3d & mean () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const DVLKinematicEstimate &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::google::protobuf::RepeatedField< double > * mutable_covariance ()
::gz::msgs::Vector3d * mutable_mean ()
DVLKinematicEstimate * New () const final
DVLKinematicEstimate * New (::google::protobuf::Arena *arena) const final
DVLKinematicEstimate & operator= (const DVLKinematicEstimate &from)
::gz::msgs::DVLKinematicEstimate_ReferenceType reference () const
::gz::msgs::Vector3d * release_mean ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_mean (::gz::msgs::Vector3d *mean)
void set_covariance (int index, double value)
void set_reference (::gz::msgs::DVLKinematicEstimate_ReferenceType value)
void Swap (DVLKinematicEstimate *other)
Static Public Member Functions
static const DVLKinematicEstimate & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const DVLKinematicEstimate * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * ReferenceType_descriptor ()
static bool ReferenceType_IsValid (int value)
static const ::std::string & ReferenceType_Name (ReferenceType value)
static bool ReferenceType_Parse (const ::std::string &name, ReferenceType *value)
Static Public Attributes
static const ReferenceType DVL_REFERENCE_EARTH
static const ReferenceType DVL_REFERENCE_SHIP
static const ReferenceType DVL_REFERENCE_UNSPECIFIED
static const int kCovarianceFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kMeanFieldNumber = 2
static const int kReferenceFieldNumber = 1
static const int ReferenceType_ARRAYSIZE
static const ReferenceType ReferenceType_MAX
static const ReferenceType ReferenceType_MIN
Member Typedef Documentation
ReferenceType
typedef DVLKinematicEstimate_ReferenceType ReferenceType
Constructor & Destructor Documentation
DVLKinematicEstimate() [1/2]
DVLKinematicEstimate ()
~DVLKinematicEstimate()
virtual ~DVLKinematicEstimate () virtual
DVLKinematicEstimate() [2/2]
DVLKinematicEstimate (const DVLKinematicEstimate & from)
Member Function Documentation
add_covariance()
void add_covariance (double value) inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_covariance()
void clear_covariance () inline
clear_mean()
void clear_mean ()
clear_reference()
void clear_reference () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const DVLKinematicEstimate & from)
covariance() [1/2]
const ::google::protobuf::RepeatedField< double > & covariance () const inline
covariance() [2/2]
double covariance (int index) const inline
covariance_size()
int covariance_size () const inline
default_instance()
static const DVLKinematicEstimate& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_mean()
bool has_mean () const inline
References DVLKinematicEstimate::internal_default_instance().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const DVLKinematicEstimate* internal_default_instance () inline static
References gz::msgs::_DVLKinematicEstimate_default_instance_.
Referenced by DVLKinematicEstimate::has_mean().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
mean()
const ::gz::msgs::Vector3d & mean () const inline
References gz::msgs::_Vector3d_default_instance_.
Referenced by DVLKinematicEstimate::set_allocated_mean().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const DVLKinematicEstimate & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_covariance()
google::protobuf::RepeatedField< double > * mutable_covariance () inline
mutable_mean()
gz::msgs::Vector3d * mutable_mean () inline
New() [1/2]
DVLKinematicEstimate* New () const inline final
New() [2/2]
DVLKinematicEstimate* New (::google::protobuf::Arena * arena) const inline final
operator=()
DVLKinematicEstimate& operator= (const DVLKinematicEstimate & from) inline
reference()
gz::msgs::DVLKinematicEstimate_ReferenceType reference () const inline
ReferenceType_descriptor()
static const ::google::protobuf::EnumDescriptor* ReferenceType_descriptor () inline static
References gz::msgs::DVLKinematicEstimate_ReferenceType_descriptor().
ReferenceType_IsValid()
static bool ReferenceType_IsValid (int value) inline static
References gz::msgs::DVLKinematicEstimate_ReferenceType_IsValid().
ReferenceType_Name()
static const ::std::string& ReferenceType_Name (ReferenceType value) inline static
References gz::msgs::DVLKinematicEstimate_ReferenceType_Name().
ReferenceType_Parse()
static bool ReferenceType_Parse (const ::std::string & name, ReferenceType * value) inline static
References gz::msgs::DVLKinematicEstimate_ReferenceType_Parse().
release_mean()
gz::msgs::Vector3d * release_mean () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_mean()
void set_allocated_mean (::gz::msgs::Vector3d * mean) inline
References DVLKinematicEstimate::mean().
set_covariance()
void set_covariance (int index, double value) inline
set_reference()
void set_reference (::gz::msgs::DVLKinematicEstimate_ReferenceType value) inline
Swap()
void Swap (DVLKinematicEstimate * other)
Member Data Documentation
DVL_REFERENCE_EARTH
const ReferenceType DVL_REFERENCE_EARTH static
Initial value:
=
    DVLKinematicEstimate_ReferenceType_DVL_REFERENCE_EARTH
DVL_REFERENCE_SHIP
const ReferenceType DVL_REFERENCE_SHIP static
Initial value:
=
    DVLKinematicEstimate_ReferenceType_DVL_REFERENCE_SHIP
DVL_REFERENCE_UNSPECIFIED
const ReferenceType DVL_REFERENCE_UNSPECIFIED static
Initial value:
=
    DVLKinematicEstimate_ReferenceType_DVL_REFERENCE_UNSPECIFIED
kCovarianceFieldNumber
const int kCovarianceFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kMeanFieldNumber
const int kMeanFieldNumber = 2 static
kReferenceFieldNumber
const int kReferenceFieldNumber = 1 static
ReferenceType_ARRAYSIZE
const int ReferenceType_ARRAYSIZE static
Initial value:
=
    DVLKinematicEstimate_ReferenceType_ReferenceType_ARRAYSIZE
ReferenceType_MAX
const ReferenceType ReferenceType_MAX static
Initial value:
=
    DVLKinematicEstimate_ReferenceType_ReferenceType_MAX
ReferenceType_MIN
const ReferenceType ReferenceType_MIN static
Initial value:
=
    DVLKinematicEstimate_ReferenceType_ReferenceType_MIN
The documentation for this class was generated from the following file:
dvl_kinematic_estimate.pb.h