Gazebo Msgs: UserCmd Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
UserCmd Class Reference
#include <user_cmd.pb.h>
Public Types
typedef UserCmd_Type Type
Public Member Functions
UserCmd ()
UserCmd (const UserCmd &from)
virtual ~UserCmd ()
::gz::msgs::Light * add_light ()
::gz::msgs::Model * add_model ()
size_t ByteSizeLong () const final
void Clear () final
void clear_description ()
void clear_entity_name ()
void clear_header ()
void clear_id ()
void clear_light ()
void clear_model ()
void clear_type ()
void clear_world_control ()
void clear_wrench ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const UserCmd &from)
const ::std::string & description () const
const ::std::string & entity_name () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_world_control () const
bool has_wrench () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::google::protobuf::RepeatedPtrField< ::gz::msgs::Light > & light () const
const ::gz::msgs::Light & light (int index) const
int light_size () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const UserCmd &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::google::protobuf::RepeatedPtrField< ::gz::msgs::Model > & model () const
const ::gz::msgs::Model & model (int index) const
int model_size () const
::std::string * mutable_description ()
::std::string * mutable_entity_name ()
::gz::msgs::Header * mutable_header ()
::google::protobuf::RepeatedPtrField< ::gz::msgs::Light > * mutable_light ()
::gz::msgs::Light * mutable_light (int index)
::google::protobuf::RepeatedPtrField< ::gz::msgs::Model > * mutable_model ()
::gz::msgs::Model * mutable_model (int index)
::gz::msgs::WorldControl * mutable_world_control ()
::gz::msgs::Wrench * mutable_wrench ()
UserCmd * New () const final
UserCmd * New (::google::protobuf::Arena *arena) const final
UserCmd & operator= (const UserCmd &from)
::std::string * release_description ()
::std::string * release_entity_name ()
::gz::msgs::Header * release_header ()
::gz::msgs::WorldControl * release_world_control ()
::gz::msgs::Wrench * release_wrench ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_description (::std::string *description)
void set_allocated_entity_name (::std::string *entity_name)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_world_control (::gz::msgs::WorldControl *world_control)
void set_allocated_wrench (::gz::msgs::Wrench *wrench)
void set_description (const ::std::string &value)
void set_description (const char *value)
void set_description (const char *value, size_t size)
void set_entity_name (const ::std::string &value)
void set_entity_name (const char *value)
void set_entity_name (const char *value, size_t size)
void set_id (::google::protobuf::uint32 value)
void set_type (::gz::msgs::UserCmd_Type value)
void Swap (UserCmd *other)
::gz::msgs::UserCmd_Type type () const
const ::gz::msgs::WorldControl & world_control () const
const ::gz::msgs::Wrench & wrench () const
Static Public Member Functions
static const UserCmd & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const UserCmd * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const int kDescriptionFieldNumber = 3
static const int kEntityNameFieldNumber = 7
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kLightFieldNumber = 6
static const int kModelFieldNumber = 5
static const int kTypeFieldNumber = 4
static const int kWorldControlFieldNumber = 8
static const int kWrenchFieldNumber = 9
static const Type MOVING
static const Type SCALING
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
static const Type WORLD_CONTROL
static const Type WRENCH
Member Typedef Documentation
Type
typedef UserCmd_Type Type
Constructor & Destructor Documentation
UserCmd() [1/2]
UserCmd ()
~UserCmd()
virtual ~UserCmd () virtual
UserCmd() [2/2]
UserCmd (const UserCmd & from)
Member Function Documentation
add_light()
gz::msgs::Light * add_light () inline
add_model()
gz::msgs::Model * add_model () inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_description()
void clear_description () inline
clear_entity_name()
void clear_entity_name () inline
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_light()
void clear_light ()
clear_model()
void clear_model ()
clear_type()
void clear_type () inline
clear_world_control()
void clear_world_control ()
clear_wrench()
void clear_wrench ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const UserCmd & from)
default_instance()
static const UserCmd& default_instance () static
description()
const ::std::string & description () const inline
Referenced by UserCmd::set_allocated_description().
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
entity_name()
const ::std::string & entity_name () const inline
Referenced by UserCmd::set_allocated_entity_name().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References UserCmd::internal_default_instance().
has_world_control()
bool has_world_control () const inline
References UserCmd::internal_default_instance().
has_wrench()
bool has_wrench () const inline
References UserCmd::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by UserCmd::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const UserCmd* internal_default_instance () inline static
References gz::msgs::_UserCmd_default_instance_.
Referenced by UserCmd::has_header(), UserCmd::has_world_control(), and UserCmd::has_wrench().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
light() [1/2]
const ::google::protobuf::RepeatedPtrField<::gz::msgs::Light > & light () const inline
light() [2/2]
const ::gz::msgs::Light & light (int index) const inline
light_size()
int light_size () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const UserCmd & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
model() [1/2]
const ::google::protobuf::RepeatedPtrField<::gz::msgs::Model > & model () const inline
model() [2/2]
const ::gz::msgs::Model & model (int index) const inline
model_size()
int model_size () const inline
mutable_description()
std::string * mutable_description () inline
mutable_entity_name()
std::string * mutable_entity_name () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_light() [1/2]
google::protobuf::RepeatedPtrField<::gz::msgs::Light > * mutable_light () inline
mutable_light() [2/2]
gz::msgs::Light * mutable_light (int index) inline
mutable_model() [1/2]
google::protobuf::RepeatedPtrField<::gz::msgs::Model > * mutable_model () inline
mutable_model() [2/2]
gz::msgs::Model * mutable_model (int index) inline
mutable_world_control()
gz::msgs::WorldControl * mutable_world_control () inline
mutable_wrench()
gz::msgs::Wrench * mutable_wrench () inline
New() [1/2]
UserCmd* New () const inline final
New() [2/2]
UserCmd* New (::google::protobuf::Arena * arena) const inline final
operator=()
UserCmd& operator= (const UserCmd & from) inline
release_description()
std::string * release_description () inline
release_entity_name()
std::string * release_entity_name () inline
release_header()
gz::msgs::Header * release_header () inline
release_world_control()
gz::msgs::WorldControl * release_world_control () inline
release_wrench()
gz::msgs::Wrench * release_wrench () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_description()
void set_allocated_description (::std::string * description) inline
References UserCmd::description().
set_allocated_entity_name()
void set_allocated_entity_name (::std::string * entity_name) inline
References UserCmd::entity_name().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References UserCmd::header().
set_allocated_world_control()
void set_allocated_world_control (::gz::msgs::WorldControl * world_control) inline
References UserCmd::world_control().
set_allocated_wrench()
void set_allocated_wrench (::gz::msgs::Wrench * wrench) inline
References UserCmd::wrench().
set_description() [1/3]
void set_description (const ::std::string & value) inline
set_description() [2/3]
void set_description (const char * value) inline
set_description() [3/3]
void set_description (const char * value, size_t size) inline
set_entity_name() [1/3]
void set_entity_name (const ::std::string & value) inline
set_entity_name() [2/3]
void set_entity_name (const char * value) inline
set_entity_name() [3/3]
void set_entity_name (const char * value, size_t size) inline
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_type()
void set_type (::gz::msgs::UserCmd_Type value) inline
Swap()
void Swap (UserCmd * other)
type()
gz::msgs::UserCmd_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References gz::msgs::UserCmd_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References gz::msgs::UserCmd_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References gz::msgs::UserCmd_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References gz::msgs::UserCmd_Type_Parse().
world_control()
const ::gz::msgs::WorldControl & world_control () const inline
References gz::msgs::_WorldControl_default_instance_.
Referenced by UserCmd::set_allocated_world_control().
wrench()
const ::gz::msgs::Wrench & wrench () const inline
References gz::msgs::_Wrench_default_instance_.
Referenced by UserCmd::set_allocated_wrench().
Member Data Documentation
kDescriptionFieldNumber
const int kDescriptionFieldNumber = 3 static
kEntityNameFieldNumber
const int kEntityNameFieldNumber = 7 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLightFieldNumber
const int kLightFieldNumber = 6 static
kModelFieldNumber
const int kModelFieldNumber = 5 static
kTypeFieldNumber
const int kTypeFieldNumber = 4 static
kWorldControlFieldNumber
const int kWorldControlFieldNumber = 8 static
kWrenchFieldNumber
const int kWrenchFieldNumber = 9 static
MOVING
const Type MOVING static
Initial value:
=
    UserCmd_Type_MOVING
SCALING
const Type SCALING static
Initial value:
=
    UserCmd_Type_SCALING
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    UserCmd_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    UserCmd_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    UserCmd_Type_Type_MIN
WORLD_CONTROL
const Type WORLD_CONTROL static
Initial value:
=
    UserCmd_Type_WORLD_CONTROL
WRENCH
const Type WRENCH static
Initial value:
=
    UserCmd_Type_WRENCH
The documentation for this class was generated from the following file:
user_cmd.pb.h