Gazebo Msgs: FuelMetadata_Model Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
FuelMetadata_Model Class Reference
#include <fuel_metadata.pb.h>
Public Member Functions
FuelMetadata_Model ()
FuelMetadata_Model (const FuelMetadata_Model &from)
virtual ~FuelMetadata_Model ()
size_t ByteSizeLong () const final
void Clear () final
void clear_file ()
void clear_file_format ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const FuelMetadata_Model &from)
const ::std::string & file () const
const ::gz::msgs::VersionedName & file_format () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_file_format () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const FuelMetadata_Model &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_file ()
::gz::msgs::VersionedName * mutable_file_format ()
FuelMetadata_Model * New () const final
FuelMetadata_Model * New (::google::protobuf::Arena *arena) const final
FuelMetadata_Model & operator= (const FuelMetadata_Model &from)
::std::string * release_file ()
::gz::msgs::VersionedName * release_file_format ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_file (::std::string *file)
void set_allocated_file_format (::gz::msgs::VersionedName *file_format)
void set_file (const ::std::string &value)
void set_file (const char *value)
void set_file (const char *value, size_t size)
void Swap (FuelMetadata_Model *other)
Static Public Member Functions
static const FuelMetadata_Model & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const FuelMetadata_Model * internal_default_instance ()
Static Public Attributes
static const int kFileFieldNumber = 1
static const int kFileFormatFieldNumber = 2
static constexpr int kIndexInFileMessages
Constructor & Destructor Documentation
FuelMetadata_Model() [1/2]
FuelMetadata_Model ()
~FuelMetadata_Model()
virtual ~FuelMetadata_Model () virtual
FuelMetadata_Model() [2/2]
FuelMetadata_Model (const FuelMetadata_Model & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_file()
void clear_file () inline
clear_file_format()
void clear_file_format ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const FuelMetadata_Model & from)
default_instance()
static const FuelMetadata_Model& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
file()
const ::std::string & file () const inline
Referenced by FuelMetadata_Model::set_allocated_file().
file_format()
const ::gz::msgs::VersionedName & file_format () const inline
References gz::msgs::_VersionedName_default_instance_.
Referenced by FuelMetadata_Model::set_allocated_file_format().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_file_format()
bool has_file_format () const inline
References FuelMetadata_Model::internal_default_instance().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const FuelMetadata_Model* internal_default_instance () inline static
References gz::msgs::_FuelMetadata_Model_default_instance_.
Referenced by FuelMetadata_Model::has_file_format().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const FuelMetadata_Model & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_file()
std::string * mutable_file () inline
mutable_file_format()
gz::msgs::VersionedName * mutable_file_format () inline
New() [1/2]
FuelMetadata_Model* New () const inline final
New() [2/2]
FuelMetadata_Model* New (::google::protobuf::Arena * arena) const inline final
operator=()
FuelMetadata_Model& operator= (const FuelMetadata_Model & from) inline
release_file()
std::string * release_file () inline
release_file_format()
gz::msgs::VersionedName * release_file_format () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_file()
void set_allocated_file (::std::string * file) inline
References FuelMetadata_Model::file().
set_allocated_file_format()
void set_allocated_file_format (::gz::msgs::VersionedName * file_format) inline
References FuelMetadata_Model::file_format().
set_file() [1/3]
void set_file (const ::std::string & value) inline
set_file() [2/3]
void set_file (const char * value) inline
set_file() [3/3]
void set_file (const char * value, size_t size) inline
Swap()
void Swap (FuelMetadata_Model * other)
Member Data Documentation
kFileFieldNumber
const int kFileFieldNumber = 1 static
kFileFormatFieldNumber
const int kFileFormatFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    2
The documentation for this class was generated from the following file:
fuel_metadata.pb.h