Gazebo Msgs: ModelConfiguration Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
ModelConfiguration Class Reference
#include <model_configuration.pb.h>
Public Member Functions
ModelConfiguration ()
ModelConfiguration (const ModelConfiguration &from)
virtual ~ModelConfiguration ()
::std::string * add_joint_names ()
void add_joint_names (const ::std::string &value)
void add_joint_names (const char *value)
void add_joint_names (const char *value, size_t size)
void add_joint_positions (double value)
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_joint_names ()
void clear_joint_positions ()
void clear_link_name ()
void clear_pose ()
void clear_time ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const ModelConfiguration &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_pose () const
bool has_time () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::google::protobuf::RepeatedPtrField< ::std::string > & joint_names () const
const ::std::string & joint_names (int index) const
int joint_names_size () const
const ::google::protobuf::RepeatedField< double > & joint_positions () const
double joint_positions (int index) const
int joint_positions_size () const
const ::std::string & link_name () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ModelConfiguration &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Header * mutable_header ()
::google::protobuf::RepeatedPtrField< ::std::string > * mutable_joint_names ()
::std::string * mutable_joint_names (int index)
::google::protobuf::RepeatedField< double > * mutable_joint_positions ()
::std::string * mutable_link_name ()
::gz::msgs::Pose * mutable_pose ()
::gz::msgs::Time * mutable_time ()
ModelConfiguration * New () const final
ModelConfiguration * New (::google::protobuf::Arena *arena) const final
ModelConfiguration & operator= (const ModelConfiguration &from)
const ::gz::msgs::Pose & pose () const
::gz::msgs::Header * release_header ()
::std::string * release_link_name ()
::gz::msgs::Pose * release_pose ()
::gz::msgs::Time * release_time ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_link_name (::std::string *link_name)
void set_allocated_pose (::gz::msgs::Pose *pose)
void set_allocated_time (::gz::msgs::Time *time)
void set_joint_names (int index, const ::std::string &value)
void set_joint_names (int index, const char *value)
void set_joint_names (int index, const char *value, size_t size)
void set_joint_positions (int index, double value)
void set_link_name (const ::std::string &value)
void set_link_name (const char *value)
void set_link_name (const char *value, size_t size)
void Swap (ModelConfiguration *other)
const ::gz::msgs::Time & time () const
Static Public Member Functions
static const ModelConfiguration & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const ModelConfiguration * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kJointNamesFieldNumber = 3
static const int kJointPositionsFieldNumber = 4
static const int kLinkNameFieldNumber = 6
static const int kPoseFieldNumber = 5
static const int kTimeFieldNumber = 2
Constructor & Destructor Documentation
ModelConfiguration() [1/2]
ModelConfiguration ()
~ModelConfiguration()
virtual ~ModelConfiguration () virtual
ModelConfiguration() [2/2]
ModelConfiguration (const ModelConfiguration & from)
Member Function Documentation
add_joint_names() [1/4]
std::string * add_joint_names () inline
add_joint_names() [2/4]
void add_joint_names (const ::std::string & value) inline
add_joint_names() [3/4]
void add_joint_names (const char * value) inline
add_joint_names() [4/4]
void add_joint_names (const char * value, size_t size) inline
add_joint_positions()
void add_joint_positions (double value) inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_joint_names()
void clear_joint_names () inline
clear_joint_positions()
void clear_joint_positions () inline
clear_link_name()
void clear_link_name () inline
clear_pose()
void clear_pose ()
clear_time()
void clear_time ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const ModelConfiguration & from)
default_instance()
static const ModelConfiguration& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References ModelConfiguration::internal_default_instance().
has_pose()
bool has_pose () const inline
References ModelConfiguration::internal_default_instance().
has_time()
bool has_time () const inline
References ModelConfiguration::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by ModelConfiguration::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const ModelConfiguration* internal_default_instance () inline static
References gz::msgs::_ModelConfiguration_default_instance_.
Referenced by ModelConfiguration::has_header(), ModelConfiguration::has_pose(), and ModelConfiguration::has_time().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
joint_names() [1/2]
const ::google::protobuf::RepeatedPtrField<::std::string > & joint_names () const inline
joint_names() [2/2]
const ::std::string & joint_names (int index) const inline
joint_names_size()
int joint_names_size () const inline
joint_positions() [1/2]
const ::google::protobuf::RepeatedField< double > & joint_positions () const inline
joint_positions() [2/2]
double joint_positions (int index) const inline
joint_positions_size()
int joint_positions_size () const inline
link_name()
const ::std::string & link_name () const inline
Referenced by ModelConfiguration::set_allocated_link_name().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const ModelConfiguration & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_joint_names() [1/2]
google::protobuf::RepeatedPtrField<::std::string > * mutable_joint_names () inline
mutable_joint_names() [2/2]
std::string * mutable_joint_names (int index) inline
mutable_joint_positions()
google::protobuf::RepeatedField< double > * mutable_joint_positions () inline
mutable_link_name()
std::string * mutable_link_name () inline
mutable_pose()
gz::msgs::Pose * mutable_pose () inline
mutable_time()
gz::msgs::Time * mutable_time () inline
New() [1/2]
ModelConfiguration* New () const inline final
New() [2/2]
ModelConfiguration* New (::google::protobuf::Arena * arena) const inline final
operator=()
ModelConfiguration& operator= (const ModelConfiguration & from) inline
pose()
const ::gz::msgs::Pose & pose () const inline
References gz::msgs::_Pose_default_instance_.
Referenced by ModelConfiguration::set_allocated_pose().
release_header()
gz::msgs::Header * release_header () inline
release_link_name()
std::string * release_link_name () inline
release_pose()
gz::msgs::Pose * release_pose () inline
release_time()
gz::msgs::Time * release_time () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References ModelConfiguration::header().
set_allocated_link_name()
void set_allocated_link_name (::std::string * link_name) inline
References ModelConfiguration::link_name().
set_allocated_pose()
void set_allocated_pose (::gz::msgs::Pose * pose) inline
References ModelConfiguration::pose().
set_allocated_time()
void set_allocated_time (::gz::msgs::Time * time) inline
References ModelConfiguration::time().
set_joint_names() [1/3]
void set_joint_names (int index, const ::std::string & value) inline
set_joint_names() [2/3]
void set_joint_names (int index, const char * value) inline
set_joint_names() [3/3]
void set_joint_names (int index, const char * value, size_t size) inline
set_joint_positions()
void set_joint_positions (int index, double value) inline
set_link_name() [1/3]
void set_link_name (const ::std::string & value) inline
set_link_name() [2/3]
void set_link_name (const char * value) inline
set_link_name() [3/3]
void set_link_name (const char * value, size_t size) inline
Swap()
void Swap (ModelConfiguration * other)
time()
const ::gz::msgs::Time & time () const inline
References gz::msgs::_Time_default_instance_.
Referenced by ModelConfiguration::set_allocated_time().
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kJointNamesFieldNumber
const int kJointNamesFieldNumber = 3 static
kJointPositionsFieldNumber
const int kJointPositionsFieldNumber = 4 static
kLinkNameFieldNumber
const int kLinkNameFieldNumber = 6 static
kPoseFieldNumber
const int kPoseFieldNumber = 5 static
kTimeFieldNumber
const int kTimeFieldNumber = 2 static
The documentation for this class was generated from the following file:
model_configuration.pb.h