Gazebo Msgs: BatteryState Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
BatteryState Class Reference
#include <battery_state.pb.h>
Public Types
typedef BatteryState_PowerSupplyStatus PowerSupplyStatus
Public Member Functions
BatteryState ()
BatteryState (const BatteryState &from)
virtual ~BatteryState ()
size_t ByteSizeLong () const final
double capacity () const
double charge () const
void Clear () final
void clear_capacity ()
void clear_charge ()
void clear_current ()
void clear_header ()
void clear_percentage ()
void clear_power_supply_status ()
void clear_voltage ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const BatteryState &from)
double current () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const BatteryState &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Header * mutable_header ()
BatteryState * New () const final
BatteryState * New (::google::protobuf::Arena *arena) const final
BatteryState & operator= (const BatteryState &from)
double percentage () const
::gz::msgs::BatteryState_PowerSupplyStatus power_supply_status () const
::gz::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::gz::msgs::Header *header)
void set_capacity (double value)
void set_charge (double value)
void set_current (double value)
void set_percentage (double value)
void set_power_supply_status (::gz::msgs::BatteryState_PowerSupplyStatus value)
void set_voltage (double value)
void Swap (BatteryState *other)
double voltage () const
Static Public Member Functions
static const BatteryState & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const BatteryState * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * PowerSupplyStatus_descriptor ()
static bool PowerSupplyStatus_IsValid (int value)
static const ::std::string & PowerSupplyStatus_Name (PowerSupplyStatus value)
static bool PowerSupplyStatus_Parse (const ::std::string &name, PowerSupplyStatus *value)
Static Public Attributes
static const PowerSupplyStatus CHARGING
static const PowerSupplyStatus DISCHARGING
static const PowerSupplyStatus FULL
static const int kCapacityFieldNumber = 5
static const int kChargeFieldNumber = 4
static const int kCurrentFieldNumber = 3
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kPercentageFieldNumber = 6
static const int kPowerSupplyStatusFieldNumber = 7
static const int kVoltageFieldNumber = 2
static const PowerSupplyStatus NOT_CHARGING
static const int PowerSupplyStatus_ARRAYSIZE
static const PowerSupplyStatus PowerSupplyStatus_MAX
static const PowerSupplyStatus PowerSupplyStatus_MIN
static const PowerSupplyStatus UNKNOWN
Member Typedef Documentation
PowerSupplyStatus
typedef BatteryState_PowerSupplyStatus PowerSupplyStatus
Constructor & Destructor Documentation
BatteryState() [1/2]
BatteryState ()
~BatteryState()
virtual ~BatteryState () virtual
BatteryState() [2/2]
BatteryState (const BatteryState & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
capacity()
double capacity () const inline
charge()
double charge () const inline
Clear()
void Clear () final
clear_capacity()
void clear_capacity () inline
clear_charge()
void clear_charge () inline
clear_current()
void clear_current () inline
clear_header()
void clear_header ()
clear_percentage()
void clear_percentage () inline
clear_power_supply_status()
void clear_power_supply_status () inline
clear_voltage()
void clear_voltage () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const BatteryState & from)
current()
double current () const inline
default_instance()
static const BatteryState& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References BatteryState::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by BatteryState::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const BatteryState* internal_default_instance () inline static
References gz::msgs::_BatteryState_default_instance_.
Referenced by BatteryState::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const BatteryState & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
gz::msgs::Header * mutable_header () inline
New() [1/2]
BatteryState* New () const inline final
New() [2/2]
BatteryState* New (::google::protobuf::Arena * arena) const inline final
operator=()
BatteryState& operator= (const BatteryState & from) inline
percentage()
double percentage () const inline
power_supply_status()
gz::msgs::BatteryState_PowerSupplyStatus power_supply_status () const inline
PowerSupplyStatus_descriptor()
static const ::google::protobuf::EnumDescriptor* PowerSupplyStatus_descriptor () inline static
References gz::msgs::BatteryState_PowerSupplyStatus_descriptor().
PowerSupplyStatus_IsValid()
static bool PowerSupplyStatus_IsValid (int value) inline static
References gz::msgs::BatteryState_PowerSupplyStatus_IsValid().
PowerSupplyStatus_Name()
static const ::std::string& PowerSupplyStatus_Name (PowerSupplyStatus value) inline static
References gz::msgs::BatteryState_PowerSupplyStatus_Name().
PowerSupplyStatus_Parse()
static bool PowerSupplyStatus_Parse (const ::std::string & name, PowerSupplyStatus * value) inline static
References gz::msgs::BatteryState_PowerSupplyStatus_Parse().
release_header()
gz::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References BatteryState::header().
set_capacity()
void set_capacity (double value) inline
set_charge()
void set_charge (double value) inline
set_current()
void set_current (double value) inline
set_percentage()
void set_percentage (double value) inline
set_power_supply_status()
void set_power_supply_status (::gz::msgs::BatteryState_PowerSupplyStatus value) inline
set_voltage()
void set_voltage (double value) inline
Swap()
void Swap (BatteryState * other)
voltage()
double voltage () const inline
Member Data Documentation
CHARGING
const PowerSupplyStatus CHARGING static
Initial value:
=
    BatteryState_PowerSupplyStatus_CHARGING
DISCHARGING
const PowerSupplyStatus DISCHARGING static
Initial value:
=
    BatteryState_PowerSupplyStatus_DISCHARGING
FULL
const PowerSupplyStatus FULL static
Initial value:
=
    BatteryState_PowerSupplyStatus_FULL
kCapacityFieldNumber
const int kCapacityFieldNumber = 5 static
kChargeFieldNumber
const int kChargeFieldNumber = 4 static
kCurrentFieldNumber
const int kCurrentFieldNumber = 3 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kPercentageFieldNumber
const int kPercentageFieldNumber = 6 static
kPowerSupplyStatusFieldNumber
const int kPowerSupplyStatusFieldNumber = 7 static
kVoltageFieldNumber
const int kVoltageFieldNumber = 2 static
NOT_CHARGING
const PowerSupplyStatus NOT_CHARGING static
Initial value:
=
    BatteryState_PowerSupplyStatus_NOT_CHARGING
PowerSupplyStatus_ARRAYSIZE
const int PowerSupplyStatus_ARRAYSIZE static
Initial value:
=
    BatteryState_PowerSupplyStatus_PowerSupplyStatus_ARRAYSIZE
PowerSupplyStatus_MAX
const PowerSupplyStatus PowerSupplyStatus_MAX static
Initial value:
=
    BatteryState_PowerSupplyStatus_PowerSupplyStatus_MAX
PowerSupplyStatus_MIN
const PowerSupplyStatus PowerSupplyStatus_MIN static
Initial value:
=
    BatteryState_PowerSupplyStatus_PowerSupplyStatus_MIN
UNKNOWN
const PowerSupplyStatus UNKNOWN static
Initial value:
=
    BatteryState_PowerSupplyStatus_UNKNOWN
The documentation for this class was generated from the following file:
battery_state.pb.h