Gazebo Msgs: Version Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Version Class Reference
#include <version.pb.h>
Public Member Functions
Version ()
Version (const Version &from)
virtual ~Version ()
const ::std::string & build () const
size_t ByteSizeLong () const final
void Clear () final
void clear_build ()
void clear_major ()
void clear_minor ()
void clear_patch ()
void clear_prerelease ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Version &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
::google::protobuf::int32 major () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Version &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::google::protobuf::int32 minor () const
::std::string * mutable_build ()
::std::string * mutable_prerelease ()
Version * New () const final
Version * New (::google::protobuf::Arena *arena) const final
Version & operator= (const Version &from)
::google::protobuf::int32 patch () const
const ::std::string & prerelease () const
::std::string * release_build ()
::std::string * release_prerelease ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_build (::std::string *build)
void set_allocated_prerelease (::std::string *prerelease)
void set_build (const ::std::string &value)
void set_build (const char *value)
void set_build (const char *value, size_t size)
void set_major (::google::protobuf::int32 value)
void set_minor (::google::protobuf::int32 value)
void set_patch (::google::protobuf::int32 value)
void set_prerelease (const ::std::string &value)
void set_prerelease (const char *value)
void set_prerelease (const char *value, size_t size)
void Swap (Version *other)
Static Public Member Functions
static const Version & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Version * internal_default_instance ()
Static Public Attributes
static const int kBuildFieldNumber = 5
static constexpr int kIndexInFileMessages
static const int kMajorFieldNumber = 1
static const int kMinorFieldNumber = 2
static const int kPatchFieldNumber = 3
static const int kPrereleaseFieldNumber = 4
Constructor & Destructor Documentation
Version() [1/2]
Version ()
~Version()
virtual ~Version () virtual
Version() [2/2]
Version (const Version & from)
Member Function Documentation
build()
const ::std::string & build () const inline
Referenced by Version::set_allocated_build().
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_build()
void clear_build () inline
clear_major()
void clear_major () inline
clear_minor()
void clear_minor () inline
clear_patch()
void clear_patch () inline
clear_prerelease()
void clear_prerelease () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Version & from)
default_instance()
static const Version& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Version* internal_default_instance () inline static
References gz::msgs::_Version_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
major()
google::protobuf::int32 major () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Version & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
minor()
google::protobuf::int32 minor () const inline
mutable_build()
std::string * mutable_build () inline
mutable_prerelease()
std::string * mutable_prerelease () inline
New() [1/2]
Version* New () const inline final
New() [2/2]
Version* New (::google::protobuf::Arena * arena) const inline final
operator=()
Version& operator= (const Version & from) inline
patch()
google::protobuf::int32 patch () const inline
prerelease()
const ::std::string & prerelease () const inline
Referenced by Version::set_allocated_prerelease().
release_build()
std::string * release_build () inline
release_prerelease()
std::string * release_prerelease () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_build()
void set_allocated_build (::std::string * build) inline
References Version::build().
set_allocated_prerelease()
void set_allocated_prerelease (::std::string * prerelease) inline
References Version::prerelease().
set_build() [1/3]
void set_build (const ::std::string & value) inline
set_build() [2/3]
void set_build (const char * value) inline
set_build() [3/3]
void set_build (const char * value, size_t size) inline
set_major()
void set_major (::google::protobuf::int32 value) inline
set_minor()
void set_minor (::google::protobuf::int32 value) inline
set_patch()
void set_patch (::google::protobuf::int32 value) inline
set_prerelease() [1/3]
void set_prerelease (const ::std::string & value) inline
set_prerelease() [2/3]
void set_prerelease (const char * value) inline
set_prerelease() [3/3]
void set_prerelease (const char * value, size_t size) inline
Swap()
void Swap (Version * other)
Member Data Documentation
kBuildFieldNumber
const int kBuildFieldNumber = 5 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kMajorFieldNumber
const int kMajorFieldNumber = 1 static
kMinorFieldNumber
const int kMinorFieldNumber = 2 static
kPatchFieldNumber
const int kPatchFieldNumber = 3 static
kPrereleaseFieldNumber
const int kPrereleaseFieldNumber = 4 static
The documentation for this class was generated from the following file:
version.pb.h