Gazebo Msgs: Bytes Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Bytes Class Reference
#include <bytes.pb.h>
Public Member Functions
Bytes ()
Bytes (const Bytes &from)
virtual ~Bytes ()
size_t ByteSizeLong () const final
void Clear () final
void clear_data ()
void clear_header ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Bytes &from)
const ::std::string & data () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Bytes &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_data ()
::gz::msgs::Header * mutable_header ()
Bytes * New () const final
Bytes * New (::google::protobuf::Arena *arena) const final
Bytes & operator= (const Bytes &from)
::std::string * release_data ()
::gz::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_data (::std::string *data)
void set_allocated_header (::gz::msgs::Header *header)
void set_data (const ::std::string &value)
void set_data (const char *value)
void set_data (const void *value, size_t size)
void Swap (Bytes *other)
Static Public Member Functions
static const Bytes & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Bytes * internal_default_instance ()
Static Public Attributes
static const int kDataFieldNumber = 2
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
Constructor & Destructor Documentation
Bytes() [1/2]
Bytes ()
~Bytes()
virtual ~Bytes () virtual
Bytes() [2/2]
Bytes (const Bytes & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_data()
void clear_data () inline
clear_header()
void clear_header ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Bytes & from)
data()
const ::std::string & data () const inline
Referenced by Bytes::set_allocated_data().
default_instance()
static const Bytes& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Bytes::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by Bytes::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Bytes* internal_default_instance () inline static
References gz::msgs::_Bytes_default_instance_.
Referenced by Bytes::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Bytes & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_data()
std::string * mutable_data () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
New() [1/2]
Bytes* New () const inline final
New() [2/2]
Bytes* New (::google::protobuf::Arena * arena) const inline final
operator=()
Bytes& operator= (const Bytes & from) inline
release_data()
std::string * release_data () inline
release_header()
gz::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_data()
void set_allocated_data (::std::string * data) inline
References Bytes::data().
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References Bytes::header().
set_data() [1/3]
void set_data (const ::std::string & value) inline
set_data() [2/3]
void set_data (const char * value) inline
set_data() [3/3]
void set_data (const void * value, size_t size) inline
Swap()
void Swap (Bytes * other)
Member Data Documentation
kDataFieldNumber
const int kDataFieldNumber = 2 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
The documentation for this class was generated from the following file:
bytes.pb.h