Gazebo Msgs: Joint Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Joint Class Reference
#include <joint.pb.h>
Public Types
typedef Joint_Gearbox Gearbox
typedef Joint_Screw Screw
typedef Joint_Type Type
Public Member Functions
Joint ()
Joint (const Joint &from)
virtual ~Joint ()
::gz::msgs::Sensor * add_sensor ()
const ::gz::msgs::Axis & axis1 () const
const ::gz::msgs::Axis & axis2 () const
double bounce () const
size_t ByteSizeLong () const final
double cfm () const
const ::std::string & child () const
::google::protobuf::uint32 child_id () const
void Clear () final
void clear_axis1 ()
void clear_axis2 ()
void clear_bounce ()
void clear_cfm ()
void clear_child ()
void clear_child_id ()
void clear_fudge_factor ()
void clear_gearbox ()
void clear_header ()
void clear_id ()
void clear_limit_cfm ()
void clear_limit_erp ()
void clear_name ()
void clear_parent ()
void clear_parent_id ()
void clear_pose ()
void clear_screw ()
void clear_sensor ()
void clear_suspension_cfm ()
void clear_suspension_erp ()
void clear_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Joint &from)
double fudge_factor () const
const ::gz::msgs::Joint_Gearbox & gearbox () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_axis1 () const
bool has_axis2 () const
bool has_gearbox () const
bool has_header () const
bool has_pose () const
bool has_screw () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
double limit_cfm () const
double limit_erp () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Joint &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Axis * mutable_axis1 ()
::gz::msgs::Axis * mutable_axis2 ()
::std::string * mutable_child ()
::gz::msgs::Joint_Gearbox * mutable_gearbox ()
::gz::msgs::Header * mutable_header ()
::std::string * mutable_name ()
::std::string * mutable_parent ()
::gz::msgs::Pose * mutable_pose ()
::gz::msgs::Joint_Screw * mutable_screw ()
::google::protobuf::RepeatedPtrField< ::gz::msgs::Sensor > * mutable_sensor ()
::gz::msgs::Sensor * mutable_sensor (int index)
const ::std::string & name () const
Joint * New () const final
Joint * New (::google::protobuf::Arena *arena) const final
Joint & operator= (const Joint &from)
const ::std::string & parent () const
::google::protobuf::uint32 parent_id () const
const ::gz::msgs::Pose & pose () const
::gz::msgs::Axis * release_axis1 ()
::gz::msgs::Axis * release_axis2 ()
::std::string * release_child ()
::gz::msgs::Joint_Gearbox * release_gearbox ()
::gz::msgs::Header * release_header ()
::std::string * release_name ()
::std::string * release_parent ()
::gz::msgs::Pose * release_pose ()
::gz::msgs::Joint_Screw * release_screw ()
const ::gz::msgs::Joint_Screw & screw () const
const ::google::protobuf::RepeatedPtrField< ::gz::msgs::Sensor > & sensor () const
const ::gz::msgs::Sensor & sensor (int index) const
int sensor_size () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_axis1 (::gz::msgs::Axis *axis1)
void set_allocated_axis2 (::gz::msgs::Axis *axis2)
void set_allocated_child (::std::string *child)
void set_allocated_gearbox (::gz::msgs::Joint_Gearbox *gearbox)
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_parent (::std::string *parent)
void set_allocated_pose (::gz::msgs::Pose *pose)
void set_allocated_screw (::gz::msgs::Joint_Screw *screw)
void set_bounce (double value)
void set_cfm (double value)
void set_child (const ::std::string &value)
void set_child (const char *value)
void set_child (const char *value, size_t size)
void set_child_id (::google::protobuf::uint32 value)
void set_fudge_factor (double value)
void set_id (::google::protobuf::uint32 value)
void set_limit_cfm (double value)
void set_limit_erp (double value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_parent (const ::std::string &value)
void set_parent (const char *value)
void set_parent (const char *value, size_t size)
void set_parent_id (::google::protobuf::uint32 value)
void set_suspension_cfm (double value)
void set_suspension_erp (double value)
void set_type (::gz::msgs::Joint_Type value)
double suspension_cfm () const
double suspension_erp () const
void Swap (Joint *other)
::gz::msgs::Joint_Type type () const
Static Public Member Functions
static const Joint & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Joint * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type BALL
static const Type CONTINUOUS
static const Type FIXED
static const Type GEARBOX
static const int kAxis1FieldNumber = 10
static const int kAxis2FieldNumber = 11
static const int kBounceFieldNumber = 13
static const int kCfmFieldNumber = 12
static const int kChildFieldNumber = 7
static const int kChildIdFieldNumber = 8
static const int kFudgeFactorFieldNumber = 14
static const int kGearboxFieldNumber = 19
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kLimitCfmFieldNumber = 15
static const int kLimitErpFieldNumber = 16
static const int kNameFieldNumber = 2
static const int kParentFieldNumber = 5
static const int kParentIdFieldNumber = 6
static const int kPoseFieldNumber = 9
static const int kScrewFieldNumber = 20
static const int kSensorFieldNumber = 21
static const int kSuspensionCfmFieldNumber = 17
static const int kSuspensionErpFieldNumber = 18
static const int kTypeFieldNumber = 4
static const Type PRISMATIC
static const Type REVOLUTE
static const Type REVOLUTE2
static const Type SCREW
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
static const Type UNIVERSAL
Member Typedef Documentation
Gearbox
typedef Joint_Gearbox Gearbox
Screw
typedef Joint_Screw Screw
Type
typedef Joint_Type Type
Constructor & Destructor Documentation
Joint() [1/2]
Joint ()
~Joint()
virtual ~Joint () virtual
Joint() [2/2]
Joint (const Joint & from)
Member Function Documentation
add_sensor()
gz::msgs::Sensor * add_sensor () inline
axis1()
const ::gz::msgs::Axis & axis1 () const inline
References gz::msgs::_Axis_default_instance_.
axis2()
const ::gz::msgs::Axis & axis2 () const inline
References gz::msgs::_Axis_default_instance_.
bounce()
double bounce () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
cfm()
double cfm () const inline
child()
const ::std::string & child () const inline
child_id()
google::protobuf::uint32 child_id () const inline
Clear()
void Clear () final
clear_axis1()
void clear_axis1 ()
clear_axis2()
void clear_axis2 ()
clear_bounce()
void clear_bounce () inline
clear_cfm()
void clear_cfm () inline
clear_child()
void clear_child () inline
clear_child_id()
void clear_child_id () inline
clear_fudge_factor()
void clear_fudge_factor () inline
clear_gearbox()
void clear_gearbox () inline
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_limit_cfm()
void clear_limit_cfm () inline
clear_limit_erp()
void clear_limit_erp () inline
clear_name()
void clear_name () inline
clear_parent()
void clear_parent () inline
clear_parent_id()
void clear_parent_id () inline
clear_pose()
void clear_pose ()
clear_screw()
void clear_screw () inline
clear_sensor()
void clear_sensor ()
clear_suspension_cfm()
void clear_suspension_cfm () inline
clear_suspension_erp()
void clear_suspension_erp () inline
clear_type()
void clear_type () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Joint & from)
default_instance()
static const Joint& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
fudge_factor()
double fudge_factor () const inline
gearbox()
const ::gz::msgs::Joint_Gearbox & gearbox () const inline
References gz::msgs::_Joint_Gearbox_default_instance_.
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_axis1()
bool has_axis1 () const inline
has_axis2()
bool has_axis2 () const inline
has_gearbox()
bool has_gearbox () const inline
has_header()
bool has_header () const inline
has_pose()
bool has_pose () const inline
has_screw()
bool has_screw () const inline
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Joint* internal_default_instance () inline static
References gz::msgs::_Joint_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
limit_cfm()
double limit_cfm () const inline
limit_erp()
double limit_erp () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Joint & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_axis1()
gz::msgs::Axis * mutable_axis1 () inline
mutable_axis2()
gz::msgs::Axis * mutable_axis2 () inline
mutable_child()
std::string * mutable_child () inline
mutable_gearbox()
gz::msgs::Joint_Gearbox * mutable_gearbox () inline
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
mutable_parent()
std::string * mutable_parent () inline
mutable_pose()
gz::msgs::Pose * mutable_pose () inline
mutable_screw()
gz::msgs::Joint_Screw * mutable_screw () inline
mutable_sensor() [1/2]
google::protobuf::RepeatedPtrField<::gz::msgs::Sensor > * mutable_sensor () inline
mutable_sensor() [2/2]
gz::msgs::Sensor * mutable_sensor (int index) inline
name()
const ::std::string & name () const inline
New() [1/2]
Joint* New () const inline final
New() [2/2]
Joint* New (::google::protobuf::Arena * arena) const inline final
operator=()
Joint& operator= (const Joint & from) inline
parent()
const ::std::string & parent () const inline
parent_id()
google::protobuf::uint32 parent_id () const inline
pose()
const ::gz::msgs::Pose & pose () const inline
References gz::msgs::_Pose_default_instance_.
release_axis1()
gz::msgs::Axis * release_axis1 () inline
release_axis2()
gz::msgs::Axis * release_axis2 () inline
release_child()
std::string * release_child () inline
release_gearbox()
gz::msgs::Joint_Gearbox * release_gearbox () inline
release_header()
gz::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_parent()
std::string * release_parent () inline
release_pose()
gz::msgs::Pose * release_pose () inline
release_screw()
gz::msgs::Joint_Screw * release_screw () inline
screw()
const ::gz::msgs::Joint_Screw & screw () const inline
References gz::msgs::_Joint_Screw_default_instance_.
sensor() [1/2]
const ::google::protobuf::RepeatedPtrField<::gz::msgs::Sensor > & sensor () const inline
sensor() [2/2]
const ::gz::msgs::Sensor & sensor (int index) const inline
sensor_size()
int sensor_size () const inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_axis1()
void set_allocated_axis1 (::gz::msgs::Axis * axis1) inline
set_allocated_axis2()
void set_allocated_axis2 (::gz::msgs::Axis * axis2) inline
set_allocated_child()
void set_allocated_child (::std::string * child) inline
set_allocated_gearbox()
void set_allocated_gearbox (::gz::msgs::Joint_Gearbox * gearbox) inline
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
set_allocated_name()
void set_allocated_name (::std::string * name) inline
set_allocated_parent()
void set_allocated_parent (::std::string * parent) inline
set_allocated_pose()
void set_allocated_pose (::gz::msgs::Pose * pose) inline
set_allocated_screw()
void set_allocated_screw (::gz::msgs::Joint_Screw * screw) inline
set_bounce()
void set_bounce (double value) inline
set_cfm()
void set_cfm (double value) inline
set_child() [1/3]
void set_child (const ::std::string & value) inline
set_child() [2/3]
void set_child (const char * value) inline
set_child() [3/3]
void set_child (const char * value, size_t size) inline
set_child_id()
void set_child_id (::google::protobuf::uint32 value) inline
set_fudge_factor()
void set_fudge_factor (double value) inline
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_limit_cfm()
void set_limit_cfm (double value) inline
set_limit_erp()
void set_limit_erp (double value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_parent() [1/3]
void set_parent (const ::std::string & value) inline
set_parent() [2/3]
void set_parent (const char * value) inline
set_parent() [3/3]
void set_parent (const char * value, size_t size) inline
set_parent_id()
void set_parent_id (::google::protobuf::uint32 value) inline
set_suspension_cfm()
void set_suspension_cfm (double value) inline
set_suspension_erp()
void set_suspension_erp (double value) inline
set_type()
void set_type (::gz::msgs::Joint_Type value) inline
suspension_cfm()
double suspension_cfm () const inline
suspension_erp()
double suspension_erp () const inline
Swap()
void Swap (Joint * other)
type()
gz::msgs::Joint_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References gz::msgs::Joint_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References gz::msgs::Joint_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References gz::msgs::Joint_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References gz::msgs::Joint_Type_Parse().
Member Data Documentation
BALL
const Type BALL static
Initial value:
=
    Joint_Type_BALL
CONTINUOUS
const Type CONTINUOUS static
Initial value:
=
    Joint_Type_CONTINUOUS
FIXED
const Type FIXED static
Initial value:
=
    Joint_Type_FIXED
GEARBOX
const Type GEARBOX static
Initial value:
=
    Joint_Type_GEARBOX
kAxis1FieldNumber
const int kAxis1FieldNumber = 10 static
kAxis2FieldNumber
const int kAxis2FieldNumber = 11 static
kBounceFieldNumber
const int kBounceFieldNumber = 13 static
kCfmFieldNumber
const int kCfmFieldNumber = 12 static
kChildFieldNumber
const int kChildFieldNumber = 7 static
kChildIdFieldNumber
const int kChildIdFieldNumber = 8 static
kFudgeFactorFieldNumber
const int kFudgeFactorFieldNumber = 14 static
kGearboxFieldNumber
const int kGearboxFieldNumber = 19 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    2
kLimitCfmFieldNumber
const int kLimitCfmFieldNumber = 15 static
kLimitErpFieldNumber
const int kLimitErpFieldNumber = 16 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
kParentFieldNumber
const int kParentFieldNumber = 5 static
kParentIdFieldNumber
const int kParentIdFieldNumber = 6 static
kPoseFieldNumber
const int kPoseFieldNumber = 9 static
kScrewFieldNumber
const int kScrewFieldNumber = 20 static
kSensorFieldNumber
const int kSensorFieldNumber = 21 static
kSuspensionCfmFieldNumber
const int kSuspensionCfmFieldNumber = 17 static
kSuspensionErpFieldNumber
const int kSuspensionErpFieldNumber = 18 static
kTypeFieldNumber
const int kTypeFieldNumber = 4 static
PRISMATIC
const Type PRISMATIC static
Initial value:
=
    Joint_Type_PRISMATIC
REVOLUTE
const Type REVOLUTE static
Initial value:
=
    Joint_Type_REVOLUTE
REVOLUTE2
const Type REVOLUTE2 static
Initial value:
=
    Joint_Type_REVOLUTE2
SCREW
const Type SCREW static
Initial value:
=
    Joint_Type_SCREW
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    Joint_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    Joint_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    Joint_Type_Type_MIN
UNIVERSAL
const Type UNIVERSAL static
Initial value:
=
    Joint_Type_UNIVERSAL
The documentation for this class was generated from the following file:
joint.pb.h