Gazebo Msgs: GPS Class Reference
Gazebo Msgs
API Reference
9.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
GPS Class Reference
#include <gps.pb.h>
Public Member Functions
GPS ()
GPS (const GPS &from)
virtual ~GPS ()
double altitude () const
size_t ByteSizeLong () const final
void Clear () final
void clear_altitude ()
void clear_header ()
void clear_latitude_deg ()
void clear_link_name ()
void clear_longitude_deg ()
void clear_velocity_east ()
void clear_velocity_north ()
void clear_velocity_up ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GPS &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::gz::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
double latitude_deg () const
const ::std::string & link_name () const
double longitude_deg () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const GPS &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::gz::msgs::Header * mutable_header ()
::std::string * mutable_link_name ()
GPS * New () const final
GPS * New (::google::protobuf::Arena *arena) const final
GPS & operator= (const GPS &from)
::gz::msgs::Header * release_header ()
::std::string * release_link_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::gz::msgs::Header *header)
void set_allocated_link_name (::std::string *link_name)
void set_altitude (double value)
void set_latitude_deg (double value)
void set_link_name (const ::std::string &value)
void set_link_name (const char *value)
void set_link_name (const char *value, size_t size)
void set_longitude_deg (double value)
void set_velocity_east (double value)
void set_velocity_north (double value)
void set_velocity_up (double value)
void Swap (GPS *other)
double velocity_east () const
double velocity_north () const
double velocity_up () const
Static Public Member Functions
static const GPS & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const GPS * internal_default_instance ()
Static Public Attributes
static const int kAltitudeFieldNumber = 5
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kLatitudeDegFieldNumber = 3
static const int kLinkNameFieldNumber = 2
static const int kLongitudeDegFieldNumber = 4
static const int kVelocityEastFieldNumber = 6
static const int kVelocityNorthFieldNumber = 7
static const int kVelocityUpFieldNumber = 8
Constructor & Destructor Documentation
GPS() [1/2]
GPS ()
~GPS()
virtual ~GPS () virtual
GPS() [2/2]
GPS (const GPS & from)
Member Function Documentation
altitude()
double altitude () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_altitude()
void clear_altitude () inline
clear_header()
void clear_header ()
clear_latitude_deg()
void clear_latitude_deg () inline
clear_link_name()
void clear_link_name () inline
clear_longitude_deg()
void clear_longitude_deg () inline
clear_velocity_east()
void clear_velocity_east () inline
clear_velocity_north()
void clear_velocity_north () inline
clear_velocity_up()
void clear_velocity_up () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const GPS & from)
default_instance()
static const GPS& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References GPS::internal_default_instance().
header()
const ::gz::msgs::Header & header () const inline
References gz::msgs::_Header_default_instance_.
Referenced by GPS::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const GPS* internal_default_instance () inline static
References gz::msgs::_GPS_default_instance_.
Referenced by GPS::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
latitude_deg()
double latitude_deg () const inline
link_name()
const ::std::string & link_name () const inline
Referenced by GPS::set_allocated_link_name().
longitude_deg()
double longitude_deg () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const GPS & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
gz::msgs::Header * mutable_header () inline
mutable_link_name()
std::string * mutable_link_name () inline
New() [1/2]
GPS* New () const inline final
New() [2/2]
GPS* New (::google::protobuf::Arena * arena) const inline final
operator=()
GPS& operator= (const GPS & from) inline
release_header()
gz::msgs::Header * release_header () inline
release_link_name()
std::string * release_link_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::gz::msgs::Header * header) inline
References GPS::header().
set_allocated_link_name()
void set_allocated_link_name (::std::string * link_name) inline
References GPS::link_name().
set_altitude()
void set_altitude (double value) inline
set_latitude_deg()
void set_latitude_deg (double value) inline
set_link_name() [1/3]
void set_link_name (const ::std::string & value) inline
set_link_name() [2/3]
void set_link_name (const char * value) inline
set_link_name() [3/3]
void set_link_name (const char * value, size_t size) inline
set_longitude_deg()
void set_longitude_deg (double value) inline
set_velocity_east()
void set_velocity_east (double value) inline
set_velocity_north()
void set_velocity_north (double value) inline
set_velocity_up()
void set_velocity_up (double value) inline
Swap()
void Swap (GPS * other)
velocity_east()
double velocity_east () const inline
velocity_north()
double velocity_north () const inline
velocity_up()
double velocity_up () const inline
Member Data Documentation
kAltitudeFieldNumber
const int kAltitudeFieldNumber = 5 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLatitudeDegFieldNumber
const int kLatitudeDegFieldNumber = 3 static
kLinkNameFieldNumber
const int kLinkNameFieldNumber = 2 static
kLongitudeDegFieldNumber
const int kLongitudeDegFieldNumber = 4 static
kVelocityEastFieldNumber
const int kVelocityEastFieldNumber = 6 static
kVelocityNorthFieldNumber
const int kVelocityNorthFieldNumber = 7 static
kVelocityUpFieldNumber
const int kVelocityUpFieldNumber = 8 static
The documentation for this class was generated from the following file:
gps.pb.h