Gazebo Math: Quaternion Class Reference
Gazebo Math
API Reference
6.15.1
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Quaternion Class Reference
A quaternion class.
#include <ignition/math/Quaternion.hh>
Public Member Functions
Quaternion ()
Default Constructor.
Quaternion (const Matrix3< T > &_mat)
Construct from rotation matrix.
Quaternion (const Quaternion< T > &_qt)
Copy constructor.
Quaternion (const T &_roll, const T &_pitch, const T &_yaw)
Constructor from Euler angles in radians.
Quaternion (const T &_w, const T &_x, const T &_y, const T &_z)
Constructor.
Quaternion (const Vector3< T > &_axis, const T &_angle)
Constructor from axis angle.
Quaternion (const Vector3< T > &_rpy)
Constructor.
~Quaternion ()
Destructor.
void Axis (const Vector3< T > &_axis, T _a)
Set the quaternion from an axis and angle.
void Axis (T _ax, T _ay, T _az, T _aa)
Set the quaternion from an axis and angle.
void Correct ()
Correct any nan values in this quaternion.
T Dot (const Quaternion< T > &_q) const
Dot product.
bool Equal (const Quaternion< T > &_qt, const T &_tol) const
Equality test with tolerance.
Vector3< T > Euler () const
Return the rotation in Euler angles.
void Euler (const Vector3< T > &_vec)
Set the quaternion from Euler angles. The order of operations is roll, pitch, yaw around a fixed body frame axis (the original frame of the object before rotation is applied). Roll is a rotation about x, pitch is about y, yaw is about z.
void Euler (T _roll, T _pitch, T _yaw)
Set the quaternion from Euler angles.
Quaternion< T > Exp () const
Return the exponent.
void From2Axes (const Vector3< T > &_v1, const Vector3< T > &_v2)
Set this quaternion to represent rotation from vector _v1 to vector _v2, so that _v2.Normalize() == this * _v1.Normalize() holds.
Quaternion< T > Integrate (const Vector3< T > &_angularVelocity, const T _deltaT) const
Integrate quaternion for constant angular velocity vector along specified interval _deltaT. Implementation based on: http://physicsforgames.blogspot.com/2010/02/quaternions.html.
Quaternion< T > Inverse () const
Get the inverse of this quaternion.
void Invert ()
Invert the quaternion.
bool IsFinite () const
See if a quaternion is finite (e.g., not nan)
Quaternion< T > Log () const
Return the logarithm.
void Matrix (const Matrix3< T > &_mat)
Set from a rotation matrix.
void Normalize ()
Normalize the quaternion.
Quaternion< T > Normalized () const
Gets a normalized version of this quaternion.
bool operator!= (const Quaternion< T > &_qt) const
Not equal to operator.
Quaternion< T > operator* (const Quaternion< T > &_q) const
Multiplication operator.
Quaternion< T > operator* (const T &_f) const
Multiplication operator by a scalar.
Vector3< T > operator* (const Vector3< T > &_v) const
Vector3 multiplication operator.
Quaternion< T > operator*= (const Quaternion< T > &_qt)
Multiplication operator.
Quaternion< T > operator+ (const Quaternion< T > &_qt) const
Addition operator.
Quaternion< T > operator+= (const Quaternion< T > &_qt)
Addition operator.
Quaternion< T > operator- () const
Unary minus operator.
Quaternion< T > operator- (const Quaternion< T > &_qt) const
Subtraction operator.
Quaternion< T > operator-= (const Quaternion< T > &_qt)
Subtraction operator.
Quaternion< T > & operator= (const Quaternion< T > &_qt)
Assignment operator.
bool operator== (const Quaternion< T > &_qt) const
Equal to operator.
T Pitch () const
Get the Euler pitch angle in radians.
T Roll () const
Get the Euler roll angle in radians.
Vector3< T > RotateVector (const Vector3< T > &_vec) const
Rotate a vector using the quaternion.
Vector3< T > RotateVectorReverse (const Vector3< T > &_vec) const
Do the reverse rotation of a vector by this quaternion.
void Round (int _precision)
Round all values to _precision decimal places.
void Scale (T _scale)
Scale a Quaternion<T>
void Set (T _w, T _x, T _y, T _z)
Set this quaternion from 4 floating numbers.
void ToAxis (Vector3< T > &_axis, T &_angle) const
Return rotation as axis and angle.
T & W ()
Get a mutable w component.
const T & W () const
Get the w component.
void W (T _v)
Set the w component.
T & X ()
Get a mutable x component.
const T & X () const
Get the x component.
void X (T _v)
Set the x component.
Vector3< T > XAxis () const
Return the X axis.
T & Y ()
Get a mutable y component.
const T & Y () const
Get the y component.
void Y (T _v)
Set the y component.
T Yaw () const
Get the Euler yaw angle in radians.
Vector3< T > YAxis () const
Return the Y axis.
T & Z ()
Get a mutable z component.
const T & Z () const
Get the z component.
void Z (T _v)
Set the z component.
Vector3< T > ZAxis () const
Return the Z axis.
Static Public Member Functions
static Quaternion< T > EulerToQuaternion (const Vector3< T > &_vec)
Convert euler angles to quatern.
static Quaternion< T > EulerToQuaternion (T _x, T _y, T _z)
Convert euler angles to quatern.
static Quaternion< T > Slerp (T _fT, const Quaternion< T > &_rkP, const Quaternion< T > &_rkQ, bool _shortestPath=false)
Spherical linear interpolation between 2 quaternions, given the ends and an interpolation parameter between 0 and 1.
static Quaternion< T > Squad (T _fT, const Quaternion< T > &_rkP, const Quaternion< T > &_rkA, const Quaternion< T > &_rkB, const Quaternion< T > &_rkQ, bool _shortestPath=false)
Spherical quadratic interpolation given the ends and an interpolation parameter between 0 and 1.
Static Public Attributes
static const Quaternion Identity
math::Quaternion(1, 0, 0, 0)
static const Quaternion Zero
math::Quaternion(0, 0, 0, 0)
Detailed Description
A quaternion class.
Constructor & Destructor Documentation
Quaternion() [1/7]
Quaternion () inline
Default Constructor.
Quaternion() [2/7]
Quaternion (const T & _w, const T & _x, const T & _y, const T & _z) inline
Constructor.
Parameters
[in] _w W param
[in] _x X param
[in] _y Y param
[in] _z Z param
Quaternion() [3/7]
Quaternion (const T & _roll, const T & _pitch, const T & _yaw) inline
Constructor from Euler angles in radians.
Parameters
[in] _roll roll
[in] _pitch pitch
[in] _yaw yaw
Quaternion() [4/7]
Quaternion (const Vector3< T > & _axis, const T & _angle) inline
Constructor from axis angle.
Parameters
[in] _axis the rotation axis
[in] _angle the rotation angle in radians
Quaternion() [5/7]
Quaternion (const Vector3< T > & _rpy) inline explicit
Constructor.
Parameters
[in] _rpy euler angles, in radians
Quaternion() [6/7]
Quaternion (const Matrix3< T > & _mat) inline explicit
Construct from rotation matrix.
Parameters
[in] _mat rotation matrix (must be orthogonal, the function doesn't check it)
Quaternion() [7/7]
Quaternion (const Quaternion< T > & _qt) inline
Copy constructor.
Parameters
[in] _qt Quaternion<T> to copy
~Quaternion()
~Quaternion () inline
Destructor.
Member Function Documentation
Axis() [1/2]
void Axis (const Vector3< T > & _axis, T _a) inline
Set the quaternion from an axis and angle.
Parameters
[in] _axis Axis
[in] _a Angle in radians
Axis() [2/2]
void Axis (T _ax, T _ay, T _az, T _aa) inline
Set the quaternion from an axis and angle.
Parameters
[in] _ax X axis
[in] _ay Y axis
[in] _az Z axis
[in] _aa Angle in radians
Referenced by Quaternion< Precision >::Axis(), Quaternion< Precision >::Quaternion(), and Quaternion< Precision >::Scale().
Correct()
void Correct () inline
Correct any nan values in this quaternion.
Referenced by Pose3< T >::Correct().
Dot()
T Dot (const Quaternion< T > & _q) const inline
Dot product.
Parameters
[in] _q the other quaternion
Returns
the product
Referenced by Quaternion< Precision >::Slerp().
Equal()
bool Equal (const Quaternion< T > & _qt, const T & _tol) const inline
Equality test with tolerance.
Parameters
[in] _qt Quaternion<T> for comparison
[in] _tol equality tolerance
Returns
true if the elements of the quaternions are equal within the tolerance specified by _tol, false otherwise
Referenced by Quaternion< Precision >::operator==().
Euler() [1/3]
Vector3<T> Euler () const inline
Return the rotation in Euler angles.
Returns
This quaternion as an Euler vector
Referenced by Quaternion< Precision >::Euler(), Quaternion< Precision >::Pitch(), Quaternion< Precision >::Quaternion(), Quaternion< Precision >::Roll(), and Quaternion< Precision >::Yaw().
Euler() [2/3]
void Euler (const Vector3< T > & _vec) inline
Set the quaternion from Euler angles. The order of operations is roll, pitch, yaw around a fixed body frame axis (the original frame of the object before rotation is applied). Roll is a rotation about x, pitch is about y, yaw is about z.
Parameters
[in] _vec Euler angle
Referenced by Quaternion< Precision >::EulerToQuaternion(), and Pose3< T >::Set().
Euler() [3/3]
void Euler (T _roll, T _pitch, T _yaw) inline
Set the quaternion from Euler angles.
Parameters
[in] _roll Roll angle (radians).
[in] _pitch Pitch angle (radians).
[in] _yaw Yaw angle (radians).
EulerToQuaternion() [1/2]
static Quaternion<T> EulerToQuaternion (const Vector3< T > & _vec) inline static
Convert euler angles to quatern.
Parameters
[in] _vec The vector of angles to convert.
Returns
The converted quaternion.
Referenced by Quaternion< Precision >::EulerToQuaternion().
EulerToQuaternion() [2/2]
static Quaternion<T> EulerToQuaternion (T _x, T _y, T _z) inline static
Convert euler angles to quatern.
Parameters
[in] _x rotation along x
[in] _y rotation along y
[in] _z rotation along z
Returns
The converted quaternion.
Exp()
Quaternion<T> Exp () const inline
Return the exponent.
Returns
the exp
From2Axes()
void From2Axes (const Vector3< T > & _v1, const Vector3< T > & _v2) inline
Set this quaternion to represent rotation from vector _v1 to vector _v2, so that _v2.Normalize() == this * _v1.Normalize() holds.
Parameters
[in] _v1 The first vector
[in] _v2 The second vector
Implementation inspired by http://stackoverflow.com/a/11741520/1076564
Integrate()
Quaternion<T> Integrate (const Vector3< T > & _angularVelocity, const T _deltaT) const inline
Integrate quaternion for constant angular velocity vector along specified interval _deltaT. Implementation based on: http://physicsforgames.blogspot.com/2010/02/quaternions.html.
Parameters
[in] _angularVelocity Angular velocity vector, specified in same reference frame as base of this quaternion.
[in] _deltaT Time interval in seconds to integrate over.
Returns
Quaternion at integrated configuration.
Inverse()
Quaternion<T> Inverse () const inline
Get the inverse of this quaternion.
Returns
Inverse quaternion
Referenced by Pose3< T >::CoordPoseSolve(), Pose3< T >::CoordPositionAdd(), Pose3< T >::CoordPositionSub(), Pose3< T >::CoordRotationSub(), Pose3< T >::Inverse(), MassMatrix3< T >::PrincipalAxesOffset(), Quaternion< Precision >::RotateVector(), Quaternion< Precision >::RotateVectorReverse(), and Inertial< T >::SetMassMatrixRotation().
Invert()
void Invert () inline
Invert the quaternion.
IsFinite()
bool IsFinite () const inline
See if a quaternion is finite (e.g., not nan)
Returns
True if quaternion is finite
Referenced by Pose3< T >::IsFinite().
Log()
Quaternion<T> Log () const inline
Return the logarithm.
Returns
the log
Matrix()
void Matrix (const Matrix3< T > & _mat) inline
Set from a rotation matrix.
Parameters
[in] _mat rotation matrix (must be orthogonal, the function doesn't check it)
Implementation inspired by http://www.euclideanspace.com/maths/geometry/rotations/ conversions/matrixToQuaternion/
Referenced by Quaternion< Precision >::Quaternion().
Normalize()
void Normalize () inline
Normalize the quaternion.
Referenced by Quaternion< Precision >::Axis(), Pose3< T >::CoordRotationSub(), Quaternion< Precision >::Euler(), Quaternion< Precision >::From2Axes(), Quaternion< Precision >::Invert(), Matrix3< T >::Matrix3(), Matrix4< T >::Matrix4(), Quaternion< Precision >::Normalized(), and Quaternion< Precision >::Slerp().
Normalized()
Quaternion<T> Normalized () const inline
Gets a normalized version of this quaternion.
Returns
a normalized quaternion
operator!=()
bool operator!= (const Quaternion< T > & _qt) const inline
Not equal to operator.
Parameters
[in] _qt Quaternion<T> for comparison
Returns
True if not equal
operator*() [1/3]
Quaternion<T> operator* (const Quaternion< T > & _q) const inline
Multiplication operator.
Parameters
[in] _q Quaternion<T> for multiplication
Returns
This quaternion multiplied by the parameter
operator*() [2/3]
Quaternion<T> operator* (const T & _f) const inline
Multiplication operator by a scalar.
Parameters
[in] _f factor
Returns
quaternion multiplied by the scalar
operator*() [3/3]
Vector3<T> operator* (const Vector3< T > & _v) const inline
Vector3 multiplication operator.
Parameters
[in] _v vector to multiply
Returns
The result of the vector multiplication
operator*=()
Quaternion<T> operator*= (const Quaternion< T > & _qt) inline
Multiplication operator.
Parameters
[in] _qt Quaternion<T> for multiplication
Returns
This quaternion multiplied by the parameter
operator+()
Quaternion<T> operator+ (const Quaternion< T > & _qt) const inline
Addition operator.
Parameters
[in] _qt quaternion for addition
Returns
this quaternion + _qt
operator+=()
Quaternion<T> operator+= (const Quaternion< T > & _qt) inline
Addition operator.
Parameters
[in] _qt quaternion for addition
Returns
this quaternion + qt
operator-() [1/2]
Quaternion<T> operator- () const inline
Unary minus operator.
Returns
negates each component of the quaternion
operator-() [2/2]
Quaternion<T> operator- (const Quaternion< T > & _qt) const inline
Subtraction operator.
Parameters
[in] _qt quaternion to subtract
Returns
this quaternion - _qt
operator-=()
Quaternion<T> operator-= (const Quaternion< T > & _qt) inline
Subtraction operator.
Parameters
[in] _qt Quaternion<T> for subtraction
Returns
This quaternion - qt
operator=()
Quaternion<T>& operator= (const Quaternion< T > & _qt) inline
Assignment operator.
Parameters
[in] _qt Quaternion<T> to copy
operator==()
bool operator== (const Quaternion< T > & _qt) const inline
Equal to operator.
Parameters
[in] _qt Quaternion<T> for comparison
Returns
True if equal
Pitch()
T Pitch () const inline
Get the Euler pitch angle in radians.
Returns
the pitch component
Referenced by Pose3< T >::Pitch().
Roll()
T Roll () const inline
Get the Euler roll angle in radians.
Returns
the roll component
Referenced by Pose3< T >::Roll().
RotateVector()
Vector3<T> RotateVector (const Vector3< T > & _vec) const inline
Rotate a vector using the quaternion.
Parameters
[in] _vec vector to rotate
Returns
the rotated vector
RotateVectorReverse()
Vector3<T> RotateVectorReverse (const Vector3< T > & _vec) const inline
Do the reverse rotation of a vector by this quaternion.
Parameters
[in] _vec the vector
Returns
the reversed vector
Round()
void Round (int _precision) inline
Round all values to _precision decimal places.
Parameters
[in] _precision the precision
Referenced by Pose3< T >::Round().
Scale()
void Scale (T _scale) inline
Scale a Quaternion<T>
Parameters
[in] _scale Amount to scale this rotation
Set()
void Set (T _w, T _x, T _y, T _z) inline
Set this quaternion from 4 floating numbers.
Parameters
[in] _w w
[in] _x x
[in] _y y
[in] _z z
Slerp()
static Quaternion<T> Slerp (T _fT, const Quaternion< T > & _rkP, const Quaternion< T > & _rkQ, bool _shortestPath = false) inline static
Spherical linear interpolation between 2 quaternions, given the ends and an interpolation parameter between 0 and 1.
Parameters
[in] _fT the interpolation parameter
[in] _rkP the beginning quaternion
[in] _rkQ the end quaternion
[in] _shortestPath when true, the rotation may be inverted to get to minimize rotation
Returns
The result of the linear interpolation
Referenced by OnePoleQuaternion::Process(), and Quaternion< Precision >::Squad().
Squad()
static Quaternion<T> Squad (T _fT, const Quaternion< T > & _rkP, const Quaternion< T > & _rkA, const Quaternion< T > & _rkB, const Quaternion< T > & _rkQ, bool _shortestPath = false) inline static
Spherical quadratic interpolation given the ends and an interpolation parameter between 0 and 1.
Parameters
[in] _fT the interpolation parameter
[in] _rkP the beginning quaternion
[in] _rkA first intermediate quaternion
[in] _rkB second intermediate quaternion
[in] _rkQ the end quaternion
[in] _shortestPath when true, the rotation may be inverted to get to minimize rotation
Returns
The result of the quadratic interpolation
ToAxis()
void ToAxis (Vector3< T > & _axis, T & _angle) const inline
Return rotation as axis and angle.
Parameters
[out] _axis rotation axis
[out] _angle ccw angle in radians
Referenced by Quaternion< Precision >::Scale().
W() [1/3]
T& W () inline
Get a mutable w component.
Returns
The w quaternion component.
W() [2/3]
const T& W () const inline
Get the w component.
Returns
The w quaternion component.
Referenced by ignition::math::eigen3::convert(), Quaternion< Precision >::Integrate(), Matrix3< T >::Matrix3(), Matrix4< T >::Matrix4(), Pose3< T >::RotatePositionAboutOrigin(), and Matrix4< T >::Rotation().
W() [3/3]
void W (T _v) inline
Set the w component.
Parameters
[in] _v The new value for the w quaternion component.
X() [1/3]
T& X () inline
Get a mutable x component.
Returns
The x quaternion component.
X() [2/3]
const T& X () const inline
Get the x component.
Returns
The x quaternion component.
Referenced by ignition::math::eigen3::convert(), Pose3< T >::CoordPoseSolve(), Pose3< T >::CoordPositionAdd(), Pose3< T >::CoordPositionSub(), Quaternion< Precision >::Integrate(), Matrix3< T >::Matrix3(), Matrix4< T >::Matrix4(), Pose3< T >::RotatePositionAboutOrigin(), and Matrix4< T >::Rotation().
X() [3/3]
void X (T _v) inline
Set the x component.
Parameters
[in] _v The new value for the x quaternion component.
XAxis()
Vector3<T> XAxis () const inline
Return the X axis.
Returns
the X axis of the vector
Y() [1/3]
T& Y () inline
Get a mutable y component.
Returns
The y quaternion component.
Y() [2/3]
const T& Y () const inline
Get the y component.
Returns
The y quaternion component.
Referenced by ignition::math::eigen3::convert(), Pose3< T >::CoordPoseSolve(), Pose3< T >::CoordPositionAdd(), Pose3< T >::CoordPositionSub(), Quaternion< Precision >::Integrate(), Matrix3< T >::Matrix3(), Matrix4< T >::Matrix4(), Pose3< T >::RotatePositionAboutOrigin(), and Matrix4< T >::Rotation().
Y() [3/3]
void Y (T _v) inline
Set the y component.
Parameters
[in] _v The new value for the y quaternion component.
Yaw()
T Yaw () const inline
Get the Euler yaw angle in radians.
Returns
the yaw component
Referenced by Pose3< T >::Yaw().
YAxis()
Vector3<T> YAxis () const inline
Return the Y axis.
Returns
the Y axis of the vector
Z() [1/3]
T& Z () inline
Get a mutable z component.
Returns
The z quaternion component.
Z() [2/3]
const T& Z () const inline
Get the z component.
Returns
The z quaternion component.
Referenced by ignition::math::eigen3::convert(), Pose3< T >::CoordPoseSolve(), Pose3< T >::CoordPositionAdd(), Pose3< T >::CoordPositionSub(), Quaternion< Precision >::Integrate(), Matrix3< T >::Matrix3(), Matrix4< T >::Matrix4(), Pose3< T >::RotatePositionAboutOrigin(), and Matrix4< T >::Rotation().
Z() [3/3]
void Z (T _v) inline
Set the z component.
Parameters
[in] _v The new value for the z quaternion component.
ZAxis()
Vector3<T> ZAxis () const inline
Return the Z axis.
Returns
the Z axis of the vector
Member Data Documentation
Identity
const Quaternion< T > Identity static
math::Quaternion(1, 0, 0, 0)
Zero
const Quaternion< T > Zero static
math::Quaternion(0, 0, 0, 0)
The documentation for this class was generated from the following files:
gz/math/Matrix3.hh
gz/math/Quaternion.hh