Gazebo Math: Material Class Reference
Gazebo Math
API Reference
6.15.1
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Material Class Reference
Contains information about a single material.
#include <Material.hh>
Public Member Functions
Material ()
Constructor.
Material (const double _density)
Construct a material based on a density value.
Material (const Material &_material)
Copy constructor.
Material (const MaterialType _type)
Construct a material based on a type.
Material (const std::string &_typename)
Construct a material based on a type name.
Material (Material &&_material)
Move constructor.
~Material ()
Destructor.
double Density () const
Get the density value of the material in kg/m^3.
std::string Name () const
Get the name of the material. This will match the enum type names used in MaterialType, but in lowercase, if a built-in material is used.
bool operator!= (const Material &_material) const
Inequality operator. This compares type and density values.
Material & operator= (const Material &_material)
Copy operator.
Material & operator= (Material &&_material)
Move operator.
bool operator== (const Material &_material) const
Equality operator. This compares type and density values.
void SetDensity (const double _density)
Set the density value of the material in kg/m^3.
void SetName (const std::string &_name)
Set the name of the material.
void SetToNearestDensity (const double _value, const double _epsilon=std::numeric_limits< double >::max())
Set this Material to the built-in Material with the nearest density value within _epsilon. If a built-in material could not be found, then this Material is not changed.
void SetType (const MaterialType _type)
Set the material's type. This will only set the type value. Other properties, such as density, will not be changed.
MaterialType Type () const
Get the material's type.
Static Public Member Functions
static const std::map< MaterialType, Material > & Predefined ()
Get all the built-in materials.
Detailed Description
Contains information about a single material.
Steel, wood, and iron are examples of materials. This class allows you to create custom materials, or use built-in materials. The list of built-in materials can be found in the MaterialType enum.
This class will replace the MaterialDensity class found in the Ignition Common library, which was at version 1 at the time of this writing.
How to create a wood material:
Material mat(MaterialType::WOOD);
std::cout << "The density of " << mat.Name() << " is "
  << mat.Density() << std::endl;
How to create a custom material:
Material mat;
mat.SetDensity(12.23);
mat.SetName("my_material");
std::cout << "The density of " << mat.Name() is "
  << mat.Density() << std::endl;
Constructor & Destructor Documentation
Material() [1/6]
Material ()
Constructor.
Material() [2/6]
Material (const MaterialType _type) explicit
Construct a material based on a type.
Parameters
[in] _type Built-in type to create.
Material() [3/6]
Material (const std::string & _typename) explicit
Construct a material based on a type name.
Parameters
[in] _typename Name of the built-in type to create. String names are listed in the MaterialType documentation.
Material() [4/6]
Material (const double _density) explicit
Construct a material based on a density value.
Parameters
[in] _density Material density.
Material() [5/6]
Material (const Material & _material)
Copy constructor.
Parameters
[in] _material Material to copy.
Material() [6/6]
Material (Material && _material)
Move constructor.
Parameters
[in] _material Material to move. The _material object will have default values after the move.
~Material()
~Material ()
Destructor.
Member Function Documentation
Density()
double Density () const
Get the density value of the material in kg/m^3.
Returns
The density of this material in kg/m^3.
Referenced by MassMatrix3< T >::SetFromBox(), MassMatrix3< T >::SetFromCylinderZ(), and MassMatrix3< T >::SetFromSphere().
Name()
std::string Name () const
Get the name of the material. This will match the enum type names used in MaterialType, but in lowercase, if a built-in material is used.
Returns
The material's name.
See also
void SetName(const std::string &_name)
operator!=()
bool operator!= (const Material & _material) const
Inequality operator. This compares type and density values.
Parameters
[in] _material Material to evaluate this object against.
Returns
True if this material is not equal to the given _material.
operator=() [1/2]
Material& operator= (const Material & _material)
Copy operator.
Parameters
[in] _material Material to copy.
Returns
Reference to this material.
operator=() [2/2]
Material& operator= (Material && _material)
Move operator.
Parameters
[in] _material Material to move. The _material object will contain default values after this move.
Returns
Reference to this Material.
operator==()
bool operator== (const Material & _material) const
Equality operator. This compares type and density values.
Parameters
[in] _material Material to evaluate this object against.
Returns
True if this material is equal to the given _material.
Predefined()
static const std::map<MaterialType, Material>& Predefined () static
Get all the built-in materials.
Returns
A map of all the materials. The map's key is material type and the map's value is the material object.
SetDensity()
void SetDensity (const double _density)
Set the density value of the material in kg/m^3.
Parameters
[in] _density The density of this material in kg/m^3.
Referenced by OrientedBox< T >::SetDensityFromMass().
SetName()
void SetName (const std::string & _name)
Set the name of the material.
Parameters
[in] _name The material's name.
See also
std::string Name() const
SetToNearestDensity()
void SetToNearestDensity (const double _value, const double _epsilon = std::numeric_limits< double >::max())
Set this Material to the built-in Material with the nearest density value within _epsilon. If a built-in material could not be found, then this Material is not changed.
Parameters
[in] _value Density value of entry to match.
[in] _epsilon Allowable range of difference between _value, and a material's density.
SetType()
void SetType (const MaterialType _type)
Set the material's type. This will only set the type value. Other properties, such as density, will not be changed.
Parameters
[in] _type The material's type.
Type()
MaterialType Type () const
Get the material's type.
Returns
The material's type.
The documentation for this class was generated from the following file:
gz/math/Material.hh