Gazebo Msgs: Fog Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Fog Class Reference
#include <fog.pb.h>
Public Types
typedef Fog_FogType FogType
Public Member Functions
Fog ()
Fog (const Fog &from)
virtual ~Fog ()
size_t ByteSizeLong () const final
void Clear () final
void clear_color ()
void clear_density ()
void clear_end ()
void clear_header ()
void clear_start ()
void clear_type ()
const ::ignition::msgs::Color & color () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Fog &from)
float density () const
float end () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_color () const
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Fog &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Color * mutable_color ()
::ignition::msgs::Header * mutable_header ()
Fog * New () const final
Fog * New (::google::protobuf::Arena *arena) const final
Fog & operator= (const Fog &from)
::ignition::msgs::Color * release_color ()
::ignition::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_color (::ignition::msgs::Color *color)
void set_allocated_header (::ignition::msgs::Header *header)
void set_density (float value)
void set_end (float value)
void set_start (float value)
void set_type (::ignition::msgs::Fog_FogType value)
float start () const
void Swap (Fog *other)
::ignition::msgs::Fog_FogType type () const
Static Public Member Functions
static const Fog & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const ::google::protobuf::EnumDescriptor * FogType_descriptor ()
static bool FogType_IsValid (int value)
static const ::std::string & FogType_Name (FogType value)
static bool FogType_Parse (const ::std::string &name, FogType *value)
static void InitAsDefaultInstance ()
static const Fog * internal_default_instance ()
Static Public Attributes
static const FogType EXPONENTIAL
static const FogType EXPONENTIAL2
static const int FogType_ARRAYSIZE
static const FogType FogType_MAX
static const FogType FogType_MIN
static const int kColorFieldNumber = 3
static const int kDensityFieldNumber = 4
static const int kEndFieldNumber = 6
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kStartFieldNumber = 5
static const int kTypeFieldNumber = 2
static const FogType LINEAR
static const FogType NONE
Member Typedef Documentation
FogType
typedef Fog_FogType FogType
Constructor & Destructor Documentation
Fog() [1/2]
Fog ()
~Fog()
virtual ~Fog () virtual
Fog() [2/2]
Fog (const Fog & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_color()
void clear_color ()
clear_density()
void clear_density () inline
clear_end()
void clear_end () inline
clear_header()
void clear_header ()
clear_start()
void clear_start () inline
clear_type()
void clear_type () inline
color()
const ::ignition::msgs::Color & color () const inline
References ignition::msgs::_Color_default_instance_.
Referenced by Fog::set_allocated_color().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Fog & from)
default_instance()
static const Fog& default_instance () static
density()
float density () const inline
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
end()
float end () const inline
FogType_descriptor()
static const ::google::protobuf::EnumDescriptor* FogType_descriptor () inline static
References ignition::msgs::Fog_FogType_descriptor().
FogType_IsValid()
static bool FogType_IsValid (int value) inline static
References ignition::msgs::Fog_FogType_IsValid().
FogType_Name()
static const ::std::string& FogType_Name (FogType value) inline static
References ignition::msgs::Fog_FogType_Name().
FogType_Parse()
static bool FogType_Parse (const ::std::string & name, FogType * value) inline static
References ignition::msgs::Fog_FogType_Parse().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_color()
bool has_color () const inline
References Fog::internal_default_instance().
has_header()
bool has_header () const inline
References Fog::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Fog::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Fog* internal_default_instance () inline static
References ignition::msgs::_Fog_default_instance_.
Referenced by Fog::has_color(), and Fog::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Fog & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_color()
ignition::msgs::Color * mutable_color () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
New() [1/2]
Fog* New () const inline final
New() [2/2]
Fog* New (::google::protobuf::Arena * arena) const inline final
operator=()
Fog& operator= (const Fog & from) inline
release_color()
ignition::msgs::Color * release_color () inline
release_header()
ignition::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_color()
void set_allocated_color (::ignition::msgs::Color * color) inline
References Fog::color().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Fog::header().
set_density()
void set_density (float value) inline
set_end()
void set_end (float value) inline
set_start()
void set_start (float value) inline
set_type()
void set_type (::ignition::msgs::Fog_FogType value) inline
start()
float start () const inline
Swap()
void Swap (Fog * other)
type()
ignition::msgs::Fog_FogType type () const inline
Member Data Documentation
EXPONENTIAL
const FogType EXPONENTIAL static
Initial value:
=
    Fog_FogType_EXPONENTIAL
EXPONENTIAL2
const FogType EXPONENTIAL2 static
Initial value:
=
    Fog_FogType_EXPONENTIAL2
FogType_ARRAYSIZE
const int FogType_ARRAYSIZE static
Initial value:
=
    Fog_FogType_FogType_ARRAYSIZE
FogType_MAX
const FogType FogType_MAX static
Initial value:
=
    Fog_FogType_FogType_MAX
FogType_MIN
const FogType FogType_MIN static
Initial value:
=
    Fog_FogType_FogType_MIN
kColorFieldNumber
const int kColorFieldNumber = 3 static
kDensityFieldNumber
const int kDensityFieldNumber = 4 static
kEndFieldNumber
const int kEndFieldNumber = 6 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kStartFieldNumber
const int kStartFieldNumber = 5 static
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
LINEAR
const FogType LINEAR static
Initial value:
=
    Fog_FogType_LINEAR
NONE
const FogType NONE static
Initial value:
=
    Fog_FogType_NONE
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/fog.pb.h