Gazebo Msgs: LinkData Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
LinkData Class Reference
#include <link_data.pb.h>
Public Member Functions
LinkData ()
LinkData (const LinkData &from)
virtual ~LinkData ()
const ::ignition::msgs::Vector3d & angular_velocity () const
size_t ByteSizeLong () const final
void Clear () final
void clear_angular_velocity ()
void clear_header ()
void clear_linear_velocity ()
void clear_name ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const LinkData &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_angular_velocity () const
bool has_header () const
bool has_linear_velocity () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::ignition::msgs::Vector3d & linear_velocity () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const LinkData &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Vector3d * mutable_angular_velocity ()
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::Vector3d * mutable_linear_velocity ()
::std::string * mutable_name ()
const ::std::string & name () const
LinkData * New () const final
LinkData * New (::google::protobuf::Arena *arena) const final
LinkData & operator= (const LinkData &from)
::ignition::msgs::Vector3d * release_angular_velocity ()
::ignition::msgs::Header * release_header ()
::ignition::msgs::Vector3d * release_linear_velocity ()
::std::string * release_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_angular_velocity (::ignition::msgs::Vector3d *angular_velocity)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_linear_velocity (::ignition::msgs::Vector3d *linear_velocity)
void set_allocated_name (::std::string *name)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void Swap (LinkData *other)
Static Public Member Functions
static const LinkData & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const LinkData * internal_default_instance ()
Static Public Attributes
static const int kAngularVelocityFieldNumber = 4
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kLinearVelocityFieldNumber = 3
static const int kNameFieldNumber = 2
Constructor & Destructor Documentation
LinkData() [1/2]
LinkData ()
~LinkData()
virtual ~LinkData () virtual
LinkData() [2/2]
LinkData (const LinkData & from)
Member Function Documentation
angular_velocity()
const ::ignition::msgs::Vector3d & angular_velocity () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by LinkData::set_allocated_angular_velocity().
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_angular_velocity()
void clear_angular_velocity ()
clear_header()
void clear_header ()
clear_linear_velocity()
void clear_linear_velocity ()
clear_name()
void clear_name () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const LinkData & from)
default_instance()
static const LinkData& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_angular_velocity()
bool has_angular_velocity () const inline
References LinkData::internal_default_instance().
has_header()
bool has_header () const inline
References LinkData::internal_default_instance().
has_linear_velocity()
bool has_linear_velocity () const inline
References LinkData::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by LinkData::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const LinkData* internal_default_instance () inline static
References ignition::msgs::_LinkData_default_instance_.
Referenced by LinkData::has_angular_velocity(), LinkData::has_header(), and LinkData::has_linear_velocity().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
linear_velocity()
const ::ignition::msgs::Vector3d & linear_velocity () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by LinkData::set_allocated_linear_velocity().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const LinkData & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_angular_velocity()
ignition::msgs::Vector3d * mutable_angular_velocity () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_linear_velocity()
ignition::msgs::Vector3d * mutable_linear_velocity () inline
mutable_name()
std::string * mutable_name () inline
name()
const ::std::string & name () const inline
Referenced by LinkData::set_allocated_name().
New() [1/2]
LinkData* New () const inline final
New() [2/2]
LinkData* New (::google::protobuf::Arena * arena) const inline final
operator=()
LinkData& operator= (const LinkData & from) inline
release_angular_velocity()
ignition::msgs::Vector3d * release_angular_velocity () inline
release_header()
ignition::msgs::Header * release_header () inline
release_linear_velocity()
ignition::msgs::Vector3d * release_linear_velocity () inline
release_name()
std::string * release_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_angular_velocity()
void set_allocated_angular_velocity (::ignition::msgs::Vector3d * angular_velocity) inline
References LinkData::angular_velocity().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References LinkData::header().
set_allocated_linear_velocity()
void set_allocated_linear_velocity (::ignition::msgs::Vector3d * linear_velocity) inline
References LinkData::linear_velocity().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References LinkData::name().
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
Swap()
void Swap (LinkData * other)
Member Data Documentation
kAngularVelocityFieldNumber
const int kAngularVelocityFieldNumber = 4 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLinearVelocityFieldNumber
const int kLinearVelocityFieldNumber = 3 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/link_data.pb.h