Gazebo Msgs: VersionedName Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
VersionedName Class Reference
#include <versioned_name.pb.h>
Public Member Functions
VersionedName ()
VersionedName (const VersionedName &from)
virtual ~VersionedName ()
size_t ByteSizeLong () const final
void Clear () final
void clear_name ()
void clear_version ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const VersionedName &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_version () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const VersionedName &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_name ()
::ignition::msgs::Version * mutable_version ()
const ::std::string & name () const
VersionedName * New () const final
VersionedName * New (::google::protobuf::Arena *arena) const final
VersionedName & operator= (const VersionedName &from)
::std::string * release_name ()
::ignition::msgs::Version * release_version ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_name (::std::string *name)
void set_allocated_version (::ignition::msgs::Version *version)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void Swap (VersionedName *other)
const ::ignition::msgs::Version & version () const
Static Public Member Functions
static const VersionedName & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const VersionedName * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 2
static const int kVersionFieldNumber = 1
Constructor & Destructor Documentation
VersionedName() [1/2]
VersionedName ()
~VersionedName()
virtual ~VersionedName () virtual
VersionedName() [2/2]
VersionedName (const VersionedName & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_name()
void clear_name () inline
clear_version()
void clear_version ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const VersionedName & from)
default_instance()
static const VersionedName& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_version()
bool has_version () const inline
References VersionedName::internal_default_instance().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const VersionedName* internal_default_instance () inline static
References ignition::msgs::_VersionedName_default_instance_.
Referenced by VersionedName::has_version().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const VersionedName & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_name()
std::string * mutable_name () inline
mutable_version()
ignition::msgs::Version * mutable_version () inline
name()
const ::std::string & name () const inline
Referenced by VersionedName::set_allocated_name().
New() [1/2]
VersionedName* New () const inline final
New() [2/2]
VersionedName* New (::google::protobuf::Arena * arena) const inline final
operator=()
VersionedName& operator= (const VersionedName & from) inline
release_name()
std::string * release_name () inline
release_version()
ignition::msgs::Version * release_version () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References VersionedName::name().
set_allocated_version()
void set_allocated_version (::ignition::msgs::Version * version) inline
References VersionedName::version().
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
Swap()
void Swap (VersionedName * other)
version()
const ::ignition::msgs::Version & version () const inline
References ignition::msgs::_Version_default_instance_.
Referenced by VersionedName::set_allocated_version().
Member Data Documentation
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 2 static
kVersionFieldNumber
const int kVersionFieldNumber = 1 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/versioned_name.pb.h