Gazebo Msgs: Metric Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Metric Class Reference
#include <statistic.pb.h>
Public Member Functions
Metric ()
Metric (const Metric &from)
virtual ~Metric ()
::ignition::msgs::Statistic * add_statistics ()
::ignition::msgs::StatisticsGroup * add_statistics_groups ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_statistics ()
void clear_statistics_groups ()
void clear_unit ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Metric &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Metric &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Statistic > * mutable_statistics ()
::ignition::msgs::Statistic * mutable_statistics (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::StatisticsGroup > * mutable_statistics_groups ()
::ignition::msgs::StatisticsGroup * mutable_statistics_groups (int index)
::std::string * mutable_unit ()
Metric * New () const final
Metric * New (::google::protobuf::Arena *arena) const final
Metric & operator= (const Metric &from)
::ignition::msgs::Header * release_header ()
::std::string * release_unit ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_unit (::std::string *unit)
void set_unit (const ::std::string &value)
void set_unit (const char *value)
void set_unit (const char *value, size_t size)
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Statistic > & statistics () const
const ::ignition::msgs::Statistic & statistics (int index) const
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::StatisticsGroup > & statistics_groups () const
const ::ignition::msgs::StatisticsGroup & statistics_groups (int index) const
int statistics_groups_size () const
int statistics_size () const
void Swap (Metric *other)
const ::std::string & unit () const
Static Public Member Functions
static const Metric & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Metric * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kStatisticsFieldNumber = 4
static const int kStatisticsGroupsFieldNumber = 3
static const int kUnitFieldNumber = 2
Constructor & Destructor Documentation
Metric() [1/2]
Metric ()
~Metric()
virtual ~Metric () virtual
Metric() [2/2]
Metric (const Metric & from)
Member Function Documentation
add_statistics()
ignition::msgs::Statistic * add_statistics () inline
add_statistics_groups()
ignition::msgs::StatisticsGroup * add_statistics_groups () inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_statistics()
void clear_statistics () inline
clear_statistics_groups()
void clear_statistics_groups () inline
clear_unit()
void clear_unit () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Metric & from)
default_instance()
static const Metric& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Metric::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Metric::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Metric* internal_default_instance () inline static
References ignition::msgs::_Metric_default_instance_.
Referenced by Metric::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Metric & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_statistics() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Statistic > * mutable_statistics () inline
mutable_statistics() [2/2]
ignition::msgs::Statistic * mutable_statistics (int index) inline
mutable_statistics_groups() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::StatisticsGroup > * mutable_statistics_groups () inline
mutable_statistics_groups() [2/2]
ignition::msgs::StatisticsGroup * mutable_statistics_groups (int index) inline
mutable_unit()
std::string * mutable_unit () inline
New() [1/2]
Metric* New () const inline final
New() [2/2]
Metric* New (::google::protobuf::Arena * arena) const inline final
operator=()
Metric& operator= (const Metric & from) inline
release_header()
ignition::msgs::Header * release_header () inline
release_unit()
std::string * release_unit () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Metric::header().
set_allocated_unit()
void set_allocated_unit (::std::string * unit) inline
References Metric::unit().
set_unit() [1/3]
void set_unit (const ::std::string & value) inline
set_unit() [2/3]
void set_unit (const char * value) inline
set_unit() [3/3]
void set_unit (const char * value, size_t size) inline
statistics() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Statistic > & statistics () const inline
statistics() [2/2]
const ::ignition::msgs::Statistic & statistics (int index) const inline
statistics_groups() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::StatisticsGroup > & statistics_groups () const inline
statistics_groups() [2/2]
const ::ignition::msgs::StatisticsGroup & statistics_groups (int index) const inline
statistics_groups_size()
int statistics_groups_size () const inline
statistics_size()
int statistics_size () const inline
Swap()
void Swap (Metric * other)
unit()
const ::std::string & unit () const inline
Referenced by Metric::set_allocated_unit().
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    2
kStatisticsFieldNumber
const int kStatisticsFieldNumber = 4 static
kStatisticsGroupsFieldNumber
const int kStatisticsGroupsFieldNumber = 3 static
kUnitFieldNumber
const int kUnitFieldNumber = 2 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/statistic.pb.h