Gazebo Msgs: GUICamera Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
GUICamera Class Reference
#include <gui_camera.pb.h>
Public Member Functions
GUICamera ()
GUICamera (const GUICamera &from)
virtual ~GUICamera ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_name ()
void clear_pose ()
void clear_projection_type ()
void clear_track ()
void clear_view_controller ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const GUICamera &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_pose () const
bool has_track () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const GUICamera &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_name ()
::ignition::msgs::Pose * mutable_pose ()
::std::string * mutable_projection_type ()
::ignition::msgs::TrackVisual * mutable_track ()
::std::string * mutable_view_controller ()
const ::std::string & name () const
GUICamera * New () const final
GUICamera * New (::google::protobuf::Arena *arena) const final
GUICamera & operator= (const GUICamera &from)
const ::ignition::msgs::Pose & pose () const
const ::std::string & projection_type () const
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
::ignition::msgs::Pose * release_pose ()
::std::string * release_projection_type ()
::ignition::msgs::TrackVisual * release_track ()
::std::string * release_view_controller ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_pose (::ignition::msgs::Pose *pose)
void set_allocated_projection_type (::std::string *projection_type)
void set_allocated_track (::ignition::msgs::TrackVisual *track)
void set_allocated_view_controller (::std::string *view_controller)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_projection_type (const ::std::string &value)
void set_projection_type (const char *value)
void set_projection_type (const char *value, size_t size)
void set_view_controller (const ::std::string &value)
void set_view_controller (const char *value)
void set_view_controller (const char *value, size_t size)
void Swap (GUICamera *other)
const ::ignition::msgs::TrackVisual & track () const
const ::std::string & view_controller () const
Static Public Member Functions
static const GUICamera & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const GUICamera * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 2
static const int kPoseFieldNumber = 4
static const int kProjectionTypeFieldNumber = 6
static const int kTrackFieldNumber = 5
static const int kViewControllerFieldNumber = 3
Constructor & Destructor Documentation
GUICamera() [1/2]
GUICamera ()
~GUICamera()
virtual ~GUICamera () virtual
GUICamera() [2/2]
GUICamera (const GUICamera & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_name()
void clear_name () inline
clear_pose()
void clear_pose ()
clear_projection_type()
void clear_projection_type () inline
clear_track()
void clear_track ()
clear_view_controller()
void clear_view_controller () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const GUICamera & from)
default_instance()
static const GUICamera& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References GUICamera::internal_default_instance().
has_pose()
bool has_pose () const inline
References GUICamera::internal_default_instance().
has_track()
bool has_track () const inline
References GUICamera::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by GUICamera::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const GUICamera* internal_default_instance () inline static
References ignition::msgs::_GUICamera_default_instance_.
Referenced by GUICamera::has_header(), GUICamera::has_pose(), and GUICamera::has_track().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const GUICamera & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
mutable_pose()
ignition::msgs::Pose * mutable_pose () inline
mutable_projection_type()
std::string * mutable_projection_type () inline
mutable_track()
ignition::msgs::TrackVisual * mutable_track () inline
mutable_view_controller()
std::string * mutable_view_controller () inline
name()
const ::std::string & name () const inline
Referenced by GUICamera::set_allocated_name().
New() [1/2]
GUICamera* New () const inline final
New() [2/2]
GUICamera* New (::google::protobuf::Arena * arena) const inline final
operator=()
GUICamera& operator= (const GUICamera & from) inline
pose()
const ::ignition::msgs::Pose & pose () const inline
References ignition::msgs::_Pose_default_instance_.
Referenced by GUICamera::set_allocated_pose().
projection_type()
const ::std::string & projection_type () const inline
Referenced by GUICamera::set_allocated_projection_type().
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_pose()
ignition::msgs::Pose * release_pose () inline
release_projection_type()
std::string * release_projection_type () inline
release_track()
ignition::msgs::TrackVisual * release_track () inline
release_view_controller()
std::string * release_view_controller () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References GUICamera::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References GUICamera::name().
set_allocated_pose()
void set_allocated_pose (::ignition::msgs::Pose * pose) inline
References GUICamera::pose().
set_allocated_projection_type()
void set_allocated_projection_type (::std::string * projection_type) inline
References GUICamera::projection_type().
set_allocated_track()
void set_allocated_track (::ignition::msgs::TrackVisual * track) inline
References GUICamera::track().
set_allocated_view_controller()
void set_allocated_view_controller (::std::string * view_controller) inline
References GUICamera::view_controller().
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_projection_type() [1/3]
void set_projection_type (const ::std::string & value) inline
set_projection_type() [2/3]
void set_projection_type (const char * value) inline
set_projection_type() [3/3]
void set_projection_type (const char * value, size_t size) inline
set_view_controller() [1/3]
void set_view_controller (const ::std::string & value) inline
set_view_controller() [2/3]
void set_view_controller (const char * value) inline
set_view_controller() [3/3]
void set_view_controller (const char * value, size_t size) inline
Swap()
void Swap (GUICamera * other)
track()
const ::ignition::msgs::TrackVisual & track () const inline
References ignition::msgs::_TrackVisual_default_instance_.
Referenced by GUICamera::set_allocated_track().
view_controller()
const ::std::string & view_controller () const inline
Referenced by GUICamera::set_allocated_view_controller().
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 2 static
kPoseFieldNumber
const int kPoseFieldNumber = 4 static
kProjectionTypeFieldNumber
const int kProjectionTypeFieldNumber = 6 static
kTrackFieldNumber
const int kTrackFieldNumber = 5 static
kViewControllerFieldNumber
const int kViewControllerFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/gui_camera.pb.h