Gazebo Msgs: VideoRecord Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
VideoRecord Class Reference
#include <video_record.pb.h>
Public Member Functions
VideoRecord ()
VideoRecord (const VideoRecord &from)
virtual ~VideoRecord ()
size_t ByteSizeLong () const final
void Clear () final
void clear_format ()
void clear_header ()
void clear_save_filename ()
void clear_start ()
void clear_stop ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const VideoRecord &from)
const ::std::string & format () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const VideoRecord &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_format ()
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_save_filename ()
VideoRecord * New () const final
VideoRecord * New (::google::protobuf::Arena *arena) const final
VideoRecord & operator= (const VideoRecord &from)
::std::string * release_format ()
::ignition::msgs::Header * release_header ()
::std::string * release_save_filename ()
const ::std::string & save_filename () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_format (::std::string *format)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_save_filename (::std::string *save_filename)
void set_format (const ::std::string &value)
void set_format (const char *value)
void set_format (const char *value, size_t size)
void set_save_filename (const ::std::string &value)
void set_save_filename (const char *value)
void set_save_filename (const char *value, size_t size)
void set_start (bool value)
void set_stop (bool value)
bool start () const
bool stop () const
void Swap (VideoRecord *other)
Static Public Member Functions
static const VideoRecord & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const VideoRecord * internal_default_instance ()
Static Public Attributes
static const int kFormatFieldNumber = 4
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kSaveFilenameFieldNumber = 5
static const int kStartFieldNumber = 2
static const int kStopFieldNumber = 3
Constructor & Destructor Documentation
VideoRecord() [1/2]
VideoRecord ()
~VideoRecord()
virtual ~VideoRecord () virtual
VideoRecord() [2/2]
VideoRecord (const VideoRecord & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_format()
void clear_format () inline
clear_header()
void clear_header ()
clear_save_filename()
void clear_save_filename () inline
clear_start()
void clear_start () inline
clear_stop()
void clear_stop () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const VideoRecord & from)
default_instance()
static const VideoRecord& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
format()
const ::std::string & format () const inline
Referenced by VideoRecord::set_allocated_format().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References VideoRecord::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by VideoRecord::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const VideoRecord* internal_default_instance () inline static
References ignition::msgs::_VideoRecord_default_instance_.
Referenced by VideoRecord::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const VideoRecord & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_format()
std::string * mutable_format () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_save_filename()
std::string * mutable_save_filename () inline
New() [1/2]
VideoRecord* New () const inline final
New() [2/2]
VideoRecord* New (::google::protobuf::Arena * arena) const inline final
operator=()
VideoRecord& operator= (const VideoRecord & from) inline
release_format()
std::string * release_format () inline
release_header()
ignition::msgs::Header * release_header () inline
release_save_filename()
std::string * release_save_filename () inline
save_filename()
const ::std::string & save_filename () const inline
Referenced by VideoRecord::set_allocated_save_filename().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_format()
void set_allocated_format (::std::string * format) inline
References VideoRecord::format().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References VideoRecord::header().
set_allocated_save_filename()
void set_allocated_save_filename (::std::string * save_filename) inline
References VideoRecord::save_filename().
set_format() [1/3]
void set_format (const ::std::string & value) inline
set_format() [2/3]
void set_format (const char * value) inline
set_format() [3/3]
void set_format (const char * value, size_t size) inline
set_save_filename() [1/3]
void set_save_filename (const ::std::string & value) inline
set_save_filename() [2/3]
void set_save_filename (const char * value) inline
set_save_filename() [3/3]
void set_save_filename (const char * value, size_t size) inline
set_start()
void set_start (bool value) inline
set_stop()
void set_stop (bool value) inline
start()
bool start () const inline
stop()
bool stop () const inline
Swap()
void Swap (VideoRecord * other)
Member Data Documentation
kFormatFieldNumber
const int kFormatFieldNumber = 4 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kSaveFilenameFieldNumber
const int kSaveFilenameFieldNumber = 5 static
kStartFieldNumber
const int kStartFieldNumber = 2 static
kStopFieldNumber
const int kStopFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/video_record.pb.h