Gazebo Msgs: TopicInfo Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
TopicInfo Class Reference
#include <topic_info.pb.h>
Public Member Functions
TopicInfo ()
TopicInfo (const TopicInfo &from)
virtual ~TopicInfo ()
::ignition::msgs::Publish * add_publisher ()
::ignition::msgs::Subscribe * add_subscriber ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_msg_type ()
void clear_publisher ()
void clear_subscriber ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const TopicInfo &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const TopicInfo &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::std::string & msg_type () const
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_msg_type ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Publish > * mutable_publisher ()
::ignition::msgs::Publish * mutable_publisher (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Subscribe > * mutable_subscriber ()
::ignition::msgs::Subscribe * mutable_subscriber (int index)
TopicInfo * New () const final
TopicInfo * New (::google::protobuf::Arena *arena) const final
TopicInfo & operator= (const TopicInfo &from)
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Publish > & publisher () const
const ::ignition::msgs::Publish & publisher (int index) const
int publisher_size () const
::ignition::msgs::Header * release_header ()
::std::string * release_msg_type ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_msg_type (::std::string *msg_type)
void set_msg_type (const ::std::string &value)
void set_msg_type (const char *value)
void set_msg_type (const char *value, size_t size)
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Subscribe > & subscriber () const
const ::ignition::msgs::Subscribe & subscriber (int index) const
int subscriber_size () const
void Swap (TopicInfo *other)
Static Public Member Functions
static const TopicInfo & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const TopicInfo * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kMsgTypeFieldNumber = 2
static const int kPublisherFieldNumber = 3
static const int kSubscriberFieldNumber = 4
Constructor & Destructor Documentation
TopicInfo() [1/2]
TopicInfo ()
~TopicInfo()
virtual ~TopicInfo () virtual
TopicInfo() [2/2]
TopicInfo (const TopicInfo & from)
Member Function Documentation
add_publisher()
ignition::msgs::Publish * add_publisher () inline
add_subscriber()
ignition::msgs::Subscribe * add_subscriber () inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_msg_type()
void clear_msg_type () inline
clear_publisher()
void clear_publisher ()
clear_subscriber()
void clear_subscriber ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const TopicInfo & from)
default_instance()
static const TopicInfo& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References TopicInfo::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by TopicInfo::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const TopicInfo* internal_default_instance () inline static
References ignition::msgs::_TopicInfo_default_instance_.
Referenced by TopicInfo::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const TopicInfo & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
msg_type()
const ::std::string & msg_type () const inline
Referenced by TopicInfo::set_allocated_msg_type().
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_msg_type()
std::string * mutable_msg_type () inline
mutable_publisher() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Publish > * mutable_publisher () inline
mutable_publisher() [2/2]
ignition::msgs::Publish * mutable_publisher (int index) inline
mutable_subscriber() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Subscribe > * mutable_subscriber () inline
mutable_subscriber() [2/2]
ignition::msgs::Subscribe * mutable_subscriber (int index) inline
New() [1/2]
TopicInfo* New () const inline final
New() [2/2]
TopicInfo* New (::google::protobuf::Arena * arena) const inline final
operator=()
TopicInfo& operator= (const TopicInfo & from) inline
publisher() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Publish > & publisher () const inline
publisher() [2/2]
const ::ignition::msgs::Publish & publisher (int index) const inline
publisher_size()
int publisher_size () const inline
release_header()
ignition::msgs::Header * release_header () inline
release_msg_type()
std::string * release_msg_type () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References TopicInfo::header().
set_allocated_msg_type()
void set_allocated_msg_type (::std::string * msg_type) inline
References TopicInfo::msg_type().
set_msg_type() [1/3]
void set_msg_type (const ::std::string & value) inline
set_msg_type() [2/3]
void set_msg_type (const char * value) inline
set_msg_type() [3/3]
void set_msg_type (const char * value, size_t size) inline
subscriber() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Subscribe > & subscriber () const inline
subscriber() [2/2]
const ::ignition::msgs::Subscribe & subscriber (int index) const inline
subscriber_size()
int subscriber_size () const inline
Swap()
void Swap (TopicInfo * other)
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kMsgTypeFieldNumber
const int kMsgTypeFieldNumber = 2 static
kPublisherFieldNumber
const int kPublisherFieldNumber = 3 static
kSubscriberFieldNumber
const int kSubscriberFieldNumber = 4 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/topic_info.pb.h