Gazebo Msgs: ImageGeom Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
ImageGeom Class Reference
#include <imagegeom.pb.h>
Public Member Functions
ImageGeom ()
ImageGeom (const ImageGeom &from)
virtual ~ImageGeom ()
size_t ByteSizeLong () const final
void Clear () final
void clear_granularity ()
void clear_header ()
void clear_height ()
void clear_scale ()
void clear_threshold ()
void clear_uri ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const ImageGeom &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::int32 granularity () const
bool has_header () const
const ::ignition::msgs::Header & header () const
double height () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ImageGeom &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_uri ()
ImageGeom * New () const final
ImageGeom * New (::google::protobuf::Arena *arena) const final
ImageGeom & operator= (const ImageGeom &from)
::ignition::msgs::Header * release_header ()
::std::string * release_uri ()
double scale () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_uri (::std::string *uri)
void set_granularity (::google::protobuf::int32 value)
void set_height (double value)
void set_scale (double value)
void set_threshold (::google::protobuf::int32 value)
void set_uri (const ::std::string &value)
void set_uri (const char *value)
void set_uri (const char *value, size_t size)
void Swap (ImageGeom *other)
::google::protobuf::int32 threshold () const
const ::std::string & uri () const
Static Public Member Functions
static const ImageGeom & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const ImageGeom * internal_default_instance ()
Static Public Attributes
static const int kGranularityFieldNumber = 6
static const int kHeaderFieldNumber = 1
static const int kHeightFieldNumber = 5
static constexpr int kIndexInFileMessages
static const int kScaleFieldNumber = 3
static const int kThresholdFieldNumber = 4
static const int kUriFieldNumber = 2
Constructor & Destructor Documentation
ImageGeom() [1/2]
ImageGeom ()
~ImageGeom()
virtual ~ImageGeom () virtual
ImageGeom() [2/2]
ImageGeom (const ImageGeom & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_granularity()
void clear_granularity () inline
clear_header()
void clear_header ()
clear_height()
void clear_height () inline
clear_scale()
void clear_scale () inline
clear_threshold()
void clear_threshold () inline
clear_uri()
void clear_uri () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const ImageGeom & from)
default_instance()
static const ImageGeom& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
granularity()
google::protobuf::int32 granularity () const inline
has_header()
bool has_header () const inline
References ImageGeom::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by ImageGeom::set_allocated_header().
height()
double height () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const ImageGeom* internal_default_instance () inline static
References ignition::msgs::_ImageGeom_default_instance_.
Referenced by ImageGeom::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const ImageGeom & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_uri()
std::string * mutable_uri () inline
New() [1/2]
ImageGeom* New () const inline final
New() [2/2]
ImageGeom* New (::google::protobuf::Arena * arena) const inline final
operator=()
ImageGeom& operator= (const ImageGeom & from) inline
release_header()
ignition::msgs::Header * release_header () inline
release_uri()
std::string * release_uri () inline
scale()
double scale () const inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References ImageGeom::header().
set_allocated_uri()
void set_allocated_uri (::std::string * uri) inline
References ImageGeom::uri().
set_granularity()
void set_granularity (::google::protobuf::int32 value) inline
set_height()
void set_height (double value) inline
set_scale()
void set_scale (double value) inline
set_threshold()
void set_threshold (::google::protobuf::int32 value) inline
set_uri() [1/3]
void set_uri (const ::std::string & value) inline
set_uri() [2/3]
void set_uri (const char * value) inline
set_uri() [3/3]
void set_uri (const char * value, size_t size) inline
Swap()
void Swap (ImageGeom * other)
threshold()
google::protobuf::int32 threshold () const inline
uri()
const ::std::string & uri () const inline
Referenced by ImageGeom::set_allocated_uri().
Member Data Documentation
kGranularityFieldNumber
const int kGranularityFieldNumber = 6 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHeightFieldNumber
const int kHeightFieldNumber = 5 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kScaleFieldNumber
const int kScaleFieldNumber = 3 static
kThresholdFieldNumber
const int kThresholdFieldNumber = 4 static
kUriFieldNumber
const int kUriFieldNumber = 2 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/imagegeom.pb.h