Gazebo Msgs: Pose Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Pose Class Reference
#include <pose.pb.h>
Public Member Functions
Pose ()
Pose (const Pose &from)
virtual ~Pose ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_id ()
void clear_name ()
void clear_orientation ()
void clear_position ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Pose &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_orientation () const
bool has_position () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Pose &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_name ()
::ignition::msgs::Quaternion * mutable_orientation ()
::ignition::msgs::Vector3d * mutable_position ()
const ::std::string & name () const
Pose * New () const final
Pose * New (::google::protobuf::Arena *arena) const final
Pose & operator= (const Pose &from)
const ::ignition::msgs::Quaternion & orientation () const
const ::ignition::msgs::Vector3d & position () const
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
::ignition::msgs::Quaternion * release_orientation ()
::ignition::msgs::Vector3d * release_position ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_orientation (::ignition::msgs::Quaternion *orientation)
void set_allocated_position (::ignition::msgs::Vector3d *position)
void set_id (::google::protobuf::uint32 value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void Swap (Pose *other)
Static Public Member Functions
static const Pose & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Pose * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 2
static const int kOrientationFieldNumber = 5
static const int kPositionFieldNumber = 4
Constructor & Destructor Documentation
Pose() [1/2]
Pose ()
~Pose()
virtual ~Pose () virtual
Pose() [2/2]
Pose (const Pose & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_name()
void clear_name () inline
clear_orientation()
void clear_orientation ()
clear_position()
void clear_position ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Pose & from)
default_instance()
static const Pose& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Pose::internal_default_instance().
has_orientation()
bool has_orientation () const inline
References Pose::internal_default_instance().
has_position()
bool has_position () const inline
References Pose::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Pose::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Pose* internal_default_instance () inline static
References ignition::msgs::_Pose_default_instance_.
Referenced by Pose::has_header(), Pose::has_orientation(), and Pose::has_position().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Pose & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
mutable_orientation()
ignition::msgs::Quaternion * mutable_orientation () inline
mutable_position()
ignition::msgs::Vector3d * mutable_position () inline
name()
const ::std::string & name () const inline
Referenced by Pose::set_allocated_name().
New() [1/2]
Pose* New () const inline final
New() [2/2]
Pose* New (::google::protobuf::Arena * arena) const inline final
operator=()
Pose& operator= (const Pose & from) inline
orientation()
const ::ignition::msgs::Quaternion & orientation () const inline
References ignition::msgs::_Quaternion_default_instance_.
Referenced by Pose::set_allocated_orientation().
position()
const ::ignition::msgs::Vector3d & position () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by Pose::set_allocated_position().
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_orientation()
ignition::msgs::Quaternion * release_orientation () inline
release_position()
ignition::msgs::Vector3d * release_position () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Pose::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Pose::name().
set_allocated_orientation()
void set_allocated_orientation (::ignition::msgs::Quaternion * orientation) inline
References Pose::orientation().
set_allocated_position()
void set_allocated_position (::ignition::msgs::Vector3d * position) inline
References Pose::position().
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
Swap()
void Swap (Pose * other)
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 2 static
kOrientationFieldNumber
const int kOrientationFieldNumber = 5 static
kPositionFieldNumber
const int kPositionFieldNumber = 4 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/pose.pb.h