Gazebo Msgs: JointWrench Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
JointWrench Class Reference
#include <joint_wrench.pb.h>
Public Member Functions
JointWrench ()
JointWrench (const JointWrench &from)
virtual ~JointWrench ()
::google::protobuf::uint32 body_1_id () const
const ::std::string & body_1_name () const
const ::ignition::msgs::Wrench & body_1_wrench () const
::google::protobuf::uint32 body_2_id () const
const ::std::string & body_2_name () const
const ::ignition::msgs::Wrench & body_2_wrench () const
size_t ByteSizeLong () const final
void Clear () final
void clear_body_1_id ()
void clear_body_1_name ()
void clear_body_1_wrench ()
void clear_body_2_id ()
void clear_body_2_name ()
void clear_body_2_wrench ()
void clear_header ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const JointWrench &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_body_1_wrench () const
bool has_body_2_wrench () const
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const JointWrench &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_body_1_name ()
::ignition::msgs::Wrench * mutable_body_1_wrench ()
::std::string * mutable_body_2_name ()
::ignition::msgs::Wrench * mutable_body_2_wrench ()
::ignition::msgs::Header * mutable_header ()
JointWrench * New () const final
JointWrench * New (::google::protobuf::Arena *arena) const final
JointWrench & operator= (const JointWrench &from)
::std::string * release_body_1_name ()
::ignition::msgs::Wrench * release_body_1_wrench ()
::std::string * release_body_2_name ()
::ignition::msgs::Wrench * release_body_2_wrench ()
::ignition::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_body_1_name (::std::string *body_1_name)
void set_allocated_body_1_wrench (::ignition::msgs::Wrench *body_1_wrench)
void set_allocated_body_2_name (::std::string *body_2_name)
void set_allocated_body_2_wrench (::ignition::msgs::Wrench *body_2_wrench)
void set_allocated_header (::ignition::msgs::Header *header)
void set_body_1_id (::google::protobuf::uint32 value)
void set_body_1_name (const ::std::string &value)
void set_body_1_name (const char *value)
void set_body_1_name (const char *value, size_t size)
void set_body_2_id (::google::protobuf::uint32 value)
void set_body_2_name (const ::std::string &value)
void set_body_2_name (const char *value)
void set_body_2_name (const char *value, size_t size)
void Swap (JointWrench *other)
Static Public Member Functions
static const JointWrench & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const JointWrench * internal_default_instance ()
Static Public Attributes
static const int kBody1IdFieldNumber = 3
static const int kBody1NameFieldNumber = 2
static const int kBody1WrenchFieldNumber = 6
static const int kBody2IdFieldNumber = 5
static const int kBody2NameFieldNumber = 4
static const int kBody2WrenchFieldNumber = 7
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
Constructor & Destructor Documentation
JointWrench() [1/2]
JointWrench ()
~JointWrench()
virtual ~JointWrench () virtual
JointWrench() [2/2]
JointWrench (const JointWrench & from)
Member Function Documentation
body_1_id()
google::protobuf::uint32 body_1_id () const inline
body_1_name()
const ::std::string & body_1_name () const inline
Referenced by JointWrench::set_allocated_body_1_name().
body_1_wrench()
const ::ignition::msgs::Wrench & body_1_wrench () const inline
References ignition::msgs::_Wrench_default_instance_.
Referenced by JointWrench::set_allocated_body_1_wrench().
body_2_id()
google::protobuf::uint32 body_2_id () const inline
body_2_name()
const ::std::string & body_2_name () const inline
Referenced by JointWrench::set_allocated_body_2_name().
body_2_wrench()
const ::ignition::msgs::Wrench & body_2_wrench () const inline
References ignition::msgs::_Wrench_default_instance_.
Referenced by JointWrench::set_allocated_body_2_wrench().
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_body_1_id()
void clear_body_1_id () inline
clear_body_1_name()
void clear_body_1_name () inline
clear_body_1_wrench()
void clear_body_1_wrench ()
clear_body_2_id()
void clear_body_2_id () inline
clear_body_2_name()
void clear_body_2_name () inline
clear_body_2_wrench()
void clear_body_2_wrench ()
clear_header()
void clear_header ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const JointWrench & from)
default_instance()
static const JointWrench& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_body_1_wrench()
bool has_body_1_wrench () const inline
References JointWrench::internal_default_instance().
has_body_2_wrench()
bool has_body_2_wrench () const inline
References JointWrench::internal_default_instance().
has_header()
bool has_header () const inline
References JointWrench::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by JointWrench::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const JointWrench* internal_default_instance () inline static
References ignition::msgs::_JointWrench_default_instance_.
Referenced by JointWrench::has_body_1_wrench(), JointWrench::has_body_2_wrench(), and JointWrench::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const JointWrench & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_body_1_name()
std::string * mutable_body_1_name () inline
mutable_body_1_wrench()
ignition::msgs::Wrench * mutable_body_1_wrench () inline
mutable_body_2_name()
std::string * mutable_body_2_name () inline
mutable_body_2_wrench()
ignition::msgs::Wrench * mutable_body_2_wrench () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
New() [1/2]
JointWrench* New () const inline final
New() [2/2]
JointWrench* New (::google::protobuf::Arena * arena) const inline final
operator=()
JointWrench& operator= (const JointWrench & from) inline
release_body_1_name()
std::string * release_body_1_name () inline
release_body_1_wrench()
ignition::msgs::Wrench * release_body_1_wrench () inline
release_body_2_name()
std::string * release_body_2_name () inline
release_body_2_wrench()
ignition::msgs::Wrench * release_body_2_wrench () inline
release_header()
ignition::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_body_1_name()
void set_allocated_body_1_name (::std::string * body_1_name) inline
References JointWrench::body_1_name().
set_allocated_body_1_wrench()
void set_allocated_body_1_wrench (::ignition::msgs::Wrench * body_1_wrench) inline
References JointWrench::body_1_wrench().
set_allocated_body_2_name()
void set_allocated_body_2_name (::std::string * body_2_name) inline
References JointWrench::body_2_name().
set_allocated_body_2_wrench()
void set_allocated_body_2_wrench (::ignition::msgs::Wrench * body_2_wrench) inline
References JointWrench::body_2_wrench().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References JointWrench::header().
set_body_1_id()
void set_body_1_id (::google::protobuf::uint32 value) inline
set_body_1_name() [1/3]
void set_body_1_name (const ::std::string & value) inline
set_body_1_name() [2/3]
void set_body_1_name (const char * value) inline
set_body_1_name() [3/3]
void set_body_1_name (const char * value, size_t size) inline
set_body_2_id()
void set_body_2_id (::google::protobuf::uint32 value) inline
set_body_2_name() [1/3]
void set_body_2_name (const ::std::string & value) inline
set_body_2_name() [2/3]
void set_body_2_name (const char * value) inline
set_body_2_name() [3/3]
void set_body_2_name (const char * value, size_t size) inline
Swap()
void Swap (JointWrench * other)
Member Data Documentation
kBody1IdFieldNumber
const int kBody1IdFieldNumber = 3 static
kBody1NameFieldNumber
const int kBody1NameFieldNumber = 2 static
kBody1WrenchFieldNumber
const int kBody1WrenchFieldNumber = 6 static
kBody2IdFieldNumber
const int kBody2IdFieldNumber = 5 static
kBody2NameFieldNumber
const int kBody2NameFieldNumber = 4 static
kBody2WrenchFieldNumber
const int kBody2WrenchFieldNumber = 7 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/joint_wrench.pb.h