Gazebo Msgs: Packet Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Packet Class Reference
#include <packet.pb.h>
Public Types
enum ContentCase {
kCmdVel2D = 3, kImage = 4, kStringMsgV = 5, kWebRequest = 6,
kPose = 7, kDoublev = 8, kPoseV = 9, kTime = 10,
kClock = 11, kWorldStats = 12, CONTENT_NOT_SET = 0
}
Public Member Functions
Packet ()
Packet (const Packet &from)
virtual ~Packet ()
size_t ByteSizeLong () const final
void Clear () final
void clear_clock ()
void clear_cmd_vel2d ()
void clear_content ()
void clear_doublev ()
void clear_image ()
void clear_pose ()
void clear_pose_v ()
void clear_string_msg_v ()
void clear_time ()
void clear_topic ()
void clear_type ()
void clear_web_request ()
void clear_world_stats ()
const ::ignition::msgs::Clock & clock () const
const ::ignition::msgs::CmdVel2D & cmd_vel2d () const
ContentCase content_case () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Packet &from)
const ::ignition::msgs::Double_V & doublev () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_clock () const
bool has_cmd_vel2d () const
bool has_doublev () const
bool has_image () const
bool has_pose () const
bool has_pose_v () const
bool has_string_msg_v () const
bool has_time () const
bool has_web_request () const
bool has_world_stats () const
const ::ignition::msgs::Image & image () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Packet &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Clock * mutable_clock ()
::ignition::msgs::CmdVel2D * mutable_cmd_vel2d ()
::ignition::msgs::Double_V * mutable_doublev ()
::ignition::msgs::Image * mutable_image ()
::ignition::msgs::Pose * mutable_pose ()
::ignition::msgs::Pose_V * mutable_pose_v ()
::ignition::msgs::StringMsg_V * mutable_string_msg_v ()
::ignition::msgs::Time * mutable_time ()
::std::string * mutable_topic ()
::std::string * mutable_type ()
::ignition::msgs::WebRequest * mutable_web_request ()
::ignition::msgs::WorldStatistics * mutable_world_stats ()
Packet * New () const final
Packet * New (::google::protobuf::Arena *arena) const final
Packet & operator= (const Packet &from)
const ::ignition::msgs::Pose & pose () const
const ::ignition::msgs::Pose_V & pose_v () const
::ignition::msgs::Clock * release_clock ()
::ignition::msgs::CmdVel2D * release_cmd_vel2d ()
::ignition::msgs::Double_V * release_doublev ()
::ignition::msgs::Image * release_image ()
::ignition::msgs::Pose * release_pose ()
::ignition::msgs::Pose_V * release_pose_v ()
::ignition::msgs::StringMsg_V * release_string_msg_v ()
::ignition::msgs::Time * release_time ()
::std::string * release_topic ()
::std::string * release_type ()
::ignition::msgs::WebRequest * release_web_request ()
::ignition::msgs::WorldStatistics * release_world_stats ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_clock (::ignition::msgs::Clock *clock)
void set_allocated_cmd_vel2d (::ignition::msgs::CmdVel2D *cmd_vel2d)
void set_allocated_doublev (::ignition::msgs::Double_V *doublev)
void set_allocated_image (::ignition::msgs::Image *image)
void set_allocated_pose (::ignition::msgs::Pose *pose)
void set_allocated_pose_v (::ignition::msgs::Pose_V *pose_v)
void set_allocated_string_msg_v (::ignition::msgs::StringMsg_V *string_msg_v)
void set_allocated_time (::ignition::msgs::Time *time)
void set_allocated_topic (::std::string *topic)
void set_allocated_type (::std::string *type)
void set_allocated_web_request (::ignition::msgs::WebRequest *web_request)
void set_allocated_world_stats (::ignition::msgs::WorldStatistics *world_stats)
void set_topic (const ::std::string &value)
void set_topic (const char *value)
void set_topic (const char *value, size_t size)
void set_type (const ::std::string &value)
void set_type (const char *value)
void set_type (const char *value, size_t size)
const ::ignition::msgs::StringMsg_V & string_msg_v () const
void Swap (Packet *other)
const ::ignition::msgs::Time & time () const
const ::std::string & topic () const
const ::std::string & type () const
const ::ignition::msgs::WebRequest & web_request () const
const ::ignition::msgs::WorldStatistics & world_stats () const
Static Public Member Functions
static const Packet & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Packet * internal_default_instance ()
Static Public Attributes
static const int kClockFieldNumber = 11
static const int kCmdVel2DFieldNumber = 3
static const int kDoublevFieldNumber = 8
static const int kImageFieldNumber = 4
static constexpr int kIndexInFileMessages
static const int kPoseFieldNumber = 7
static const int kPoseVFieldNumber = 9
static const int kStringMsgVFieldNumber = 5
static const int kTimeFieldNumber = 10
static const int kTopicFieldNumber = 1
static const int kTypeFieldNumber = 2
static const int kWebRequestFieldNumber = 6
static const int kWorldStatsFieldNumber = 12
Member Enumeration Documentation
ContentCase
enum ContentCase
Enumerator
kCmdVel2D
kImage
kStringMsgV
kWebRequest
kPose
kDoublev
kPoseV
kTime
kClock
kWorldStats
CONTENT_NOT_SET
Constructor & Destructor Documentation
Packet() [1/2]
Packet ()
~Packet()
virtual ~Packet () virtual
Packet() [2/2]
Packet (const Packet & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_clock()
void clear_clock ()
clear_cmd_vel2d()
void clear_cmd_vel2d ()
clear_content()
void clear_content ()
Referenced by Packet::mutable_clock(), Packet::mutable_cmd_vel2d(), Packet::mutable_doublev(), Packet::mutable_image(), Packet::mutable_pose(), Packet::mutable_pose_v(), Packet::mutable_string_msg_v(), Packet::mutable_time(), Packet::mutable_web_request(), and Packet::mutable_world_stats().
clear_doublev()
void clear_doublev ()
clear_image()
void clear_image ()
clear_pose()
void clear_pose ()
clear_pose_v()
void clear_pose_v ()
clear_string_msg_v()
void clear_string_msg_v ()
clear_time()
void clear_time ()
clear_topic()
void clear_topic () inline
clear_type()
void clear_type () inline
clear_web_request()
void clear_web_request ()
clear_world_stats()
void clear_world_stats ()
clock()
const ::ignition::msgs::Clock & clock () const inline
References ignition::msgs::_Clock_default_instance_, and Packet::has_clock().
cmd_vel2d()
const ::ignition::msgs::CmdVel2D & cmd_vel2d () const inline
References ignition::msgs::_CmdVel2D_default_instance_, and Packet::has_cmd_vel2d().
content_case()
Packet::ContentCase content_case () const inline
Referenced by Packet::has_clock(), Packet::has_cmd_vel2d(), Packet::has_doublev(), Packet::has_image(), Packet::has_pose(), Packet::has_pose_v(), Packet::has_string_msg_v(), Packet::has_time(), Packet::has_web_request(), and Packet::has_world_stats().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Packet & from)
default_instance()
static const Packet& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
doublev()
const ::ignition::msgs::Double_V & doublev () const inline
References ignition::msgs::_Double_V_default_instance_, and Packet::has_doublev().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_clock()
bool has_clock () const inline
References Packet::content_case(), and Packet::kClock.
Referenced by Packet::clock(), Packet::mutable_clock(), and Packet::release_clock().
has_cmd_vel2d()
bool has_cmd_vel2d () const inline
References Packet::content_case(), and Packet::kCmdVel2D.
Referenced by Packet::cmd_vel2d(), Packet::mutable_cmd_vel2d(), and Packet::release_cmd_vel2d().
has_doublev()
bool has_doublev () const inline
References Packet::content_case(), and Packet::kDoublev.
Referenced by Packet::doublev(), Packet::mutable_doublev(), and Packet::release_doublev().
has_image()
bool has_image () const inline
References Packet::content_case(), and Packet::kImage.
Referenced by Packet::image(), Packet::mutable_image(), and Packet::release_image().
has_pose()
bool has_pose () const inline
References Packet::content_case(), and Packet::kPose.
Referenced by Packet::mutable_pose(), Packet::pose(), and Packet::release_pose().
has_pose_v()
bool has_pose_v () const inline
References Packet::content_case(), and Packet::kPoseV.
Referenced by Packet::mutable_pose_v(), Packet::pose_v(), and Packet::release_pose_v().
has_string_msg_v()
bool has_string_msg_v () const inline
References Packet::content_case(), and Packet::kStringMsgV.
Referenced by Packet::mutable_string_msg_v(), Packet::release_string_msg_v(), and Packet::string_msg_v().
has_time()
bool has_time () const inline
References Packet::content_case(), and Packet::kTime.
Referenced by Packet::mutable_time(), Packet::release_time(), and Packet::time().
has_web_request()
bool has_web_request () const inline
References Packet::content_case(), and Packet::kWebRequest.
Referenced by Packet::mutable_web_request(), Packet::release_web_request(), and Packet::web_request().
has_world_stats()
bool has_world_stats () const inline
References Packet::content_case(), and Packet::kWorldStats.
Referenced by Packet::mutable_world_stats(), Packet::release_world_stats(), and Packet::world_stats().
image()
const ::ignition::msgs::Image & image () const inline
References ignition::msgs::_Image_default_instance_, and Packet::has_image().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Packet* internal_default_instance () inline static
References ignition::msgs::_Packet_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Packet & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_clock()
ignition::msgs::Clock * mutable_clock () inline
References Packet::clear_content(), and Packet::has_clock().
mutable_cmd_vel2d()
ignition::msgs::CmdVel2D * mutable_cmd_vel2d () inline
References Packet::clear_content(), and Packet::has_cmd_vel2d().
mutable_doublev()
ignition::msgs::Double_V * mutable_doublev () inline
References Packet::clear_content(), and Packet::has_doublev().
mutable_image()
ignition::msgs::Image * mutable_image () inline
References Packet::clear_content(), and Packet::has_image().
mutable_pose()
ignition::msgs::Pose * mutable_pose () inline
References Packet::clear_content(), and Packet::has_pose().
mutable_pose_v()
ignition::msgs::Pose_V * mutable_pose_v () inline
References Packet::clear_content(), and Packet::has_pose_v().
mutable_string_msg_v()
ignition::msgs::StringMsg_V * mutable_string_msg_v () inline
References Packet::clear_content(), and Packet::has_string_msg_v().
mutable_time()
ignition::msgs::Time * mutable_time () inline
References Packet::clear_content(), and Packet::has_time().
mutable_topic()
std::string * mutable_topic () inline
mutable_type()
std::string * mutable_type () inline
mutable_web_request()
ignition::msgs::WebRequest * mutable_web_request () inline
References Packet::clear_content(), and Packet::has_web_request().
mutable_world_stats()
ignition::msgs::WorldStatistics * mutable_world_stats () inline
References Packet::clear_content(), and Packet::has_world_stats().
New() [1/2]
Packet* New () const inline final
New() [2/2]
Packet* New (::google::protobuf::Arena * arena) const inline final
operator=()
Packet& operator= (const Packet & from) inline
pose()
const ::ignition::msgs::Pose & pose () const inline
References ignition::msgs::_Pose_default_instance_, and Packet::has_pose().
pose_v()
const ::ignition::msgs::Pose_V & pose_v () const inline
References ignition::msgs::_Pose_V_default_instance_, and Packet::has_pose_v().
release_clock()
ignition::msgs::Clock * release_clock () inline
References Packet::has_clock().
release_cmd_vel2d()
ignition::msgs::CmdVel2D * release_cmd_vel2d () inline
References Packet::has_cmd_vel2d().
release_doublev()
ignition::msgs::Double_V * release_doublev () inline
References Packet::has_doublev().
release_image()
ignition::msgs::Image * release_image () inline
References Packet::has_image().
release_pose()
ignition::msgs::Pose * release_pose () inline
References Packet::has_pose().
release_pose_v()
ignition::msgs::Pose_V * release_pose_v () inline
References Packet::has_pose_v().
release_string_msg_v()
ignition::msgs::StringMsg_V * release_string_msg_v () inline
References Packet::has_string_msg_v().
release_time()
ignition::msgs::Time * release_time () inline
References Packet::has_time().
release_topic()
std::string * release_topic () inline
release_type()
std::string * release_type () inline
release_web_request()
ignition::msgs::WebRequest * release_web_request () inline
References Packet::has_web_request().
release_world_stats()
ignition::msgs::WorldStatistics * release_world_stats () inline
References Packet::has_world_stats().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_clock()
void set_allocated_clock (::ignition::msgs::Clock * clock)
set_allocated_cmd_vel2d()
void set_allocated_cmd_vel2d (::ignition::msgs::CmdVel2D * cmd_vel2d)
set_allocated_doublev()
void set_allocated_doublev (::ignition::msgs::Double_V * doublev)
set_allocated_image()
void set_allocated_image (::ignition::msgs::Image * image)
set_allocated_pose()
void set_allocated_pose (::ignition::msgs::Pose * pose)
set_allocated_pose_v()
void set_allocated_pose_v (::ignition::msgs::Pose_V * pose_v)
set_allocated_string_msg_v()
void set_allocated_string_msg_v (::ignition::msgs::StringMsg_V * string_msg_v)
set_allocated_time()
void set_allocated_time (::ignition::msgs::Time * time)
set_allocated_topic()
void set_allocated_topic (::std::string * topic) inline
References Packet::topic().
set_allocated_type()
void set_allocated_type (::std::string * type) inline
References Packet::type().
set_allocated_web_request()
void set_allocated_web_request (::ignition::msgs::WebRequest * web_request)
set_allocated_world_stats()
void set_allocated_world_stats (::ignition::msgs::WorldStatistics * world_stats)
set_topic() [1/3]
void set_topic (const ::std::string & value) inline
set_topic() [2/3]
void set_topic (const char * value) inline
set_topic() [3/3]
void set_topic (const char * value, size_t size) inline
set_type() [1/3]
void set_type (const ::std::string & value) inline
set_type() [2/3]
void set_type (const char * value) inline
set_type() [3/3]
void set_type (const char * value, size_t size) inline
string_msg_v()
const ::ignition::msgs::StringMsg_V & string_msg_v () const inline
References ignition::msgs::_StringMsg_V_default_instance_, and Packet::has_string_msg_v().
Swap()
void Swap (Packet * other)
time()
const ::ignition::msgs::Time & time () const inline
References ignition::msgs::_Time_default_instance_, and Packet::has_time().
topic()
const ::std::string & topic () const inline
Referenced by Packet::set_allocated_topic().
type()
const ::std::string & type () const inline
Referenced by Packet::set_allocated_type().
web_request()
const ::ignition::msgs::WebRequest & web_request () const inline
References ignition::msgs::_WebRequest_default_instance_, and Packet::has_web_request().
world_stats()
const ::ignition::msgs::WorldStatistics & world_stats () const inline
References ignition::msgs::_WorldStatistics_default_instance_, and Packet::has_world_stats().
Member Data Documentation
kClockFieldNumber
const int kClockFieldNumber = 11 static
kCmdVel2DFieldNumber
const int kCmdVel2DFieldNumber = 3 static
kDoublevFieldNumber
const int kDoublevFieldNumber = 8 static
kImageFieldNumber
const int kImageFieldNumber = 4 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kPoseFieldNumber
const int kPoseFieldNumber = 7 static
kPoseVFieldNumber
const int kPoseVFieldNumber = 9 static
kStringMsgVFieldNumber
const int kStringMsgVFieldNumber = 5 static
kTimeFieldNumber
const int kTimeFieldNumber = 10 static
kTopicFieldNumber
const int kTopicFieldNumber = 1 static
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
kWebRequestFieldNumber
const int kWebRequestFieldNumber = 6 static
kWorldStatsFieldNumber
const int kWorldStatsFieldNumber = 12 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/packet.pb.h