Gazebo Msgs: EntityFactory Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
EntityFactory Class Reference
#include <entity_factory.pb.h>
Public Types
enum FromCase {
kSdf = 2, kSdfFilename = 3, kModel = 4, kLight = 5,
kCloneName = 6, FROM_NOT_SET = 0
}
Public Member Functions
EntityFactory ()
EntityFactory (const EntityFactory &from)
virtual ~EntityFactory ()
bool allow_renaming () const
size_t ByteSizeLong () const final
void Clear () final
void clear_allow_renaming ()
void clear_clone_name ()
void clear_from ()
void clear_header ()
void clear_light ()
void clear_model ()
void clear_name ()
void clear_pose ()
void clear_relative_to ()
void clear_sdf ()
void clear_sdf_filename ()
const ::std::string & clone_name () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const EntityFactory &from)
FromCase from_case () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_light () const
bool has_model () const
bool has_pose () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::ignition::msgs::Light & light () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const EntityFactory &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::ignition::msgs::Model & model () const
::std::string * mutable_clone_name ()
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::Light * mutable_light ()
::ignition::msgs::Model * mutable_model ()
::std::string * mutable_name ()
::ignition::msgs::Pose * mutable_pose ()
::std::string * mutable_relative_to ()
::std::string * mutable_sdf ()
::std::string * mutable_sdf_filename ()
const ::std::string & name () const
EntityFactory * New () const final
EntityFactory * New (::google::protobuf::Arena *arena) const final
EntityFactory & operator= (const EntityFactory &from)
const ::ignition::msgs::Pose & pose () const
const ::std::string & relative_to () const
::std::string * release_clone_name ()
::ignition::msgs::Header * release_header ()
::ignition::msgs::Light * release_light ()
::ignition::msgs::Model * release_model ()
::std::string * release_name ()
::ignition::msgs::Pose * release_pose ()
::std::string * release_relative_to ()
::std::string * release_sdf ()
::std::string * release_sdf_filename ()
const ::std::string & sdf () const
const ::std::string & sdf_filename () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_clone_name (::std::string *clone_name)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_light (::ignition::msgs::Light *light)
void set_allocated_model (::ignition::msgs::Model *model)
void set_allocated_name (::std::string *name)
void set_allocated_pose (::ignition::msgs::Pose *pose)
void set_allocated_relative_to (::std::string *relative_to)
void set_allocated_sdf (::std::string *sdf)
void set_allocated_sdf_filename (::std::string *sdf_filename)
void set_allow_renaming (bool value)
void set_clone_name (const ::std::string &value)
void set_clone_name (const char *value)
void set_clone_name (const char *value, size_t size)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_relative_to (const ::std::string &value)
void set_relative_to (const char *value)
void set_relative_to (const char *value, size_t size)
void set_sdf (const ::std::string &value)
void set_sdf (const char *value)
void set_sdf (const char *value, size_t size)
void set_sdf_filename (const ::std::string &value)
void set_sdf_filename (const char *value)
void set_sdf_filename (const char *value, size_t size)
void Swap (EntityFactory *other)
Static Public Member Functions
static const EntityFactory & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const EntityFactory * internal_default_instance ()
Static Public Attributes
static const int kAllowRenamingFieldNumber = 9
static const int kCloneNameFieldNumber = 6
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kLightFieldNumber = 5
static const int kModelFieldNumber = 4
static const int kNameFieldNumber = 8
static const int kPoseFieldNumber = 7
static const int kRelativeToFieldNumber = 10
static const int kSdfFieldNumber = 2
static const int kSdfFilenameFieldNumber = 3
Member Enumeration Documentation
FromCase
enum FromCase
Enumerator
kSdf
kSdfFilename
kModel
kLight
kCloneName
FROM_NOT_SET
Constructor & Destructor Documentation
EntityFactory() [1/2]
EntityFactory ()
~EntityFactory()
virtual ~EntityFactory () virtual
EntityFactory() [2/2]
EntityFactory (const EntityFactory & from)
Member Function Documentation
allow_renaming()
bool allow_renaming () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_allow_renaming()
void clear_allow_renaming () inline
clear_clone_name()
void clear_clone_name () inline
clear_from()
void clear_from ()
Referenced by EntityFactory::mutable_clone_name(), EntityFactory::mutable_light(), EntityFactory::mutable_model(), EntityFactory::mutable_sdf(), EntityFactory::mutable_sdf_filename(), EntityFactory::set_allocated_clone_name(), EntityFactory::set_allocated_sdf(), EntityFactory::set_allocated_sdf_filename(), EntityFactory::set_clone_name(), EntityFactory::set_sdf(), and EntityFactory::set_sdf_filename().
clear_header()
void clear_header ()
clear_light()
void clear_light ()
clear_model()
void clear_model ()
clear_name()
void clear_name () inline
clear_pose()
void clear_pose ()
clear_relative_to()
void clear_relative_to () inline
clear_sdf()
void clear_sdf () inline
clear_sdf_filename()
void clear_sdf_filename () inline
clone_name()
const ::std::string & clone_name () const inline
Referenced by EntityFactory::set_allocated_clone_name().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const EntityFactory & from)
default_instance()
static const EntityFactory& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
from_case()
EntityFactory::FromCase from_case () const inline
Referenced by EntityFactory::has_light(), and EntityFactory::has_model().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References EntityFactory::internal_default_instance().
has_light()
bool has_light () const inline
References EntityFactory::from_case(), and EntityFactory::kLight.
Referenced by EntityFactory::light(), EntityFactory::mutable_light(), and EntityFactory::release_light().
has_model()
bool has_model () const inline
References EntityFactory::from_case(), and EntityFactory::kModel.
Referenced by EntityFactory::model(), EntityFactory::mutable_model(), and EntityFactory::release_model().
has_pose()
bool has_pose () const inline
References EntityFactory::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by EntityFactory::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const EntityFactory* internal_default_instance () inline static
References ignition::msgs::_EntityFactory_default_instance_.
Referenced by EntityFactory::has_header(), and EntityFactory::has_pose().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
light()
const ::ignition::msgs::Light & light () const inline
References ignition::msgs::_Light_default_instance_, and EntityFactory::has_light().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const EntityFactory & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
model()
const ::ignition::msgs::Model & model () const inline
References ignition::msgs::_Model_default_instance_, and EntityFactory::has_model().
mutable_clone_name()
std::string * mutable_clone_name () inline
References EntityFactory::clear_from().
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_light()
ignition::msgs::Light * mutable_light () inline
References EntityFactory::clear_from(), and EntityFactory::has_light().
mutable_model()
ignition::msgs::Model * mutable_model () inline
References EntityFactory::clear_from(), and EntityFactory::has_model().
mutable_name()
std::string * mutable_name () inline
mutable_pose()
ignition::msgs::Pose * mutable_pose () inline
mutable_relative_to()
std::string * mutable_relative_to () inline
mutable_sdf()
std::string * mutable_sdf () inline
References EntityFactory::clear_from().
mutable_sdf_filename()
std::string * mutable_sdf_filename () inline
References EntityFactory::clear_from().
name()
const ::std::string & name () const inline
Referenced by EntityFactory::set_allocated_name().
New() [1/2]
EntityFactory* New () const inline final
New() [2/2]
EntityFactory* New (::google::protobuf::Arena * arena) const inline final
operator=()
EntityFactory& operator= (const EntityFactory & from) inline
pose()
const ::ignition::msgs::Pose & pose () const inline
References ignition::msgs::_Pose_default_instance_.
Referenced by EntityFactory::set_allocated_pose().
relative_to()
const ::std::string & relative_to () const inline
Referenced by EntityFactory::set_allocated_relative_to().
release_clone_name()
std::string * release_clone_name () inline
release_header()
ignition::msgs::Header * release_header () inline
release_light()
ignition::msgs::Light * release_light () inline
References EntityFactory::has_light().
release_model()
ignition::msgs::Model * release_model () inline
References EntityFactory::has_model().
release_name()
std::string * release_name () inline
release_pose()
ignition::msgs::Pose * release_pose () inline
release_relative_to()
std::string * release_relative_to () inline
release_sdf()
std::string * release_sdf () inline
release_sdf_filename()
std::string * release_sdf_filename () inline
sdf()
const ::std::string & sdf () const inline
Referenced by EntityFactory::set_allocated_sdf().
sdf_filename()
const ::std::string & sdf_filename () const inline
Referenced by EntityFactory::set_allocated_sdf_filename().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_clone_name()
void set_allocated_clone_name (::std::string * clone_name) inline
References EntityFactory::clear_from(), and EntityFactory::clone_name().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References EntityFactory::header().
set_allocated_light()
void set_allocated_light (::ignition::msgs::Light * light)
set_allocated_model()
void set_allocated_model (::ignition::msgs::Model * model)
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References EntityFactory::name().
set_allocated_pose()
void set_allocated_pose (::ignition::msgs::Pose * pose) inline
References EntityFactory::pose().
set_allocated_relative_to()
void set_allocated_relative_to (::std::string * relative_to) inline
References EntityFactory::relative_to().
set_allocated_sdf()
void set_allocated_sdf (::std::string * sdf) inline
References EntityFactory::clear_from(), and EntityFactory::sdf().
set_allocated_sdf_filename()
void set_allocated_sdf_filename (::std::string * sdf_filename) inline
References EntityFactory::clear_from(), and EntityFactory::sdf_filename().
set_allow_renaming()
void set_allow_renaming (bool value) inline
set_clone_name() [1/3]
void set_clone_name (const ::std::string & value) inline
References EntityFactory::clear_from().
set_clone_name() [2/3]
void set_clone_name (const char * value) inline
References EntityFactory::clear_from().
set_clone_name() [3/3]
void set_clone_name (const char * value, size_t size) inline
References EntityFactory::clear_from().
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_relative_to() [1/3]
void set_relative_to (const ::std::string & value) inline
set_relative_to() [2/3]
void set_relative_to (const char * value) inline
set_relative_to() [3/3]
void set_relative_to (const char * value, size_t size) inline
set_sdf() [1/3]
void set_sdf (const ::std::string & value) inline
References EntityFactory::clear_from().
set_sdf() [2/3]
void set_sdf (const char * value) inline
References EntityFactory::clear_from().
set_sdf() [3/3]
void set_sdf (const char * value, size_t size) inline
References EntityFactory::clear_from().
set_sdf_filename() [1/3]
void set_sdf_filename (const ::std::string & value) inline
References EntityFactory::clear_from().
set_sdf_filename() [2/3]
void set_sdf_filename (const char * value) inline
References EntityFactory::clear_from().
set_sdf_filename() [3/3]
void set_sdf_filename (const char * value, size_t size) inline
References EntityFactory::clear_from().
Swap()
void Swap (EntityFactory * other)
Member Data Documentation
kAllowRenamingFieldNumber
const int kAllowRenamingFieldNumber = 9 static
kCloneNameFieldNumber
const int kCloneNameFieldNumber = 6 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLightFieldNumber
const int kLightFieldNumber = 5 static
kModelFieldNumber
const int kModelFieldNumber = 4 static
kNameFieldNumber
const int kNameFieldNumber = 8 static
kPoseFieldNumber
const int kPoseFieldNumber = 7 static
kRelativeToFieldNumber
const int kRelativeToFieldNumber = 10 static
kSdfFieldNumber
const int kSdfFieldNumber = 2 static
kSdfFilenameFieldNumber
const int kSdfFilenameFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/entity_factory.pb.h