Gazebo Msgs: Model Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Model Class Reference
#include <model.pb.h>
Public Member Functions
Model ()
Model (const Model &from)
virtual ~Model ()
::ignition::msgs::Joint * add_joint ()
::ignition::msgs::Link * add_link ()
::ignition::msgs::Model * add_model ()
::ignition::msgs::Visual * add_visual ()
const ::ignition::msgs::AxisAlignedBox & bounding_box () const
size_t ByteSizeLong () const final
void Clear () final
void clear_bounding_box ()
void clear_deleted ()
void clear_header ()
void clear_id ()
void clear_is_static ()
void clear_joint ()
void clear_link ()
void clear_model ()
void clear_name ()
void clear_pose ()
void clear_scale ()
void clear_self_collide ()
void clear_visual ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Model &from)
bool deleted () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_bounding_box () const
bool has_header () const
bool has_pose () const
bool has_scale () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool is_static () const
bool IsInitialized () const final
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Joint > & joint () const
const ::ignition::msgs::Joint & joint (int index) const
int joint_size () const
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Link > & link () const
const ::ignition::msgs::Link & link (int index) const
int link_size () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Model &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Model > & model () const
const ::ignition::msgs::Model & model (int index) const
int model_size () const
::ignition::msgs::AxisAlignedBox * mutable_bounding_box ()
::ignition::msgs::Header * mutable_header ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Joint > * mutable_joint ()
::ignition::msgs::Joint * mutable_joint (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Link > * mutable_link ()
::ignition::msgs::Link * mutable_link (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Model > * mutable_model ()
::ignition::msgs::Model * mutable_model (int index)
::std::string * mutable_name ()
::ignition::msgs::Pose * mutable_pose ()
::ignition::msgs::Vector3d * mutable_scale ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Visual > * mutable_visual ()
::ignition::msgs::Visual * mutable_visual (int index)
const ::std::string & name () const
Model * New () const final
Model * New (::google::protobuf::Arena *arena) const final
Model & operator= (const Model &from)
const ::ignition::msgs::Pose & pose () const
::ignition::msgs::AxisAlignedBox * release_bounding_box ()
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
::ignition::msgs::Pose * release_pose ()
::ignition::msgs::Vector3d * release_scale ()
const ::ignition::msgs::Vector3d & scale () const
bool self_collide () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_bounding_box (::ignition::msgs::AxisAlignedBox *bounding_box)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_pose (::ignition::msgs::Pose *pose)
void set_allocated_scale (::ignition::msgs::Vector3d *scale)
void set_deleted (bool value)
void set_id (::google::protobuf::uint32 value)
void set_is_static (bool value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_self_collide (bool value)
void Swap (Model *other)
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Visual > & visual () const
const ::ignition::msgs::Visual & visual (int index) const
int visual_size () const
Static Public Member Functions
static const Model & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Model * internal_default_instance ()
Static Public Attributes
static const int kBoundingBoxFieldNumber = 13
static const int kDeletedFieldNumber = 8
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kIsStaticFieldNumber = 4
static const int kJointFieldNumber = 6
static const int kLinkFieldNumber = 7
static const int kModelFieldNumber = 12
static const int kNameFieldNumber = 2
static const int kPoseFieldNumber = 5
static const int kScaleFieldNumber = 10
static const int kSelfCollideFieldNumber = 11
static const int kVisualFieldNumber = 9
Constructor & Destructor Documentation
Model() [1/2]
Model ()
~Model()
virtual ~Model () virtual
Model() [2/2]
Model (const Model & from)
Member Function Documentation
add_joint()
ignition::msgs::Joint * add_joint () inline
add_link()
ignition::msgs::Link * add_link () inline
add_model()
ignition::msgs::Model * add_model () inline
add_visual()
ignition::msgs::Visual * add_visual () inline
bounding_box()
const ::ignition::msgs::AxisAlignedBox & bounding_box () const inline
References ignition::msgs::_AxisAlignedBox_default_instance_.
Referenced by Model::set_allocated_bounding_box().
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_bounding_box()
void clear_bounding_box ()
clear_deleted()
void clear_deleted () inline
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_is_static()
void clear_is_static () inline
clear_joint()
void clear_joint ()
clear_link()
void clear_link ()
clear_model()
void clear_model () inline
clear_name()
void clear_name () inline
clear_pose()
void clear_pose ()
clear_scale()
void clear_scale ()
clear_self_collide()
void clear_self_collide () inline
clear_visual()
void clear_visual ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Model & from)
default_instance()
static const Model& default_instance () static
deleted()
bool deleted () const inline
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_bounding_box()
bool has_bounding_box () const inline
References Model::internal_default_instance().
has_header()
bool has_header () const inline
References Model::internal_default_instance().
has_pose()
bool has_pose () const inline
References Model::internal_default_instance().
has_scale()
bool has_scale () const inline
References Model::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Model::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Model* internal_default_instance () inline static
References ignition::msgs::_Model_default_instance_.
Referenced by Model::has_bounding_box(), Model::has_header(), Model::has_pose(), and Model::has_scale().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
is_static()
bool is_static () const inline
IsInitialized()
bool IsInitialized () const final
joint() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Joint > & joint () const inline
joint() [2/2]
const ::ignition::msgs::Joint & joint (int index) const inline
joint_size()
int joint_size () const inline
link() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Link > & link () const inline
link() [2/2]
const ::ignition::msgs::Link & link (int index) const inline
link_size()
int link_size () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Model & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
model() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Model > & model () const inline
model() [2/2]
const ::ignition::msgs::Model & model (int index) const inline
model_size()
int model_size () const inline
mutable_bounding_box()
ignition::msgs::AxisAlignedBox * mutable_bounding_box () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_joint() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Joint > * mutable_joint () inline
mutable_joint() [2/2]
ignition::msgs::Joint * mutable_joint (int index) inline
mutable_link() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Link > * mutable_link () inline
mutable_link() [2/2]
ignition::msgs::Link * mutable_link (int index) inline
mutable_model() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Model > * mutable_model () inline
mutable_model() [2/2]
ignition::msgs::Model * mutable_model (int index) inline
mutable_name()
std::string * mutable_name () inline
mutable_pose()
ignition::msgs::Pose * mutable_pose () inline
mutable_scale()
ignition::msgs::Vector3d * mutable_scale () inline
mutable_visual() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Visual > * mutable_visual () inline
mutable_visual() [2/2]
ignition::msgs::Visual * mutable_visual (int index) inline
name()
const ::std::string & name () const inline
Referenced by Model::set_allocated_name().
New() [1/2]
Model* New () const inline final
New() [2/2]
Model* New (::google::protobuf::Arena * arena) const inline final
operator=()
Model& operator= (const Model & from) inline
pose()
const ::ignition::msgs::Pose & pose () const inline
References ignition::msgs::_Pose_default_instance_.
Referenced by Model::set_allocated_pose().
release_bounding_box()
ignition::msgs::AxisAlignedBox * release_bounding_box () inline
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_pose()
ignition::msgs::Pose * release_pose () inline
release_scale()
ignition::msgs::Vector3d * release_scale () inline
scale()
const ::ignition::msgs::Vector3d & scale () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by Model::set_allocated_scale().
self_collide()
bool self_collide () const inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_bounding_box()
void set_allocated_bounding_box (::ignition::msgs::AxisAlignedBox * bounding_box) inline
References Model::bounding_box().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Model::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Model::name().
set_allocated_pose()
void set_allocated_pose (::ignition::msgs::Pose * pose) inline
References Model::pose().
set_allocated_scale()
void set_allocated_scale (::ignition::msgs::Vector3d * scale) inline
References Model::scale().
set_deleted()
void set_deleted (bool value) inline
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_is_static()
void set_is_static (bool value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_self_collide()
void set_self_collide (bool value) inline
Swap()
void Swap (Model * other)
visual() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Visual > & visual () const inline
visual() [2/2]
const ::ignition::msgs::Visual & visual (int index) const inline
visual_size()
int visual_size () const inline
Member Data Documentation
kBoundingBoxFieldNumber
const int kBoundingBoxFieldNumber = 13 static
kDeletedFieldNumber
const int kDeletedFieldNumber = 8 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kIsStaticFieldNumber
const int kIsStaticFieldNumber = 4 static
kJointFieldNumber
const int kJointFieldNumber = 6 static
kLinkFieldNumber
const int kLinkFieldNumber = 7 static
kModelFieldNumber
const int kModelFieldNumber = 12 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
kPoseFieldNumber
const int kPoseFieldNumber = 5 static
kScaleFieldNumber
const int kScaleFieldNumber = 10 static
kSelfCollideFieldNumber
const int kSelfCollideFieldNumber = 11 static
kVisualFieldNumber
const int kVisualFieldNumber = 9 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/model.pb.h