Gazebo Msgs: Discovery Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Discovery Class Reference
#include <discovery.pb.h>
Public Types
enum DiscContentsCase { kSub = 6, kPub = 7, DISC_CONTENTS_NOT_SET = 0 }
typedef Discovery_Flags Flags
typedef Discovery_Publisher Publisher
typedef Discovery_Subscriber Subscriber
typedef Discovery_Type Type
Public Member Functions
Discovery ()
Discovery (const Discovery &from)
virtual ~Discovery ()
size_t ByteSizeLong () const final
void Clear () final
void clear_disc_contents ()
void clear_flags ()
void clear_header ()
void clear_process_uuid ()
void clear_pub ()
void clear_sub ()
void clear_type ()
void clear_version ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Discovery &from)
DiscContentsCase disc_contents_case () const
const ::ignition::msgs::Discovery_Flags & flags () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_flags () const
bool has_header () const
bool has_pub () const
bool has_sub () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Discovery &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Discovery_Flags * mutable_flags ()
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_process_uuid ()
::ignition::msgs::Discovery_Publisher * mutable_pub ()
::ignition::msgs::Discovery_Subscriber * mutable_sub ()
Discovery * New () const final
Discovery * New (::google::protobuf::Arena *arena) const final
Discovery & operator= (const Discovery &from)
const ::std::string & process_uuid () const
const ::ignition::msgs::Discovery_Publisher & pub () const
::ignition::msgs::Discovery_Flags * release_flags ()
::ignition::msgs::Header * release_header ()
::std::string * release_process_uuid ()
::ignition::msgs::Discovery_Publisher * release_pub ()
::ignition::msgs::Discovery_Subscriber * release_sub ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_flags (::ignition::msgs::Discovery_Flags *flags)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_process_uuid (::std::string *process_uuid)
void set_allocated_pub (::ignition::msgs::Discovery_Publisher *pub)
void set_allocated_sub (::ignition::msgs::Discovery_Subscriber *sub)
void set_process_uuid (const ::std::string &value)
void set_process_uuid (const char *value)
void set_process_uuid (const char *value, size_t size)
void set_type (::ignition::msgs::Discovery_Type value)
void set_version (::google::protobuf::uint32 value)
const ::ignition::msgs::Discovery_Subscriber & sub () const
void Swap (Discovery *other)
::ignition::msgs::Discovery_Type type () const
::google::protobuf::uint32 version () const
Static Public Member Functions
static const Discovery & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Discovery * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type ADVERTISE
static const Type BYE
static const Type END_CONNECTION
static const Type HEARTBEAT
static const int kFlagsFieldNumber = 5
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kProcessUuidFieldNumber = 3
static const int kPubFieldNumber = 7
static const int kSubFieldNumber = 6
static const int kTypeFieldNumber = 4
static const int kVersionFieldNumber = 2
static const Type NEW_CONNECTION
static const Type SUBSCRIBE
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
static const Type UNADVERTISE
static const Type UNINITIALIZED
Member Typedef Documentation
Flags
typedef Discovery_Flags Flags
Publisher
typedef Discovery_Publisher Publisher
Subscriber
typedef Discovery_Subscriber Subscriber
Type
typedef Discovery_Type Type
Member Enumeration Documentation
DiscContentsCase
enum DiscContentsCase
Enumerator
kSub
kPub
DISC_CONTENTS_NOT_SET
Constructor & Destructor Documentation
Discovery() [1/2]
Discovery ()
~Discovery()
virtual ~Discovery () virtual
Discovery() [2/2]
Discovery (const Discovery & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_disc_contents()
void clear_disc_contents ()
clear_flags()
void clear_flags () inline
clear_header()
void clear_header ()
clear_process_uuid()
void clear_process_uuid () inline
clear_pub()
void clear_pub () inline
clear_sub()
void clear_sub () inline
clear_type()
void clear_type () inline
clear_version()
void clear_version () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Discovery & from)
default_instance()
static const Discovery& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
disc_contents_case()
Discovery::DiscContentsCase disc_contents_case () const inline
flags()
const ::ignition::msgs::Discovery_Flags & flags () const inline
References ignition::msgs::_Discovery_Flags_default_instance_.
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_flags()
bool has_flags () const inline
has_header()
bool has_header () const inline
has_pub()
bool has_pub () const inline
has_sub()
bool has_sub () const inline
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Discovery* internal_default_instance () inline static
References ignition::msgs::_Discovery_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Discovery & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_flags()
ignition::msgs::Discovery_Flags * mutable_flags () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_process_uuid()
std::string * mutable_process_uuid () inline
mutable_pub()
ignition::msgs::Discovery_Publisher * mutable_pub () inline
mutable_sub()
ignition::msgs::Discovery_Subscriber * mutable_sub () inline
New() [1/2]
Discovery* New () const inline final
New() [2/2]
Discovery* New (::google::protobuf::Arena * arena) const inline final
operator=()
Discovery& operator= (const Discovery & from) inline
process_uuid()
const ::std::string & process_uuid () const inline
pub()
const ::ignition::msgs::Discovery_Publisher & pub () const inline
References ignition::msgs::_Discovery_Publisher_default_instance_.
release_flags()
ignition::msgs::Discovery_Flags * release_flags () inline
release_header()
ignition::msgs::Header * release_header () inline
release_process_uuid()
std::string * release_process_uuid () inline
release_pub()
ignition::msgs::Discovery_Publisher * release_pub () inline
release_sub()
ignition::msgs::Discovery_Subscriber * release_sub () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_flags()
void set_allocated_flags (::ignition::msgs::Discovery_Flags * flags) inline
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
set_allocated_process_uuid()
void set_allocated_process_uuid (::std::string * process_uuid) inline
set_allocated_pub()
void set_allocated_pub (::ignition::msgs::Discovery_Publisher * pub)
set_allocated_sub()
void set_allocated_sub (::ignition::msgs::Discovery_Subscriber * sub)
set_process_uuid() [1/3]
void set_process_uuid (const ::std::string & value) inline
set_process_uuid() [2/3]
void set_process_uuid (const char * value) inline
set_process_uuid() [3/3]
void set_process_uuid (const char * value, size_t size) inline
set_type()
void set_type (::ignition::msgs::Discovery_Type value) inline
set_version()
void set_version (::google::protobuf::uint32 value) inline
sub()
const ::ignition::msgs::Discovery_Subscriber & sub () const inline
References ignition::msgs::_Discovery_Subscriber_default_instance_.
Swap()
void Swap (Discovery * other)
type()
ignition::msgs::Discovery_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References ignition::msgs::Discovery_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References ignition::msgs::Discovery_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References ignition::msgs::Discovery_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References ignition::msgs::Discovery_Type_Parse().
version()
google::protobuf::uint32 version () const inline
Member Data Documentation
ADVERTISE
const Type ADVERTISE static
Initial value:
=
    Discovery_Type_ADVERTISE
BYE
const Type BYE static
Initial value:
=
    Discovery_Type_BYE
END_CONNECTION
const Type END_CONNECTION static
Initial value:
=
    Discovery_Type_END_CONNECTION
HEARTBEAT
const Type HEARTBEAT static
Initial value:
=
    Discovery_Type_HEARTBEAT
kFlagsFieldNumber
const int kFlagsFieldNumber = 5 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    5
kProcessUuidFieldNumber
const int kProcessUuidFieldNumber = 3 static
kPubFieldNumber
const int kPubFieldNumber = 7 static
kSubFieldNumber
const int kSubFieldNumber = 6 static
kTypeFieldNumber
const int kTypeFieldNumber = 4 static
kVersionFieldNumber
const int kVersionFieldNumber = 2 static
NEW_CONNECTION
const Type NEW_CONNECTION static
Initial value:
=
    Discovery_Type_NEW_CONNECTION
SUBSCRIBE
const Type SUBSCRIBE static
Initial value:
=
    Discovery_Type_SUBSCRIBE
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    Discovery_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    Discovery_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    Discovery_Type_Type_MIN
UNADVERTISE
const Type UNADVERTISE static
Initial value:
=
    Discovery_Type_UNADVERTISE
UNINITIALIZED
const Type UNINITIALIZED static
Initial value:
=
    Discovery_Type_UNINITIALIZED
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/discovery.pb.h