Gazebo Msgs: RestLogin Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
RestLogin Class Reference
#include <rest_login.pb.h>
Public Member Functions
RestLogin ()
RestLogin (const RestLogin &from)
virtual ~RestLogin ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_id ()
void clear_password ()
void clear_url ()
void clear_username ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const RestLogin &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const RestLogin &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_password ()
::std::string * mutable_url ()
::std::string * mutable_username ()
RestLogin * New () const final
RestLogin * New (::google::protobuf::Arena *arena) const final
RestLogin & operator= (const RestLogin &from)
const ::std::string & password () const
::ignition::msgs::Header * release_header ()
::std::string * release_password ()
::std::string * release_url ()
::std::string * release_username ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_password (::std::string *password)
void set_allocated_url (::std::string *url)
void set_allocated_username (::std::string *username)
void set_id (::google::protobuf::uint32 value)
void set_password (const ::std::string &value)
void set_password (const char *value)
void set_password (const char *value, size_t size)
void set_url (const ::std::string &value)
void set_url (const char *value)
void set_url (const char *value, size_t size)
void set_username (const ::std::string &value)
void set_username (const char *value)
void set_username (const char *value, size_t size)
void Swap (RestLogin *other)
const ::std::string & url () const
const ::std::string & username () const
Static Public Member Functions
static const RestLogin & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const RestLogin * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kPasswordFieldNumber = 5
static const int kUrlFieldNumber = 3
static const int kUsernameFieldNumber = 4
Constructor & Destructor Documentation
RestLogin() [1/2]
RestLogin ()
~RestLogin()
virtual ~RestLogin () virtual
RestLogin() [2/2]
RestLogin (const RestLogin & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_password()
void clear_password () inline
clear_url()
void clear_url () inline
clear_username()
void clear_username () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const RestLogin & from)
default_instance()
static const RestLogin& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References RestLogin::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by RestLogin::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const RestLogin* internal_default_instance () inline static
References ignition::msgs::_RestLogin_default_instance_.
Referenced by RestLogin::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const RestLogin & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_password()
std::string * mutable_password () inline
mutable_url()
std::string * mutable_url () inline
mutable_username()
std::string * mutable_username () inline
New() [1/2]
RestLogin* New () const inline final
New() [2/2]
RestLogin* New (::google::protobuf::Arena * arena) const inline final
operator=()
RestLogin& operator= (const RestLogin & from) inline
password()
const ::std::string & password () const inline
Referenced by RestLogin::set_allocated_password().
release_header()
ignition::msgs::Header * release_header () inline
release_password()
std::string * release_password () inline
release_url()
std::string * release_url () inline
release_username()
std::string * release_username () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References RestLogin::header().
set_allocated_password()
void set_allocated_password (::std::string * password) inline
References RestLogin::password().
set_allocated_url()
void set_allocated_url (::std::string * url) inline
References RestLogin::url().
set_allocated_username()
void set_allocated_username (::std::string * username) inline
References RestLogin::username().
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_password() [1/3]
void set_password (const ::std::string & value) inline
set_password() [2/3]
void set_password (const char * value) inline
set_password() [3/3]
void set_password (const char * value, size_t size) inline
set_url() [1/3]
void set_url (const ::std::string & value) inline
set_url() [2/3]
void set_url (const char * value) inline
set_url() [3/3]
void set_url (const char * value, size_t size) inline
set_username() [1/3]
void set_username (const ::std::string & value) inline
set_username() [2/3]
void set_username (const char * value) inline
set_username() [3/3]
void set_username (const char * value, size_t size) inline
Swap()
void Swap (RestLogin * other)
url()
const ::std::string & url () const inline
Referenced by RestLogin::set_allocated_url().
username()
const ::std::string & username () const inline
Referenced by RestLogin::set_allocated_username().
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kPasswordFieldNumber
const int kPasswordFieldNumber = 5 static
kUrlFieldNumber
const int kUrlFieldNumber = 3 static
kUsernameFieldNumber
const int kUsernameFieldNumber = 4 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/rest_login.pb.h