Gazebo Msgs: Axis Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Axis Class Reference
#include <axis.pb.h>
Public Member Functions
Axis ()
Axis (const Axis &from)
virtual ~Axis ()
double acceleration () const
size_t ByteSizeLong () const final
void Clear () final
void clear_acceleration ()
void clear_damping ()
void clear_force ()
void clear_friction ()
void clear_header ()
void clear_limit_effort ()
void clear_limit_lower ()
void clear_limit_upper ()
void clear_limit_velocity ()
void clear_position ()
GOOGLE_PROTOBUF_DEPRECATED_ATTR void clear_use_parent_model_frame ()
void clear_velocity ()
void clear_xyz ()
void clear_xyz_expressed_in ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Axis &from)
double damping () const
double force () const
double friction () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_xyz () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
double limit_effort () const
double limit_lower () const
double limit_upper () const
double limit_velocity () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Axis &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::Vector3d * mutable_xyz ()
::std::string * mutable_xyz_expressed_in ()
Axis * New () const final
Axis * New (::google::protobuf::Arena *arena) const final
Axis & operator= (const Axis &from)
double position () const
::ignition::msgs::Header * release_header ()
::ignition::msgs::Vector3d * release_xyz ()
::std::string * release_xyz_expressed_in ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_acceleration (double value)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_xyz (::ignition::msgs::Vector3d *xyz)
void set_allocated_xyz_expressed_in (::std::string *xyz_expressed_in)
void set_damping (double value)
void set_force (double value)
void set_friction (double value)
void set_limit_effort (double value)
void set_limit_lower (double value)
void set_limit_upper (double value)
void set_limit_velocity (double value)
void set_position (double value)
GOOGLE_PROTOBUF_DEPRECATED_ATTR void set_use_parent_model_frame (bool value)
void set_velocity (double value)
void set_xyz_expressed_in (const ::std::string &value)
void set_xyz_expressed_in (const char *value)
void set_xyz_expressed_in (const char *value, size_t size)
void Swap (Axis *other)
GOOGLE_PROTOBUF_DEPRECATED_ATTR bool use_parent_model_frame () const
double velocity () const
const ::ignition::msgs::Vector3d & xyz () const
const ::std::string & xyz_expressed_in () const
Static Public Member Functions
static const Axis & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Axis * internal_default_instance ()
Static Public Attributes
static const int kAccelerationFieldNumber = 13
static const int kDampingFieldNumber = 7
static const int kForceFieldNumber = 12
static const int kFrictionFieldNumber = 8
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kLimitEffortFieldNumber = 5
static const int kLimitLowerFieldNumber = 3
static const int kLimitUpperFieldNumber = 4
static const int kLimitVelocityFieldNumber = 6
static const int kPositionFieldNumber = 10
static const GOOGLE_PROTOBUF_DEPRECATED_ATTR int kUseParentModelFrameFieldNumber = 9
static const int kVelocityFieldNumber = 11
static const int kXyzExpressedInFieldNumber = 14
static const int kXyzFieldNumber = 2
Constructor & Destructor Documentation
Axis() [1/2]
Axis ()
~Axis()
virtual ~Axis () virtual
Axis() [2/2]
Axis (const Axis & from)
Member Function Documentation
acceleration()
double acceleration () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_acceleration()
void clear_acceleration () inline
clear_damping()
void clear_damping () inline
clear_force()
void clear_force () inline
clear_friction()
void clear_friction () inline
clear_header()
void clear_header ()
clear_limit_effort()
void clear_limit_effort () inline
clear_limit_lower()
void clear_limit_lower () inline
clear_limit_upper()
void clear_limit_upper () inline
clear_limit_velocity()
void clear_limit_velocity () inline
clear_position()
void clear_position () inline
clear_use_parent_model_frame()
void clear_use_parent_model_frame () inline
clear_velocity()
void clear_velocity () inline
clear_xyz()
void clear_xyz ()
clear_xyz_expressed_in()
void clear_xyz_expressed_in () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Axis & from)
damping()
double damping () const inline
default_instance()
static const Axis& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
force()
double force () const inline
friction()
double friction () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Axis::internal_default_instance().
has_xyz()
bool has_xyz () const inline
References Axis::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Axis::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Axis* internal_default_instance () inline static
References ignition::msgs::_Axis_default_instance_.
Referenced by Axis::has_header(), and Axis::has_xyz().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
limit_effort()
double limit_effort () const inline
limit_lower()
double limit_lower () const inline
limit_upper()
double limit_upper () const inline
limit_velocity()
double limit_velocity () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Axis & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_xyz()
ignition::msgs::Vector3d * mutable_xyz () inline
mutable_xyz_expressed_in()
std::string * mutable_xyz_expressed_in () inline
New() [1/2]
Axis* New () const inline final
New() [2/2]
Axis* New (::google::protobuf::Arena * arena) const inline final
operator=()
Axis& operator= (const Axis & from) inline
position()
double position () const inline
release_header()
ignition::msgs::Header * release_header () inline
release_xyz()
ignition::msgs::Vector3d * release_xyz () inline
release_xyz_expressed_in()
std::string * release_xyz_expressed_in () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_acceleration()
void set_acceleration (double value) inline
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Axis::header().
set_allocated_xyz()
void set_allocated_xyz (::ignition::msgs::Vector3d * xyz) inline
References Axis::xyz().
set_allocated_xyz_expressed_in()
void set_allocated_xyz_expressed_in (::std::string * xyz_expressed_in) inline
References Axis::xyz_expressed_in().
set_damping()
void set_damping (double value) inline
set_force()
void set_force (double value) inline
set_friction()
void set_friction (double value) inline
set_limit_effort()
void set_limit_effort (double value) inline
set_limit_lower()
void set_limit_lower (double value) inline
set_limit_upper()
void set_limit_upper (double value) inline
set_limit_velocity()
void set_limit_velocity (double value) inline
set_position()
void set_position (double value) inline
set_use_parent_model_frame()
void set_use_parent_model_frame (bool value) inline
set_velocity()
void set_velocity (double value) inline
set_xyz_expressed_in() [1/3]
void set_xyz_expressed_in (const ::std::string & value) inline
set_xyz_expressed_in() [2/3]
void set_xyz_expressed_in (const char * value) inline
set_xyz_expressed_in() [3/3]
void set_xyz_expressed_in (const char * value, size_t size) inline
Swap()
void Swap (Axis * other)
use_parent_model_frame()
bool use_parent_model_frame () const inline
velocity()
double velocity () const inline
xyz()
const ::ignition::msgs::Vector3d & xyz () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by Axis::set_allocated_xyz().
xyz_expressed_in()
const ::std::string & xyz_expressed_in () const inline
Referenced by Axis::set_allocated_xyz_expressed_in().
Member Data Documentation
kAccelerationFieldNumber
const int kAccelerationFieldNumber = 13 static
kDampingFieldNumber
const int kDampingFieldNumber = 7 static
kForceFieldNumber
const int kForceFieldNumber = 12 static
kFrictionFieldNumber
const int kFrictionFieldNumber = 8 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLimitEffortFieldNumber
const int kLimitEffortFieldNumber = 5 static
kLimitLowerFieldNumber
const int kLimitLowerFieldNumber = 3 static
kLimitUpperFieldNumber
const int kLimitUpperFieldNumber = 4 static
kLimitVelocityFieldNumber
const int kLimitVelocityFieldNumber = 6 static
kPositionFieldNumber
const int kPositionFieldNumber = 10 static
kUseParentModelFrameFieldNumber
const GOOGLE_PROTOBUF_DEPRECATED_ATTR int kUseParentModelFrameFieldNumber = 9 static
kVelocityFieldNumber
const int kVelocityFieldNumber = 11 static
kXyzExpressedInFieldNumber
const int kXyzExpressedInFieldNumber = 14 static
kXyzFieldNumber
const int kXyzFieldNumber = 2 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/axis.pb.h