Gazebo Msgs: Link Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Link Class Reference
#include <link.pb.h>
Public Member Functions
Link ()
Link (const Link &from)
virtual ~Link ()
::ignition::msgs::Battery * add_battery ()
::ignition::msgs::Collision * add_collision ()
::ignition::msgs::Light * add_light ()
::ignition::msgs::Projector * add_projector ()
::ignition::msgs::Sensor * add_sensor ()
::ignition::msgs::Visual * add_visual ()
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Battery > & battery () const
const ::ignition::msgs::Battery & battery (int index) const
int battery_size () const
size_t ByteSizeLong () const final
bool canonical () const
void Clear () final
void clear_battery ()
void clear_canonical ()
void clear_collision ()
void clear_density ()
void clear_enabled ()
void clear_gravity ()
void clear_header ()
void clear_id ()
void clear_inertial ()
void clear_kinematic ()
void clear_light ()
void clear_name ()
void clear_pose ()
void clear_projector ()
void clear_self_collide ()
void clear_sensor ()
void clear_visual ()
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Collision > & collision () const
const ::ignition::msgs::Collision & collision (int index) const
int collision_size () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Link &from)
const ::ignition::msgs::Density & density () const
bool enabled () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool gravity () const
bool has_density () const
bool has_header () const
bool has_inertial () const
bool has_pose () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
const ::ignition::msgs::Inertial & inertial () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
bool kinematic () const
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Light > & light () const
const ::ignition::msgs::Light & light (int index) const
int light_size () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Link &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Battery > * mutable_battery ()
::ignition::msgs::Battery * mutable_battery (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Collision > * mutable_collision ()
::ignition::msgs::Collision * mutable_collision (int index)
::ignition::msgs::Density * mutable_density ()
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::Inertial * mutable_inertial ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Light > * mutable_light ()
::ignition::msgs::Light * mutable_light (int index)
::std::string * mutable_name ()
::ignition::msgs::Pose * mutable_pose ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Projector > * mutable_projector ()
::ignition::msgs::Projector * mutable_projector (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Sensor > * mutable_sensor ()
::ignition::msgs::Sensor * mutable_sensor (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Visual > * mutable_visual ()
::ignition::msgs::Visual * mutable_visual (int index)
const ::std::string & name () const
Link * New () const final
Link * New (::google::protobuf::Arena *arena) const final
Link & operator= (const Link &from)
const ::ignition::msgs::Pose & pose () const
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Projector > & projector () const
const ::ignition::msgs::Projector & projector (int index) const
int projector_size () const
::ignition::msgs::Density * release_density ()
::ignition::msgs::Header * release_header ()
::ignition::msgs::Inertial * release_inertial ()
::std::string * release_name ()
::ignition::msgs::Pose * release_pose ()
bool self_collide () const
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Sensor > & sensor () const
const ::ignition::msgs::Sensor & sensor (int index) const
int sensor_size () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_density (::ignition::msgs::Density *density)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_inertial (::ignition::msgs::Inertial *inertial)
void set_allocated_name (::std::string *name)
void set_allocated_pose (::ignition::msgs::Pose *pose)
void set_canonical (bool value)
void set_enabled (bool value)
void set_gravity (bool value)
void set_id (::google::protobuf::uint32 value)
void set_kinematic (bool value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_self_collide (bool value)
void Swap (Link *other)
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Visual > & visual () const
const ::ignition::msgs::Visual & visual (int index) const
int visual_size () const
Static Public Member Functions
static const Link & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Link * internal_default_instance ()
Static Public Attributes
static const int kBatteryFieldNumber = 16
static const int kCanonicalFieldNumber = 15
static const int kCollisionFieldNumber = 12
static const int kDensityFieldNumber = 8
static const int kEnabledFieldNumber = 7
static const int kGravityFieldNumber = 5
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kInertialFieldNumber = 9
static const int kKinematicFieldNumber = 6
static const int kLightFieldNumber = 17
static const int kNameFieldNumber = 3
static const int kPoseFieldNumber = 10
static const int kProjectorFieldNumber = 14
static const int kSelfCollideFieldNumber = 4
static const int kSensorFieldNumber = 13
static const int kVisualFieldNumber = 11
Constructor & Destructor Documentation
Link() [1/2]
Link ()
~Link()
virtual ~Link () virtual
Link() [2/2]
Link (const Link & from)
Member Function Documentation
add_battery()
ignition::msgs::Battery * add_battery () inline
add_collision()
ignition::msgs::Collision * add_collision () inline
add_light()
ignition::msgs::Light * add_light () inline
add_projector()
ignition::msgs::Projector * add_projector () inline
add_sensor()
ignition::msgs::Sensor * add_sensor () inline
add_visual()
ignition::msgs::Visual * add_visual () inline
battery() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Battery > & battery () const inline
battery() [2/2]
const ::ignition::msgs::Battery & battery (int index) const inline
battery_size()
int battery_size () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
canonical()
bool canonical () const inline
Clear()
void Clear () final
clear_battery()
void clear_battery ()
clear_canonical()
void clear_canonical () inline
clear_collision()
void clear_collision ()
clear_density()
void clear_density ()
clear_enabled()
void clear_enabled () inline
clear_gravity()
void clear_gravity () inline
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_inertial()
void clear_inertial ()
clear_kinematic()
void clear_kinematic () inline
clear_light()
void clear_light ()
clear_name()
void clear_name () inline
clear_pose()
void clear_pose ()
clear_projector()
void clear_projector ()
clear_self_collide()
void clear_self_collide () inline
clear_sensor()
void clear_sensor ()
clear_visual()
void clear_visual ()
collision() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Collision > & collision () const inline
collision() [2/2]
const ::ignition::msgs::Collision & collision (int index) const inline
collision_size()
int collision_size () const inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Link & from)
default_instance()
static const Link& default_instance () static
density()
const ::ignition::msgs::Density & density () const inline
References ignition::msgs::_Density_default_instance_.
Referenced by Link::set_allocated_density().
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
enabled()
bool enabled () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
gravity()
bool gravity () const inline
has_density()
bool has_density () const inline
References Link::internal_default_instance().
has_header()
bool has_header () const inline
References Link::internal_default_instance().
has_inertial()
bool has_inertial () const inline
References Link::internal_default_instance().
has_pose()
bool has_pose () const inline
References Link::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Link::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
inertial()
const ::ignition::msgs::Inertial & inertial () const inline
References ignition::msgs::_Inertial_default_instance_.
Referenced by Link::set_allocated_inertial().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Link* internal_default_instance () inline static
References ignition::msgs::_Link_default_instance_.
Referenced by Link::has_density(), Link::has_header(), Link::has_inertial(), and Link::has_pose().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
kinematic()
bool kinematic () const inline
light() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Light > & light () const inline
light() [2/2]
const ::ignition::msgs::Light & light (int index) const inline
light_size()
int light_size () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Link & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_battery() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Battery > * mutable_battery () inline
mutable_battery() [2/2]
ignition::msgs::Battery * mutable_battery (int index) inline
mutable_collision() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Collision > * mutable_collision () inline
mutable_collision() [2/2]
ignition::msgs::Collision * mutable_collision (int index) inline
mutable_density()
ignition::msgs::Density * mutable_density () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_inertial()
ignition::msgs::Inertial * mutable_inertial () inline
mutable_light() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Light > * mutable_light () inline
mutable_light() [2/2]
ignition::msgs::Light * mutable_light (int index) inline
mutable_name()
std::string * mutable_name () inline
mutable_pose()
ignition::msgs::Pose * mutable_pose () inline
mutable_projector() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Projector > * mutable_projector () inline
mutable_projector() [2/2]
ignition::msgs::Projector * mutable_projector (int index) inline
mutable_sensor() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Sensor > * mutable_sensor () inline
mutable_sensor() [2/2]
ignition::msgs::Sensor * mutable_sensor (int index) inline
mutable_visual() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Visual > * mutable_visual () inline
mutable_visual() [2/2]
ignition::msgs::Visual * mutable_visual (int index) inline
name()
const ::std::string & name () const inline
Referenced by Link::set_allocated_name().
New() [1/2]
Link* New () const inline final
New() [2/2]
Link* New (::google::protobuf::Arena * arena) const inline final
operator=()
Link& operator= (const Link & from) inline
pose()
const ::ignition::msgs::Pose & pose () const inline
References ignition::msgs::_Pose_default_instance_.
Referenced by Link::set_allocated_pose().
projector() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Projector > & projector () const inline
projector() [2/2]
const ::ignition::msgs::Projector & projector (int index) const inline
projector_size()
int projector_size () const inline
release_density()
ignition::msgs::Density * release_density () inline
release_header()
ignition::msgs::Header * release_header () inline
release_inertial()
ignition::msgs::Inertial * release_inertial () inline
release_name()
std::string * release_name () inline
release_pose()
ignition::msgs::Pose * release_pose () inline
self_collide()
bool self_collide () const inline
sensor() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Sensor > & sensor () const inline
sensor() [2/2]
const ::ignition::msgs::Sensor & sensor (int index) const inline
sensor_size()
int sensor_size () const inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_density()
void set_allocated_density (::ignition::msgs::Density * density) inline
References Link::density().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Link::header().
set_allocated_inertial()
void set_allocated_inertial (::ignition::msgs::Inertial * inertial) inline
References Link::inertial().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Link::name().
set_allocated_pose()
void set_allocated_pose (::ignition::msgs::Pose * pose) inline
References Link::pose().
set_canonical()
void set_canonical (bool value) inline
set_enabled()
void set_enabled (bool value) inline
set_gravity()
void set_gravity (bool value) inline
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_kinematic()
void set_kinematic (bool value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_self_collide()
void set_self_collide (bool value) inline
Swap()
void Swap (Link * other)
visual() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Visual > & visual () const inline
visual() [2/2]
const ::ignition::msgs::Visual & visual (int index) const inline
visual_size()
int visual_size () const inline
Member Data Documentation
kBatteryFieldNumber
const int kBatteryFieldNumber = 16 static
kCanonicalFieldNumber
const int kCanonicalFieldNumber = 15 static
kCollisionFieldNumber
const int kCollisionFieldNumber = 12 static
kDensityFieldNumber
const int kDensityFieldNumber = 8 static
kEnabledFieldNumber
const int kEnabledFieldNumber = 7 static
kGravityFieldNumber
const int kGravityFieldNumber = 5 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kInertialFieldNumber
const int kInertialFieldNumber = 9 static
kKinematicFieldNumber
const int kKinematicFieldNumber = 6 static
kLightFieldNumber
const int kLightFieldNumber = 17 static
kNameFieldNumber
const int kNameFieldNumber = 3 static
kPoseFieldNumber
const int kPoseFieldNumber = 10 static
kProjectorFieldNumber
const int kProjectorFieldNumber = 14 static
kSelfCollideFieldNumber
const int kSelfCollideFieldNumber = 4 static
kSensorFieldNumber
const int kSensorFieldNumber = 13 static
kVisualFieldNumber
const int kVisualFieldNumber = 11 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/link.pb.h