Gazebo Msgs: WorldModify Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
WorldModify Class Reference
#include <world_modify.pb.h>
Public Member Functions
WorldModify ()
WorldModify (const WorldModify &from)
virtual ~WorldModify ()
size_t ByteSizeLong () const final
void Clear () final
void clear_cloned ()
void clear_cloned_uri ()
void clear_create ()
void clear_header ()
void clear_remove ()
void clear_world_name ()
bool cloned () const
const ::std::string & cloned_uri () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const WorldModify &from)
bool create () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const WorldModify &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_cloned_uri ()
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_world_name ()
WorldModify * New () const final
WorldModify * New (::google::protobuf::Arena *arena) const final
WorldModify & operator= (const WorldModify &from)
::std::string * release_cloned_uri ()
::ignition::msgs::Header * release_header ()
::std::string * release_world_name ()
bool remove () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_cloned_uri (::std::string *cloned_uri)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_world_name (::std::string *world_name)
void set_cloned (bool value)
void set_cloned_uri (const ::std::string &value)
void set_cloned_uri (const char *value)
void set_cloned_uri (const char *value, size_t size)
void set_create (bool value)
void set_remove (bool value)
void set_world_name (const ::std::string &value)
void set_world_name (const char *value)
void set_world_name (const char *value, size_t size)
void Swap (WorldModify *other)
const ::std::string & world_name () const
Static Public Member Functions
static const WorldModify & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const WorldModify * internal_default_instance ()
Static Public Attributes
static const int kClonedFieldNumber = 5
static const int kClonedUriFieldNumber = 6
static const int kCreateFieldNumber = 4
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kRemoveFieldNumber = 3
static const int kWorldNameFieldNumber = 2
Constructor & Destructor Documentation
WorldModify() [1/2]
WorldModify ()
~WorldModify()
virtual ~WorldModify () virtual
WorldModify() [2/2]
WorldModify (const WorldModify & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_cloned()
void clear_cloned () inline
clear_cloned_uri()
void clear_cloned_uri () inline
clear_create()
void clear_create () inline
clear_header()
void clear_header ()
clear_remove()
void clear_remove () inline
clear_world_name()
void clear_world_name () inline
cloned()
bool cloned () const inline
cloned_uri()
const ::std::string & cloned_uri () const inline
Referenced by WorldModify::set_allocated_cloned_uri().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const WorldModify & from)
create()
bool create () const inline
default_instance()
static const WorldModify& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References WorldModify::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by WorldModify::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const WorldModify* internal_default_instance () inline static
References ignition::msgs::_WorldModify_default_instance_.
Referenced by WorldModify::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const WorldModify & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_cloned_uri()
std::string * mutable_cloned_uri () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_world_name()
std::string * mutable_world_name () inline
New() [1/2]
WorldModify* New () const inline final
New() [2/2]
WorldModify* New (::google::protobuf::Arena * arena) const inline final
operator=()
WorldModify& operator= (const WorldModify & from) inline
release_cloned_uri()
std::string * release_cloned_uri () inline
release_header()
ignition::msgs::Header * release_header () inline
release_world_name()
std::string * release_world_name () inline
remove()
bool remove () const inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_cloned_uri()
void set_allocated_cloned_uri (::std::string * cloned_uri) inline
References WorldModify::cloned_uri().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References WorldModify::header().
set_allocated_world_name()
void set_allocated_world_name (::std::string * world_name) inline
References WorldModify::world_name().
set_cloned()
void set_cloned (bool value) inline
set_cloned_uri() [1/3]
void set_cloned_uri (const ::std::string & value) inline
set_cloned_uri() [2/3]
void set_cloned_uri (const char * value) inline
set_cloned_uri() [3/3]
void set_cloned_uri (const char * value, size_t size) inline
set_create()
void set_create (bool value) inline
set_remove()
void set_remove (bool value) inline
set_world_name() [1/3]
void set_world_name (const ::std::string & value) inline
set_world_name() [2/3]
void set_world_name (const char * value) inline
set_world_name() [3/3]
void set_world_name (const char * value, size_t size) inline
Swap()
void Swap (WorldModify * other)
world_name()
const ::std::string & world_name () const inline
Referenced by WorldModify::set_allocated_world_name().
Member Data Documentation
kClonedFieldNumber
const int kClonedFieldNumber = 5 static
kClonedUriFieldNumber
const int kClonedUriFieldNumber = 6 static
kCreateFieldNumber
const int kCreateFieldNumber = 4 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kRemoveFieldNumber
const int kRemoveFieldNumber = 3 static
kWorldNameFieldNumber
const int kWorldNameFieldNumber = 2 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/world_modify.pb.h