Gazebo Msgs: LogControl Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
LogControl Class Reference
#include <log_control.pb.h>
Public Member Functions
LogControl ()
LogControl (const LogControl &from)
virtual ~LogControl ()
const ::std::string & base_path () const
size_t ByteSizeLong () const final
void Clear () final
void clear_base_path ()
void clear_encoding ()
void clear_header ()
void clear_paused ()
void clear_record_resources ()
void clear_start ()
void clear_stop ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const LogControl &from)
const ::std::string & encoding () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const LogControl &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_base_path ()
::std::string * mutable_encoding ()
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_record_resources ()
LogControl * New () const final
LogControl * New (::google::protobuf::Arena *arena) const final
LogControl & operator= (const LogControl &from)
bool paused () const
const ::std::string & record_resources () const
::std::string * release_base_path ()
::std::string * release_encoding ()
::ignition::msgs::Header * release_header ()
::std::string * release_record_resources ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_base_path (::std::string *base_path)
void set_allocated_encoding (::std::string *encoding)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_record_resources (::std::string *record_resources)
void set_base_path (const ::std::string &value)
void set_base_path (const char *value)
void set_base_path (const char *value, size_t size)
void set_encoding (const ::std::string &value)
void set_encoding (const char *value)
void set_encoding (const char *value, size_t size)
void set_paused (bool value)
void set_record_resources (const ::std::string &value)
void set_record_resources (const char *value)
void set_record_resources (const char *value, size_t size)
void set_start (bool value)
void set_stop (bool value)
bool start () const
bool stop () const
void Swap (LogControl *other)
Static Public Member Functions
static const LogControl & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const LogControl * internal_default_instance ()
Static Public Attributes
static const int kBasePathFieldNumber = 5
static const int kEncodingFieldNumber = 6
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kPausedFieldNumber = 4
static const int kRecordResourcesFieldNumber = 7
static const int kStartFieldNumber = 2
static const int kStopFieldNumber = 3
Constructor & Destructor Documentation
LogControl() [1/2]
LogControl ()
~LogControl()
virtual ~LogControl () virtual
LogControl() [2/2]
LogControl (const LogControl & from)
Member Function Documentation
base_path()
const ::std::string & base_path () const inline
Referenced by LogControl::set_allocated_base_path().
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_base_path()
void clear_base_path () inline
clear_encoding()
void clear_encoding () inline
clear_header()
void clear_header ()
clear_paused()
void clear_paused () inline
clear_record_resources()
void clear_record_resources () inline
clear_start()
void clear_start () inline
clear_stop()
void clear_stop () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const LogControl & from)
default_instance()
static const LogControl& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
encoding()
const ::std::string & encoding () const inline
Referenced by LogControl::set_allocated_encoding().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References LogControl::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by LogControl::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const LogControl* internal_default_instance () inline static
References ignition::msgs::_LogControl_default_instance_.
Referenced by LogControl::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const LogControl & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_base_path()
std::string * mutable_base_path () inline
mutable_encoding()
std::string * mutable_encoding () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_record_resources()
std::string * mutable_record_resources () inline
New() [1/2]
LogControl* New () const inline final
New() [2/2]
LogControl* New (::google::protobuf::Arena * arena) const inline final
operator=()
LogControl& operator= (const LogControl & from) inline
paused()
bool paused () const inline
record_resources()
const ::std::string & record_resources () const inline
Referenced by LogControl::set_allocated_record_resources().
release_base_path()
std::string * release_base_path () inline
release_encoding()
std::string * release_encoding () inline
release_header()
ignition::msgs::Header * release_header () inline
release_record_resources()
std::string * release_record_resources () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_base_path()
void set_allocated_base_path (::std::string * base_path) inline
References LogControl::base_path().
set_allocated_encoding()
void set_allocated_encoding (::std::string * encoding) inline
References LogControl::encoding().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References LogControl::header().
set_allocated_record_resources()
void set_allocated_record_resources (::std::string * record_resources) inline
References LogControl::record_resources().
set_base_path() [1/3]
void set_base_path (const ::std::string & value) inline
set_base_path() [2/3]
void set_base_path (const char * value) inline
set_base_path() [3/3]
void set_base_path (const char * value, size_t size) inline
set_encoding() [1/3]
void set_encoding (const ::std::string & value) inline
set_encoding() [2/3]
void set_encoding (const char * value) inline
set_encoding() [3/3]
void set_encoding (const char * value, size_t size) inline
set_paused()
void set_paused (bool value) inline
set_record_resources() [1/3]
void set_record_resources (const ::std::string & value) inline
set_record_resources() [2/3]
void set_record_resources (const char * value) inline
set_record_resources() [3/3]
void set_record_resources (const char * value, size_t size) inline
set_start()
void set_start (bool value) inline
set_stop()
void set_stop (bool value) inline
start()
bool start () const inline
stop()
bool stop () const inline
Swap()
void Swap (LogControl * other)
Member Data Documentation
kBasePathFieldNumber
const int kBasePathFieldNumber = 5 static
kEncodingFieldNumber
const int kEncodingFieldNumber = 6 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kPausedFieldNumber
const int kPausedFieldNumber = 4 static
kRecordResourcesFieldNumber
const int kRecordResourcesFieldNumber = 7 static
kStartFieldNumber
const int kStartFieldNumber = 2 static
kStopFieldNumber
const int kStopFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/log_control.pb.h