Gazebo Msgs: FuelMetadata_Legal Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
FuelMetadata_Legal Class Reference
#include <fuel_metadata.pb.h>
Public Member Functions
FuelMetadata_Legal ()
FuelMetadata_Legal (const FuelMetadata_Legal &from)
virtual ~FuelMetadata_Legal ()
size_t ByteSizeLong () const final
void Clear () final
void clear_copyright ()
void clear_license ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const FuelMetadata_Legal &from)
const ::std::string & copyright () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::std::string & license () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const FuelMetadata_Legal &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_copyright ()
::std::string * mutable_license ()
FuelMetadata_Legal * New () const final
FuelMetadata_Legal * New (::google::protobuf::Arena *arena) const final
FuelMetadata_Legal & operator= (const FuelMetadata_Legal &from)
::std::string * release_copyright ()
::std::string * release_license ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_copyright (::std::string *copyright)
void set_allocated_license (::std::string *license)
void set_copyright (const ::std::string &value)
void set_copyright (const char *value)
void set_copyright (const char *value, size_t size)
void set_license (const ::std::string &value)
void set_license (const char *value)
void set_license (const char *value, size_t size)
void Swap (FuelMetadata_Legal *other)
Static Public Member Functions
static const FuelMetadata_Legal & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const FuelMetadata_Legal * internal_default_instance ()
Static Public Attributes
static const int kCopyrightFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kLicenseFieldNumber = 2
Constructor & Destructor Documentation
FuelMetadata_Legal() [1/2]
FuelMetadata_Legal ()
~FuelMetadata_Legal()
virtual ~FuelMetadata_Legal () virtual
FuelMetadata_Legal() [2/2]
FuelMetadata_Legal (const FuelMetadata_Legal & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_copyright()
void clear_copyright () inline
clear_license()
void clear_license () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const FuelMetadata_Legal & from)
copyright()
const ::std::string & copyright () const inline
Referenced by FuelMetadata_Legal::set_allocated_copyright().
default_instance()
static const FuelMetadata_Legal& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const FuelMetadata_Legal* internal_default_instance () inline static
References ignition::msgs::_FuelMetadata_Legal_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
license()
const ::std::string & license () const inline
Referenced by FuelMetadata_Legal::set_allocated_license().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const FuelMetadata_Legal & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_copyright()
std::string * mutable_copyright () inline
mutable_license()
std::string * mutable_license () inline
New() [1/2]
FuelMetadata_Legal* New () const inline final
New() [2/2]
FuelMetadata_Legal* New (::google::protobuf::Arena * arena) const inline final
operator=()
FuelMetadata_Legal& operator= (const FuelMetadata_Legal & from) inline
release_copyright()
std::string * release_copyright () inline
release_license()
std::string * release_license () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_copyright()
void set_allocated_copyright (::std::string * copyright) inline
References FuelMetadata_Legal::copyright().
set_allocated_license()
void set_allocated_license (::std::string * license) inline
References FuelMetadata_Legal::license().
set_copyright() [1/3]
void set_copyright (const ::std::string & value) inline
set_copyright() [2/3]
void set_copyright (const char * value) inline
set_copyright() [3/3]
void set_copyright (const char * value, size_t size) inline
set_license() [1/3]
void set_license (const ::std::string & value) inline
set_license() [2/3]
void set_license (const char * value) inline
set_license() [3/3]
void set_license (const char * value, size_t size) inline
Swap()
void Swap (FuelMetadata_Legal * other)
Member Data Documentation
kCopyrightFieldNumber
const int kCopyrightFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    1
kLicenseFieldNumber
const int kLicenseFieldNumber = 2 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/fuel_metadata.pb.h