Gazebo Msgs: Road Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Road Class Reference
#include <road.pb.h>
Public Member Functions
Road ()
Road (const Road &from)
virtual ~Road ()
::ignition::msgs::Vector3d * add_point ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_material ()
void clear_name ()
void clear_point ()
void clear_width ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Road &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_material () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::ignition::msgs::Material & material () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Road &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::Material * mutable_material ()
::std::string * mutable_name ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Vector3d > * mutable_point ()
::ignition::msgs::Vector3d * mutable_point (int index)
const ::std::string & name () const
Road * New () const final
Road * New (::google::protobuf::Arena *arena) const final
Road & operator= (const Road &from)
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Vector3d > & point () const
const ::ignition::msgs::Vector3d & point (int index) const
int point_size () const
::ignition::msgs::Header * release_header ()
::ignition::msgs::Material * release_material ()
::std::string * release_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_material (::ignition::msgs::Material *material)
void set_allocated_name (::std::string *name)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_width (double value)
void Swap (Road *other)
double width () const
Static Public Member Functions
static const Road & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Road * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kMaterialFieldNumber = 5
static const int kNameFieldNumber = 2
static const int kPointFieldNumber = 4
static const int kWidthFieldNumber = 3
Constructor & Destructor Documentation
Road() [1/2]
Road ()
~Road()
virtual ~Road () virtual
Road() [2/2]
Road (const Road & from)
Member Function Documentation
add_point()
ignition::msgs::Vector3d * add_point () inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_material()
void clear_material ()
clear_name()
void clear_name () inline
clear_point()
void clear_point ()
clear_width()
void clear_width () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Road & from)
default_instance()
static const Road& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Road::internal_default_instance().
has_material()
bool has_material () const inline
References Road::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Road::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Road* internal_default_instance () inline static
References ignition::msgs::_Road_default_instance_.
Referenced by Road::has_header(), and Road::has_material().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
material()
const ::ignition::msgs::Material & material () const inline
References ignition::msgs::_Material_default_instance_.
Referenced by Road::set_allocated_material().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Road & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_material()
ignition::msgs::Material * mutable_material () inline
mutable_name()
std::string * mutable_name () inline
mutable_point() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Vector3d > * mutable_point () inline
mutable_point() [2/2]
ignition::msgs::Vector3d * mutable_point (int index) inline
name()
const ::std::string & name () const inline
Referenced by Road::set_allocated_name().
New() [1/2]
Road* New () const inline final
New() [2/2]
Road* New (::google::protobuf::Arena * arena) const inline final
operator=()
Road& operator= (const Road & from) inline
point() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Vector3d > & point () const inline
point() [2/2]
const ::ignition::msgs::Vector3d & point (int index) const inline
point_size()
int point_size () const inline
release_header()
ignition::msgs::Header * release_header () inline
release_material()
ignition::msgs::Material * release_material () inline
release_name()
std::string * release_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Road::header().
set_allocated_material()
void set_allocated_material (::ignition::msgs::Material * material) inline
References Road::material().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Road::name().
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_width()
void set_width (double value) inline
Swap()
void Swap (Road * other)
width()
double width () const inline
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kMaterialFieldNumber
const int kMaterialFieldNumber = 5 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
kPointFieldNumber
const int kPointFieldNumber = 4 static
kWidthFieldNumber
const int kWidthFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/road.pb.h