Gazebo Msgs: Entity Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Entity Class Reference
#include <entity.pb.h>
Public Types
typedef Entity_Type Type
Public Member Functions
Entity ()
Entity (const Entity &from)
virtual ~Entity ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_id ()
void clear_name ()
void clear_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Entity &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint64 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Entity &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_name ()
const ::std::string & name () const
Entity * New () const final
Entity * New (::google::protobuf::Arena *arena) const final
Entity & operator= (const Entity &from)
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_id (::google::protobuf::uint64 value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_type (::ignition::msgs::Entity_Type value)
void Swap (Entity *other)
::ignition::msgs::Entity_Type type () const
Static Public Member Functions
static const Entity & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Entity * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type ACTOR
static const Type COLLISION
static const Type JOINT
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 3
static const int kTypeFieldNumber = 4
static const Type LIGHT
static const Type LINK
static const Type MODEL
static const Type NONE
static const Type SENSOR
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
static const Type VISUAL
static const Type WORLD
Member Typedef Documentation
Type
typedef Entity_Type Type
Constructor & Destructor Documentation
Entity() [1/2]
Entity ()
~Entity()
virtual ~Entity () virtual
Entity() [2/2]
Entity (const Entity & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_name()
void clear_name () inline
clear_type()
void clear_type () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Entity & from)
default_instance()
static const Entity& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Entity::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Entity::set_allocated_header().
id()
google::protobuf::uint64 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Entity* internal_default_instance () inline static
References ignition::msgs::_Entity_default_instance_.
Referenced by Entity::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Entity & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
name()
const ::std::string & name () const inline
Referenced by Entity::set_allocated_name().
New() [1/2]
Entity* New () const inline final
New() [2/2]
Entity* New (::google::protobuf::Arena * arena) const inline final
operator=()
Entity& operator= (const Entity & from) inline
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Entity::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Entity::name().
set_id()
void set_id (::google::protobuf::uint64 value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_type()
void set_type (::ignition::msgs::Entity_Type value) inline
Swap()
void Swap (Entity * other)
type()
ignition::msgs::Entity_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References ignition::msgs::Entity_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References ignition::msgs::Entity_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References ignition::msgs::Entity_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References ignition::msgs::Entity_Type_Parse().
Member Data Documentation
ACTOR
const Type ACTOR static
Initial value:
=
    Entity_Type_ACTOR
COLLISION
const Type COLLISION static
Initial value:
=
    Entity_Type_COLLISION
JOINT
const Type JOINT static
Initial value:
=
    Entity_Type_JOINT
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 3 static
kTypeFieldNumber
const int kTypeFieldNumber = 4 static
LIGHT
const Type LIGHT static
Initial value:
=
    Entity_Type_LIGHT
LINK
const Type LINK static
Initial value:
=
    Entity_Type_LINK
MODEL
const Type MODEL static
Initial value:
=
    Entity_Type_MODEL
NONE
const Type NONE static
Initial value:
=
    Entity_Type_NONE
SENSOR
const Type SENSOR static
Initial value:
=
    Entity_Type_SENSOR
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    Entity_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    Entity_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    Entity_Type_Type_MIN
VISUAL
const Type VISUAL static
Initial value:
=
    Entity_Type_VISUAL
WORLD
const Type WORLD static
Initial value:
=
    Entity_Type_WORLD
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/entity.pb.h