Gazebo Msgs: Collision Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Collision Class Reference
#include <collision.pb.h>
Public Member Functions
Collision ()
Collision (const Collision &from)
virtual ~Collision ()
::ignition::msgs::Visual * add_visual ()
size_t ByteSizeLong () const final
void Clear () final
void clear_geometry ()
void clear_header ()
void clear_id ()
void clear_laser_retro ()
void clear_max_contacts ()
void clear_name ()
void clear_pose ()
void clear_surface ()
void clear_visual ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Collision &from)
const ::ignition::msgs::Geometry & geometry () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_geometry () const
bool has_header () const
bool has_pose () const
bool has_surface () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
double laser_retro () const
double max_contacts () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Collision &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Geometry * mutable_geometry ()
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_name ()
::ignition::msgs::Pose * mutable_pose ()
::ignition::msgs::Surface * mutable_surface ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Visual > * mutable_visual ()
::ignition::msgs::Visual * mutable_visual (int index)
const ::std::string & name () const
Collision * New () const final
Collision * New (::google::protobuf::Arena *arena) const final
Collision & operator= (const Collision &from)
const ::ignition::msgs::Pose & pose () const
::ignition::msgs::Geometry * release_geometry ()
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
::ignition::msgs::Pose * release_pose ()
::ignition::msgs::Surface * release_surface ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_geometry (::ignition::msgs::Geometry *geometry)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_pose (::ignition::msgs::Pose *pose)
void set_allocated_surface (::ignition::msgs::Surface *surface)
void set_id (::google::protobuf::uint32 value)
void set_laser_retro (double value)
void set_max_contacts (double value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
const ::ignition::msgs::Surface & surface () const
void Swap (Collision *other)
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Visual > & visual () const
const ::ignition::msgs::Visual & visual (int index) const
int visual_size () const
Static Public Member Functions
static const Collision & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Collision * internal_default_instance ()
Static Public Attributes
static const int kGeometryFieldNumber = 7
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kLaserRetroFieldNumber = 4
static const int kMaxContactsFieldNumber = 5
static const int kNameFieldNumber = 3
static const int kPoseFieldNumber = 6
static const int kSurfaceFieldNumber = 8
static const int kVisualFieldNumber = 9
Constructor & Destructor Documentation
Collision() [1/2]
Collision ()
~Collision()
virtual ~Collision () virtual
Collision() [2/2]
Collision (const Collision & from)
Member Function Documentation
add_visual()
ignition::msgs::Visual * add_visual () inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_geometry()
void clear_geometry ()
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_laser_retro()
void clear_laser_retro () inline
clear_max_contacts()
void clear_max_contacts () inline
clear_name()
void clear_name () inline
clear_pose()
void clear_pose ()
clear_surface()
void clear_surface ()
clear_visual()
void clear_visual ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Collision & from)
default_instance()
static const Collision& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
geometry()
const ::ignition::msgs::Geometry & geometry () const inline
References ignition::msgs::_Geometry_default_instance_.
Referenced by Collision::set_allocated_geometry().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_geometry()
bool has_geometry () const inline
References Collision::internal_default_instance().
has_header()
bool has_header () const inline
References Collision::internal_default_instance().
has_pose()
bool has_pose () const inline
References Collision::internal_default_instance().
has_surface()
bool has_surface () const inline
References Collision::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Collision::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Collision* internal_default_instance () inline static
References ignition::msgs::_Collision_default_instance_.
Referenced by Collision::has_geometry(), Collision::has_header(), Collision::has_pose(), and Collision::has_surface().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
laser_retro()
double laser_retro () const inline
max_contacts()
double max_contacts () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Collision & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_geometry()
ignition::msgs::Geometry * mutable_geometry () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
mutable_pose()
ignition::msgs::Pose * mutable_pose () inline
mutable_surface()
ignition::msgs::Surface * mutable_surface () inline
mutable_visual() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Visual > * mutable_visual () inline
mutable_visual() [2/2]
ignition::msgs::Visual * mutable_visual (int index) inline
name()
const ::std::string & name () const inline
Referenced by Collision::set_allocated_name().
New() [1/2]
Collision* New () const inline final
New() [2/2]
Collision* New (::google::protobuf::Arena * arena) const inline final
operator=()
Collision& operator= (const Collision & from) inline
pose()
const ::ignition::msgs::Pose & pose () const inline
References ignition::msgs::_Pose_default_instance_.
Referenced by Collision::set_allocated_pose().
release_geometry()
ignition::msgs::Geometry * release_geometry () inline
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_pose()
ignition::msgs::Pose * release_pose () inline
release_surface()
ignition::msgs::Surface * release_surface () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_geometry()
void set_allocated_geometry (::ignition::msgs::Geometry * geometry) inline
References Collision::geometry().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Collision::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Collision::name().
set_allocated_pose()
void set_allocated_pose (::ignition::msgs::Pose * pose) inline
References Collision::pose().
set_allocated_surface()
void set_allocated_surface (::ignition::msgs::Surface * surface) inline
References Collision::surface().
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_laser_retro()
void set_laser_retro (double value) inline
set_max_contacts()
void set_max_contacts (double value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
surface()
const ::ignition::msgs::Surface & surface () const inline
References ignition::msgs::_Surface_default_instance_.
Referenced by Collision::set_allocated_surface().
Swap()
void Swap (Collision * other)
visual() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Visual > & visual () const inline
visual() [2/2]
const ::ignition::msgs::Visual & visual (int index) const inline
visual_size()
int visual_size () const inline
Member Data Documentation
kGeometryFieldNumber
const int kGeometryFieldNumber = 7 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLaserRetroFieldNumber
const int kLaserRetroFieldNumber = 4 static
kMaxContactsFieldNumber
const int kMaxContactsFieldNumber = 5 static
kNameFieldNumber
const int kNameFieldNumber = 3 static
kPoseFieldNumber
const int kPoseFieldNumber = 6 static
kSurfaceFieldNumber
const int kSurfaceFieldNumber = 8 static
kVisualFieldNumber
const int kVisualFieldNumber = 9 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/collision.pb.h