Gazebo Msgs: Fluid Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Fluid Class Reference
#include <fluid.pb.h>
Public Member Functions
Fluid ()
Fluid (const Fluid &from)
virtual ~Fluid ()
::ignition::msgs::Vector3d * add_position ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_name ()
void clear_position ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Fluid &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Fluid &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_name ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Vector3d > * mutable_position ()
::ignition::msgs::Vector3d * mutable_position (int index)
const ::std::string & name () const
Fluid * New () const final
Fluid * New (::google::protobuf::Arena *arena) const final
Fluid & operator= (const Fluid &from)
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Vector3d > & position () const
const ::ignition::msgs::Vector3d & position (int index) const
int position_size () const
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void Swap (Fluid *other)
Static Public Member Functions
static const Fluid & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Fluid * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 2
static const int kPositionFieldNumber = 3
Constructor & Destructor Documentation
Fluid() [1/2]
Fluid ()
~Fluid()
virtual ~Fluid () virtual
Fluid() [2/2]
Fluid (const Fluid & from)
Member Function Documentation
add_position()
ignition::msgs::Vector3d * add_position () inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_name()
void clear_name () inline
clear_position()
void clear_position ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Fluid & from)
default_instance()
static const Fluid& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Fluid::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Fluid::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Fluid* internal_default_instance () inline static
References ignition::msgs::_Fluid_default_instance_.
Referenced by Fluid::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Fluid & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
mutable_position() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Vector3d > * mutable_position () inline
mutable_position() [2/2]
ignition::msgs::Vector3d * mutable_position (int index) inline
name()
const ::std::string & name () const inline
Referenced by Fluid::set_allocated_name().
New() [1/2]
Fluid* New () const inline final
New() [2/2]
Fluid* New (::google::protobuf::Arena * arena) const inline final
operator=()
Fluid& operator= (const Fluid & from) inline
position() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Vector3d > & position () const inline
position() [2/2]
const ::ignition::msgs::Vector3d & position (int index) const inline
position_size()
int position_size () const inline
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Fluid::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Fluid::name().
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
Swap()
void Swap (Fluid * other)
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 2 static
kPositionFieldNumber
const int kPositionFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/fluid.pb.h