Gazebo Msgs: Atmosphere Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Atmosphere Class Reference
#include <atmosphere.pb.h>
Public Types
typedef Atmosphere_Type Type
Public Member Functions
Atmosphere ()
Atmosphere (const Atmosphere &from)
virtual ~Atmosphere ()
size_t ByteSizeLong () const final
void Clear () final
void clear_enable_atmosphere ()
void clear_header ()
void clear_mass_density ()
void clear_pressure ()
void clear_temperature ()
void clear_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Atmosphere &from)
bool enable_atmosphere () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
double mass_density () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Atmosphere &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
Atmosphere * New () const final
Atmosphere * New (::google::protobuf::Arena *arena) const final
Atmosphere & operator= (const Atmosphere &from)
double pressure () const
::ignition::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_enable_atmosphere (bool value)
void set_mass_density (double value)
void set_pressure (double value)
void set_temperature (double value)
void set_type (::ignition::msgs::Atmosphere_Type value)
void Swap (Atmosphere *other)
double temperature () const
::ignition::msgs::Atmosphere_Type type () const
Static Public Member Functions
static const Atmosphere & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Atmosphere * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type ADIABATIC
static const int kEnableAtmosphereFieldNumber = 6
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kMassDensityFieldNumber = 5
static const int kPressureFieldNumber = 4
static const int kTemperatureFieldNumber = 3
static const int kTypeFieldNumber = 2
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
Member Typedef Documentation
Type
typedef Atmosphere_Type Type
Constructor & Destructor Documentation
Atmosphere() [1/2]
Atmosphere ()
~Atmosphere()
virtual ~Atmosphere () virtual
Atmosphere() [2/2]
Atmosphere (const Atmosphere & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_enable_atmosphere()
void clear_enable_atmosphere () inline
clear_header()
void clear_header ()
clear_mass_density()
void clear_mass_density () inline
clear_pressure()
void clear_pressure () inline
clear_temperature()
void clear_temperature () inline
clear_type()
void clear_type () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Atmosphere & from)
default_instance()
static const Atmosphere& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
enable_atmosphere()
bool enable_atmosphere () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Atmosphere::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Atmosphere::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Atmosphere* internal_default_instance () inline static
References ignition::msgs::_Atmosphere_default_instance_.
Referenced by Atmosphere::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
mass_density()
double mass_density () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Atmosphere & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
New() [1/2]
Atmosphere* New () const inline final
New() [2/2]
Atmosphere* New (::google::protobuf::Arena * arena) const inline final
operator=()
Atmosphere& operator= (const Atmosphere & from) inline
pressure()
double pressure () const inline
release_header()
ignition::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Atmosphere::header().
set_enable_atmosphere()
void set_enable_atmosphere (bool value) inline
set_mass_density()
void set_mass_density (double value) inline
set_pressure()
void set_pressure (double value) inline
set_temperature()
void set_temperature (double value) inline
set_type()
void set_type (::ignition::msgs::Atmosphere_Type value) inline
Swap()
void Swap (Atmosphere * other)
temperature()
double temperature () const inline
type()
ignition::msgs::Atmosphere_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References ignition::msgs::Atmosphere_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References ignition::msgs::Atmosphere_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References ignition::msgs::Atmosphere_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References ignition::msgs::Atmosphere_Type_Parse().
Member Data Documentation
ADIABATIC
const Type ADIABATIC static
Initial value:
=
    Atmosphere_Type_ADIABATIC
kEnableAtmosphereFieldNumber
const int kEnableAtmosphereFieldNumber = 6 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kMassDensityFieldNumber
const int kMassDensityFieldNumber = 5 static
kPressureFieldNumber
const int kPressureFieldNumber = 4 static
kTemperatureFieldNumber
const int kTemperatureFieldNumber = 3 static
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    Atmosphere_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    Atmosphere_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    Atmosphere_Type_Type_MIN
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/atmosphere.pb.h