Gazebo Msgs: Physics Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Physics Class Reference
#include <physics.pb.h>
Public Types
typedef Physics_Type Type
Public Member Functions
Physics ()
Physics (const Physics &from)
virtual ~Physics ()
size_t ByteSizeLong () const final
double cfm () const
void Clear () final
void clear_cfm ()
void clear_contact_max_correcting_vel ()
void clear_contact_surface_layer ()
void clear_enable_physics ()
void clear_erp ()
void clear_gravity ()
void clear_header ()
void clear_iters ()
void clear_magnetic_field ()
void clear_max_step_size ()
void clear_min_step_size ()
void clear_precon_iters ()
void clear_profile_name ()
void clear_real_time_factor ()
void clear_real_time_update_rate ()
void clear_solver_type ()
void clear_sor ()
void clear_type ()
double contact_max_correcting_vel () const
double contact_surface_layer () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Physics &from)
bool enable_physics () const
double erp () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
const ::ignition::msgs::Vector3d & gravity () const
bool has_gravity () const
bool has_header () const
bool has_magnetic_field () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
::google::protobuf::int32 iters () const
const ::ignition::msgs::Vector3d & magnetic_field () const
double max_step_size () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Physics &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
double min_step_size () const
::ignition::msgs::Vector3d * mutable_gravity ()
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::Vector3d * mutable_magnetic_field ()
::std::string * mutable_profile_name ()
::std::string * mutable_solver_type ()
Physics * New () const final
Physics * New (::google::protobuf::Arena *arena) const final
Physics & operator= (const Physics &from)
::google::protobuf::int32 precon_iters () const
const ::std::string & profile_name () const
double real_time_factor () const
double real_time_update_rate () const
::ignition::msgs::Vector3d * release_gravity ()
::ignition::msgs::Header * release_header ()
::ignition::msgs::Vector3d * release_magnetic_field ()
::std::string * release_profile_name ()
::std::string * release_solver_type ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_gravity (::ignition::msgs::Vector3d *gravity)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_magnetic_field (::ignition::msgs::Vector3d *magnetic_field)
void set_allocated_profile_name (::std::string *profile_name)
void set_allocated_solver_type (::std::string *solver_type)
void set_cfm (double value)
void set_contact_max_correcting_vel (double value)
void set_contact_surface_layer (double value)
void set_enable_physics (bool value)
void set_erp (double value)
void set_iters (::google::protobuf::int32 value)
void set_max_step_size (double value)
void set_min_step_size (double value)
void set_precon_iters (::google::protobuf::int32 value)
void set_profile_name (const ::std::string &value)
void set_profile_name (const char *value)
void set_profile_name (const char *value, size_t size)
void set_real_time_factor (double value)
void set_real_time_update_rate (double value)
void set_solver_type (const ::std::string &value)
void set_solver_type (const char *value)
void set_solver_type (const char *value, size_t size)
void set_sor (double value)
void set_type (::ignition::msgs::Physics_Type value)
const ::std::string & solver_type () const
double sor () const
void Swap (Physics *other)
::ignition::msgs::Physics_Type type () const
Static Public Member Functions
static const Physics & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Physics * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type BULLET
static const Type DART
static const int kCfmFieldNumber = 8
static const int kContactMaxCorrectingVelFieldNumber = 10
static const int kContactSurfaceLayerFieldNumber = 11
static const int kEnablePhysicsFieldNumber = 13
static const int kErpFieldNumber = 9
static const int kGravityFieldNumber = 12
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kItersFieldNumber = 6
static const int kMagneticFieldFieldNumber = 18
static const int kMaxStepSizeFieldNumber = 16
static const int kMinStepSizeFieldNumber = 4
static const int kPreconItersFieldNumber = 5
static const int kProfileNameFieldNumber = 17
static const int kRealTimeFactorFieldNumber = 14
static const int kRealTimeUpdateRateFieldNumber = 15
static const int kSolverTypeFieldNumber = 3
static const int kSorFieldNumber = 7
static const int kTypeFieldNumber = 2
static const Type ODE
static const Type SIMBODY
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
Member Typedef Documentation
Type
typedef Physics_Type Type
Constructor & Destructor Documentation
Physics() [1/2]
Physics ()
~Physics()
virtual ~Physics () virtual
Physics() [2/2]
Physics (const Physics & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
cfm()
double cfm () const inline
Clear()
void Clear () final
clear_cfm()
void clear_cfm () inline
clear_contact_max_correcting_vel()
void clear_contact_max_correcting_vel () inline
clear_contact_surface_layer()
void clear_contact_surface_layer () inline
clear_enable_physics()
void clear_enable_physics () inline
clear_erp()
void clear_erp () inline
clear_gravity()
void clear_gravity ()
clear_header()
void clear_header ()
clear_iters()
void clear_iters () inline
clear_magnetic_field()
void clear_magnetic_field ()
clear_max_step_size()
void clear_max_step_size () inline
clear_min_step_size()
void clear_min_step_size () inline
clear_precon_iters()
void clear_precon_iters () inline
clear_profile_name()
void clear_profile_name () inline
clear_real_time_factor()
void clear_real_time_factor () inline
clear_real_time_update_rate()
void clear_real_time_update_rate () inline
clear_solver_type()
void clear_solver_type () inline
clear_sor()
void clear_sor () inline
clear_type()
void clear_type () inline
contact_max_correcting_vel()
double contact_max_correcting_vel () const inline
contact_surface_layer()
double contact_surface_layer () const inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Physics & from)
default_instance()
static const Physics& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
enable_physics()
bool enable_physics () const inline
erp()
double erp () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
gravity()
const ::ignition::msgs::Vector3d & gravity () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by Physics::set_allocated_gravity().
has_gravity()
bool has_gravity () const inline
References Physics::internal_default_instance().
has_header()
bool has_header () const inline
References Physics::internal_default_instance().
has_magnetic_field()
bool has_magnetic_field () const inline
References Physics::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Physics::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Physics* internal_default_instance () inline static
References ignition::msgs::_Physics_default_instance_.
Referenced by Physics::has_gravity(), Physics::has_header(), and Physics::has_magnetic_field().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
iters()
google::protobuf::int32 iters () const inline
magnetic_field()
const ::ignition::msgs::Vector3d & magnetic_field () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by Physics::set_allocated_magnetic_field().
max_step_size()
double max_step_size () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Physics & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
min_step_size()
double min_step_size () const inline
mutable_gravity()
ignition::msgs::Vector3d * mutable_gravity () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_magnetic_field()
ignition::msgs::Vector3d * mutable_magnetic_field () inline
mutable_profile_name()
std::string * mutable_profile_name () inline
mutable_solver_type()
std::string * mutable_solver_type () inline
New() [1/2]
Physics* New () const inline final
New() [2/2]
Physics* New (::google::protobuf::Arena * arena) const inline final
operator=()
Physics& operator= (const Physics & from) inline
precon_iters()
google::protobuf::int32 precon_iters () const inline
profile_name()
const ::std::string & profile_name () const inline
Referenced by Physics::set_allocated_profile_name().
real_time_factor()
double real_time_factor () const inline
real_time_update_rate()
double real_time_update_rate () const inline
release_gravity()
ignition::msgs::Vector3d * release_gravity () inline
release_header()
ignition::msgs::Header * release_header () inline
release_magnetic_field()
ignition::msgs::Vector3d * release_magnetic_field () inline
release_profile_name()
std::string * release_profile_name () inline
release_solver_type()
std::string * release_solver_type () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_gravity()
void set_allocated_gravity (::ignition::msgs::Vector3d * gravity) inline
References Physics::gravity().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Physics::header().
set_allocated_magnetic_field()
void set_allocated_magnetic_field (::ignition::msgs::Vector3d * magnetic_field) inline
References Physics::magnetic_field().
set_allocated_profile_name()
void set_allocated_profile_name (::std::string * profile_name) inline
References Physics::profile_name().
set_allocated_solver_type()
void set_allocated_solver_type (::std::string * solver_type) inline
References Physics::solver_type().
set_cfm()
void set_cfm (double value) inline
set_contact_max_correcting_vel()
void set_contact_max_correcting_vel (double value) inline
set_contact_surface_layer()
void set_contact_surface_layer (double value) inline
set_enable_physics()
void set_enable_physics (bool value) inline
set_erp()
void set_erp (double value) inline
set_iters()
void set_iters (::google::protobuf::int32 value) inline
set_max_step_size()
void set_max_step_size (double value) inline
set_min_step_size()
void set_min_step_size (double value) inline
set_precon_iters()
void set_precon_iters (::google::protobuf::int32 value) inline
set_profile_name() [1/3]
void set_profile_name (const ::std::string & value) inline
set_profile_name() [2/3]
void set_profile_name (const char * value) inline
set_profile_name() [3/3]
void set_profile_name (const char * value, size_t size) inline
set_real_time_factor()
void set_real_time_factor (double value) inline
set_real_time_update_rate()
void set_real_time_update_rate (double value) inline
set_solver_type() [1/3]
void set_solver_type (const ::std::string & value) inline
set_solver_type() [2/3]
void set_solver_type (const char * value) inline
set_solver_type() [3/3]
void set_solver_type (const char * value, size_t size) inline
set_sor()
void set_sor (double value) inline
set_type()
void set_type (::ignition::msgs::Physics_Type value) inline
solver_type()
const ::std::string & solver_type () const inline
Referenced by Physics::set_allocated_solver_type().
sor()
double sor () const inline
Swap()
void Swap (Physics * other)
type()
ignition::msgs::Physics_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References ignition::msgs::Physics_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References ignition::msgs::Physics_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References ignition::msgs::Physics_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References ignition::msgs::Physics_Type_Parse().
Member Data Documentation
BULLET
const Type BULLET static
Initial value:
=
    Physics_Type_BULLET
DART
const Type DART static
Initial value:
=
    Physics_Type_DART
kCfmFieldNumber
const int kCfmFieldNumber = 8 static
kContactMaxCorrectingVelFieldNumber
const int kContactMaxCorrectingVelFieldNumber = 10 static
kContactSurfaceLayerFieldNumber
const int kContactSurfaceLayerFieldNumber = 11 static
kEnablePhysicsFieldNumber
const int kEnablePhysicsFieldNumber = 13 static
kErpFieldNumber
const int kErpFieldNumber = 9 static
kGravityFieldNumber
const int kGravityFieldNumber = 12 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kItersFieldNumber
const int kItersFieldNumber = 6 static
kMagneticFieldFieldNumber
const int kMagneticFieldFieldNumber = 18 static
kMaxStepSizeFieldNumber
const int kMaxStepSizeFieldNumber = 16 static
kMinStepSizeFieldNumber
const int kMinStepSizeFieldNumber = 4 static
kPreconItersFieldNumber
const int kPreconItersFieldNumber = 5 static
kProfileNameFieldNumber
const int kProfileNameFieldNumber = 17 static
kRealTimeFactorFieldNumber
const int kRealTimeFactorFieldNumber = 14 static
kRealTimeUpdateRateFieldNumber
const int kRealTimeUpdateRateFieldNumber = 15 static
kSolverTypeFieldNumber
const int kSolverTypeFieldNumber = 3 static
kSorFieldNumber
const int kSorFieldNumber = 7 static
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
ODE
const Type ODE static
Initial value:
=
    Physics_Type_ODE
SIMBODY
const Type SIMBODY static
Initial value:
=
    Physics_Type_SIMBODY
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    Physics_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    Physics_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    Physics_Type_Type_MIN
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/physics.pb.h