Gazebo Msgs: Sensor Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Sensor Class Reference
#include <sensor.pb.h>
Public Member Functions
Sensor ()
Sensor (const Sensor &from)
virtual ~Sensor ()
const ::ignition::msgs::AirPressureSensor & air_pressure () const
const ::ignition::msgs::AltimeterSensor & altimeter () const
bool always_on () const
size_t ByteSizeLong () const final
const ::ignition::msgs::CameraSensor & camera () const
void Clear () final
void clear_air_pressure ()
void clear_altimeter ()
void clear_always_on ()
void clear_camera ()
void clear_contact ()
void clear_gps ()
void clear_header ()
void clear_id ()
void clear_imu ()
void clear_lidar ()
void clear_logical_camera ()
void clear_magnetometer ()
void clear_name ()
void clear_parent ()
void clear_parent_id ()
void clear_pose ()
void clear_topic ()
void clear_type ()
void clear_update_rate ()
void clear_visualize ()
const ::ignition::msgs::ContactSensor & contact () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Sensor &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
const ::ignition::msgs::GPSSensor & gps () const
bool has_air_pressure () const
bool has_altimeter () const
bool has_camera () const
bool has_contact () const
bool has_gps () const
bool has_header () const
bool has_imu () const
bool has_lidar () const
bool has_logical_camera () const
bool has_magnetometer () const
bool has_pose () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
const ::ignition::msgs::IMUSensor & imu () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::ignition::msgs::LidarSensor & lidar () const
const ::ignition::msgs::LogicalCameraSensor & logical_camera () const
const ::ignition::msgs::MagnetometerSensor & magnetometer () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Sensor &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::AirPressureSensor * mutable_air_pressure ()
::ignition::msgs::AltimeterSensor * mutable_altimeter ()
::ignition::msgs::CameraSensor * mutable_camera ()
::ignition::msgs::ContactSensor * mutable_contact ()
::ignition::msgs::GPSSensor * mutable_gps ()
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::IMUSensor * mutable_imu ()
::ignition::msgs::LidarSensor * mutable_lidar ()
::ignition::msgs::LogicalCameraSensor * mutable_logical_camera ()
::ignition::msgs::MagnetometerSensor * mutable_magnetometer ()
::std::string * mutable_name ()
::std::string * mutable_parent ()
::ignition::msgs::Pose * mutable_pose ()
::std::string * mutable_topic ()
::std::string * mutable_type ()
const ::std::string & name () const
Sensor * New () const final
Sensor * New (::google::protobuf::Arena *arena) const final
Sensor & operator= (const Sensor &from)
const ::std::string & parent () const
::google::protobuf::uint32 parent_id () const
const ::ignition::msgs::Pose & pose () const
::ignition::msgs::AirPressureSensor * release_air_pressure ()
::ignition::msgs::AltimeterSensor * release_altimeter ()
::ignition::msgs::CameraSensor * release_camera ()
::ignition::msgs::ContactSensor * release_contact ()
::ignition::msgs::GPSSensor * release_gps ()
::ignition::msgs::Header * release_header ()
::ignition::msgs::IMUSensor * release_imu ()
::ignition::msgs::LidarSensor * release_lidar ()
::ignition::msgs::LogicalCameraSensor * release_logical_camera ()
::ignition::msgs::MagnetometerSensor * release_magnetometer ()
::std::string * release_name ()
::std::string * release_parent ()
::ignition::msgs::Pose * release_pose ()
::std::string * release_topic ()
::std::string * release_type ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_air_pressure (::ignition::msgs::AirPressureSensor *air_pressure)
void set_allocated_altimeter (::ignition::msgs::AltimeterSensor *altimeter)
void set_allocated_camera (::ignition::msgs::CameraSensor *camera)
void set_allocated_contact (::ignition::msgs::ContactSensor *contact)
void set_allocated_gps (::ignition::msgs::GPSSensor *gps)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_imu (::ignition::msgs::IMUSensor *imu)
void set_allocated_lidar (::ignition::msgs::LidarSensor *lidar)
void set_allocated_logical_camera (::ignition::msgs::LogicalCameraSensor *logical_camera)
void set_allocated_magnetometer (::ignition::msgs::MagnetometerSensor *magnetometer)
void set_allocated_name (::std::string *name)
void set_allocated_parent (::std::string *parent)
void set_allocated_pose (::ignition::msgs::Pose *pose)
void set_allocated_topic (::std::string *topic)
void set_allocated_type (::std::string *type)
void set_always_on (bool value)
void set_id (::google::protobuf::uint32 value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_parent (const ::std::string &value)
void set_parent (const char *value)
void set_parent (const char *value, size_t size)
void set_parent_id (::google::protobuf::uint32 value)
void set_topic (const ::std::string &value)
void set_topic (const char *value)
void set_topic (const char *value, size_t size)
void set_type (const ::std::string &value)
void set_type (const char *value)
void set_type (const char *value, size_t size)
void set_update_rate (double value)
void set_visualize (bool value)
void Swap (Sensor *other)
const ::std::string & topic () const
const ::std::string & type () const
double update_rate () const
bool visualize () const
Static Public Member Functions
static const Sensor & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Sensor * internal_default_instance ()
Static Public Attributes
static const int kAirPressureFieldNumber = 19
static const int kAltimeterFieldNumber = 18
static const int kAlwaysOnFieldNumber = 7
static const int kCameraFieldNumber = 10
static const int kContactFieldNumber = 11
static const int kGpsFieldNumber = 15
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 3
static const int kImuFieldNumber = 16
static constexpr int kIndexInFileMessages
static const int kLidarFieldNumber = 20
static const int kLogicalCameraFieldNumber = 14
static const int kMagnetometerFieldNumber = 17
static const int kNameFieldNumber = 2
static const int kParentFieldNumber = 4
static const int kParentIdFieldNumber = 5
static const int kPoseFieldNumber = 9
static const int kTopicFieldNumber = 13
static const int kTypeFieldNumber = 6
static const int kUpdateRateFieldNumber = 8
static const int kVisualizeFieldNumber = 12
Constructor & Destructor Documentation
Sensor() [1/2]
Sensor ()
~Sensor()
virtual ~Sensor () virtual
Sensor() [2/2]
Sensor (const Sensor & from)
Member Function Documentation
air_pressure()
const ::ignition::msgs::AirPressureSensor & air_pressure () const inline
References ignition::msgs::_AirPressureSensor_default_instance_.
Referenced by Sensor::set_allocated_air_pressure().
altimeter()
const ::ignition::msgs::AltimeterSensor & altimeter () const inline
References ignition::msgs::_AltimeterSensor_default_instance_.
Referenced by Sensor::set_allocated_altimeter().
always_on()
bool always_on () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
camera()
const ::ignition::msgs::CameraSensor & camera () const inline
References ignition::msgs::_CameraSensor_default_instance_.
Referenced by Sensor::set_allocated_camera().
Clear()
void Clear () final
clear_air_pressure()
void clear_air_pressure ()
clear_altimeter()
void clear_altimeter ()
clear_always_on()
void clear_always_on () inline
clear_camera()
void clear_camera ()
clear_contact()
void clear_contact ()
clear_gps()
void clear_gps ()
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_imu()
void clear_imu ()
clear_lidar()
void clear_lidar ()
clear_logical_camera()
void clear_logical_camera ()
clear_magnetometer()
void clear_magnetometer ()
clear_name()
void clear_name () inline
clear_parent()
void clear_parent () inline
clear_parent_id()
void clear_parent_id () inline
clear_pose()
void clear_pose ()
clear_topic()
void clear_topic () inline
clear_type()
void clear_type () inline
clear_update_rate()
void clear_update_rate () inline
clear_visualize()
void clear_visualize () inline
contact()
const ::ignition::msgs::ContactSensor & contact () const inline
References ignition::msgs::_ContactSensor_default_instance_.
Referenced by Sensor::set_allocated_contact().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Sensor & from)
default_instance()
static const Sensor& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
gps()
const ::ignition::msgs::GPSSensor & gps () const inline
References ignition::msgs::_GPSSensor_default_instance_.
Referenced by Sensor::set_allocated_gps().
has_air_pressure()
bool has_air_pressure () const inline
References Sensor::internal_default_instance().
has_altimeter()
bool has_altimeter () const inline
References Sensor::internal_default_instance().
has_camera()
bool has_camera () const inline
References Sensor::internal_default_instance().
has_contact()
bool has_contact () const inline
References Sensor::internal_default_instance().
has_gps()
bool has_gps () const inline
References Sensor::internal_default_instance().
has_header()
bool has_header () const inline
References Sensor::internal_default_instance().
has_imu()
bool has_imu () const inline
References Sensor::internal_default_instance().
has_lidar()
bool has_lidar () const inline
References Sensor::internal_default_instance().
has_logical_camera()
bool has_logical_camera () const inline
References Sensor::internal_default_instance().
has_magnetometer()
bool has_magnetometer () const inline
References Sensor::internal_default_instance().
has_pose()
bool has_pose () const inline
References Sensor::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Sensor::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
imu()
const ::ignition::msgs::IMUSensor & imu () const inline
References ignition::msgs::_IMUSensor_default_instance_.
Referenced by Sensor::set_allocated_imu().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Sensor* internal_default_instance () inline static
References ignition::msgs::_Sensor_default_instance_.
Referenced by Sensor::has_air_pressure(), Sensor::has_altimeter(), Sensor::has_camera(), Sensor::has_contact(), Sensor::has_gps(), Sensor::has_header(), Sensor::has_imu(), Sensor::has_lidar(), Sensor::has_logical_camera(), Sensor::has_magnetometer(), and Sensor::has_pose().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
lidar()
const ::ignition::msgs::LidarSensor & lidar () const inline
References ignition::msgs::_LidarSensor_default_instance_.
Referenced by Sensor::set_allocated_lidar().
logical_camera()
const ::ignition::msgs::LogicalCameraSensor & logical_camera () const inline
References ignition::msgs::_LogicalCameraSensor_default_instance_.
Referenced by Sensor::set_allocated_logical_camera().
magnetometer()
const ::ignition::msgs::MagnetometerSensor & magnetometer () const inline
References ignition::msgs::_MagnetometerSensor_default_instance_.
Referenced by Sensor::set_allocated_magnetometer().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Sensor & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_air_pressure()
ignition::msgs::AirPressureSensor * mutable_air_pressure () inline
mutable_altimeter()
ignition::msgs::AltimeterSensor * mutable_altimeter () inline
mutable_camera()
ignition::msgs::CameraSensor * mutable_camera () inline
mutable_contact()
ignition::msgs::ContactSensor * mutable_contact () inline
mutable_gps()
ignition::msgs::GPSSensor * mutable_gps () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_imu()
ignition::msgs::IMUSensor * mutable_imu () inline
mutable_lidar()
ignition::msgs::LidarSensor * mutable_lidar () inline
mutable_logical_camera()
ignition::msgs::LogicalCameraSensor * mutable_logical_camera () inline
mutable_magnetometer()
ignition::msgs::MagnetometerSensor * mutable_magnetometer () inline
mutable_name()
std::string * mutable_name () inline
mutable_parent()
std::string * mutable_parent () inline
mutable_pose()
ignition::msgs::Pose * mutable_pose () inline
mutable_topic()
std::string * mutable_topic () inline
mutable_type()
std::string * mutable_type () inline
name()
const ::std::string & name () const inline
Referenced by Sensor::set_allocated_name().
New() [1/2]
Sensor* New () const inline final
New() [2/2]
Sensor* New (::google::protobuf::Arena * arena) const inline final
operator=()
Sensor& operator= (const Sensor & from) inline
parent()
const ::std::string & parent () const inline
Referenced by Sensor::set_allocated_parent().
parent_id()
google::protobuf::uint32 parent_id () const inline
pose()
const ::ignition::msgs::Pose & pose () const inline
References ignition::msgs::_Pose_default_instance_.
Referenced by Sensor::set_allocated_pose().
release_air_pressure()
ignition::msgs::AirPressureSensor * release_air_pressure () inline
release_altimeter()
ignition::msgs::AltimeterSensor * release_altimeter () inline
release_camera()
ignition::msgs::CameraSensor * release_camera () inline
release_contact()
ignition::msgs::ContactSensor * release_contact () inline
release_gps()
ignition::msgs::GPSSensor * release_gps () inline
release_header()
ignition::msgs::Header * release_header () inline
release_imu()
ignition::msgs::IMUSensor * release_imu () inline
release_lidar()
ignition::msgs::LidarSensor * release_lidar () inline
release_logical_camera()
ignition::msgs::LogicalCameraSensor * release_logical_camera () inline
release_magnetometer()
ignition::msgs::MagnetometerSensor * release_magnetometer () inline
release_name()
std::string * release_name () inline
release_parent()
std::string * release_parent () inline
release_pose()
ignition::msgs::Pose * release_pose () inline
release_topic()
std::string * release_topic () inline
release_type()
std::string * release_type () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_air_pressure()
void set_allocated_air_pressure (::ignition::msgs::AirPressureSensor * air_pressure) inline
References Sensor::air_pressure().
set_allocated_altimeter()
void set_allocated_altimeter (::ignition::msgs::AltimeterSensor * altimeter) inline
References Sensor::altimeter().
set_allocated_camera()
void set_allocated_camera (::ignition::msgs::CameraSensor * camera) inline
References Sensor::camera().
set_allocated_contact()
void set_allocated_contact (::ignition::msgs::ContactSensor * contact) inline
References Sensor::contact().
set_allocated_gps()
void set_allocated_gps (::ignition::msgs::GPSSensor * gps) inline
References Sensor::gps().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Sensor::header().
set_allocated_imu()
void set_allocated_imu (::ignition::msgs::IMUSensor * imu) inline
References Sensor::imu().
set_allocated_lidar()
void set_allocated_lidar (::ignition::msgs::LidarSensor * lidar) inline
References Sensor::lidar().
set_allocated_logical_camera()
void set_allocated_logical_camera (::ignition::msgs::LogicalCameraSensor * logical_camera) inline
References Sensor::logical_camera().
set_allocated_magnetometer()
void set_allocated_magnetometer (::ignition::msgs::MagnetometerSensor * magnetometer) inline
References Sensor::magnetometer().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Sensor::name().
set_allocated_parent()
void set_allocated_parent (::std::string * parent) inline
References Sensor::parent().
set_allocated_pose()
void set_allocated_pose (::ignition::msgs::Pose * pose) inline
References Sensor::pose().
set_allocated_topic()
void set_allocated_topic (::std::string * topic) inline
References Sensor::topic().
set_allocated_type()
void set_allocated_type (::std::string * type) inline
References Sensor::type().
set_always_on()
void set_always_on (bool value) inline
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_parent() [1/3]
void set_parent (const ::std::string & value) inline
set_parent() [2/3]
void set_parent (const char * value) inline
set_parent() [3/3]
void set_parent (const char * value, size_t size) inline
set_parent_id()
void set_parent_id (::google::protobuf::uint32 value) inline
set_topic() [1/3]
void set_topic (const ::std::string & value) inline
set_topic() [2/3]
void set_topic (const char * value) inline
set_topic() [3/3]
void set_topic (const char * value, size_t size) inline
set_type() [1/3]
void set_type (const ::std::string & value) inline
set_type() [2/3]
void set_type (const char * value) inline
set_type() [3/3]
void set_type (const char * value, size_t size) inline
set_update_rate()
void set_update_rate (double value) inline
set_visualize()
void set_visualize (bool value) inline
Swap()
void Swap (Sensor * other)
topic()
const ::std::string & topic () const inline
Referenced by Sensor::set_allocated_topic().
type()
const ::std::string & type () const inline
Referenced by Sensor::set_allocated_type().
update_rate()
double update_rate () const inline
visualize()
bool visualize () const inline
Member Data Documentation
kAirPressureFieldNumber
const int kAirPressureFieldNumber = 19 static
kAltimeterFieldNumber
const int kAltimeterFieldNumber = 18 static
kAlwaysOnFieldNumber
const int kAlwaysOnFieldNumber = 7 static
kCameraFieldNumber
const int kCameraFieldNumber = 10 static
kContactFieldNumber
const int kContactFieldNumber = 11 static
kGpsFieldNumber
const int kGpsFieldNumber = 15 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 3 static
kImuFieldNumber
const int kImuFieldNumber = 16 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLidarFieldNumber
const int kLidarFieldNumber = 20 static
kLogicalCameraFieldNumber
const int kLogicalCameraFieldNumber = 14 static
kMagnetometerFieldNumber
const int kMagnetometerFieldNumber = 17 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
kParentFieldNumber
const int kParentFieldNumber = 4 static
kParentIdFieldNumber
const int kParentIdFieldNumber = 5 static
kPoseFieldNumber
const int kPoseFieldNumber = 9 static
kTopicFieldNumber
const int kTopicFieldNumber = 13 static
kTypeFieldNumber
const int kTypeFieldNumber = 6 static
kUpdateRateFieldNumber
const int kUpdateRateFieldNumber = 8 static
kVisualizeFieldNumber
const int kVisualizeFieldNumber = 12 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/sensor.pb.h