Gazebo Msgs: SensorNoise Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
SensorNoise Class Reference
#include <sensor_noise.pb.h>
Public Types
typedef SensorNoise_Type Type
Public Member Functions
SensorNoise ()
SensorNoise (const SensorNoise &from)
virtual ~SensorNoise ()
double bias_mean () const
double bias_stddev () const
size_t ByteSizeLong () const final
void Clear () final
void clear_bias_mean ()
void clear_bias_stddev ()
void clear_dynamic_bias_correlation_time ()
void clear_dynamic_bias_stddev ()
void clear_header ()
void clear_mean ()
void clear_precision ()
void clear_stddev ()
void clear_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SensorNoise &from)
double dynamic_bias_correlation_time () const
double dynamic_bias_stddev () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
double mean () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const SensorNoise &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
SensorNoise * New () const final
SensorNoise * New (::google::protobuf::Arena *arena) const final
SensorNoise & operator= (const SensorNoise &from)
double precision () const
::ignition::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_bias_mean (double value)
void set_bias_stddev (double value)
void set_dynamic_bias_correlation_time (double value)
void set_dynamic_bias_stddev (double value)
void set_mean (double value)
void set_precision (double value)
void set_stddev (double value)
void set_type (::ignition::msgs::SensorNoise_Type value)
double stddev () const
void Swap (SensorNoise *other)
::ignition::msgs::SensorNoise_Type type () const
Static Public Member Functions
static const SensorNoise & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const SensorNoise * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type GAUSSIAN
static const Type GAUSSIAN_QUANTIZED
static const int kBiasMeanFieldNumber = 5
static const int kBiasStddevFieldNumber = 6
static const int kDynamicBiasCorrelationTimeFieldNumber = 9
static const int kDynamicBiasStddevFieldNumber = 8
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kMeanFieldNumber = 3
static const int kPrecisionFieldNumber = 7
static const int kStddevFieldNumber = 4
static const int kTypeFieldNumber = 2
static const Type NONE
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
Member Typedef Documentation
Type
typedef SensorNoise_Type Type
Constructor & Destructor Documentation
SensorNoise() [1/2]
SensorNoise ()
~SensorNoise()
virtual ~SensorNoise () virtual
SensorNoise() [2/2]
SensorNoise (const SensorNoise & from)
Member Function Documentation
bias_mean()
double bias_mean () const inline
bias_stddev()
double bias_stddev () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_bias_mean()
void clear_bias_mean () inline
clear_bias_stddev()
void clear_bias_stddev () inline
clear_dynamic_bias_correlation_time()
void clear_dynamic_bias_correlation_time () inline
clear_dynamic_bias_stddev()
void clear_dynamic_bias_stddev () inline
clear_header()
void clear_header ()
clear_mean()
void clear_mean () inline
clear_precision()
void clear_precision () inline
clear_stddev()
void clear_stddev () inline
clear_type()
void clear_type () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const SensorNoise & from)
default_instance()
static const SensorNoise& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
dynamic_bias_correlation_time()
double dynamic_bias_correlation_time () const inline
dynamic_bias_stddev()
double dynamic_bias_stddev () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References SensorNoise::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by SensorNoise::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const SensorNoise* internal_default_instance () inline static
References ignition::msgs::_SensorNoise_default_instance_.
Referenced by SensorNoise::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
mean()
double mean () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const SensorNoise & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
New() [1/2]
SensorNoise* New () const inline final
New() [2/2]
SensorNoise* New (::google::protobuf::Arena * arena) const inline final
operator=()
SensorNoise& operator= (const SensorNoise & from) inline
precision()
double precision () const inline
release_header()
ignition::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References SensorNoise::header().
set_bias_mean()
void set_bias_mean (double value) inline
set_bias_stddev()
void set_bias_stddev (double value) inline
set_dynamic_bias_correlation_time()
void set_dynamic_bias_correlation_time (double value) inline
set_dynamic_bias_stddev()
void set_dynamic_bias_stddev (double value) inline
set_mean()
void set_mean (double value) inline
set_precision()
void set_precision (double value) inline
set_stddev()
void set_stddev (double value) inline
set_type()
void set_type (::ignition::msgs::SensorNoise_Type value) inline
stddev()
double stddev () const inline
Swap()
void Swap (SensorNoise * other)
type()
ignition::msgs::SensorNoise_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References ignition::msgs::SensorNoise_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References ignition::msgs::SensorNoise_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References ignition::msgs::SensorNoise_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References ignition::msgs::SensorNoise_Type_Parse().
Member Data Documentation
GAUSSIAN
const Type GAUSSIAN static
Initial value:
=
    SensorNoise_Type_GAUSSIAN
GAUSSIAN_QUANTIZED
const Type GAUSSIAN_QUANTIZED static
Initial value:
=
    SensorNoise_Type_GAUSSIAN_QUANTIZED
kBiasMeanFieldNumber
const int kBiasMeanFieldNumber = 5 static
kBiasStddevFieldNumber
const int kBiasStddevFieldNumber = 6 static
kDynamicBiasCorrelationTimeFieldNumber
const int kDynamicBiasCorrelationTimeFieldNumber = 9 static
kDynamicBiasStddevFieldNumber
const int kDynamicBiasStddevFieldNumber = 8 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kMeanFieldNumber
const int kMeanFieldNumber = 3 static
kPrecisionFieldNumber
const int kPrecisionFieldNumber = 7 static
kStddevFieldNumber
const int kStddevFieldNumber = 4 static
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
NONE
const Type NONE static
Initial value:
=
    SensorNoise_Type_NONE
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    SensorNoise_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    SensorNoise_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    SensorNoise_Type_Type_MIN
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/sensor_noise.pb.h