Gazebo Msgs: IMU Class Reference
Gazebo Msgs
API Reference
5.11.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
IMU Class Reference
#include <imu.pb.h>
Public Member Functions
IMU ()
IMU (const IMU &from)
virtual ~IMU ()
const ::ignition::msgs::Vector3d & angular_velocity () const
size_t ByteSizeLong () const final
void Clear () final
void clear_angular_velocity ()
void clear_entity_name ()
void clear_header ()
void clear_linear_acceleration ()
void clear_orientation ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const IMU &from)
const ::std::string & entity_name () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_angular_velocity () const
bool has_header () const
bool has_linear_acceleration () const
bool has_orientation () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::ignition::msgs::Vector3d & linear_acceleration () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const IMU &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Vector3d * mutable_angular_velocity ()
::std::string * mutable_entity_name ()
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::Vector3d * mutable_linear_acceleration ()
::ignition::msgs::Quaternion * mutable_orientation ()
IMU * New () const final
IMU * New (::google::protobuf::Arena *arena) const final
IMU & operator= (const IMU &from)
const ::ignition::msgs::Quaternion & orientation () const
::ignition::msgs::Vector3d * release_angular_velocity ()
::std::string * release_entity_name ()
::ignition::msgs::Header * release_header ()
::ignition::msgs::Vector3d * release_linear_acceleration ()
::ignition::msgs::Quaternion * release_orientation ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_angular_velocity (::ignition::msgs::Vector3d *angular_velocity)
void set_allocated_entity_name (::std::string *entity_name)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_linear_acceleration (::ignition::msgs::Vector3d *linear_acceleration)
void set_allocated_orientation (::ignition::msgs::Quaternion *orientation)
void set_entity_name (const ::std::string &value)
void set_entity_name (const char *value)
void set_entity_name (const char *value, size_t size)
void Swap (IMU *other)
Static Public Member Functions
static const IMU & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const IMU * internal_default_instance ()
Static Public Attributes
static const int kAngularVelocityFieldNumber = 4
static const int kEntityNameFieldNumber = 2
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kLinearAccelerationFieldNumber = 5
static const int kOrientationFieldNumber = 3
Constructor & Destructor Documentation
IMU() [1/2]
IMU ()
~IMU()
virtual ~IMU () virtual
IMU() [2/2]
IMU (const IMU & from)
Member Function Documentation
angular_velocity()
const ::ignition::msgs::Vector3d & angular_velocity () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by IMU::set_allocated_angular_velocity().
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_angular_velocity()
void clear_angular_velocity ()
clear_entity_name()
void clear_entity_name () inline
clear_header()
void clear_header ()
clear_linear_acceleration()
void clear_linear_acceleration ()
clear_orientation()
void clear_orientation ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const IMU & from)
default_instance()
static const IMU& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
entity_name()
const ::std::string & entity_name () const inline
Referenced by IMU::set_allocated_entity_name().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_angular_velocity()
bool has_angular_velocity () const inline
References IMU::internal_default_instance().
has_header()
bool has_header () const inline
References IMU::internal_default_instance().
has_linear_acceleration()
bool has_linear_acceleration () const inline
References IMU::internal_default_instance().
has_orientation()
bool has_orientation () const inline
References IMU::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by IMU::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const IMU* internal_default_instance () inline static
References ignition::msgs::_IMU_default_instance_.
Referenced by IMU::has_angular_velocity(), IMU::has_header(), IMU::has_linear_acceleration(), and IMU::has_orientation().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
linear_acceleration()
const ::ignition::msgs::Vector3d & linear_acceleration () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by IMU::set_allocated_linear_acceleration().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const IMU & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_angular_velocity()
ignition::msgs::Vector3d * mutable_angular_velocity () inline
mutable_entity_name()
std::string * mutable_entity_name () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_linear_acceleration()
ignition::msgs::Vector3d * mutable_linear_acceleration () inline
mutable_orientation()
ignition::msgs::Quaternion * mutable_orientation () inline
New() [1/2]
IMU* New () const inline final
New() [2/2]
IMU* New (::google::protobuf::Arena * arena) const inline final
operator=()
IMU& operator= (const IMU & from) inline
orientation()
const ::ignition::msgs::Quaternion & orientation () const inline
References ignition::msgs::_Quaternion_default_instance_.
Referenced by IMU::set_allocated_orientation().
release_angular_velocity()
ignition::msgs::Vector3d * release_angular_velocity () inline
release_entity_name()
std::string * release_entity_name () inline
release_header()
ignition::msgs::Header * release_header () inline
release_linear_acceleration()
ignition::msgs::Vector3d * release_linear_acceleration () inline
release_orientation()
ignition::msgs::Quaternion * release_orientation () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_angular_velocity()
void set_allocated_angular_velocity (::ignition::msgs::Vector3d * angular_velocity) inline
References IMU::angular_velocity().
set_allocated_entity_name()
void set_allocated_entity_name (::std::string * entity_name) inline
References IMU::entity_name().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References IMU::header().
set_allocated_linear_acceleration()
void set_allocated_linear_acceleration (::ignition::msgs::Vector3d * linear_acceleration) inline
References IMU::linear_acceleration().
set_allocated_orientation()
void set_allocated_orientation (::ignition::msgs::Quaternion * orientation) inline
References IMU::orientation().
set_entity_name() [1/3]
void set_entity_name (const ::std::string & value) inline
set_entity_name() [2/3]
void set_entity_name (const char * value) inline
set_entity_name() [3/3]
void set_entity_name (const char * value, size_t size) inline
Swap()
void Swap (IMU * other)
Member Data Documentation
kAngularVelocityFieldNumber
const int kAngularVelocityFieldNumber = 4 static
kEntityNameFieldNumber
const int kEntityNameFieldNumber = 2 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLinearAccelerationFieldNumber
const int kLinearAccelerationFieldNumber = 5 static
kOrientationFieldNumber
const int kOrientationFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs5/include/ignition/msgs/imu.pb.h