Gazebo Rendering: Object Class Reference
Gazebo Rendering
API Reference
3.7.2
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Object Class Reference abstract
Represents an object present in the scene graph. This includes sub-meshes, materials, render targets, as well as posable nodes.
#include <ignition/rendering/Object.hh>
Public Member Functions
virtual ~Object ()
Destructor.
virtual void Destroy ()=0
Destroy any resources associated with this object. Invoking any other functions after destroying an object will result in undefined behavior.
virtual unsigned int Id () const =0
Get the object ID. This ID will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
virtual std::string Name () const =0
Get the object name. This name will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
virtual void PostRender ()=0
Post process this object and any of its children after rendering.
virtual void PreRender ()=0
Prepare this object and any of its children for rendering. This should be called for each object in a scene just before rendering, which can be achieved by a single call to Scene::PreRender.
virtual ScenePtr Scene () const =0
Get the Scene that created this object.
Detailed Description
Represents an object present in the scene graph. This includes sub-meshes, materials, render targets, as well as posable nodes.
Constructor & Destructor Documentation
~Object()
virtual ~Object () inline virtual
Destructor.
Member Function Documentation
Destroy()
virtual void Destroy () pure virtual
Destroy any resources associated with this object. Invoking any other functions after destroying an object will result in undefined behavior.
Implemented in Ogre2RenderTarget, OgreRenderTarget, Ogre2RenderWindow, Ogre2RenderTexture, BaseNode< T >, BaseNode< Ogre2Object >, BaseNode< OgreObject >, OgreRenderTexture, BaseSubMesh< T >, BaseSubMesh< Ogre2Object >, BaseSubMesh< OgreObject >, OgreCamera, Ogre2Camera, OgreThermalCamera, Ogre2Light, BaseVisual< T >, BaseVisual< Ogre2Node >, BaseVisual< OgreNode >, OgreSubMesh, BaseMesh< T >, BaseMesh< Ogre2Geometry >, BaseMesh< OgreGeometry >, Ogre2GpuRays, OgreGpuRays, Ogre2ThermalCamera, Ogre2RenderPass, Ogre2Node, OgreGaussianNoisePass, BaseGeometry< T >, OgreMarker, Ogre2Marker, BaseGeometry< Ogre2Object >, BaseGeometry< OgreObject >, Ogre2Mesh, OgreMesh, OgreNode, OgreRenderPass, BaseMarker< T >, OgreMaterial, BaseMarker< Ogre2Geometry >, BaseMarker< OgreGeometry >, BaseText< T >, BaseText< OgreGeometry >, Ogre2Material, OgreRenderWindow, OgreLight, BaseGrid< T >, BaseGrid< Ogre2Geometry >, and BaseGrid< OgreGeometry >.
Id()
virtual unsigned int Id () const pure virtual
Get the object ID. This ID will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
Returns
The object ID
Name()
virtual std::string Name () const pure virtual
Get the object name. This name will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
Returns
The object name
PostRender()
virtual void PostRender () pure virtual
Post process this object and any of its children after rendering.
Implemented in Camera, Ogre2RenderTexture, OgreRenderTexture, BaseCamera< T >, BaseCamera< Ogre2Sensor >, BaseCamera< OgreSensor >, Ogre2GpuRays, Ogre2RenderTarget, OgreGpuRays, OgreThermalCamera, Ogre2ThermalCamera, OgreRenderTarget, BaseRenderTarget< T >, BaseRenderTarget< Ogre2Object >, and BaseRenderTarget< OgreObject >.
Referenced by BaseCamera< OgreSensor >::PostRender().
PreRender()
virtual void PreRender () pure virtual
Prepare this object and any of its children for rendering. This should be called for each object in a scene just before rendering, which can be achieved by a single call to Scene::PreRender.
Implemented in BaseMaterial< T >, BaseMaterial< Ogre2Object >, BaseMaterial< OgreObject >, Ogre2RenderTexture, Ogre2Material, BaseNode< T >, BaseNode< Ogre2Object >, BaseNode< OgreObject >, OgreMaterial, OgreRenderTexture, BaseSubMesh< T >, BaseSubMesh< Ogre2Object >, BaseSubMesh< OgreObject >, OgreThermalCamera, BaseCamera< T >, BaseCamera< Ogre2Sensor >, BaseCamera< OgreSensor >, Ogre2GpuRays, BaseVisual< T >, BaseVisual< Ogre2Node >, BaseVisual< OgreNode >, Ogre2RenderTarget, BaseMesh< T >, BaseMesh< Ogre2Geometry >, BaseMesh< OgreGeometry >, OgreGpuRays, Ogre2ThermalCamera, OgreRenderTarget, BaseGizmoVisual< T >, BaseGizmoVisual< OgreVisual >, BaseGizmoVisual< Ogre2Visual >, OgreText, OgreGaussianNoisePass, OgreMarker, Ogre2Marker, Ogre2GaussianNoisePass, BaseMarker< T >, BaseRenderTarget< T >, BaseMarker< Ogre2Geometry >, BaseMarker< OgreGeometry >, BaseRenderTarget< Ogre2Object >, BaseRenderTarget< OgreObject >, BaseText< T >, BaseText< OgreGeometry >, OgreGrid, Ogre2Grid, BaseGrid< T >, BaseGrid< Ogre2Geometry >, and BaseGrid< OgreGeometry >.
Referenced by BaseCamera< OgreSensor >::PreRender(), and BaseSubMesh< OgreObject >::PreRender().
Scene()
virtual ScenePtr Scene () const pure virtual
Get the Scene that created this object.
Returns
The parent scene
The documentation for this class was generated from the following file:
gz/rendering/Object.hh