Gazebo Msgs: ServerControl Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
ServerControl Class Reference
#include <server_control.pb.h>
Public Member Functions
ServerControl ()
ServerControl (const ServerControl &from)
virtual ~ServerControl ()
size_t ByteSizeLong () const final
void Clear () final
void clear_clone ()
void clear_header ()
void clear_new_port ()
void clear_new_world ()
void clear_open_filename ()
void clear_save_filename ()
void clear_save_world_name ()
void clear_stop ()
bool clone () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const ServerControl &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ServerControl &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_open_filename ()
::std::string * mutable_save_filename ()
::std::string * mutable_save_world_name ()
ServerControl * New () const final
ServerControl * New (::google::protobuf::Arena *arena) const final
::google::protobuf::uint32 new_port () const
bool new_world () const
const ::std::string & open_filename () const
ServerControl & operator= (const ServerControl &from)
::ignition::msgs::Header * release_header ()
::std::string * release_open_filename ()
::std::string * release_save_filename ()
::std::string * release_save_world_name ()
const ::std::string & save_filename () const
const ::std::string & save_world_name () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_open_filename (::std::string *open_filename)
void set_allocated_save_filename (::std::string *save_filename)
void set_allocated_save_world_name (::std::string *save_world_name)
void set_clone (bool value)
void set_new_port (::google::protobuf::uint32 value)
void set_new_world (bool value)
void set_open_filename (const ::std::string &value)
void set_open_filename (const char *value)
void set_open_filename (const char *value, size_t size)
void set_save_filename (const ::std::string &value)
void set_save_filename (const char *value)
void set_save_filename (const char *value, size_t size)
void set_save_world_name (const ::std::string &value)
void set_save_world_name (const char *value)
void set_save_world_name (const char *value, size_t size)
void set_stop (bool value)
bool stop () const
void Swap (ServerControl *other)
Static Public Member Functions
static const ServerControl & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const ServerControl * internal_default_instance ()
Static Public Attributes
static const int kCloneFieldNumber = 7
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kNewPortFieldNumber = 8
static const int kNewWorldFieldNumber = 5
static const int kOpenFilenameFieldNumber = 4
static const int kSaveFilenameFieldNumber = 3
static const int kSaveWorldNameFieldNumber = 2
static const int kStopFieldNumber = 6
Constructor & Destructor Documentation
ServerControl() [1/2]
ServerControl ()
~ServerControl()
virtual ~ServerControl () virtual
ServerControl() [2/2]
ServerControl (const ServerControl & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_clone()
void clear_clone () inline
clear_header()
void clear_header ()
clear_new_port()
void clear_new_port () inline
clear_new_world()
void clear_new_world () inline
clear_open_filename()
void clear_open_filename () inline
clear_save_filename()
void clear_save_filename () inline
clear_save_world_name()
void clear_save_world_name () inline
clear_stop()
void clear_stop () inline
clone()
bool clone () const inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const ServerControl & from)
default_instance()
static const ServerControl& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References ServerControl::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by ServerControl::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const ServerControl* internal_default_instance () inline static
References ignition::msgs::_ServerControl_default_instance_.
Referenced by ServerControl::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const ServerControl & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_open_filename()
std::string * mutable_open_filename () inline
mutable_save_filename()
std::string * mutable_save_filename () inline
mutable_save_world_name()
std::string * mutable_save_world_name () inline
New() [1/2]
ServerControl* New () const inline final
New() [2/2]
ServerControl* New (::google::protobuf::Arena * arena) const inline final
new_port()
google::protobuf::uint32 new_port () const inline
new_world()
bool new_world () const inline
open_filename()
const ::std::string & open_filename () const inline
Referenced by ServerControl::set_allocated_open_filename().
operator=()
ServerControl& operator= (const ServerControl & from) inline
release_header()
ignition::msgs::Header * release_header () inline
release_open_filename()
std::string * release_open_filename () inline
release_save_filename()
std::string * release_save_filename () inline
release_save_world_name()
std::string * release_save_world_name () inline
save_filename()
const ::std::string & save_filename () const inline
Referenced by ServerControl::set_allocated_save_filename().
save_world_name()
const ::std::string & save_world_name () const inline
Referenced by ServerControl::set_allocated_save_world_name().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References ServerControl::header().
set_allocated_open_filename()
void set_allocated_open_filename (::std::string * open_filename) inline
References ServerControl::open_filename().
set_allocated_save_filename()
void set_allocated_save_filename (::std::string * save_filename) inline
References ServerControl::save_filename().
set_allocated_save_world_name()
void set_allocated_save_world_name (::std::string * save_world_name) inline
References ServerControl::save_world_name().
set_clone()
void set_clone (bool value) inline
set_new_port()
void set_new_port (::google::protobuf::uint32 value) inline
set_new_world()
void set_new_world (bool value) inline
set_open_filename() [1/3]
void set_open_filename (const ::std::string & value) inline
set_open_filename() [2/3]
void set_open_filename (const char * value) inline
set_open_filename() [3/3]
void set_open_filename (const char * value, size_t size) inline
set_save_filename() [1/3]
void set_save_filename (const ::std::string & value) inline
set_save_filename() [2/3]
void set_save_filename (const char * value) inline
set_save_filename() [3/3]
void set_save_filename (const char * value, size_t size) inline
set_save_world_name() [1/3]
void set_save_world_name (const ::std::string & value) inline
set_save_world_name() [2/3]
void set_save_world_name (const char * value) inline
set_save_world_name() [3/3]
void set_save_world_name (const char * value, size_t size) inline
set_stop()
void set_stop (bool value) inline
stop()
bool stop () const inline
Swap()
void Swap (ServerControl * other)
Member Data Documentation
kCloneFieldNumber
const int kCloneFieldNumber = 7 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNewPortFieldNumber
const int kNewPortFieldNumber = 8 static
kNewWorldFieldNumber
const int kNewWorldFieldNumber = 5 static
kOpenFilenameFieldNumber
const int kOpenFilenameFieldNumber = 4 static
kSaveFilenameFieldNumber
const int kSaveFilenameFieldNumber = 3 static
kSaveWorldNameFieldNumber
const int kSaveWorldNameFieldNumber = 2 static
kStopFieldNumber
const int kStopFieldNumber = 6 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/server_control.pb.h