Gazebo Msgs: Material Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Material Class Reference
#include <material.pb.h>
Public Types
typedef Material_PBR PBR
typedef Material_Script Script
typedef Material_ShaderType ShaderType
Public Member Functions
Material ()
Material (const Material &from)
virtual ~Material ()
const ::ignition::msgs::Color & ambient () const
size_t ByteSizeLong () const final
void Clear () final
void clear_ambient ()
void clear_diffuse ()
void clear_double_sided ()
void clear_emissive ()
void clear_header ()
void clear_lighting ()
void clear_normal_map ()
void clear_pbr ()
void clear_render_order ()
void clear_script ()
void clear_shader_type ()
void clear_specular ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Material &from)
const ::ignition::msgs::Color & diffuse () const
bool double_sided () const
const ::ignition::msgs::Color & emissive () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_ambient () const
bool has_diffuse () const
bool has_emissive () const
bool has_header () const
bool has_pbr () const
bool has_script () const
bool has_specular () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
bool lighting () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Material &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Color * mutable_ambient ()
::ignition::msgs::Color * mutable_diffuse ()
::ignition::msgs::Color * mutable_emissive ()
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_normal_map ()
::ignition::msgs::Material_PBR * mutable_pbr ()
::ignition::msgs::Material_Script * mutable_script ()
::ignition::msgs::Color * mutable_specular ()
Material * New () const final
Material * New (::google::protobuf::Arena *arena) const final
const ::std::string & normal_map () const
Material & operator= (const Material &from)
const ::ignition::msgs::Material_PBR & pbr () const
::ignition::msgs::Color * release_ambient ()
::ignition::msgs::Color * release_diffuse ()
::ignition::msgs::Color * release_emissive ()
::ignition::msgs::Header * release_header ()
::std::string * release_normal_map ()
::ignition::msgs::Material_PBR * release_pbr ()
::ignition::msgs::Material_Script * release_script ()
::ignition::msgs::Color * release_specular ()
double render_order () const
const ::ignition::msgs::Material_Script & script () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_ambient (::ignition::msgs::Color *ambient)
void set_allocated_diffuse (::ignition::msgs::Color *diffuse)
void set_allocated_emissive (::ignition::msgs::Color *emissive)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_normal_map (::std::string *normal_map)
void set_allocated_pbr (::ignition::msgs::Material_PBR *pbr)
void set_allocated_script (::ignition::msgs::Material_Script *script)
void set_allocated_specular (::ignition::msgs::Color *specular)
void set_double_sided (bool value)
void set_lighting (bool value)
void set_normal_map (const ::std::string &value)
void set_normal_map (const char *value)
void set_normal_map (const char *value, size_t size)
void set_render_order (double value)
void set_shader_type (::ignition::msgs::Material_ShaderType value)
::ignition::msgs::Material_ShaderType shader_type () const
const ::ignition::msgs::Color & specular () const
void Swap (Material *other)
Static Public Member Functions
static const Material & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Material * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * ShaderType_descriptor ()
static bool ShaderType_IsValid (int value)
static const ::std::string & ShaderType_Name (ShaderType value)
static bool ShaderType_Parse (const ::std::string &name, ShaderType *value)
Static Public Attributes
static const int kAmbientFieldNumber = 5
static const int kDiffuseFieldNumber = 6
static const int kDoubleSidedFieldNumber = 12
static const int kEmissiveFieldNumber = 8
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kLightingFieldNumber = 9
static const int kNormalMapFieldNumber = 4
static const int kPbrFieldNumber = 10
static const int kRenderOrderFieldNumber = 11
static const int kScriptFieldNumber = 2
static const int kShaderTypeFieldNumber = 3
static const int kSpecularFieldNumber = 7
static const ShaderType NORMAL_MAP_OBJECT_SPACE
static const ShaderType NORMAL_MAP_TANGENT_SPACE
static const ShaderType PIXEL
static const int ShaderType_ARRAYSIZE
static const ShaderType ShaderType_MAX
static const ShaderType ShaderType_MIN
static const ShaderType VERTEX
Member Typedef Documentation
PBR
typedef Material_PBR PBR
Script
typedef Material_Script Script
ShaderType
typedef Material_ShaderType ShaderType
Constructor & Destructor Documentation
Material() [1/2]
Material ()
~Material()
virtual ~Material () virtual
Material() [2/2]
Material (const Material & from)
Member Function Documentation
ambient()
const ::ignition::msgs::Color & ambient () const inline
References ignition::msgs::_Color_default_instance_.
Referenced by Material::set_allocated_ambient().
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_ambient()
void clear_ambient ()
clear_diffuse()
void clear_diffuse ()
clear_double_sided()
void clear_double_sided () inline
clear_emissive()
void clear_emissive ()
clear_header()
void clear_header ()
clear_lighting()
void clear_lighting () inline
clear_normal_map()
void clear_normal_map () inline
clear_pbr()
void clear_pbr () inline
clear_render_order()
void clear_render_order () inline
clear_script()
void clear_script () inline
clear_shader_type()
void clear_shader_type () inline
clear_specular()
void clear_specular ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Material & from)
default_instance()
static const Material& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
diffuse()
const ::ignition::msgs::Color & diffuse () const inline
References ignition::msgs::_Color_default_instance_.
Referenced by Material::set_allocated_diffuse().
double_sided()
bool double_sided () const inline
emissive()
const ::ignition::msgs::Color & emissive () const inline
References ignition::msgs::_Color_default_instance_.
Referenced by Material::set_allocated_emissive().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_ambient()
bool has_ambient () const inline
References Material::internal_default_instance().
has_diffuse()
bool has_diffuse () const inline
References Material::internal_default_instance().
has_emissive()
bool has_emissive () const inline
References Material::internal_default_instance().
has_header()
bool has_header () const inline
References Material::internal_default_instance().
has_pbr()
bool has_pbr () const inline
References Material::internal_default_instance().
has_script()
bool has_script () const inline
References Material::internal_default_instance().
has_specular()
bool has_specular () const inline
References Material::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Material::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Material* internal_default_instance () inline static
References ignition::msgs::_Material_default_instance_.
Referenced by Material::has_ambient(), Material::has_diffuse(), Material::has_emissive(), Material::has_header(), Material::has_pbr(), Material::has_script(), and Material::has_specular().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
lighting()
bool lighting () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Material & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_ambient()
ignition::msgs::Color * mutable_ambient () inline
mutable_diffuse()
ignition::msgs::Color * mutable_diffuse () inline
mutable_emissive()
ignition::msgs::Color * mutable_emissive () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_normal_map()
std::string * mutable_normal_map () inline
mutable_pbr()
ignition::msgs::Material_PBR * mutable_pbr () inline
mutable_script()
ignition::msgs::Material_Script * mutable_script () inline
mutable_specular()
ignition::msgs::Color * mutable_specular () inline
New() [1/2]
Material* New () const inline final
New() [2/2]
Material* New (::google::protobuf::Arena * arena) const inline final
normal_map()
const ::std::string & normal_map () const inline
Referenced by Material::set_allocated_normal_map().
operator=()
Material& operator= (const Material & from) inline
pbr()
const ::ignition::msgs::Material_PBR & pbr () const inline
References ignition::msgs::_Material_PBR_default_instance_.
Referenced by Material::set_allocated_pbr().
release_ambient()
ignition::msgs::Color * release_ambient () inline
release_diffuse()
ignition::msgs::Color * release_diffuse () inline
release_emissive()
ignition::msgs::Color * release_emissive () inline
release_header()
ignition::msgs::Header * release_header () inline
release_normal_map()
std::string * release_normal_map () inline
release_pbr()
ignition::msgs::Material_PBR * release_pbr () inline
release_script()
ignition::msgs::Material_Script * release_script () inline
release_specular()
ignition::msgs::Color * release_specular () inline
render_order()
double render_order () const inline
script()
const ::ignition::msgs::Material_Script & script () const inline
References ignition::msgs::_Material_Script_default_instance_.
Referenced by Material::set_allocated_script().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_ambient()
void set_allocated_ambient (::ignition::msgs::Color * ambient) inline
References Material::ambient().
set_allocated_diffuse()
void set_allocated_diffuse (::ignition::msgs::Color * diffuse) inline
References Material::diffuse().
set_allocated_emissive()
void set_allocated_emissive (::ignition::msgs::Color * emissive) inline
References Material::emissive().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Material::header().
set_allocated_normal_map()
void set_allocated_normal_map (::std::string * normal_map) inline
References Material::normal_map().
set_allocated_pbr()
void set_allocated_pbr (::ignition::msgs::Material_PBR * pbr) inline
References Material::pbr().
set_allocated_script()
void set_allocated_script (::ignition::msgs::Material_Script * script) inline
References Material::script().
set_allocated_specular()
void set_allocated_specular (::ignition::msgs::Color * specular) inline
References Material::specular().
set_double_sided()
void set_double_sided (bool value) inline
set_lighting()
void set_lighting (bool value) inline
set_normal_map() [1/3]
void set_normal_map (const ::std::string & value) inline
set_normal_map() [2/3]
void set_normal_map (const char * value) inline
set_normal_map() [3/3]
void set_normal_map (const char * value, size_t size) inline
set_render_order()
void set_render_order (double value) inline
set_shader_type()
void set_shader_type (::ignition::msgs::Material_ShaderType value) inline
shader_type()
ignition::msgs::Material_ShaderType shader_type () const inline
ShaderType_descriptor()
static const ::google::protobuf::EnumDescriptor* ShaderType_descriptor () inline static
References ignition::msgs::Material_ShaderType_descriptor().
ShaderType_IsValid()
static bool ShaderType_IsValid (int value) inline static
References ignition::msgs::Material_ShaderType_IsValid().
ShaderType_Name()
static const ::std::string& ShaderType_Name (ShaderType value) inline static
References ignition::msgs::Material_ShaderType_Name().
ShaderType_Parse()
static bool ShaderType_Parse (const ::std::string & name, ShaderType * value) inline static
References ignition::msgs::Material_ShaderType_Parse().
specular()
const ::ignition::msgs::Color & specular () const inline
References ignition::msgs::_Color_default_instance_.
Referenced by Material::set_allocated_specular().
Swap()
void Swap (Material * other)
Member Data Documentation
kAmbientFieldNumber
const int kAmbientFieldNumber = 5 static
kDiffuseFieldNumber
const int kDiffuseFieldNumber = 6 static
kDoubleSidedFieldNumber
const int kDoubleSidedFieldNumber = 12 static
kEmissiveFieldNumber
const int kEmissiveFieldNumber = 8 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    2
kLightingFieldNumber
const int kLightingFieldNumber = 9 static
kNormalMapFieldNumber
const int kNormalMapFieldNumber = 4 static
kPbrFieldNumber
const int kPbrFieldNumber = 10 static
kRenderOrderFieldNumber
const int kRenderOrderFieldNumber = 11 static
kScriptFieldNumber
const int kScriptFieldNumber = 2 static
kShaderTypeFieldNumber
const int kShaderTypeFieldNumber = 3 static
kSpecularFieldNumber
const int kSpecularFieldNumber = 7 static
NORMAL_MAP_OBJECT_SPACE
const ShaderType NORMAL_MAP_OBJECT_SPACE static
Initial value:
=
    Material_ShaderType_NORMAL_MAP_OBJECT_SPACE
NORMAL_MAP_TANGENT_SPACE
const ShaderType NORMAL_MAP_TANGENT_SPACE static
Initial value:
=
    Material_ShaderType_NORMAL_MAP_TANGENT_SPACE
PIXEL
const ShaderType PIXEL static
Initial value:
=
    Material_ShaderType_PIXEL
ShaderType_ARRAYSIZE
const int ShaderType_ARRAYSIZE static
Initial value:
=
    Material_ShaderType_ShaderType_ARRAYSIZE
ShaderType_MAX
const ShaderType ShaderType_MAX static
Initial value:
=
    Material_ShaderType_ShaderType_MAX
ShaderType_MIN
const ShaderType ShaderType_MIN static
Initial value:
=
    Material_ShaderType_ShaderType_MIN
VERTEX
const ShaderType VERTEX static
Initial value:
=
    Material_ShaderType_VERTEX
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/material.pb.h