Gazebo Msgs: PointCloudPacked_Field Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
PointCloudPacked_Field Class Reference
#include <pointcloud_packed.pb.h>
Public Types
typedef PointCloudPacked_Field_DataType DataType
Public Member Functions
PointCloudPacked_Field ()
PointCloudPacked_Field (const PointCloudPacked_Field &from)
virtual ~PointCloudPacked_Field ()
size_t ByteSizeLong () const final
void Clear () final
void clear_count ()
void clear_datatype ()
void clear_name ()
void clear_offset ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const PointCloudPacked_Field &from)
::google::protobuf::uint32 count () const
::ignition::msgs::PointCloudPacked_Field_DataType datatype () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const PointCloudPacked_Field &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_name ()
const ::std::string & name () const
PointCloudPacked_Field * New () const final
PointCloudPacked_Field * New (::google::protobuf::Arena *arena) const final
::google::protobuf::uint32 offset () const
PointCloudPacked_Field & operator= (const PointCloudPacked_Field &from)
::std::string * release_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_name (::std::string *name)
void set_count (::google::protobuf::uint32 value)
void set_datatype (::ignition::msgs::PointCloudPacked_Field_DataType value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_offset (::google::protobuf::uint32 value)
void Swap (PointCloudPacked_Field *other)
Static Public Member Functions
static const ::google::protobuf::EnumDescriptor * DataType_descriptor ()
static bool DataType_IsValid (int value)
static const ::std::string & DataType_Name (DataType value)
static bool DataType_Parse (const ::std::string &name, DataType *value)
static const PointCloudPacked_Field & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const PointCloudPacked_Field * internal_default_instance ()
Static Public Attributes
static const int DataType_ARRAYSIZE
static const DataType DataType_MAX
static const DataType DataType_MIN
static const DataType FLOAT32
static const DataType FLOAT64
static const DataType INT16
static const DataType INT32
static const DataType INT8
static const int kCountFieldNumber = 4
static const int kDatatypeFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 1
static const int kOffsetFieldNumber = 2
static const DataType UINT16
static const DataType UINT32
static const DataType UINT8
Member Typedef Documentation
DataType
typedef PointCloudPacked_Field_DataType DataType
Constructor & Destructor Documentation
PointCloudPacked_Field() [1/2]
PointCloudPacked_Field ()
~PointCloudPacked_Field()
virtual ~PointCloudPacked_Field () virtual
PointCloudPacked_Field() [2/2]
PointCloudPacked_Field (const PointCloudPacked_Field & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_count()
void clear_count () inline
clear_datatype()
void clear_datatype () inline
clear_name()
void clear_name () inline
clear_offset()
void clear_offset () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const PointCloudPacked_Field & from)
count()
google::protobuf::uint32 count () const inline
datatype()
ignition::msgs::PointCloudPacked_Field_DataType datatype () const inline
DataType_descriptor()
static const ::google::protobuf::EnumDescriptor* DataType_descriptor () inline static
References ignition::msgs::PointCloudPacked_Field_DataType_descriptor().
DataType_IsValid()
static bool DataType_IsValid (int value) inline static
References ignition::msgs::PointCloudPacked_Field_DataType_IsValid().
DataType_Name()
static const ::std::string& DataType_Name (DataType value) inline static
References ignition::msgs::PointCloudPacked_Field_DataType_Name().
DataType_Parse()
static bool DataType_Parse (const ::std::string & name, DataType * value) inline static
References ignition::msgs::PointCloudPacked_Field_DataType_Parse().
default_instance()
static const PointCloudPacked_Field& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const PointCloudPacked_Field* internal_default_instance () inline static
References ignition::msgs::_PointCloudPacked_Field_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const PointCloudPacked_Field & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_name()
std::string * mutable_name () inline
name()
const ::std::string & name () const inline
Referenced by PointCloudPacked_Field::set_allocated_name().
New() [1/2]
PointCloudPacked_Field* New () const inline final
New() [2/2]
PointCloudPacked_Field* New (::google::protobuf::Arena * arena) const inline final
offset()
google::protobuf::uint32 offset () const inline
operator=()
PointCloudPacked_Field& operator= (const PointCloudPacked_Field & from) inline
release_name()
std::string * release_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References PointCloudPacked_Field::name().
set_count()
void set_count (::google::protobuf::uint32 value) inline
set_datatype()
void set_datatype (::ignition::msgs::PointCloudPacked_Field_DataType value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_offset()
void set_offset (::google::protobuf::uint32 value) inline
Swap()
void Swap (PointCloudPacked_Field * other)
Member Data Documentation
DataType_ARRAYSIZE
const int DataType_ARRAYSIZE static
Initial value:
=
    PointCloudPacked_Field_DataType_DataType_ARRAYSIZE
DataType_MAX
const DataType DataType_MAX static
Initial value:
=
    PointCloudPacked_Field_DataType_DataType_MAX
DataType_MIN
const DataType DataType_MIN static
Initial value:
=
    PointCloudPacked_Field_DataType_DataType_MIN
FLOAT32
const DataType FLOAT32 static
Initial value:
=
    PointCloudPacked_Field_DataType_FLOAT32
Referenced by ignition::msgs::sizeOfPointField().
FLOAT64
const DataType FLOAT64 static
Initial value:
=
    PointCloudPacked_Field_DataType_FLOAT64
Referenced by ignition::msgs::sizeOfPointField().
INT16
const DataType INT16 static
Initial value:
=
    PointCloudPacked_Field_DataType_INT16
Referenced by ignition::msgs::sizeOfPointField().
INT32
const DataType INT32 static
Initial value:
=
    PointCloudPacked_Field_DataType_INT32
Referenced by ignition::msgs::sizeOfPointField().
INT8
const DataType INT8 static
Initial value:
=
    PointCloudPacked_Field_DataType_INT8
Referenced by ignition::msgs::sizeOfPointField().
kCountFieldNumber
const int kCountFieldNumber = 4 static
kDatatypeFieldNumber
const int kDatatypeFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 1 static
kOffsetFieldNumber
const int kOffsetFieldNumber = 2 static
UINT16
const DataType UINT16 static
Initial value:
=
    PointCloudPacked_Field_DataType_UINT16
Referenced by ignition::msgs::sizeOfPointField().
UINT32
const DataType UINT32 static
Initial value:
=
    PointCloudPacked_Field_DataType_UINT32
Referenced by ignition::msgs::sizeOfPointField().
UINT8
const DataType UINT8 static
Initial value:
=
    PointCloudPacked_Field_DataType_UINT8
Referenced by ignition::msgs::sizeOfPointField().
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/pointcloud_packed.pb.h