Gazebo Msgs: LaserScan Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
LaserScan Class Reference
#include <laserscan.pb.h>
Public Member Functions
LaserScan ()
LaserScan (const LaserScan &from)
virtual ~LaserScan ()
void add_intensities (double value)
void add_ranges (double value)
double angle_max () const
double angle_min () const
double angle_step () const
size_t ByteSizeLong () const final
void Clear () final
void clear_angle_max ()
void clear_angle_min ()
void clear_angle_step ()
void clear_count ()
void clear_frame ()
void clear_header ()
void clear_intensities ()
void clear_range_max ()
void clear_range_min ()
void clear_ranges ()
void clear_vertical_angle_max ()
void clear_vertical_angle_min ()
void clear_vertical_angle_step ()
void clear_vertical_count ()
void clear_world_pose ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const LaserScan &from)
::google::protobuf::uint32 count () const
const ::std::string & frame () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_world_pose () const
const ::ignition::msgs::Header & header () const
const ::google::protobuf::RepeatedField< double > & intensities () const
double intensities (int index) const
int intensities_size () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const LaserScan &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_frame ()
::ignition::msgs::Header * mutable_header ()
::google::protobuf::RepeatedField< double > * mutable_intensities ()
::google::protobuf::RepeatedField< double > * mutable_ranges ()
::ignition::msgs::Pose * mutable_world_pose ()
LaserScan * New () const final
LaserScan * New (::google::protobuf::Arena *arena) const final
LaserScan & operator= (const LaserScan &from)
double range_max () const
double range_min () const
const ::google::protobuf::RepeatedField< double > & ranges () const
double ranges (int index) const
int ranges_size () const
::std::string * release_frame ()
::ignition::msgs::Header * release_header ()
::ignition::msgs::Pose * release_world_pose ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_frame (::std::string *frame)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_world_pose (::ignition::msgs::Pose *world_pose)
void set_angle_max (double value)
void set_angle_min (double value)
void set_angle_step (double value)
void set_count (::google::protobuf::uint32 value)
void set_frame (const ::std::string &value)
void set_frame (const char *value)
void set_frame (const char *value, size_t size)
void set_intensities (int index, double value)
void set_range_max (double value)
void set_range_min (double value)
void set_ranges (int index, double value)
void set_vertical_angle_max (double value)
void set_vertical_angle_min (double value)
void set_vertical_angle_step (double value)
void set_vertical_count (::google::protobuf::uint32 value)
void Swap (LaserScan *other)
double vertical_angle_max () const
double vertical_angle_min () const
double vertical_angle_step () const
::google::protobuf::uint32 vertical_count () const
const ::ignition::msgs::Pose & world_pose () const
Static Public Member Functions
static const LaserScan & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const LaserScan * internal_default_instance ()
Static Public Attributes
static const int kAngleMaxFieldNumber = 5
static const int kAngleMinFieldNumber = 4
static const int kAngleStepFieldNumber = 6
static const int kCountFieldNumber = 9
static const int kFrameFieldNumber = 2
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kIntensitiesFieldNumber = 15
static const int kRangeMaxFieldNumber = 8
static const int kRangeMinFieldNumber = 7
static const int kRangesFieldNumber = 14
static const int kVerticalAngleMaxFieldNumber = 11
static const int kVerticalAngleMinFieldNumber = 10
static const int kVerticalAngleStepFieldNumber = 12
static const int kVerticalCountFieldNumber = 13
static const int kWorldPoseFieldNumber = 3
Constructor & Destructor Documentation
LaserScan() [1/2]
LaserScan ()
~LaserScan()
virtual ~LaserScan () virtual
LaserScan() [2/2]
LaserScan (const LaserScan & from)
Member Function Documentation
add_intensities()
void add_intensities (double value) inline
add_ranges()
void add_ranges (double value) inline
angle_max()
double angle_max () const inline
angle_min()
double angle_min () const inline
angle_step()
double angle_step () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_angle_max()
void clear_angle_max () inline
clear_angle_min()
void clear_angle_min () inline
clear_angle_step()
void clear_angle_step () inline
clear_count()
void clear_count () inline
clear_frame()
void clear_frame () inline
clear_header()
void clear_header ()
clear_intensities()
void clear_intensities () inline
clear_range_max()
void clear_range_max () inline
clear_range_min()
void clear_range_min () inline
clear_ranges()
void clear_ranges () inline
clear_vertical_angle_max()
void clear_vertical_angle_max () inline
clear_vertical_angle_min()
void clear_vertical_angle_min () inline
clear_vertical_angle_step()
void clear_vertical_angle_step () inline
clear_vertical_count()
void clear_vertical_count () inline
clear_world_pose()
void clear_world_pose ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const LaserScan & from)
count()
google::protobuf::uint32 count () const inline
default_instance()
static const LaserScan& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
frame()
const ::std::string & frame () const inline
Referenced by LaserScan::set_allocated_frame().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References LaserScan::internal_default_instance().
has_world_pose()
bool has_world_pose () const inline
References LaserScan::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by LaserScan::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
intensities() [1/2]
const ::google::protobuf::RepeatedField< double > & intensities () const inline
intensities() [2/2]
double intensities (int index) const inline
intensities_size()
int intensities_size () const inline
internal_default_instance()
static const LaserScan* internal_default_instance () inline static
References ignition::msgs::_LaserScan_default_instance_.
Referenced by LaserScan::has_header(), and LaserScan::has_world_pose().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const LaserScan & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_frame()
std::string * mutable_frame () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_intensities()
google::protobuf::RepeatedField< double > * mutable_intensities () inline
mutable_ranges()
google::protobuf::RepeatedField< double > * mutable_ranges () inline
mutable_world_pose()
ignition::msgs::Pose * mutable_world_pose () inline
New() [1/2]
LaserScan* New () const inline final
New() [2/2]
LaserScan* New (::google::protobuf::Arena * arena) const inline final
operator=()
LaserScan& operator= (const LaserScan & from) inline
range_max()
double range_max () const inline
range_min()
double range_min () const inline
ranges() [1/2]
const ::google::protobuf::RepeatedField< double > & ranges () const inline
ranges() [2/2]
double ranges (int index) const inline
ranges_size()
int ranges_size () const inline
release_frame()
std::string * release_frame () inline
release_header()
ignition::msgs::Header * release_header () inline
release_world_pose()
ignition::msgs::Pose * release_world_pose () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_frame()
void set_allocated_frame (::std::string * frame) inline
References LaserScan::frame().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References LaserScan::header().
set_allocated_world_pose()
void set_allocated_world_pose (::ignition::msgs::Pose * world_pose) inline
References LaserScan::world_pose().
set_angle_max()
void set_angle_max (double value) inline
set_angle_min()
void set_angle_min (double value) inline
set_angle_step()
void set_angle_step (double value) inline
set_count()
void set_count (::google::protobuf::uint32 value) inline
set_frame() [1/3]
void set_frame (const ::std::string & value) inline
set_frame() [2/3]
void set_frame (const char * value) inline
set_frame() [3/3]
void set_frame (const char * value, size_t size) inline
set_intensities()
void set_intensities (int index, double value) inline
set_range_max()
void set_range_max (double value) inline
set_range_min()
void set_range_min (double value) inline
set_ranges()
void set_ranges (int index, double value) inline
set_vertical_angle_max()
void set_vertical_angle_max (double value) inline
set_vertical_angle_min()
void set_vertical_angle_min (double value) inline
set_vertical_angle_step()
void set_vertical_angle_step (double value) inline
set_vertical_count()
void set_vertical_count (::google::protobuf::uint32 value) inline
Swap()
void Swap (LaserScan * other)
vertical_angle_max()
double vertical_angle_max () const inline
vertical_angle_min()
double vertical_angle_min () const inline
vertical_angle_step()
double vertical_angle_step () const inline
vertical_count()
google::protobuf::uint32 vertical_count () const inline
world_pose()
const ::ignition::msgs::Pose & world_pose () const inline
References ignition::msgs::_Pose_default_instance_.
Referenced by LaserScan::set_allocated_world_pose().
Member Data Documentation
kAngleMaxFieldNumber
const int kAngleMaxFieldNumber = 5 static
kAngleMinFieldNumber
const int kAngleMinFieldNumber = 4 static
kAngleStepFieldNumber
const int kAngleStepFieldNumber = 6 static
kCountFieldNumber
const int kCountFieldNumber = 9 static
kFrameFieldNumber
const int kFrameFieldNumber = 2 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kIntensitiesFieldNumber
const int kIntensitiesFieldNumber = 15 static
kRangeMaxFieldNumber
const int kRangeMaxFieldNumber = 8 static
kRangeMinFieldNumber
const int kRangeMinFieldNumber = 7 static
kRangesFieldNumber
const int kRangesFieldNumber = 14 static
kVerticalAngleMaxFieldNumber
const int kVerticalAngleMaxFieldNumber = 11 static
kVerticalAngleMinFieldNumber
const int kVerticalAngleMinFieldNumber = 10 static
kVerticalAngleStepFieldNumber
const int kVerticalAngleStepFieldNumber = 12 static
kVerticalCountFieldNumber
const int kVerticalCountFieldNumber = 13 static
kWorldPoseFieldNumber
const int kWorldPoseFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/laserscan.pb.h