Gazebo Msgs: Marker Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Marker Class Reference
#include <marker.pb.h>
Public Types
typedef Marker_Action Action
typedef Marker_Type Type
typedef Marker_Visibility Visibility
Public Member Functions
Marker ()
Marker (const Marker &from)
virtual ~Marker ()
::ignition::msgs::Marker_Action action () const
::ignition::msgs::Vector3d * add_point ()
size_t ByteSizeLong () const final
void Clear () final
void clear_action ()
void clear_header ()
void clear_id ()
void clear_layer ()
void clear_lifetime ()
void clear_material ()
void clear_ns ()
void clear_parent ()
void clear_point ()
void clear_pose ()
void clear_scale ()
void clear_text ()
void clear_type ()
void clear_visibility ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Marker &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_lifetime () const
bool has_material () const
bool has_pose () const
bool has_scale () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint64 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
::google::protobuf::int32 layer () const
const ::ignition::msgs::Time & lifetime () const
const ::ignition::msgs::Material & material () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Marker &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::Time * mutable_lifetime ()
::ignition::msgs::Material * mutable_material ()
::std::string * mutable_ns ()
::std::string * mutable_parent ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Vector3d > * mutable_point ()
::ignition::msgs::Vector3d * mutable_point (int index)
::ignition::msgs::Pose * mutable_pose ()
::ignition::msgs::Vector3d * mutable_scale ()
::std::string * mutable_text ()
Marker * New () const final
Marker * New (::google::protobuf::Arena *arena) const final
const ::std::string & ns () const
Marker & operator= (const Marker &from)
const ::std::string & parent () const
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Vector3d > & point () const
const ::ignition::msgs::Vector3d & point (int index) const
int point_size () const
const ::ignition::msgs::Pose & pose () const
::ignition::msgs::Header * release_header ()
::ignition::msgs::Time * release_lifetime ()
::ignition::msgs::Material * release_material ()
::std::string * release_ns ()
::std::string * release_parent ()
::ignition::msgs::Pose * release_pose ()
::ignition::msgs::Vector3d * release_scale ()
::std::string * release_text ()
const ::ignition::msgs::Vector3d & scale () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_action (::ignition::msgs::Marker_Action value)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_lifetime (::ignition::msgs::Time *lifetime)
void set_allocated_material (::ignition::msgs::Material *material)
void set_allocated_ns (::std::string *ns)
void set_allocated_parent (::std::string *parent)
void set_allocated_pose (::ignition::msgs::Pose *pose)
void set_allocated_scale (::ignition::msgs::Vector3d *scale)
void set_allocated_text (::std::string *text)
void set_id (::google::protobuf::uint64 value)
void set_layer (::google::protobuf::int32 value)
void set_ns (const ::std::string &value)
void set_ns (const char *value)
void set_ns (const char *value, size_t size)
void set_parent (const ::std::string &value)
void set_parent (const char *value)
void set_parent (const char *value, size_t size)
void set_text (const ::std::string &value)
void set_text (const char *value)
void set_text (const char *value, size_t size)
void set_type (::ignition::msgs::Marker_Type value)
void set_visibility (::ignition::msgs::Marker_Visibility value)
void Swap (Marker *other)
const ::std::string & text () const
::ignition::msgs::Marker_Type type () const
::ignition::msgs::Marker_Visibility visibility () const
Static Public Member Functions
static const ::google::protobuf::EnumDescriptor * Action_descriptor ()
static bool Action_IsValid (int value)
static const ::std::string & Action_Name (Action value)
static bool Action_Parse (const ::std::string &name, Action *value)
static const Marker & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Marker * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
static const ::google::protobuf::EnumDescriptor * Visibility_descriptor ()
static bool Visibility_IsValid (int value)
static const ::std::string & Visibility_Name (Visibility value)
static bool Visibility_Parse (const ::std::string &name, Visibility *value)
Static Public Attributes
static const int Action_ARRAYSIZE
static const Action Action_MAX
static const Action Action_MIN
static const Action ADD_MODIFY
static const Visibility ALL
static const Type ARROW
static const Type AXIS
static const Type BOX
static const Type CAPSULE
static const Type CONE
static const Type CYLINDER
static const Action DELETE_ALL
static const Action DELETE_MARKER
static const Type ELLIPSOID
static const Visibility GUI
static const int kActionFieldNumber = 2
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 4
static constexpr int kIndexInFileMessages
static const int kLayerFieldNumber = 5
static const int kLifetimeFieldNumber = 7
static const int kMaterialFieldNumber = 10
static const int kNsFieldNumber = 3
static const int kParentFieldNumber = 13
static const int kPointFieldNumber = 11
static const int kPoseFieldNumber = 8
static const int kScaleFieldNumber = 9
static const int kTextFieldNumber = 12
static const int kTypeFieldNumber = 6
static const int kVisibilityFieldNumber = 14
static const Type LINE_LIST
static const Type LINE_STRIP
static const Type NONE
static const Type POINTS
static const Type SPHERE
static const Type TEXT
static const Type TRIANGLE_FAN
static const Type TRIANGLE_LIST
static const Type TRIANGLE_STRIP
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
static const int Visibility_ARRAYSIZE
static const Visibility Visibility_MAX
static const Visibility Visibility_MIN
Member Typedef Documentation
Action
typedef Marker_Action Action
Type
typedef Marker_Type Type
Visibility
typedef Marker_Visibility Visibility
Constructor & Destructor Documentation
Marker() [1/2]
Marker ()
~Marker()
virtual ~Marker () virtual
Marker() [2/2]
Marker (const Marker & from)
Member Function Documentation
action()
ignition::msgs::Marker_Action action () const inline
Action_descriptor()
static const ::google::protobuf::EnumDescriptor* Action_descriptor () inline static
References ignition::msgs::Marker_Action_descriptor().
Action_IsValid()
static bool Action_IsValid (int value) inline static
References ignition::msgs::Marker_Action_IsValid().
Action_Name()
static const ::std::string& Action_Name (Action value) inline static
References ignition::msgs::Marker_Action_Name().
Action_Parse()
static bool Action_Parse (const ::std::string & name, Action * value) inline static
References ignition::msgs::Marker_Action_Parse().
add_point()
ignition::msgs::Vector3d * add_point () inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_action()
void clear_action () inline
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_layer()
void clear_layer () inline
clear_lifetime()
void clear_lifetime ()
clear_material()
void clear_material ()
clear_ns()
void clear_ns () inline
clear_parent()
void clear_parent () inline
clear_point()
void clear_point ()
clear_pose()
void clear_pose ()
clear_scale()
void clear_scale ()
clear_text()
void clear_text () inline
clear_type()
void clear_type () inline
clear_visibility()
void clear_visibility () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Marker & from)
default_instance()
static const Marker& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Marker::internal_default_instance().
has_lifetime()
bool has_lifetime () const inline
References Marker::internal_default_instance().
has_material()
bool has_material () const inline
References Marker::internal_default_instance().
has_pose()
bool has_pose () const inline
References Marker::internal_default_instance().
has_scale()
bool has_scale () const inline
References Marker::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Marker::set_allocated_header().
id()
google::protobuf::uint64 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Marker* internal_default_instance () inline static
References ignition::msgs::_Marker_default_instance_.
Referenced by Marker::has_header(), Marker::has_lifetime(), Marker::has_material(), Marker::has_pose(), and Marker::has_scale().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
layer()
google::protobuf::int32 layer () const inline
lifetime()
const ::ignition::msgs::Time & lifetime () const inline
References ignition::msgs::_Time_default_instance_.
Referenced by Marker::set_allocated_lifetime().
material()
const ::ignition::msgs::Material & material () const inline
References ignition::msgs::_Material_default_instance_.
Referenced by Marker::set_allocated_material().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Marker & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_lifetime()
ignition::msgs::Time * mutable_lifetime () inline
mutable_material()
ignition::msgs::Material * mutable_material () inline
mutable_ns()
std::string * mutable_ns () inline
mutable_parent()
std::string * mutable_parent () inline
mutable_point() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Vector3d > * mutable_point () inline
mutable_point() [2/2]
ignition::msgs::Vector3d * mutable_point (int index) inline
mutable_pose()
ignition::msgs::Pose * mutable_pose () inline
mutable_scale()
ignition::msgs::Vector3d * mutable_scale () inline
mutable_text()
std::string * mutable_text () inline
New() [1/2]
Marker* New () const inline final
New() [2/2]
Marker* New (::google::protobuf::Arena * arena) const inline final
ns()
const ::std::string & ns () const inline
Referenced by Marker::set_allocated_ns().
operator=()
Marker& operator= (const Marker & from) inline
parent()
const ::std::string & parent () const inline
Referenced by Marker::set_allocated_parent().
point() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Vector3d > & point () const inline
point() [2/2]
const ::ignition::msgs::Vector3d & point (int index) const inline
point_size()
int point_size () const inline
pose()
const ::ignition::msgs::Pose & pose () const inline
References ignition::msgs::_Pose_default_instance_.
Referenced by Marker::set_allocated_pose().
release_header()
ignition::msgs::Header * release_header () inline
release_lifetime()
ignition::msgs::Time * release_lifetime () inline
release_material()
ignition::msgs::Material * release_material () inline
release_ns()
std::string * release_ns () inline
release_parent()
std::string * release_parent () inline
release_pose()
ignition::msgs::Pose * release_pose () inline
release_scale()
ignition::msgs::Vector3d * release_scale () inline
release_text()
std::string * release_text () inline
scale()
const ::ignition::msgs::Vector3d & scale () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by Marker::set_allocated_scale().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_action()
void set_action (::ignition::msgs::Marker_Action value) inline
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Marker::header().
set_allocated_lifetime()
void set_allocated_lifetime (::ignition::msgs::Time * lifetime) inline
References Marker::lifetime().
set_allocated_material()
void set_allocated_material (::ignition::msgs::Material * material) inline
References Marker::material().
set_allocated_ns()
void set_allocated_ns (::std::string * ns) inline
References Marker::ns().
set_allocated_parent()
void set_allocated_parent (::std::string * parent) inline
References Marker::parent().
set_allocated_pose()
void set_allocated_pose (::ignition::msgs::Pose * pose) inline
References Marker::pose().
set_allocated_scale()
void set_allocated_scale (::ignition::msgs::Vector3d * scale) inline
References Marker::scale().
set_allocated_text()
void set_allocated_text (::std::string * text) inline
References Marker::text().
set_id()
void set_id (::google::protobuf::uint64 value) inline
set_layer()
void set_layer (::google::protobuf::int32 value) inline
set_ns() [1/3]
void set_ns (const ::std::string & value) inline
set_ns() [2/3]
void set_ns (const char * value) inline
set_ns() [3/3]
void set_ns (const char * value, size_t size) inline
set_parent() [1/3]
void set_parent (const ::std::string & value) inline
set_parent() [2/3]
void set_parent (const char * value) inline
set_parent() [3/3]
void set_parent (const char * value, size_t size) inline
set_text() [1/3]
void set_text (const ::std::string & value) inline
set_text() [2/3]
void set_text (const char * value) inline
set_text() [3/3]
void set_text (const char * value, size_t size) inline
set_type()
void set_type (::ignition::msgs::Marker_Type value) inline
set_visibility()
void set_visibility (::ignition::msgs::Marker_Visibility value) inline
Swap()
void Swap (Marker * other)
text()
const ::std::string & text () const inline
Referenced by Marker::set_allocated_text().
type()
ignition::msgs::Marker_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References ignition::msgs::Marker_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References ignition::msgs::Marker_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References ignition::msgs::Marker_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References ignition::msgs::Marker_Type_Parse().
visibility()
ignition::msgs::Marker_Visibility visibility () const inline
Visibility_descriptor()
static const ::google::protobuf::EnumDescriptor* Visibility_descriptor () inline static
References ignition::msgs::Marker_Visibility_descriptor().
Visibility_IsValid()
static bool Visibility_IsValid (int value) inline static
References ignition::msgs::Marker_Visibility_IsValid().
Visibility_Name()
static const ::std::string& Visibility_Name (Visibility value) inline static
References ignition::msgs::Marker_Visibility_Name().
Visibility_Parse()
static bool Visibility_Parse (const ::std::string & name, Visibility * value) inline static
References ignition::msgs::Marker_Visibility_Parse().
Member Data Documentation
Action_ARRAYSIZE
const int Action_ARRAYSIZE static
Initial value:
=
    Marker_Action_Action_ARRAYSIZE
Action_MAX
const Action Action_MAX static
Initial value:
=
    Marker_Action_Action_MAX
Action_MIN
const Action Action_MIN static
Initial value:
=
    Marker_Action_Action_MIN
ADD_MODIFY
const Action ADD_MODIFY static
Initial value:
=
    Marker_Action_ADD_MODIFY
ALL
const Visibility ALL static
Initial value:
=
    Marker_Visibility_ALL
ARROW
const Type ARROW static
Initial value:
=
    Marker_Type_ARROW
AXIS
const Type AXIS static
Initial value:
=
    Marker_Type_AXIS
BOX
const Type BOX static
Initial value:
=
    Marker_Type_BOX
CAPSULE
const Type CAPSULE static
Initial value:
=
    Marker_Type_CAPSULE
CONE
const Type CONE static
Initial value:
=
    Marker_Type_CONE
CYLINDER
const Type CYLINDER static
Initial value:
=
    Marker_Type_CYLINDER
DELETE_ALL
const Action DELETE_ALL static
Initial value:
=
    Marker_Action_DELETE_ALL
DELETE_MARKER
const Action DELETE_MARKER static
Initial value:
=
    Marker_Action_DELETE_MARKER
ELLIPSOID
const Type ELLIPSOID static
Initial value:
=
    Marker_Type_ELLIPSOID
GUI
const Visibility GUI static
Initial value:
=
    Marker_Visibility_GUI
kActionFieldNumber
const int kActionFieldNumber = 2 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 4 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLayerFieldNumber
const int kLayerFieldNumber = 5 static
kLifetimeFieldNumber
const int kLifetimeFieldNumber = 7 static
kMaterialFieldNumber
const int kMaterialFieldNumber = 10 static
kNsFieldNumber
const int kNsFieldNumber = 3 static
kParentFieldNumber
const int kParentFieldNumber = 13 static
kPointFieldNumber
const int kPointFieldNumber = 11 static
kPoseFieldNumber
const int kPoseFieldNumber = 8 static
kScaleFieldNumber
const int kScaleFieldNumber = 9 static
kTextFieldNumber
const int kTextFieldNumber = 12 static
kTypeFieldNumber
const int kTypeFieldNumber = 6 static
kVisibilityFieldNumber
const int kVisibilityFieldNumber = 14 static
LINE_LIST
const Type LINE_LIST static
Initial value:
=
    Marker_Type_LINE_LIST
LINE_STRIP
const Type LINE_STRIP static
Initial value:
=
    Marker_Type_LINE_STRIP
NONE
const Type NONE static
Initial value:
=
    Marker_Type_NONE
POINTS
const Type POINTS static
Initial value:
=
    Marker_Type_POINTS
SPHERE
const Type SPHERE static
Initial value:
=
    Marker_Type_SPHERE
TEXT
const Type TEXT static
Initial value:
=
    Marker_Type_TEXT
TRIANGLE_FAN
const Type TRIANGLE_FAN static
Initial value:
=
    Marker_Type_TRIANGLE_FAN
TRIANGLE_LIST
const Type TRIANGLE_LIST static
Initial value:
=
    Marker_Type_TRIANGLE_LIST
TRIANGLE_STRIP
const Type TRIANGLE_STRIP static
Initial value:
=
    Marker_Type_TRIANGLE_STRIP
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    Marker_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    Marker_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    Marker_Type_Type_MIN
Visibility_ARRAYSIZE
const int Visibility_ARRAYSIZE static
Initial value:
=
    Marker_Visibility_Visibility_ARRAYSIZE
Visibility_MAX
const Visibility Visibility_MAX static
Initial value:
=
    Marker_Visibility_Visibility_MAX
Visibility_MIN
const Visibility Visibility_MIN static
Initial value:
=
    Marker_Visibility_Visibility_MIN
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/marker.pb.h