Gazebo Msgs: Dataframe Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Dataframe Class Reference
#include <dataframe.pb.h>
Public Member Functions
Dataframe ()
Dataframe (const Dataframe &from)
virtual ~Dataframe ()
size_t ByteSizeLong () const final
void Clear () final
void clear_data ()
void clear_dst_address ()
void clear_header ()
void clear_src_address ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Dataframe &from)
const ::std::string & data () const
const ::std::string & dst_address () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Dataframe &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_data ()
::std::string * mutable_dst_address ()
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_src_address ()
Dataframe * New () const final
Dataframe * New (::google::protobuf::Arena *arena) const final
Dataframe & operator= (const Dataframe &from)
::std::string * release_data ()
::std::string * release_dst_address ()
::ignition::msgs::Header * release_header ()
::std::string * release_src_address ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_data (::std::string *data)
void set_allocated_dst_address (::std::string *dst_address)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_src_address (::std::string *src_address)
void set_data (const ::std::string &value)
void set_data (const char *value)
void set_data (const void *value, size_t size)
void set_dst_address (const ::std::string &value)
void set_dst_address (const char *value)
void set_dst_address (const char *value, size_t size)
void set_src_address (const ::std::string &value)
void set_src_address (const char *value)
void set_src_address (const char *value, size_t size)
const ::std::string & src_address () const
void Swap (Dataframe *other)
Static Public Member Functions
static const Dataframe & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Dataframe * internal_default_instance ()
Static Public Attributes
static const int kDataFieldNumber = 4
static const int kDstAddressFieldNumber = 3
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kSrcAddressFieldNumber = 2
Constructor & Destructor Documentation
Dataframe() [1/2]
Dataframe ()
~Dataframe()
virtual ~Dataframe () virtual
Dataframe() [2/2]
Dataframe (const Dataframe & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_data()
void clear_data () inline
clear_dst_address()
void clear_dst_address () inline
clear_header()
void clear_header ()
clear_src_address()
void clear_src_address () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Dataframe & from)
data()
const ::std::string & data () const inline
Referenced by Dataframe::set_allocated_data().
default_instance()
static const Dataframe& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
dst_address()
const ::std::string & dst_address () const inline
Referenced by Dataframe::set_allocated_dst_address().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Dataframe::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Dataframe::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Dataframe* internal_default_instance () inline static
References ignition::msgs::_Dataframe_default_instance_.
Referenced by Dataframe::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Dataframe & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_data()
std::string * mutable_data () inline
mutable_dst_address()
std::string * mutable_dst_address () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_src_address()
std::string * mutable_src_address () inline
New() [1/2]
Dataframe* New () const inline final
New() [2/2]
Dataframe* New (::google::protobuf::Arena * arena) const inline final
operator=()
Dataframe& operator= (const Dataframe & from) inline
release_data()
std::string * release_data () inline
release_dst_address()
std::string * release_dst_address () inline
release_header()
ignition::msgs::Header * release_header () inline
release_src_address()
std::string * release_src_address () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_data()
void set_allocated_data (::std::string * data) inline
References Dataframe::data().
set_allocated_dst_address()
void set_allocated_dst_address (::std::string * dst_address) inline
References Dataframe::dst_address().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Dataframe::header().
set_allocated_src_address()
void set_allocated_src_address (::std::string * src_address) inline
References Dataframe::src_address().
set_data() [1/3]
void set_data (const ::std::string & value) inline
set_data() [2/3]
void set_data (const char * value) inline
set_data() [3/3]
void set_data (const void * value, size_t size) inline
set_dst_address() [1/3]
void set_dst_address (const ::std::string & value) inline
set_dst_address() [2/3]
void set_dst_address (const char * value) inline
set_dst_address() [3/3]
void set_dst_address (const char * value, size_t size) inline
set_src_address() [1/3]
void set_src_address (const ::std::string & value) inline
set_src_address() [2/3]
void set_src_address (const char * value) inline
set_src_address() [3/3]
void set_src_address (const char * value, size_t size) inline
src_address()
const ::std::string & src_address () const inline
Referenced by Dataframe::set_allocated_src_address().
Swap()
void Swap (Dataframe * other)
Member Data Documentation
kDataFieldNumber
const int kDataFieldNumber = 4 static
kDstAddressFieldNumber
const int kDstAddressFieldNumber = 3 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kSrcAddressFieldNumber
const int kSrcAddressFieldNumber = 2 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/dataframe.pb.h