Gazebo Msgs: Any Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Any Class Reference
#include <any.pb.h>
Public Types
enum ValueCase {
kDoubleValue = 3, kIntValue = 4, kStringValue = 5, kBoolValue = 6,
kVector3DValue = 7, kColorValue = 8, kPose3DValue = 9, kQuaternionValue = 10,
kTimeValue = 11, VALUE_NOT_SET = 0
}
typedef Any_ValueType ValueType
Public Member Functions
Any ()
Any (const Any &from)
virtual ~Any ()
bool bool_value () const
size_t ByteSizeLong () const final
void Clear () final
void clear_bool_value ()
void clear_color_value ()
void clear_double_value ()
void clear_header ()
void clear_int_value ()
void clear_pose3d_value ()
void clear_quaternion_value ()
void clear_string_value ()
void clear_time_value ()
void clear_type ()
void clear_value ()
void clear_vector3d_value ()
const ::ignition::msgs::Color & color_value () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Any &from)
double double_value () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_color_value () const
bool has_header () const
bool has_pose3d_value () const
bool has_quaternion_value () const
bool has_time_value () const
bool has_vector3d_value () const
const ::ignition::msgs::Header & header () const
::google::protobuf::int32 int_value () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Any &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Color * mutable_color_value ()
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::Pose * mutable_pose3d_value ()
::ignition::msgs::Quaternion * mutable_quaternion_value ()
::std::string * mutable_string_value ()
::ignition::msgs::Time * mutable_time_value ()
::ignition::msgs::Vector3d * mutable_vector3d_value ()
Any * New () const final
Any * New (::google::protobuf::Arena *arena) const final
Any & operator= (const Any &from)
const ::ignition::msgs::Pose & pose3d_value () const
const ::ignition::msgs::Quaternion & quaternion_value () const
::ignition::msgs::Color * release_color_value ()
::ignition::msgs::Header * release_header ()
::ignition::msgs::Pose * release_pose3d_value ()
::ignition::msgs::Quaternion * release_quaternion_value ()
::std::string * release_string_value ()
::ignition::msgs::Time * release_time_value ()
::ignition::msgs::Vector3d * release_vector3d_value ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_color_value (::ignition::msgs::Color *color_value)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_pose3d_value (::ignition::msgs::Pose *pose3d_value)
void set_allocated_quaternion_value (::ignition::msgs::Quaternion *quaternion_value)
void set_allocated_string_value (::std::string *string_value)
void set_allocated_time_value (::ignition::msgs::Time *time_value)
void set_allocated_vector3d_value (::ignition::msgs::Vector3d *vector3d_value)
void set_bool_value (bool value)
void set_double_value (double value)
void set_int_value (::google::protobuf::int32 value)
void set_string_value (const ::std::string &value)
void set_string_value (const char *value)
void set_string_value (const char *value, size_t size)
void set_type (::ignition::msgs::Any_ValueType value)
const ::std::string & string_value () const
void Swap (Any *other)
const ::ignition::msgs::Time & time_value () const
::ignition::msgs::Any_ValueType type () const
ValueCase value_case () const
const ::ignition::msgs::Vector3d & vector3d_value () const
Static Public Member Functions
static const Any & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Any * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * ValueType_descriptor ()
static bool ValueType_IsValid (int value)
static const ::std::string & ValueType_Name (ValueType value)
static bool ValueType_Parse (const ::std::string &name, ValueType *value)
Static Public Attributes
static const ValueType BOOLEAN
static const ValueType COLOR
static const ValueType DOUBLE
static const ValueType INT32
static const int kBoolValueFieldNumber = 6
static const int kColorValueFieldNumber = 8
static const int kDoubleValueFieldNumber = 3
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kIntValueFieldNumber = 4
static const int kPose3DValueFieldNumber = 9
static const int kQuaternionValueFieldNumber = 10
static const int kStringValueFieldNumber = 5
static const int kTimeValueFieldNumber = 11
static const int kTypeFieldNumber = 2
static const int kVector3DValueFieldNumber = 7
static const ValueType NONE
static const ValueType POSE3D
static const ValueType QUATERNIOND
static const ValueType STRING
static const ValueType TIME
static const int ValueType_ARRAYSIZE
static const ValueType ValueType_MAX
static const ValueType ValueType_MIN
static const ValueType VECTOR3D
Member Typedef Documentation
ValueType
typedef Any_ValueType ValueType
Member Enumeration Documentation
ValueCase
enum ValueCase
Enumerator
kDoubleValue
kIntValue
kStringValue
kBoolValue
kVector3DValue
kColorValue
kPose3DValue
kQuaternionValue
kTimeValue
VALUE_NOT_SET
Constructor & Destructor Documentation
Any() [1/2]
Any ()
~Any()
virtual ~Any () virtual
Any() [2/2]
Any (const Any & from)
Member Function Documentation
bool_value()
bool bool_value () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_bool_value()
void clear_bool_value () inline
clear_color_value()
void clear_color_value ()
clear_double_value()
void clear_double_value () inline
clear_header()
void clear_header ()
clear_int_value()
void clear_int_value () inline
clear_pose3d_value()
void clear_pose3d_value ()
clear_quaternion_value()
void clear_quaternion_value ()
clear_string_value()
void clear_string_value () inline
clear_time_value()
void clear_time_value ()
clear_type()
void clear_type () inline
clear_value()
void clear_value ()
Referenced by Any::mutable_color_value(), Any::mutable_pose3d_value(), Any::mutable_quaternion_value(), Any::mutable_string_value(), Any::mutable_time_value(), Any::mutable_vector3d_value(), Any::set_allocated_string_value(), Any::set_bool_value(), Any::set_double_value(), Any::set_int_value(), and Any::set_string_value().
clear_vector3d_value()
void clear_vector3d_value ()
color_value()
const ::ignition::msgs::Color & color_value () const inline
References ignition::msgs::_Color_default_instance_, and Any::has_color_value().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Any & from)
default_instance()
static const Any& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
double_value()
double double_value () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_color_value()
bool has_color_value () const inline
References Any::kColorValue, and Any::value_case().
Referenced by Any::color_value(), Any::mutable_color_value(), and Any::release_color_value().
has_header()
bool has_header () const inline
References Any::internal_default_instance().
has_pose3d_value()
bool has_pose3d_value () const inline
References Any::kPose3DValue, and Any::value_case().
Referenced by Any::mutable_pose3d_value(), Any::pose3d_value(), and Any::release_pose3d_value().
has_quaternion_value()
bool has_quaternion_value () const inline
References Any::kQuaternionValue, and Any::value_case().
Referenced by Any::mutable_quaternion_value(), Any::quaternion_value(), and Any::release_quaternion_value().
has_time_value()
bool has_time_value () const inline
References Any::kTimeValue, and Any::value_case().
Referenced by Any::mutable_time_value(), Any::release_time_value(), and Any::time_value().
has_vector3d_value()
bool has_vector3d_value () const inline
References Any::kVector3DValue, and Any::value_case().
Referenced by Any::mutable_vector3d_value(), Any::release_vector3d_value(), and Any::vector3d_value().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Any::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
int_value()
google::protobuf::int32 int_value () const inline
internal_default_instance()
static const Any* internal_default_instance () inline static
References ignition::msgs::_Any_default_instance_.
Referenced by Any::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Any & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_color_value()
ignition::msgs::Color * mutable_color_value () inline
References Any::clear_value(), and Any::has_color_value().
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_pose3d_value()
ignition::msgs::Pose * mutable_pose3d_value () inline
References Any::clear_value(), and Any::has_pose3d_value().
mutable_quaternion_value()
ignition::msgs::Quaternion * mutable_quaternion_value () inline
References Any::clear_value(), and Any::has_quaternion_value().
mutable_string_value()
std::string * mutable_string_value () inline
References Any::clear_value().
mutable_time_value()
ignition::msgs::Time * mutable_time_value () inline
References Any::clear_value(), and Any::has_time_value().
mutable_vector3d_value()
ignition::msgs::Vector3d * mutable_vector3d_value () inline
References Any::clear_value(), and Any::has_vector3d_value().
New() [1/2]
Any* New () const inline final
New() [2/2]
Any* New (::google::protobuf::Arena * arena) const inline final
operator=()
Any& operator= (const Any & from) inline
pose3d_value()
const ::ignition::msgs::Pose & pose3d_value () const inline
References ignition::msgs::_Pose_default_instance_, and Any::has_pose3d_value().
quaternion_value()
const ::ignition::msgs::Quaternion & quaternion_value () const inline
References ignition::msgs::_Quaternion_default_instance_, and Any::has_quaternion_value().
release_color_value()
ignition::msgs::Color * release_color_value () inline
References Any::has_color_value().
release_header()
ignition::msgs::Header * release_header () inline
release_pose3d_value()
ignition::msgs::Pose * release_pose3d_value () inline
References Any::has_pose3d_value().
release_quaternion_value()
ignition::msgs::Quaternion * release_quaternion_value () inline
References Any::has_quaternion_value().
release_string_value()
std::string * release_string_value () inline
release_time_value()
ignition::msgs::Time * release_time_value () inline
References Any::has_time_value().
release_vector3d_value()
ignition::msgs::Vector3d * release_vector3d_value () inline
References Any::has_vector3d_value().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_color_value()
void set_allocated_color_value (::ignition::msgs::Color * color_value)
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Any::header().
set_allocated_pose3d_value()
void set_allocated_pose3d_value (::ignition::msgs::Pose * pose3d_value)
set_allocated_quaternion_value()
void set_allocated_quaternion_value (::ignition::msgs::Quaternion * quaternion_value)
set_allocated_string_value()
void set_allocated_string_value (::std::string * string_value) inline
References Any::clear_value(), and Any::string_value().
set_allocated_time_value()
void set_allocated_time_value (::ignition::msgs::Time * time_value)
set_allocated_vector3d_value()
void set_allocated_vector3d_value (::ignition::msgs::Vector3d * vector3d_value)
set_bool_value()
void set_bool_value (bool value) inline
References Any::clear_value().
set_double_value()
void set_double_value (double value) inline
References Any::clear_value().
set_int_value()
void set_int_value (::google::protobuf::int32 value) inline
References Any::clear_value().
set_string_value() [1/3]
void set_string_value (const ::std::string & value) inline
References Any::clear_value().
set_string_value() [2/3]
void set_string_value (const char * value) inline
References Any::clear_value().
set_string_value() [3/3]
void set_string_value (const char * value, size_t size) inline
References Any::clear_value().
set_type()
void set_type (::ignition::msgs::Any_ValueType value) inline
string_value()
const ::std::string & string_value () const inline
Referenced by Any::set_allocated_string_value().
Swap()
void Swap (Any * other)
time_value()
const ::ignition::msgs::Time & time_value () const inline
References ignition::msgs::_Time_default_instance_, and Any::has_time_value().
type()
ignition::msgs::Any_ValueType type () const inline
value_case()
Any::ValueCase value_case () const inline
Referenced by Any::has_color_value(), Any::has_pose3d_value(), Any::has_quaternion_value(), Any::has_time_value(), and Any::has_vector3d_value().
ValueType_descriptor()
static const ::google::protobuf::EnumDescriptor* ValueType_descriptor () inline static
References ignition::msgs::Any_ValueType_descriptor().
ValueType_IsValid()
static bool ValueType_IsValid (int value) inline static
References ignition::msgs::Any_ValueType_IsValid().
ValueType_Name()
static const ::std::string& ValueType_Name (ValueType value) inline static
References ignition::msgs::Any_ValueType_Name().
ValueType_Parse()
static bool ValueType_Parse (const ::std::string & name, ValueType * value) inline static
References ignition::msgs::Any_ValueType_Parse().
vector3d_value()
const ::ignition::msgs::Vector3d & vector3d_value () const inline
References ignition::msgs::_Vector3d_default_instance_, and Any::has_vector3d_value().
Member Data Documentation
BOOLEAN
const ValueType BOOLEAN static
Initial value:
=
    Any_ValueType_BOOLEAN
COLOR
const ValueType COLOR static
Initial value:
=
    Any_ValueType_COLOR
DOUBLE
const ValueType DOUBLE static
Initial value:
=
    Any_ValueType_DOUBLE
INT32
const ValueType INT32 static
Initial value:
=
    Any_ValueType_INT32
kBoolValueFieldNumber
const int kBoolValueFieldNumber = 6 static
kColorValueFieldNumber
const int kColorValueFieldNumber = 8 static
kDoubleValueFieldNumber
const int kDoubleValueFieldNumber = 3 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kIntValueFieldNumber
const int kIntValueFieldNumber = 4 static
kPose3DValueFieldNumber
const int kPose3DValueFieldNumber = 9 static
kQuaternionValueFieldNumber
const int kQuaternionValueFieldNumber = 10 static
kStringValueFieldNumber
const int kStringValueFieldNumber = 5 static
kTimeValueFieldNumber
const int kTimeValueFieldNumber = 11 static
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
kVector3DValueFieldNumber
const int kVector3DValueFieldNumber = 7 static
NONE
const ValueType NONE static
Initial value:
=
    Any_ValueType_NONE
POSE3D
const ValueType POSE3D static
Initial value:
=
    Any_ValueType_POSE3D
QUATERNIOND
const ValueType QUATERNIOND static
Initial value:
=
    Any_ValueType_QUATERNIOND
STRING
const ValueType STRING static
Initial value:
=
    Any_ValueType_STRING
TIME
const ValueType TIME static
Initial value:
=
    Any_ValueType_TIME
ValueType_ARRAYSIZE
const int ValueType_ARRAYSIZE static
Initial value:
=
    Any_ValueType_ValueType_ARRAYSIZE
ValueType_MAX
const ValueType ValueType_MAX static
Initial value:
=
    Any_ValueType_ValueType_MAX
ValueType_MIN
const ValueType ValueType_MIN static
Initial value:
=
    Any_ValueType_ValueType_MIN
VECTOR3D
const ValueType VECTOR3D static
Initial value:
=
    Any_ValueType_VECTOR3D
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/any.pb.h