Gazebo Msgs: TrackVisual Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
TrackVisual Class Reference
#include <track_visual.pb.h>
Public Member Functions
TrackVisual ()
TrackVisual (const TrackVisual &from)
virtual ~TrackVisual ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_id ()
void clear_inherit_orientation ()
void clear_inherit_yaw ()
void clear_max_dist ()
void clear_min_dist ()
void clear_name ()
void clear_static_ ()
void clear_use_model_frame ()
void clear_xyz ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const TrackVisual &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_xyz () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
bool inherit_orientation () const
bool inherit_yaw () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
double max_dist () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const TrackVisual &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
double min_dist () const
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_name ()
::ignition::msgs::Vector3d * mutable_xyz ()
const ::std::string & name () const
TrackVisual * New () const final
TrackVisual * New (::google::protobuf::Arena *arena) const final
TrackVisual & operator= (const TrackVisual &from)
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
::ignition::msgs::Vector3d * release_xyz ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_xyz (::ignition::msgs::Vector3d *xyz)
void set_id (::google::protobuf::uint32 value)
void set_inherit_orientation (bool value)
void set_inherit_yaw (bool value)
void set_max_dist (double value)
void set_min_dist (double value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_static_ (bool value)
void set_use_model_frame (bool value)
bool static_ () const
void Swap (TrackVisual *other)
bool use_model_frame () const
const ::ignition::msgs::Vector3d & xyz () const
Static Public Member Functions
static const TrackVisual & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const TrackVisual * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kInheritOrientationFieldNumber = 4
static const int kInheritYawFieldNumber = 10
static const int kMaxDistFieldNumber = 6
static const int kMinDistFieldNumber = 5
static const int kNameFieldNumber = 2
static const int kStaticFieldNumber = 7
static const int kUseModelFrameFieldNumber = 8
static const int kXyzFieldNumber = 9
Constructor & Destructor Documentation
TrackVisual() [1/2]
TrackVisual ()
~TrackVisual()
virtual ~TrackVisual () virtual
TrackVisual() [2/2]
TrackVisual (const TrackVisual & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_inherit_orientation()
void clear_inherit_orientation () inline
clear_inherit_yaw()
void clear_inherit_yaw () inline
clear_max_dist()
void clear_max_dist () inline
clear_min_dist()
void clear_min_dist () inline
clear_name()
void clear_name () inline
clear_static_()
void clear_static_ () inline
clear_use_model_frame()
void clear_use_model_frame () inline
clear_xyz()
void clear_xyz ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const TrackVisual & from)
default_instance()
static const TrackVisual& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References TrackVisual::internal_default_instance().
has_xyz()
bool has_xyz () const inline
References TrackVisual::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by TrackVisual::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
inherit_orientation()
bool inherit_orientation () const inline
inherit_yaw()
bool inherit_yaw () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const TrackVisual* internal_default_instance () inline static
References ignition::msgs::_TrackVisual_default_instance_.
Referenced by TrackVisual::has_header(), and TrackVisual::has_xyz().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
max_dist()
double max_dist () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const TrackVisual & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
min_dist()
double min_dist () const inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
mutable_xyz()
ignition::msgs::Vector3d * mutable_xyz () inline
name()
const ::std::string & name () const inline
Referenced by TrackVisual::set_allocated_name().
New() [1/2]
TrackVisual* New () const inline final
New() [2/2]
TrackVisual* New (::google::protobuf::Arena * arena) const inline final
operator=()
TrackVisual& operator= (const TrackVisual & from) inline
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_xyz()
ignition::msgs::Vector3d * release_xyz () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References TrackVisual::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References TrackVisual::name().
set_allocated_xyz()
void set_allocated_xyz (::ignition::msgs::Vector3d * xyz) inline
References TrackVisual::xyz().
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_inherit_orientation()
void set_inherit_orientation (bool value) inline
set_inherit_yaw()
void set_inherit_yaw (bool value) inline
set_max_dist()
void set_max_dist (double value) inline
set_min_dist()
void set_min_dist (double value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_static_()
void set_static_ (bool value) inline
set_use_model_frame()
void set_use_model_frame (bool value) inline
static_()
bool static_ () const inline
Swap()
void Swap (TrackVisual * other)
use_model_frame()
bool use_model_frame () const inline
xyz()
const ::ignition::msgs::Vector3d & xyz () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by TrackVisual::set_allocated_xyz().
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kInheritOrientationFieldNumber
const int kInheritOrientationFieldNumber = 4 static
kInheritYawFieldNumber
const int kInheritYawFieldNumber = 10 static
kMaxDistFieldNumber
const int kMaxDistFieldNumber = 6 static
kMinDistFieldNumber
const int kMinDistFieldNumber = 5 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
kStaticFieldNumber
const int kStaticFieldNumber = 7 static
kUseModelFrameFieldNumber
const int kUseModelFrameFieldNumber = 8 static
kXyzFieldNumber
const int kXyzFieldNumber = 9 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/track_visual.pb.h