Gazebo Msgs: CameraSensor Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
CameraSensor Class Reference
#include <camerasensor.pb.h>
Public Member Functions
CameraSensor ()
CameraSensor (const CameraSensor &from)
virtual ~CameraSensor ()
size_t ByteSizeLong () const final
void Clear () final
void clear_distortion ()
void clear_far_clip ()
void clear_header ()
void clear_horizontal_fov ()
void clear_image_format ()
void clear_image_size ()
void clear_near_clip ()
void clear_save_enabled ()
void clear_save_path ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const CameraSensor &from)
const ::ignition::msgs::Distortion & distortion () const
double far_clip () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_distortion () const
bool has_header () const
bool has_image_size () const
const ::ignition::msgs::Header & header () const
double horizontal_fov () const
const ::std::string & image_format () const
const ::ignition::msgs::Vector2d & image_size () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const CameraSensor &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Distortion * mutable_distortion ()
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_image_format ()
::ignition::msgs::Vector2d * mutable_image_size ()
::std::string * mutable_save_path ()
double near_clip () const
CameraSensor * New () const final
CameraSensor * New (::google::protobuf::Arena *arena) const final
CameraSensor & operator= (const CameraSensor &from)
::ignition::msgs::Distortion * release_distortion ()
::ignition::msgs::Header * release_header ()
::std::string * release_image_format ()
::ignition::msgs::Vector2d * release_image_size ()
::std::string * release_save_path ()
bool save_enabled () const
const ::std::string & save_path () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_distortion (::ignition::msgs::Distortion *distortion)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_image_format (::std::string *image_format)
void set_allocated_image_size (::ignition::msgs::Vector2d *image_size)
void set_allocated_save_path (::std::string *save_path)
void set_far_clip (double value)
void set_horizontal_fov (double value)
void set_image_format (const ::std::string &value)
void set_image_format (const char *value)
void set_image_format (const char *value, size_t size)
void set_near_clip (double value)
void set_save_enabled (bool value)
void set_save_path (const ::std::string &value)
void set_save_path (const char *value)
void set_save_path (const char *value, size_t size)
void Swap (CameraSensor *other)
Static Public Member Functions
static const CameraSensor & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const CameraSensor * internal_default_instance ()
Static Public Attributes
static const int kDistortionFieldNumber = 9
static const int kFarClipFieldNumber = 6
static const int kHeaderFieldNumber = 1
static const int kHorizontalFovFieldNumber = 2
static const int kImageFormatFieldNumber = 4
static const int kImageSizeFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kNearClipFieldNumber = 5
static const int kSaveEnabledFieldNumber = 7
static const int kSavePathFieldNumber = 8
Constructor & Destructor Documentation
CameraSensor() [1/2]
CameraSensor ()
~CameraSensor()
virtual ~CameraSensor () virtual
CameraSensor() [2/2]
CameraSensor (const CameraSensor & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_distortion()
void clear_distortion ()
clear_far_clip()
void clear_far_clip () inline
clear_header()
void clear_header ()
clear_horizontal_fov()
void clear_horizontal_fov () inline
clear_image_format()
void clear_image_format () inline
clear_image_size()
void clear_image_size ()
clear_near_clip()
void clear_near_clip () inline
clear_save_enabled()
void clear_save_enabled () inline
clear_save_path()
void clear_save_path () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const CameraSensor & from)
default_instance()
static const CameraSensor& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
distortion()
const ::ignition::msgs::Distortion & distortion () const inline
References ignition::msgs::_Distortion_default_instance_.
Referenced by CameraSensor::set_allocated_distortion().
far_clip()
double far_clip () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_distortion()
bool has_distortion () const inline
References CameraSensor::internal_default_instance().
has_header()
bool has_header () const inline
References CameraSensor::internal_default_instance().
has_image_size()
bool has_image_size () const inline
References CameraSensor::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by CameraSensor::set_allocated_header().
horizontal_fov()
double horizontal_fov () const inline
image_format()
const ::std::string & image_format () const inline
Referenced by CameraSensor::set_allocated_image_format().
image_size()
const ::ignition::msgs::Vector2d & image_size () const inline
References ignition::msgs::_Vector2d_default_instance_.
Referenced by CameraSensor::set_allocated_image_size().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const CameraSensor* internal_default_instance () inline static
References ignition::msgs::_CameraSensor_default_instance_.
Referenced by CameraSensor::has_distortion(), CameraSensor::has_header(), and CameraSensor::has_image_size().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const CameraSensor & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_distortion()
ignition::msgs::Distortion * mutable_distortion () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_image_format()
std::string * mutable_image_format () inline
mutable_image_size()
ignition::msgs::Vector2d * mutable_image_size () inline
mutable_save_path()
std::string * mutable_save_path () inline
near_clip()
double near_clip () const inline
New() [1/2]
CameraSensor* New () const inline final
New() [2/2]
CameraSensor* New (::google::protobuf::Arena * arena) const inline final
operator=()
CameraSensor& operator= (const CameraSensor & from) inline
release_distortion()
ignition::msgs::Distortion * release_distortion () inline
release_header()
ignition::msgs::Header * release_header () inline
release_image_format()
std::string * release_image_format () inline
release_image_size()
ignition::msgs::Vector2d * release_image_size () inline
release_save_path()
std::string * release_save_path () inline
save_enabled()
bool save_enabled () const inline
save_path()
const ::std::string & save_path () const inline
Referenced by CameraSensor::set_allocated_save_path().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_distortion()
void set_allocated_distortion (::ignition::msgs::Distortion * distortion) inline
References CameraSensor::distortion().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References CameraSensor::header().
set_allocated_image_format()
void set_allocated_image_format (::std::string * image_format) inline
References CameraSensor::image_format().
set_allocated_image_size()
void set_allocated_image_size (::ignition::msgs::Vector2d * image_size) inline
References CameraSensor::image_size().
set_allocated_save_path()
void set_allocated_save_path (::std::string * save_path) inline
References CameraSensor::save_path().
set_far_clip()
void set_far_clip (double value) inline
set_horizontal_fov()
void set_horizontal_fov (double value) inline
set_image_format() [1/3]
void set_image_format (const ::std::string & value) inline
set_image_format() [2/3]
void set_image_format (const char * value) inline
set_image_format() [3/3]
void set_image_format (const char * value, size_t size) inline
set_near_clip()
void set_near_clip (double value) inline
set_save_enabled()
void set_save_enabled (bool value) inline
set_save_path() [1/3]
void set_save_path (const ::std::string & value) inline
set_save_path() [2/3]
void set_save_path (const char * value) inline
set_save_path() [3/3]
void set_save_path (const char * value, size_t size) inline
Swap()
void Swap (CameraSensor * other)
Member Data Documentation
kDistortionFieldNumber
const int kDistortionFieldNumber = 9 static
kFarClipFieldNumber
const int kFarClipFieldNumber = 6 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHorizontalFovFieldNumber
const int kHorizontalFovFieldNumber = 2 static
kImageFormatFieldNumber
const int kImageFormatFieldNumber = 4 static
kImageSizeFieldNumber
const int kImageSizeFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNearClipFieldNumber
const int kNearClipFieldNumber = 5 static
kSaveEnabledFieldNumber
const int kSaveEnabledFieldNumber = 7 static
kSavePathFieldNumber
const int kSavePathFieldNumber = 8 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/camerasensor.pb.h