Gazebo Msgs: Geometry Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Geometry Class Reference
#include <geometry.pb.h>
Public Types
typedef Geometry_Type Type
Public Member Functions
Geometry ()
Geometry (const Geometry &from)
virtual ~Geometry ()
::ignition::msgs::Vector3d * add_points ()
::ignition::msgs::Polyline * add_polyline ()
const ::ignition::msgs::BoxGeom & box () const
size_t ByteSizeLong () const final
const ::ignition::msgs::CapsuleGeom & capsule () const
void Clear () final
void clear_box ()
void clear_capsule ()
void clear_cone ()
void clear_cylinder ()
void clear_ellipsoid ()
void clear_header ()
void clear_heightmap ()
void clear_image ()
void clear_mesh ()
void clear_plane ()
void clear_points ()
void clear_polyline ()
void clear_sphere ()
void clear_type ()
const ::ignition::msgs::ConeGeom & cone () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Geometry &from)
const ::ignition::msgs::CylinderGeom & cylinder () const
const ::ignition::msgs::EllipsoidGeom & ellipsoid () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_box () const
bool has_capsule () const
bool has_cone () const
bool has_cylinder () const
bool has_ellipsoid () const
bool has_header () const
bool has_heightmap () const
bool has_image () const
bool has_mesh () const
bool has_plane () const
bool has_sphere () const
const ::ignition::msgs::Header & header () const
const ::ignition::msgs::HeightmapGeom & heightmap () const
const ::ignition::msgs::ImageGeom & image () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Geometry &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::ignition::msgs::MeshGeom & mesh () const
::ignition::msgs::BoxGeom * mutable_box ()
::ignition::msgs::CapsuleGeom * mutable_capsule ()
::ignition::msgs::ConeGeom * mutable_cone ()
::ignition::msgs::CylinderGeom * mutable_cylinder ()
::ignition::msgs::EllipsoidGeom * mutable_ellipsoid ()
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::HeightmapGeom * mutable_heightmap ()
::ignition::msgs::ImageGeom * mutable_image ()
::ignition::msgs::MeshGeom * mutable_mesh ()
::ignition::msgs::PlaneGeom * mutable_plane ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Vector3d > * mutable_points ()
::ignition::msgs::Vector3d * mutable_points (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Polyline > * mutable_polyline ()
::ignition::msgs::Polyline * mutable_polyline (int index)
::ignition::msgs::SphereGeom * mutable_sphere ()
Geometry * New () const final
Geometry * New (::google::protobuf::Arena *arena) const final
Geometry & operator= (const Geometry &from)
const ::ignition::msgs::PlaneGeom & plane () const
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Vector3d > & points () const
const ::ignition::msgs::Vector3d & points (int index) const
int points_size () const
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Polyline > & polyline () const
const ::ignition::msgs::Polyline & polyline (int index) const
int polyline_size () const
::ignition::msgs::BoxGeom * release_box ()
::ignition::msgs::CapsuleGeom * release_capsule ()
::ignition::msgs::ConeGeom * release_cone ()
::ignition::msgs::CylinderGeom * release_cylinder ()
::ignition::msgs::EllipsoidGeom * release_ellipsoid ()
::ignition::msgs::Header * release_header ()
::ignition::msgs::HeightmapGeom * release_heightmap ()
::ignition::msgs::ImageGeom * release_image ()
::ignition::msgs::MeshGeom * release_mesh ()
::ignition::msgs::PlaneGeom * release_plane ()
::ignition::msgs::SphereGeom * release_sphere ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_box (::ignition::msgs::BoxGeom *box)
void set_allocated_capsule (::ignition::msgs::CapsuleGeom *capsule)
void set_allocated_cone (::ignition::msgs::ConeGeom *cone)
void set_allocated_cylinder (::ignition::msgs::CylinderGeom *cylinder)
void set_allocated_ellipsoid (::ignition::msgs::EllipsoidGeom *ellipsoid)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_heightmap (::ignition::msgs::HeightmapGeom *heightmap)
void set_allocated_image (::ignition::msgs::ImageGeom *image)
void set_allocated_mesh (::ignition::msgs::MeshGeom *mesh)
void set_allocated_plane (::ignition::msgs::PlaneGeom *plane)
void set_allocated_sphere (::ignition::msgs::SphereGeom *sphere)
void set_type (::ignition::msgs::Geometry_Type value)
const ::ignition::msgs::SphereGeom & sphere () const
void Swap (Geometry *other)
::ignition::msgs::Geometry_Type type () const
Static Public Member Functions
static const Geometry & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Geometry * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type ARROW
static const Type AXIS
static const Type BOX
static const Type CAPSULE
static const Type CONE
static const Type CYLINDER
static const Type ELLIPSOID
static const Type EMPTY
static const Type HEIGHTMAP
static const Type IMAGE
static const int kBoxFieldNumber = 3
static const int kCapsuleFieldNumber = 13
static const int kConeFieldNumber = 10
static const int kCylinderFieldNumber = 4
static const int kEllipsoidFieldNumber = 14
static const int kHeaderFieldNumber = 1
static const int kHeightmapFieldNumber = 8
static const int kImageFieldNumber = 7
static constexpr int kIndexInFileMessages
static const int kMeshFieldNumber = 9
static const int kPlaneFieldNumber = 5
static const int kPointsFieldNumber = 11
static const int kPolylineFieldNumber = 12
static const int kSphereFieldNumber = 6
static const int kTypeFieldNumber = 2
static const Type LINE_STRIP
static const Type MESH
static const Type PLANE
static const Type POLYLINE
static const Type SPHERE
static const Type TRIANGLE_FAN
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
Member Typedef Documentation
Type
typedef Geometry_Type Type
Constructor & Destructor Documentation
Geometry() [1/2]
Geometry ()
~Geometry()
virtual ~Geometry () virtual
Geometry() [2/2]
Geometry (const Geometry & from)
Member Function Documentation
add_points()
ignition::msgs::Vector3d * add_points () inline
add_polyline()
ignition::msgs::Polyline * add_polyline () inline
box()
const ::ignition::msgs::BoxGeom & box () const inline
References ignition::msgs::_BoxGeom_default_instance_.
Referenced by Geometry::set_allocated_box().
ByteSizeLong()
size_t ByteSizeLong () const final
capsule()
const ::ignition::msgs::CapsuleGeom & capsule () const inline
References ignition::msgs::_CapsuleGeom_default_instance_.
Referenced by Geometry::set_allocated_capsule().
Clear()
void Clear () final
clear_box()
void clear_box ()
clear_capsule()
void clear_capsule ()
clear_cone()
void clear_cone ()
clear_cylinder()
void clear_cylinder ()
clear_ellipsoid()
void clear_ellipsoid ()
clear_header()
void clear_header ()
clear_heightmap()
void clear_heightmap ()
clear_image()
void clear_image ()
clear_mesh()
void clear_mesh ()
clear_plane()
void clear_plane ()
clear_points()
void clear_points ()
clear_polyline()
void clear_polyline ()
clear_sphere()
void clear_sphere ()
clear_type()
void clear_type () inline
cone()
const ::ignition::msgs::ConeGeom & cone () const inline
References ignition::msgs::_ConeGeom_default_instance_.
Referenced by Geometry::set_allocated_cone().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Geometry & from)
cylinder()
const ::ignition::msgs::CylinderGeom & cylinder () const inline
References ignition::msgs::_CylinderGeom_default_instance_.
Referenced by Geometry::set_allocated_cylinder().
default_instance()
static const Geometry& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
ellipsoid()
const ::ignition::msgs::EllipsoidGeom & ellipsoid () const inline
References ignition::msgs::_EllipsoidGeom_default_instance_.
Referenced by Geometry::set_allocated_ellipsoid().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_box()
bool has_box () const inline
References Geometry::internal_default_instance().
has_capsule()
bool has_capsule () const inline
References Geometry::internal_default_instance().
has_cone()
bool has_cone () const inline
References Geometry::internal_default_instance().
has_cylinder()
bool has_cylinder () const inline
References Geometry::internal_default_instance().
has_ellipsoid()
bool has_ellipsoid () const inline
References Geometry::internal_default_instance().
has_header()
bool has_header () const inline
References Geometry::internal_default_instance().
has_heightmap()
bool has_heightmap () const inline
References Geometry::internal_default_instance().
has_image()
bool has_image () const inline
References Geometry::internal_default_instance().
has_mesh()
bool has_mesh () const inline
References Geometry::internal_default_instance().
has_plane()
bool has_plane () const inline
References Geometry::internal_default_instance().
has_sphere()
bool has_sphere () const inline
References Geometry::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Geometry::set_allocated_header().
heightmap()
const ::ignition::msgs::HeightmapGeom & heightmap () const inline
References ignition::msgs::_HeightmapGeom_default_instance_.
Referenced by Geometry::set_allocated_heightmap().
image()
const ::ignition::msgs::ImageGeom & image () const inline
References ignition::msgs::_ImageGeom_default_instance_.
Referenced by Geometry::set_allocated_image().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Geometry* internal_default_instance () inline static
References ignition::msgs::_Geometry_default_instance_.
Referenced by Geometry::has_box(), Geometry::has_capsule(), Geometry::has_cone(), Geometry::has_cylinder(), Geometry::has_ellipsoid(), Geometry::has_header(), Geometry::has_heightmap(), Geometry::has_image(), Geometry::has_mesh(), Geometry::has_plane(), and Geometry::has_sphere().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Geometry & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mesh()
const ::ignition::msgs::MeshGeom & mesh () const inline
References ignition::msgs::_MeshGeom_default_instance_.
Referenced by Geometry::set_allocated_mesh().
mutable_box()
ignition::msgs::BoxGeom * mutable_box () inline
mutable_capsule()
ignition::msgs::CapsuleGeom * mutable_capsule () inline
mutable_cone()
ignition::msgs::ConeGeom * mutable_cone () inline
mutable_cylinder()
ignition::msgs::CylinderGeom * mutable_cylinder () inline
mutable_ellipsoid()
ignition::msgs::EllipsoidGeom * mutable_ellipsoid () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_heightmap()
ignition::msgs::HeightmapGeom * mutable_heightmap () inline
mutable_image()
ignition::msgs::ImageGeom * mutable_image () inline
mutable_mesh()
ignition::msgs::MeshGeom * mutable_mesh () inline
mutable_plane()
ignition::msgs::PlaneGeom * mutable_plane () inline
mutable_points() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Vector3d > * mutable_points () inline
mutable_points() [2/2]
ignition::msgs::Vector3d * mutable_points (int index) inline
mutable_polyline() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Polyline > * mutable_polyline () inline
mutable_polyline() [2/2]
ignition::msgs::Polyline * mutable_polyline (int index) inline
mutable_sphere()
ignition::msgs::SphereGeom * mutable_sphere () inline
New() [1/2]
Geometry* New () const inline final
New() [2/2]
Geometry* New (::google::protobuf::Arena * arena) const inline final
operator=()
Geometry& operator= (const Geometry & from) inline
plane()
const ::ignition::msgs::PlaneGeom & plane () const inline
References ignition::msgs::_PlaneGeom_default_instance_.
Referenced by Geometry::set_allocated_plane().
points() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Vector3d > & points () const inline
points() [2/2]
const ::ignition::msgs::Vector3d & points (int index) const inline
points_size()
int points_size () const inline
polyline() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Polyline > & polyline () const inline
polyline() [2/2]
const ::ignition::msgs::Polyline & polyline (int index) const inline
polyline_size()
int polyline_size () const inline
release_box()
ignition::msgs::BoxGeom * release_box () inline
release_capsule()
ignition::msgs::CapsuleGeom * release_capsule () inline
release_cone()
ignition::msgs::ConeGeom * release_cone () inline
release_cylinder()
ignition::msgs::CylinderGeom * release_cylinder () inline
release_ellipsoid()
ignition::msgs::EllipsoidGeom * release_ellipsoid () inline
release_header()
ignition::msgs::Header * release_header () inline
release_heightmap()
ignition::msgs::HeightmapGeom * release_heightmap () inline
release_image()
ignition::msgs::ImageGeom * release_image () inline
release_mesh()
ignition::msgs::MeshGeom * release_mesh () inline
release_plane()
ignition::msgs::PlaneGeom * release_plane () inline
release_sphere()
ignition::msgs::SphereGeom * release_sphere () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_box()
void set_allocated_box (::ignition::msgs::BoxGeom * box) inline
References Geometry::box().
set_allocated_capsule()
void set_allocated_capsule (::ignition::msgs::CapsuleGeom * capsule) inline
References Geometry::capsule().
set_allocated_cone()
void set_allocated_cone (::ignition::msgs::ConeGeom * cone) inline
References Geometry::cone().
set_allocated_cylinder()
void set_allocated_cylinder (::ignition::msgs::CylinderGeom * cylinder) inline
References Geometry::cylinder().
set_allocated_ellipsoid()
void set_allocated_ellipsoid (::ignition::msgs::EllipsoidGeom * ellipsoid) inline
References Geometry::ellipsoid().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Geometry::header().
set_allocated_heightmap()
void set_allocated_heightmap (::ignition::msgs::HeightmapGeom * heightmap) inline
References Geometry::heightmap().
set_allocated_image()
void set_allocated_image (::ignition::msgs::ImageGeom * image) inline
References Geometry::image().
set_allocated_mesh()
void set_allocated_mesh (::ignition::msgs::MeshGeom * mesh) inline
References Geometry::mesh().
set_allocated_plane()
void set_allocated_plane (::ignition::msgs::PlaneGeom * plane) inline
References Geometry::plane().
set_allocated_sphere()
void set_allocated_sphere (::ignition::msgs::SphereGeom * sphere) inline
References Geometry::sphere().
set_type()
void set_type (::ignition::msgs::Geometry_Type value) inline
sphere()
const ::ignition::msgs::SphereGeom & sphere () const inline
References ignition::msgs::_SphereGeom_default_instance_.
Referenced by Geometry::set_allocated_sphere().
Swap()
void Swap (Geometry * other)
type()
ignition::msgs::Geometry_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References ignition::msgs::Geometry_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References ignition::msgs::Geometry_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References ignition::msgs::Geometry_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References ignition::msgs::Geometry_Type_Parse().
Member Data Documentation
ARROW
const Type ARROW static
Initial value:
=
    Geometry_Type_ARROW
AXIS
const Type AXIS static
Initial value:
=
    Geometry_Type_AXIS
BOX
const Type BOX static
Initial value:
=
    Geometry_Type_BOX
CAPSULE
const Type CAPSULE static
Initial value:
=
    Geometry_Type_CAPSULE
CONE
const Type CONE static
Initial value:
=
    Geometry_Type_CONE
CYLINDER
const Type CYLINDER static
Initial value:
=
    Geometry_Type_CYLINDER
ELLIPSOID
const Type ELLIPSOID static
Initial value:
=
    Geometry_Type_ELLIPSOID
EMPTY
const Type EMPTY static
Initial value:
=
    Geometry_Type_EMPTY
HEIGHTMAP
const Type HEIGHTMAP static
Initial value:
=
    Geometry_Type_HEIGHTMAP
IMAGE
const Type IMAGE static
Initial value:
=
    Geometry_Type_IMAGE
kBoxFieldNumber
const int kBoxFieldNumber = 3 static
kCapsuleFieldNumber
const int kCapsuleFieldNumber = 13 static
kConeFieldNumber
const int kConeFieldNumber = 10 static
kCylinderFieldNumber
const int kCylinderFieldNumber = 4 static
kEllipsoidFieldNumber
const int kEllipsoidFieldNumber = 14 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHeightmapFieldNumber
const int kHeightmapFieldNumber = 8 static
kImageFieldNumber
const int kImageFieldNumber = 7 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kMeshFieldNumber
const int kMeshFieldNumber = 9 static
kPlaneFieldNumber
const int kPlaneFieldNumber = 5 static
kPointsFieldNumber
const int kPointsFieldNumber = 11 static
kPolylineFieldNumber
const int kPolylineFieldNumber = 12 static
kSphereFieldNumber
const int kSphereFieldNumber = 6 static
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
LINE_STRIP
const Type LINE_STRIP static
Initial value:
=
    Geometry_Type_LINE_STRIP
MESH
const Type MESH static
Initial value:
=
    Geometry_Type_MESH
PLANE
const Type PLANE static
Initial value:
=
    Geometry_Type_PLANE
POLYLINE
const Type POLYLINE static
Initial value:
=
    Geometry_Type_POLYLINE
SPHERE
const Type SPHERE static
Initial value:
=
    Geometry_Type_SPHERE
TRIANGLE_FAN
const Type TRIANGLE_FAN static
Initial value:
=
    Geometry_Type_TRIANGLE_FAN
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    Geometry_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    Geometry_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    Geometry_Type_Type_MIN
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/geometry.pb.h