Gazebo Msgs: RestPost Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
RestPost Class Reference
#include <rest_post.pb.h>
Public Member Functions
RestPost ()
RestPost (const RestPost &from)
virtual ~RestPost ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_id ()
void clear_json ()
void clear_route ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const RestPost &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::std::string & json () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const RestPost &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_json ()
::std::string * mutable_route ()
RestPost * New () const final
RestPost * New (::google::protobuf::Arena *arena) const final
RestPost & operator= (const RestPost &from)
::ignition::msgs::Header * release_header ()
::std::string * release_json ()
::std::string * release_route ()
const ::std::string & route () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_json (::std::string *json)
void set_allocated_route (::std::string *route)
void set_id (::google::protobuf::uint32 value)
void set_json (const ::std::string &value)
void set_json (const char *value)
void set_json (const char *value, size_t size)
void set_route (const ::std::string &value)
void set_route (const char *value)
void set_route (const char *value, size_t size)
void Swap (RestPost *other)
Static Public Member Functions
static const RestPost & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const RestPost * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kJsonFieldNumber = 4
static const int kRouteFieldNumber = 3
Constructor & Destructor Documentation
RestPost() [1/2]
RestPost ()
~RestPost()
virtual ~RestPost () virtual
RestPost() [2/2]
RestPost (const RestPost & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_json()
void clear_json () inline
clear_route()
void clear_route () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const RestPost & from)
default_instance()
static const RestPost& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References RestPost::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by RestPost::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const RestPost* internal_default_instance () inline static
References ignition::msgs::_RestPost_default_instance_.
Referenced by RestPost::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
json()
const ::std::string & json () const inline
Referenced by RestPost::set_allocated_json().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const RestPost & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_json()
std::string * mutable_json () inline
mutable_route()
std::string * mutable_route () inline
New() [1/2]
RestPost* New () const inline final
New() [2/2]
RestPost* New (::google::protobuf::Arena * arena) const inline final
operator=()
RestPost& operator= (const RestPost & from) inline
release_header()
ignition::msgs::Header * release_header () inline
release_json()
std::string * release_json () inline
release_route()
std::string * release_route () inline
route()
const ::std::string & route () const inline
Referenced by RestPost::set_allocated_route().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References RestPost::header().
set_allocated_json()
void set_allocated_json (::std::string * json) inline
References RestPost::json().
set_allocated_route()
void set_allocated_route (::std::string * route) inline
References RestPost::route().
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_json() [1/3]
void set_json (const ::std::string & value) inline
set_json() [2/3]
void set_json (const char * value) inline
set_json() [3/3]
void set_json (const char * value, size_t size) inline
set_route() [1/3]
void set_route (const ::std::string & value) inline
set_route() [2/3]
void set_route (const char * value) inline
set_route() [3/3]
void set_route (const char * value, size_t size) inline
Swap()
void Swap (RestPost * other)
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kJsonFieldNumber
const int kJsonFieldNumber = 4 static
kRouteFieldNumber
const int kRouteFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/rest_post.pb.h