Gazebo Msgs: Projector Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Projector Class Reference
#include <projector.pb.h>
Public Member Functions
Projector ()
Projector (const Projector &from)
virtual ~Projector ()
size_t ByteSizeLong () const final
void Clear () final
void clear_enabled ()
void clear_far_clip ()
void clear_fov ()
void clear_header ()
void clear_name ()
void clear_near_clip ()
void clear_pose ()
void clear_texture ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Projector &from)
bool enabled () const
double far_clip () const
double fov () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_pose () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Projector &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_name ()
::ignition::msgs::Pose * mutable_pose ()
::std::string * mutable_texture ()
const ::std::string & name () const
double near_clip () const
Projector * New () const final
Projector * New (::google::protobuf::Arena *arena) const final
Projector & operator= (const Projector &from)
const ::ignition::msgs::Pose & pose () const
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
::ignition::msgs::Pose * release_pose ()
::std::string * release_texture ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_pose (::ignition::msgs::Pose *pose)
void set_allocated_texture (::std::string *texture)
void set_enabled (bool value)
void set_far_clip (double value)
void set_fov (double value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_near_clip (double value)
void set_texture (const ::std::string &value)
void set_texture (const char *value)
void set_texture (const char *value, size_t size)
void Swap (Projector *other)
const ::std::string & texture () const
Static Public Member Functions
static const Projector & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Projector * internal_default_instance ()
Static Public Attributes
static const int kEnabledFieldNumber = 8
static const int kFarClipFieldNumber = 7
static const int kFovFieldNumber = 5
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 2
static const int kNearClipFieldNumber = 6
static const int kPoseFieldNumber = 4
static const int kTextureFieldNumber = 3
Constructor & Destructor Documentation
Projector() [1/2]
Projector ()
~Projector()
virtual ~Projector () virtual
Projector() [2/2]
Projector (const Projector & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_enabled()
void clear_enabled () inline
clear_far_clip()
void clear_far_clip () inline
clear_fov()
void clear_fov () inline
clear_header()
void clear_header ()
clear_name()
void clear_name () inline
clear_near_clip()
void clear_near_clip () inline
clear_pose()
void clear_pose ()
clear_texture()
void clear_texture () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Projector & from)
default_instance()
static const Projector& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
enabled()
bool enabled () const inline
far_clip()
double far_clip () const inline
fov()
double fov () const inline
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Projector::internal_default_instance().
has_pose()
bool has_pose () const inline
References Projector::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Projector::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Projector* internal_default_instance () inline static
References ignition::msgs::_Projector_default_instance_.
Referenced by Projector::has_header(), and Projector::has_pose().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Projector & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
mutable_pose()
ignition::msgs::Pose * mutable_pose () inline
mutable_texture()
std::string * mutable_texture () inline
name()
const ::std::string & name () const inline
Referenced by Projector::set_allocated_name().
near_clip()
double near_clip () const inline
New() [1/2]
Projector* New () const inline final
New() [2/2]
Projector* New (::google::protobuf::Arena * arena) const inline final
operator=()
Projector& operator= (const Projector & from) inline
pose()
const ::ignition::msgs::Pose & pose () const inline
References ignition::msgs::_Pose_default_instance_.
Referenced by Projector::set_allocated_pose().
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_pose()
ignition::msgs::Pose * release_pose () inline
release_texture()
std::string * release_texture () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Projector::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Projector::name().
set_allocated_pose()
void set_allocated_pose (::ignition::msgs::Pose * pose) inline
References Projector::pose().
set_allocated_texture()
void set_allocated_texture (::std::string * texture) inline
References Projector::texture().
set_enabled()
void set_enabled (bool value) inline
set_far_clip()
void set_far_clip (double value) inline
set_fov()
void set_fov (double value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_near_clip()
void set_near_clip (double value) inline
set_texture() [1/3]
void set_texture (const ::std::string & value) inline
set_texture() [2/3]
void set_texture (const char * value) inline
set_texture() [3/3]
void set_texture (const char * value, size_t size) inline
Swap()
void Swap (Projector * other)
texture()
const ::std::string & texture () const inline
Referenced by Projector::set_allocated_texture().
Member Data Documentation
kEnabledFieldNumber
const int kEnabledFieldNumber = 8 static
kFarClipFieldNumber
const int kFarClipFieldNumber = 7 static
kFovFieldNumber
const int kFovFieldNumber = 5 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 2 static
kNearClipFieldNumber
const int kNearClipFieldNumber = 6 static
kPoseFieldNumber
const int kPoseFieldNumber = 4 static
kTextureFieldNumber
const int kTextureFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/projector.pb.h