Gazebo Msgs: JointCmd Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
JointCmd Class Reference
#include <joint_cmd.pb.h>
Public Member Functions
JointCmd ()
JointCmd (const JointCmd &from)
virtual ~JointCmd ()
::google::protobuf::int32 axis () const
size_t ByteSizeLong () const final
void Clear () final
void clear_axis ()
void clear_force_optional ()
void clear_header ()
void clear_name ()
void clear_position ()
void clear_reset ()
void clear_velocity ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const JointCmd &from)
const ::ignition::msgs::Double & force_optional () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_force_optional () const
bool has_header () const
bool has_position () const
bool has_velocity () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const JointCmd &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Double * mutable_force_optional ()
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_name ()
::ignition::msgs::PID * mutable_position ()
::ignition::msgs::PID * mutable_velocity ()
const ::std::string & name () const
JointCmd * New () const final
JointCmd * New (::google::protobuf::Arena *arena) const final
JointCmd & operator= (const JointCmd &from)
const ::ignition::msgs::PID & position () const
::ignition::msgs::Double * release_force_optional ()
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
::ignition::msgs::PID * release_position ()
::ignition::msgs::PID * release_velocity ()
bool reset () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_force_optional (::ignition::msgs::Double *force_optional)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_position (::ignition::msgs::PID *position)
void set_allocated_velocity (::ignition::msgs::PID *velocity)
void set_axis (::google::protobuf::int32 value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_reset (bool value)
void Swap (JointCmd *other)
const ::ignition::msgs::PID & velocity () const
Static Public Member Functions
static const JointCmd & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const JointCmd * internal_default_instance ()
Static Public Attributes
static const int kAxisFieldNumber = 3
static const int kForceOptionalFieldNumber = 8
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 2
static const int kPositionFieldNumber = 5
static const int kResetFieldNumber = 7
static const int kVelocityFieldNumber = 6
Constructor & Destructor Documentation
JointCmd() [1/2]
JointCmd ()
~JointCmd()
virtual ~JointCmd () virtual
JointCmd() [2/2]
JointCmd (const JointCmd & from)
Member Function Documentation
axis()
google::protobuf::int32 axis () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_axis()
void clear_axis () inline
clear_force_optional()
void clear_force_optional ()
clear_header()
void clear_header ()
clear_name()
void clear_name () inline
clear_position()
void clear_position ()
clear_reset()
void clear_reset () inline
clear_velocity()
void clear_velocity ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const JointCmd & from)
default_instance()
static const JointCmd& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
force_optional()
const ::ignition::msgs::Double & force_optional () const inline
References ignition::msgs::_Double_default_instance_.
Referenced by JointCmd::set_allocated_force_optional().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_force_optional()
bool has_force_optional () const inline
References JointCmd::internal_default_instance().
has_header()
bool has_header () const inline
References JointCmd::internal_default_instance().
has_position()
bool has_position () const inline
References JointCmd::internal_default_instance().
has_velocity()
bool has_velocity () const inline
References JointCmd::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by JointCmd::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const JointCmd* internal_default_instance () inline static
References ignition::msgs::_JointCmd_default_instance_.
Referenced by JointCmd::has_force_optional(), JointCmd::has_header(), JointCmd::has_position(), and JointCmd::has_velocity().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const JointCmd & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_force_optional()
ignition::msgs::Double * mutable_force_optional () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
mutable_position()
ignition::msgs::PID * mutable_position () inline
mutable_velocity()
ignition::msgs::PID * mutable_velocity () inline
name()
const ::std::string & name () const inline
Referenced by JointCmd::set_allocated_name().
New() [1/2]
JointCmd* New () const inline final
New() [2/2]
JointCmd* New (::google::protobuf::Arena * arena) const inline final
operator=()
JointCmd& operator= (const JointCmd & from) inline
position()
const ::ignition::msgs::PID & position () const inline
References ignition::msgs::_PID_default_instance_.
Referenced by JointCmd::set_allocated_position().
release_force_optional()
ignition::msgs::Double * release_force_optional () inline
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_position()
ignition::msgs::PID * release_position () inline
release_velocity()
ignition::msgs::PID * release_velocity () inline
reset()
bool reset () const inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_force_optional()
void set_allocated_force_optional (::ignition::msgs::Double * force_optional) inline
References JointCmd::force_optional().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References JointCmd::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References JointCmd::name().
set_allocated_position()
void set_allocated_position (::ignition::msgs::PID * position) inline
References JointCmd::position().
set_allocated_velocity()
void set_allocated_velocity (::ignition::msgs::PID * velocity) inline
References JointCmd::velocity().
set_axis()
void set_axis (::google::protobuf::int32 value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_reset()
void set_reset (bool value) inline
Swap()
void Swap (JointCmd * other)
velocity()
const ::ignition::msgs::PID & velocity () const inline
References ignition::msgs::_PID_default_instance_.
Referenced by JointCmd::set_allocated_velocity().
Member Data Documentation
kAxisFieldNumber
const int kAxisFieldNumber = 3 static
kForceOptionalFieldNumber
const int kForceOptionalFieldNumber = 8 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 2 static
kPositionFieldNumber
const int kPositionFieldNumber = 5 static
kResetFieldNumber
const int kResetFieldNumber = 7 static
kVelocityFieldNumber
const int kVelocityFieldNumber = 6 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/joint_cmd.pb.h