Gazebo Msgs: RestResponse Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
RestResponse Class Reference
#include <rest_response.pb.h>
Public Types
typedef RestResponse_Type Type
Public Member Functions
RestResponse ()
RestResponse (const RestResponse &from)
virtual ~RestResponse ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_id ()
void clear_msg ()
void clear_type ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const RestResponse &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const RestResponse &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::std::string & msg () const
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_msg ()
RestResponse * New () const final
RestResponse * New (::google::protobuf::Arena *arena) const final
RestResponse & operator= (const RestResponse &from)
::ignition::msgs::Header * release_header ()
::std::string * release_msg ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_msg (::std::string *msg)
void set_id (::google::protobuf::uint32 value)
void set_msg (const ::std::string &value)
void set_msg (const char *value)
void set_msg (const char *value, size_t size)
void set_type (::ignition::msgs::RestResponse_Type value)
void Swap (RestResponse *other)
::ignition::msgs::RestResponse_Type type () const
Static Public Member Functions
static const RestResponse & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const RestResponse * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type ERR
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kMsgFieldNumber = 4
static const int kTypeFieldNumber = 3
static const Type LOGIN
static const Type LOGOUT
static const Type SUCCESS
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
Member Typedef Documentation
Type
typedef RestResponse_Type Type
Constructor & Destructor Documentation
RestResponse() [1/2]
RestResponse ()
~RestResponse()
virtual ~RestResponse () virtual
RestResponse() [2/2]
RestResponse (const RestResponse & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_msg()
void clear_msg () inline
clear_type()
void clear_type () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const RestResponse & from)
default_instance()
static const RestResponse& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References RestResponse::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by RestResponse::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const RestResponse* internal_default_instance () inline static
References ignition::msgs::_RestResponse_default_instance_.
Referenced by RestResponse::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const RestResponse & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
msg()
const ::std::string & msg () const inline
Referenced by RestResponse::set_allocated_msg().
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_msg()
std::string * mutable_msg () inline
New() [1/2]
RestResponse* New () const inline final
New() [2/2]
RestResponse* New (::google::protobuf::Arena * arena) const inline final
operator=()
RestResponse& operator= (const RestResponse & from) inline
release_header()
ignition::msgs::Header * release_header () inline
release_msg()
std::string * release_msg () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References RestResponse::header().
set_allocated_msg()
void set_allocated_msg (::std::string * msg) inline
References RestResponse::msg().
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_msg() [1/3]
void set_msg (const ::std::string & value) inline
set_msg() [2/3]
void set_msg (const char * value) inline
set_msg() [3/3]
void set_msg (const char * value, size_t size) inline
set_type()
void set_type (::ignition::msgs::RestResponse_Type value) inline
Swap()
void Swap (RestResponse * other)
type()
ignition::msgs::RestResponse_Type type () const inline
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References ignition::msgs::RestResponse_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References ignition::msgs::RestResponse_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References ignition::msgs::RestResponse_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References ignition::msgs::RestResponse_Type_Parse().
Member Data Documentation
ERR
const Type ERR static
Initial value:
=
    RestResponse_Type_ERR
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kMsgFieldNumber
const int kMsgFieldNumber = 4 static
kTypeFieldNumber
const int kTypeFieldNumber = 3 static
LOGIN
const Type LOGIN static
Initial value:
=
    RestResponse_Type_LOGIN
LOGOUT
const Type LOGOUT static
Initial value:
=
    RestResponse_Type_LOGOUT
SUCCESS
const Type SUCCESS static
Initial value:
=
    RestResponse_Type_SUCCESS
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    RestResponse_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    RestResponse_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    RestResponse_Type_Type_MIN
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/rest_response.pb.h