Gazebo Msgs: ParticleEmitter Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
ParticleEmitter Class Reference
#include <particle_emitter.pb.h>
Public Types
typedef ParticleEmitter_EmitterType EmitterType
Public Member Functions
ParticleEmitter ()
ParticleEmitter (const ParticleEmitter &from)
virtual ~ParticleEmitter ()
size_t ByteSizeLong () const final
void Clear () final
void clear_color_end ()
void clear_color_range_image ()
void clear_color_start ()
void clear_duration ()
void clear_emitting ()
void clear_header ()
void clear_id ()
void clear_lifetime ()
void clear_material ()
void clear_max_velocity ()
void clear_min_velocity ()
void clear_name ()
void clear_particle_scatter_ratio ()
void clear_particle_size ()
void clear_pose ()
void clear_rate ()
void clear_scale_rate ()
void clear_size ()
void clear_topic ()
void clear_type ()
const ::ignition::msgs::Color & color_end () const
const ::ignition::msgs::StringMsg & color_range_image () const
const ::ignition::msgs::Color & color_start () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const ParticleEmitter &from)
const ::ignition::msgs::Float & duration () const
const ::ignition::msgs::Boolean & emitting () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_color_end () const
bool has_color_range_image () const
bool has_color_start () const
bool has_duration () const
bool has_emitting () const
bool has_header () const
bool has_lifetime () const
bool has_material () const
bool has_max_velocity () const
bool has_min_velocity () const
bool has_particle_scatter_ratio () const
bool has_particle_size () const
bool has_pose () const
bool has_rate () const
bool has_scale_rate () const
bool has_size () const
bool has_topic () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::ignition::msgs::Float & lifetime () const
const ::ignition::msgs::Material & material () const
const ::ignition::msgs::Float & max_velocity () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ParticleEmitter &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::ignition::msgs::Float & min_velocity () const
::ignition::msgs::Color * mutable_color_end ()
::ignition::msgs::StringMsg * mutable_color_range_image ()
::ignition::msgs::Color * mutable_color_start ()
::ignition::msgs::Float * mutable_duration ()
::ignition::msgs::Boolean * mutable_emitting ()
::ignition::msgs::Header * mutable_header ()
::ignition::msgs::Float * mutable_lifetime ()
::ignition::msgs::Material * mutable_material ()
::ignition::msgs::Float * mutable_max_velocity ()
::ignition::msgs::Float * mutable_min_velocity ()
::std::string * mutable_name ()
::ignition::msgs::Float * mutable_particle_scatter_ratio ()
::ignition::msgs::Vector3d * mutable_particle_size ()
::ignition::msgs::Pose * mutable_pose ()
::ignition::msgs::Float * mutable_rate ()
::ignition::msgs::Float * mutable_scale_rate ()
::ignition::msgs::Vector3d * mutable_size ()
::ignition::msgs::StringMsg * mutable_topic ()
const ::std::string & name () const
ParticleEmitter * New () const final
ParticleEmitter * New (::google::protobuf::Arena *arena) const final
ParticleEmitter & operator= (const ParticleEmitter &from)
const ::ignition::msgs::Float & particle_scatter_ratio () const
const ::ignition::msgs::Vector3d & particle_size () const
const ::ignition::msgs::Pose & pose () const
const ::ignition::msgs::Float & rate () const
::ignition::msgs::Color * release_color_end ()
::ignition::msgs::StringMsg * release_color_range_image ()
::ignition::msgs::Color * release_color_start ()
::ignition::msgs::Float * release_duration ()
::ignition::msgs::Boolean * release_emitting ()
::ignition::msgs::Header * release_header ()
::ignition::msgs::Float * release_lifetime ()
::ignition::msgs::Material * release_material ()
::ignition::msgs::Float * release_max_velocity ()
::ignition::msgs::Float * release_min_velocity ()
::std::string * release_name ()
::ignition::msgs::Float * release_particle_scatter_ratio ()
::ignition::msgs::Vector3d * release_particle_size ()
::ignition::msgs::Pose * release_pose ()
::ignition::msgs::Float * release_rate ()
::ignition::msgs::Float * release_scale_rate ()
::ignition::msgs::Vector3d * release_size ()
::ignition::msgs::StringMsg * release_topic ()
const ::ignition::msgs::Float & scale_rate () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_color_end (::ignition::msgs::Color *color_end)
void set_allocated_color_range_image (::ignition::msgs::StringMsg *color_range_image)
void set_allocated_color_start (::ignition::msgs::Color *color_start)
void set_allocated_duration (::ignition::msgs::Float *duration)
void set_allocated_emitting (::ignition::msgs::Boolean *emitting)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_lifetime (::ignition::msgs::Float *lifetime)
void set_allocated_material (::ignition::msgs::Material *material)
void set_allocated_max_velocity (::ignition::msgs::Float *max_velocity)
void set_allocated_min_velocity (::ignition::msgs::Float *min_velocity)
void set_allocated_name (::std::string *name)
void set_allocated_particle_scatter_ratio (::ignition::msgs::Float *particle_scatter_ratio)
void set_allocated_particle_size (::ignition::msgs::Vector3d *particle_size)
void set_allocated_pose (::ignition::msgs::Pose *pose)
void set_allocated_rate (::ignition::msgs::Float *rate)
void set_allocated_scale_rate (::ignition::msgs::Float *scale_rate)
void set_allocated_size (::ignition::msgs::Vector3d *size)
void set_allocated_topic (::ignition::msgs::StringMsg *topic)
void set_id (::google::protobuf::uint32 value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_type (::ignition::msgs::ParticleEmitter_EmitterType value)
const ::ignition::msgs::Vector3d & size () const
void Swap (ParticleEmitter *other)
const ::ignition::msgs::StringMsg & topic () const
::ignition::msgs::ParticleEmitter_EmitterType type () const
Static Public Member Functions
static const ParticleEmitter & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static const ::google::protobuf::EnumDescriptor * EmitterType_descriptor ()
static bool EmitterType_IsValid (int value)
static const ::std::string & EmitterType_Name (EmitterType value)
static bool EmitterType_Parse (const ::std::string &name, EmitterType *value)
static void InitAsDefaultInstance ()
static const ParticleEmitter * internal_default_instance ()
Static Public Attributes
static const EmitterType BOX
static const EmitterType CYLINDER
static const EmitterType ELLIPSOID
static const int EmitterType_ARRAYSIZE
static const EmitterType EmitterType_MAX
static const EmitterType EmitterType_MIN
static const int kColorEndFieldNumber = 16
static const int kColorRangeImageFieldNumber = 18
static const int kColorStartFieldNumber = 15
static const int kDurationFieldNumber = 8
static const int kEmittingFieldNumber = 9
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 3
static constexpr int kIndexInFileMessages
static const int kLifetimeFieldNumber = 11
static const int kMaterialFieldNumber = 12
static const int kMaxVelocityFieldNumber = 14
static const int kMinVelocityFieldNumber = 13
static const int kNameFieldNumber = 2
static const int kParticleScatterRatioFieldNumber = 20
static const int kParticleSizeFieldNumber = 10
static const int kPoseFieldNumber = 5
static const int kRateFieldNumber = 7
static const int kScaleRateFieldNumber = 17
static const int kSizeFieldNumber = 6
static const int kTopicFieldNumber = 19
static const int kTypeFieldNumber = 4
static const EmitterType POINT
Member Typedef Documentation
EmitterType
typedef ParticleEmitter_EmitterType EmitterType
Constructor & Destructor Documentation
ParticleEmitter() [1/2]
ParticleEmitter ()
~ParticleEmitter()
virtual ~ParticleEmitter () virtual
ParticleEmitter() [2/2]
ParticleEmitter (const ParticleEmitter & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_color_end()
void clear_color_end ()
clear_color_range_image()
void clear_color_range_image ()
clear_color_start()
void clear_color_start ()
clear_duration()
void clear_duration ()
clear_emitting()
void clear_emitting ()
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_lifetime()
void clear_lifetime ()
clear_material()
void clear_material ()
clear_max_velocity()
void clear_max_velocity ()
clear_min_velocity()
void clear_min_velocity ()
clear_name()
void clear_name () inline
clear_particle_scatter_ratio()
void clear_particle_scatter_ratio ()
clear_particle_size()
void clear_particle_size ()
clear_pose()
void clear_pose ()
clear_rate()
void clear_rate ()
clear_scale_rate()
void clear_scale_rate ()
clear_size()
void clear_size ()
clear_topic()
void clear_topic ()
clear_type()
void clear_type () inline
color_end()
const ::ignition::msgs::Color & color_end () const inline
References ignition::msgs::_Color_default_instance_.
Referenced by ParticleEmitter::set_allocated_color_end().
color_range_image()
const ::ignition::msgs::StringMsg & color_range_image () const inline
References ignition::msgs::_StringMsg_default_instance_.
Referenced by ParticleEmitter::set_allocated_color_range_image().
color_start()
const ::ignition::msgs::Color & color_start () const inline
References ignition::msgs::_Color_default_instance_.
Referenced by ParticleEmitter::set_allocated_color_start().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const ParticleEmitter & from)
default_instance()
static const ParticleEmitter& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
duration()
const ::ignition::msgs::Float & duration () const inline
References ignition::msgs::_Float_default_instance_.
Referenced by ParticleEmitter::set_allocated_duration().
EmitterType_descriptor()
static const ::google::protobuf::EnumDescriptor* EmitterType_descriptor () inline static
References ignition::msgs::ParticleEmitter_EmitterType_descriptor().
EmitterType_IsValid()
static bool EmitterType_IsValid (int value) inline static
References ignition::msgs::ParticleEmitter_EmitterType_IsValid().
EmitterType_Name()
static const ::std::string& EmitterType_Name (EmitterType value) inline static
References ignition::msgs::ParticleEmitter_EmitterType_Name().
EmitterType_Parse()
static bool EmitterType_Parse (const ::std::string & name, EmitterType * value) inline static
References ignition::msgs::ParticleEmitter_EmitterType_Parse().
emitting()
const ::ignition::msgs::Boolean & emitting () const inline
References ignition::msgs::_Boolean_default_instance_.
Referenced by ParticleEmitter::set_allocated_emitting().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_color_end()
bool has_color_end () const inline
References ParticleEmitter::internal_default_instance().
has_color_range_image()
bool has_color_range_image () const inline
References ParticleEmitter::internal_default_instance().
has_color_start()
bool has_color_start () const inline
References ParticleEmitter::internal_default_instance().
has_duration()
bool has_duration () const inline
References ParticleEmitter::internal_default_instance().
has_emitting()
bool has_emitting () const inline
References ParticleEmitter::internal_default_instance().
has_header()
bool has_header () const inline
References ParticleEmitter::internal_default_instance().
has_lifetime()
bool has_lifetime () const inline
References ParticleEmitter::internal_default_instance().
has_material()
bool has_material () const inline
References ParticleEmitter::internal_default_instance().
has_max_velocity()
bool has_max_velocity () const inline
References ParticleEmitter::internal_default_instance().
has_min_velocity()
bool has_min_velocity () const inline
References ParticleEmitter::internal_default_instance().
has_particle_scatter_ratio()
bool has_particle_scatter_ratio () const inline
References ParticleEmitter::internal_default_instance().
has_particle_size()
bool has_particle_size () const inline
References ParticleEmitter::internal_default_instance().
has_pose()
bool has_pose () const inline
References ParticleEmitter::internal_default_instance().
has_rate()
bool has_rate () const inline
References ParticleEmitter::internal_default_instance().
has_scale_rate()
bool has_scale_rate () const inline
References ParticleEmitter::internal_default_instance().
has_size()
bool has_size () const inline
References ParticleEmitter::internal_default_instance().
has_topic()
bool has_topic () const inline
References ParticleEmitter::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by ParticleEmitter::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const ParticleEmitter* internal_default_instance () inline static
References ignition::msgs::_ParticleEmitter_default_instance_.
Referenced by ParticleEmitter::has_color_end(), ParticleEmitter::has_color_range_image(), ParticleEmitter::has_color_start(), ParticleEmitter::has_duration(), ParticleEmitter::has_emitting(), ParticleEmitter::has_header(), ParticleEmitter::has_lifetime(), ParticleEmitter::has_material(), ParticleEmitter::has_max_velocity(), ParticleEmitter::has_min_velocity(), ParticleEmitter::has_particle_scatter_ratio(), ParticleEmitter::has_particle_size(), ParticleEmitter::has_pose(), ParticleEmitter::has_rate(), ParticleEmitter::has_scale_rate(), ParticleEmitter::has_size(), and ParticleEmitter::has_topic().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
lifetime()
const ::ignition::msgs::Float & lifetime () const inline
References ignition::msgs::_Float_default_instance_.
Referenced by ParticleEmitter::set_allocated_lifetime().
material()
const ::ignition::msgs::Material & material () const inline
References ignition::msgs::_Material_default_instance_.
Referenced by ParticleEmitter::set_allocated_material().
max_velocity()
const ::ignition::msgs::Float & max_velocity () const inline
References ignition::msgs::_Float_default_instance_.
Referenced by ParticleEmitter::set_allocated_max_velocity().
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const ParticleEmitter & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
min_velocity()
const ::ignition::msgs::Float & min_velocity () const inline
References ignition::msgs::_Float_default_instance_.
Referenced by ParticleEmitter::set_allocated_min_velocity().
mutable_color_end()
ignition::msgs::Color * mutable_color_end () inline
mutable_color_range_image()
ignition::msgs::StringMsg * mutable_color_range_image () inline
mutable_color_start()
ignition::msgs::Color * mutable_color_start () inline
mutable_duration()
ignition::msgs::Float * mutable_duration () inline
mutable_emitting()
ignition::msgs::Boolean * mutable_emitting () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_lifetime()
ignition::msgs::Float * mutable_lifetime () inline
mutable_material()
ignition::msgs::Material * mutable_material () inline
mutable_max_velocity()
ignition::msgs::Float * mutable_max_velocity () inline
mutable_min_velocity()
ignition::msgs::Float * mutable_min_velocity () inline
mutable_name()
std::string * mutable_name () inline
mutable_particle_scatter_ratio()
ignition::msgs::Float * mutable_particle_scatter_ratio () inline
mutable_particle_size()
ignition::msgs::Vector3d * mutable_particle_size () inline
mutable_pose()
ignition::msgs::Pose * mutable_pose () inline
mutable_rate()
ignition::msgs::Float * mutable_rate () inline
mutable_scale_rate()
ignition::msgs::Float * mutable_scale_rate () inline
mutable_size()
ignition::msgs::Vector3d * mutable_size () inline
mutable_topic()
ignition::msgs::StringMsg * mutable_topic () inline
name()
const ::std::string & name () const inline
Referenced by ParticleEmitter::set_allocated_name().
New() [1/2]
ParticleEmitter* New () const inline final
New() [2/2]
ParticleEmitter* New (::google::protobuf::Arena * arena) const inline final
operator=()
ParticleEmitter& operator= (const ParticleEmitter & from) inline
particle_scatter_ratio()
const ::ignition::msgs::Float & particle_scatter_ratio () const inline
References ignition::msgs::_Float_default_instance_.
Referenced by ParticleEmitter::set_allocated_particle_scatter_ratio().
particle_size()
const ::ignition::msgs::Vector3d & particle_size () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by ParticleEmitter::set_allocated_particle_size().
pose()
const ::ignition::msgs::Pose & pose () const inline
References ignition::msgs::_Pose_default_instance_.
Referenced by ParticleEmitter::set_allocated_pose().
rate()
const ::ignition::msgs::Float & rate () const inline
References ignition::msgs::_Float_default_instance_.
Referenced by ParticleEmitter::set_allocated_rate().
release_color_end()
ignition::msgs::Color * release_color_end () inline
release_color_range_image()
ignition::msgs::StringMsg * release_color_range_image () inline
release_color_start()
ignition::msgs::Color * release_color_start () inline
release_duration()
ignition::msgs::Float * release_duration () inline
release_emitting()
ignition::msgs::Boolean * release_emitting () inline
release_header()
ignition::msgs::Header * release_header () inline
release_lifetime()
ignition::msgs::Float * release_lifetime () inline
release_material()
ignition::msgs::Material * release_material () inline
release_max_velocity()
ignition::msgs::Float * release_max_velocity () inline
release_min_velocity()
ignition::msgs::Float * release_min_velocity () inline
release_name()
std::string * release_name () inline
release_particle_scatter_ratio()
ignition::msgs::Float * release_particle_scatter_ratio () inline
release_particle_size()
ignition::msgs::Vector3d * release_particle_size () inline
release_pose()
ignition::msgs::Pose * release_pose () inline
release_rate()
ignition::msgs::Float * release_rate () inline
release_scale_rate()
ignition::msgs::Float * release_scale_rate () inline
release_size()
ignition::msgs::Vector3d * release_size () inline
release_topic()
ignition::msgs::StringMsg * release_topic () inline
scale_rate()
const ::ignition::msgs::Float & scale_rate () const inline
References ignition::msgs::_Float_default_instance_.
Referenced by ParticleEmitter::set_allocated_scale_rate().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_color_end()
void set_allocated_color_end (::ignition::msgs::Color * color_end) inline
References ParticleEmitter::color_end().
set_allocated_color_range_image()
void set_allocated_color_range_image (::ignition::msgs::StringMsg * color_range_image) inline
References ParticleEmitter::color_range_image().
set_allocated_color_start()
void set_allocated_color_start (::ignition::msgs::Color * color_start) inline
References ParticleEmitter::color_start().
set_allocated_duration()
void set_allocated_duration (::ignition::msgs::Float * duration) inline
References ParticleEmitter::duration().
set_allocated_emitting()
void set_allocated_emitting (::ignition::msgs::Boolean * emitting) inline
References ParticleEmitter::emitting().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References ParticleEmitter::header().
set_allocated_lifetime()
void set_allocated_lifetime (::ignition::msgs::Float * lifetime) inline
References ParticleEmitter::lifetime().
set_allocated_material()
void set_allocated_material (::ignition::msgs::Material * material) inline
References ParticleEmitter::material().
set_allocated_max_velocity()
void set_allocated_max_velocity (::ignition::msgs::Float * max_velocity) inline
References ParticleEmitter::max_velocity().
set_allocated_min_velocity()
void set_allocated_min_velocity (::ignition::msgs::Float * min_velocity) inline
References ParticleEmitter::min_velocity().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References ParticleEmitter::name().
set_allocated_particle_scatter_ratio()
void set_allocated_particle_scatter_ratio (::ignition::msgs::Float * particle_scatter_ratio) inline
References ParticleEmitter::particle_scatter_ratio().
set_allocated_particle_size()
void set_allocated_particle_size (::ignition::msgs::Vector3d * particle_size) inline
References ParticleEmitter::particle_size().
set_allocated_pose()
void set_allocated_pose (::ignition::msgs::Pose * pose) inline
References ParticleEmitter::pose().
set_allocated_rate()
void set_allocated_rate (::ignition::msgs::Float * rate) inline
References ParticleEmitter::rate().
set_allocated_scale_rate()
void set_allocated_scale_rate (::ignition::msgs::Float * scale_rate) inline
References ParticleEmitter::scale_rate().
set_allocated_size()
void set_allocated_size (::ignition::msgs::Vector3d * size) inline
References ParticleEmitter::size().
set_allocated_topic()
void set_allocated_topic (::ignition::msgs::StringMsg * topic) inline
References ParticleEmitter::topic().
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
References ParticleEmitter::size().
set_type()
void set_type (::ignition::msgs::ParticleEmitter_EmitterType value) inline
size()
const ::ignition::msgs::Vector3d & size () const inline
References ignition::msgs::_Vector3d_default_instance_.
Referenced by ParticleEmitter::set_allocated_size(), and ParticleEmitter::set_name().
Swap()
void Swap (ParticleEmitter * other)
topic()
const ::ignition::msgs::StringMsg & topic () const inline
References ignition::msgs::_StringMsg_default_instance_.
Referenced by ParticleEmitter::set_allocated_topic().
type()
ignition::msgs::ParticleEmitter_EmitterType type () const inline
Member Data Documentation
BOX
const EmitterType BOX static
Initial value:
=
    ParticleEmitter_EmitterType_BOX
CYLINDER
const EmitterType CYLINDER static
Initial value:
=
    ParticleEmitter_EmitterType_CYLINDER
ELLIPSOID
const EmitterType ELLIPSOID static
Initial value:
=
    ParticleEmitter_EmitterType_ELLIPSOID
EmitterType_ARRAYSIZE
const int EmitterType_ARRAYSIZE static
Initial value:
=
    ParticleEmitter_EmitterType_EmitterType_ARRAYSIZE
EmitterType_MAX
const EmitterType EmitterType_MAX static
Initial value:
=
    ParticleEmitter_EmitterType_EmitterType_MAX
EmitterType_MIN
const EmitterType EmitterType_MIN static
Initial value:
=
    ParticleEmitter_EmitterType_EmitterType_MIN
kColorEndFieldNumber
const int kColorEndFieldNumber = 16 static
kColorRangeImageFieldNumber
const int kColorRangeImageFieldNumber = 18 static
kColorStartFieldNumber
const int kColorStartFieldNumber = 15 static
kDurationFieldNumber
const int kDurationFieldNumber = 8 static
kEmittingFieldNumber
const int kEmittingFieldNumber = 9 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 3 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kLifetimeFieldNumber
const int kLifetimeFieldNumber = 11 static
kMaterialFieldNumber
const int kMaterialFieldNumber = 12 static
kMaxVelocityFieldNumber
const int kMaxVelocityFieldNumber = 14 static
kMinVelocityFieldNumber
const int kMinVelocityFieldNumber = 13 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
kParticleScatterRatioFieldNumber
const int kParticleScatterRatioFieldNumber = 20 static
kParticleSizeFieldNumber
const int kParticleSizeFieldNumber = 10 static
kPoseFieldNumber
const int kPoseFieldNumber = 5 static
kRateFieldNumber
const int kRateFieldNumber = 7 static
kScaleRateFieldNumber
const int kScaleRateFieldNumber = 17 static
kSizeFieldNumber
const int kSizeFieldNumber = 6 static
kTopicFieldNumber
const int kTopicFieldNumber = 19 static
kTypeFieldNumber
const int kTypeFieldNumber = 4 static
POINT
const EmitterType POINT static
Initial value:
=
    ParticleEmitter_EmitterType_POINT
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/particle_emitter.pb.h