Gazebo Msgs: FuelMetadata_Categories Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
FuelMetadata_Categories Class Reference
#include <fuel_metadata.pb.h>
Public Member Functions
FuelMetadata_Categories ()
FuelMetadata_Categories (const FuelMetadata_Categories &from)
virtual ~FuelMetadata_Categories ()
size_t ByteSizeLong () const final
void Clear () final
void clear_first ()
void clear_second ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const FuelMetadata_Categories &from)
const ::std::string & first () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const FuelMetadata_Categories &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_first ()
::std::string * mutable_second ()
FuelMetadata_Categories * New () const final
FuelMetadata_Categories * New (::google::protobuf::Arena *arena) const final
FuelMetadata_Categories & operator= (const FuelMetadata_Categories &from)
::std::string * release_first ()
::std::string * release_second ()
const ::std::string & second () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_first (::std::string *first)
void set_allocated_second (::std::string *second)
void set_first (const ::std::string &value)
void set_first (const char *value)
void set_first (const char *value, size_t size)
void set_second (const ::std::string &value)
void set_second (const char *value)
void set_second (const char *value, size_t size)
void Swap (FuelMetadata_Categories *other)
Static Public Member Functions
static const FuelMetadata_Categories & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const FuelMetadata_Categories * internal_default_instance ()
Static Public Attributes
static const int kFirstFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kSecondFieldNumber = 2
Constructor & Destructor Documentation
FuelMetadata_Categories() [1/2]
FuelMetadata_Categories ()
~FuelMetadata_Categories()
virtual ~FuelMetadata_Categories () virtual
FuelMetadata_Categories() [2/2]
FuelMetadata_Categories (const FuelMetadata_Categories & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_first()
void clear_first () inline
clear_second()
void clear_second () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const FuelMetadata_Categories & from)
default_instance()
static const FuelMetadata_Categories& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
first()
const ::std::string & first () const inline
Referenced by FuelMetadata_Categories::set_allocated_first().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const FuelMetadata_Categories* internal_default_instance () inline static
References ignition::msgs::_FuelMetadata_Categories_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const FuelMetadata_Categories & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_first()
std::string * mutable_first () inline
mutable_second()
std::string * mutable_second () inline
New() [1/2]
FuelMetadata_Categories* New () const inline final
New() [2/2]
FuelMetadata_Categories* New (::google::protobuf::Arena * arena) const inline final
operator=()
FuelMetadata_Categories& operator= (const FuelMetadata_Categories & from) inline
release_first()
std::string * release_first () inline
release_second()
std::string * release_second () inline
second()
const ::std::string & second () const inline
Referenced by FuelMetadata_Categories::set_allocated_second().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_first()
void set_allocated_first (::std::string * first) inline
References FuelMetadata_Categories::first().
set_allocated_second()
void set_allocated_second (::std::string * second) inline
References FuelMetadata_Categories::second().
set_first() [1/3]
void set_first (const ::std::string & value) inline
set_first() [2/3]
void set_first (const char * value) inline
set_first() [3/3]
void set_first (const char * value, size_t size) inline
set_second() [1/3]
void set_second (const ::std::string & value) inline
set_second() [2/3]
void set_second (const char * value) inline
set_second() [3/3]
void set_second (const char * value, size_t size) inline
Swap()
void Swap (FuelMetadata_Categories * other)
Member Data Documentation
kFirstFieldNumber
const int kFirstFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    6
kSecondFieldNumber
const int kSecondFieldNumber = 2 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/fuel_metadata.pb.h