Gazebo Msgs: Shadows Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Shadows Class Reference
#include <shadows.pb.h>
Public Types
typedef Shadows_ShadowType ShadowType
Public Member Functions
Shadows ()
Shadows (const Shadows &from)
virtual ~Shadows ()
size_t ByteSizeLong () const final
void Clear () final
void clear_color ()
void clear_header ()
void clear_type ()
const ::ignition::msgs::Color & color () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Shadows &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_color () const
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Shadows &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Color * mutable_color ()
::ignition::msgs::Header * mutable_header ()
Shadows * New () const final
Shadows * New (::google::protobuf::Arena *arena) const final
Shadows & operator= (const Shadows &from)
::ignition::msgs::Color * release_color ()
::ignition::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_color (::ignition::msgs::Color *color)
void set_allocated_header (::ignition::msgs::Header *header)
void set_type (::ignition::msgs::Shadows_ShadowType value)
void Swap (Shadows *other)
::ignition::msgs::Shadows_ShadowType type () const
Static Public Member Functions
static const Shadows & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Shadows * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * ShadowType_descriptor ()
static bool ShadowType_IsValid (int value)
static const ::std::string & ShadowType_Name (ShadowType value)
static bool ShadowType_Parse (const ::std::string &name, ShadowType *value)
Static Public Attributes
static const int kColorFieldNumber = 3
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kTypeFieldNumber = 2
static const int ShadowType_ARRAYSIZE
static const ShadowType ShadowType_MAX
static const ShadowType ShadowType_MIN
static const ShadowType STENCIL_ADDITIVE
static const ShadowType STENCIL_MODULATIVE
static const ShadowType TEXTURE_ADDITIVE
static const ShadowType TEXTURE_MODULATIVE
Member Typedef Documentation
ShadowType
typedef Shadows_ShadowType ShadowType
Constructor & Destructor Documentation
Shadows() [1/2]
Shadows ()
~Shadows()
virtual ~Shadows () virtual
Shadows() [2/2]
Shadows (const Shadows & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_color()
void clear_color ()
clear_header()
void clear_header ()
clear_type()
void clear_type () inline
color()
const ::ignition::msgs::Color & color () const inline
References ignition::msgs::_Color_default_instance_.
Referenced by Shadows::set_allocated_color().
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Shadows & from)
default_instance()
static const Shadows& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_color()
bool has_color () const inline
References Shadows::internal_default_instance().
has_header()
bool has_header () const inline
References Shadows::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Shadows::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Shadows* internal_default_instance () inline static
References ignition::msgs::_Shadows_default_instance_.
Referenced by Shadows::has_color(), and Shadows::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Shadows & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_color()
ignition::msgs::Color * mutable_color () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
New() [1/2]
Shadows* New () const inline final
New() [2/2]
Shadows* New (::google::protobuf::Arena * arena) const inline final
operator=()
Shadows& operator= (const Shadows & from) inline
release_color()
ignition::msgs::Color * release_color () inline
release_header()
ignition::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_color()
void set_allocated_color (::ignition::msgs::Color * color) inline
References Shadows::color().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Shadows::header().
set_type()
void set_type (::ignition::msgs::Shadows_ShadowType value) inline
ShadowType_descriptor()
static const ::google::protobuf::EnumDescriptor* ShadowType_descriptor () inline static
References ignition::msgs::Shadows_ShadowType_descriptor().
ShadowType_IsValid()
static bool ShadowType_IsValid (int value) inline static
References ignition::msgs::Shadows_ShadowType_IsValid().
ShadowType_Name()
static const ::std::string& ShadowType_Name (ShadowType value) inline static
References ignition::msgs::Shadows_ShadowType_Name().
ShadowType_Parse()
static bool ShadowType_Parse (const ::std::string & name, ShadowType * value) inline static
References ignition::msgs::Shadows_ShadowType_Parse().
Swap()
void Swap (Shadows * other)
type()
ignition::msgs::Shadows_ShadowType type () const inline
Member Data Documentation
kColorFieldNumber
const int kColorFieldNumber = 3 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kTypeFieldNumber
const int kTypeFieldNumber = 2 static
ShadowType_ARRAYSIZE
const int ShadowType_ARRAYSIZE static
Initial value:
=
    Shadows_ShadowType_ShadowType_ARRAYSIZE
ShadowType_MAX
const ShadowType ShadowType_MAX static
Initial value:
=
    Shadows_ShadowType_ShadowType_MAX
ShadowType_MIN
const ShadowType ShadowType_MIN static
Initial value:
=
    Shadows_ShadowType_ShadowType_MIN
STENCIL_ADDITIVE
const ShadowType STENCIL_ADDITIVE static
Initial value:
=
    Shadows_ShadowType_STENCIL_ADDITIVE
STENCIL_MODULATIVE
const ShadowType STENCIL_MODULATIVE static
Initial value:
=
    Shadows_ShadowType_STENCIL_MODULATIVE
TEXTURE_ADDITIVE
const ShadowType TEXTURE_ADDITIVE static
Initial value:
=
    Shadows_ShadowType_TEXTURE_ADDITIVE
TEXTURE_MODULATIVE
const ShadowType TEXTURE_MODULATIVE static
Initial value:
=
    Shadows_ShadowType_TEXTURE_MODULATIVE
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/shadows.pb.h