Gazebo Msgs: ParameterError Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
ParameterError Class Reference
#include <parameter_error.pb.h>
Public Types
typedef ParameterError_Type Type
Public Member Functions
ParameterError ()
ParameterError (const ParameterError &from)
virtual ~ParameterError ()
size_t ByteSizeLong () const final
void Clear () final
void clear_data ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const ParameterError &from)
::ignition::msgs::ParameterError_Type data () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ParameterError &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
ParameterError * New () const final
ParameterError * New (::google::protobuf::Arena *arena) const final
ParameterError & operator= (const ParameterError &from)
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_data (::ignition::msgs::ParameterError_Type value)
void Swap (ParameterError *other)
Static Public Member Functions
static const ParameterError & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const ParameterError * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Type_descriptor ()
static bool Type_IsValid (int value)
static const ::std::string & Type_Name (Type value)
static bool Type_Parse (const ::std::string &name, Type *value)
Static Public Attributes
static const Type ALREADY_DECLARED
static const Type INVALID_TYPE
static const int kDataFieldNumber = 1
static constexpr int kIndexInFileMessages
static const Type NOT_DECLARED
static const Type SUCCESS
static const int Type_ARRAYSIZE
static const Type Type_MAX
static const Type Type_MIN
Member Typedef Documentation
Type
typedef ParameterError_Type Type
Constructor & Destructor Documentation
ParameterError() [1/2]
ParameterError ()
~ParameterError()
virtual ~ParameterError () virtual
ParameterError() [2/2]
ParameterError (const ParameterError & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_data()
void clear_data () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const ParameterError & from)
data()
ignition::msgs::ParameterError_Type data () const inline
default_instance()
static const ParameterError& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const ParameterError* internal_default_instance () inline static
References ignition::msgs::_ParameterError_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const ParameterError & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
New() [1/2]
ParameterError* New () const inline final
New() [2/2]
ParameterError* New (::google::protobuf::Arena * arena) const inline final
operator=()
ParameterError& operator= (const ParameterError & from) inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_data()
void set_data (::ignition::msgs::ParameterError_Type value) inline
Swap()
void Swap (ParameterError * other)
Type_descriptor()
static const ::google::protobuf::EnumDescriptor* Type_descriptor () inline static
References ignition::msgs::ParameterError_Type_descriptor().
Type_IsValid()
static bool Type_IsValid (int value) inline static
References ignition::msgs::ParameterError_Type_IsValid().
Type_Name()
static const ::std::string& Type_Name (Type value) inline static
References ignition::msgs::ParameterError_Type_Name().
Type_Parse()
static bool Type_Parse (const ::std::string & name, Type * value) inline static
References ignition::msgs::ParameterError_Type_Parse().
Member Data Documentation
ALREADY_DECLARED
const Type ALREADY_DECLARED static
Initial value:
=
    ParameterError_Type_ALREADY_DECLARED
INVALID_TYPE
const Type INVALID_TYPE static
Initial value:
=
    ParameterError_Type_INVALID_TYPE
kDataFieldNumber
const int kDataFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
NOT_DECLARED
const Type NOT_DECLARED static
Initial value:
=
    ParameterError_Type_NOT_DECLARED
SUCCESS
const Type SUCCESS static
Initial value:
=
    ParameterError_Type_SUCCESS
Type_ARRAYSIZE
const int Type_ARRAYSIZE static
Initial value:
=
    ParameterError_Type_Type_ARRAYSIZE
Type_MAX
const Type Type_MAX static
Initial value:
=
    ParameterError_Type_Type_MAX
Type_MIN
const Type Type_MIN static
Initial value:
=
    ParameterError_Type_Type_MIN
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/parameter_error.pb.h