Gazebo Msgs: JointAnimation Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
JointAnimation Class Reference
#include <joint_animation.pb.h>
Public Types
typedef JointAnimation_Joint Joint
Public Member Functions
JointAnimation ()
JointAnimation (const JointAnimation &from)
virtual ~JointAnimation ()
::ignition::msgs::JointAnimation_Joint * add_joint ()
::ignition::msgs::Time * add_time ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_joint ()
void clear_model_name ()
void clear_time ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const JointAnimation &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::JointAnimation_Joint > & joint () const
const ::ignition::msgs::JointAnimation_Joint & joint (int index) const
int joint_size () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const JointAnimation &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::std::string & model_name () const
::ignition::msgs::Header * mutable_header ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::JointAnimation_Joint > * mutable_joint ()
::ignition::msgs::JointAnimation_Joint * mutable_joint (int index)
::std::string * mutable_model_name ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Time > * mutable_time ()
::ignition::msgs::Time * mutable_time (int index)
JointAnimation * New () const final
JointAnimation * New (::google::protobuf::Arena *arena) const final
JointAnimation & operator= (const JointAnimation &from)
::ignition::msgs::Header * release_header ()
::std::string * release_model_name ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_model_name (::std::string *model_name)
void set_model_name (const ::std::string &value)
void set_model_name (const char *value)
void set_model_name (const char *value, size_t size)
void Swap (JointAnimation *other)
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Time > & time () const
const ::ignition::msgs::Time & time (int index) const
int time_size () const
Static Public Member Functions
static const JointAnimation & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const JointAnimation * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kJointFieldNumber = 3
static const int kModelNameFieldNumber = 2
static const int kTimeFieldNumber = 4
Member Typedef Documentation
Joint
typedef JointAnimation_Joint Joint
Constructor & Destructor Documentation
JointAnimation() [1/2]
JointAnimation ()
~JointAnimation()
virtual ~JointAnimation () virtual
JointAnimation() [2/2]
JointAnimation (const JointAnimation & from)
Member Function Documentation
add_joint()
ignition::msgs::JointAnimation_Joint * add_joint () inline
add_time()
ignition::msgs::Time * add_time () inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_joint()
void clear_joint () inline
clear_model_name()
void clear_model_name () inline
clear_time()
void clear_time ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const JointAnimation & from)
default_instance()
static const JointAnimation& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References JointAnimation::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by JointAnimation::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const JointAnimation* internal_default_instance () inline static
References ignition::msgs::_JointAnimation_default_instance_.
Referenced by JointAnimation::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
joint() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::JointAnimation_Joint > & joint () const inline
joint() [2/2]
const ::ignition::msgs::JointAnimation_Joint & joint (int index) const inline
joint_size()
int joint_size () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const JointAnimation & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
model_name()
const ::std::string & model_name () const inline
Referenced by JointAnimation::set_allocated_model_name().
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_joint() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::JointAnimation_Joint > * mutable_joint () inline
mutable_joint() [2/2]
ignition::msgs::JointAnimation_Joint * mutable_joint (int index) inline
mutable_model_name()
std::string * mutable_model_name () inline
mutable_time() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Time > * mutable_time () inline
mutable_time() [2/2]
ignition::msgs::Time * mutable_time (int index) inline
New() [1/2]
JointAnimation* New () const inline final
New() [2/2]
JointAnimation* New (::google::protobuf::Arena * arena) const inline final
operator=()
JointAnimation& operator= (const JointAnimation & from) inline
release_header()
ignition::msgs::Header * release_header () inline
release_model_name()
std::string * release_model_name () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References JointAnimation::header().
set_allocated_model_name()
void set_allocated_model_name (::std::string * model_name) inline
References JointAnimation::model_name().
set_model_name() [1/3]
void set_model_name (const ::std::string & value) inline
set_model_name() [2/3]
void set_model_name (const char * value) inline
set_model_name() [3/3]
void set_model_name (const char * value, size_t size) inline
Swap()
void Swap (JointAnimation * other)
time() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Time > & time () const inline
time() [2/2]
const ::ignition::msgs::Time & time (int index) const inline
time_size()
int time_size () const inline
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    1
kJointFieldNumber
const int kJointFieldNumber = 3 static
kModelNameFieldNumber
const int kModelNameFieldNumber = 2 static
kTimeFieldNumber
const int kTimeFieldNumber = 4 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/joint_animation.pb.h