Gazebo Msgs: JointTrajectory Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
JointTrajectory Class Reference
#include <joint_trajectory.pb.h>
Public Member Functions
JointTrajectory ()
JointTrajectory (const JointTrajectory &from)
virtual ~JointTrajectory ()
::std::string * add_joint_names ()
void add_joint_names (const ::std::string &value)
void add_joint_names (const char *value)
void add_joint_names (const char *value, size_t size)
::ignition::msgs::JointTrajectoryPoint * add_points ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_joint_names ()
void clear_points ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const JointTrajectory &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::google::protobuf::RepeatedPtrField< ::std::string > & joint_names () const
const ::std::string & joint_names (int index) const
int joint_names_size () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const JointTrajectory &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::ignition::msgs::Header * mutable_header ()
::google::protobuf::RepeatedPtrField< ::std::string > * mutable_joint_names ()
::std::string * mutable_joint_names (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::JointTrajectoryPoint > * mutable_points ()
::ignition::msgs::JointTrajectoryPoint * mutable_points (int index)
JointTrajectory * New () const final
JointTrajectory * New (::google::protobuf::Arena *arena) const final
JointTrajectory & operator= (const JointTrajectory &from)
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::JointTrajectoryPoint > & points () const
const ::ignition::msgs::JointTrajectoryPoint & points (int index) const
int points_size () const
::ignition::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_joint_names (int index, const ::std::string &value)
void set_joint_names (int index, const char *value)
void set_joint_names (int index, const char *value, size_t size)
void Swap (JointTrajectory *other)
Static Public Member Functions
static const JointTrajectory & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const JointTrajectory * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kJointNamesFieldNumber = 2
static const int kPointsFieldNumber = 3
Constructor & Destructor Documentation
JointTrajectory() [1/2]
JointTrajectory ()
~JointTrajectory()
virtual ~JointTrajectory () virtual
JointTrajectory() [2/2]
JointTrajectory (const JointTrajectory & from)
Member Function Documentation
add_joint_names() [1/4]
std::string * add_joint_names () inline
add_joint_names() [2/4]
void add_joint_names (const ::std::string & value) inline
add_joint_names() [3/4]
void add_joint_names (const char * value) inline
add_joint_names() [4/4]
void add_joint_names (const char * value, size_t size) inline
add_points()
ignition::msgs::JointTrajectoryPoint * add_points () inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_joint_names()
void clear_joint_names () inline
clear_points()
void clear_points ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const JointTrajectory & from)
default_instance()
static const JointTrajectory& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References JointTrajectory::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by JointTrajectory::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const JointTrajectory* internal_default_instance () inline static
References ignition::msgs::_JointTrajectory_default_instance_.
Referenced by JointTrajectory::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
joint_names() [1/2]
const ::google::protobuf::RepeatedPtrField<::std::string > & joint_names () const inline
joint_names() [2/2]
const ::std::string & joint_names (int index) const inline
joint_names_size()
int joint_names_size () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const JointTrajectory & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_joint_names() [1/2]
google::protobuf::RepeatedPtrField<::std::string > * mutable_joint_names () inline
mutable_joint_names() [2/2]
std::string * mutable_joint_names (int index) inline
mutable_points() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::JointTrajectoryPoint > * mutable_points () inline
mutable_points() [2/2]
ignition::msgs::JointTrajectoryPoint * mutable_points (int index) inline
New() [1/2]
JointTrajectory* New () const inline final
New() [2/2]
JointTrajectory* New (::google::protobuf::Arena * arena) const inline final
operator=()
JointTrajectory& operator= (const JointTrajectory & from) inline
points() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::JointTrajectoryPoint > & points () const inline
points() [2/2]
const ::ignition::msgs::JointTrajectoryPoint & points (int index) const inline
points_size()
int points_size () const inline
release_header()
ignition::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References JointTrajectory::header().
set_joint_names() [1/3]
void set_joint_names (int index, const ::std::string & value) inline
set_joint_names() [2/3]
void set_joint_names (int index, const char * value) inline
set_joint_names() [3/3]
void set_joint_names (int index, const char * value, size_t size) inline
Swap()
void Swap (JointTrajectory * other)
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kJointNamesFieldNumber
const int kJointNamesFieldNumber = 2 static
kPointsFieldNumber
const int kPointsFieldNumber = 3 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/joint_trajectory.pb.h