Gazebo Msgs: Tactile Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Tactile Class Reference
#include <tactile.pb.h>
Public Member Functions
Tactile ()
Tactile (const Tactile &from)
virtual ~Tactile ()
void add_collision_id (::google::protobuf::uint32 value)
::std::string * add_collision_name ()
void add_collision_name (const ::std::string &value)
void add_collision_name (const char *value)
void add_collision_name (const char *value, size_t size)
void add_pressure (double value)
size_t ByteSizeLong () const final
void Clear () final
void clear_collision_id ()
void clear_collision_name ()
void clear_header ()
void clear_pressure ()
const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > & collision_id () const
::google::protobuf::uint32 collision_id (int index) const
int collision_id_size () const
const ::google::protobuf::RepeatedPtrField< ::std::string > & collision_name () const
const ::std::string & collision_name (int index) const
int collision_name_size () const
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Tactile &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Tactile &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::google::protobuf::RepeatedField< ::google::protobuf::uint32 > * mutable_collision_id ()
::google::protobuf::RepeatedPtrField< ::std::string > * mutable_collision_name ()
::std::string * mutable_collision_name (int index)
::ignition::msgs::Header * mutable_header ()
::google::protobuf::RepeatedField< double > * mutable_pressure ()
Tactile * New () const final
Tactile * New (::google::protobuf::Arena *arena) const final
Tactile & operator= (const Tactile &from)
const ::google::protobuf::RepeatedField< double > & pressure () const
double pressure (int index) const
int pressure_size () const
::ignition::msgs::Header * release_header ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_collision_id (int index, ::google::protobuf::uint32 value)
void set_collision_name (int index, const ::std::string &value)
void set_collision_name (int index, const char *value)
void set_collision_name (int index, const char *value, size_t size)
void set_pressure (int index, double value)
void Swap (Tactile *other)
Static Public Member Functions
static const Tactile & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Tactile * internal_default_instance ()
Static Public Attributes
static const int kCollisionIdFieldNumber = 3
static const int kCollisionNameFieldNumber = 2
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kPressureFieldNumber = 4
Constructor & Destructor Documentation
Tactile() [1/2]
Tactile ()
~Tactile()
virtual ~Tactile () virtual
Tactile() [2/2]
Tactile (const Tactile & from)
Member Function Documentation
add_collision_id()
void add_collision_id (::google::protobuf::uint32 value) inline
add_collision_name() [1/4]
std::string * add_collision_name () inline
add_collision_name() [2/4]
void add_collision_name (const ::std::string & value) inline
add_collision_name() [3/4]
void add_collision_name (const char * value) inline
add_collision_name() [4/4]
void add_collision_name (const char * value, size_t size) inline
add_pressure()
void add_pressure (double value) inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_collision_id()
void clear_collision_id () inline
clear_collision_name()
void clear_collision_name () inline
clear_header()
void clear_header ()
clear_pressure()
void clear_pressure () inline
collision_id() [1/2]
const ::google::protobuf::RepeatedField<::google::protobuf::uint32 > & collision_id () const inline
collision_id() [2/2]
google::protobuf::uint32 collision_id (int index) const inline
collision_id_size()
int collision_id_size () const inline
collision_name() [1/2]
const ::google::protobuf::RepeatedPtrField<::std::string > & collision_name () const inline
collision_name() [2/2]
const ::std::string & collision_name (int index) const inline
collision_name_size()
int collision_name_size () const inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Tactile & from)
default_instance()
static const Tactile& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Tactile::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Tactile::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Tactile* internal_default_instance () inline static
References ignition::msgs::_Tactile_default_instance_.
Referenced by Tactile::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Tactile & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_collision_id()
google::protobuf::RepeatedField<::google::protobuf::uint32 > * mutable_collision_id () inline
mutable_collision_name() [1/2]
google::protobuf::RepeatedPtrField<::std::string > * mutable_collision_name () inline
mutable_collision_name() [2/2]
std::string * mutable_collision_name (int index) inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_pressure()
google::protobuf::RepeatedField< double > * mutable_pressure () inline
New() [1/2]
Tactile* New () const inline final
New() [2/2]
Tactile* New (::google::protobuf::Arena * arena) const inline final
operator=()
Tactile& operator= (const Tactile & from) inline
pressure() [1/2]
const ::google::protobuf::RepeatedField< double > & pressure () const inline
pressure() [2/2]
double pressure (int index) const inline
pressure_size()
int pressure_size () const inline
release_header()
ignition::msgs::Header * release_header () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Tactile::header().
set_collision_id()
void set_collision_id (int index, ::google::protobuf::uint32 value) inline
set_collision_name() [1/3]
void set_collision_name (int index, const ::std::string & value) inline
set_collision_name() [2/3]
void set_collision_name (int index, const char * value) inline
set_collision_name() [3/3]
void set_collision_name (int index, const char * value, size_t size) inline
set_pressure()
void set_pressure (int index, double value) inline
Swap()
void Swap (Tactile * other)
Member Data Documentation
kCollisionIdFieldNumber
const int kCollisionIdFieldNumber = 3 static
kCollisionNameFieldNumber
const int kCollisionNameFieldNumber = 2 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kPressureFieldNumber
const int kPressureFieldNumber = 4 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/tactile.pb.h