Gazebo Msgs: Publish Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Publish Class Reference
#include <publish.pb.h>
Public Member Functions
Publish ()
Publish (const Publish &from)
virtual ~Publish ()
size_t ByteSizeLong () const final
void Clear () final
void clear_header ()
void clear_host ()
void clear_msg_type ()
void clear_port ()
void clear_topic ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Publish &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
const ::ignition::msgs::Header & header () const
const ::std::string & host () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Publish &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::std::string & msg_type () const
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_host ()
::std::string * mutable_msg_type ()
::std::string * mutable_topic ()
Publish * New () const final
Publish * New (::google::protobuf::Arena *arena) const final
Publish & operator= (const Publish &from)
::google::protobuf::uint32 port () const
::ignition::msgs::Header * release_header ()
::std::string * release_host ()
::std::string * release_msg_type ()
::std::string * release_topic ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_host (::std::string *host)
void set_allocated_msg_type (::std::string *msg_type)
void set_allocated_topic (::std::string *topic)
void set_host (const ::std::string &value)
void set_host (const char *value)
void set_host (const char *value, size_t size)
void set_msg_type (const ::std::string &value)
void set_msg_type (const char *value)
void set_msg_type (const char *value, size_t size)
void set_port (::google::protobuf::uint32 value)
void set_topic (const ::std::string &value)
void set_topic (const char *value)
void set_topic (const char *value, size_t size)
void Swap (Publish *other)
const ::std::string & topic () const
Static Public Member Functions
static const Publish & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Publish * internal_default_instance ()
Static Public Attributes
static const int kHeaderFieldNumber = 1
static const int kHostFieldNumber = 4
static constexpr int kIndexInFileMessages
static const int kMsgTypeFieldNumber = 3
static const int kPortFieldNumber = 5
static const int kTopicFieldNumber = 2
Constructor & Destructor Documentation
Publish() [1/2]
Publish ()
~Publish()
virtual ~Publish () virtual
Publish() [2/2]
Publish (const Publish & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_header()
void clear_header ()
clear_host()
void clear_host () inline
clear_msg_type()
void clear_msg_type () inline
clear_port()
void clear_port () inline
clear_topic()
void clear_topic () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Publish & from)
default_instance()
static const Publish& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References Publish::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Publish::set_allocated_header().
host()
const ::std::string & host () const inline
Referenced by Publish::set_allocated_host().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Publish* internal_default_instance () inline static
References ignition::msgs::_Publish_default_instance_.
Referenced by Publish::has_header().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Publish & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
msg_type()
const ::std::string & msg_type () const inline
Referenced by Publish::set_allocated_msg_type().
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_host()
std::string * mutable_host () inline
mutable_msg_type()
std::string * mutable_msg_type () inline
mutable_topic()
std::string * mutable_topic () inline
New() [1/2]
Publish* New () const inline final
New() [2/2]
Publish* New (::google::protobuf::Arena * arena) const inline final
operator=()
Publish& operator= (const Publish & from) inline
port()
google::protobuf::uint32 port () const inline
release_header()
ignition::msgs::Header * release_header () inline
release_host()
std::string * release_host () inline
release_msg_type()
std::string * release_msg_type () inline
release_topic()
std::string * release_topic () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Publish::header().
set_allocated_host()
void set_allocated_host (::std::string * host) inline
References Publish::host().
set_allocated_msg_type()
void set_allocated_msg_type (::std::string * msg_type) inline
References Publish::msg_type().
set_allocated_topic()
void set_allocated_topic (::std::string * topic) inline
References Publish::topic().
set_host() [1/3]
void set_host (const ::std::string & value) inline
set_host() [2/3]
void set_host (const char * value) inline
set_host() [3/3]
void set_host (const char * value, size_t size) inline
set_msg_type() [1/3]
void set_msg_type (const ::std::string & value) inline
set_msg_type() [2/3]
void set_msg_type (const char * value) inline
set_msg_type() [3/3]
void set_msg_type (const char * value, size_t size) inline
set_port()
void set_port (::google::protobuf::uint32 value) inline
set_topic() [1/3]
void set_topic (const ::std::string & value) inline
set_topic() [2/3]
void set_topic (const char * value) inline
set_topic() [3/3]
void set_topic (const char * value, size_t size) inline
Swap()
void Swap (Publish * other)
topic()
const ::std::string & topic () const inline
Referenced by Publish::set_allocated_topic().
Member Data Documentation
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kHostFieldNumber
const int kHostFieldNumber = 4 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kMsgTypeFieldNumber
const int kMsgTypeFieldNumber = 3 static
kPortFieldNumber
const int kPortFieldNumber = 5 static
kTopicFieldNumber
const int kTopicFieldNumber = 2 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/publish.pb.h