Gazebo Msgs: FuelMetadata_World Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
FuelMetadata_World Class Reference
#include <fuel_metadata.pb.h>
Public Member Functions
FuelMetadata_World ()
FuelMetadata_World (const FuelMetadata_World &from)
virtual ~FuelMetadata_World ()
size_t ByteSizeLong () const final
void Clear () final
void clear_file ()
void clear_file_format ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const FuelMetadata_World &from)
const ::std::string & file () const
const ::ignition::msgs::VersionedName & file_format () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_file_format () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const FuelMetadata_World &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_file ()
::ignition::msgs::VersionedName * mutable_file_format ()
FuelMetadata_World * New () const final
FuelMetadata_World * New (::google::protobuf::Arena *arena) const final
FuelMetadata_World & operator= (const FuelMetadata_World &from)
::std::string * release_file ()
::ignition::msgs::VersionedName * release_file_format ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_file (::std::string *file)
void set_allocated_file_format (::ignition::msgs::VersionedName *file_format)
void set_file (const ::std::string &value)
void set_file (const char *value)
void set_file (const char *value, size_t size)
void Swap (FuelMetadata_World *other)
Static Public Member Functions
static const FuelMetadata_World & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const FuelMetadata_World * internal_default_instance ()
Static Public Attributes
static const int kFileFieldNumber = 1
static const int kFileFormatFieldNumber = 2
static constexpr int kIndexInFileMessages
Constructor & Destructor Documentation
FuelMetadata_World() [1/2]
FuelMetadata_World ()
~FuelMetadata_World()
virtual ~FuelMetadata_World () virtual
FuelMetadata_World() [2/2]
FuelMetadata_World (const FuelMetadata_World & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_file()
void clear_file () inline
clear_file_format()
void clear_file_format ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const FuelMetadata_World & from)
default_instance()
static const FuelMetadata_World& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
file()
const ::std::string & file () const inline
Referenced by FuelMetadata_World::set_allocated_file().
file_format()
const ::ignition::msgs::VersionedName & file_format () const inline
References ignition::msgs::_VersionedName_default_instance_.
Referenced by FuelMetadata_World::set_allocated_file_format().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_file_format()
bool has_file_format () const inline
References FuelMetadata_World::internal_default_instance().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const FuelMetadata_World* internal_default_instance () inline static
References ignition::msgs::_FuelMetadata_World_default_instance_.
Referenced by FuelMetadata_World::has_file_format().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const FuelMetadata_World & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_file()
std::string * mutable_file () inline
mutable_file_format()
ignition::msgs::VersionedName * mutable_file_format () inline
New() [1/2]
FuelMetadata_World* New () const inline final
New() [2/2]
FuelMetadata_World* New (::google::protobuf::Arena * arena) const inline final
operator=()
FuelMetadata_World& operator= (const FuelMetadata_World & from) inline
release_file()
std::string * release_file () inline
release_file_format()
ignition::msgs::VersionedName * release_file_format () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_file()
void set_allocated_file (::std::string * file) inline
References FuelMetadata_World::file().
set_allocated_file_format()
void set_allocated_file_format (::ignition::msgs::VersionedName * file_format) inline
References FuelMetadata_World::file_format().
set_file() [1/3]
void set_file (const ::std::string & value) inline
set_file() [2/3]
void set_file (const char * value) inline
set_file() [3/3]
void set_file (const char * value, size_t size) inline
Swap()
void Swap (FuelMetadata_World * other)
Member Data Documentation
kFileFieldNumber
const int kFileFieldNumber = 1 static
kFileFormatFieldNumber
const int kFileFormatFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    3
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/fuel_metadata.pb.h