Gazebo Msgs: SimEvent Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
SimEvent Class Reference
#include <sim_event.pb.h>
Public Member Functions
SimEvent ()
SimEvent (const SimEvent &from)
virtual ~SimEvent ()
size_t ByteSizeLong () const final
void Clear () final
void clear_data ()
void clear_header ()
void clear_id ()
void clear_name ()
void clear_type ()
void clear_world_statistics ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const SimEvent &from)
const ::std::string & data () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_header () const
bool has_world_statistics () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint32 id () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const SimEvent &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
::std::string * mutable_data ()
::ignition::msgs::Header * mutable_header ()
::std::string * mutable_name ()
::std::string * mutable_type ()
::ignition::msgs::WorldStatistics * mutable_world_statistics ()
const ::std::string & name () const
SimEvent * New () const final
SimEvent * New (::google::protobuf::Arena *arena) const final
SimEvent & operator= (const SimEvent &from)
::std::string * release_data ()
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
::std::string * release_type ()
::ignition::msgs::WorldStatistics * release_world_statistics ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_data (::std::string *data)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_type (::std::string *type)
void set_allocated_world_statistics (::ignition::msgs::WorldStatistics *world_statistics)
void set_data (const ::std::string &value)
void set_data (const char *value)
void set_data (const char *value, size_t size)
void set_id (::google::protobuf::uint32 value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_type (const ::std::string &value)
void set_type (const char *value)
void set_type (const char *value, size_t size)
void Swap (SimEvent *other)
const ::std::string & type () const
const ::ignition::msgs::WorldStatistics & world_statistics () const
Static Public Member Functions
static const SimEvent & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const SimEvent * internal_default_instance ()
Static Public Attributes
static const int kDataFieldNumber = 6
static const int kHeaderFieldNumber = 1
static const int kIdFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kNameFieldNumber = 4
static const int kTypeFieldNumber = 3
static const int kWorldStatisticsFieldNumber = 5
Constructor & Destructor Documentation
SimEvent() [1/2]
SimEvent ()
~SimEvent()
virtual ~SimEvent () virtual
SimEvent() [2/2]
SimEvent (const SimEvent & from)
Member Function Documentation
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_data()
void clear_data () inline
clear_header()
void clear_header ()
clear_id()
void clear_id () inline
clear_name()
void clear_name () inline
clear_type()
void clear_type () inline
clear_world_statistics()
void clear_world_statistics ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const SimEvent & from)
data()
const ::std::string & data () const inline
Referenced by SimEvent::set_allocated_data().
default_instance()
static const SimEvent& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_header()
bool has_header () const inline
References SimEvent::internal_default_instance().
has_world_statistics()
bool has_world_statistics () const inline
References SimEvent::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by SimEvent::set_allocated_header().
id()
google::protobuf::uint32 id () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const SimEvent* internal_default_instance () inline static
References ignition::msgs::_SimEvent_default_instance_.
Referenced by SimEvent::has_header(), and SimEvent::has_world_statistics().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const SimEvent & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
mutable_data()
std::string * mutable_data () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_name()
std::string * mutable_name () inline
mutable_type()
std::string * mutable_type () inline
mutable_world_statistics()
ignition::msgs::WorldStatistics * mutable_world_statistics () inline
name()
const ::std::string & name () const inline
Referenced by SimEvent::set_allocated_name().
New() [1/2]
SimEvent* New () const inline final
New() [2/2]
SimEvent* New (::google::protobuf::Arena * arena) const inline final
operator=()
SimEvent& operator= (const SimEvent & from) inline
release_data()
std::string * release_data () inline
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_type()
std::string * release_type () inline
release_world_statistics()
ignition::msgs::WorldStatistics * release_world_statistics () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_data()
void set_allocated_data (::std::string * data) inline
References SimEvent::data().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References SimEvent::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References SimEvent::name().
set_allocated_type()
void set_allocated_type (::std::string * type) inline
References SimEvent::type().
set_allocated_world_statistics()
void set_allocated_world_statistics (::ignition::msgs::WorldStatistics * world_statistics) inline
References SimEvent::world_statistics().
set_data() [1/3]
void set_data (const ::std::string & value) inline
set_data() [2/3]
void set_data (const char * value) inline
set_data() [3/3]
void set_data (const char * value, size_t size) inline
set_id()
void set_id (::google::protobuf::uint32 value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_type() [1/3]
void set_type (const ::std::string & value) inline
set_type() [2/3]
void set_type (const char * value) inline
set_type() [3/3]
void set_type (const char * value, size_t size) inline
Swap()
void Swap (SimEvent * other)
type()
const ::std::string & type () const inline
Referenced by SimEvent::set_allocated_type().
world_statistics()
const ::ignition::msgs::WorldStatistics & world_statistics () const inline
References ignition::msgs::_WorldStatistics_default_instance_.
Referenced by SimEvent::set_allocated_world_statistics().
Member Data Documentation
kDataFieldNumber
const int kDataFieldNumber = 6 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIdFieldNumber
const int kIdFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kNameFieldNumber
const int kNameFieldNumber = 4 static
kTypeFieldNumber
const int kTypeFieldNumber = 3 static
kWorldStatisticsFieldNumber
const int kWorldStatisticsFieldNumber = 5 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/sim_event.pb.h