Gazebo Msgs: Scene Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Scene Class Reference
#include <scene.pb.h>
Public Member Functions
Scene ()
Scene (const Scene &from)
virtual ~Scene ()
::ignition::msgs::Joint * add_joint ()
::ignition::msgs::Light * add_light ()
::ignition::msgs::Model * add_model ()
const ::ignition::msgs::Color & ambient () const
const ::ignition::msgs::Color & background () const
size_t ByteSizeLong () const final
void Clear () final
void clear_ambient ()
void clear_background ()
void clear_fog ()
void clear_grid ()
void clear_header ()
void clear_joint ()
void clear_light ()
void clear_model ()
void clear_name ()
void clear_origin_visual ()
void clear_shadow_caster_material_script ()
void clear_shadows ()
void clear_sky ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Scene &from)
const ::ignition::msgs::Fog & fog () const
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool grid () const
bool has_ambient () const
bool has_background () const
bool has_fog () const
bool has_header () const
bool has_shadow_caster_material_script () const
bool has_sky () const
const ::ignition::msgs::Header & header () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Joint > & joint () const
const ::ignition::msgs::Joint & joint (int index) const
int joint_size () const
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Light > & light () const
const ::ignition::msgs::Light & light (int index) const
int light_size () const
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Scene &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::google::protobuf::RepeatedPtrField< ::ignition::msgs::Model > & model () const
const ::ignition::msgs::Model & model (int index) const
int model_size () const
::ignition::msgs::Color * mutable_ambient ()
::ignition::msgs::Color * mutable_background ()
::ignition::msgs::Fog * mutable_fog ()
::ignition::msgs::Header * mutable_header ()
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Joint > * mutable_joint ()
::ignition::msgs::Joint * mutable_joint (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Light > * mutable_light ()
::ignition::msgs::Light * mutable_light (int index)
::google::protobuf::RepeatedPtrField< ::ignition::msgs::Model > * mutable_model ()
::ignition::msgs::Model * mutable_model (int index)
::std::string * mutable_name ()
::ignition::msgs::Material_Script * mutable_shadow_caster_material_script ()
::ignition::msgs::Sky * mutable_sky ()
const ::std::string & name () const
Scene * New () const final
Scene * New (::google::protobuf::Arena *arena) const final
Scene & operator= (const Scene &from)
bool origin_visual () const
::ignition::msgs::Color * release_ambient ()
::ignition::msgs::Color * release_background ()
::ignition::msgs::Fog * release_fog ()
::ignition::msgs::Header * release_header ()
::std::string * release_name ()
::ignition::msgs::Material_Script * release_shadow_caster_material_script ()
::ignition::msgs::Sky * release_sky ()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_allocated_ambient (::ignition::msgs::Color *ambient)
void set_allocated_background (::ignition::msgs::Color *background)
void set_allocated_fog (::ignition::msgs::Fog *fog)
void set_allocated_header (::ignition::msgs::Header *header)
void set_allocated_name (::std::string *name)
void set_allocated_shadow_caster_material_script (::ignition::msgs::Material_Script *shadow_caster_material_script)
void set_allocated_sky (::ignition::msgs::Sky *sky)
void set_grid (bool value)
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
void set_origin_visual (bool value)
void set_shadows (bool value)
const ::ignition::msgs::Material_Script & shadow_caster_material_script () const
bool shadows () const
const ::ignition::msgs::Sky & sky () const
void Swap (Scene *other)
Static Public Member Functions
static const Scene & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Scene * internal_default_instance ()
Static Public Attributes
static const int kAmbientFieldNumber = 3
static const int kBackgroundFieldNumber = 4
static const int kFogFieldNumber = 7
static const int kGridFieldNumber = 8
static const int kHeaderFieldNumber = 1
static constexpr int kIndexInFileMessages
static const int kJointFieldNumber = 11
static const int kLightFieldNumber = 10
static const int kModelFieldNumber = 9
static const int kNameFieldNumber = 2
static const int kOriginVisualFieldNumber = 12
static const int kShadowCasterMaterialScriptFieldNumber = 13
static const int kShadowsFieldNumber = 6
static const int kSkyFieldNumber = 5
Constructor & Destructor Documentation
Scene() [1/2]
Scene ()
~Scene()
virtual ~Scene () virtual
Scene() [2/2]
Scene (const Scene & from)
Member Function Documentation
add_joint()
ignition::msgs::Joint * add_joint () inline
add_light()
ignition::msgs::Light * add_light () inline
add_model()
ignition::msgs::Model * add_model () inline
ambient()
const ::ignition::msgs::Color & ambient () const inline
References ignition::msgs::_Color_default_instance_.
Referenced by Scene::set_allocated_ambient().
background()
const ::ignition::msgs::Color & background () const inline
References ignition::msgs::_Color_default_instance_.
Referenced by Scene::set_allocated_background().
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_ambient()
void clear_ambient ()
clear_background()
void clear_background ()
clear_fog()
void clear_fog ()
clear_grid()
void clear_grid () inline
clear_header()
void clear_header ()
clear_joint()
void clear_joint ()
clear_light()
void clear_light ()
clear_model()
void clear_model ()
clear_name()
void clear_name () inline
clear_origin_visual()
void clear_origin_visual () inline
clear_shadow_caster_material_script()
void clear_shadow_caster_material_script ()
clear_shadows()
void clear_shadows () inline
clear_sky()
void clear_sky ()
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Scene & from)
default_instance()
static const Scene& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
fog()
const ::ignition::msgs::Fog & fog () const inline
References ignition::msgs::_Fog_default_instance_.
Referenced by Scene::set_allocated_fog().
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
grid()
bool grid () const inline
has_ambient()
bool has_ambient () const inline
References Scene::internal_default_instance().
has_background()
bool has_background () const inline
References Scene::internal_default_instance().
has_fog()
bool has_fog () const inline
References Scene::internal_default_instance().
has_header()
bool has_header () const inline
References Scene::internal_default_instance().
has_shadow_caster_material_script()
bool has_shadow_caster_material_script () const inline
References Scene::internal_default_instance().
has_sky()
bool has_sky () const inline
References Scene::internal_default_instance().
header()
const ::ignition::msgs::Header & header () const inline
References ignition::msgs::_Header_default_instance_.
Referenced by Scene::set_allocated_header().
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Scene* internal_default_instance () inline static
References ignition::msgs::_Scene_default_instance_.
Referenced by Scene::has_ambient(), Scene::has_background(), Scene::has_fog(), Scene::has_header(), Scene::has_shadow_caster_material_script(), and Scene::has_sky().
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
joint() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Joint > & joint () const inline
joint() [2/2]
const ::ignition::msgs::Joint & joint (int index) const inline
joint_size()
int joint_size () const inline
light() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Light > & light () const inline
light() [2/2]
const ::ignition::msgs::Light & light (int index) const inline
light_size()
int light_size () const inline
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Scene & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
model() [1/2]
const ::google::protobuf::RepeatedPtrField<::ignition::msgs::Model > & model () const inline
model() [2/2]
const ::ignition::msgs::Model & model (int index) const inline
model_size()
int model_size () const inline
mutable_ambient()
ignition::msgs::Color * mutable_ambient () inline
mutable_background()
ignition::msgs::Color * mutable_background () inline
mutable_fog()
ignition::msgs::Fog * mutable_fog () inline
mutable_header()
ignition::msgs::Header * mutable_header () inline
mutable_joint() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Joint > * mutable_joint () inline
mutable_joint() [2/2]
ignition::msgs::Joint * mutable_joint (int index) inline
mutable_light() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Light > * mutable_light () inline
mutable_light() [2/2]
ignition::msgs::Light * mutable_light (int index) inline
mutable_model() [1/2]
google::protobuf::RepeatedPtrField<::ignition::msgs::Model > * mutable_model () inline
mutable_model() [2/2]
ignition::msgs::Model * mutable_model (int index) inline
mutable_name()
std::string * mutable_name () inline
mutable_shadow_caster_material_script()
ignition::msgs::Material_Script * mutable_shadow_caster_material_script () inline
mutable_sky()
ignition::msgs::Sky * mutable_sky () inline
name()
const ::std::string & name () const inline
Referenced by Scene::set_allocated_name().
New() [1/2]
Scene* New () const inline final
New() [2/2]
Scene* New (::google::protobuf::Arena * arena) const inline final
operator=()
Scene& operator= (const Scene & from) inline
origin_visual()
bool origin_visual () const inline
release_ambient()
ignition::msgs::Color * release_ambient () inline
release_background()
ignition::msgs::Color * release_background () inline
release_fog()
ignition::msgs::Fog * release_fog () inline
release_header()
ignition::msgs::Header * release_header () inline
release_name()
std::string * release_name () inline
release_shadow_caster_material_script()
ignition::msgs::Material_Script * release_shadow_caster_material_script () inline
release_sky()
ignition::msgs::Sky * release_sky () inline
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_allocated_ambient()
void set_allocated_ambient (::ignition::msgs::Color * ambient) inline
References Scene::ambient().
set_allocated_background()
void set_allocated_background (::ignition::msgs::Color * background) inline
References Scene::background().
set_allocated_fog()
void set_allocated_fog (::ignition::msgs::Fog * fog) inline
References Scene::fog().
set_allocated_header()
void set_allocated_header (::ignition::msgs::Header * header) inline
References Scene::header().
set_allocated_name()
void set_allocated_name (::std::string * name) inline
References Scene::name().
set_allocated_shadow_caster_material_script()
void set_allocated_shadow_caster_material_script (::ignition::msgs::Material_Script * shadow_caster_material_script) inline
References Scene::shadow_caster_material_script().
set_allocated_sky()
void set_allocated_sky (::ignition::msgs::Sky * sky) inline
References Scene::sky().
set_grid()
void set_grid (bool value) inline
set_name() [1/3]
void set_name (const ::std::string & value) inline
set_name() [2/3]
void set_name (const char * value) inline
set_name() [3/3]
void set_name (const char * value, size_t size) inline
set_origin_visual()
void set_origin_visual (bool value) inline
set_shadows()
void set_shadows (bool value) inline
shadow_caster_material_script()
const ::ignition::msgs::Material_Script & shadow_caster_material_script () const inline
References ignition::msgs::_Material_Script_default_instance_.
Referenced by Scene::set_allocated_shadow_caster_material_script().
shadows()
bool shadows () const inline
sky()
const ::ignition::msgs::Sky & sky () const inline
References ignition::msgs::_Sky_default_instance_.
Referenced by Scene::set_allocated_sky().
Swap()
void Swap (Scene * other)
Member Data Documentation
kAmbientFieldNumber
const int kAmbientFieldNumber = 3 static
kBackgroundFieldNumber
const int kBackgroundFieldNumber = 4 static
kFogFieldNumber
const int kFogFieldNumber = 7 static
kGridFieldNumber
const int kGridFieldNumber = 8 static
kHeaderFieldNumber
const int kHeaderFieldNumber = 1 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    0
kJointFieldNumber
const int kJointFieldNumber = 11 static
kLightFieldNumber
const int kLightFieldNumber = 10 static
kModelFieldNumber
const int kModelFieldNumber = 9 static
kNameFieldNumber
const int kNameFieldNumber = 2 static
kOriginVisualFieldNumber
const int kOriginVisualFieldNumber = 12 static
kShadowCasterMaterialScriptFieldNumber
const int kShadowCasterMaterialScriptFieldNumber = 13 static
kShadowsFieldNumber
const int kShadowsFieldNumber = 6 static
kSkyFieldNumber
const int kSkyFieldNumber = 5 static
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/scene.pb.h