Gazebo Msgs: Discovery_Publisher Class Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Discovery_Publisher Class Reference
#include <discovery.pb.h>
Public Types
typedef Discovery_Publisher_MessagePublisher MessagePublisher
enum PubTypeCase { kMsgPub = 6, kSrvPub = 7, PUB_TYPE_NOT_SET = 0 }
typedef Discovery_Publisher_Scope Scope
typedef Discovery_Publisher_ServicePublisher ServicePublisher
Public Member Functions
Discovery_Publisher ()
Discovery_Publisher (const Discovery_Publisher &from)
virtual ~Discovery_Publisher ()
const ::std::string & address () const
size_t ByteSizeLong () const final
void Clear () final
void clear_address ()
void clear_msg_pub ()
void clear_node_uuid ()
void clear_process_uuid ()
void clear_pub_type ()
void clear_scope ()
void clear_srv_pub ()
void clear_topic ()
void CopyFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const Discovery_Publisher &from)
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
bool has_msg_pub () const
bool has_srv_pub () const
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
bool IsInitialized () const final
void MergeFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const Discovery_Publisher &from)
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
const ::ignition::msgs::Discovery_Publisher_MessagePublisher & msg_pub () const
::std::string * mutable_address ()
::ignition::msgs::Discovery_Publisher_MessagePublisher * mutable_msg_pub ()
::std::string * mutable_node_uuid ()
::std::string * mutable_process_uuid ()
::ignition::msgs::Discovery_Publisher_ServicePublisher * mutable_srv_pub ()
::std::string * mutable_topic ()
Discovery_Publisher * New () const final
Discovery_Publisher * New (::google::protobuf::Arena *arena) const final
const ::std::string & node_uuid () const
Discovery_Publisher & operator= (const Discovery_Publisher &from)
const ::std::string & process_uuid () const
PubTypeCase pub_type_case () const
::std::string * release_address ()
::ignition::msgs::Discovery_Publisher_MessagePublisher * release_msg_pub ()
::std::string * release_node_uuid ()
::std::string * release_process_uuid ()
::ignition::msgs::Discovery_Publisher_ServicePublisher * release_srv_pub ()
::std::string * release_topic ()
::ignition::msgs::Discovery_Publisher_Scope scope () const
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
void set_address (const ::std::string &value)
void set_address (const char *value)
void set_address (const char *value, size_t size)
void set_allocated_address (::std::string *address)
void set_allocated_msg_pub (::ignition::msgs::Discovery_Publisher_MessagePublisher *msg_pub)
void set_allocated_node_uuid (::std::string *node_uuid)
void set_allocated_process_uuid (::std::string *process_uuid)
void set_allocated_srv_pub (::ignition::msgs::Discovery_Publisher_ServicePublisher *srv_pub)
void set_allocated_topic (::std::string *topic)
void set_node_uuid (const ::std::string &value)
void set_node_uuid (const char *value)
void set_node_uuid (const char *value, size_t size)
void set_process_uuid (const ::std::string &value)
void set_process_uuid (const char *value)
void set_process_uuid (const char *value, size_t size)
void set_scope (::ignition::msgs::Discovery_Publisher_Scope value)
void set_topic (const ::std::string &value)
void set_topic (const char *value)
void set_topic (const char *value, size_t size)
const ::ignition::msgs::Discovery_Publisher_ServicePublisher & srv_pub () const
void Swap (Discovery_Publisher *other)
const ::std::string & topic () const
Static Public Member Functions
static const Discovery_Publisher & default_instance ()
static const ::google::protobuf::Descriptor * descriptor ()
static void InitAsDefaultInstance ()
static const Discovery_Publisher * internal_default_instance ()
static const ::google::protobuf::EnumDescriptor * Scope_descriptor ()
static bool Scope_IsValid (int value)
static const ::std::string & Scope_Name (Scope value)
static bool Scope_Parse (const ::std::string &name, Scope *value)
Static Public Attributes
static const Scope ALL
static const Scope HOST
static const int kAddressFieldNumber = 2
static constexpr int kIndexInFileMessages
static const int kMsgPubFieldNumber = 6
static const int kNodeUuidFieldNumber = 4
static const int kProcessUuidFieldNumber = 3
static const int kScopeFieldNumber = 5
static const int kSrvPubFieldNumber = 7
static const int kTopicFieldNumber = 1
static const Scope PROCESS
static const int Scope_ARRAYSIZE
static const Scope Scope_MAX
static const Scope Scope_MIN
Member Typedef Documentation
MessagePublisher
typedef Discovery_Publisher_MessagePublisher MessagePublisher
Scope
typedef Discovery_Publisher_Scope Scope
ServicePublisher
typedef Discovery_Publisher_ServicePublisher ServicePublisher
Member Enumeration Documentation
PubTypeCase
enum PubTypeCase
Enumerator
kMsgPub
kSrvPub
PUB_TYPE_NOT_SET
Constructor & Destructor Documentation
Discovery_Publisher() [1/2]
Discovery_Publisher ()
~Discovery_Publisher()
virtual ~Discovery_Publisher () virtual
Discovery_Publisher() [2/2]
Discovery_Publisher (const Discovery_Publisher & from)
Member Function Documentation
address()
const ::std::string & address () const inline
ByteSizeLong()
size_t ByteSizeLong () const final
Clear()
void Clear () final
clear_address()
void clear_address () inline
clear_msg_pub()
void clear_msg_pub () inline
clear_node_uuid()
void clear_node_uuid () inline
clear_process_uuid()
void clear_process_uuid () inline
clear_pub_type()
void clear_pub_type ()
clear_scope()
void clear_scope () inline
clear_srv_pub()
void clear_srv_pub () inline
clear_topic()
void clear_topic () inline
CopyFrom() [1/2]
void CopyFrom (const ::google::protobuf::Message & from) final
CopyFrom() [2/2]
void CopyFrom (const Discovery_Publisher & from)
default_instance()
static const Discovery_Publisher& default_instance () static
descriptor()
static const ::google::protobuf::Descriptor* descriptor () static
GetCachedSize()
int GetCachedSize () const inline final
GetMetadata()
::google::protobuf::Metadata GetMetadata () const final
has_msg_pub()
bool has_msg_pub () const inline
has_srv_pub()
bool has_srv_pub () const inline
InitAsDefaultInstance()
static void InitAsDefaultInstance () static
internal_default_instance()
static const Discovery_Publisher* internal_default_instance () inline static
References ignition::msgs::_Discovery_Publisher_default_instance_.
InternalSerializeWithCachedSizesToArray()
::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
IsInitialized()
bool IsInitialized () const final
MergeFrom() [1/2]
void MergeFrom (const ::google::protobuf::Message & from) final
MergeFrom() [2/2]
void MergeFrom (const Discovery_Publisher & from)
MergePartialFromCodedStream()
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
msg_pub()
const ::ignition::msgs::Discovery_Publisher_MessagePublisher & msg_pub () const inline
References ignition::msgs::_Discovery_Publisher_MessagePublisher_default_instance_.
mutable_address()
std::string * mutable_address () inline
mutable_msg_pub()
ignition::msgs::Discovery_Publisher_MessagePublisher * mutable_msg_pub () inline
mutable_node_uuid()
std::string * mutable_node_uuid () inline
mutable_process_uuid()
std::string * mutable_process_uuid () inline
mutable_srv_pub()
ignition::msgs::Discovery_Publisher_ServicePublisher * mutable_srv_pub () inline
mutable_topic()
std::string * mutable_topic () inline
New() [1/2]
Discovery_Publisher* New () const inline final
New() [2/2]
Discovery_Publisher* New (::google::protobuf::Arena * arena) const inline final
node_uuid()
const ::std::string & node_uuid () const inline
operator=()
Discovery_Publisher& operator= (const Discovery_Publisher & from) inline
process_uuid()
const ::std::string & process_uuid () const inline
pub_type_case()
Discovery_Publisher::PubTypeCase pub_type_case () const inline
release_address()
std::string * release_address () inline
release_msg_pub()
ignition::msgs::Discovery_Publisher_MessagePublisher * release_msg_pub () inline
release_node_uuid()
std::string * release_node_uuid () inline
release_process_uuid()
std::string * release_process_uuid () inline
release_srv_pub()
ignition::msgs::Discovery_Publisher_ServicePublisher * release_srv_pub () inline
release_topic()
std::string * release_topic () inline
scope()
ignition::msgs::Discovery_Publisher_Scope scope () const inline
Scope_descriptor()
static const ::google::protobuf::EnumDescriptor* Scope_descriptor () inline static
References ignition::msgs::Discovery_Publisher_Scope_descriptor().
Scope_IsValid()
static bool Scope_IsValid (int value) inline static
References ignition::msgs::Discovery_Publisher_Scope_IsValid().
Scope_Name()
static const ::std::string& Scope_Name (Scope value) inline static
References ignition::msgs::Discovery_Publisher_Scope_Name().
Scope_Parse()
static bool Scope_Parse (const ::std::string & name, Scope * value) inline static
References ignition::msgs::Discovery_Publisher_Scope_Parse().
SerializeWithCachedSizes()
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
set_address() [1/3]
void set_address (const ::std::string & value) inline
set_address() [2/3]
void set_address (const char * value) inline
set_address() [3/3]
void set_address (const char * value, size_t size) inline
set_allocated_address()
void set_allocated_address (::std::string * address) inline
set_allocated_msg_pub()
void set_allocated_msg_pub (::ignition::msgs::Discovery_Publisher_MessagePublisher * msg_pub)
set_allocated_node_uuid()
void set_allocated_node_uuid (::std::string * node_uuid) inline
set_allocated_process_uuid()
void set_allocated_process_uuid (::std::string * process_uuid) inline
set_allocated_srv_pub()
void set_allocated_srv_pub (::ignition::msgs::Discovery_Publisher_ServicePublisher * srv_pub)
set_allocated_topic()
void set_allocated_topic (::std::string * topic) inline
set_node_uuid() [1/3]
void set_node_uuid (const ::std::string & value) inline
set_node_uuid() [2/3]
void set_node_uuid (const char * value) inline
set_node_uuid() [3/3]
void set_node_uuid (const char * value, size_t size) inline
set_process_uuid() [1/3]
void set_process_uuid (const ::std::string & value) inline
set_process_uuid() [2/3]
void set_process_uuid (const char * value) inline
set_process_uuid() [3/3]
void set_process_uuid (const char * value, size_t size) inline
set_scope()
void set_scope (::ignition::msgs::Discovery_Publisher_Scope value) inline
set_topic() [1/3]
void set_topic (const ::std::string & value) inline
set_topic() [2/3]
void set_topic (const char * value) inline
set_topic() [3/3]
void set_topic (const char * value, size_t size) inline
srv_pub()
const ::ignition::msgs::Discovery_Publisher_ServicePublisher & srv_pub () const inline
References ignition::msgs::_Discovery_Publisher_ServicePublisher_default_instance_.
Swap()
void Swap (Discovery_Publisher * other)
topic()
const ::std::string & topic () const inline
Member Data Documentation
ALL
const Scope ALL static
Initial value:
=
    Discovery_Publisher_Scope_ALL
HOST
const Scope HOST static
Initial value:
=
    Discovery_Publisher_Scope_HOST
kAddressFieldNumber
const int kAddressFieldNumber = 2 static
kIndexInFileMessages
constexpr int kIndexInFileMessages static constexpr
Initial value:
=
    4
kMsgPubFieldNumber
const int kMsgPubFieldNumber = 6 static
kNodeUuidFieldNumber
const int kNodeUuidFieldNumber = 4 static
kProcessUuidFieldNumber
const int kProcessUuidFieldNumber = 3 static
kScopeFieldNumber
const int kScopeFieldNumber = 5 static
kSrvPubFieldNumber
const int kSrvPubFieldNumber = 7 static
kTopicFieldNumber
const int kTopicFieldNumber = 1 static
PROCESS
const Scope PROCESS static
Initial value:
=
    Discovery_Publisher_Scope_PROCESS
Scope_ARRAYSIZE
const int Scope_ARRAYSIZE static
Initial value:
=
    Discovery_Publisher_Scope_Scope_ARRAYSIZE
Scope_MAX
const Scope Scope_MAX static
Initial value:
=
    Discovery_Publisher_Scope_Scope_MAX
Scope_MIN
const Scope Scope_MIN static
Initial value:
=
    Discovery_Publisher_Scope_Scope_MIN
The documentation for this class was generated from the following file:
build/ignition-msgs8/include/ignition/msgs/discovery.pb.h