Gazebo Msgs: google::protobuf Namespace Reference
Gazebo Msgs
API Reference
8.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
google::protobuf Namespace Reference
Classes
struct is_proto_enum< ::ignition::msgs::Any_ValueType >
struct is_proto_enum< ::ignition::msgs::Atmosphere_Type >
struct is_proto_enum< ::ignition::msgs::BatteryState_PowerSupplyStatus >
struct is_proto_enum< ::ignition::msgs::CameraInfo_Distortion_DistortionModelType >
struct is_proto_enum< ::ignition::msgs::Discovery_Publisher_Scope >
struct is_proto_enum< ::ignition::msgs::Discovery_Type >
struct is_proto_enum< ::ignition::msgs::Entity_Type >
struct is_proto_enum< ::ignition::msgs::Fog_FogType >
struct is_proto_enum< ::ignition::msgs::Geometry_Type >
struct is_proto_enum< ::ignition::msgs::Joint_Type >
struct is_proto_enum< ::ignition::msgs::Light_LightType >
struct is_proto_enum< ::ignition::msgs::LogStatus_LogFile_Units >
struct is_proto_enum< ::ignition::msgs::Marker_Action >
struct is_proto_enum< ::ignition::msgs::Marker_Type >
struct is_proto_enum< ::ignition::msgs::Marker_Visibility >
struct is_proto_enum< ::ignition::msgs::Material_PBR_WorkflowType >
struct is_proto_enum< ::ignition::msgs::Material_ShaderType >
struct is_proto_enum< ::ignition::msgs::ParameterError_Type >
struct is_proto_enum< ::ignition::msgs::ParticleEmitter_EmitterType >
struct is_proto_enum< ::ignition::msgs::Physics_Type >
struct is_proto_enum< ::ignition::msgs::PixelFormatType >
struct is_proto_enum< ::ignition::msgs::PointCloudPacked_Field_DataType >
struct is_proto_enum< ::ignition::msgs::RestResponse_Type >
struct is_proto_enum< ::ignition::msgs::SensorNoise_Type >
struct is_proto_enum< ::ignition::msgs::Shadows_ShadowType >
struct is_proto_enum< ::ignition::msgs::SphericalCoordinates_SurfaceModel >
struct is_proto_enum< ::ignition::msgs::Statistic_DataType >
struct is_proto_enum< ::ignition::msgs::UserCmd_Type >
struct is_proto_enum< ::ignition::msgs::Visual_Type >
Functions
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Actor * Arena::CreateMaybeMessage<::ignition::msgs::Actor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Actor_Animation * Arena::CreateMaybeMessage<::ignition::msgs::Actor_Animation > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Actor_Trajectory * Arena::CreateMaybeMessage<::ignition::msgs::Actor_Trajectory > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Actor_Waypoint * Arena::CreateMaybeMessage<::ignition::msgs::Actor_Waypoint > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Actuators * Arena::CreateMaybeMessage<::ignition::msgs::Actuators > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::AirPressureSensor * Arena::CreateMaybeMessage<::ignition::msgs::AirPressureSensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Altimeter * Arena::CreateMaybeMessage<::ignition::msgs::Altimeter > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::AltimeterSensor * Arena::CreateMaybeMessage<::ignition::msgs::AltimeterSensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::AnnotatedAxisAligned2DBox * Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedAxisAligned2DBox > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::AnnotatedAxisAligned2DBox_V * Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedAxisAligned2DBox_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::AnnotatedOriented3DBox * Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedOriented3DBox > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::AnnotatedOriented3DBox_V * Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedOriented3DBox_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Any * Arena::CreateMaybeMessage<::ignition::msgs::Any > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Atmosphere * Arena::CreateMaybeMessage<::ignition::msgs::Atmosphere > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Axis * Arena::CreateMaybeMessage<::ignition::msgs::Axis > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::AxisAligned2DBox * Arena::CreateMaybeMessage<::ignition::msgs::AxisAligned2DBox > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::AxisAlignedBox * Arena::CreateMaybeMessage<::ignition::msgs::AxisAlignedBox > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Battery * Arena::CreateMaybeMessage<::ignition::msgs::Battery > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::BatteryState * Arena::CreateMaybeMessage<::ignition::msgs::BatteryState > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Boolean * Arena::CreateMaybeMessage<::ignition::msgs::Boolean > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::BoxGeom * Arena::CreateMaybeMessage<::ignition::msgs::BoxGeom > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Bytes * Arena::CreateMaybeMessage<::ignition::msgs::Bytes > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraCmd * Arena::CreateMaybeMessage<::ignition::msgs::CameraCmd > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraInfo * Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraInfo_Distortion * Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo_Distortion > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraInfo_Intrinsics * Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo_Intrinsics > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraInfo_Projection * Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo_Projection > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraLens * Arena::CreateMaybeMessage<::ignition::msgs::CameraLens > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraSensor * Arena::CreateMaybeMessage<::ignition::msgs::CameraSensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::CapsuleGeom * Arena::CreateMaybeMessage<::ignition::msgs::CapsuleGeom > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Cessna * Arena::CreateMaybeMessage<::ignition::msgs::Cessna > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Clock * Arena::CreateMaybeMessage<::ignition::msgs::Clock > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::CmdVel2D * Arena::CreateMaybeMessage<::ignition::msgs::CmdVel2D > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Collision * Arena::CreateMaybeMessage<::ignition::msgs::Collision > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Color * Arena::CreateMaybeMessage<::ignition::msgs::Color > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ConeGeom * Arena::CreateMaybeMessage<::ignition::msgs::ConeGeom > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Contact * Arena::CreateMaybeMessage<::ignition::msgs::Contact > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Contacts * Arena::CreateMaybeMessage<::ignition::msgs::Contacts > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ContactSensor * Arena::CreateMaybeMessage<::ignition::msgs::ContactSensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::CylinderGeom * Arena::CreateMaybeMessage<::ignition::msgs::CylinderGeom > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Dataframe * Arena::CreateMaybeMessage<::ignition::msgs::Dataframe > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Density * Arena::CreateMaybeMessage<::ignition::msgs::Density > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Diagnostics * Arena::CreateMaybeMessage<::ignition::msgs::Diagnostics > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Diagnostics_DiagTime * Arena::CreateMaybeMessage<::ignition::msgs::Diagnostics_DiagTime > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery * Arena::CreateMaybeMessage<::ignition::msgs::Discovery > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery_Flags * Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Flags > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery_Publisher * Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Publisher > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery_Publisher_MessagePublisher * Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Publisher_MessagePublisher > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery_Publisher_ServicePublisher * Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Publisher_ServicePublisher > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery_Subscriber * Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Subscriber > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Distortion * Arena::CreateMaybeMessage<::ignition::msgs::Distortion > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Double * Arena::CreateMaybeMessage<::ignition::msgs::Double > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Double_V * Arena::CreateMaybeMessage<::ignition::msgs::Double_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Duration * Arena::CreateMaybeMessage<::ignition::msgs::Duration > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::EllipsoidGeom * Arena::CreateMaybeMessage<::ignition::msgs::EllipsoidGeom > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Empty * Arena::CreateMaybeMessage<::ignition::msgs::Empty > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Entity * Arena::CreateMaybeMessage<::ignition::msgs::Entity > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::EntityFactory * Arena::CreateMaybeMessage<::ignition::msgs::EntityFactory > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::EntityFactory_V * Arena::CreateMaybeMessage<::ignition::msgs::EntityFactory_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::EntityPlugin_V * Arena::CreateMaybeMessage<::ignition::msgs::EntityPlugin_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::EntityWrench * Arena::CreateMaybeMessage<::ignition::msgs::EntityWrench > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Float * Arena::CreateMaybeMessage<::ignition::msgs::Float > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Float_V * Arena::CreateMaybeMessage<::ignition::msgs::Float_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Fluid * Arena::CreateMaybeMessage<::ignition::msgs::Fluid > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::FluidPressure * Arena::CreateMaybeMessage<::ignition::msgs::FluidPressure > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Fog * Arena::CreateMaybeMessage<::ignition::msgs::Fog > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Friction * Arena::CreateMaybeMessage<::ignition::msgs::Friction > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Friction_Torsional * Arena::CreateMaybeMessage<::ignition::msgs::Friction_Torsional > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Friction_Torsional_ODE * Arena::CreateMaybeMessage<::ignition::msgs::Friction_Torsional_ODE > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata * Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_AnnotationsEntry_DoNotUse * Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_AnnotationsEntry_DoNotUse > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Categories * Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Categories > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Compatibility * Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Compatibility > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Contact * Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Contact > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Dependency * Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Dependency > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Legal * Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Legal > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Model * Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Model > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_World * Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_World > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Geometry * Arena::CreateMaybeMessage<::ignition::msgs::Geometry > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::GPS * Arena::CreateMaybeMessage<::ignition::msgs::GPS > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::GPSSensor * Arena::CreateMaybeMessage<::ignition::msgs::GPSSensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::GPSSensor_Sensing * Arena::CreateMaybeMessage<::ignition::msgs::GPSSensor_Sensing > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::GUI * Arena::CreateMaybeMessage<::ignition::msgs::GUI > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::GUICamera * Arena::CreateMaybeMessage<::ignition::msgs::GUICamera > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Header * Arena::CreateMaybeMessage<::ignition::msgs::Header > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Header_Map * Arena::CreateMaybeMessage<::ignition::msgs::Header_Map > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::HeightmapGeom * Arena::CreateMaybeMessage<::ignition::msgs::HeightmapGeom > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::HeightmapGeom_Blend * Arena::CreateMaybeMessage<::ignition::msgs::HeightmapGeom_Blend > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::HeightmapGeom_Texture * Arena::CreateMaybeMessage<::ignition::msgs::HeightmapGeom_Texture > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Hydra * Arena::CreateMaybeMessage<::ignition::msgs::Hydra > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Hydra_Paddle * Arena::CreateMaybeMessage<::ignition::msgs::Hydra_Paddle > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Image * Arena::CreateMaybeMessage<::ignition::msgs::Image > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ImageGeom * Arena::CreateMaybeMessage<::ignition::msgs::ImageGeom > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::IMU * Arena::CreateMaybeMessage<::ignition::msgs::IMU > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::IMUSensor * Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::IMUSensor_AngularVelocity * Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor_AngularVelocity > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::IMUSensor_LinearAcceleration * Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor_LinearAcceleration > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::IMUSensor_OrientationReferenceFrame * Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor_OrientationReferenceFrame > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Inertial * Arena::CreateMaybeMessage<::ignition::msgs::Inertial > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Int32 * Arena::CreateMaybeMessage<::ignition::msgs::Int32 > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Int32_V * Arena::CreateMaybeMessage<::ignition::msgs::Int32_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Int64 * Arena::CreateMaybeMessage<::ignition::msgs::Int64 > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Int64_V * Arena::CreateMaybeMessage<::ignition::msgs::Int64_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Joint * Arena::CreateMaybeMessage<::ignition::msgs::Joint > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Joint_Gearbox * Arena::CreateMaybeMessage<::ignition::msgs::Joint_Gearbox > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Joint_Screw * Arena::CreateMaybeMessage<::ignition::msgs::Joint_Screw > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointAnimation * Arena::CreateMaybeMessage<::ignition::msgs::JointAnimation > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointAnimation_Joint * Arena::CreateMaybeMessage<::ignition::msgs::JointAnimation_Joint > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointCmd * Arena::CreateMaybeMessage<::ignition::msgs::JointCmd > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointTrajectory * Arena::CreateMaybeMessage<::ignition::msgs::JointTrajectory > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointTrajectoryPoint * Arena::CreateMaybeMessage<::ignition::msgs::JointTrajectoryPoint > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointWrench * Arena::CreateMaybeMessage<::ignition::msgs::JointWrench > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Joy * Arena::CreateMaybeMessage<::ignition::msgs::Joy > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Joystick * Arena::CreateMaybeMessage<::ignition::msgs::Joystick > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LaserScan * Arena::CreateMaybeMessage<::ignition::msgs::LaserScan > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LidarSensor * Arena::CreateMaybeMessage<::ignition::msgs::LidarSensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Light * Arena::CreateMaybeMessage<::ignition::msgs::Light > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Link * Arena::CreateMaybeMessage<::ignition::msgs::Link > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LinkData * Arena::CreateMaybeMessage<::ignition::msgs::LinkData > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogControl * Arena::CreateMaybeMessage<::ignition::msgs::LogControl > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogicalCameraImage * Arena::CreateMaybeMessage<::ignition::msgs::LogicalCameraImage > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogicalCameraImage_Model * Arena::CreateMaybeMessage<::ignition::msgs::LogicalCameraImage_Model > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogicalCameraSensor * Arena::CreateMaybeMessage<::ignition::msgs::LogicalCameraSensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogPlaybackControl * Arena::CreateMaybeMessage<::ignition::msgs::LogPlaybackControl > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogPlaybackStatistics * Arena::CreateMaybeMessage<::ignition::msgs::LogPlaybackStatistics > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogStatus * Arena::CreateMaybeMessage<::ignition::msgs::LogStatus > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogStatus_LogFile * Arena::CreateMaybeMessage<::ignition::msgs::LogStatus_LogFile > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Magnetometer * Arena::CreateMaybeMessage<::ignition::msgs::Magnetometer > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::MagnetometerSensor * Arena::CreateMaybeMessage<::ignition::msgs::MagnetometerSensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Marker * Arena::CreateMaybeMessage<::ignition::msgs::Marker > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Marker_V * Arena::CreateMaybeMessage<::ignition::msgs::Marker_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Material * Arena::CreateMaybeMessage<::ignition::msgs::Material > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Material_PBR * Arena::CreateMaybeMessage<::ignition::msgs::Material_PBR > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Material_Script * Arena::CreateMaybeMessage<::ignition::msgs::Material_Script > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::MeshGeom * Arena::CreateMaybeMessage<::ignition::msgs::MeshGeom > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Metric * Arena::CreateMaybeMessage<::ignition::msgs::Metric > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Model * Arena::CreateMaybeMessage<::ignition::msgs::Model > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Model_V * Arena::CreateMaybeMessage<::ignition::msgs::Model_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ModelConfiguration * Arena::CreateMaybeMessage<::ignition::msgs::ModelConfiguration > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::NavSat * Arena::CreateMaybeMessage<::ignition::msgs::NavSat > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::NavSatSensor * Arena::CreateMaybeMessage<::ignition::msgs::NavSatSensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::NavSatSensor_Sensing * Arena::CreateMaybeMessage<::ignition::msgs::NavSatSensor_Sensing > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::OccupancyGrid * Arena::CreateMaybeMessage<::ignition::msgs::OccupancyGrid > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::OccupancyGrid_MapMetaInfo * Arena::CreateMaybeMessage<::ignition::msgs::OccupancyGrid_MapMetaInfo > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Odometry * Arena::CreateMaybeMessage<::ignition::msgs::Odometry > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::OdometryWithCovariance * Arena::CreateMaybeMessage<::ignition::msgs::OdometryWithCovariance > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Oriented3DBox * Arena::CreateMaybeMessage<::ignition::msgs::Oriented3DBox > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Packet * Arena::CreateMaybeMessage<::ignition::msgs::Packet > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Param * Arena::CreateMaybeMessage<::ignition::msgs::Param > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Param_ParamsEntry_DoNotUse * Arena::CreateMaybeMessage<::ignition::msgs::Param_ParamsEntry_DoNotUse > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Param_V * Arena::CreateMaybeMessage<::ignition::msgs::Param_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Parameter * Arena::CreateMaybeMessage<::ignition::msgs::Parameter > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParameterDeclaration * Arena::CreateMaybeMessage<::ignition::msgs::ParameterDeclaration > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParameterDeclarations * Arena::CreateMaybeMessage<::ignition::msgs::ParameterDeclarations > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParameterError * Arena::CreateMaybeMessage<::ignition::msgs::ParameterError > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParameterName * Arena::CreateMaybeMessage<::ignition::msgs::ParameterName > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParameterValue * Arena::CreateMaybeMessage<::ignition::msgs::ParameterValue > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParticleEmitter * Arena::CreateMaybeMessage<::ignition::msgs::ParticleEmitter > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParticleEmitter_V * Arena::CreateMaybeMessage<::ignition::msgs::ParticleEmitter_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PerformanceSensorMetrics * Arena::CreateMaybeMessage<::ignition::msgs::PerformanceSensorMetrics > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Physics * Arena::CreateMaybeMessage<::ignition::msgs::Physics > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PID * Arena::CreateMaybeMessage<::ignition::msgs::PID > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PlaneGeom * Arena::CreateMaybeMessage<::ignition::msgs::PlaneGeom > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Plugin * Arena::CreateMaybeMessage<::ignition::msgs::Plugin > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Plugin_V * Arena::CreateMaybeMessage<::ignition::msgs::Plugin_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PointCloud * Arena::CreateMaybeMessage<::ignition::msgs::PointCloud > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PointCloudPacked * Arena::CreateMaybeMessage<::ignition::msgs::PointCloudPacked > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PointCloudPacked_Field * Arena::CreateMaybeMessage<::ignition::msgs::PointCloudPacked_Field > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Polyline * Arena::CreateMaybeMessage<::ignition::msgs::Polyline > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Pose * Arena::CreateMaybeMessage<::ignition::msgs::Pose > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Pose_V * Arena::CreateMaybeMessage<::ignition::msgs::Pose_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PoseAnimation * Arena::CreateMaybeMessage<::ignition::msgs::PoseAnimation > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PoseTrajectory * Arena::CreateMaybeMessage<::ignition::msgs::PoseTrajectory > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PoseWithCovariance * Arena::CreateMaybeMessage<::ignition::msgs::PoseWithCovariance > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Projector * Arena::CreateMaybeMessage<::ignition::msgs::Projector > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PropagationGrid * Arena::CreateMaybeMessage<::ignition::msgs::PropagationGrid > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::PropagationParticle * Arena::CreateMaybeMessage<::ignition::msgs::PropagationParticle > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Publish * Arena::CreateMaybeMessage<::ignition::msgs::Publish > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Publishers * Arena::CreateMaybeMessage<::ignition::msgs::Publishers > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Quaternion * Arena::CreateMaybeMessage<::ignition::msgs::Quaternion > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::RaySensor * Arena::CreateMaybeMessage<::ignition::msgs::RaySensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Request * Arena::CreateMaybeMessage<::ignition::msgs::Request > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Response * Arena::CreateMaybeMessage<::ignition::msgs::Response > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::RestLogin * Arena::CreateMaybeMessage<::ignition::msgs::RestLogin > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::RestLogout * Arena::CreateMaybeMessage<::ignition::msgs::RestLogout > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::RestPost * Arena::CreateMaybeMessage<::ignition::msgs::RestPost > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::RestResponse * Arena::CreateMaybeMessage<::ignition::msgs::RestResponse > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Road * Arena::CreateMaybeMessage<::ignition::msgs::Road > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Scene * Arena::CreateMaybeMessage<::ignition::msgs::Scene > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SdfGeneratorConfig * Arena::CreateMaybeMessage<::ignition::msgs::SdfGeneratorConfig > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SdfGeneratorConfig_EntityGeneratorConfig * Arena::CreateMaybeMessage<::ignition::msgs::SdfGeneratorConfig_EntityGeneratorConfig > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SdfGeneratorConfig_OverrideEntityGenConfigsEntry_DoNotUse * Arena::CreateMaybeMessage<::ignition::msgs::SdfGeneratorConfig_OverrideEntityGenConfigsEntry_DoNotUse > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Selection * Arena::CreateMaybeMessage<::ignition::msgs::Selection > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Sensor * Arena::CreateMaybeMessage<::ignition::msgs::Sensor > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Sensor_V * Arena::CreateMaybeMessage<::ignition::msgs::Sensor_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SensorNoise * Arena::CreateMaybeMessage<::ignition::msgs::SensorNoise > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedComponent * Arena::CreateMaybeMessage<::ignition::msgs::SerializedComponent > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedEntity * Arena::CreateMaybeMessage<::ignition::msgs::SerializedEntity > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedEntityMap * Arena::CreateMaybeMessage<::ignition::msgs::SerializedEntityMap > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedEntityMap_ComponentsEntry_DoNotUse * Arena::CreateMaybeMessage<::ignition::msgs::SerializedEntityMap_ComponentsEntry_DoNotUse > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedState * Arena::CreateMaybeMessage<::ignition::msgs::SerializedState > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedStateMap * Arena::CreateMaybeMessage<::ignition::msgs::SerializedStateMap > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedStateMap_EntitiesEntry_DoNotUse * Arena::CreateMaybeMessage<::ignition::msgs::SerializedStateMap_EntitiesEntry_DoNotUse > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedStep * Arena::CreateMaybeMessage<::ignition::msgs::SerializedStep > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedStepMap * Arena::CreateMaybeMessage<::ignition::msgs::SerializedStepMap > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::ServerControl * Arena::CreateMaybeMessage<::ignition::msgs::ServerControl > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Shadows * Arena::CreateMaybeMessage<::ignition::msgs::Shadows > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SimEvent * Arena::CreateMaybeMessage<::ignition::msgs::SimEvent > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Sky * Arena::CreateMaybeMessage<::ignition::msgs::Sky > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Sonar * Arena::CreateMaybeMessage<::ignition::msgs::Sonar > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SphereGeom * Arena::CreateMaybeMessage<::ignition::msgs::SphereGeom > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::SphericalCoordinates * Arena::CreateMaybeMessage<::ignition::msgs::SphericalCoordinates > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Statistic * Arena::CreateMaybeMessage<::ignition::msgs::Statistic > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::StatisticsGroup * Arena::CreateMaybeMessage<::ignition::msgs::StatisticsGroup > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::StringMsg * Arena::CreateMaybeMessage<::ignition::msgs::StringMsg > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::StringMsg_V * Arena::CreateMaybeMessage<::ignition::msgs::StringMsg_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Subscribe * Arena::CreateMaybeMessage<::ignition::msgs::Subscribe > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Surface * Arena::CreateMaybeMessage<::ignition::msgs::Surface > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Tactile * Arena::CreateMaybeMessage<::ignition::msgs::Tactile > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Test * Arena::CreateMaybeMessage<::ignition::msgs::Test > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Time * Arena::CreateMaybeMessage<::ignition::msgs::Time > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::TopicInfo * Arena::CreateMaybeMessage<::ignition::msgs::TopicInfo > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::TrackVisual * Arena::CreateMaybeMessage<::ignition::msgs::TrackVisual > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Twist * Arena::CreateMaybeMessage<::ignition::msgs::Twist > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::TwistWithCovariance * Arena::CreateMaybeMessage<::ignition::msgs::TwistWithCovariance > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::UInt32 * Arena::CreateMaybeMessage<::ignition::msgs::UInt32 > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::UInt32_V * Arena::CreateMaybeMessage<::ignition::msgs::UInt32_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::UInt64 * Arena::CreateMaybeMessage<::ignition::msgs::UInt64 > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::UInt64_V * Arena::CreateMaybeMessage<::ignition::msgs::UInt64_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::UndoRedo * Arena::CreateMaybeMessage<::ignition::msgs::UndoRedo > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::UserCmd * Arena::CreateMaybeMessage<::ignition::msgs::UserCmd > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::UserCmdStats * Arena::CreateMaybeMessage<::ignition::msgs::UserCmdStats > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Vector2d * Arena::CreateMaybeMessage<::ignition::msgs::Vector2d > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Vector3d * Arena::CreateMaybeMessage<::ignition::msgs::Vector3d > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Version * Arena::CreateMaybeMessage<::ignition::msgs::Version > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::VersionedName * Arena::CreateMaybeMessage<::ignition::msgs::VersionedName > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::VersionRange * Arena::CreateMaybeMessage<::ignition::msgs::VersionRange > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::VideoRecord * Arena::CreateMaybeMessage<::ignition::msgs::VideoRecord > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Visual * Arena::CreateMaybeMessage<::ignition::msgs::Visual > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Visual_Meta * Arena::CreateMaybeMessage<::ignition::msgs::Visual_Meta > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Visual_V * Arena::CreateMaybeMessage<::ignition::msgs::Visual_V > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::WebRequest * Arena::CreateMaybeMessage<::ignition::msgs::WebRequest > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::WheelSlipParametersCmd * Arena::CreateMaybeMessage<::ignition::msgs::WheelSlipParametersCmd > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Wind * Arena::CreateMaybeMessage<::ignition::msgs::Wind > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::WirelessNode * Arena::CreateMaybeMessage<::ignition::msgs::WirelessNode > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::WirelessNodes * Arena::CreateMaybeMessage<::ignition::msgs::WirelessNodes > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::WorldControl * Arena::CreateMaybeMessage<::ignition::msgs::WorldControl > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::WorldControlState * Arena::CreateMaybeMessage<::ignition::msgs::WorldControlState > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::WorldModify * Arena::CreateMaybeMessage<::ignition::msgs::WorldModify > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::WorldReset * Arena::CreateMaybeMessage<::ignition::msgs::WorldReset > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::WorldStatistics * Arena::CreateMaybeMessage<::ignition::msgs::WorldStatistics > (Arena *)
template<>
IGNITION_MSGS_VISIBLE ::ignition::msgs::Wrench * Arena::CreateMaybeMessage<::ignition::msgs::Wrench > (Arena *)
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Any_ValueType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Atmosphere_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::BatteryState_PowerSupplyStatus > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::CameraInfo_Distortion_DistortionModelType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Discovery_Publisher_Scope > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Discovery_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Entity_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Fog_FogType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Geometry_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Joint_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Light_LightType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::LogStatus_LogFile_Units > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Marker_Action > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Marker_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Marker_Visibility > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Material_PBR_WorkflowType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Material_ShaderType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::ParameterError_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::ParticleEmitter_EmitterType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Physics_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::PixelFormatType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::PointCloudPacked_Field_DataType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::RestResponse_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::SensorNoise_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Shadows_ShadowType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::SphericalCoordinates_SurfaceModel > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Statistic_DataType > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::UserCmd_Type > ()
template<>
const EnumDescriptor * GetEnumDescriptor< ::ignition::msgs::Visual_Type > ()
Function Documentation
Arena::CreateMaybeMessage<::ignition::msgs::Actor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Actor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Actor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Actor_Animation >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Actor_Animation* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Actor_Animation > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Actor_Trajectory >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Actor_Trajectory* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Actor_Trajectory > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Actor_Waypoint >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Actor_Waypoint* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Actor_Waypoint > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Actuators >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Actuators* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Actuators > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::AirPressureSensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::AirPressureSensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::AirPressureSensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Altimeter >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Altimeter* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Altimeter > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::AltimeterSensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::AltimeterSensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::AltimeterSensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedAxisAligned2DBox >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::AnnotatedAxisAligned2DBox* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedAxisAligned2DBox > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedAxisAligned2DBox_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::AnnotatedAxisAligned2DBox_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedAxisAligned2DBox_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedOriented3DBox >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::AnnotatedOriented3DBox* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedOriented3DBox > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedOriented3DBox_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::AnnotatedOriented3DBox_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::AnnotatedOriented3DBox_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Any >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Any* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Any > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Atmosphere >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Atmosphere* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Atmosphere > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Axis >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Axis* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Axis > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::AxisAligned2DBox >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::AxisAligned2DBox* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::AxisAligned2DBox > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::AxisAlignedBox >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::AxisAlignedBox* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::AxisAlignedBox > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Battery >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Battery* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Battery > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::BatteryState >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::BatteryState* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::BatteryState > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Boolean >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Boolean* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Boolean > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::BoxGeom >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::BoxGeom* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::BoxGeom > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Bytes >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Bytes* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Bytes > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::CameraCmd >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraCmd* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::CameraCmd > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraInfo* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo_Distortion >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraInfo_Distortion* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo_Distortion > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo_Intrinsics >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraInfo_Intrinsics* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo_Intrinsics > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo_Projection >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraInfo_Projection* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::CameraInfo_Projection > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::CameraLens >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraLens* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::CameraLens > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::CameraSensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::CameraSensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::CameraSensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::CapsuleGeom >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::CapsuleGeom* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::CapsuleGeom > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Cessna >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Cessna* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Cessna > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Clock >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Clock* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Clock > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::CmdVel2D >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::CmdVel2D* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::CmdVel2D > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Collision >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Collision* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Collision > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Color >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Color* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Color > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ConeGeom >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ConeGeom* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ConeGeom > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Contact >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Contact* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Contact > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Contacts >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Contacts* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Contacts > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ContactSensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ContactSensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ContactSensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::CylinderGeom >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::CylinderGeom* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::CylinderGeom > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Dataframe >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Dataframe* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Dataframe > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Density >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Density* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Density > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Diagnostics >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Diagnostics* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Diagnostics > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Diagnostics_DiagTime >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Diagnostics_DiagTime* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Diagnostics_DiagTime > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Discovery >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Discovery > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Flags >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery_Flags* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Flags > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Publisher >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery_Publisher* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Publisher > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Publisher_MessagePublisher >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery_Publisher_MessagePublisher* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Publisher_MessagePublisher > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Publisher_ServicePublisher >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery_Publisher_ServicePublisher* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Publisher_ServicePublisher > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Subscriber >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Discovery_Subscriber* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Discovery_Subscriber > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Distortion >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Distortion* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Distortion > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Double >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Double* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Double > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Double_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Double_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Double_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Duration >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Duration* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Duration > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::EllipsoidGeom >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::EllipsoidGeom* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::EllipsoidGeom > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Empty >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Empty* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Empty > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Entity >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Entity* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Entity > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::EntityFactory >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::EntityFactory* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::EntityFactory > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::EntityFactory_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::EntityFactory_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::EntityFactory_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::EntityPlugin_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::EntityPlugin_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::EntityPlugin_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::EntityWrench >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::EntityWrench* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::EntityWrench > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Float >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Float* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Float > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Float_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Float_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Float_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Fluid >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Fluid* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Fluid > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::FluidPressure >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::FluidPressure* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::FluidPressure > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Fog >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Fog* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Fog > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Friction >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Friction* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Friction > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Friction_Torsional >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Friction_Torsional* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Friction_Torsional > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Friction_Torsional_ODE >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Friction_Torsional_ODE* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Friction_Torsional_ODE > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_AnnotationsEntry_DoNotUse >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_AnnotationsEntry_DoNotUse* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_AnnotationsEntry_DoNotUse > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Categories >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Categories* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Categories > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Compatibility >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Compatibility* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Compatibility > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Contact >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Contact* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Contact > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Dependency >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Dependency* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Dependency > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Legal >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Legal* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Legal > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Model >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_Model* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_Model > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_World >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::FuelMetadata_World* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::FuelMetadata_World > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Geometry >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Geometry* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Geometry > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::GPS >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::GPS* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::GPS > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::GPSSensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::GPSSensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::GPSSensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::GPSSensor_Sensing >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::GPSSensor_Sensing* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::GPSSensor_Sensing > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::GUI >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::GUI* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::GUI > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::GUICamera >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::GUICamera* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::GUICamera > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Header >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Header* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Header > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Header_Map >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Header_Map* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Header_Map > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::HeightmapGeom >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::HeightmapGeom* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::HeightmapGeom > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::HeightmapGeom_Blend >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::HeightmapGeom_Blend* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::HeightmapGeom_Blend > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::HeightmapGeom_Texture >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::HeightmapGeom_Texture* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::HeightmapGeom_Texture > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Hydra >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Hydra* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Hydra > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Hydra_Paddle >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Hydra_Paddle* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Hydra_Paddle > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Image >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Image* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Image > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ImageGeom >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ImageGeom* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ImageGeom > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::IMU >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::IMU* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::IMU > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::IMUSensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor_AngularVelocity >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::IMUSensor_AngularVelocity* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor_AngularVelocity > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor_LinearAcceleration >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::IMUSensor_LinearAcceleration* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor_LinearAcceleration > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor_OrientationReferenceFrame >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::IMUSensor_OrientationReferenceFrame* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::IMUSensor_OrientationReferenceFrame > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Inertial >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Inertial* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Inertial > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Int32 >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Int32* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Int32 > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Int32_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Int32_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Int32_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Int64 >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Int64* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Int64 > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Int64_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Int64_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Int64_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Joint >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Joint* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Joint > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Joint_Gearbox >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Joint_Gearbox* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Joint_Gearbox > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Joint_Screw >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Joint_Screw* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Joint_Screw > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::JointAnimation >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointAnimation* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::JointAnimation > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::JointAnimation_Joint >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointAnimation_Joint* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::JointAnimation_Joint > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::JointCmd >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointCmd* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::JointCmd > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::JointTrajectory >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointTrajectory* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::JointTrajectory > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::JointTrajectoryPoint >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointTrajectoryPoint* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::JointTrajectoryPoint > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::JointWrench >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::JointWrench* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::JointWrench > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Joy >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Joy* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Joy > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Joystick >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Joystick* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Joystick > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LaserScan >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LaserScan* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LaserScan > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LidarSensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LidarSensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LidarSensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Light >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Light* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Light > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Link >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Link* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Link > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LinkData >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LinkData* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LinkData > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LogControl >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogControl* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LogControl > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LogicalCameraImage >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogicalCameraImage* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LogicalCameraImage > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LogicalCameraImage_Model >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogicalCameraImage_Model* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LogicalCameraImage_Model > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LogicalCameraSensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogicalCameraSensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LogicalCameraSensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LogPlaybackControl >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogPlaybackControl* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LogPlaybackControl > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LogPlaybackStatistics >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogPlaybackStatistics* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LogPlaybackStatistics > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LogStatus >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogStatus* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LogStatus > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::LogStatus_LogFile >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::LogStatus_LogFile* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::LogStatus_LogFile > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Magnetometer >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Magnetometer* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Magnetometer > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::MagnetometerSensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::MagnetometerSensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::MagnetometerSensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Marker >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Marker* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Marker > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Marker_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Marker_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Marker_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Material >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Material* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Material > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Material_PBR >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Material_PBR* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Material_PBR > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Material_Script >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Material_Script* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Material_Script > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::MeshGeom >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::MeshGeom* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::MeshGeom > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Metric >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Metric* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Metric > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Model >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Model* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Model > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Model_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Model_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Model_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ModelConfiguration >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ModelConfiguration* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ModelConfiguration > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::NavSat >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::NavSat* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::NavSat > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::NavSatSensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::NavSatSensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::NavSatSensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::NavSatSensor_Sensing >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::NavSatSensor_Sensing* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::NavSatSensor_Sensing > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::OccupancyGrid >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::OccupancyGrid* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::OccupancyGrid > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::OccupancyGrid_MapMetaInfo >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::OccupancyGrid_MapMetaInfo* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::OccupancyGrid_MapMetaInfo > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Odometry >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Odometry* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Odometry > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::OdometryWithCovariance >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::OdometryWithCovariance* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::OdometryWithCovariance > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Oriented3DBox >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Oriented3DBox* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Oriented3DBox > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Packet >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Packet* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Packet > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Param >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Param* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Param > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Param_ParamsEntry_DoNotUse >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Param_ParamsEntry_DoNotUse* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Param_ParamsEntry_DoNotUse > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Param_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Param_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Param_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Parameter >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Parameter* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Parameter > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ParameterDeclaration >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParameterDeclaration* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ParameterDeclaration > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ParameterDeclarations >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParameterDeclarations* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ParameterDeclarations > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ParameterError >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParameterError* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ParameterError > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ParameterName >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParameterName* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ParameterName > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ParameterValue >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParameterValue* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ParameterValue > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ParticleEmitter >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParticleEmitter* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ParticleEmitter > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ParticleEmitter_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ParticleEmitter_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ParticleEmitter_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PerformanceSensorMetrics >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PerformanceSensorMetrics* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PerformanceSensorMetrics > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Physics >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Physics* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Physics > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PID >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PID* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PID > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PlaneGeom >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PlaneGeom* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PlaneGeom > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Plugin >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Plugin* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Plugin > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Plugin_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Plugin_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Plugin_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PointCloud >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PointCloud* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PointCloud > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PointCloudPacked >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PointCloudPacked* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PointCloudPacked > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PointCloudPacked_Field >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PointCloudPacked_Field* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PointCloudPacked_Field > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Polyline >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Polyline* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Polyline > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Pose >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Pose* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Pose > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Pose_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Pose_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Pose_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PoseAnimation >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PoseAnimation* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PoseAnimation > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PoseTrajectory >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PoseTrajectory* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PoseTrajectory > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PoseWithCovariance >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PoseWithCovariance* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PoseWithCovariance > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Projector >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Projector* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Projector > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PropagationGrid >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PropagationGrid* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PropagationGrid > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::PropagationParticle >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::PropagationParticle* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::PropagationParticle > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Publish >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Publish* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Publish > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Publishers >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Publishers* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Publishers > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Quaternion >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Quaternion* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Quaternion > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::RaySensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::RaySensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::RaySensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Request >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Request* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Request > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Response >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Response* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Response > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::RestLogin >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::RestLogin* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::RestLogin > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::RestLogout >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::RestLogout* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::RestLogout > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::RestPost >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::RestPost* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::RestPost > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::RestResponse >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::RestResponse* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::RestResponse > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Road >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Road* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Road > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Scene >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Scene* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Scene > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SdfGeneratorConfig >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SdfGeneratorConfig* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SdfGeneratorConfig > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SdfGeneratorConfig_EntityGeneratorConfig >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SdfGeneratorConfig_EntityGeneratorConfig* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SdfGeneratorConfig_EntityGeneratorConfig > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SdfGeneratorConfig_OverrideEntityGenConfigsEntry_DoNotUse >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SdfGeneratorConfig_OverrideEntityGenConfigsEntry_DoNotUse* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SdfGeneratorConfig_OverrideEntityGenConfigsEntry_DoNotUse > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Selection >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Selection* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Selection > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Sensor >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Sensor* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Sensor > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Sensor_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Sensor_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Sensor_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SensorNoise >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SensorNoise* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SensorNoise > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SerializedComponent >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedComponent* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SerializedComponent > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SerializedEntity >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedEntity* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SerializedEntity > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SerializedEntityMap >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedEntityMap* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SerializedEntityMap > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SerializedEntityMap_ComponentsEntry_DoNotUse >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedEntityMap_ComponentsEntry_DoNotUse* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SerializedEntityMap_ComponentsEntry_DoNotUse > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SerializedState >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedState* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SerializedState > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SerializedStateMap >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedStateMap* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SerializedStateMap > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SerializedStateMap_EntitiesEntry_DoNotUse >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedStateMap_EntitiesEntry_DoNotUse* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SerializedStateMap_EntitiesEntry_DoNotUse > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SerializedStep >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedStep* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SerializedStep > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SerializedStepMap >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SerializedStepMap* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SerializedStepMap > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::ServerControl >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::ServerControl* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::ServerControl > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Shadows >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Shadows* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Shadows > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SimEvent >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SimEvent* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SimEvent > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Sky >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Sky* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Sky > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Sonar >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Sonar* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Sonar > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SphereGeom >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SphereGeom* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SphereGeom > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::SphericalCoordinates >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::SphericalCoordinates* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::SphericalCoordinates > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Statistic >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Statistic* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Statistic > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::StatisticsGroup >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::StatisticsGroup* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::StatisticsGroup > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::StringMsg >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::StringMsg* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::StringMsg > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::StringMsg_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::StringMsg_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::StringMsg_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Subscribe >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Subscribe* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Subscribe > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Surface >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Surface* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Surface > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Tactile >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Tactile* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Tactile > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Test >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Test* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Test > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Time >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Time* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Time > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::TopicInfo >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::TopicInfo* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::TopicInfo > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::TrackVisual >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::TrackVisual* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::TrackVisual > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Twist >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Twist* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Twist > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::TwistWithCovariance >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::TwistWithCovariance* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::TwistWithCovariance > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::UInt32 >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::UInt32* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::UInt32 > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::UInt32_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::UInt32_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::UInt32_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::UInt64 >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::UInt64* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::UInt64 > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::UInt64_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::UInt64_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::UInt64_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::UndoRedo >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::UndoRedo* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::UndoRedo > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::UserCmd >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::UserCmd* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::UserCmd > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::UserCmdStats >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::UserCmdStats* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::UserCmdStats > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Vector2d >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Vector2d* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Vector2d > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Vector3d >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Vector3d* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Vector3d > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Version >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Version* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Version > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::VersionedName >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::VersionedName* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::VersionedName > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::VersionRange >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::VersionRange* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::VersionRange > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::VideoRecord >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::VideoRecord* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::VideoRecord > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Visual >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Visual* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Visual > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Visual_Meta >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Visual_Meta* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Visual_Meta > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Visual_V >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Visual_V* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Visual_V > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::WebRequest >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::WebRequest* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::WebRequest > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::WheelSlipParametersCmd >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::WheelSlipParametersCmd* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::WheelSlipParametersCmd > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Wind >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Wind* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Wind > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::WirelessNode >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::WirelessNode* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::WirelessNode > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::WirelessNodes >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::WirelessNodes* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::WirelessNodes > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::WorldControl >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::WorldControl* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::WorldControl > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::WorldControlState >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::WorldControlState* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::WorldControlState > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::WorldModify >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::WorldModify* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::WorldModify > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::WorldReset >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::WorldReset* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::WorldReset > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::WorldStatistics >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::WorldStatistics* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::WorldStatistics > (Arena *)
Arena::CreateMaybeMessage<::ignition::msgs::Wrench >()
IGNITION_MSGS_VISIBLE ::ignition::msgs::Wrench* google::protobuf::Arena::CreateMaybeMessage<::ignition::msgs::Wrench > (Arena *)
GetEnumDescriptor< ::ignition::msgs::Any_ValueType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Any_ValueType > () inline
References ignition::msgs::Any_ValueType_descriptor().
GetEnumDescriptor< ::ignition::msgs::Atmosphere_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Atmosphere_Type > () inline
References ignition::msgs::Atmosphere_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::BatteryState_PowerSupplyStatus >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::BatteryState_PowerSupplyStatus > () inline
References ignition::msgs::BatteryState_PowerSupplyStatus_descriptor().
GetEnumDescriptor< ::ignition::msgs::CameraInfo_Distortion_DistortionModelType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::CameraInfo_Distortion_DistortionModelType > () inline
References ignition::msgs::CameraInfo_Distortion_DistortionModelType_descriptor().
GetEnumDescriptor< ::ignition::msgs::Discovery_Publisher_Scope >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Discovery_Publisher_Scope > () inline
References ignition::msgs::Discovery_Publisher_Scope_descriptor().
GetEnumDescriptor< ::ignition::msgs::Discovery_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Discovery_Type > () inline
References ignition::msgs::Discovery_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::Entity_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Entity_Type > () inline
References ignition::msgs::Entity_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::Fog_FogType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Fog_FogType > () inline
References ignition::msgs::Fog_FogType_descriptor().
GetEnumDescriptor< ::ignition::msgs::Geometry_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Geometry_Type > () inline
References ignition::msgs::Geometry_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::Joint_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Joint_Type > () inline
References ignition::msgs::Joint_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::Light_LightType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Light_LightType > () inline
References ignition::msgs::Light_LightType_descriptor().
GetEnumDescriptor< ::ignition::msgs::LogStatus_LogFile_Units >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::LogStatus_LogFile_Units > () inline
References ignition::msgs::LogStatus_LogFile_Units_descriptor().
GetEnumDescriptor< ::ignition::msgs::Marker_Action >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Marker_Action > () inline
References ignition::msgs::Marker_Action_descriptor().
GetEnumDescriptor< ::ignition::msgs::Marker_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Marker_Type > () inline
References ignition::msgs::Marker_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::Marker_Visibility >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Marker_Visibility > () inline
References ignition::msgs::Marker_Visibility_descriptor().
GetEnumDescriptor< ::ignition::msgs::Material_PBR_WorkflowType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Material_PBR_WorkflowType > () inline
References ignition::msgs::Material_PBR_WorkflowType_descriptor().
GetEnumDescriptor< ::ignition::msgs::Material_ShaderType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Material_ShaderType > () inline
References ignition::msgs::Material_ShaderType_descriptor().
GetEnumDescriptor< ::ignition::msgs::ParameterError_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::ParameterError_Type > () inline
References ignition::msgs::ParameterError_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::ParticleEmitter_EmitterType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::ParticleEmitter_EmitterType > () inline
References ignition::msgs::ParticleEmitter_EmitterType_descriptor().
GetEnumDescriptor< ::ignition::msgs::Physics_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Physics_Type > () inline
References ignition::msgs::Physics_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::PixelFormatType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::PixelFormatType > () inline
References ignition::msgs::PixelFormatType_descriptor().
GetEnumDescriptor< ::ignition::msgs::PointCloudPacked_Field_DataType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::PointCloudPacked_Field_DataType > () inline
References ignition::msgs::PointCloudPacked_Field_DataType_descriptor().
GetEnumDescriptor< ::ignition::msgs::RestResponse_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::RestResponse_Type > () inline
References ignition::msgs::RestResponse_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::SensorNoise_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::SensorNoise_Type > () inline
References ignition::msgs::SensorNoise_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::Shadows_ShadowType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Shadows_ShadowType > () inline
References ignition::msgs::Shadows_ShadowType_descriptor().
GetEnumDescriptor< ::ignition::msgs::SphericalCoordinates_SurfaceModel >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::SphericalCoordinates_SurfaceModel > () inline
References ignition::msgs::SphericalCoordinates_SurfaceModel_descriptor().
GetEnumDescriptor< ::ignition::msgs::Statistic_DataType >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Statistic_DataType > () inline
References ignition::msgs::Statistic_DataType_descriptor().
GetEnumDescriptor< ::ignition::msgs::UserCmd_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::UserCmd_Type > () inline
References ignition::msgs::UserCmd_Type_descriptor().
GetEnumDescriptor< ::ignition::msgs::Visual_Type >()
const EnumDescriptor* google::protobuf::GetEnumDescriptor< ::ignition::msgs::Visual_Type > () inline
References ignition::msgs::Visual_Type_descriptor().