Gazebo Rendering: BaseStore< T, U > Class Template Reference
Gazebo Rendering
API Reference
7.4.2
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
BaseStore< T, U > Class Template Reference
#include <BaseStorage.hh>
Public Member Functions
BaseStore ()
virtual ~BaseStore ()
virtual bool Add (TPtr _object)
Add given element. If the element has already been added or its name or ID conflict with other existing elements, then no work will be done.
virtual bool AddDerived (UPtr _object)
virtual UIter Begin ()
Return an iterator to the beginning.
virtual bool Contains (ConstTPtr _object) const
Determine if store contains the given element.
virtual bool ContainsId (unsigned int _id) const
Determine if store contains the element with the given ID.
virtual bool ContainsName (const std::string &_name) const
Determine if store contains the element with the given name.
virtual UPtr DerivedById (unsigned int _id) const
virtual UPtr DerivedByIndex (unsigned int _index) const
virtual UPtr DerivedByName (const std::string &_name) const
virtual void Destroy (TPtr _object)
Remove and destroy given element. If the given element does not exists, in this store, then no work will be done.
virtual void DestroyAll ()
Remove and destroy all elements in store.
virtual void DestroyById (unsigned int _id)
Remove and destroy element with the given ID. If the specified element does not exists in this store, then no work will be done.
virtual void DestroyByIndex (unsigned int _index)
Remove and destroy element at the given index. If the specified element does not exists in this store, then no work will be done.
virtual void DestroyByName (const std::string &_name)
Remove and destroy element with the given name. If the specified element does not exists in this store, then no work will be done.
virtual UIter End ()
Return an iterator to the end.
virtual TPtr GetById (unsigned int _id) const
Get element with the given ID.
virtual TPtr GetByIndex (unsigned int _index) const
Get element at the given index.
virtual TPtr GetByName (const std::string &_name) const
Get element with the given name.
virtual TPtr Remove (TPtr _object)
Remove given element. If the given element does not exists in this store, then no work will be done.
virtual void RemoveAll ()
Remove all elements from store.
virtual TPtr RemoveById (unsigned int _id)
Remove element with the given ID. If the specified element does not exists in this store, then no work will be done.
virtual TPtr RemoveByIndex (unsigned int _index)
Remove element at the given index. If the specified element does not exists in this store, then no work will be done.
virtual TPtr RemoveByName (const std::string &_name)
Remove element with the given name. If the specified element does not exists in this store, then no work will be done.
virtual UPtr RemoveDerived (UPtr _object)
virtual UPtr RemoveDerivedById (unsigned int _id)
virtual UPtr RemoveDerivedByIndex (unsigned int _index)
virtual UPtr RemoveDerivedByName (const std::string &_name)
virtual unsigned int Size () const
Get number of elements in this store.
Public Member Functions inherited from Store< T >
virtual ~Store ()=default
Destructor.
Protected Member Functions
virtual bool AddImpl (UPtr _object)
virtual ConstUIter ConstIter (ConstTPtr _object) const
virtual ConstUIter ConstIterById (unsigned int _id) const
virtual ConstUIter ConstIterByIndex (unsigned int _index) const
virtual ConstUIter ConstIterByName (const std::string &_name) const
virtual void DestroyImpl (UIter _iter)
virtual bool IsValidIter (ConstUIter _iter) const
virtual UIter Iter (ConstTPtr _object)
virtual UIter IterById (unsigned int _id)
virtual UIter IterByIndex (unsigned int _index)
virtual UIter IterByName (const std::string &_name)
virtual UIter RemoveConstness (ConstUIter _iter)
virtual UPtr RemoveImpl (UIter _iter)
Protected Attributes
UStore store
Constructor & Destructor Documentation
BaseStore()
BaseStore
~BaseStore()
~BaseStore virtual
Member Function Documentation
Add()
bool Add (TPtr _object) virtual
Add given element. If the element has already been added or its name or ID conflict with other existing elements, then no work will be done.
Parameters
[in] _object Element to be added
Returns
True if successful
Implements Store< T >.
References std::endl(), and gzerr.
AddDerived()
bool AddDerived (UPtr _object) virtual
References std::endl(), and gzerr.
AddImpl()
bool AddImpl (UPtr _object) protected virtual
References std::endl(), and gzerr.
Begin()
BaseStore< T, U >::UIter Begin virtual
Return an iterator to the beginning.
Returns
Iterator to beginning
ConstIter()
BaseStore< T, U >::ConstUIter ConstIter (ConstTPtr _object) const protected virtual
ConstIterById()
BaseStore< T, U >::ConstUIter ConstIterById (unsigned int _id) const protected virtual
ConstIterByIndex()
BaseStore< T, U >::ConstUIter ConstIterByIndex (unsigned int _index) const protected virtual
References std::advance(), std::endl(), and gzerr.
ConstIterByName()
BaseStore< T, U >::ConstUIter ConstIterByName (const std::string & _name) const protected virtual
Contains()
bool Contains (ConstTPtr _object) const virtual
Determine if store contains the given element.
Parameters
[in] _object The element in question
Returns
True if this store contains the given element
Implements Store< T >.
ContainsId()
bool ContainsId (unsigned int _id) const virtual
Determine if store contains the element with the given ID.
Parameters
[in] _id ID of the element in question
Returns
True if this store contains the specified element
Implements Store< T >.
ContainsName()
bool ContainsName (const std::string & _name) const virtual
Determine if store contains the element with the given name.
Parameters
[in] _name Name of the element in question
Returns
True if this store contains the specified element
Implements Store< T >.
DerivedById()
BaseStore< T, U >::UPtr DerivedById (unsigned int _id) const virtual
DerivedByIndex()
BaseStore< T, U >::UPtr DerivedByIndex (unsigned int _index) const virtual
DerivedByName()
BaseStore< T, U >::UPtr DerivedByName (const std::string & _name) const virtual
Destroy()
void Destroy (TPtr _object) virtual
Remove and destroy given element. If the given element does not exists, in this store, then no work will be done.
Parameters
[in] _object Element to be removed
Implements Store< T >.
DestroyAll()
void DestroyAll () virtual
Remove and destroy all elements in store.
Implements Store< T >.
DestroyById()
void DestroyById (unsigned int _id) virtual
Remove and destroy element with the given ID. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _id ID of the element to be removed
Implements Store< T >.
DestroyByIndex()
void DestroyByIndex (unsigned int _index) virtual
Remove and destroy element at the given index. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _index Index of the element to be removed
Implements Store< T >.
DestroyByName()
void DestroyByName (const std::string & _name) virtual
Remove and destroy element with the given name. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _name Name of the element to be removed
Implements Store< T >.
DestroyImpl()
void DestroyImpl (UIter _iter) protected virtual
End()
BaseStore< T, U >::UIter End virtual
Return an iterator to the end.
Returns
Iterator to end
GetById()
BaseStore< T, U >::TPtr GetById (unsigned int _id) const virtual
Get element with the given ID.
Parameters
[in] _id ID of the desired element
Returns
The specified element
Implements Store< T >.
GetByIndex()
BaseStore< T, U >::TPtr GetByIndex (unsigned int _index) const virtual
Get element at the given index.
Parameters
[in] _index Index of the desired element
Returns
The specified element
Implements Store< T >.
GetByName()
BaseStore< T, U >::TPtr GetByName (const std::string & _name) const virtual
Get element with the given name.
Parameters
[in] _name Name of the desired element
Returns
The specified element
Implements Store< T >.
IsValidIter()
bool IsValidIter (ConstUIter _iter) const protected virtual
Iter()
BaseStore< T, U >::UIter Iter (ConstTPtr _object) protected virtual
IterById()
BaseStore< T, U >::UIter IterById (unsigned int _id) protected virtual
IterByIndex()
BaseStore< T, U >::UIter IterByIndex (unsigned int _index) protected virtual
IterByName()
BaseStore< T, U >::UIter IterByName (const std::string & _name) protected virtual
Remove()
BaseStore< T, U >::TPtr Remove (TPtr _object) virtual
Remove given element. If the given element does not exists in this store, then no work will be done.
Parameters
[in] _object Element to be removed
Returns
The removed element
Implements Store< T >.
RemoveAll()
void RemoveAll () virtual
Remove all elements from store.
Implements Store< T >.
RemoveById()
BaseStore< T, U >::TPtr RemoveById (unsigned int _id) virtual
Remove element with the given ID. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _id ID of the element to be removed
Returns
The removed element
Implements Store< T >.
RemoveByIndex()
BaseStore< T, U >::TPtr RemoveByIndex (unsigned int _index) virtual
Remove element at the given index. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _index Index of the element to be removed
Returns
The removed element
Implements Store< T >.
RemoveByName()
BaseStore< T, U >::TPtr RemoveByName (const std::string & _name) virtual
Remove element with the given name. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _name Name of the element to be removed
Returns
The removed element
Implements Store< T >.
RemoveConstness()
BaseStore< T, U >::UIter RemoveConstness (ConstUIter _iter) protected virtual
RemoveDerived()
BaseStore< T, U >::UPtr RemoveDerived (UPtr _object) virtual
RemoveDerivedById()
BaseStore< T, U >::UPtr RemoveDerivedById (unsigned int _id) virtual
RemoveDerivedByIndex()
BaseStore< T, U >::UPtr RemoveDerivedByIndex (unsigned int _index) virtual
RemoveDerivedByName()
BaseStore< T, U >::UPtr RemoveDerivedByName (const std::string & _name) virtual
RemoveImpl()
BaseStore< T, U >::UPtr RemoveImpl (UIter _iter) protected virtual
Size()
unsigned int Size () const virtual
Get number of elements in this store.
Returns
The number of elements in this store
Implements Store< T >.
Member Data Documentation
store
UStore store protected
The documentation for this class was generated from the following file:
gz/rendering/base/BaseStorage.hh