Gazebo Sim: ElevatorStateMachinePrivate Class Reference
Gazebo Sim
API Reference
7.7.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
ElevatorStateMachinePrivate Class Reference
#include <ElevatorStateMachineImpl.hh>
Public Member Functions
ElevatorStateMachinePrivate (const std::shared_ptr< ElevatorCommonPrivate > &_system)
Constructor.
void EnqueueNewTarget (double _target)
Adds a new target to the queue.
void SendCmd (transport::Node::Publisher &_pub, double _cmd)
Publishes a command message.
Public Attributes
std::shared_ptr< ElevatorCommonPrivate > system
Data of the enclosing system.
std::deque< int32_t > targets
Floor target queue.
Constructor & Destructor Documentation
ElevatorStateMachinePrivate()
ElevatorStateMachinePrivate (const std::shared_ptr< ElevatorCommonPrivate > & _system)
Constructor.
Parameters
[in] _system Data of the enclosing system
Member Function Documentation
EnqueueNewTarget()
void EnqueueNewTarget (double _target)
Adds a new target to the queue.
If there is another target in the queue, and the new target is an intermediate stop, the new target will take precedence
Parameters
[in] _target Target to add to the queue
References deque< T >::cbegin(), deque< T >::cend(), std::endl(), std::find(), gzmsg, deque< T >::insert(), deque< T >::push_back(), ostringstream::str(), std::swap(), ElevatorStateMachinePrivate::system, and ElevatorStateMachinePrivate::targets.
SendCmd()
void SendCmd (transport::Node::Publisher & _pub, double _cmd)
Publishes a command message.
Parameters
[in] _pub Joint command publisher
[in] _cmd Joint command
References Node::Publisher::Publish(), and Double::set_data().
Member Data Documentation
system
std::shared_ptr<ElevatorCommonPrivate> system
Data of the enclosing system.
Referenced by ElevatorStateMachinePrivate::EnqueueNewTarget().
targets
std::deque<int32_t> targets
Floor target queue.
Referenced by ElevatorStateMachinePrivate::EnqueueNewTarget().
The documentation for this class was generated from the following file:
ElevatorStateMachineImpl.hh