Gazebo Math: OnePoleQuaternion Class Reference
Gazebo Math
API Reference
7.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
OnePoleQuaternion Class Reference
One-pole quaternion filter.
#include <gz/math/Filter.hh>
Public Member Functions
OnePoleQuaternion ()
Constructor.
OnePoleQuaternion (double _fc, double _fs)
Constructor.
const math::Quaterniond & Process (const math::Quaterniond &_x)
Update the filter's output.
Public Member Functions inherited from OnePole< math::Quaterniond >
OnePole ()=default
Constructor.
OnePole (double _fc, double _fs)
Constructor.
virtual void Fc (double _fc, double _fs) override
Set the cutoff frequency and sample rate.
const math::Quaterniond & Process (const math::Quaterniond &_x)
Update the filter's output.
Public Member Functions inherited from Filter< T >
virtual ~Filter ()
Destructor.
virtual void Set (const T &_val)
Set the output of the filter.
virtual const T & Value () const
Get the output of the filter.
Additional Inherited Members
Protected Attributes inherited from OnePole< math::Quaterniond >
double a0
Input gain control.
double b1
Gain of the feedback.
Protected Attributes inherited from Filter< T >
T y0 {}
Output.
Detailed Description
One-pole quaternion filter.
Constructor & Destructor Documentation
OnePoleQuaternion() [1/2]
OnePoleQuaternion () inline
Constructor.
References Filter< T >::Set().
OnePoleQuaternion() [2/2]
OnePoleQuaternion (double _fc, double _fs) inline
Constructor.
Parameters
[in] _fc Cutoff frequency.
[in] _fs Sample rate.
References Filter< T >::Set().
Member Function Documentation
Process()
const math::Quaterniond& Process (const math::Quaterniond & _x) inline
Update the filter's output.
Parameters
[in] _x Input value.
Returns
The filter's current output.
References OnePole< math::Quaterniond >::a0, Quaternion< T >::Slerp(), and Filter< T >::y0.
The documentation for this class was generated from the following file:
gz/math/Filter.hh
"classgz_1_1math_1_1Filter.html#a8c46b09412b05975f6eee5cc9c1bf3ef">Filter< math::Quaterniond >::y0. The documentation for this class was generated from the following file:
gz/math/Filter.hh