Gazebo Math: Vertex< V > Class Template Reference
Gazebo Math
API Reference
7.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
Vertex< V > Class Template Reference
A vertex of a graph. It stores user information, an optional name, and keeps an internal unique Id. This class does not enforce to choose a unique name.
#include <Vertex.hh>
Public Member Functions
Vertex (const std::string &_name, const V &_data=V(), const VertexId _id=kNullId)
Constructor.
V & Data ()
Get a mutable reference to the user information.
const V & Data () const
Retrieve the user information.
VertexId Id () const
Get the vertex Id.
const std::string & Name () const
Get the vertex name.
void SetName (const std::string &_name)
Set the vertex name.
bool Valid () const
Whether the vertex is considered valid or not (id==kNullId).
Static Public Attributes
static Vertex< V > NullVertex
An invalid vertex.
Detailed Description
template<typename V>
class gz::math::graph::Vertex< V >
A vertex of a graph. It stores user information, an optional name, and keeps an internal unique Id. This class does not enforce to choose a unique name.
Constructor & Destructor Documentation
Vertex()
Vertex (const std::string & _name, const V & _data = V(), const VertexId _id = kNullId) inline
Constructor.
Parameters
[in] _name Non-unique vertex name.
[in] _data User information.
[in] _id Optional unique id.
Member Function Documentation
Data() [1/2]
V& Data () inline
Get a mutable reference to the user information.
Returns
Mutable reference to the user information.
Data() [2/2]
const V& Data () const inline
Retrieve the user information.
Returns
Reference to the user information.
Id()
VertexId Id () const inline
Get the vertex Id.
Returns
The vertex Id.
Referenced by Graph< V, E, EdgeType >::AdjacentsFrom(), Graph< V, E, EdgeType >::AdjacentsTo(), Graph< V, E, EdgeType >::IncidentsFrom(), Graph< V, E, EdgeType >::IncidentsTo(), Graph< V, E, EdgeType >::InDegree(), Graph< V, E, EdgeType >::OutDegree(), and Graph< V, E, EdgeType >::RemoveVertex().
Name()
const std::string& Name () const inline
Get the vertex name.
Returns
The vertex name.
SetName()
void SetName (const std::string & _name) inline
Set the vertex name.
Parameters
[in] _name The vertex name.
Valid()
bool Valid () const inline
Whether the vertex is considered valid or not (id==kNullId).
Returns
True when the vertex is valid or false otherwise (id==kNullId)
References gz::math::graph::kNullId.
Member Data Documentation
NullVertex
Vertex< V > NullVertex static
An invalid vertex.
The documentation for this class was generated from the following file:
gz/math/graph/Vertex.hh