Gazebo Rendering: BaseScene Class Reference
Gazebo Rendering
API Reference
8.2.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
BaseScene Class Reference abstract
#include <BaseScene.hh>
Public Member Functions
virtual ~BaseScene ()
virtual math::Color BackgroundColor () const override
virtual MaterialPtr BackgroundMaterial () const override
virtual uint8_t CameraPassCountPerGpuFlush () const override
virtual void Clear () override
virtual ArrowVisualPtr CreateArrowVisual () override
virtual ArrowVisualPtr CreateArrowVisual (const std::string &_name) override
virtual ArrowVisualPtr CreateArrowVisual (unsigned int _id) override
virtual ArrowVisualPtr CreateArrowVisual (unsigned int _id, const std::string &_name) override
virtual AxisVisualPtr CreateAxisVisual () override
virtual AxisVisualPtr CreateAxisVisual (const std::string &_name) override
virtual AxisVisualPtr CreateAxisVisual (unsigned int _id) override
virtual AxisVisualPtr CreateAxisVisual (unsigned int _id, const std::string &_name) override
virtual BoundingBoxCameraPtr CreateBoundingBoxCamera () override
virtual BoundingBoxCameraPtr CreateBoundingBoxCamera (const std::string &_name) override
virtual BoundingBoxCameraPtr CreateBoundingBoxCamera (const unsigned int _id) override
virtual BoundingBoxCameraPtr CreateBoundingBoxCamera (const unsigned int _id, const std::string &_name) override
virtual GeometryPtr CreateBox () override
virtual CameraPtr CreateCamera () override
virtual CameraPtr CreateCamera (const std::string &_name) override
virtual CameraPtr CreateCamera (unsigned int _id) override
virtual CameraPtr CreateCamera (unsigned int _id, const std::string &_name) override
virtual CapsulePtr CreateCapsule () override
virtual COMVisualPtr CreateCOMVisual () override
virtual COMVisualPtr CreateCOMVisual (const std::string &_name) override
virtual COMVisualPtr CreateCOMVisual (unsigned int _id) override
virtual COMVisualPtr CreateCOMVisual (unsigned int _id, const std::string &_name) override
virtual GeometryPtr CreateCone () override
virtual GeometryPtr CreateCylinder () override
virtual DepthCameraPtr CreateDepthCamera () override
virtual DepthCameraPtr CreateDepthCamera (const std::string &_name) override
virtual DepthCameraPtr CreateDepthCamera (const unsigned int _id) override
virtual DepthCameraPtr CreateDepthCamera (const unsigned int _id, const std::string &_name) override
virtual DirectionalLightPtr CreateDirectionalLight () override
virtual DirectionalLightPtr CreateDirectionalLight (const std::string &_name) override
virtual DirectionalLightPtr CreateDirectionalLight (unsigned int _id) override
virtual DirectionalLightPtr CreateDirectionalLight (unsigned int _id, const std::string &_name) override
virtual GizmoVisualPtr CreateGizmoVisual () override
virtual GizmoVisualPtr CreateGizmoVisual (const std::string &_name) override
virtual GizmoVisualPtr CreateGizmoVisual (unsigned int _id) override
virtual GizmoVisualPtr CreateGizmoVisual (unsigned int _id, const std::string &_name) override
virtual GlobalIlluminationCiVctPtr CreateGlobalIlluminationCiVct () override
virtual GlobalIlluminationCiVctPtr CreateGlobalIlluminationCiVct (const std::string &_name) override
virtual GlobalIlluminationCiVctPtr CreateGlobalIlluminationCiVct (unsigned int _id) override
virtual GlobalIlluminationCiVctPtr CreateGlobalIlluminationCiVct (unsigned int _id, const std::string &_name) override
virtual GlobalIlluminationVctPtr CreateGlobalIlluminationVct () override
virtual GlobalIlluminationVctPtr CreateGlobalIlluminationVct (const std::string &_name) override
virtual GlobalIlluminationVctPtr CreateGlobalIlluminationVct (unsigned int _id) override
virtual GlobalIlluminationVctPtr CreateGlobalIlluminationVct (unsigned int _id, const std::string &_name) override
virtual GpuRaysPtr CreateGpuRays () override
virtual GpuRaysPtr CreateGpuRays (const std::string &_name) override
virtual GpuRaysPtr CreateGpuRays (const unsigned int _id) override
virtual GpuRaysPtr CreateGpuRays (const unsigned int _id, const std::string &_name) override
virtual GridPtr CreateGrid () override
virtual HeightmapPtr CreateHeightmap (const HeightmapDescriptor &_desc) override
virtual InertiaVisualPtr CreateInertiaVisual () override
virtual InertiaVisualPtr CreateInertiaVisual (const std::string &_name) override
virtual InertiaVisualPtr CreateInertiaVisual (unsigned int _id) override
virtual InertiaVisualPtr CreateInertiaVisual (unsigned int _id, const std::string &_name) override
virtual JointVisualPtr CreateJointVisual () override
virtual JointVisualPtr CreateJointVisual (const std::string &_name) override
virtual JointVisualPtr CreateJointVisual (unsigned int _id) override
virtual JointVisualPtr CreateJointVisual (unsigned int _id, const std::string &_name) override
virtual LidarVisualPtr CreateLidarVisual () override
virtual LidarVisualPtr CreateLidarVisual (const std::string &_name) override
virtual LidarVisualPtr CreateLidarVisual (unsigned int _id) override
virtual LidarVisualPtr CreateLidarVisual (unsigned int _id, const std::string &_name) override
virtual LightVisualPtr CreateLightVisual () override
virtual LightVisualPtr CreateLightVisual (const std::string &_name) override
virtual LightVisualPtr CreateLightVisual (unsigned int _id) override
virtual LightVisualPtr CreateLightVisual (unsigned int _id, const std::string &_name) override
virtual MarkerPtr CreateMarker () override
virtual MaterialPtr CreateMaterial (const common::Material &_material) override
virtual MaterialPtr CreateMaterial (const std::string &_name="") override
virtual MeshPtr CreateMesh (const common::Mesh *_mesh) override
virtual MeshPtr CreateMesh (const MeshDescriptor &_desc) override
virtual MeshPtr CreateMesh (const std::string &_meshName) override
virtual ParticleEmitterPtr CreateParticleEmitter () override
virtual ParticleEmitterPtr CreateParticleEmitter (const std::string &_name) override
virtual ParticleEmitterPtr CreateParticleEmitter (unsigned int _id) override
virtual ParticleEmitterPtr CreateParticleEmitter (unsigned int _id, const std::string &_name) override
virtual GeometryPtr CreatePlane () override
virtual PointLightPtr CreatePointLight () override
virtual PointLightPtr CreatePointLight (const std::string &_name) override
virtual PointLightPtr CreatePointLight (unsigned int _id) override
virtual PointLightPtr CreatePointLight (unsigned int _id, const std::string &_name) override
virtual ProjectorPtr CreateProjector () override
virtual ProjectorPtr CreateProjector (const std::string &_name) override
virtual ProjectorPtr CreateProjector (unsigned int _id) override
virtual ProjectorPtr CreateProjector (unsigned int _id, const std::string &_name) override
virtual RayQueryPtr CreateRayQuery () override
virtual RenderTexturePtr CreateRenderTexture () override
virtual RenderWindowPtr CreateRenderWindow () override
virtual SegmentationCameraPtr CreateSegmentationCamera () override
virtual SegmentationCameraPtr CreateSegmentationCamera (const std::string &_name) override
virtual SegmentationCameraPtr CreateSegmentationCamera (const unsigned int _id) override
virtual SegmentationCameraPtr CreateSegmentationCamera (const unsigned int _id, const std::string &_name) override
virtual GeometryPtr CreateSphere () override
virtual SpotLightPtr CreateSpotLight () override
virtual SpotLightPtr CreateSpotLight (const std::string &_name) override
virtual SpotLightPtr CreateSpotLight (unsigned int _id) override
virtual SpotLightPtr CreateSpotLight (unsigned int _id, const std::string &_name) override
virtual TextPtr CreateText () override
virtual ThermalCameraPtr CreateThermalCamera () override
virtual ThermalCameraPtr CreateThermalCamera (const std::string &_name) override
virtual ThermalCameraPtr CreateThermalCamera (const unsigned int _id) override
virtual ThermalCameraPtr CreateThermalCamera (const unsigned int _id, const std::string &_name) override
virtual VisualPtr CreateVisual () override
virtual VisualPtr CreateVisual (const std::string &_name) override
virtual VisualPtr CreateVisual (unsigned int _id) override
virtual VisualPtr CreateVisual (unsigned int _id, const std::string &_name) override
virtual WideAngleCameraPtr CreateWideAngleCamera () override
virtual WideAngleCameraPtr CreateWideAngleCamera (const std::string &_name) override
virtual WideAngleCameraPtr CreateWideAngleCamera (const unsigned int _id) override
virtual WideAngleCameraPtr CreateWideAngleCamera (const unsigned int _id, const std::string &_name) override
virtual WireBoxPtr CreateWireBox () override
virtual void Destroy () override
virtual void DestroyLight (LightPtr _light, bool _recursive=false) override
virtual void DestroyLightById (unsigned int _id) override
virtual void DestroyLightByIndex (unsigned int _index) override
virtual void DestroyLightByName (const std::string &_name) override
virtual void DestroyLights () override
virtual void DestroyMaterial (MaterialPtr _material) override
virtual void DestroyMaterials () override
virtual void DestroyNode (NodePtr _node, bool _recursive=false) override
virtual void DestroyNodeById (unsigned int _id) override
virtual void DestroyNodeByIndex (unsigned int _index) override
virtual void DestroyNodeByName (const std::string &_name) override
virtual void DestroyNodes () override
virtual void DestroySensor (SensorPtr _sensor, bool _recursive=false) override
virtual void DestroySensorById (unsigned int _id) override
virtual void DestroySensorByIndex (unsigned int _index) override
virtual void DestroySensorByName (const std::string &_name) override
virtual void DestroySensors () override
virtual void DestroyVisual (VisualPtr _visual, bool _recursive=false) override
virtual void DestroyVisualById (unsigned int _id) override
virtual void DestroyVisualByIndex (unsigned int _index) override
virtual void DestroyVisualByName (const std::string &_name) override
virtual void DestroyVisuals () override
virtual void Fini () override
virtual std::array< math::Color, 4 > GradientBackgroundColor () const override
virtual bool HasLight (ConstLightPtr _light) const override
virtual bool HasLightId (unsigned int _id) const override
virtual bool HasLightName (const std::string &_name) const override
virtual bool HasNode (ConstNodePtr _node) const override
virtual bool HasNodeId (unsigned int _id) const override
virtual bool HasNodeName (const std::string &_name) const override
virtual bool HasSensor (ConstSensorPtr _sensor) const override
virtual bool HasSensorId (unsigned int _id) const override
virtual bool HasSensorName (const std::string &_name) const override
virtual bool HasVisual (ConstVisualPtr _visual) const override
virtual bool HasVisualId (unsigned int _id) const override
virtual bool HasVisualName (const std::string &_name) const override
virtual unsigned int Id () const override
virtual void Init () override
virtual bool IsGradientBackgroundColor () const override
virtual bool IsInitialized () const override
virtual bool IsLoaded () const
virtual bool LegacyAutoGpuFlush () const override
virtual LightPtr LightById (unsigned int _id) const override
virtual LightPtr LightByIndex (unsigned int _index) const override
virtual LightPtr LightByName (const std::string &_name) const override
virtual unsigned int LightCount () const override
virtual void Load () override
virtual MaterialPtr Material (const std::string &_name) const override
virtual bool MaterialRegistered (const std::string &_name) const override
virtual std::string Name () const override
virtual NodePtr NodeById (unsigned int _id) const override
virtual NodePtr NodeByIndex (unsigned int _index) const override
virtual NodePtr NodeByName (const std::string &_name) const override
virtual unsigned int NodeCount () const override
virtual void PostRender () override
virtual void PreRender () override
virtual void RegisterMaterial (const std::string &_name, MaterialPtr _material) override
virtual void RemoveGradientBackgroundColor () override
virtual SensorPtr SensorById (unsigned int _id) const override
virtual SensorPtr SensorByIndex (unsigned int _index) const override
virtual SensorPtr SensorByName (const std::string &_name) const override
virtual unsigned int SensorCount () const override
virtual void SetActiveGlobalIllumination (GlobalIlluminationBasePtr _gi) override
virtual void SetAmbientLight (const math::Color &_color) override=0
virtual void SetAmbientLight (double _r, double _g, double _b, double _a=1.0) override
virtual void SetBackgroundColor (const math::Color &_color) override
virtual void SetBackgroundColor (double _r, double _g, double _b, double _a=1.0) override
virtual void SetBackgroundMaterial (MaterialPtr _material) override
virtual void SetCameraPassCountPerGpuFlush (uint8_t _numPass) override
virtual void SetGradientBackgroundColor (const std::array< math::Color, 4 > &_colors) override
virtual void SetSkyEnabled (bool _enabled) override
virtual void SetTime (const std::chrono::steady_clock::duration &_time) override
virtual bool SkyEnabled () const override
virtual std::chrono::steady_clock::duration Time () const override
virtual void UnregisterMaterial (const std::string &_name) override
virtual void UnregisterMaterials () override
virtual VisualPtr VisualAt (const CameraPtr &_camera, const gz::math::Vector2i &_mousePos) override
virtual VisualPtr VisualById (unsigned int _id) const override
virtual VisualPtr VisualByIndex (unsigned int _index) const override
virtual VisualPtr VisualByName (const std::string &_name) const override
virtual unsigned int VisualCount () const override
Protected Member Functions
BaseScene (unsigned int _id, const std::string &_name)
virtual ArrowVisualPtr CreateArrowVisualImpl (unsigned int _id, const std::string &_name)=0
virtual AxisVisualPtr CreateAxisVisualImpl (unsigned int _id, const std::string &_name)=0
virtual BoundingBoxCameraPtr CreateBoundingBoxCameraImpl (unsigned int _id, const std::string &_name)
Implementation for creating a BoundingBox camera.
virtual GeometryPtr CreateBoxImpl (unsigned int _id, const std::string &_name)=0
virtual CameraPtr CreateCameraImpl (unsigned int _id, const std::string &_name)=0
virtual CapsulePtr CreateCapsuleImpl (unsigned int _id, const std::string &_name)=0
Implementation for creating a capsule geometry object.
virtual COMVisualPtr CreateCOMVisualImpl (unsigned int _id, const std::string &_name)=0
Implementation for creating CoM visual.
virtual GeometryPtr CreateConeImpl (unsigned int _id, const std::string &_name)=0
virtual GeometryPtr CreateCylinderImpl (unsigned int _id, const std::string &_name)=0
virtual DepthCameraPtr CreateDepthCameraImpl (unsigned int _id, const std::string &_name)=0
virtual DirectionalLightPtr CreateDirectionalLightImpl (unsigned int _id, const std::string &_name)=0
virtual GizmoVisualPtr CreateGizmoVisualImpl (unsigned int _id, const std::string &_name)
Implementation for creating a GizmoVisual.
virtual GlobalIlluminationCiVctPtr CreateGlobalIlluminationCiVctImpl (unsigned int _id, const std::string &_name)
Implementation for creating a GlobalIlluminationCiVct.
virtual GlobalIlluminationVctPtr CreateGlobalIlluminationVctImpl (unsigned int _id, const std::string &_name)
Implementation for creating a GlobalIlluminationVct.
virtual GpuRaysPtr CreateGpuRaysImpl (unsigned int _id, const std::string &_name)
Implementation for creating GpuRays sensor.
virtual GridPtr CreateGridImpl (unsigned int _id, const std::string &_name)=0
Implementation for creating a grid geometry object.
virtual HeightmapPtr CreateHeightmapImpl (unsigned int _id, const std::string &_name, const HeightmapDescriptor &_desc)=0
Implementation for creating a heightmap geometry.
virtual InertiaVisualPtr CreateInertiaVisualImpl (unsigned int _id, const std::string &_name)=0
Implementation for creating Inertia visual.
virtual JointVisualPtr CreateJointVisualImpl (unsigned int _id, const std::string &_name)=0
Implementation for creating Joint visual.
virtual LidarVisualPtr CreateLidarVisualImpl (unsigned int _id, const std::string &_name)=0
Implementation for creating a lidar visual.
virtual LightVisualPtr CreateLightVisualImpl (unsigned int _id, const std::string &_name)=0
Implementation for creating Light visual.
virtual MarkerPtr CreateMarkerImpl (unsigned int _id, const std::string &_name)=0
Implementation for creating a marker geometry object.
virtual MaterialPtr CreateMaterialImpl (unsigned int _id, const std::string &_name)=0
virtual MeshPtr CreateMeshImpl (unsigned int _id, const std::string &_name, const MeshDescriptor &_desc)=0
virtual unsigned int CreateObjectId ()
virtual std::string CreateObjectName (unsigned int _id, const std::string &_prefix)
virtual ParticleEmitterPtr CreateParticleEmitterImpl (unsigned int _id, const std::string &_name)
Implementation for creating a ParticleEmitter.
virtual GeometryPtr CreatePlaneImpl (unsigned int _id, const std::string &_name)=0
virtual PointLightPtr CreatePointLightImpl (unsigned int _id, const std::string &_name)=0
virtual ProjectorPtr CreateProjectorImpl (unsigned int _id, const std::string &_name)
Implementation for creating a Projector.
virtual RayQueryPtr CreateRayQueryImpl (unsigned int _id, const std::string &_name)=0
virtual RenderTexturePtr CreateRenderTextureImpl (unsigned int _id, const std::string &_name)=0
virtual RenderWindowPtr CreateRenderWindowImpl (unsigned int _id, const std::string &_name)=0
Render engine specific implementation for creating a render window.
virtual SegmentationCameraPtr CreateSegmentationCameraImpl (unsigned int _id, const std::string &_name)
Implementation for creating a segmentation camera.
virtual GeometryPtr CreateSphereImpl (unsigned int _id, const std::string &_name)=0
virtual SpotLightPtr CreateSpotLightImpl (unsigned int _id, const std::string &_name)=0
virtual TextPtr CreateTextImpl (unsigned int _id, const std::string &_name)
Implementation for creating a text's geometry object.
virtual ThermalCameraPtr CreateThermalCameraImpl (unsigned int _id, const std::string &_name)
Implementation for creating a thermal camera.
virtual VisualPtr CreateVisualImpl (unsigned int _id, const std::string &_name)=0
virtual WideAngleCameraPtr CreateWideAngleCameraImpl (unsigned int _id, const std::string &_name)
Implementation for creating a wide angle camera.
virtual WireBoxPtr CreateWireBoxImpl (unsigned int _id, const std::string &_name)=0
Implementation for creating a wire box geometry.
virtual bool InitImpl ()=0
virtual LightStorePtr Lights () const =0
virtual bool LoadImpl ()=0
virtual MaterialMapPtr Materials () const =0
virtual bool RegisterLight (LightPtr _light)
virtual bool RegisterSensor (SensorPtr _vensor)
virtual bool RegisterVisual (VisualPtr _visual)
virtual SensorStorePtr Sensors () const =0
virtual VisualStorePtr Visuals () const =0
Protected Attributes
math::Color backgroundColor
Scene background color. Default should be black.
MaterialPtr backgroundMaterial
Scene background material.
std::array< math::Color, 4 > gradientBackgroundColor
The four corners of the gradient background color. Next is the description of how to interpret each value of the array: 0: Top left corner color. 1: Bottom left corner color. 2: Top right corner color. 3: Bottom right corner color. Default should be black.
unsigned int id
bool initialized
bool isGradientBackgroundColor = false
Whether the scene has a gradient background.
bool loaded
std::string name
std::chrono::steady_clock::duration time
Constructor & Destructor Documentation
BaseScene()
BaseScene (unsigned int _id, const std::string & _name) protected
~BaseScene()
virtual ~BaseScene () virtual
Member Function Documentation
BackgroundColor()
virtual math::Color BackgroundColor () const override virtual
BackgroundMaterial()
virtual MaterialPtr BackgroundMaterial () const override virtual
CameraPassCountPerGpuFlush()
virtual uint8_t CameraPassCountPerGpuFlush () const override virtual
Reimplemented in Ogre2Scene.
Clear()
virtual void Clear () override virtual
Reimplemented in Ogre2Scene, and OgreScene.
CreateArrowVisual() [1/4]
virtual ArrowVisualPtr CreateArrowVisual () override virtual
CreateArrowVisual() [2/4]
virtual ArrowVisualPtr CreateArrowVisual (const std::string & _name) override virtual
CreateArrowVisual() [3/4]
virtual ArrowVisualPtr CreateArrowVisual (unsigned int _id) override virtual
CreateArrowVisual() [4/4]
virtual ArrowVisualPtr CreateArrowVisual (unsigned int _id, const std::string & _name) override virtual
CreateArrowVisualImpl()
virtual ArrowVisualPtr CreateArrowVisualImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateAxisVisual() [1/4]
virtual AxisVisualPtr CreateAxisVisual () override virtual
CreateAxisVisual() [2/4]
virtual AxisVisualPtr CreateAxisVisual (const std::string & _name) override virtual
CreateAxisVisual() [3/4]
virtual AxisVisualPtr CreateAxisVisual (unsigned int _id) override virtual
CreateAxisVisual() [4/4]
virtual AxisVisualPtr CreateAxisVisual (unsigned int _id, const std::string & _name) override virtual
CreateAxisVisualImpl()
virtual AxisVisualPtr CreateAxisVisualImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateBoundingBoxCamera() [1/4]
virtual BoundingBoxCameraPtr CreateBoundingBoxCamera () override virtual
CreateBoundingBoxCamera() [2/4]
virtual BoundingBoxCameraPtr CreateBoundingBoxCamera (const std::string & _name) override virtual
CreateBoundingBoxCamera() [3/4]
virtual BoundingBoxCameraPtr CreateBoundingBoxCamera (const unsigned int _id) override virtual
CreateBoundingBoxCamera() [4/4]
virtual BoundingBoxCameraPtr CreateBoundingBoxCamera (const unsigned int _id, const std::string & _name) override virtual
CreateBoundingBoxCameraImpl()
virtual BoundingBoxCameraPtr CreateBoundingBoxCameraImpl (unsigned int _id, const std::string & _name) inline protected virtual
Implementation for creating a BoundingBox camera.
Parameters
[in] _id Unique id
[in] _name Name of BoundingBox camera
Returns
Pointer to BoundingBox camera
Reimplemented in Ogre2Scene.
References std::endl(), and gzerr.
CreateBox()
virtual GeometryPtr CreateBox () override virtual
CreateBoxImpl()
virtual GeometryPtr CreateBoxImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateCamera() [1/4]
virtual CameraPtr CreateCamera () override virtual
CreateCamera() [2/4]
virtual CameraPtr CreateCamera (const std::string & _name) override virtual
CreateCamera() [3/4]
virtual CameraPtr CreateCamera (unsigned int _id) override virtual
CreateCamera() [4/4]
virtual CameraPtr CreateCamera (unsigned int _id, const std::string & _name) override virtual
CreateCameraImpl()
virtual CameraPtr CreateCameraImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateCapsule()
virtual CapsulePtr CreateCapsule () override virtual
CreateCapsuleImpl()
virtual CapsulePtr CreateCapsuleImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implementation for creating a capsule geometry object.
Parameters
[in] _id unique object id.
[in] _name unique object name.
Returns
Pointer to a capsule geometry object
Implemented in Ogre2Scene, and OgreScene.
CreateCOMVisual() [1/4]
virtual COMVisualPtr CreateCOMVisual () override virtual
CreateCOMVisual() [2/4]
virtual COMVisualPtr CreateCOMVisual (const std::string & _name) override virtual
CreateCOMVisual() [3/4]
virtual COMVisualPtr CreateCOMVisual (unsigned int _id) override virtual
CreateCOMVisual() [4/4]
virtual COMVisualPtr CreateCOMVisual (unsigned int _id, const std::string & _name) override virtual
CreateCOMVisualImpl()
virtual COMVisualPtr CreateCOMVisualImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implementation for creating CoM visual.
Parameters
[in] _id Unique id
[in] _name Name of CoM visual
Returns
Pointer to a CoM visual object
Implemented in Ogre2Scene, and OgreScene.
CreateCone()
virtual GeometryPtr CreateCone () override virtual
CreateConeImpl()
virtual GeometryPtr CreateConeImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateCylinder()
virtual GeometryPtr CreateCylinder () override virtual
CreateCylinderImpl()
virtual GeometryPtr CreateCylinderImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateDepthCamera() [1/4]
virtual DepthCameraPtr CreateDepthCamera () override virtual
CreateDepthCamera() [2/4]
virtual DepthCameraPtr CreateDepthCamera (const std::string & _name) override virtual
CreateDepthCamera() [3/4]
virtual DepthCameraPtr CreateDepthCamera (const unsigned int _id) override virtual
CreateDepthCamera() [4/4]
virtual DepthCameraPtr CreateDepthCamera (const unsigned int _id, const std::string & _name) override virtual
CreateDepthCameraImpl()
virtual DepthCameraPtr CreateDepthCameraImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateDirectionalLight() [1/4]
virtual DirectionalLightPtr CreateDirectionalLight () override virtual
CreateDirectionalLight() [2/4]
virtual DirectionalLightPtr CreateDirectionalLight (const std::string & _name) override virtual
CreateDirectionalLight() [3/4]
virtual DirectionalLightPtr CreateDirectionalLight (unsigned int _id) override virtual
CreateDirectionalLight() [4/4]
virtual DirectionalLightPtr CreateDirectionalLight (unsigned int _id, const std::string & _name) override virtual
CreateDirectionalLightImpl()
virtual DirectionalLightPtr CreateDirectionalLightImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateGizmoVisual() [1/4]
virtual GizmoVisualPtr CreateGizmoVisual () override virtual
CreateGizmoVisual() [2/4]
virtual GizmoVisualPtr CreateGizmoVisual (const std::string & _name) override virtual
CreateGizmoVisual() [3/4]
virtual GizmoVisualPtr CreateGizmoVisual (unsigned int _id) override virtual
CreateGizmoVisual() [4/4]
virtual GizmoVisualPtr CreateGizmoVisual (unsigned int _id, const std::string & _name) override virtual
CreateGizmoVisualImpl()
virtual GizmoVisualPtr CreateGizmoVisualImpl (unsigned int _id, const std::string & _name) inline protected virtual
Implementation for creating a GizmoVisual.
Parameters
[in] _id Unique id
[in] _name Name of GizmoVisual
Reimplemented in Ogre2Scene, and OgreScene.
References std::endl(), and gzerr.
CreateGlobalIlluminationCiVct() [1/4]
virtual GlobalIlluminationCiVctPtr CreateGlobalIlluminationCiVct () override virtual
CreateGlobalIlluminationCiVct() [2/4]
virtual GlobalIlluminationCiVctPtr CreateGlobalIlluminationCiVct (const std::string & _name) override virtual
CreateGlobalIlluminationCiVct() [3/4]
virtual GlobalIlluminationCiVctPtr CreateGlobalIlluminationCiVct (unsigned int _id) override virtual
CreateGlobalIlluminationCiVct() [4/4]
virtual GlobalIlluminationCiVctPtr CreateGlobalIlluminationCiVct (unsigned int _id, const std::string & _name) override virtual
CreateGlobalIlluminationCiVctImpl()
virtual GlobalIlluminationCiVctPtr CreateGlobalIlluminationCiVctImpl (unsigned int _id, const std::string & _name) inline protected virtual
Implementation for creating a GlobalIlluminationCiVct.
Parameters
[in] _id Unique id.
[in] _name Name of GlobalIlluminationCiVct.
Returns
Pointer to the created Global Illumination CIVCT solution.
Reimplemented in Ogre2Scene.
References std::endl(), and gzerr.
CreateGlobalIlluminationVct() [1/4]
virtual GlobalIlluminationVctPtr CreateGlobalIlluminationVct () override virtual
CreateGlobalIlluminationVct() [2/4]
virtual GlobalIlluminationVctPtr CreateGlobalIlluminationVct (const std::string & _name) override virtual
CreateGlobalIlluminationVct() [3/4]
virtual GlobalIlluminationVctPtr CreateGlobalIlluminationVct (unsigned int _id) override virtual
CreateGlobalIlluminationVct() [4/4]
virtual GlobalIlluminationVctPtr CreateGlobalIlluminationVct (unsigned int _id, const std::string & _name) override virtual
CreateGlobalIlluminationVctImpl()
virtual GlobalIlluminationVctPtr CreateGlobalIlluminationVctImpl (unsigned int _id, const std::string & _name) inline protected virtual
Implementation for creating a GlobalIlluminationVct.
Parameters
[in] _id Unique id.
[in] _name Name of GlobalIlluminationVct.
Returns
Pointer to the created Global Illumination VCT solution.
Reimplemented in Ogre2Scene.
References std::endl(), and gzerr.
CreateGpuRays() [1/4]
virtual GpuRaysPtr CreateGpuRays () override virtual
CreateGpuRays() [2/4]
virtual GpuRaysPtr CreateGpuRays (const std::string & _name) override virtual
CreateGpuRays() [3/4]
virtual GpuRaysPtr CreateGpuRays (const unsigned int _id) override virtual
CreateGpuRays() [4/4]
virtual GpuRaysPtr CreateGpuRays (const unsigned int _id, const std::string & _name) override virtual
CreateGpuRaysImpl()
virtual GpuRaysPtr CreateGpuRaysImpl (unsigned int _id, const std::string & _name) inline protected virtual
Implementation for creating GpuRays sensor.
Parameters
[in] _id Unique id
[in] _name Name of GpuRays sensor
Reimplemented in Ogre2Scene, and OgreScene.
References std::endl(), and gzerr.
CreateGrid()
virtual GridPtr CreateGrid () override virtual
CreateGridImpl()
virtual GridPtr CreateGridImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implementation for creating a grid geometry object.
Parameters
[in] _id unique object id.
[in] _name unique object name.
Returns
Pointer to a grid geometry object
Implemented in Ogre2Scene, and OgreScene.
CreateHeightmap()
virtual HeightmapPtr CreateHeightmap (const HeightmapDescriptor & _desc) override virtual
CreateHeightmapImpl()
virtual HeightmapPtr CreateHeightmapImpl (unsigned int _id, const std::string & _name, const HeightmapDescriptor & _desc) protected pure virtual
Implementation for creating a heightmap geometry.
Parameters
[in] _id Unique object id.
[in] _name Unique object name.
[in] _desc Heightmap descriptor.
Returns
Pointer to a heightmap geometry.
Implemented in Ogre2Scene, and OgreScene.
CreateInertiaVisual() [1/4]
virtual InertiaVisualPtr CreateInertiaVisual () override virtual
CreateInertiaVisual() [2/4]
virtual InertiaVisualPtr CreateInertiaVisual (const std::string & _name) override virtual
CreateInertiaVisual() [3/4]
virtual InertiaVisualPtr CreateInertiaVisual (unsigned int _id) override virtual
CreateInertiaVisual() [4/4]
virtual InertiaVisualPtr CreateInertiaVisual (unsigned int _id, const std::string & _name) override virtual
CreateInertiaVisualImpl()
virtual InertiaVisualPtr CreateInertiaVisualImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implementation for creating Inertia visual.
Parameters
[in] _id Unique id
[in] _name Name of inertia visual
Returns
Pointer to a inertia visual object
Implemented in Ogre2Scene, and OgreScene.
CreateJointVisual() [1/4]
virtual JointVisualPtr CreateJointVisual () override virtual
CreateJointVisual() [2/4]
virtual JointVisualPtr CreateJointVisual (const std::string & _name) override virtual
CreateJointVisual() [3/4]
virtual JointVisualPtr CreateJointVisual (unsigned int _id) override virtual
CreateJointVisual() [4/4]
virtual JointVisualPtr CreateJointVisual (unsigned int _id, const std::string & _name) override virtual
CreateJointVisualImpl()
virtual JointVisualPtr CreateJointVisualImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implementation for creating Joint visual.
Parameters
[in] _id Unique id
[in] _name Name of Joint visual
Returns
Pointer to a joint visual object
Implemented in Ogre2Scene, and OgreScene.
CreateLidarVisual() [1/4]
virtual LidarVisualPtr CreateLidarVisual () override virtual
CreateLidarVisual() [2/4]
virtual LidarVisualPtr CreateLidarVisual (const std::string & _name) override virtual
CreateLidarVisual() [3/4]
virtual LidarVisualPtr CreateLidarVisual (unsigned int _id) override virtual
CreateLidarVisual() [4/4]
virtual LidarVisualPtr CreateLidarVisual (unsigned int _id, const std::string & _name) override virtual
CreateLidarVisualImpl()
virtual LidarVisualPtr CreateLidarVisualImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implementation for creating a lidar visual.
Parameters
[in] _id unique object id.
[in] _name unique object name.
Returns
Pointer to a lidar visual
Implemented in Ogre2Scene, and OgreScene.
CreateLightVisual() [1/4]
virtual LightVisualPtr CreateLightVisual () override virtual
CreateLightVisual() [2/4]
virtual LightVisualPtr CreateLightVisual (const std::string & _name) override virtual
CreateLightVisual() [3/4]
virtual LightVisualPtr CreateLightVisual (unsigned int _id) override virtual
CreateLightVisual() [4/4]
virtual LightVisualPtr CreateLightVisual (unsigned int _id, const std::string & _name) override virtual
CreateLightVisualImpl()
virtual LightVisualPtr CreateLightVisualImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implementation for creating Light visual.
Parameters
[in] _id Unique id
[in] _name Name of light visual
Returns
Pointer to a light visual object
Implemented in Ogre2Scene, and OgreScene.
CreateMarker()
virtual MarkerPtr CreateMarker () override virtual
CreateMarkerImpl()
virtual MarkerPtr CreateMarkerImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implementation for creating a marker geometry object.
Parameters
[in] _id unique object id.
[in] _name unique object name.
Returns
Pointer to a marker geometry object
Implemented in Ogre2Scene, and OgreScene.
CreateMaterial() [1/2]
virtual MaterialPtr CreateMaterial (const common::Material & _material) override virtual
CreateMaterial() [2/2]
virtual MaterialPtr CreateMaterial (const std::string & _name = "") override virtual
CreateMaterialImpl()
virtual MaterialPtr CreateMaterialImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateMesh() [1/3]
virtual MeshPtr CreateMesh (const common::Mesh * _mesh) override virtual
CreateMesh() [2/3]
virtual MeshPtr CreateMesh (const MeshDescriptor & _desc) override virtual
CreateMesh() [3/3]
virtual MeshPtr CreateMesh (const std::string & _meshName) override virtual
CreateMeshImpl()
virtual MeshPtr CreateMeshImpl (unsigned int _id, const std::string & _name, const MeshDescriptor & _desc) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateObjectId()
virtual unsigned int CreateObjectId () protected virtual
Reimplemented in Ogre2Scene, and OgreScene.
CreateObjectName()
virtual std::string CreateObjectName (unsigned int _id, const std::string & _prefix) protected virtual
CreateParticleEmitter() [1/4]
virtual ParticleEmitterPtr CreateParticleEmitter () override virtual
CreateParticleEmitter() [2/4]
virtual ParticleEmitterPtr CreateParticleEmitter (const std::string & _name) override virtual
CreateParticleEmitter() [3/4]
virtual ParticleEmitterPtr CreateParticleEmitter (unsigned int _id) override virtual
CreateParticleEmitter() [4/4]
virtual ParticleEmitterPtr CreateParticleEmitter (unsigned int _id, const std::string & _name) override virtual
CreateParticleEmitterImpl()
virtual ParticleEmitterPtr CreateParticleEmitterImpl (unsigned int _id, const std::string & _name) inline protected virtual
Implementation for creating a ParticleEmitter.
Parameters
[in] _id Unique id.
[in] _name Name of ParticleEmitter.
Returns
Pointer to the created particle emitter.
Reimplemented in Ogre2Scene, and OgreScene.
References std::endl(), and gzerr.
CreatePlane()
virtual GeometryPtr CreatePlane () override virtual
CreatePlaneImpl()
virtual GeometryPtr CreatePlaneImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreatePointLight() [1/4]
virtual PointLightPtr CreatePointLight () override virtual
CreatePointLight() [2/4]
virtual PointLightPtr CreatePointLight (const std::string & _name) override virtual
CreatePointLight() [3/4]
virtual PointLightPtr CreatePointLight (unsigned int _id) override virtual
CreatePointLight() [4/4]
virtual PointLightPtr CreatePointLight (unsigned int _id, const std::string & _name) override virtual
CreatePointLightImpl()
virtual PointLightPtr CreatePointLightImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateProjector() [1/4]
virtual ProjectorPtr CreateProjector () override virtual
CreateProjector() [2/4]
virtual ProjectorPtr CreateProjector (const std::string & _name) override virtual
CreateProjector() [3/4]
virtual ProjectorPtr CreateProjector (unsigned int _id) override virtual
CreateProjector() [4/4]
virtual ProjectorPtr CreateProjector (unsigned int _id, const std::string & _name) override virtual
CreateProjectorImpl()
virtual ProjectorPtr CreateProjectorImpl (unsigned int _id, const std::string & _name) inline protected virtual
Implementation for creating a Projector.
Parameters
[in] _id Unique id.
[in] _name Name of Projector.
Returns
Pointer to the created projector
Reimplemented in Ogre2Scene, and OgreScene.
References std::endl(), and gzerr.
CreateRayQuery()
virtual RayQueryPtr CreateRayQuery () override virtual
CreateRayQueryImpl()
virtual RayQueryPtr CreateRayQueryImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateRenderTexture()
virtual RenderTexturePtr CreateRenderTexture () override virtual
CreateRenderTextureImpl()
virtual RenderTexturePtr CreateRenderTextureImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateRenderWindow()
virtual RenderWindowPtr CreateRenderWindow () override virtual
CreateRenderWindowImpl()
virtual RenderWindowPtr CreateRenderWindowImpl (unsigned int _id, const std::string & _name) protected pure virtual
Render engine specific implementation for creating a render window.
Parameters
[in] _id unique object id
[in] _name object name
Returns
Pointer to the created render window.
Implemented in Ogre2Scene, and OgreScene.
CreateSegmentationCamera() [1/4]
virtual SegmentationCameraPtr CreateSegmentationCamera () override virtual
CreateSegmentationCamera() [2/4]
virtual SegmentationCameraPtr CreateSegmentationCamera (const std::string & _name) override virtual
CreateSegmentationCamera() [3/4]
virtual SegmentationCameraPtr CreateSegmentationCamera (const unsigned int _id) override virtual
CreateSegmentationCamera() [4/4]
virtual SegmentationCameraPtr CreateSegmentationCamera (const unsigned int _id, const std::string & _name) override virtual
CreateSegmentationCameraImpl()
virtual SegmentationCameraPtr CreateSegmentationCameraImpl (unsigned int _id, const std::string & _name) inline protected virtual
Implementation for creating a segmentation camera.
Parameters
[in] _id Unique id
[in] _name Name of segmentation camera
Returns
Pointer to segmentation camera
Reimplemented in Ogre2Scene.
References std::endl(), and gzerr.
CreateSphere()
virtual GeometryPtr CreateSphere () override virtual
CreateSphereImpl()
virtual GeometryPtr CreateSphereImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateSpotLight() [1/4]
virtual SpotLightPtr CreateSpotLight () override virtual
CreateSpotLight() [2/4]
virtual SpotLightPtr CreateSpotLight (const std::string & _name) override virtual
CreateSpotLight() [3/4]
virtual SpotLightPtr CreateSpotLight (unsigned int _id) override virtual
CreateSpotLight() [4/4]
virtual SpotLightPtr CreateSpotLight (unsigned int _id, const std::string & _name) override virtual
CreateSpotLightImpl()
virtual SpotLightPtr CreateSpotLightImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateText()
virtual TextPtr CreateText () override virtual
CreateTextImpl()
virtual TextPtr CreateTextImpl (unsigned int _id, const std::string & _name) protected virtual
Implementation for creating a text's geometry object.
Parameters
[in] _id unique object id.
[in] _name unique object name.
Returns
Pointer to a text geometry object
Reimplemented in Ogre2Scene, and OgreScene.
CreateThermalCamera() [1/4]
virtual ThermalCameraPtr CreateThermalCamera () override virtual
CreateThermalCamera() [2/4]
virtual ThermalCameraPtr CreateThermalCamera (const std::string & _name) override virtual
CreateThermalCamera() [3/4]
virtual ThermalCameraPtr CreateThermalCamera (const unsigned int _id) override virtual
CreateThermalCamera() [4/4]
virtual ThermalCameraPtr CreateThermalCamera (const unsigned int _id, const std::string & _name) override virtual
CreateThermalCameraImpl()
virtual ThermalCameraPtr CreateThermalCameraImpl (unsigned int _id, const std::string & _name) inline protected virtual
Implementation for creating a thermal camera.
Parameters
[in] _id Unique id
[in] _name Name of thermal camera
Reimplemented in Ogre2Scene, and OgreScene.
References std::endl(), and gzerr.
CreateVisual() [1/4]
virtual VisualPtr CreateVisual () override virtual
CreateVisual() [2/4]
virtual VisualPtr CreateVisual (const std::string & _name) override virtual
CreateVisual() [3/4]
virtual VisualPtr CreateVisual (unsigned int _id) override virtual
CreateVisual() [4/4]
virtual VisualPtr CreateVisual (unsigned int _id, const std::string & _name) override virtual
CreateVisualImpl()
virtual VisualPtr CreateVisualImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
CreateWideAngleCamera() [1/4]
virtual WideAngleCameraPtr CreateWideAngleCamera () override virtual
CreateWideAngleCamera() [2/4]
virtual WideAngleCameraPtr CreateWideAngleCamera (const std::string & _name) override virtual
CreateWideAngleCamera() [3/4]
virtual WideAngleCameraPtr CreateWideAngleCamera (const unsigned int _id) override virtual
CreateWideAngleCamera() [4/4]
virtual WideAngleCameraPtr CreateWideAngleCamera (const unsigned int _id, const std::string & _name) override virtual
CreateWideAngleCameraImpl()
virtual WideAngleCameraPtr CreateWideAngleCameraImpl (unsigned int _id, const std::string & _name) inline protected virtual
Implementation for creating a wide angle camera.
Parameters
[in] _id Unique id
[in] _name Name of wide angle camera
Returns
Pointer to wide angle camera
Reimplemented in Ogre2Scene, and OgreScene.
References std::endl(), and gzerr.
CreateWireBox()
virtual WireBoxPtr CreateWireBox () override virtual
CreateWireBoxImpl()
virtual WireBoxPtr CreateWireBoxImpl (unsigned int _id, const std::string & _name) protected pure virtual
Implementation for creating a wire box geometry.
Parameters
[in] _id unique object id.
[in] _name unique object name.
Returns
Pointer to a wire box geometry object
Implemented in Ogre2Scene, and OgreScene.
Destroy()
virtual void Destroy () override virtual
Reimplemented in Ogre2Scene, and OgreScene.
DestroyLight()
virtual void DestroyLight (LightPtr _light, bool _recursive = false) override virtual
DestroyLightById()
virtual void DestroyLightById (unsigned int _id) override virtual
DestroyLightByIndex()
virtual void DestroyLightByIndex (unsigned int _index) override virtual
DestroyLightByName()
virtual void DestroyLightByName (const std::string & _name) override virtual
DestroyLights()
virtual void DestroyLights () override virtual
DestroyMaterial()
virtual void DestroyMaterial (MaterialPtr _material) override virtual
DestroyMaterials()
virtual void DestroyMaterials () override virtual
DestroyNode()
virtual void DestroyNode (NodePtr _node, bool _recursive = false) override virtual
DestroyNodeById()
virtual void DestroyNodeById (unsigned int _id) override virtual
DestroyNodeByIndex()
virtual void DestroyNodeByIndex (unsigned int _index) override virtual
DestroyNodeByName()
virtual void DestroyNodeByName (const std::string & _name) override virtual
DestroyNodes()
virtual void DestroyNodes () override virtual
DestroySensor()
virtual void DestroySensor (SensorPtr _sensor, bool _recursive = false) override virtual
DestroySensorById()
virtual void DestroySensorById (unsigned int _id) override virtual
DestroySensorByIndex()
virtual void DestroySensorByIndex (unsigned int _index) override virtual
DestroySensorByName()
virtual void DestroySensorByName (const std::string & _name) override virtual
DestroySensors()
virtual void DestroySensors () override virtual
DestroyVisual()
virtual void DestroyVisual (VisualPtr _visual, bool _recursive = false) override virtual
DestroyVisualById()
virtual void DestroyVisualById (unsigned int _id) override virtual
DestroyVisualByIndex()
virtual void DestroyVisualByIndex (unsigned int _index) override virtual
DestroyVisualByName()
virtual void DestroyVisualByName (const std::string & _name) override virtual
DestroyVisuals()
virtual void DestroyVisuals () override virtual
Fini()
virtual void Fini () override virtual
Reimplemented in Ogre2Scene, and OgreScene.
GradientBackgroundColor()
virtual std::array<math::Color, 4> GradientBackgroundColor () const override virtual
HasLight()
virtual bool HasLight (ConstLightPtr _light) const override virtual
HasLightId()
virtual bool HasLightId (unsigned int _id) const override virtual
HasLightName()
virtual bool HasLightName (const std::string & _name) const override virtual
HasNode()
virtual bool HasNode (ConstNodePtr _node) const override virtual
HasNodeId()
virtual bool HasNodeId (unsigned int _id) const override virtual
HasNodeName()
virtual bool HasNodeName (const std::string & _name) const override virtual
HasSensor()
virtual bool HasSensor (ConstSensorPtr _sensor) const override virtual
HasSensorId()
virtual bool HasSensorId (unsigned int _id) const override virtual
HasSensorName()
virtual bool HasSensorName (const std::string & _name) const override virtual
HasVisual()
virtual bool HasVisual (ConstVisualPtr _visual) const override virtual
HasVisualId()
virtual bool HasVisualId (unsigned int _id) const override virtual
HasVisualName()
virtual bool HasVisualName (const std::string & _name) const override virtual
Id()
virtual unsigned int Id () const override virtual
Init()
virtual void Init () override virtual
InitImpl()
virtual bool InitImpl () protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
IsGradientBackgroundColor()
virtual bool IsGradientBackgroundColor () const override virtual
IsInitialized()
virtual bool IsInitialized () const override virtual
IsLoaded()
virtual bool IsLoaded () const virtual
LegacyAutoGpuFlush()
virtual bool LegacyAutoGpuFlush () const override virtual
Reimplemented in Ogre2Scene.
LightById()
virtual LightPtr LightById (unsigned int _id) const override virtual
LightByIndex()
virtual LightPtr LightByIndex (unsigned int _index) const override virtual
LightByName()
virtual LightPtr LightByName (const std::string & _name) const override virtual
LightCount()
virtual unsigned int LightCount () const override virtual
Lights()
virtual LightStorePtr Lights () const protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
Load()
virtual void Load () override virtual
LoadImpl()
virtual bool LoadImpl () protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
Material()
virtual MaterialPtr Material (const std::string & _name) const override virtual
MaterialRegistered()
virtual bool MaterialRegistered (const std::string & _name) const override virtual
Materials()
virtual MaterialMapPtr Materials () const protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
Name()
virtual std::string Name () const override virtual
NodeById()
virtual NodePtr NodeById (unsigned int _id) const override virtual
NodeByIndex()
virtual NodePtr NodeByIndex (unsigned int _index) const override virtual
NodeByName()
virtual NodePtr NodeByName (const std::string & _name) const override virtual
NodeCount()
virtual unsigned int NodeCount () const override virtual
PostRender()
virtual void PostRender () override virtual
Reimplemented in Ogre2Scene.
PreRender()
virtual void PreRender () override virtual
Reimplemented in Ogre2Scene, and OgreScene.
RegisterLight()
virtual bool RegisterLight (LightPtr _light) protected virtual
RegisterMaterial()
virtual void RegisterMaterial (const std::string & _name, MaterialPtr _material) override virtual
RegisterSensor()
virtual bool RegisterSensor (SensorPtr _vensor) protected virtual
RegisterVisual()
virtual bool RegisterVisual (VisualPtr _visual) protected virtual
RemoveGradientBackgroundColor()
virtual void RemoveGradientBackgroundColor () override virtual
Reimplemented in OgreScene.
SensorById()
virtual SensorPtr SensorById (unsigned int _id) const override virtual
SensorByIndex()
virtual SensorPtr SensorByIndex (unsigned int _index) const override virtual
SensorByName()
virtual SensorPtr SensorByName (const std::string & _name) const override virtual
SensorCount()
virtual unsigned int SensorCount () const override virtual
Sensors()
virtual SensorStorePtr Sensors () const protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
SetActiveGlobalIllumination()
virtual void SetActiveGlobalIllumination (GlobalIlluminationBasePtr _gi) override virtual
Reimplemented in Ogre2Scene.
SetAmbientLight() [1/2]
virtual void SetAmbientLight (const math::Color & _color) override pure virtual
Implemented in Ogre2Scene, and OgreScene.
SetAmbientLight() [2/2]
virtual void SetAmbientLight (double _r, double _g, double _b, double _a = 1.0) override virtual
SetBackgroundColor() [1/2]
virtual void SetBackgroundColor (const math::Color & _color) override virtual
Reimplemented in Ogre2Scene, and OgreScene.
SetBackgroundColor() [2/2]
virtual void SetBackgroundColor (double _r, double _g, double _b, double _a = 1.0) override virtual
SetBackgroundMaterial()
virtual void SetBackgroundMaterial (MaterialPtr _material) override virtual
SetCameraPassCountPerGpuFlush()
virtual void SetCameraPassCountPerGpuFlush (uint8_t _numPass) override virtual
Reimplemented in Ogre2Scene.
SetGradientBackgroundColor()
virtual void SetGradientBackgroundColor (const std::array< math::Color, 4 > & _colors) override virtual
Reimplemented in OgreScene.
SetSkyEnabled()
virtual void SetSkyEnabled (bool _enabled) override virtual
Reimplemented in Ogre2Scene.
SetTime()
virtual void SetTime (const std::chrono::steady_clock::duration & _time) override virtual
Reimplemented in Ogre2Scene.
SkyEnabled()
virtual bool SkyEnabled () const override virtual
Reimplemented in Ogre2Scene.
Time()
virtual std::chrono::steady_clock::duration Time () const override virtual
UnregisterMaterial()
virtual void UnregisterMaterial (const std::string & _name) override virtual
UnregisterMaterials()
virtual void UnregisterMaterials () override virtual
VisualAt()
virtual VisualPtr VisualAt (const CameraPtr & _camera, const gz::math::Vector2i & _mousePos) override virtual
VisualById()
virtual VisualPtr VisualById (unsigned int _id) const override virtual
VisualByIndex()
virtual VisualPtr VisualByIndex (unsigned int _index) const override virtual
VisualByName()
virtual VisualPtr VisualByName (const std::string & _name) const override virtual
VisualCount()
virtual unsigned int VisualCount () const override virtual
Visuals()
virtual VisualStorePtr Visuals () const protected pure virtual
Implemented in Ogre2Scene, and OgreScene.
Member Data Documentation
backgroundColor
math::Color backgroundColor protected
Scene background color. Default should be black.
backgroundMaterial
MaterialPtr backgroundMaterial protected
Scene background material.
gradientBackgroundColor
std::array<math::Color, 4> gradientBackgroundColor protected
The four corners of the gradient background color. Next is the description of how to interpret each value of the array: 0: Top left corner color. 1: Bottom left corner color. 2: Top right corner color. 3: Bottom right corner color. Default should be black.
id
unsigned int id protected
initialized
bool initialized protected
isGradientBackgroundColor
bool isGradientBackgroundColor = false protected
Whether the scene has a gradient background.
loaded
bool loaded protected
name
std::string name protected
time
std::chrono::steady_clock::duration time protected
Initial value:
=
        std::chrono::steady_clock::duration::zero()
The documentation for this class was generated from the following file:
BaseScene.hh