Gazebo Rendering: BaseJointVisual< T > Class Template Reference
Gazebo Rendering
API Reference
8.2.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
BaseJointVisual< T > Class Template Reference
Base implementation of a joint visual.
#include <BaseJointVisual.hh>
Public Member Functions
virtual ~BaseJointVisual ()
Destructor.
virtual ArrowVisualPtr ArrowVisual () const override
Get the arrow visual which represents the axis attached to the child.
virtual gz::math::Vector3d Axis () const override
Get axis vector.
virtual gz::math::Vector3d ParentAxis () const override
Get parent axis vector.
virtual JointVisualPtr ParentAxisVisual () const override
Get the JointVisual which is attached to the parent.
virtual void SetAxis (const gz::math::Vector3d &_axis, bool _useParentFrame) override
Create an axis and attach it to the joint visual.
virtual void SetParentAxis (const gz::math::Vector3d &_axis, const std::string &_parentName, bool _useParentFrame) override
Create a parent axis for hinge2 and universal joint types and attach it to the joint visual.
virtual void SetType (const JointVisualType _type) override
Set type for joint visual.
virtual void SetVisible (bool _visible) override
Specify if this visual is visible.
virtual JointVisualType Type () const override
Get joint visual type.
virtual bool UpdateAxis (const gz::math::Vector3d &_axis, bool _useParentFrame) override
Update an axis' arrow visual.
virtual bool UpdateParentAxis (const gz::math::Vector3d &_axis, bool _useParentFrame) override
Update the parent axis' arrow visual if it exists.
Public Member Functions inherited from JointVisual
virtual ~JointVisual ()
Destructor.
Public Member Functions inherited from Visual
virtual ~Visual ()
Destructor.
virtual void AddGeometry (GeometryPtr _geometry)=0
Add the given geometry to this visual. If the given node is already attached, no work will be done.
virtual void AddVisibilityFlags (uint32_t _flags)=0
Add visibility flags.
virtual gz::math::AxisAlignedBox BoundingBox () const =0
Get the bounding box in world frame coordinates.
virtual VisualPtr Clone (const std::string &_name, NodePtr _newParent) const =0
Clone the visual (and its children) with a new name.
virtual GeometryPtr GeometryByIndex (unsigned int _index) const =0
Get geometry at given index. If no geometry exists at given index, NULL will be returned.
virtual unsigned int GeometryCount () const =0
Get the number of geometries attached to this visual.
virtual bool HasGeometry (ConstGeometryPtr _geometry) const =0
Determine if given geometry is attached to this visual.
virtual gz::math::AxisAlignedBox LocalBoundingBox () const =0
Get the local bounding box of the visual.
virtual MaterialPtr Material () const =0
Get the material assigned to attached visuals and geometries.
virtual void RemoveGeometries ()=0
Remove all attached geometries from this visual.
virtual GeometryPtr RemoveGeometry (GeometryPtr _geometry)=0
Remove the given geometry from this visual. If the given node is not a child of this visual, no work will be done.
virtual GeometryPtr RemoveGeometryByIndex (unsigned int _index)=0
Remove the geometry at the given index from this visual. If the specified node is not attached this visual, no work will be done.
virtual void RemoveVisibilityFlags (uint32_t _flags)=0
Remove visibility flags.
virtual void SetChildMaterial (MaterialPtr _material, bool _unique=true)=0
Set the material for all attached visuals only.
virtual void SetGeometryMaterial (MaterialPtr _material, bool _unique=true)=0
Set the material for all attached geometries only.
virtual void SetMaterial (const std::string &_name, bool _unique=true)=0
Set the material for all attached visuals and geometries. The specified material will be retrieved from Scene::Material using the given material name. If no material is registered with the given name, no work will be done.
virtual void SetMaterial (MaterialPtr _material, bool _unique=true)=0
Set the material for all attached visuals and geometries.
virtual void SetStatic (bool _static)=0
Tells Render Engine this Visual will be static (i.e. won't move, rotate or scale) You can still move, rotate or scale the Visual; however doing so has a performance impact. How much of an impact will depend on the rendering backend being used.
virtual void SetVisibilityFlags (uint32_t _flags)=0
Set visibility flags.
virtual void SetWireframe (bool _show)=0
Enable or disable wireframe.
virtual bool Static () const =0
Get whether the visual is static.
virtual uint32_t VisibilityFlags () const =0
Get visibility flags.
virtual bool Wireframe () const =0
Get whether wireframe is enabled for this visual.
Public Member Functions inherited from Node
virtual ~Node ()
Destructor.
virtual void AddChild (NodePtr _child)=0
Add the given node to this node. If the given node is already a child, no work will be done.
virtual NodePtr ChildById (unsigned int _id) const =0
Get node with given ID. If no child exists with given ID, NULL will be returned.
virtual NodePtr ChildByIndex (unsigned int _index) const =0
Get node at given index. If no child exists at given index, NULL will be returned.
virtual NodePtr ChildByName (const std::string &_name) const =0
Get node with given name. If no child exists with given name, NULL will be returned.
virtual unsigned int ChildCount () const =0
Get number of child nodes.
virtual bool HasChild (ConstNodePtr _child) const =0
Determine if given node is an attached child.
virtual bool HasChildId (unsigned int _id) const =0
Determine if node with given ID is an attached child.
virtual bool HasChildName (const std::string &_name) const =0
Determine if node with given name is an attached child.
virtual bool HasParent () const =0
Determine if this Node is attached to another Node.
virtual bool HasUserData (const std::string &_key) const =0
Check if node has custom data.
virtual bool InheritScale () const =0
Determine if this node inherits scale from this parent.
virtual math::Pose3d InitialLocalPose () const =0
Get the initial local pose.
virtual math::Pose3d LocalPose () const =0
Get the local pose.
virtual math::Vector3d LocalPosition () const =0
Get the local position.
virtual math::Quaterniond LocalRotation () const =0
Get the local rotation.
virtual math::Vector3d LocalScale () const =0
Get the local scale.
virtual math::Vector3d Origin () const =0
Get position of origin.
virtual NodePtr Parent () const =0
Get the parent Node.
virtual NodePtr RemoveChild (NodePtr _child)=0
Remove (detach) the given node from this node. If the given node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildById (unsigned int _id)=0
Remove (detach) the node with the given ID from this node. If the specified node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildByIndex (unsigned int _index)=0
Remove (detach) the node at the given index from this node. If the specified node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildByName (const std::string &_name)=0
Remove (detach) the node with the given name from this node. If the specified node is not a child of this node, no work will be done.
virtual void RemoveChildren ()=0
Remove all child nodes from this node This detaches all the child nodes but does not destroy them.
virtual void RemoveParent ()=0
Detach this Node from its parent. If this Node does not have a parent, no work will be done.
virtual void Scale (const math::Vector3d &_scale)=0
Scale the current scale by the given scalars.
virtual void Scale (double _scale)=0
Scale the current scale by the given scalar. The given scalar will be assigned to the x, y, and z coordinates.
virtual void Scale (double _x, double _y, double _z)=0
Scale the current scale by the given scalars.
virtual void SetInheritScale (bool _inherit)=0
Specify if this node inherits scale from its parent.
virtual void SetLocalPose (const math::Pose3d &_pose)=0
Set the local pose.
virtual void SetLocalPosition (const math::Vector3d &_position)=0
Set the local position.
virtual void SetLocalPosition (double _x, double _y, double _z)=0
Set the local position.
virtual void SetLocalRotation (const math::Quaterniond &_rotation)=0
Set the local rotation.
virtual void SetLocalRotation (double _r, double _p, double _y)=0
Set the local rotation.
virtual void SetLocalRotation (double _w, double _x, double _y, double _z)=0
Set the local rotation.
virtual void SetLocalScale (const math::Vector3d &_scale)=0
Set the local scale.
virtual void SetLocalScale (double _scale)=0
Set the local scale. The given scale will be assigned to the x, y, and z coordinates.
virtual void SetLocalScale (double _x, double _y, double _z)=0
Set the local scale.
virtual void SetOrigin (const math::Vector3d &_origin)=0
Set position of origin. The position should be relative to the original origin of the geometry.
virtual void SetOrigin (double _x, double _y, double _z)=0
Set position of origin. The position should be relative to the original origin of the geometry.
virtual void SetUserData (const std::string &_key, Variant _value)=0
Store any custom data associated with this node.
virtual void SetWorldPose (const math::Pose3d &_pose)=0
Set the world pose.
virtual void SetWorldPosition (const math::Vector3d &_position)=0
Set the world position.
virtual void SetWorldPosition (double _x, double _y, double _z)=0
Set the world position.
virtual void SetWorldRotation (const math::Quaterniond &_rotation)=0
Set the world rotation.
virtual void SetWorldRotation (double _r, double _p, double _y)=0
Set the world rotation.
virtual void SetWorldRotation (double _w, double _x, double _y, double _z)=0
Set the world rotation.
virtual void SetWorldScale (const math::Vector3d &_scale)=0
Set the world scale.
virtual void SetWorldScale (double _scale)=0
Set the world scale. The given scale will be assigned to the x, y, and z coordinates.
virtual void SetWorldScale (double _x, double _y, double _z)=0
Set the world scale.
virtual Variant UserData (const std::string &_key) const =0
Get custom data stored in this node.
virtual math::Pose3d WorldPose () const =0
Get the world pose.
virtual math::Vector3d WorldPosition () const =0
Get the world position.
virtual math::Quaterniond WorldRotation () const =0
Get the world rotation.
virtual math::Vector3d WorldScale () const =0
Get the world scale.
virtual math::Pose3d WorldToLocal (const math::Pose3d &_pose) const =0
Convert given world pose to local pose.
Public Member Functions inherited from Object
virtual ~Object ()
Destructor.
virtual unsigned int Id () const =0
Get the object ID. This ID will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
virtual std::string Name () const =0
Get the object name. This name will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
virtual void PostRender ()=0
Post process this object and any of its children after rendering.
virtual ScenePtr Scene () const =0
Get the Scene that created this object.
Protected Member Functions
BaseJointVisual ()
Constructor.
void CreateAxis ()
Helper function to create axis visual.
void CreateParentAxis ()
Helper function to create parent axis visual.
virtual void Destroy () override
Destroy any resources associated with this object. Invoking any other functions after destroying an object will result in undefined behavior.
virtual void Init () override
virtual void PreRender () override
Prepare this object and any of its children for rendering. This should be called for each object in a scene just before rendering, which can be achieved by a single call to Scene::PreRender.
void ScaleToChild ()
Scale the joint visual according to the joint's child.
void UpdateAxisImpl (ArrowVisualPtr _arrowVisual, const gz::math::Vector3d &_axis, bool _useParentFrame)
Implementation for updating an axis' arrow visual.
Protected Attributes
ArrowVisualPtr arrowVisual = nullptr
The visual representing the one joint axis. There can be only one axis visual per joint visual, so joints with two axes have a 2nd JointVisual with its own arrowVisual.
gz::math::Vector3d axis
Joint visual axis vector.
AxisVisualPtr axisVisual = nullptr
The joint's XYZ frame visual.
bool dirtyAxis = false
Flag to indicate axis data has changed.
bool dirtyJointType = false
Flag to indicate joint visual type has changed.
bool dirtyParentAxis = false
Flag to indicate parent axis data has changed.
std::string jointParentName = ""
Joint parent name.
JointVisualType jointVisualType
Type of joint visualization.
gz::math::Vector3d parentAxis
Parent axis vector.
bool parentAxisUseParentFrame = false
Flag to indicate whether parent axis vector is expressed in joint parent frame.
JointVisualPtr parentAxisVis = nullptr
Second joint visual for hinge2 and universal joints. It is a simplified visual without an XYZ frame.
gz::math::Vector3d scaleToChild
Scale based on the size of the joint's child.
bool updateAxis = false
Flag to update the axis visual.
bool updateParentAxis = false
Flag to update the parent axis visual.
bool useParentFrame = false
Flag to indicate whether axis vector is expressed in joint parent frame.
Detailed Description
template<class T>
class gz::rendering::BaseJointVisual< T >
Base implementation of a joint visual.
Constructor & Destructor Documentation
BaseJointVisual()
BaseJointVisual protected
Constructor.
~BaseJointVisual()
~BaseJointVisual virtual
Destructor.
Member Function Documentation
ArrowVisual()
ArrowVisualPtr ArrowVisual () const override virtual
Get the arrow visual which represents the axis attached to the child.
Returns
Arrow visual.
Implements JointVisual.
Axis()
gz::math::Vector3d Axis () const override virtual
Get axis vector.
Returns
The axis vector.
Implements JointVisual.
CreateAxis()
void CreateAxis protected
Helper function to create axis visual.
References Scene::CreateArrowVisual().
CreateParentAxis()
void CreateParentAxis protected
Helper function to create parent axis visual.
References Scene::CreateJointVisual(), gzlog, and Scene::NodeByName().
Destroy()
void Destroy () override protected virtual
Destroy any resources associated with this object. Invoking any other functions after destroying an object will result in undefined behavior.
Implements Object.
Init()
void Init override protected virtual
References Scene::CreateAxisVisual().
ParentAxis()
gz::math::Vector3d ParentAxis () const override virtual
Get parent axis vector.
Returns
The parent axis vector.
Implements JointVisual.
ParentAxisVisual()
JointVisualPtr ParentAxisVisual () const override virtual
Get the JointVisual which is attached to the parent.
Returns
Parent axis visual.
Implements JointVisual.
PreRender()
void PreRender () override protected virtual
Prepare this object and any of its children for rendering. This should be called for each object in a scene just before rendering, which can be achieved by a single call to Scene::PreRender.
Implements Object.
ScaleToChild()
void ScaleToChild protected
Scale the joint visual according to the joint's child.
References std::max().
SetAxis()
void SetAxis (const gz::math::Vector3d & _axis, bool _useParentFrame) override virtual
Create an axis and attach it to the joint visual.
Parameters
[in] _axis Axis vector.
[in] _useParentFrame True if axis vector is expressed in parent frame.
Implements JointVisual.
SetParentAxis()
void SetParentAxis (const gz::math::Vector3d & _axis, const std::string & _parentName, bool _useParentFrame) override virtual
Create a parent axis for hinge2 and universal joint types and attach it to the joint visual.
Parameters
[in] _axis Axis vector.
[in] _parentName Joint parent name.
[in] _useParentFrame True if axis vector is expressed in parent frame.
Implements JointVisual.
References gzlog, gz::rendering::JVT_REVOLUTE2, and gz::rendering::JVT_UNIVERSAL.
SetType()
void SetType (const JointVisualType _type) override virtual
Set type for joint visual.
Parameters
[in] _type The type of visualisation for joint.
Implements JointVisual.
SetVisible()
void SetVisible (bool _visible) override virtual
Specify if this visual is visible.
Parameters
[in] _visible True if this visual should be made visible
Implements Visual.
References gz::rendering::JVT_REVOLUTE2, gz::rendering::JVT_UNIVERSAL, and Visual::SetVisible().
Type()
JointVisualType Type () const override virtual
Get joint visual type.
Returns
The joint visual type.
Implements JointVisual.
UpdateAxis()
bool UpdateAxis (const gz::math::Vector3d & _axis, bool _useParentFrame) override virtual
Update an axis' arrow visual.
Parameters
[in] _axis Axis vector.
[in] _useParentFrame True if axis vector is expressed in parent frame.
Returns
True if axis was updated else false.
Implements JointVisual.
UpdateAxisImpl()
void UpdateAxisImpl (ArrowVisualPtr _arrowVisual, const gz::math::Vector3d & _axis, bool _useParentFrame) protected
Implementation for updating an axis' arrow visual.
Parameters
[in] _arrowVisual Arrow visual to be updated.
[in] _axis Axis vector.
[in] _useParentFrame True if the axis vector is expressed in the joint parent frame.
References Vector3< class >::Cross(), Vector3< class >::Dot(), gz::math::equal(), GZ_PI, Quaternion< class >::Inverse(), gz::rendering::JVT_GEARBOX, gz::rendering::JVT_REVOLUTE, gz::rendering::JVT_REVOLUTE2, gz::rendering::JVT_UNIVERSAL, Vector3< class >::Normalize(), Vector3< class >::Perpendicular(), Quaternion< class >::SetFromAxisAngle(), Vector3< class >::UnitX, Vector3< class >::UnitY, and Vector3< class >::UnitZ.
UpdateParentAxis()
bool UpdateParentAxis (const gz::math::Vector3d & _axis, bool _useParentFrame) override virtual
Update the parent axis' arrow visual if it exists.
Parameters
[in] _axis Axis vector.
[in] _useParentFrame True if axis vector is expressed in parent frame.
Returns
True if parent axis was updated else false.
Implements JointVisual.
Member Data Documentation
arrowVisual
ArrowVisualPtr arrowVisual = nullptr protected
The visual representing the one joint axis. There can be only one axis visual per joint visual, so joints with two axes have a 2nd JointVisual with its own arrowVisual.
axis
gz::math::Vector3d axis protected
Initial value:
=
          gz::math::Vector3d::Zero
Joint visual axis vector.
axisVisual
AxisVisualPtr axisVisual = nullptr protected
The joint's XYZ frame visual.
dirtyAxis
bool dirtyAxis = false protected
Flag to indicate axis data has changed.
dirtyJointType
bool dirtyJointType = false protected
Flag to indicate joint visual type has changed.
dirtyParentAxis
bool dirtyParentAxis = false protected
Flag to indicate parent axis data has changed.
jointParentName
std::string jointParentName = "" protected
Joint parent name.
jointVisualType
JointVisualType jointVisualType protected
Initial value:
=
          JointVisualType::JVT_NONE
Type of joint visualization.
parentAxis
gz::math::Vector3d parentAxis protected
Initial value:
=
          gz::math::Vector3d::Zero
Parent axis vector.
parentAxisUseParentFrame
bool parentAxisUseParentFrame = false protected
Flag to indicate whether parent axis vector is expressed in joint parent frame.
parentAxisVis
JointVisualPtr parentAxisVis = nullptr protected
Second joint visual for hinge2 and universal joints. It is a simplified visual without an XYZ frame.
scaleToChild
gz::math::Vector3d scaleToChild protected
Initial value:
=
          gz::math::Vector3d::One
Scale based on the size of the joint's child.
updateAxis
bool updateAxis = false protected
Flag to update the axis visual.
updateParentAxis
bool updateParentAxis = false protected
Flag to update the parent axis visual.
useParentFrame
bool useParentFrame = false protected
Flag to indicate whether axis vector is expressed in joint parent frame.
The documentation for this class was generated from the following file:
BaseJointVisual.hh