Gazebo Transport: AdvertiseMessage< T > Class Template Reference
Gazebo Transport
API Reference
8.5.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
AdvertiseMessage< T > Class Template Reference
Advertise packet used in the discovery protocol to broadcast information about the node advertising a topic. The information sent contains the name of the protobuf message type advertised. This message is used for advertising messages and services. 'T' is the Publisher type used inside this AdvertiseMessage object.
#include <ignition/transport/Packet.hh>
Public Member Functions
AdvertiseMessage ()=default
Constructor.
AdvertiseMessage (const Header &_header, const T &_publisher)
Constructor.
transport::Header Header () const
Get the message header.
size_t MsgLength () const
Get the total length of the message.
size_t Pack (char *_buffer) const
Serialize the advertise message.
T & Publisher ()
Get the publisher of this message.
void SetFromDiscovery (const msgs::Discovery &_msg)
Set from discovery message.
void SetHeader (const transport::Header &_header)
Set the header of the message.
void SetPublisher (const T &_publisher)
Set the publisher of this message.
size_t Unpack (const char *_buffer)
Unserialize a stream of bytes into an AdvertiseMessage.
Detailed Description
template<class T>
class ignition::transport::AdvertiseMessage< T >
Advertise packet used in the discovery protocol to broadcast information about the node advertising a topic. The information sent contains the name of the protobuf message type advertised. This message is used for advertising messages and services. 'T' is the Publisher type used inside this AdvertiseMessage object.
Deprecated:
This class is deprecated. Discovery uses the gz::msgs::Discovery message.
Constructor & Destructor Documentation
AdvertiseMessage() [1/2]
AdvertiseMessage () default
Constructor.
AdvertiseMessage() [2/2]
AdvertiseMessage (const Header & _header, const T & _publisher) inline
Constructor.
Parameters
[in] _header Message header.
[in] _publisher Contains the topic name, UUIDs, addresses.
Member Function Documentation
Header()
transport::Header Header () const inline
Get the message header.
Returns
Reference to the message header.
See also
SetHeader.
MsgLength()
size_t MsgLength () const inline
Get the total length of the message.
Returns
Return the length of the message in bytes.
References Header::HeaderLength().
Referenced by AdvertiseMessage< T >::Pack().
Pack()
size_t Pack (char * _buffer) const inline
Serialize the advertise message.
Parameters
[out] _buffer Buffer where the message will be serialized.
Returns
The length of the serialized message in bytes.
References AdvertiseMessage< T >::MsgLength(), and Header::Pack().
Publisher()
T& Publisher () inline
Get the publisher of this message.
Returns
Publisher.
See also
SetPublisher.
SetFromDiscovery()
void SetFromDiscovery (const msgs::Discovery & _msg) inline
Set from discovery message.
Parameters
[in] _msg Discovery message.
SetHeader()
void SetHeader (const transport::Header & _header) inline
Set the header of the message.
Parameters
[in] _header Message header.
See also
Header.
SetPublisher()
void SetPublisher (const T & _publisher) inline
Set the publisher of this message.
Parameters
[in] _publisher New publisher.
See also
Publisher.
Unpack()
size_t Unpack (const char * _buffer) inline
Unserialize a stream of bytes into an AdvertiseMessage.
Parameters
[out] _buffer Unpack the body from the buffer.
Returns
The number of bytes from the body.
The documentation for this class was generated from the following file:
gz/transport/Packet.hh