SDF: sdf::SDF_VERSION_NAMESPACE::Param Class Reference
Class
List
Hierarchy
Links
SDF Website
Report Documentation Issues
sdf::SDF_VERSION_NAMESPACE::Param Class Reference
A parameter class.
#include <sdf/sdf.hh>
Public Member Functions
Param (const Param &_param)
Copy constructor Note that the updateFunc member does not get copied.
Param (const std::string &_key, const std::string &_typeName, const std::string &_default, bool _required, const std::string &_description="")
Constructor.
Param (const std::string &_key, const std::string &_typeName, const std::string &_default, bool _required, const std::string &_minValue, const std::string &_maxValue, const std::string &_description="")
Constructor with min and max values.
Param (const std::string &_key, const std::string &_typeName, const std::string &_default, bool _required, const std::string &_minValue, const std::string &_maxValue, sdf::Errors &_errors, const std::string &_description="")
Constructor with min and max values.
Param (const std::string &_key, const std::string &_typeName, const std::string &_default, bool _required, sdf::Errors &_errors, const std::string &_description="")
Constructor.
Param (Param &&_param) noexcept=default
Move constructor.
virtual ~Param ()
Destructor.
ParamPtr Clone () const
Clone the parameter.
template<typename T >
bool Get (T &_value) const
Get the value of the parameter.
template<typename T >
bool Get (T &_value, sdf::Errors &_errors) const
Get the value of the parameter.
bool GetAny (std::any &_anyVal) const
Get the value of the parameter as a std::any.
bool GetAny (std::any &_anyVal, sdf::Errors &_errors) const
Get the value of the parameter as a std::any.
std::string GetAsString (const PrintConfig &_config=PrintConfig()) const
Get the value as a string.
std::string GetAsString (sdf::Errors &_errors, const PrintConfig &_config=PrintConfig()) const
Get the value as a string.
template<typename T >
bool GetDefault (T &_value) const
Get the default value of the parameter.
template<typename T >
bool GetDefault (T &_value, sdf::Errors &_errors) const
Get the default value of the parameter.
std::string GetDefaultAsString (const PrintConfig &_config=PrintConfig()) const
Get the default value as a string.
std::string GetDefaultAsString (sdf::Errors &_errors, const PrintConfig &_config=PrintConfig()) const
Get the default value as a string.
std::string GetDescription () const
Get the description of the parameter.
const std::string & GetKey () const
Get the key value.
std::optional< std::string > GetMaxValueAsString (const PrintConfig &_config=PrintConfig()) const
Get the maximum allowed value as a string.
std::optional< std::string > GetMaxValueAsString (sdf::Errors &_errors, const PrintConfig &_config=PrintConfig()) const
Get the maximum allowed value as a string.
std::optional< std::string > GetMinValueAsString (const PrintConfig &_config=PrintConfig()) const
Get the minimum allowed value as a string.
std::optional< std::string > GetMinValueAsString (sdf::Errors &_errors, const PrintConfig &_config=PrintConfig()) const
Get the minimum allowed value as a string.
ElementPtr GetParentElement () const
Get the parent Element of this Param.
bool GetRequired () const
Return whether the parameter is required.
bool GetSet () const
Return true if the parameter has been set.
const std::string & GetTypeName () const
Get the type name value.
bool IgnoresParentElementAttribute () const
Return true if the parameter ignores the parent element's attributes, or if the parameter has no parent element.
template<typename Type >
bool IsType () const
Return true if the param is a particular type.
Param & operator= (const Param &_param)
Copy assignment operator Note that the updateFunc member will not get copied.
Param & operator= (Param &&_param) noexcept=default
Move assignment operator.
bool Reparse ()
Reparse the parameter value.
bool Reparse (sdf::Errors &_errors)
Reparse the parameter value.
void Reset ()
Reset the parameter to the default value.
template<typename T >
bool Set (const T &_value)
Set the parameter's value.
template<typename T >
bool Set (const T &_value, sdf::Errors &_errors)
Set the parameter's value.
void SetDescription (const std::string &_desc)
Set the description of the parameter.
bool SetFromString (const std::string &_value)
Set the parameter value from a string.
bool SetFromString (const std::string &_value, bool _ignoreParentAttributes)
Set the parameter value from a string.
bool SetFromString (const std::string &_value, bool _ignoreParentAttributes, sdf::Errors &_errors)
Set the parameter value from a string.
bool SetFromString (const std::string &_value, sdf::Errors &_errors)
Set the parameter value from a string.
bool SetParentElement (ElementPtr _parentElement)
Set the parent Element of this Param.
bool SetParentElement (ElementPtr _parentElement, sdf::Errors &_errors)
Set the parent Element of this Param.
template<typename T >
void SetUpdateFunc (T _updateFunc)
Set the update function.
void Update ()
Set the parameter's value using the updateFunc.
void Update (sdf::Errors &_errors)
Set the parameter's value using the updateFunc.
bool ValidateValue () const
Validate the value against minimum and maximum allowed values.
bool ValidateValue (sdf::Errors &_errors) const
Validate the value against minimum and maximum allowed values.
Detailed Description
A parameter class.
Constructor & Destructor Documentation
Param() [1/6]
sdf::SDF_VERSION_NAMESPACE::Param::Param (const std::string & _key, const std::string & _typeName, const std::string & _default, bool _required, const std::string & _description = "")
Constructor.
Parameters
[in] _key Key for the parameter.
[in] _typeName String name for the value type (double, int,...).
[in] _default Default value.
[in] _required True if the parameter is required to be set.
[in] _description Description of the parameter.
Exceptions
sdf::AssertionInternalError if an invalid type is given.
Param() [2/6]
sdf::SDF_VERSION_NAMESPACE::Param::Param (const std::string & _key, const std::string & _typeName, const std::string & _default, bool _required, sdf::Errors & _errors, const std::string & _description = "")
Constructor.
Parameters
[in] _key Key for the parameter.
[in] _typeName String name for the value type (double, int,...).
[in] _default Default value.
[in] _required True if the parameter is required to be set.
[out] _errors Vector of errors.
[in] _description Description of the parameter.
Param() [3/6]
sdf::SDF_VERSION_NAMESPACE::Param::Param (const std::string & _key, const std::string & _typeName, const std::string & _default, bool _required, const std::string & _minValue, const std::string & _maxValue, const std::string & _description = "")
Constructor with min and max values.
Parameters
[in] _key Key for the parameter.
[in] _typeName String name for the value type (double, int,...).
[in] _default Default value.
[in] _required True if the parameter is required to be set.
[in] _minValue Minimum allowed value for the parameter.
[in] _maxValue Maximum allowed value for the parameter.
[in] _description Description of the parameter.
Exceptions
sdf::AssertionInternalError if an invalid type is given.
Param() [4/6]
sdf::SDF_VERSION_NAMESPACE::Param::Param (const std::string & _key, const std::string & _typeName, const std::string & _default, bool _required, const std::string & _minValue, const std::string & _maxValue, sdf::Errors & _errors, const std::string & _description = "")
Constructor with min and max values.
Parameters
[in] _key Key for the parameter.
[in] _typeName String name for the value type (double, int,...).
[in] _default Default value.
[in] _required True if the parameter is required to be set.
[in] _minValue Minimum allowed value for the parameter.
[in] _maxValue Maximum allowed value for the parameter.
[out] _errors Vector of errors.
[in] _description Description of the parameter.
Param() [5/6]
sdf::SDF_VERSION_NAMESPACE::Param::Param (const Param & _param)
Copy constructor Note that the updateFunc member does not get copied.
Parameters
[in] _param Param to copy
Param() [6/6]
sdf::SDF_VERSION_NAMESPACE::Param::Param (Param && _param) default noexcept
Move constructor.
Parameters
[in] _param Param to move from
~Param()
virtual sdf::SDF_VERSION_NAMESPACE::Param::~Param () virtual
Destructor.
Member Function Documentation
Clone()
ParamPtr sdf::SDF_VERSION_NAMESPACE::Param::Clone () const
Clone the parameter.
Returns
A new parameter that is the clone of this.
Get() [1/2]
template<typename T > bool sdf::SDF_VERSION_NAMESPACE::Param::Get (T & _value) const
Get the value of the parameter.
Parameters
[out] _value The value of the parameter.
Returns
True if parameter was successfully cast to the value type passed in.
References sdferr.
Get() [2/2]
template<typename T > bool sdf::SDF_VERSION_NAMESPACE::Param::Get (T & _value, sdf::Errors & _errors) const
Get the value of the parameter.
Parameters
[out] _value The value of the parameter.
[out] _errors Vector of errors.
Returns
True if parameter was successfully cast to the value type passed in.
References GetAsString(), sdf::SDF_VERSION_NAMESPACE::lowercase(), and sdf::SDF_VERSION_NAMESPACE::UNKNOWN_PARAMETER_TYPE.
GetAny() [1/2]
bool sdf::SDF_VERSION_NAMESPACE::Param::GetAny (std::any & _anyVal) const
Get the value of the parameter as a std::any.
Parameters
[out] _anyVal The std::any object to set.
Returns
True if successfully fetched _anyVal, false otherwise.
GetAny() [2/2]
bool sdf::SDF_VERSION_NAMESPACE::Param::GetAny (std::any & _anyVal, sdf::Errors & _errors) const
Get the value of the parameter as a std::any.
Parameters
[out] _anyVal The std::any object to set.
[out] _errors Vector of errors.
Returns
True if successfully fetched _anyVal, false otherwise.
GetAsString() [1/2]
std::string sdf::SDF_VERSION_NAMESPACE::Param::GetAsString (const PrintConfig & _config = PrintConfig()) const
Get the value as a string.
Parameters
[in] _config Configuration for conversion to string.
Returns
String containing the value of the parameter.
Referenced by Get().
GetAsString() [2/2]
std::string sdf::SDF_VERSION_NAMESPACE::Param::GetAsString (sdf::Errors & _errors, const PrintConfig & _config = PrintConfig()) const
Get the value as a string.
Parameters
[out] _errors Vector of errors.
[in] _config Configuration for conversion to string.
Returns
String containing the value of the parameter.
GetDefault() [1/2]
template<typename T > bool sdf::SDF_VERSION_NAMESPACE::Param::GetDefault (T & _value) const
Get the default value of the parameter.
Parameters
[out] _value The default value of the parameter.
Returns
True if parameter was successfully cast to the value type passed in.
References sdferr.
GetDefault() [2/2]
template<typename T > bool sdf::SDF_VERSION_NAMESPACE::Param::GetDefault (T & _value, sdf::Errors & _errors) const
Get the default value of the parameter.
Parameters
[out] _value The default value of the parameter.
[out] _errors Vector of errors.
Returns
True if parameter was successfully cast to the value type passed in.
References sdf::SDF_VERSION_NAMESPACE::PARAMETER_ERROR.
GetDefaultAsString() [1/2]
std::string sdf::SDF_VERSION_NAMESPACE::Param::GetDefaultAsString (const PrintConfig & _config = PrintConfig()) const
Get the default value as a string.
Parameters
[in] _config Configuration for conversion to string.
Returns
String containing the default value of the parameter.
GetDefaultAsString() [2/2]
std::string sdf::SDF_VERSION_NAMESPACE::Param::GetDefaultAsString (sdf::Errors & _errors, const PrintConfig & _config = PrintConfig()) const
Get the default value as a string.
Parameters
[out] _errors Vector of errors.
[in] _config Configuration for conversion to string.
Returns
String containing the default value of the parameter.
GetDescription()
std::string sdf::SDF_VERSION_NAMESPACE::Param::GetDescription () const
Get the description of the parameter.
Returns
The description of the parameter.
GetKey()
const std::string& sdf::SDF_VERSION_NAMESPACE::Param::GetKey () const
Get the key value.
Returns
The key.
GetMaxValueAsString() [1/2]
std::optional<std::string> sdf::SDF_VERSION_NAMESPACE::Param::GetMaxValueAsString (const PrintConfig & _config = PrintConfig()) const
Get the maximum allowed value as a string.
Parameters
[in] _config Configuration for conversion to string.
Returns
Returns a string containing the maximum allowed value of the parameter if the maximum value is specified in the SDFormat description of the parameter. nullopt otherwise.
GetMaxValueAsString() [2/2]
std::optional<std::string> sdf::SDF_VERSION_NAMESPACE::Param::GetMaxValueAsString (sdf::Errors & _errors, const PrintConfig & _config = PrintConfig()) const
Get the maximum allowed value as a string.
Parameters
[in] _config Configuration for conversion to string.
[out] _errors Vector of errors.
Returns
Returns a string containing the maximum allowed value of the parameter if the maximum value is specified in the SDFormat description of the parameter. nullopt otherwise.
GetMinValueAsString() [1/2]
std::optional<std::string> sdf::SDF_VERSION_NAMESPACE::Param::GetMinValueAsString (const PrintConfig & _config = PrintConfig()) const
Get the minimum allowed value as a string.
Parameters
[in] _config Configuration for conversion to string.
Returns
Returns a string containing the minimum allowed value of the parameter if the minimum value is specified in the SDFormat description of the parameter. nullopt otherwise.
GetMinValueAsString() [2/2]
std::optional<std::string> sdf::SDF_VERSION_NAMESPACE::Param::GetMinValueAsString (sdf::Errors & _errors, const PrintConfig & _config = PrintConfig()) const
Get the minimum allowed value as a string.
Parameters
[out] _errors Vector of errors.
[in] _config Configuration for conversion to string.
Returns
Returns a string containing the minimum allowed value of the parameter if the minimum value is specified in the SDFormat description of the parameter. nullopt otherwise.
GetParentElement()
ElementPtr sdf::SDF_VERSION_NAMESPACE::Param::GetParentElement () const
Get the parent Element of this Param.
Returns
Pointer to this Param's parent Element, nullptr if there is no parent Element.
GetRequired()
bool sdf::SDF_VERSION_NAMESPACE::Param::GetRequired () const
Return whether the parameter is required.
Returns
True if the parameter is required.
GetSet()
bool sdf::SDF_VERSION_NAMESPACE::Param::GetSet () const
Return true if the parameter has been set.
Returns
True if the parameter has been set.
GetTypeName()
const std::string& sdf::SDF_VERSION_NAMESPACE::Param::GetTypeName () const
Get the type name value.
Returns
The type name.
IgnoresParentElementAttribute()
bool sdf::SDF_VERSION_NAMESPACE::Param::IgnoresParentElementAttribute () const
Return true if the parameter ignores the parent element's attributes, or if the parameter has no parent element.
Returns
True if the parameter ignores the parent element's attributes, or if the parameter has no parent element.
IsType()
template<typename Type > bool sdf::SDF_VERSION_NAMESPACE::Param::IsType
Return true if the param is a particular type.
Returns
True if the type held by this Param matches the Type template parameter.
operator=() [1/2]
Param& sdf::SDF_VERSION_NAMESPACE::Param::operator= (const Param & _param)
Copy assignment operator Note that the updateFunc member will not get copied.
Parameters
[in] _param The parameter to set values from.
Returns
*This
operator=() [2/2]
Param& sdf::SDF_VERSION_NAMESPACE::Param::operator= (Param && _param) default noexcept
Move assignment operator.
Parameters
[in] _param Param to move from
Returns
Reference to this
Reparse() [1/2]
bool sdf::SDF_VERSION_NAMESPACE::Param::Reparse ()
Reparse the parameter value.
This should be called after the parent element's attributes have been modified, in the event that the value was set using SetFromString or posesses a default value, and that the final parsed value is dependent on the attributes of the parent element. For example, the rotation component of a pose element can be parsed as degrees or radians, depending on the attribute @degrees of the parent element. If however the value was explicitly set using the Set<T> function, reparsing would not change the value.
Returns
True if the parameter value has been reparsed successfully.
See also
bool SetFromString(const std::string &_value)
bool Set(const T &_value)
Reparse() [2/2]
bool sdf::SDF_VERSION_NAMESPACE::Param::Reparse (sdf::Errors & _errors)
Reparse the parameter value.
This should be called after the parent element's attributes have been modified, in the event that the value was set using SetFromString or posesses a default value, and that the final parsed value is dependent on the attributes of the parent element. For example, the rotation component of a pose element can be parsed as degrees or radians, depending on the attribute @degrees of the parent element. If however the value was explicitly set using the Set<T> function, reparsing would not change the value.
Parameters
[out] _errors Vector of errors.
Returns
True if the parameter value has been reparsed successfully.
See also
bool SetFromString(const std::string &_value)
bool Set(const T &_value)
Reset()
void sdf::SDF_VERSION_NAMESPACE::Param::Reset ()
Reset the parameter to the default value.
Set() [1/2]
template<typename T > bool sdf::SDF_VERSION_NAMESPACE::Param::Set (const T & _value)
Set the parameter's value.
The passed in value value must have an input and output stream operator.
Parameters
[in] _value The value to set the parameter to.
Returns
True if the value was successfully set.
References sdferr.
Set() [2/2]
template<typename T > bool sdf::SDF_VERSION_NAMESPACE::Param::Set (const T & _value, sdf::Errors & _errors)
Set the parameter's value.
The passed in value value must have an input and output stream operator.
Parameters
[in] _value The value to set the parameter to.
[out] _errors Vector of errors.
Returns
True if the value was successfully set.
References sdf::SDF_VERSION_NAMESPACE::PARAMETER_ERROR, and SetFromString().
SetDescription()
void sdf::SDF_VERSION_NAMESPACE::Param::SetDescription (const std::string & _desc)
Set the description of the parameter.
Parameters
[in] _desc New description for the parameter.
SetFromString() [1/4]
bool sdf::SDF_VERSION_NAMESPACE::Param::SetFromString (const std::string & _value)
Set the parameter value from a string.
Parameters
[in] _value New value for the parameter in string form.
SetFromString() [2/4]
bool sdf::SDF_VERSION_NAMESPACE::Param::SetFromString (const std::string & _value, bool _ignoreParentAttributes)
Set the parameter value from a string.
Parameters
[in] _value New value for the parameter in string form.
[in] _ignoreParentAttributes Whether to ignore parent element attributes when parsing value from string as well as subsequent reparses.
Referenced by Set().
SetFromString() [3/4]
bool sdf::SDF_VERSION_NAMESPACE::Param::SetFromString (const std::string & _value, bool _ignoreParentAttributes, sdf::Errors & _errors)
Set the parameter value from a string.
Parameters
[in] _value New value for the parameter in string form.
[in] _ignoreParentAttributes Whether to ignore parent element
[out] _errors Vector of errors. attributes when parsing value from string as well as subsequent reparses.
SetFromString() [4/4]
bool sdf::SDF_VERSION_NAMESPACE::Param::SetFromString (const std::string & _value, sdf::Errors & _errors)
Set the parameter value from a string.
Parameters
[in] _value New value for the parameter in string form.
[out] _errors Vector of errors.
SetParentElement() [1/2]
bool sdf::SDF_VERSION_NAMESPACE::Param::SetParentElement (ElementPtr _parentElement)
Set the parent Element of this Param.
Parameters
[in] _parentElement Pointer to new parent Element. A nullptr can be provided to remove the current parent Element.
Returns
True if the parent Element was set and the value was reparsed successfully.
SetParentElement() [2/2]
bool sdf::SDF_VERSION_NAMESPACE::Param::SetParentElement (ElementPtr _parentElement, sdf::Errors & _errors)
Set the parent Element of this Param.
Parameters
[in] _parentElement Pointer to new parent Element. A nullptr can be provided to remove the current parent Element.
[out] _errors Vector of errors.
Returns
True if the parent Element was set and the value was reparsed successfully.
SetUpdateFunc()
template<typename T > void sdf::SDF_VERSION_NAMESPACE::Param::SetUpdateFunc (T _updateFunc)
Set the update function.
The updateFunc will be used to set the parameter's value when Param::Update is called.
Parameters
[in] _updateFunc Function pointer to an update function.
Update() [1/2]
void sdf::SDF_VERSION_NAMESPACE::Param::Update ()
Set the parameter's value using the updateFunc.
See also
Param::SetUpdateFunc
Update() [2/2]
void sdf::SDF_VERSION_NAMESPACE::Param::Update (sdf::Errors & _errors)
Set the parameter's value using the updateFunc.
Parameters
[out] _errors Vector of errors.
See also
Param::SetUpdateFunc
ValidateValue() [1/2]
bool sdf::SDF_VERSION_NAMESPACE::Param::ValidateValue () const
Validate the value against minimum and maximum allowed values.
Returns
True if the value is valid
ValidateValue() [2/2]
bool sdf::SDF_VERSION_NAMESPACE::Param::ValidateValue (sdf::Errors & _errors) const
Validate the value against minimum and maximum allowed values.
Parameters
[out] _errors Vector of errors.
Returns
True if the value is valid
The documentation for this class was generated from the following file:
Param.hh