Gazebo Sim: EntityFeatureMap< PhysicsEntityT, PolicyT, RequiredFeatureList, OptionalFeatureLists > Class Template Reference
Gazebo Sim
API Reference
9.0.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
EntityFeatureMap< PhysicsEntityT, PolicyT, RequiredFeatureList, OptionalFeatureLists > Class Template Reference
#include <EntityFeatureMap.hh>
Public Types
template<typename T >
using HasFeatureList = std::disjunction< std::is_same< T, OptionalFeatureLists >... >
Checks whether type T is in the OptionalFeatureLists.
template<typename T >
using PhysicsEntityPtr = physics::EntityPtr< PhysicsEntityT< PolicyT, T > >
Template that's preset with the class's Policy type.
using RequiredEntityPtr = PhysicsEntityPtr< RequiredFeatureList >
A EntityPtr with made from RequiredFeatureList.
Public Member Functions
void AddEntity (const Entity &_entity, const RequiredEntityPtr &_physicsEntity)
Add a mapping between gazebo and physics entities.
template<typename ToFeatureList >
PhysicsEntityPtr< ToFeatureList > EntityCast (const RequiredEntityPtr &_physicsEntity) const
Helper function to cast from an entity type with minimum features to an entity with a different set of features. This overload takes a physics entity as input.
template<typename ToFeatureList >
PhysicsEntityPtr< ToFeatureList > EntityCast (sim::Entity _entity) const
Helper function to cast from an entity type with minimum features to an entity with a different set of features. When the entity is cast successfully, it is added to an internal cache so that subsequent casts will use the entity from the cache.
RequiredEntityPtr Get (const Entity &_entity) const
Get the physics entity with required features that corresponds to the input Gazebo entity.
Entity Get (const RequiredEntityPtr &_physEntity) const
Get Gazebo entity that corresponds to the physics entity with required features.
Entity GetByPhysicsId (std::size_t _id) const
Get Gazebo entity that corresponds to the physics entity ID.
RequiredEntityPtr GetPhysicsEntityPtr (std::size_t _id) const
Get the physics entity with required features that has a particular ID.
bool HasEntity (const Entity &_entity) const
Check whether there is a physics entity associated with the given Gazebo entity.
bool HasEntity (const RequiredEntityPtr &_physicsEntity) const
Check whether there is a gazebo entity associated with the given physics entity.
const std::unordered_map< Entity, RequiredEntityPtr > & Map () const
Get the map from Gazebo entity to physics entities with required features.
bool Remove (const RequiredEntityPtr &_physicsEntity)
Remove physics entity from all associated maps.
bool Remove (Entity _entity)
Remove entity from all associated maps.
std::size_t TotalMapEntryCount () const
Get the total number of entries in the maps. Only used for testing.
Member Typedef Documentation
HasFeatureList
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> template<typename T > using HasFeatureList = std::disjunction<std::is_same<T, OptionalFeatureLists>...>
Checks whether type T is in the OptionalFeatureLists.
Template Parameters
T A FeatureList to search for in OptionalFeatureLists
PhysicsEntityPtr
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> template<typename T > using PhysicsEntityPtr = physics::EntityPtr<PhysicsEntityT<PolicyT, T> >
Template that's preset with the class's Policy type.
Template Parameters
T A FeatureList that is used in creating an EntityPtr
RequiredEntityPtr
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> using RequiredEntityPtr = PhysicsEntityPtr<RequiredFeatureList>
A EntityPtr with made from RequiredFeatureList.
Member Function Documentation
AddEntity()
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> void AddEntity (const Entity & _entity, const RequiredEntityPtr & _physicsEntity) inline
Add a mapping between gazebo and physics entities.
Parameters
[in] _entity Gazebo entity.
[in] _physicsEntity Physics entity with required feature
EntityCast() [1/2]
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> template<typename ToFeatureList > PhysicsEntityPtr< ToFeatureList > EntityCast (const RequiredEntityPtr & _physicsEntity) const inline
Helper function to cast from an entity type with minimum features to an entity with a different set of features. This overload takes a physics entity as input.
Template Parameters
ToFeatureList The list of features of the resulting entity.
Parameters
[in] _physicsEntity Physics entity with required features.
Returns
Physics entity with features in ToFeatureList. nullptr if the entity can't be found or the physics engine doesn't support the requested feature.
References EntityFeatureMap< PhysicsEntityT, PolicyT, RequiredFeatureList, OptionalFeatureLists >::Get(), and gz::sim::kNullEntity.
EntityCast() [2/2]
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> template<typename ToFeatureList > PhysicsEntityPtr< ToFeatureList > EntityCast (sim::Entity _entity) const inline
Helper function to cast from an entity type with minimum features to an entity with a different set of features. When the entity is cast successfully, it is added to an internal cache so that subsequent casts will use the entity from the cache.
Template Parameters
ToFeatureList The list of features of the resulting entity.
Parameters
[in] _entity Gazebo entity.
Returns
Physics entity with features in ToFeatureList. nullptr if the entity can't be found or the physics engine doesn't support the requested feature.
References RequestFeatures< typename ToFeatureList >::From(), and EntityFeatureMap< PhysicsEntityT, PolicyT, RequiredFeatureList, OptionalFeatureLists >::Get().
Get() [1/2]
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> RequiredEntityPtr Get (const Entity & _entity) const inline
Get the physics entity with required features that corresponds to the input Gazebo entity.
Parameters
[in] _entity Gazebo entity.
Returns
If found, returns the corresponding physics entity. Otherwise, nullptr
Referenced by EntityFeatureMap< PhysicsEntityT, PolicyT, RequiredFeatureList, OptionalFeatureLists >::EntityCast(), and EntityFeatureMap< PhysicsEntityT, PolicyT, RequiredFeatureList, OptionalFeatureLists >::EntityCast().
Get() [2/2]
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> Entity Get (const RequiredEntityPtr & _physEntity) const inline
Get Gazebo entity that corresponds to the physics entity with required features.
Parameters
[in] _physEntity Physics entity with required features
Returns
If found, returns the corresponding Gazebo entity. Otherwise, kNullEntity
References gz::sim::kNullEntity.
GetByPhysicsId()
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> Entity GetByPhysicsId (std::size_t _id) const inline
Get Gazebo entity that corresponds to the physics entity ID.
Parameters
[in] _id Physics entity ID
Returns
If found, returns the corresponding Gazebo entity. Otherwise, kNullEntity
References unordered_map< K, T >::end(), unordered_map< K, T >::find(), and gz::sim::kNullEntity.
GetPhysicsEntityPtr()
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> RequiredEntityPtr GetPhysicsEntityPtr (std::size_t _id) const inline
Get the physics entity with required features that has a particular ID.
Parameters
[in] _id The ID of the desired physics entity
Returns
If found, returns the corresponding physics entity. Otherwise, nullptr
HasEntity() [1/2]
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> bool HasEntity (const Entity & _entity) const inline
Check whether there is a physics entity associated with the given Gazebo entity.
Parameters
[in] _entity Gazebo entity.
Returns
True if the there is a physics entity associated with the given Gazebo entity
HasEntity() [2/2]
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> bool HasEntity (const RequiredEntityPtr & _physicsEntity) const inline
Check whether there is a gazebo entity associated with the given physics entity.
Parameters
[in] _physicsEntity physics entity with required features.
Returns
True if the there is a gazebo entity associated with the given physics entity
Map()
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> const std::unordered_map< Entity, RequiredEntityPtr > & Map () const inline
Get the map from Gazebo entity to physics entities with required features.
Returns
Immumtable entity map
Remove() [1/2]
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> bool Remove (const RequiredEntityPtr & _physicsEntity) inline
Remove physics entity from all associated maps.
Parameters
[in] _physicsEntity Physics entity.
Returns
True if the entity was found and removed.
References unordered_map< K, T >::erase().
Remove() [2/2]
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> bool Remove (Entity _entity) inline
Remove entity from all associated maps.
Parameters
[in] _entity Gazebo entity.
Returns
True if the entity was found and removed.
References unordered_map< K, T >::erase().
TotalMapEntryCount()
template<template< typename, typename > class PhysicsEntityT, typename PolicyT , typename RequiredFeatureList , typename... OptionalFeatureLists> std::size_t TotalMapEntryCount () const inline
Get the total number of entries in the maps. Only used for testing.
Returns
Number of entries in all the maps.
References unordered_map< K, T >::size().
The documentation for this class was generated from the following file:
EntityFeatureMap.hh