Gazebo Transport: TopicStorage< T > Class Template Reference
Gazebo Transport
API Reference
11.4.1
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
TopicStorage< T > Class Template Reference
Store address information about topics and provide convenient methods for adding new topics, removing them, etc.
#include <ignition/transport/TopicStorage.hh>
Public Member Functions
TopicStorage ()=default
Constructor.
virtual ~TopicStorage ()=default
Destructor.
bool AddPublisher (const T &_publisher)
Add a new address associated to a given topic and node UUID.
bool DelPublisherByNode (const std::string &_topic, const std::string &_pUuid, const std::string &_nUuid)
Remove a publisher associated to a given topic and UUID pair.
bool DelPublishersByProc (const std::string &_pUuid)
Remove all the publishers associated to a given process.
bool HasAnyPublishers (const std::string &_topic, const std::string &_pUuid) const
Return if there is any publisher stored for the given topic and process UUID.
bool HasPublisher (const std::string &_addr) const
Return if the requested publisher's address is stored.
bool HasTopic (const std::string &_topic) const
Return if there is any publisher stored for the given topic.
bool HasTopic (const std::string &_topic, const std::string &_type) const
Return if there is any publisher stored for the given topic and type.
void Print () const
Print all the information for debugging purposes.
bool Publisher (const std::string &_topic, const std::string &_pUuid, const std::string &_nUuid, T &_publisher) const
Get the address information for a given topic and node UUID.
bool Publishers (const std::string &_topic, std::map< std::string, std::vector< T >> &_info) const
Get the map of publishers stored for a given topic.
void PublishersByNode (const std::string &_pUuid, const std::string &_nUuid, std::vector< T > &_pubs) const
Given a process UUID and the node UUID, the function returns the list of publishers contained in the node.
void PublishersByProc (const std::string &_pUuid, std::map< std::string, std::vector< T >> &_pubs) const
Given a process UUID, the function returns the list of publishers contained in this process UUID with its address information.
void TopicList (std::vector< std::string > &_topics) const
Get the list of topics currently stored.
Detailed Description
template<typename T>
class ignition::transport::TopicStorage< T >
Store address information about topics and provide convenient methods for adding new topics, removing them, etc.
Constructor & Destructor Documentation
TopicStorage()
TopicStorage () default
Constructor.
~TopicStorage()
virtual ~TopicStorage () virtual default
Destructor.
Member Function Documentation
AddPublisher()
bool AddPublisher (const T & _publisher) inline
Add a new address associated to a given topic and node UUID.
Parameters
[in] _publisher New publisher.
Returns
true if the new entry is added or false if not (because it was already stored).
Referenced by Discovery< Pub >::Advertise().
DelPublisherByNode()
bool DelPublisherByNode (const std::string & _topic, const std::string & _pUuid, const std::string & _nUuid) inline
Remove a publisher associated to a given topic and UUID pair.
Parameters
[in] _topic Topic name
[in] _pUuid Process UUID of the publisher.
[in] _nUuid Node UUID of the publisher.
Returns
True when the publisher was removed or false otherwise.
Referenced by Discovery< Pub >::Unadvertise().
DelPublishersByProc()
bool DelPublishersByProc (const std::string & _pUuid) inline
Remove all the publishers associated to a given process.
Parameters
[in] _pUuid Process' UUID of the publisher.
Returns
True when at least one address was removed or false otherwise.
HasAnyPublishers()
bool HasAnyPublishers (const std::string & _topic, const std::string & _pUuid) const inline
Return if there is any publisher stored for the given topic and process UUID.
Parameters
[in] _topic Topic name.
[in] _pUuid Process UUID of the publisher.
Returns
True if there is at least one address stored for the topic and process UUID.
HasPublisher()
bool HasPublisher (const std::string & _addr) const inline
Return if the requested publisher's address is stored.
Parameters
[in] _addr Publisher's address requested
Returns
true if the publisher's address is stored.
HasTopic() [1/2]
bool HasTopic (const std::string & _topic) const inline
Return if there is any publisher stored for the given topic.
Parameters
[in] _topic Topic name.
Returns
True if there is at least one entry stored for the topic.
Referenced by TopicStorage< ignition::transport::MessagePublisher >::HasAnyPublishers(), TopicStorage< ignition::transport::MessagePublisher >::HasTopic(), and TopicStorage< ignition::transport::MessagePublisher >::Publishers().
HasTopic() [2/2]
bool HasTopic (const std::string & _topic, const std::string & _type) const inline
Return if there is any publisher stored for the given topic and type.
Parameters
[in] _topic Topic name.
[in] _type Topic type.
Returns
True if there is at least one entry stored for the topic and type.
Print()
void Print () const inline
Print all the information for debugging purposes.
Referenced by Discovery< Pub >::PrintCurrentState().
Publisher()
bool Publisher (const std::string & _topic, const std::string & _pUuid, const std::string & _nUuid, T & _publisher) const inline
Get the address information for a given topic and node UUID.
Parameters
[in] _topic Topic name.
[in] _pUuid Process UUID of the publisher.
[in] _nUuid Node UUID of the publisher.
[out] _publisher Publisher's information requested.
Returns
true if a publisher is found for the given topic and UUID pair
Referenced by Discovery< Pub >::Unadvertise().
Publishers()
bool Publishers (const std::string & _topic, std::map< std::string, std::vector< T >> & _info) const inline
Get the map of publishers stored for a given topic.
Parameters
[in] _topic Topic name.
[out] _info Map of publishers requested.
Returns
true if at least there is one publisher stored.
Referenced by Discovery< Pub >::Discover(), and Discovery< Pub >::Publishers().
PublishersByNode()
void PublishersByNode (const std::string & _pUuid, const std::string & _nUuid, std::vector< T > & _pubs) const inline
Given a process UUID and the node UUID, the function returns the list of publishers contained in the node.
Parameters
[in] _pUuid Process UUID.
[in] _nUuid Node UUID.
[out] _pubs Vector of publishers.
PublishersByProc()
void PublishersByProc (const std::string & _pUuid, std::map< std::string, std::vector< T >> & _pubs) const inline
Given a process UUID, the function returns the list of publishers contained in this process UUID with its address information.
Parameters
[in] _pUuid Process UUID.
[out] _pubs Map of publishers where the keys are the node UUIDs and the value is its address information.
TopicList()
void TopicList (std::vector< std::string > & _topics) const inline
Get the list of topics currently stored.
Parameters
[out] _topics List of stored topics.
Referenced by Discovery< Pub >::TopicList().
The documentation for this class was generated from the following file:
gz/transport/TopicStorage.hh