Gazebo Rendering: BaseGizmoVisual< T > Class Template Reference
Gazebo Rendering
API Reference
9.0.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
BaseGizmoVisual< T > Class Template Reference
A base implementation of the GizmoVisual class.
#include <BaseGizmoVisual.hh>
Public Member Functions
virtual ~BaseGizmoVisual ()
Destructor.
virtual math::Vector3d ActiveAxis () const override
Get the current active axis.
virtual TransformAxis AxisById (unsigned int _id) const override
Get the Transform axis associated with the given id.
virtual VisualPtr ChildByAxis (unsigned int _axis) const override
Get the child visual by axis.
virtual void Init () override
virtual void LookAt (const math::Vector3d &_pos, const math::Quaterniond &_rot) override
Update the Gizmo visual's rotation visuals to face the specified position.
virtual TransformMode Mode () const override
Get the current transform mode.
virtual void PreRender () override
Prepare this object and any of its children for rendering. This should be called for each object in a scene just before rendering, which can be achieved by a single call to Scene::PreRender.
virtual void Reset ()
Reset the gizmo visual state.
virtual void SetActiveAxis (const math::Vector3d &_axis) override
Set the active axis in the gizmo visual.
virtual void SetTransformMode (TransformMode _mode) override
Set the transform mode of the gizmo. This controls the visual appearance of the gizmo. Only the visuals in the specified mode will be visible, e.g. if set to TM_TRANSLATION mode, then only the translation axis visuals will be visible.
Public Member Functions inherited from GizmoVisual
virtual ~GizmoVisual ()
Destructor.
Public Member Functions inherited from CompositeVisual
virtual ~CompositeVisual ()
Destructor.
Public Member Functions inherited from Visual
virtual ~Visual ()
Destructor.
virtual void AddGeometry (GeometryPtr _geometry)=0
Add the given geometry to this visual. If the given node is already attached, no work will be done.
virtual void AddVisibilityFlags (uint32_t _flags)=0
Add visibility flags.
virtual gz::math::AxisAlignedBox BoundingBox () const =0
Get the bounding box in world frame coordinates.
virtual VisualPtr Clone (const std::string &_name, NodePtr _newParent) const =0
Clone the visual (and its children) with a new name.
virtual GeometryPtr GeometryByIndex (unsigned int _index) const =0
Get geometry at given index. If no geometry exists at given index, NULL will be returned.
virtual unsigned int GeometryCount () const =0
Get the number of geometries attached to this visual.
virtual bool HasGeometry (ConstGeometryPtr _geometry) const =0
Determine if given geometry is attached to this visual.
virtual gz::math::AxisAlignedBox LocalBoundingBox () const =0
Get the local bounding box of the visual.
virtual MaterialPtr Material () const =0
Get the material assigned to attached visuals and geometries.
virtual void RemoveGeometries ()=0
Remove all attached geometries from this visual.
virtual GeometryPtr RemoveGeometry (GeometryPtr _geometry)=0
Remove the given geometry from this visual. If the given node is not a child of this visual, no work will be done.
virtual GeometryPtr RemoveGeometryByIndex (unsigned int _index)=0
Remove the geometry at the given index from this visual. If the specified node is not attached this visual, no work will be done.
virtual void RemoveVisibilityFlags (uint32_t _flags)=0
Remove visibility flags.
virtual void SetChildMaterial (MaterialPtr _material, bool _unique=true)=0
Set the material for all attached visuals only.
virtual void SetGeometryMaterial (MaterialPtr _material, bool _unique=true)=0
Set the material for all attached geometries only.
virtual void SetMaterial (const std::string &_name, bool _unique=true)=0
Set the material for all attached visuals and geometries. The specified material will be retrieved from Scene::Material using the given material name. If no material is registered with the given name, no work will be done.
virtual void SetMaterial (MaterialPtr _material, bool _unique=true)=0
Set the material for all attached visuals and geometries.
virtual void SetStatic (bool _static)=0
Tells Render Engine this Visual will be static (i.e. won't move, rotate or scale) You can still move, rotate or scale the Visual; however doing so has a performance impact. How much of an impact will depend on the rendering backend being used.
virtual void SetVisibilityFlags (uint32_t _flags)=0
Set visibility flags.
virtual void SetVisible (bool _visible)=0
Specify if this visual is visible.
virtual void SetWireframe (bool _show)=0
Enable or disable wireframe.
virtual bool Static () const =0
Get whether the visual is static.
virtual uint32_t VisibilityFlags () const =0
Get visibility flags.
virtual bool Wireframe () const =0
Get whether wireframe is enabled for this visual.
Public Member Functions inherited from Node
virtual ~Node ()
Destructor.
virtual void AddChild (NodePtr _child)=0
Add the given node to this node. If the given node is already a child, no work will be done.
virtual NodePtr ChildById (unsigned int _id) const =0
Get node with given ID. If no child exists with given ID, NULL will be returned.
virtual NodePtr ChildByIndex (unsigned int _index) const =0
Get node at given index. If no child exists at given index, NULL will be returned.
virtual NodePtr ChildByName (const std::string &_name) const =0
Get node with given name. If no child exists with given name, NULL will be returned.
virtual unsigned int ChildCount () const =0
Get number of child nodes.
virtual bool HasChild (ConstNodePtr _child) const =0
Determine if given node is an attached child.
virtual bool HasChildId (unsigned int _id) const =0
Determine if node with given ID is an attached child.
virtual bool HasChildName (const std::string &_name) const =0
Determine if node with given name is an attached child.
virtual bool HasParent () const =0
Determine if this Node is attached to another Node.
virtual bool HasUserData (const std::string &_key) const =0
Check if node has custom data.
virtual bool InheritScale () const =0
Determine if this node inherits scale from this parent.
virtual math::Pose3d InitialLocalPose () const =0
Get the initial local pose.
virtual math::Pose3d LocalPose () const =0
Get the local pose.
virtual math::Vector3d LocalPosition () const =0
Get the local position.
virtual math::Quaterniond LocalRotation () const =0
Get the local rotation.
virtual math::Vector3d LocalScale () const =0
Get the local scale.
virtual math::Vector3d Origin () const =0
Get position of origin.
virtual NodePtr Parent () const =0
Get the parent Node.
virtual NodePtr RemoveChild (NodePtr _child)=0
Remove (detach) the given node from this node. If the given node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildById (unsigned int _id)=0
Remove (detach) the node with the given ID from this node. If the specified node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildByIndex (unsigned int _index)=0
Remove (detach) the node at the given index from this node. If the specified node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildByName (const std::string &_name)=0
Remove (detach) the node with the given name from this node. If the specified node is not a child of this node, no work will be done.
virtual void RemoveChildren ()=0
Remove all child nodes from this node This detaches all the child nodes but does not destroy them.
virtual void RemoveParent ()=0
Detach this Node from its parent. If this Node does not have a parent, no work will be done.
virtual void Scale (const math::Vector3d &_scale)=0
Scale the current scale by the given scalars.
virtual void Scale (double _scale)=0
Scale the current scale by the given scalar. The given scalar will be assigned to the x, y, and z coordinates.
virtual void Scale (double _x, double _y, double _z)=0
Scale the current scale by the given scalars.
virtual void SetInheritScale (bool _inherit)=0
Specify if this node inherits scale from its parent.
virtual void SetLocalPose (const math::Pose3d &_pose)=0
Set the local pose.
virtual void SetLocalPosition (const math::Vector3d &_position)=0
Set the local position.
virtual void SetLocalPosition (double _x, double _y, double _z)=0
Set the local position.
virtual void SetLocalRotation (const math::Quaterniond &_rotation)=0
Set the local rotation.
virtual void SetLocalRotation (double _r, double _p, double _y)=0
Set the local rotation.
virtual void SetLocalRotation (double _w, double _x, double _y, double _z)=0
Set the local rotation.
virtual void SetLocalScale (const math::Vector3d &_scale)=0
Set the local scale.
virtual void SetLocalScale (double _scale)=0
Set the local scale. The given scale will be assigned to the x, y, and z coordinates.
virtual void SetLocalScale (double _x, double _y, double _z)=0
Set the local scale.
virtual void SetOrigin (const math::Vector3d &_origin)=0
Set position of origin. The position should be relative to the original origin of the geometry.
virtual void SetOrigin (double _x, double _y, double _z)=0
Set position of origin. The position should be relative to the original origin of the geometry.
virtual void SetUserData (const std::string &_key, Variant _value)=0
Store any custom data associated with this node.
virtual void SetWorldPose (const math::Pose3d &_pose)=0
Set the world pose.
virtual void SetWorldPosition (const math::Vector3d &_position)=0
Set the world position.
virtual void SetWorldPosition (double _x, double _y, double _z)=0
Set the world position.
virtual void SetWorldRotation (const math::Quaterniond &_rotation)=0
Set the world rotation.
virtual void SetWorldRotation (double _r, double _p, double _y)=0
Set the world rotation.
virtual void SetWorldRotation (double _w, double _x, double _y, double _z)=0
Set the world rotation.
virtual void SetWorldScale (const math::Vector3d &_scale)=0
Set the world scale.
virtual void SetWorldScale (double _scale)=0
Set the world scale. The given scale will be assigned to the x, y, and z coordinates.
virtual void SetWorldScale (double _x, double _y, double _z)=0
Set the world scale.
virtual Variant UserData (const std::string &_key) const =0
Get custom data stored in this node.
virtual math::Pose3d WorldPose () const =0
Get the world pose.
virtual math::Vector3d WorldPosition () const =0
Get the world position.
virtual math::Quaterniond WorldRotation () const =0
Get the world rotation.
virtual math::Vector3d WorldScale () const =0
Get the world scale.
virtual math::Pose3d WorldToLocal (const math::Pose3d &_pose) const =0
Convert given world pose to local pose.
Public Member Functions inherited from Object
virtual ~Object ()
Destructor.
virtual void Destroy ()=0
Destroy any resources associated with this object. Invoking any other functions after destroying an object will result in undefined behavior.
virtual unsigned int Id () const =0
Get the object ID. This ID will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
virtual std::string Name () const =0
Get the object name. This name will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
virtual void PostRender ()=0
Post process this object and any of its children after rendering.
virtual ScenePtr Scene () const =0
Get the Scene that created this object.
Protected Types
enum AxisMaterial {
AM_X , AM_Y , AM_Z , AM_ACTIVE ,
AM_O , AM_HANDLE
}
Material used by axes.
Protected Member Functions
BaseGizmoVisual ()
Constructor.
void CreateMaterials ()
Create materials used by the gizmo visual.
void CreateRotationVisual ()
Create gizmo visual for rotation.
void CreateScaleVisual ()
Create gizmo visual for scale.
void CreateTranslationVisual ()
Create gizmo visual for translation.
Protected Attributes
VisualPtr activeVis
Currently active visual.
math::Vector3d axis = math::Vector3d::Zero
Active axis.
std::map< unsigned int, VisualPtr > handles
A map of gizmo axis and their handle visuals.
std::map< unsigned int, MaterialPtr > materials
A map of axis enums to materials.
TransformMode mode = TransformMode::TM_NONE
Current gizmo mode.
bool modeDirty = false
Flag to indicate the mode has changed.
std::map< unsigned int, VisualPtr > visuals
A map of gizmo axis and their visuals.
Detailed Description
template<class T>
class gz::rendering::BaseGizmoVisual< T >
A base implementation of the GizmoVisual class.
Member Enumeration Documentation
AxisMaterial
template<class T > enum AxisMaterial protected
Material used by axes.
Enumerator
AM_X
X axis.
AM_Y
Y axis.
AM_Z
Z axis.
AM_ACTIVE
Active axis.
AM_O
Origin.
AM_HANDLE
handle
Constructor & Destructor Documentation
BaseGizmoVisual()
template<class T > BaseGizmoVisual () protected
Constructor.
~BaseGizmoVisual()
template<class T > ~BaseGizmoVisual () virtual
Destructor.
Member Function Documentation
ActiveAxis()
template<class T > math::Vector3d ActiveAxis () const override virtual
Get the current active axis.
Returns
Active axis
See also
SetActiveAxis
Implements GizmoVisual.
AxisById()
template<class T > TransformAxis AxisById (unsigned int _id) const override virtual
Get the Transform axis associated with the given id.
Parameters
[in] _id Id of the visual associated with a transform axis
Returns
Transform axis with the given id
Implements GizmoVisual.
References gz::rendering::TA_NONE.
ChildByAxis()
template<class T > VisualPtr ChildByAxis (unsigned int _axis) const override virtual
Get the child visual by axis.
Returns
Visual representing the specified transform axis or transform mode
See also
TransformAxis, TransformMode
Implements GizmoVisual.
CreateMaterials()
template<class T > void CreateMaterials () protected
Create materials used by the gizmo visual.
References Scene::CreateMaterial(), and Scene::Material().
CreateRotationVisual()
template<class T > void CreateRotationVisual () protected
Create gizmo visual for rotation.
References MeshManager::CreateTube(), Scene::CreateVisual(), GZ_PI, MeshManager::HasMesh(), MeshManager::Instance(), gz::rendering::TA_ROTATION_X, gz::rendering::TA_ROTATION_Y, and gz::rendering::TA_ROTATION_Z.
CreateScaleVisual()
template<class T > void CreateScaleVisual () protected
Create gizmo visual for scale.
References Scene::CreateVisual(), GZ_PI, gz::rendering::TA_SCALE_X, gz::rendering::TA_SCALE_Y, and gz::rendering::TA_SCALE_Z.
CreateTranslationVisual()
template<class T > void CreateTranslationVisual () protected
Create gizmo visual for translation.
References Scene::CreateVisual(), GZ_PI, gz::rendering::TA_TRANSLATION_X, gz::rendering::TA_TRANSLATION_Y, and gz::rendering::TA_TRANSLATION_Z.
Init()
template<class T > void Init () override virtual
LookAt()
template<class T > void LookAt (const math::Vector3d & _pos, const math::Quaterniond & _rot) override virtual
Update the Gizmo visual's rotation visuals to face the specified position.
Parameters
[in] _pos Position to face. One typical position to face is the eye (camera) position so that the rotation visuals are rendered in a pose that is not behind the object the Gizmo visual is attached to.
[in] _rot Rotation to be applied. For local space rotation, set this to the rotation of the object that the Gizmo visual is attached to so that the rotation visuals are rotated to match the object's rotation. For world space rotation, set this to identity quarternion for rotation visuals to be rendered in a pose that the rotation visuals are aligned with the world axes.
Implements GizmoVisual.
References GZ_PI, Matrix4< typename T >::LookAt(), Vector3< typename T >::Normalize(), Quaternion< typename T >::RotateVectorReverse(), Matrix4< typename T >::Rotation(), gz::rendering::TA_ROTATION_X, gz::rendering::TA_ROTATION_Y, gz::rendering::TA_ROTATION_Z, Vector3< typename T >::X(), Vector3< typename T >::Y(), and Vector3< typename T >::Z().
Mode()
template<class T > TransformMode Mode () const override virtual
Get the current transform mode.
Returns
Transform mode
See also
SetTransformMode
Implements GizmoVisual.
PreRender()
template<class T > void PreRender () override virtual
Prepare this object and any of its children for rendering. This should be called for each object in a scene just before rendering, which can be achieved by a single call to Scene::PreRender.
Implements Object.
References gz::rendering::TA_ROTATION_X, gz::rendering::TA_ROTATION_Y, gz::rendering::TA_ROTATION_Z, gz::rendering::TA_SCALE_X, gz::rendering::TA_SCALE_Y, gz::rendering::TA_SCALE_Z, gz::rendering::TA_TRANSLATION_X, gz::rendering::TA_TRANSLATION_Y, gz::rendering::TA_TRANSLATION_Z, gz::rendering::TM_NONE, gz::rendering::TM_ROTATION, gz::rendering::TM_SCALE, and gz::rendering::TM_TRANSLATION.
Reset()
template<class T > void Reset () virtual
Reset the gizmo visual state.
References gz::rendering::TA_ROTATION_X, gz::rendering::TA_ROTATION_Y, gz::rendering::TA_ROTATION_Z, gz::rendering::TA_SCALE_X, gz::rendering::TA_SCALE_Y, gz::rendering::TA_SCALE_Z, gz::rendering::TA_TRANSLATION_X, gz::rendering::TA_TRANSLATION_Y, and gz::rendering::TA_TRANSLATION_Z.
SetActiveAxis()
template<class T > void SetActiveAxis (const math::Vector3d & _axis) override virtual
Set the active axis in the gizmo visual.
Parameters
[in] _axis Axis to be set active
Implements GizmoVisual.
SetTransformMode()
template<class T > void SetTransformMode (TransformMode _mode) override virtual
Set the transform mode of the gizmo. This controls the visual appearance of the gizmo. Only the visuals in the specified mode will be visible, e.g. if set to TM_TRANSLATION mode, then only the translation axis visuals will be visible.
Parameters
[in] _mode Transform mode to set the gizmo to
See also
GizmoMode
Implements GizmoVisual.
References Vector3< typename T >::Zero.
Member Data Documentation
activeVis
template<class T > VisualPtr activeVis protected
Currently active visual.
axis
template<class T > math::Vector3d axis = math::Vector3d::Zero protected
Active axis.
handles
template<class T > std::map<unsigned int, VisualPtr> handles protected
A map of gizmo axis and their handle visuals.
materials
template<class T > std::map<unsigned int, MaterialPtr> materials protected
A map of axis enums to materials.
mode
template<class T > TransformMode mode = TransformMode::TM_NONE protected
Current gizmo mode.
modeDirty
template<class T > bool modeDirty = false protected
Flag to indicate the mode has changed.
visuals
template<class T > std::map<unsigned int, VisualPtr> visuals protected
A map of gizmo axis and their visuals.
The documentation for this class was generated from the following file:
BaseGizmoVisual.hh