Gazebo Rendering: BaseCamera< T > Class Template Reference
Gazebo Rendering
API Reference
9.0.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
BaseCamera< T > Class Template Reference abstract
#include <BaseCamera.hh>
Public Member Functions
virtual ~BaseCamera ()
virtual void AddRenderPass (const RenderPassPtr &_pass) override
Add a render pass to the camera.
virtual unsigned int AntiAliasing () const override
Get the level of anti-aliasing used during rendering.
virtual double AspectRatio () const override
Get the camera's aspect ratio.
virtual void Capture (Image &_image) override
Renders a new frame and writes the results to the given image. This is a convenience function for single-camera scenes. It wraps the pre-render, render, post-render, and get-image calls into a single function. This should NOT be used in applications with multiple cameras or multiple consumers of a single camera's images.
virtual common::ConnectionPtr ConnectNewImageFrame (Camera::NewFrameListener _listener) override
Subscribes a new listener to this camera's new frame event.
virtual void Copy (Image &_image) const override
Writes the last rendered image to the given image buffer. This function can be called multiple times after PostRender has been called, without rendering the scene again. Calling this function before a single image has been rendered will have undefined behavior.
virtual Image CreateImage () const override
Created an empty image buffer for capturing images. The resulting image will have sufficient memory allocated for subsequent calls to this camera's Capture function. However, any changes to this cameras properties may invalidate the condition.
virtual RenderWindowPtr CreateRenderWindow () override
Create a render window.
virtual double FarClipPlane () const override
Get the camera's far clipping plane distance.
virtual math::Vector3d FollowOffset () const override
Get the follow offset vector in the frame specified at the time the follow target is set.
virtual double FollowPGain () const override
Get the camera follow movement P gain.
virtual NodePtr FollowTarget () const override
Get the target node being followed.
virtual math::Angle HFOV () const override
Get the camera's horizontal field-of-view.
virtual PixelFormat ImageFormat () const override
Get the image pixel format. If the image pixel format has not been set with a valid value, PF_UNKNOWN will be returned.
virtual unsigned int ImageHeight () const override
Get the image height in pixels.
virtual unsigned int ImageMemorySize () const override
Get the total image memory size in bytes.
virtual unsigned int ImageWidth () const override
Get the image width in pixels.
virtual double NearClipPlane () const override
Get the camera's near clipping plane distance.
virtual void PostRender () override
Preforms any necessary final rendering work. Once rendering is complete the camera will alert any listeners of the new frame event. This function should only be called after a call to Render has successfully been executed.
virtual void PrepareForExternalSampling () override
Right now this is Vulkan-only. This function needs to be called after rendering, and before handling the texture pointer (i.e. by calling RenderTextureMetalId()) so that external APIs (e.g. Qt) can sample the texture.
virtual void PreRender () override
Prepare this object and any of its children for rendering. This should be called for each object in a scene just before rendering, which can be achieved by a single call to Scene::PreRender.
virtual math::Vector2i Project (const math::Vector3d &_pt) const override
Project point in 3d world space to 2d screen space.
virtual math::Matrix4d ProjectionMatrix () const override
Get the projection matrix for this camera.
virtual CameraProjectionType ProjectionType () const override
Get the projection type for this camera.
void RemoveAllRenderPasses () override
Remove all render passes from the camera.
virtual void RemoveRenderPass (const RenderPassPtr &_pass) override
Remove a render pass from the camera.
virtual RenderPassPtr RenderPassByIndex (unsigned int _index) const override
Get a render passes by index.
virtual unsigned int RenderPassCount () const override
Get the number of render passes applied to the camera.
virtual unsigned int RenderTextureGLId () const override
Get the OpenGL texture id associated with the render texture used by this camera. A valid id is returned only if the underlying render engine is OpenGL based.
virtual void RenderTextureMetalId (void *_textureIdPtr) const override
Get the Metal texture id associated with the render texture used by this camera. A valid Id is obtained only if the underlying render engine is Metal based. The pointer set by this function must be released to an id<MTLTexture> using CFBridgingRelease.
virtual bool SaveFrame (const std::string &_name) override
Writes the previously rendered frame to a file. This function can be called multiple times after PostRender has been called, without rendering the scene again. Calling this function before a single image has been rendered will have undefined behavior.
virtual void SetAntiAliasing (const unsigned int _aa) override
Set the level of anti-aliasing used during rendering. If a value of 0 is given, no anti-aliasing will be performed. Higher values can significantly slow-down rendering times, depending on the underlying render engine.
virtual void SetAspectRatio (const double _ratio) override
Set the camera's aspect ratio. This value determines the cameras vertical field-of-view. It is often the.
virtual void SetFarClipPlane (const double _far) override
Set the camera's far clipping plane distance.
virtual void SetFollowOffset (const math::Vector3d &_offset) override
Set offset of camera from target node being followed. The offset will be in the frame that is specified at the time the follow target is set.
virtual void SetFollowPGain (const double _pGain) override
Set follow P Gain. Determines how fast the camera moves to follow the target node. Valid range: [0-1].
virtual void SetFollowTarget (const NodePtr &_target, const math::Vector3d &_Offset, const bool _worldFrame) override
Set a node for camera to follow. The camera will automatically update its position to keep itself at the specified offset distance from the target being followed. If null is specified, camera follow is disabled. In contrast to SetTrackTarget, the camera does not change its orientation when following is enabled.
virtual void SetHFOV (const math::Angle &_hfov) override
Set the camera's horizontal field-of-view.
virtual void SetImageFormat (PixelFormat _format, bool _reinterpretable=false) override
Set the image pixel format.
virtual void SetImageHeight (const unsigned int _height) override
Set the image height in pixels.
virtual void SetImageWidth (const unsigned int _width) override
Set the image width in pixels.
virtual void SetMaterial (const MaterialPtr &_material) override
Set a material that the camera should see on all objects.
virtual void SetNearClipPlane (const double _near) override
Set the camera's near clipping plane distance.
virtual void SetProjectionMatrix (const math::Matrix4d &_matrix) override
Set the projection matrix for this camera. This overrides the standard projection matrix computed based on camera parameters.
virtual void SetProjectionType (CameraProjectionType _type) override
Set the projection type for this camera This changes the projection matrix of the camera based on the camera projection type. A custom projection matrix can be specified via SetProjectionMatrix to override the provided one. To disable the custom projection matrix, just call this function again with the desired projection type.
virtual void SetShadowsDirty () override
virtual void SetTrackOffset (const math::Vector3d &_offset) override
Set track offset. Camera will track a point that's at an offset from the target node. The offset will be in the frame that is specified at the time the track target is set.
virtual void SetTrackPGain (const double _pGain) override
Set track P Gain. Determines how fast the camera rotates to look at the target node. Valid range: [0-1].
virtual void SetTrackTarget (const NodePtr &_target, const math::Vector3d &_offset, const bool _worldFrame) override
Set a node for camera to track. The camera will automatically change its orientation to face the target being tracked. If null is specified, tracking is disabled. In contrast to SetFollowTarget the camera does not change its position when tracking is enabled.
virtual math::Vector3d TrackOffset () const override
Get the track offset vector in the frame specified at the time the track target is set.
virtual double TrackPGain () const override
Get the camera track rotation P gain.
virtual NodePtr TrackTarget () const override
Get the target node being tracked.
virtual void Update () override
Renders a new frame. This is a convenience function for single-camera scenes. It wraps the pre-render, render, and post-render into a single function. This should NOT be used in applications with multiple cameras or multiple consumers of a single camera's images.
virtual math::Matrix4d ViewMatrix () const override
Get the view matrix for this camera.
virtual VisualPtr VisualAt (const gz::math::Vector2i &_mousePos) override
Get the visual for a given mouse position param[in] _mousePos mouse position.
Public Member Functions inherited from Camera
virtual ~Camera ()
Destructor.
virtual void Render ()=0
Renders the current scene using this camera. This function assumes PreRender() has already been called on the parent Scene, allowing the camera and the scene itself to prepare for rendering.
Public Member Functions inherited from Sensor
virtual ~Sensor ()
Sensor.
virtual void SetVisibilityMask (uint32_t _mask)=0
Set visibility mask.
virtual uint32_t VisibilityMask () const =0
Get visibility mask.
Public Member Functions inherited from Node
virtual ~Node ()
Destructor.
virtual void AddChild (NodePtr _child)=0
Add the given node to this node. If the given node is already a child, no work will be done.
virtual NodePtr ChildById (unsigned int _id) const =0
Get node with given ID. If no child exists with given ID, NULL will be returned.
virtual NodePtr ChildByIndex (unsigned int _index) const =0
Get node at given index. If no child exists at given index, NULL will be returned.
virtual NodePtr ChildByName (const std::string &_name) const =0
Get node with given name. If no child exists with given name, NULL will be returned.
virtual unsigned int ChildCount () const =0
Get number of child nodes.
virtual bool HasChild (ConstNodePtr _child) const =0
Determine if given node is an attached child.
virtual bool HasChildId (unsigned int _id) const =0
Determine if node with given ID is an attached child.
virtual bool HasChildName (const std::string &_name) const =0
Determine if node with given name is an attached child.
virtual bool HasParent () const =0
Determine if this Node is attached to another Node.
virtual bool HasUserData (const std::string &_key) const =0
Check if node has custom data.
virtual bool InheritScale () const =0
Determine if this node inherits scale from this parent.
virtual math::Pose3d InitialLocalPose () const =0
Get the initial local pose.
virtual math::Pose3d LocalPose () const =0
Get the local pose.
virtual math::Vector3d LocalPosition () const =0
Get the local position.
virtual math::Quaterniond LocalRotation () const =0
Get the local rotation.
virtual math::Vector3d LocalScale () const =0
Get the local scale.
virtual math::Vector3d Origin () const =0
Get position of origin.
virtual NodePtr Parent () const =0
Get the parent Node.
virtual NodePtr RemoveChild (NodePtr _child)=0
Remove (detach) the given node from this node. If the given node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildById (unsigned int _id)=0
Remove (detach) the node with the given ID from this node. If the specified node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildByIndex (unsigned int _index)=0
Remove (detach) the node at the given index from this node. If the specified node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildByName (const std::string &_name)=0
Remove (detach) the node with the given name from this node. If the specified node is not a child of this node, no work will be done.
virtual void RemoveChildren ()=0
Remove all child nodes from this node This detaches all the child nodes but does not destroy them.
virtual void RemoveParent ()=0
Detach this Node from its parent. If this Node does not have a parent, no work will be done.
virtual void Scale (const math::Vector3d &_scale)=0
Scale the current scale by the given scalars.
virtual void Scale (double _scale)=0
Scale the current scale by the given scalar. The given scalar will be assigned to the x, y, and z coordinates.
virtual void Scale (double _x, double _y, double _z)=0
Scale the current scale by the given scalars.
virtual void SetInheritScale (bool _inherit)=0
Specify if this node inherits scale from its parent.
virtual void SetLocalPose (const math::Pose3d &_pose)=0
Set the local pose.
virtual void SetLocalPosition (const math::Vector3d &_position)=0
Set the local position.
virtual void SetLocalPosition (double _x, double _y, double _z)=0
Set the local position.
virtual void SetLocalRotation (const math::Quaterniond &_rotation)=0
Set the local rotation.
virtual void SetLocalRotation (double _r, double _p, double _y)=0
Set the local rotation.
virtual void SetLocalRotation (double _w, double _x, double _y, double _z)=0
Set the local rotation.
virtual void SetLocalScale (const math::Vector3d &_scale)=0
Set the local scale.
virtual void SetLocalScale (double _scale)=0
Set the local scale. The given scale will be assigned to the x, y, and z coordinates.
virtual void SetLocalScale (double _x, double _y, double _z)=0
Set the local scale.
virtual void SetOrigin (const math::Vector3d &_origin)=0
Set position of origin. The position should be relative to the original origin of the geometry.
virtual void SetOrigin (double _x, double _y, double _z)=0
Set position of origin. The position should be relative to the original origin of the geometry.
virtual void SetUserData (const std::string &_key, Variant _value)=0
Store any custom data associated with this node.
virtual void SetWorldPose (const math::Pose3d &_pose)=0
Set the world pose.
virtual void SetWorldPosition (const math::Vector3d &_position)=0
Set the world position.
virtual void SetWorldPosition (double _x, double _y, double _z)=0
Set the world position.
virtual void SetWorldRotation (const math::Quaterniond &_rotation)=0
Set the world rotation.
virtual void SetWorldRotation (double _r, double _p, double _y)=0
Set the world rotation.
virtual void SetWorldRotation (double _w, double _x, double _y, double _z)=0
Set the world rotation.
virtual void SetWorldScale (const math::Vector3d &_scale)=0
Set the world scale.
virtual void SetWorldScale (double _scale)=0
Set the world scale. The given scale will be assigned to the x, y, and z coordinates.
virtual void SetWorldScale (double _x, double _y, double _z)=0
Set the world scale.
virtual Variant UserData (const std::string &_key) const =0
Get custom data stored in this node.
virtual math::Pose3d WorldPose () const =0
Get the world pose.
virtual math::Vector3d WorldPosition () const =0
Get the world position.
virtual math::Quaterniond WorldRotation () const =0
Get the world rotation.
virtual math::Vector3d WorldScale () const =0
Get the world scale.
virtual math::Pose3d WorldToLocal (const math::Pose3d &_pose) const =0
Convert given world pose to local pose.
Public Member Functions inherited from Object
virtual ~Object ()
Destructor.
virtual void Destroy ()=0
Destroy any resources associated with this object. Invoking any other functions after destroying an object will result in undefined behavior.
virtual unsigned int Id () const =0
Get the object ID. This ID will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
virtual std::string Name () const =0
Get the object name. This name will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
virtual ScenePtr Scene () const =0
Get the Scene that created this object.
Protected Member Functions
BaseCamera ()
virtual void * CreateImageBuffer () const
virtual void Load () override
virtual RenderTargetPtr RenderTarget () const =0
virtual void Reset ()
Protected Attributes
unsigned int antiAliasing = 0u
Anti-aliasing.
double aspect = 1.3333333
Aspect ratio.
double farClip = 1000.0
Far clipping plane distance.
NodePtr followNode
Target node to follow.
math::Vector3d followOffset
Offset distance between camera and target node being followed.
double followPGain = 1.0
P gain for follow mode. Determines how fast the camera moves to follow the target node. Valid range: [0-1].
bool followWorldFrame = false
Follow target in world frame.
math::Angle hfov
Horizontal camera field of view.
ImagePtr imageBuffer
double nearClip = 0.01
Near clipping plane distance.
common::EventT< void(const void *, unsigned int, unsigned int, unsigned int, const std::string &)> newFrameEvent
math::Matrix4d projectionMatrix
Custom projection matrix.
CameraProjectionType projectionType = CPT_PERSPECTIVE
Camera projection type.
NodePtr trackNode
Target node to track if camera tracking is on.
math::Vector3d trackOffset
Set camera to track a point offset in target node's local or world frame depending on trackWorldFrame.
double trackPGain = 1.0
P gain for tracking. Determines how fast the camera rotates to look at the target node. Valid range: [0-1].
bool trackWorldFrame = false
Track point relative to target in world frame.
Additional Inherited Members
Public Types inherited from Camera
typedef std::function< void(const void *, unsigned int, unsigned int, unsigned int, const std::string &)> NewFrameListener
Callback function for new frame render event listeners.
Constructor & Destructor Documentation
BaseCamera()
template<class T > BaseCamera () protected
~BaseCamera()
template<class T > ~BaseCamera () virtual
Member Function Documentation
AddRenderPass()
template<class T > void AddRenderPass (const RenderPassPtr & _pass) override virtual
Add a render pass to the camera.
Parameters
[in] _pass New render pass to add
Implements Camera.
Reimplemented in OgreWideAngleCamera, Ogre2DepthCamera, and Ogre2WideAngleCamera.
References RenderTarget::AddRenderPass().
AntiAliasing()
template<class T > unsigned int AntiAliasing () const override virtual
Get the level of anti-aliasing used during rendering.
Returns
The level of anti-aliasing used during rendering
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
AspectRatio()
template<class T > double AspectRatio () const override virtual
Get the camera's aspect ratio.
Remarks
If SetAspectRatio() gets called with an input <= 0 this function returns the Aspect Ratio autocalculated based on the camera's dimensions.
Returns
The camera's aspect ratio. This value is always in range (0; inf) unless the dimensions are invalid (e.g. 0 width or height, NaN resolution, etc)
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
Capture()
template<class T > void Capture (Image & _image) override virtual
Renders a new frame and writes the results to the given image. This is a convenience function for single-camera scenes. It wraps the pre-render, render, post-render, and get-image calls into a single function. This should NOT be used in applications with multiple cameras or multiple consumers of a single camera's images.
Parameters
[out] _image Output image buffer
Implements Camera.
ConnectNewImageFrame()
template<class T > common::ConnectionPtr ConnectNewImageFrame (Camera::NewFrameListener _listener) override virtual
Subscribes a new listener to this camera's new frame event.
Parameters
[in] _listener New camera listener callback
Implements Camera.
Copy()
template<class T > void Copy (Image & _image) const override virtual
Writes the last rendered image to the given image buffer. This function can be called multiple times after PostRender has been called, without rendering the scene again. Calling this function before a single image has been rendered will have undefined behavior.
Parameters
[out] _image Output image buffer
Implements Camera.
Reimplemented in OgreWideAngleCamera, and Ogre2WideAngleCamera.
References RenderTarget::Copy().
CreateImage()
template<class T > Image CreateImage () const override virtual
Created an empty image buffer for capturing images. The resulting image will have sufficient memory allocated for subsequent calls to this camera's Capture function. However, any changes to this cameras properties may invalidate the condition.
Returns
A newly allocated Image for storing this cameras images
Implements Camera.
CreateImageBuffer()
template<class T > void * CreateImageBuffer () const protected virtual
CreateRenderWindow()
template<class T > RenderWindowPtr CreateRenderWindow () override virtual
Create a render window.
Returns
A pointer to the render window.
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
References std::endl(), Scene::Engine(), gzerr, and RenderEngine::Name().
FarClipPlane()
template<class T > double FarClipPlane () const override virtual
Get the camera's far clipping plane distance.
Returns
Far clipping plane distance
Implements Camera.
Reimplemented in OgreDepthCamera, and Ogre2DepthCamera.
FollowOffset()
template<class T > math::Vector3d FollowOffset () const override virtual
Get the follow offset vector in the frame specified at the time the follow target is set.
Returns
Offset of camera from target.
Implements Camera.
FollowPGain()
template<class T > double FollowPGain () const override virtual
Get the camera follow movement P gain.
Returns
P gain for camera following
Implements Camera.
FollowTarget()
template<class T > NodePtr FollowTarget () const override virtual
Get the target node being followed.
Returns
Target node being tracked.
Implements Camera.
HFOV()
template<class T > math::Angle HFOV () const override virtual
Get the camera's horizontal field-of-view.
Returns
Angle containing the camera's horizontal field-of-view
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
ImageFormat()
template<class T > PixelFormat ImageFormat () const override virtual
Get the image pixel format. If the image pixel format has not been set with a valid value, PF_UNKNOWN will be returned.
Returns
The image pixel format
Implements Camera.
References RenderTarget::Format().
ImageHeight()
template<class T > unsigned int ImageHeight () const override virtual
Get the image height in pixels.
Returns
The image height in pixels
Implements Camera.
References RenderTarget::Height().
ImageMemorySize()
template<class T > unsigned int ImageMemorySize () const override virtual
Get the total image memory size in bytes.
Returns
The image memory size in bytes
Implements Camera.
References PixelUtil::MemorySize().
ImageWidth()
template<class T > unsigned int ImageWidth () const override virtual
Get the image width in pixels.
Returns
The image width in pixels
Implements Camera.
References RenderTarget::Width().
Load()
template<class T > void Load () override protected virtual
NearClipPlane()
template<class T > double NearClipPlane () const override virtual
Get the camera's near clipping plane distance.
Returns
Near clipping plane distance
Implements Camera.
Reimplemented in OgreDepthCamera, and Ogre2DepthCamera.
PostRender()
template<class T > void PostRender () override virtual
Preforms any necessary final rendering work. Once rendering is complete the camera will alert any listeners of the new frame event. This function should only be called after a call to Render has successfully been executed.
Implements Camera.
Reimplemented in OgreDepthCamera, OgreGpuRays, OgreThermalCamera, OgreWideAngleCamera, Ogre2BoundingBoxCamera, Ogre2DepthCamera, Ogre2GpuRays, Ogre2SegmentationCamera, Ogre2ThermalCamera, and Ogre2WideAngleCamera.
References Object::PostRender().
PrepareForExternalSampling()
template<class T > void PrepareForExternalSampling () override virtual
Right now this is Vulkan-only. This function needs to be called after rendering, and before handling the texture pointer (i.e. by calling RenderTextureMetalId()) so that external APIs (e.g. Qt) can sample the texture.
Implements Camera.
Reimplemented in Ogre2Camera.
References std::endl(), and gzerr.
PreRender()
template<class T > void PreRender () override virtual
Prepare this object and any of its children for rendering. This should be called for each object in a scene just before rendering, which can be achieved by a single call to Scene::PreRender.
Implements Object.
Reimplemented in OgreDepthCamera, OgreGpuRays, OgreThermalCamera, OgreWideAngleCamera, Ogre2BoundingBoxCamera, Ogre2DepthCamera, Ogre2GpuRays, Ogre2SegmentationCamera, Ogre2ThermalCamera, and Ogre2WideAngleCamera.
References std::dynamic_pointer_cast(), gz::math::equal(), Quaternion< typename T >::Identity, Matrix4< typename T >::LookAt(), Pose3< typename T >::Pos(), RenderTarget::PreRender(), Pose3< typename T >::Rot(), and Quaternion< typename T >::Slerp().
Project()
template<class T > math::Vector2i Project (const math::Vector3d & _pt) const override virtual
Project point in 3d world space to 2d screen space.
Parameters
[in] _pt Point in 3d world space
Returns
Point in 2d screen space
Implements Camera.
References Vector2< typename T >::X(), Vector3< typename T >::X(), Vector2< typename T >::Y(), Vector3< typename T >::Y(), and Vector3< typename T >::Z().
ProjectionMatrix()
template<class T > math::Matrix4d ProjectionMatrix () const override virtual
Get the projection matrix for this camera.
Returns
Camera projection matrix
Implements Camera.
Reimplemented in OgreCamera, OgreDepthCamera, Ogre2BoundingBoxCamera, Ogre2Camera, Ogre2DepthCamera, Ogre2SegmentationCamera, and Ogre2ThermalCamera.
References std::atan(), gz::rendering::CPT_ORTHOGRAPHIC, gz::rendering::CPT_PERSPECTIVE, std::endl(), gzerr, and std::tan().
ProjectionType()
template<class T > CameraProjectionType ProjectionType () const override virtual
Get the projection type for this camera.
Returns
Camera projection type
Implements Camera.
RemoveAllRenderPasses()
template<class T > void RemoveAllRenderPasses () override virtual
Remove all render passes from the camera.
Implements Camera.
Reimplemented in OgreWideAngleCamera, and Ogre2WideAngleCamera.
RemoveRenderPass()
template<class T > void RemoveRenderPass (const RenderPassPtr & _pass) override virtual
Remove a render pass from the camera.
Parameters
[in] _pass render pass to remove
Implements Camera.
Reimplemented in OgreWideAngleCamera, and Ogre2WideAngleCamera.
References RenderTarget::RemoveRenderPass().
RenderPassByIndex()
template<class T > RenderPassPtr RenderPassByIndex (unsigned int _index) const override virtual
Get a render passes by index.
Returns
Render pass at the specified index
Implements Camera.
References RenderTarget::RenderPassByIndex().
RenderPassCount()
template<class T > unsigned int RenderPassCount () const override virtual
Get the number of render passes applied to the camera.
Returns
Number of render passes applied
Implements Camera.
References RenderTarget::RenderPassCount().
RenderTarget()
template<class T > virtual RenderTargetPtr RenderTarget () const protected pure virtual
Implemented in OgreCamera, OgreDepthCamera, OgreGpuRays, OgreThermalCamera, OgreWideAngleCamera, Ogre2BoundingBoxCamera, Ogre2Camera, Ogre2DepthCamera, Ogre2GpuRays, Ogre2SegmentationCamera, Ogre2ThermalCamera, Ogre2WideAngleCamera, BaseGpuRays< T >, BaseGpuRays< Ogre2Sensor >, and BaseGpuRays< OgreSensor >.
RenderTextureGLId()
template<class T > unsigned int RenderTextureGLId () const override virtual
Get the OpenGL texture id associated with the render texture used by this camera. A valid id is returned only if the underlying render engine is OpenGL based.
Returns
Texture Id of type GLuint.
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
References std::endl(), and gzerr.
RenderTextureMetalId()
template<class T > void RenderTextureMetalId (void * _textureIdPtr) const override virtual
Get the Metal texture id associated with the render texture used by this camera. A valid Id is obtained only if the underlying render engine is Metal based. The pointer set by this function must be released to an id<MTLTexture> using CFBridgingRelease.
Parameters
[out] _textureIdPtr the address of a void* pointer.
Implements Camera.
Reimplemented in Ogre2Camera.
References std::endl(), and gzerr.
Reset()
template<class T > void Reset () protected virtual
References gz::rendering::PF_R8G8B8, and Angle::SetDegree().
SaveFrame()
template<class T > bool SaveFrame (const std::string & _name) override virtual
Writes the previously rendered frame to a file. This function can be called multiple times after PostRender has been called, without rendering the scene again. Calling this function before a single image has been rendered will have undefined behavior.
Parameters
[in] _name Name of the output file
Implements Camera.
SetAntiAliasing()
template<class T > void SetAntiAliasing (const unsigned int _aa) override virtual
Set the level of anti-aliasing used during rendering. If a value of 0 is given, no anti-aliasing will be performed. Higher values can significantly slow-down rendering times, depending on the underlying render engine.
Parameters
[in] _aa Level of anti-aliasing used during rendering
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
SetAspectRatio()
template<class T > void SetAspectRatio (const double _ratio) override virtual
Set the camera's aspect ratio. This value determines the cameras vertical field-of-view. It is often the.
 image_height /
image_width
but this is not necessarily true.
Setting a value <= 0.0 indicates the aspect ratio will be automatically calculated based on width & height.
Parameters
[in] _ratio The camera's aspect ratio
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
SetFarClipPlane()
template<class T > void SetFarClipPlane (const double _far) override virtual
Set the camera's far clipping plane distance.
Parameters
[in] _far Far clipping plane distance
Implements Camera.
Reimplemented in OgreCamera, OgreDepthCamera, Ogre2Camera, and Ogre2DepthCamera.
SetFollowOffset()
template<class T > void SetFollowOffset (const math::Vector3d & _offset) override virtual
Set offset of camera from target node being followed. The offset will be in the frame that is specified at the time the follow target is set.
Parameters
[in] _offset Offset distance from target node.
Implements Camera.
SetFollowPGain()
template<class T > void SetFollowPGain (const double _pGain) override virtual
Set follow P Gain. Determines how fast the camera moves to follow the target node. Valid range: [0-1].
Parameters
[in] _pGain P gain for camera following
Implements Camera.
References gz::math::clamp().
SetFollowTarget()
template<class T > void SetFollowTarget (const NodePtr & _target, const math::Vector3d & _offset, const bool _worldFrame) override virtual
Set a node for camera to follow. The camera will automatically update its position to keep itself at the specified offset distance from the target being followed. If null is specified, camera follow is disabled. In contrast to SetTrackTarget, the camera does not change its orientation when following is enabled.
Parameters
[in] _target Target node to follow
[in] _offset Tether the camera at an offset distance from the target node.
[in] _worldFrame True to follow the target node at a distance that's fixed in world frame. Default is false which means the camera follows at fixed distance in target node's local frame.
Implements Camera.
SetHFOV()
template<class T > void SetHFOV (const math::Angle & _hfov) override virtual
Set the camera's horizontal field-of-view.
Parameters
[in] _hfov Desired horizontal field-of-view
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
SetImageFormat()
template<class T > void SetImageFormat (PixelFormat _format, bool _reinterpretable = false) override virtual
Set the image pixel format.
Parameters
[in] _format New image pixel format
[in] _reinterpretable See RenderTarget::SetFormat
Implements Camera.
References RenderTarget::SetFormat().
SetImageHeight()
template<class T > void SetImageHeight (const unsigned int _height) override virtual
Set the image height in pixels.
Parameters
[in] _height New image height in pixels
Implements Camera.
References RenderTarget::SetHeight().
SetImageWidth()
template<class T > void SetImageWidth (const unsigned int _width) override virtual
Set the image width in pixels.
Parameters
[in] _width New image width in pixels
Implements Camera.
References RenderTarget::SetWidth().
SetMaterial()
template<class T > void SetMaterial (const MaterialPtr & _material) override virtual
Set a material that the camera should see on all objects.
Parameters
[in] _material a material instance
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
References std::endl(), and gzerr.
SetNearClipPlane()
template<class T > void SetNearClipPlane (const double _near) override virtual
Set the camera's near clipping plane distance.
Parameters
[in] _near Near clipping plane distance
Implements Camera.
Reimplemented in OgreCamera, OgreDepthCamera, Ogre2Camera, and Ogre2DepthCamera.
SetProjectionMatrix()
template<class T > void SetProjectionMatrix (const math::Matrix4d & _matrix) override virtual
Set the projection matrix for this camera. This overrides the standard projection matrix computed based on camera parameters.
Parameters
[in] _matrix Camera projection matrix
Implements Camera.
Reimplemented in OgreCamera, OgreDepthCamera, Ogre2BoundingBoxCamera, Ogre2Camera, Ogre2DepthCamera, Ogre2SegmentationCamera, and Ogre2ThermalCamera.
SetProjectionType()
template<class T > void SetProjectionType (CameraProjectionType _type) override virtual
Set the projection type for this camera This changes the projection matrix of the camera based on the camera projection type. A custom projection matrix can be specified via SetProjectionMatrix to override the provided one. To disable the custom projection matrix, just call this function again with the desired projection type.
Parameters
[in] _type Camera projection type
See also
SetProjectionMatrix
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
SetShadowsDirty()
template<class T > void SetShadowsDirty () override virtual
Implements Camera.
Reimplemented in Ogre2Camera, and Ogre2DepthCamera.
SetTrackOffset()
template<class T > void SetTrackOffset (const math::Vector3d & _offset) override virtual
Set track offset. Camera will track a point that's at an offset from the target node. The offset will be in the frame that is specified at the time the track target is set.
Parameters
[in] _offset Point offset to track
Implements Camera.
SetTrackPGain()
template<class T > void SetTrackPGain (const double _pGain) override virtual
Set track P Gain. Determines how fast the camera rotates to look at the target node. Valid range: [0-1].
Parameters
[in] _pGain P gain for camera tracking
Implements Camera.
References gz::math::clamp().
SetTrackTarget()
template<class T > void SetTrackTarget (const NodePtr & _target, const math::Vector3d & _offset, const bool _worldFrame) override virtual
Set a node for camera to track. The camera will automatically change its orientation to face the target being tracked. If null is specified, tracking is disabled. In contrast to SetFollowTarget the camera does not change its position when tracking is enabled.
Parameters
[in] _target Target node to track
[in] _offset Track a point that is at an offset relative to target.
[in] _worldFrame If true, the offset point to track will be treated in world frame and its position relative to the target node remains fixed regardless of the target node's rotation. Default is false, which means the camera tracks the point in target node's local frame.
Implements Camera.
TrackOffset()
template<class T > math::Vector3d TrackOffset () const override virtual
Get the track offset vector in the frame specified at the time the track target is set.
Returns
Point offset from target.
Implements Camera.
TrackPGain()
template<class T > double TrackPGain () const override virtual
Get the camera track rotation P gain.
Returns
P gain for camera tracking
Implements Camera.
TrackTarget()
template<class T > NodePtr TrackTarget () const override virtual
Get the target node being tracked.
Returns
Target node being tracked.
Implements Camera.
Update()
template<class T > void Update () override virtual
Renders a new frame. This is a convenience function for single-camera scenes. It wraps the pre-render, render, and post-render into a single function. This should NOT be used in applications with multiple cameras or multiple consumers of a single camera's images.
Implements Camera.
References Scene::PostRender(), and Scene::PreRender().
ViewMatrix()
template<class T > math::Matrix4d ViewMatrix () const override virtual
Get the view matrix for this camera.
Returns
Camera view matrix
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
References Matrix4< typename T >::SetTranslation(), and Matrix3< typename T >::Transpose().
VisualAt()
template<class T > VisualPtr VisualAt (const gz::math::Vector2i & _mousePos) override virtual
Get the visual for a given mouse position param[in] _mousePos mouse position.
Implements Camera.
Reimplemented in OgreCamera, and Ogre2Camera.
References std::endl(), and gzerr.
Member Data Documentation
antiAliasing
template<class T > unsigned int antiAliasing = 0u protected
Anti-aliasing.
aspect
template<class T > double aspect = 1.3333333 protected
Aspect ratio.
farClip
template<class T > double farClip = 1000.0 protected
Far clipping plane distance.
followNode
template<class T > NodePtr followNode protected
Target node to follow.
followOffset
template<class T > math::Vector3d followOffset protected
Offset distance between camera and target node being followed.
followPGain
template<class T > double followPGain = 1.0 protected
P gain for follow mode. Determines how fast the camera moves to follow the target node. Valid range: [0-1].
followWorldFrame
template<class T > bool followWorldFrame = false protected
Follow target in world frame.
hfov
template<class T > math::Angle hfov protected
Horizontal camera field of view.
imageBuffer
template<class T > ImagePtr imageBuffer protected
nearClip
template<class T > double nearClip = 0.01 protected
Near clipping plane distance.
newFrameEvent
template<class T > common::EventT<void(const void *, unsigned int, unsigned int, unsigned int, const std::string &)> newFrameEvent protected
projectionMatrix
template<class T > math::Matrix4d projectionMatrix protected
Custom projection matrix.
projectionType
template<class T > CameraProjectionType projectionType = CPT_PERSPECTIVE protected
Camera projection type.
trackNode
template<class T > NodePtr trackNode protected
Target node to track if camera tracking is on.
trackOffset
template<class T > math::Vector3d trackOffset protected
Set camera to track a point offset in target node's local or world frame depending on trackWorldFrame.
trackPGain
template<class T > double trackPGain = 1.0 protected
P gain for tracking. Determines how fast the camera rotates to look at the target node. Valid range: [0-1].
trackWorldFrame
template<class T > bool trackWorldFrame = false protected
Track point relative to target in world frame.
The documentation for this class was generated from the following file:
BaseCamera.hh