Gazebo Rendering: BaseStoreWrapper< T, U > Class Template Reference
Gazebo Rendering
API Reference
9.0.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
BaseStoreWrapper< T, U > Class Template Reference
#include <BaseStorage.hh>
Public Member Functions
BaseStoreWrapper (UStorePtr _store)
virtual ~BaseStoreWrapper ()
virtual bool Add (TPtr _object)
Add given element. If the element has already been added or its name or ID conflict with other existing elements, then no work will be done.
virtual bool Contains (ConstTPtr _object) const
Determine if store contains the given element.
virtual bool ContainsId (unsigned int _id) const
Determine if store contains the element with the given ID.
virtual bool ContainsName (const std::string &_name) const
Determine if store contains the element with the given name.
virtual void Destroy (TPtr _object)
Remove and destroy given element. If the given element does not exists, in this store, then no work will be done.
virtual void DestroyAll ()
Remove and destroy all elements in store.
virtual void DestroyById (unsigned int _id)
Remove and destroy element with the given ID. If the specified element does not exists in this store, then no work will be done.
virtual void DestroyByIndex (unsigned int _index)
Remove and destroy element at the given index. If the specified element does not exists in this store, then no work will be done.
virtual void DestroyByName (const std::string &_name)
Remove and destroy element with the given name. If the specified element does not exists in this store, then no work will be done.
virtual TPtr GetById (unsigned int _id) const
Get element with the given ID.
virtual TPtr GetByIndex (unsigned int _index) const
Get element at the given index.
virtual TPtr GetByName (const std::string &_name) const
Get element with the given name.
virtual TPtr Remove (TPtr _object)
Remove given element. If the given element does not exists in this store, then no work will be done.
virtual void RemoveAll ()
Remove all elements from store.
virtual TPtr RemoveById (unsigned int _id)
Remove element with the given ID. If the specified element does not exists in this store, then no work will be done.
virtual TPtr RemoveByIndex (unsigned int _index)
Remove element at the given index. If the specified element does not exists in this store, then no work will be done.
virtual TPtr RemoveByName (const std::string &_name)
Remove element with the given name. If the specified element does not exists in this store, then no work will be done.
virtual unsigned int Size () const
Get number of elements in this store.
Public Member Functions inherited from StoreWrapper< T, U >
virtual ~StoreWrapper ()=default
Public Member Functions inherited from Store< T >
virtual ~Store ()=default
Destructor.
Protected Attributes
UStorePtr store
Constructor & Destructor Documentation
BaseStoreWrapper()
template<class T , class U > BaseStoreWrapper (UStorePtr _store) explicit
~BaseStoreWrapper()
template<class T , class U > ~BaseStoreWrapper () virtual
Member Function Documentation
Add()
template<class T , class U > bool Add (TPtr _object) virtual
Add given element. If the element has already been added or its name or ID conflict with other existing elements, then no work will be done.
Parameters
[in] _object Element to be added
Returns
True if successful
Implements Store< T >.
References std::dynamic_pointer_cast().
Contains()
template<class T , class U > bool Contains (ConstTPtr _object) const virtual
Determine if store contains the given element.
Parameters
[in] _object The element in question
Returns
True if this store contains the given element
Implements Store< T >.
References std::dynamic_pointer_cast().
ContainsId()
template<class T , class U > bool ContainsId (unsigned int _id) const virtual
Determine if store contains the element with the given ID.
Parameters
[in] _id ID of the element in question
Returns
True if this store contains the specified element
Implements Store< T >.
ContainsName()
template<class T , class U > bool ContainsName (const std::string & _name) const virtual
Determine if store contains the element with the given name.
Parameters
[in] _name Name of the element in question
Returns
True if this store contains the specified element
Implements Store< T >.
Destroy()
template<class T , class U > void Destroy (TPtr _object) virtual
Remove and destroy given element. If the given element does not exists, in this store, then no work will be done.
Parameters
[in] _object Element to be removed
Implements Store< T >.
References std::dynamic_pointer_cast().
DestroyAll()
template<class T , class U > void DestroyAll () virtual
Remove and destroy all elements in store.
Implements Store< T >.
DestroyById()
template<class T , class U > void DestroyById (unsigned int _id) virtual
Remove and destroy element with the given ID. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _id ID of the element to be removed
Implements Store< T >.
DestroyByIndex()
template<class T , class U > void DestroyByIndex (unsigned int _index) virtual
Remove and destroy element at the given index. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _index Index of the element to be removed
Implements Store< T >.
DestroyByName()
template<class T , class U > void DestroyByName (const std::string & _name) virtual
Remove and destroy element with the given name. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _name Name of the element to be removed
Implements Store< T >.
GetById()
template<class T , class U > BaseStoreWrapper< T, U >::TPtr GetById (unsigned int _id) const virtual
Get element with the given ID.
Parameters
[in] _id ID of the desired element
Returns
The specified element
Implements Store< T >.
GetByIndex()
template<class T , class U > BaseStoreWrapper< T, U >::TPtr GetByIndex (unsigned int _index) const virtual
Get element at the given index.
Parameters
[in] _index Index of the desired element
Returns
The specified element
Implements Store< T >.
GetByName()
template<class T , class U > BaseStoreWrapper< T, U >::TPtr GetByName (const std::string & _name) const virtual
Get element with the given name.
Parameters
[in] _name Name of the desired element
Returns
The specified element
Implements Store< T >.
Remove()
template<class T , class U > BaseStoreWrapper< T, U >::TPtr Remove (TPtr _object) virtual
Remove given element. If the given element does not exists in this store, then no work will be done.
Parameters
[in] _object Element to be removed
Returns
The removed element
Implements Store< T >.
References std::dynamic_pointer_cast().
RemoveAll()
template<class T , class U > void RemoveAll () virtual
Remove all elements from store.
Implements Store< T >.
RemoveById()
template<class T , class U > BaseStoreWrapper< T, U >::TPtr RemoveById (unsigned int _id) virtual
Remove element with the given ID. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _id ID of the element to be removed
Returns
The removed element
Implements Store< T >.
RemoveByIndex()
template<class T , class U > BaseStoreWrapper< T, U >::TPtr RemoveByIndex (unsigned int _index) virtual
Remove element at the given index. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _index Index of the element to be removed
Returns
The removed element
Implements Store< T >.
RemoveByName()
template<class T , class U > BaseStoreWrapper< T, U >::TPtr RemoveByName (const std::string & _name) virtual
Remove element with the given name. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _name Name of the element to be removed
Returns
The removed element
Implements Store< T >.
Size()
template<class T , class U > unsigned int Size () const virtual
Get number of elements in this store.
Returns
The number of elements in this store
Implements Store< T >.
Member Data Documentation
store
template<class T , class U > UStorePtr store protected
The documentation for this class was generated from the following file:
BaseStorage.hh