Gazebo Rendering: BaseLidarVisual< T > Class Template Reference
Gazebo Rendering
API Reference
9.0.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
BaseLidarVisual< T > Class Template Reference
Base implementation of a Lidar Visual.
#include <BaseLidarVisual.hh>
Public Member Functions
virtual ~BaseLidarVisual ()
virtual void ClearPoints () override
Clear the points of the lidar visual.
virtual void CreateMaterials ()
Create predefined materials for lidar visual.
virtual void Destroy () override
Destroy any resources associated with this object. Invoking any other functions after destroying an object will result in undefined behavior.
virtual bool DisplayNonHitting () const override
Get if non-hitting rays will be displayed.
virtual unsigned int HorizontalRayCount () const override
Get number of horizontal rays.
virtual void Init () override
virtual double MaxHorizontalAngle () const override
Get maximum horizontal angle.
virtual double MaxRange () const override
Get maximum range of lidar rays.
virtual double MaxVerticalAngle () const override
Get minimum vertical angle.
virtual double MinHorizontalAngle () const override
Get minimum horizontal angle.
virtual double MinRange () const override
Get minimum range of lidar rays.
virtual double MinVerticalAngle () const override
Get minimum vertical angle.
virtual gz::math::Pose3d Offset () const override
Get offset of visual.
virtual unsigned int PointCount () const override
Get number of points in laser data.
virtual std::vector< double > Points () const override
Get the points in laser data.
virtual void PreRender () override
Prepare this object and any of its children for rendering. This should be called for each object in a scene just before rendering, which can be achieved by a single call to Scene::PreRender.
virtual void SetDisplayNonHitting (bool _display) override
Set if non-hitting rays will be displayed (this does not work for TRIANGLE_STRIPS visual)
virtual void SetHorizontalRayCount (unsigned int _horizontalRayCount) override
Set number of horizontal rays.
virtual void SetMaxHorizontalAngle (double _maxHorizontalAngle) override
Set maximum horizontal angle.
virtual void SetMaxRange (double _maxRange) override
Set maximum range of lidar rays.
virtual void SetMaxVerticalAngle (double _maxVerticalAngle) override
Set maximum vertical angle.
virtual void SetMinHorizontalAngle (double _minHorizontalAngle) override
Set minimum horizontal angle.
virtual void SetMinRange (double _minRange) override
Set minimum range of lidar rays.
virtual void SetMinVerticalAngle (double _minVerticalAngle) override
Set minimum vertical angle.
virtual void SetOffset (const gz::math::Pose3d _offset) override
Set offset of visual.
virtual void SetPoints (const std::vector< double > &_points) override
Set lidar points to be visualised.
virtual void SetPoints (const std::vector< double > &_points, const std::vector< gz::math::Color > &_colors) override
Set lidar points to be visualised.
virtual void SetSize (double _size) override
Set size of the lidar visualization, e.g. size of rasterized lidar points in pixels.
virtual void SetType (const LidarVisualType _type) override
Set type for lidar visual.
virtual void SetVerticalRayCount (unsigned int _verticalRayCount) override
Set number of vertical rays.
virtual double Size () const override
Get size of the lidar visualization.
virtual LidarVisualType Type () const override
Get the type for lidar visual.
virtual void Update () override
Update the Visual.
virtual unsigned int VerticalRayCount () const override
Get number of vertical rays.
Public Member Functions inherited from LidarVisual
virtual ~LidarVisual ()
Destructor.
Public Member Functions inherited from Visual
virtual ~Visual ()
Destructor.
virtual void AddGeometry (GeometryPtr _geometry)=0
Add the given geometry to this visual. If the given node is already attached, no work will be done.
virtual void AddVisibilityFlags (uint32_t _flags)=0
Add visibility flags.
virtual gz::math::AxisAlignedBox BoundingBox () const =0
Get the bounding box in world frame coordinates.
virtual VisualPtr Clone (const std::string &_name, NodePtr _newParent) const =0
Clone the visual (and its children) with a new name.
virtual GeometryPtr GeometryByIndex (unsigned int _index) const =0
Get geometry at given index. If no geometry exists at given index, NULL will be returned.
virtual unsigned int GeometryCount () const =0
Get the number of geometries attached to this visual.
virtual bool HasGeometry (ConstGeometryPtr _geometry) const =0
Determine if given geometry is attached to this visual.
virtual gz::math::AxisAlignedBox LocalBoundingBox () const =0
Get the local bounding box of the visual.
virtual MaterialPtr Material () const =0
Get the material assigned to attached visuals and geometries.
virtual void RemoveGeometries ()=0
Remove all attached geometries from this visual.
virtual GeometryPtr RemoveGeometry (GeometryPtr _geometry)=0
Remove the given geometry from this visual. If the given node is not a child of this visual, no work will be done.
virtual GeometryPtr RemoveGeometryByIndex (unsigned int _index)=0
Remove the geometry at the given index from this visual. If the specified node is not attached this visual, no work will be done.
virtual void RemoveVisibilityFlags (uint32_t _flags)=0
Remove visibility flags.
virtual void SetChildMaterial (MaterialPtr _material, bool _unique=true)=0
Set the material for all attached visuals only.
virtual void SetGeometryMaterial (MaterialPtr _material, bool _unique=true)=0
Set the material for all attached geometries only.
virtual void SetMaterial (const std::string &_name, bool _unique=true)=0
Set the material for all attached visuals and geometries. The specified material will be retrieved from Scene::Material using the given material name. If no material is registered with the given name, no work will be done.
virtual void SetMaterial (MaterialPtr _material, bool _unique=true)=0
Set the material for all attached visuals and geometries.
virtual void SetStatic (bool _static)=0
Tells Render Engine this Visual will be static (i.e. won't move, rotate or scale) You can still move, rotate or scale the Visual; however doing so has a performance impact. How much of an impact will depend on the rendering backend being used.
virtual void SetVisibilityFlags (uint32_t _flags)=0
Set visibility flags.
virtual void SetVisible (bool _visible)=0
Specify if this visual is visible.
virtual void SetWireframe (bool _show)=0
Enable or disable wireframe.
virtual bool Static () const =0
Get whether the visual is static.
virtual uint32_t VisibilityFlags () const =0
Get visibility flags.
virtual bool Wireframe () const =0
Get whether wireframe is enabled for this visual.
Public Member Functions inherited from Node
virtual ~Node ()
Destructor.
virtual void AddChild (NodePtr _child)=0
Add the given node to this node. If the given node is already a child, no work will be done.
virtual NodePtr ChildById (unsigned int _id) const =0
Get node with given ID. If no child exists with given ID, NULL will be returned.
virtual NodePtr ChildByIndex (unsigned int _index) const =0
Get node at given index. If no child exists at given index, NULL will be returned.
virtual NodePtr ChildByName (const std::string &_name) const =0
Get node with given name. If no child exists with given name, NULL will be returned.
virtual unsigned int ChildCount () const =0
Get number of child nodes.
virtual bool HasChild (ConstNodePtr _child) const =0
Determine if given node is an attached child.
virtual bool HasChildId (unsigned int _id) const =0
Determine if node with given ID is an attached child.
virtual bool HasChildName (const std::string &_name) const =0
Determine if node with given name is an attached child.
virtual bool HasParent () const =0
Determine if this Node is attached to another Node.
virtual bool HasUserData (const std::string &_key) const =0
Check if node has custom data.
virtual bool InheritScale () const =0
Determine if this node inherits scale from this parent.
virtual math::Pose3d InitialLocalPose () const =0
Get the initial local pose.
virtual math::Pose3d LocalPose () const =0
Get the local pose.
virtual math::Vector3d LocalPosition () const =0
Get the local position.
virtual math::Quaterniond LocalRotation () const =0
Get the local rotation.
virtual math::Vector3d LocalScale () const =0
Get the local scale.
virtual math::Vector3d Origin () const =0
Get position of origin.
virtual NodePtr Parent () const =0
Get the parent Node.
virtual NodePtr RemoveChild (NodePtr _child)=0
Remove (detach) the given node from this node. If the given node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildById (unsigned int _id)=0
Remove (detach) the node with the given ID from this node. If the specified node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildByIndex (unsigned int _index)=0
Remove (detach) the node at the given index from this node. If the specified node is not a child of this node, no work will be done.
virtual NodePtr RemoveChildByName (const std::string &_name)=0
Remove (detach) the node with the given name from this node. If the specified node is not a child of this node, no work will be done.
virtual void RemoveChildren ()=0
Remove all child nodes from this node This detaches all the child nodes but does not destroy them.
virtual void RemoveParent ()=0
Detach this Node from its parent. If this Node does not have a parent, no work will be done.
virtual void Scale (const math::Vector3d &_scale)=0
Scale the current scale by the given scalars.
virtual void Scale (double _scale)=0
Scale the current scale by the given scalar. The given scalar will be assigned to the x, y, and z coordinates.
virtual void Scale (double _x, double _y, double _z)=0
Scale the current scale by the given scalars.
virtual void SetInheritScale (bool _inherit)=0
Specify if this node inherits scale from its parent.
virtual void SetLocalPose (const math::Pose3d &_pose)=0
Set the local pose.
virtual void SetLocalPosition (const math::Vector3d &_position)=0
Set the local position.
virtual void SetLocalPosition (double _x, double _y, double _z)=0
Set the local position.
virtual void SetLocalRotation (const math::Quaterniond &_rotation)=0
Set the local rotation.
virtual void SetLocalRotation (double _r, double _p, double _y)=0
Set the local rotation.
virtual void SetLocalRotation (double _w, double _x, double _y, double _z)=0
Set the local rotation.
virtual void SetLocalScale (const math::Vector3d &_scale)=0
Set the local scale.
virtual void SetLocalScale (double _scale)=0
Set the local scale. The given scale will be assigned to the x, y, and z coordinates.
virtual void SetLocalScale (double _x, double _y, double _z)=0
Set the local scale.
virtual void SetOrigin (const math::Vector3d &_origin)=0
Set position of origin. The position should be relative to the original origin of the geometry.
virtual void SetOrigin (double _x, double _y, double _z)=0
Set position of origin. The position should be relative to the original origin of the geometry.
virtual void SetUserData (const std::string &_key, Variant _value)=0
Store any custom data associated with this node.
virtual void SetWorldPose (const math::Pose3d &_pose)=0
Set the world pose.
virtual void SetWorldPosition (const math::Vector3d &_position)=0
Set the world position.
virtual void SetWorldPosition (double _x, double _y, double _z)=0
Set the world position.
virtual void SetWorldRotation (const math::Quaterniond &_rotation)=0
Set the world rotation.
virtual void SetWorldRotation (double _r, double _p, double _y)=0
Set the world rotation.
virtual void SetWorldRotation (double _w, double _x, double _y, double _z)=0
Set the world rotation.
virtual void SetWorldScale (const math::Vector3d &_scale)=0
Set the world scale.
virtual void SetWorldScale (double _scale)=0
Set the world scale. The given scale will be assigned to the x, y, and z coordinates.
virtual void SetWorldScale (double _x, double _y, double _z)=0
Set the world scale.
virtual Variant UserData (const std::string &_key) const =0
Get custom data stored in this node.
virtual math::Pose3d WorldPose () const =0
Get the world pose.
virtual math::Vector3d WorldPosition () const =0
Get the world position.
virtual math::Quaterniond WorldRotation () const =0
Get the world rotation.
virtual math::Vector3d WorldScale () const =0
Get the world scale.
virtual math::Pose3d WorldToLocal (const math::Pose3d &_pose) const =0
Convert given world pose to local pose.
Public Member Functions inherited from Object
virtual ~Object ()
Destructor.
virtual unsigned int Id () const =0
Get the object ID. This ID will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
virtual std::string Name () const =0
Get the object name. This name will be unique across all objects inside a given scene, but necessarily true for objects across different scenes.
virtual void PostRender ()=0
Post process this object and any of its children after rendering.
virtual ScenePtr Scene () const =0
Get the Scene that created this object.
Protected Member Functions
BaseLidarVisual ()
Protected Member Functions inherited from LidarVisual
LidarVisual ()
Protected Attributes
bool displayNonHitting = true
Option to display non-hitting rays.
double horizontalAngleStep = 0
Angle between two horizontal rays.
unsigned int horizontalCount = 1u
Horizontal laser count.
LidarVisualType lidarVisualType
Type of lidar visualisation.
double maxHorizontalAngle = 0
Horizontal maximum angle.
double maxRange = 0
Maximum Range.
double maxVerticalAngle = 0
Vertical maximum angle.
double minHorizontalAngle = 0
Horizontal minimal angle.
double minRange = 0
Minimum Range.
double minVerticalAngle = 0
Vertical minimal angle.
gz::math::Pose3d offset = gz::math::Pose3d::Zero
Offset of visual.
double size = 1.0
Size of lidar visualisation.
double verticalAngleStep = 0
Angle between two vertical rays.
unsigned int verticalCount = 1u
Vertical laser count.
Detailed Description
template<class T>
class gz::rendering::BaseLidarVisual< T >
Base implementation of a Lidar Visual.
Constructor & Destructor Documentation
BaseLidarVisual()
template<class T > BaseLidarVisual () protected
~BaseLidarVisual()
template<class T > ~BaseLidarVisual () virtual
Member Function Documentation
ClearPoints()
template<class T > void ClearPoints () override virtual
Clear the points of the lidar visual.
Implements LidarVisual.
Reimplemented in OgreLidarVisual, and Ogre2LidarVisual.
CreateMaterials()
template<class T > void CreateMaterials () virtual
Create predefined materials for lidar visual.
References Scene::CreateMaterial().
Destroy()
template<class T > void Destroy () override virtual
Destroy any resources associated with this object. Invoking any other functions after destroying an object will result in undefined behavior.
Implements Object.
Reimplemented in OgreLidarVisual, and Ogre2LidarVisual.
DisplayNonHitting()
template<class T > bool DisplayNonHitting () const override virtual
Get if non-hitting rays will be displayed.
Returns
Boolean value if non-hitting rays will be displayed
Implements LidarVisual.
HorizontalRayCount()
template<class T > unsigned int HorizontalRayCount () const override virtual
Get number of horizontal rays.
Returns
The number of horizontal rays
Implements LidarVisual.
Init()
template<class T > void Init () override virtual
Reimplemented in OgreLidarVisual, and Ogre2LidarVisual.
MaxHorizontalAngle()
template<class T > double MaxHorizontalAngle () const override virtual
Get maximum horizontal angle.
Returns
The maximum horizontal angle value of the lidar visual
Implements LidarVisual.
MaxRange()
template<class T > double MaxRange () const override virtual
Get maximum range of lidar rays.
Returns
The maximum range for lidar rays
Implements LidarVisual.
MaxVerticalAngle()
template<class T > double MaxVerticalAngle () const override virtual
Get minimum vertical angle.
Returns
The maximum vertical angle value of the lidar visual
Implements LidarVisual.
MinHorizontalAngle()
template<class T > double MinHorizontalAngle () const override virtual
Get minimum horizontal angle.
Returns
The minimum horizontal angle value of the lidar visual
Implements LidarVisual.
MinRange()
template<class T > double MinRange () const override virtual
Get minimum range of lidar rays.
Returns
The minimum range for lidar rays
Implements LidarVisual.
MinVerticalAngle()
template<class T > double MinVerticalAngle () const override virtual
Get minimum vertical angle.
Returns
The minimum vertical angle value of the lidar visual
Implements LidarVisual.
Offset()
template<class T > gz::math::Pose3d Offset () const override virtual
Get offset of visual.
Returns
The offset of the lidar rays from visual origin
Implements LidarVisual.
PointCount()
template<class T > unsigned int PointCount () const override virtual
Get number of points in laser data.
Returns
The number of points in the laser data
Implements LidarVisual.
Reimplemented in OgreLidarVisual, and Ogre2LidarVisual.
Points()
template<class T > std::vector< double > Points () const override virtual
Get the points in laser data.
Returns
The points in the laser data
Implements LidarVisual.
Reimplemented in OgreLidarVisual, and Ogre2LidarVisual.
PreRender()
template<class T > void PreRender () override virtual
Prepare this object and any of its children for rendering. This should be called for each object in a scene just before rendering, which can be achieved by a single call to Scene::PreRender.
Implements Object.
Reimplemented in OgreLidarVisual, and Ogre2LidarVisual.
SetDisplayNonHitting()
template<class T > void SetDisplayNonHitting (bool _display) override virtual
Set if non-hitting rays will be displayed (this does not work for TRIANGLE_STRIPS visual)
Parameters
[in] _display Boolean value to display non hitting visuals
Implements LidarVisual.
SetHorizontalRayCount()
template<class T > void SetHorizontalRayCount (unsigned int _horizontalRayCount) override virtual
Set number of horizontal rays.
Parameters
[in] _horizontalRayCount Number of vertical rays
Implements LidarVisual.
References std::endl(), and gzwarn.
SetMaxHorizontalAngle()
template<class T > void SetMaxHorizontalAngle (double _maxHorizontalAngle) override virtual
Set maximum horizontal angle.
Parameters
[in] _maxHorizontalAngle Maximum horizontal angle value
Implements LidarVisual.
SetMaxRange()
template<class T > void SetMaxRange (double _maxRange) override virtual
Set maximum range of lidar rays.
Parameters
[in] _maxRange The maximum range for lidar rays
Implements LidarVisual.
SetMaxVerticalAngle()
template<class T > void SetMaxVerticalAngle (double _maxVerticalAngle) override virtual
Set maximum vertical angle.
Parameters
[in] _maxVerticalAngle Maximum vertical angle value
Implements LidarVisual.
SetMinHorizontalAngle()
template<class T > void SetMinHorizontalAngle (double _minHorizontalAngle) override virtual
Set minimum horizontal angle.
Parameters
[in] _minHorizontalAngle Minimum horizontal angle value
Implements LidarVisual.
SetMinRange()
template<class T > void SetMinRange (double _minRange) override virtual
Set minimum range of lidar rays.
Parameters
[in] _minRange The minimum range for lidar rays
Implements LidarVisual.
SetMinVerticalAngle()
template<class T > void SetMinVerticalAngle (double _minVerticalAngle) override virtual
Set minimum vertical angle.
Parameters
[in] _minVerticalAngle Minimum vertical angle
Implements LidarVisual.
SetOffset()
template<class T > void SetOffset (const gz::math::Pose3d _offset) override virtual
Set offset of visual.
Parameters
[in] _offset The offset of the lidar rays from visual origin
Implements LidarVisual.
SetPoints() [1/2]
template<class T > void SetPoints (const std::vector< double > & _points) override virtual
Set lidar points to be visualised.
Parameters
[in] _points Vector of points representing distance of the ray
Implements LidarVisual.
Reimplemented in OgreLidarVisual, and Ogre2LidarVisual.
SetPoints() [2/2]
template<class T > void SetPoints (const std::vector< double > & _points, const std::vector< gz::math::Color > & _colors) override virtual
Set lidar points to be visualised.
Parameters
[in] _points Vector of points representing distance of the ray
[in] _colors Vector of colors for the rendered points
Implements LidarVisual.
Reimplemented in OgreLidarVisual.
SetSize()
template<class T > void SetSize (double _size) override virtual
Set size of the lidar visualization, e.g. size of rasterized lidar points in pixels.
Parameters
[in] _size Size of the lidar visualization.
Implements LidarVisual.
SetType()
template<class T > void SetType (const LidarVisualType _type) override virtual
Set type for lidar visual.
Parameters
[in] _type The type of visualisation for lidar data
Implements LidarVisual.
SetVerticalRayCount()
template<class T > void SetVerticalRayCount (unsigned int _verticalRayCount) override virtual
Set number of vertical rays.
Parameters
[in] _verticalRayCount Number of vertical rays
Implements LidarVisual.
References std::endl(), and gzwarn.
Size()
template<class T > double Size () const override virtual
Get size of the lidar visualization.
Returns
Size of the lidar visualization.
See also
SetSize
Implements LidarVisual.
Type()
template<class T > LidarVisualType Type () const override virtual
Get the type for lidar visual.
Returns
The type for lidar visual
Implements LidarVisual.
Update()
template<class T > void Update () override virtual
Update the Visual.
Implements LidarVisual.
Reimplemented in OgreLidarVisual, and Ogre2LidarVisual.
VerticalRayCount()
template<class T > unsigned int VerticalRayCount () const override virtual
Get number of vertical rays.
Returns
The number of vertical rays
Implements LidarVisual.
Member Data Documentation
displayNonHitting
template<class T > bool displayNonHitting = true protected
Option to display non-hitting rays.
horizontalAngleStep
template<class T > double horizontalAngleStep = 0 protected
Angle between two horizontal rays.
horizontalCount
template<class T > unsigned int horizontalCount = 1u protected
Horizontal laser count.
lidarVisualType
template<class T > LidarVisualType lidarVisualType protected
Initial value:
=
                      LidarVisualType::LVT_TRIANGLE_STRIPS
Type of lidar visualisation.
maxHorizontalAngle
template<class T > double maxHorizontalAngle = 0 protected
Horizontal maximum angle.
maxRange
template<class T > double maxRange = 0 protected
Maximum Range.
maxVerticalAngle
template<class T > double maxVerticalAngle = 0 protected
Vertical maximum angle.
minHorizontalAngle
template<class T > double minHorizontalAngle = 0 protected
Horizontal minimal angle.
minRange
template<class T > double minRange = 0 protected
Minimum Range.
minVerticalAngle
template<class T > double minVerticalAngle = 0 protected
Vertical minimal angle.
offset
template<class T > gz::math::Pose3d offset = gz::math::Pose3d::Zero protected
Offset of visual.
size
template<class T > double size = 1.0 protected
Size of lidar visualisation.
verticalAngleStep
template<class T > double verticalAngleStep = 0 protected
Angle between two vertical rays.
verticalCount
template<class T > unsigned int verticalCount = 1u protected
Vertical laser count.
The documentation for this class was generated from the following file:
BaseLidarVisual.hh