Gazebo Rendering: BaseCompositeStore< T > Class Template Reference
Gazebo Rendering
API Reference
9.0.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
BaseCompositeStore< T > Class Template Reference
#include <BaseStorage.hh>
Public Member Functions
BaseCompositeStore ()
virtual ~BaseCompositeStore ()
virtual bool Add (TPtr _object)
Add given element. If the element has already been added or its name or ID conflict with other existing elements, then no work will be done.
virtual bool AddStore (TStorePtr _store)
Add the given store. If the given store already exists, then no work will be done.
virtual bool Contains (ConstTPtr _object) const
Determine if store contains the given element.
virtual bool ContainsId (unsigned int _id) const
Determine if store contains the element with the given ID.
virtual bool ContainsName (const std::string &_name) const
Determine if store contains the element with the given name.
virtual bool ContainsStore (ConstTStorePtr _store) const
Determine if given store exists.
virtual void Destroy (TPtr _object)
Remove and destroy given element. If the given element does not exists, in this store, then no work will be done.
virtual void DestroyAll ()
Remove and destroy all elements in store.
virtual void DestroyById (unsigned int _id)
Remove and destroy element with the given ID. If the specified element does not exists in this store, then no work will be done.
virtual void DestroyByIndex (unsigned int _index)
Remove and destroy element at the given index. If the specified element does not exists in this store, then no work will be done.
virtual void DestroyByName (const std::string &_name)
Remove and destroy element with the given name. If the specified element does not exists in this store, then no work will be done.
virtual TPtr GetById (unsigned int _id) const
Get element with the given ID.
virtual TPtr GetByIndex (unsigned int _index) const
Get element at the given index.
virtual TPtr GetByName (const std::string &_name) const
Get element with the given name.
virtual TStorePtr GetStore (unsigned int _index) const
Get store at the given index. If no such store exists NULL will be returned.
virtual unsigned int GetStoreCount () const
Get number of Stores.
virtual TPtr Remove (TPtr _object)
Remove given element. If the given element does not exists in this store, then no work will be done.
virtual void RemoveAll ()
Remove all elements from store.
virtual TPtr RemoveById (unsigned int _id)
Remove element with the given ID. If the specified element does not exists in this store, then no work will be done.
virtual TPtr RemoveByIndex (unsigned int _index)
Remove element at the given index. If the specified element does not exists in this store, then no work will be done.
virtual TPtr RemoveByName (const std::string &_name)
Remove element with the given name. If the specified element does not exists in this store, then no work will be done.
virtual TStorePtr RemoveStore (TStorePtr _store)
Remove given store. If no such store exists no work will be done and NULL will be returned.
virtual TStorePtr RemoveStore (unsigned int _index)
Remove store at the given index. If no such store exists no work will be done and NULL will be returned.
virtual TStorePtr RemoveStoreImpl (TStoreIter _iter)
virtual unsigned int Size () const
Get number of elements in this store.
Public Member Functions inherited from CompositeStore< T >
virtual ~CompositeStore ()=default
Destructor.
Public Member Functions inherited from Store< T >
virtual ~Store ()=default
Destructor.
Protected Attributes
TStoreList stores
Constructor & Destructor Documentation
BaseCompositeStore()
template<class T > BaseCompositeStore ()
~BaseCompositeStore()
template<class T > ~BaseCompositeStore () virtual
Member Function Documentation
Add()
template<class T > bool Add (TPtr _object) virtual
Add given element. If the element has already been added or its name or ID conflict with other existing elements, then no work will be done.
Parameters
[in] _object Element to be added
Returns
True if successful
Implements Store< T >.
References std::endl(), and gzerr.
AddStore()
template<class T > bool AddStore (TStorePtr _store) virtual
Add the given store. If the given store already exists, then no work will be done.
Parameters
[in] _store Store to be added
Returns
True if successful
Implements CompositeStore< T >.
References std::endl(), and gzerr.
Contains()
template<class T > bool Contains (ConstTPtr _object) const virtual
Determine if store contains the given element.
Parameters
[in] _object The element in question
Returns
True if this store contains the given element
Implements Store< T >.
ContainsId()
template<class T > bool ContainsId (unsigned int _id) const virtual
Determine if store contains the element with the given ID.
Parameters
[in] _id ID of the element in question
Returns
True if this store contains the specified element
Implements Store< T >.
ContainsName()
template<class T > bool ContainsName (const std::string & _name) const virtual
Determine if store contains the element with the given name.
Parameters
[in] _name Name of the element in question
Returns
True if this store contains the specified element
Implements Store< T >.
ContainsStore()
template<class T > bool ContainsStore (ConstTStorePtr _store) const virtual
Determine if given store exists.
Parameters
[in] _store Store in question
Returns
True if given store exists
Implements CompositeStore< T >.
References std::find().
Destroy()
template<class T > void Destroy (TPtr _object) virtual
Remove and destroy given element. If the given element does not exists, in this store, then no work will be done.
Parameters
[in] _object Element to be removed
Implements Store< T >.
DestroyAll()
template<class T > void DestroyAll () virtual
Remove and destroy all elements in store.
Implements Store< T >.
DestroyById()
template<class T > void DestroyById (unsigned int _id) virtual
Remove and destroy element with the given ID. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _id ID of the element to be removed
Implements Store< T >.
DestroyByIndex()
template<class T > void DestroyByIndex (unsigned int _index) virtual
Remove and destroy element at the given index. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _index Index of the element to be removed
Implements Store< T >.
DestroyByName()
template<class T > void DestroyByName (const std::string & _name) virtual
Remove and destroy element with the given name. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _name Name of the element to be removed
Implements Store< T >.
GetById()
template<class T > BaseCompositeStore< T >::TPtr GetById (unsigned int _id) const virtual
Get element with the given ID.
Parameters
[in] _id ID of the desired element
Returns
The specified element
Implements Store< T >.
GetByIndex()
template<class T > BaseCompositeStore< T >::TPtr GetByIndex (unsigned int _index) const virtual
Get element at the given index.
Parameters
[in] _index Index of the desired element
Returns
The specified element
Implements Store< T >.
References std::endl(), and gzerr.
GetByName()
template<class T > BaseCompositeStore< T >::TPtr GetByName (const std::string & _name) const virtual
Get element with the given name.
Parameters
[in] _name Name of the desired element
Returns
The specified element
Implements Store< T >.
GetStore()
template<class T > BaseCompositeStore< T >::TStorePtr GetStore (unsigned int _index) const virtual
Get store at the given index. If no such store exists NULL will be returned.
Parameters
[in] _index Index of the desired store
Returns
The specified store
Implements CompositeStore< T >.
References std::endl(), and gzerr.
GetStoreCount()
template<class T > unsigned int GetStoreCount () const virtual
Get number of Stores.
Returns
The number of Stores
Implements CompositeStore< T >.
Remove()
template<class T > BaseCompositeStore< T >::TPtr Remove (TPtr _object) virtual
Remove given element. If the given element does not exists in this store, then no work will be done.
Parameters
[in] _object Element to be removed
Returns
The removed element
Implements Store< T >.
RemoveAll()
template<class T > void RemoveAll () virtual
Remove all elements from store.
Implements Store< T >.
RemoveById()
template<class T > BaseCompositeStore< T >::TPtr RemoveById (unsigned int _id) virtual
Remove element with the given ID. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _id ID of the element to be removed
Returns
The removed element
Implements Store< T >.
RemoveByIndex()
template<class T > BaseCompositeStore< T >::TPtr RemoveByIndex (unsigned int _index) virtual
Remove element at the given index. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _index Index of the element to be removed
Returns
The removed element
Implements Store< T >.
RemoveByName()
template<class T > BaseCompositeStore< T >::TPtr RemoveByName (const std::string & _name) virtual
Remove element with the given name. If the specified element does not exists in this store, then no work will be done.
Parameters
[in] _name Name of the element to be removed
Returns
The removed element
Implements Store< T >.
RemoveStore() [1/2]
template<class T > BaseCompositeStore< T >::TStorePtr RemoveStore (TStorePtr _store) virtual
Remove given store. If no such store exists no work will be done and NULL will be returned.
Parameters
[in] _store Store to be removed
Returns
The removed store
Implements CompositeStore< T >.
References std::find().
RemoveStore() [2/2]
template<class T > BaseCompositeStore< T >::TStorePtr RemoveStore (unsigned int _index) virtual
Remove store at the given index. If no such store exists no work will be done and NULL will be returned.
Parameters
[in] _index Index of the store to be removed
Returns
The removed store
Implements CompositeStore< T >.
References std::advance(), std::endl(), and gzerr.
RemoveStoreImpl()
template<class T > BaseCompositeStore< T >::TStorePtr RemoveStoreImpl (TStoreIter _iter) virtual
Size()
template<class T > unsigned int Size () const virtual
Get number of elements in this store.
Returns
The number of elements in this store
Implements Store< T >.
Member Data Documentation
stores
template<class T > TStoreList stores protected
The documentation for this class was generated from the following file:
BaseStorage.hh