Gazebo Sim: BaseComponent Class Reference
Gazebo Sim
API Reference
8.6.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
BaseComponent Class Reference abstract
Base class for all components.
#include <Component.hh>
Public Member Functions
BaseComponent ()=default
Default constructor.
virtual ~BaseComponent ()=default
Default destructor.
virtual std::unique_ptr< BaseComponent > Clone () const =0
Clone the component.
virtual void Deserialize (std::istream &_in)
Fills a component based on a stream with a serialized data. By default, it will do nothing. Derived classes should override this function to support deserialization.
virtual void Serialize (std::ostream &_out) const
Fills a stream with a serialized version of the component. By default, it will leave the stream empty. Derived classes should override this function to support serialization.
virtual ComponentTypeId TypeId () const =0
Returns the unique ID for the component's type. The ID is derived from the name that is manually chosen during the Factory registration and is guaranteed to be the same across compilers and runs.
Detailed Description
Base class for all components.
Constructor & Destructor Documentation
BaseComponent()
BaseComponent () default
Default constructor.
~BaseComponent()
virtual ~BaseComponent () virtual default
Default destructor.
Member Function Documentation
Clone()
virtual std::unique_ptr<BaseComponent> Clone () const pure virtual
Clone the component.
Returns
A pointer to the component.
Implemented in Component< NoData, Identifier, Serializer >, and Component< DataType, Identifier, Serializer >.
Deserialize()
virtual void Deserialize (std::istream & _in) inline virtual
Fills a component based on a stream with a serialized data. By default, it will do nothing. Derived classes should override this function to support deserialization.
Parameters
[in] _in In stream.
Reimplemented in Component< NoData, Identifier, Serializer >, and Component< DataType, Identifier, Serializer >.
References std::endl(), gzwarn, and BaseComponent::TypeId().
Serialize()
virtual void Serialize (std::ostream & _out) const inline virtual
Fills a stream with a serialized version of the component. By default, it will leave the stream empty. Derived classes should override this function to support serialization.
Parameters
[in] _out Out stream.
Reimplemented in Component< NoData, Identifier, Serializer >, and Component< DataType, Identifier, Serializer >.
References std::endl(), gzwarn, and BaseComponent::TypeId().
TypeId()
virtual ComponentTypeId TypeId () const pure virtual
Returns the unique ID for the component's type. The ID is derived from the name that is manually chosen during the Factory registration and is guaranteed to be the same across compilers and runs.
Implemented in Component< NoData, Identifier, Serializer >, and Component< DataType, Identifier, Serializer >.
Referenced by BaseComponent::Deserialize(), Factory::New(), and BaseComponent::Serialize().
The documentation for this class was generated from the following file:
Component.hh