Gazebo Transport: ReqHandler< google::protobuf::Message, google::protobuf::Message > Class Reference
Gazebo Transport
API Reference
13.4.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
ReqHandler< google::protobuf::Message, google::protobuf::Message > Class Reference
#include <ReqHandler.hh>
Public Member Functions
ReqHandler (const std::string &_nUuid)
void NotifyResult (const std::string &_rep, const bool _result)
Executes the callback registered for this handler and notify a potential requester waiting on a blocking call.
virtual std::string RepTypeName () const
Get the message type name used in the service response.
virtual std::string ReqTypeName () const
Get the message type name used in the service request.
bool Serialize (std::string &_buffer) const
Serialize the Req protobuf message stored.
void SetMessage (const google::protobuf::Message *_reqMsg)
Set the REQ protobuf message for this handler.
void SetResponse (const google::protobuf::Message *_repMsg)
Set the REP protobuf message for this handler.
Public Member Functions inherited from IReqHandler
IReqHandler (const std::string &_nUuid)
Constructor.
virtual ~IReqHandler ()=default
Destructor.
std::string HandlerUuid () const
Returns the unique handler UUID.
std::string NodeUuid () const
Get the node UUID.
bool Requested () const
Returns if this service call request has already been requested.
void Requested (const bool _value)
Mark the service call as requested (or not).
std::string Response () const
Get the service response as raw bytes.
bool Result () const
Get the result of the service response.
template<typename Lock >
bool WaitUntil (Lock &_lock, const unsigned int _timeout)
Block the current thread until the response to the service request is available or until the timeout expires. This method uses a condition variable to notify when the response is available.
Additional Inherited Members
Public Attributes inherited from IReqHandler
bool repAvailable
When there is a blocking service call request, the call can be unlocked when a service call REP is available. This variable captures if we have found a node that can satisty our request.
Protected Attributes inherited from IReqHandler
std::condition_variable_any condition
Condition variable used to wait until a service call REP is available.
std::string hUuid
Unique handler's UUID.
std::string rep
Stores the service response as raw bytes.
bool result
Stores the result of the service call.
Constructor & Destructor Documentation
ReqHandler()
ReqHandler (const std::string & _nUuid) inline explicit
Member Function Documentation
NotifyResult()
void NotifyResult (const std::string & _rep, const bool _result) inline virtual
Executes the callback registered for this handler and notify a potential requester waiting on a blocking call.
Parameters
[in] _rep Serialized data containing the response coming from the service call responser.
[in] _result Contains the result of the service call coming from the service call responser.
Implements IReqHandler.
References IReqHandler::condition, condition_variable_any::notify_one(), IReqHandler::rep, IReqHandler::repAvailable, and IReqHandler::result.
RepTypeName()
virtual std::string RepTypeName () const inline virtual
Get the message type name used in the service response.
Returns
Message type name.
Implements IReqHandler.
References std::endl().
ReqTypeName()
virtual std::string ReqTypeName () const inline virtual
Get the message type name used in the service request.
Returns
Message type name.
Implements IReqHandler.
References std::endl().
Serialize()
bool Serialize (std::string & _buffer) const inline virtual
Serialize the Req protobuf message stored.
Parameters
[out] _buffer The serialized data.
Returns
True if the serialization succeed or false otherwise.
Implements IReqHandler.
References std::endl().
SetMessage()
void SetMessage (const google::protobuf::Message * _reqMsg) inline
Set the REQ protobuf message for this handler.
Parameters
[in] _reqMsg Protofub message containing the input parameters of of the service request.
References std::endl().
SetResponse()
void SetResponse (const google::protobuf::Message * _repMsg) inline
Set the REP protobuf message for this handler.
Parameters
[in] _repMsg Protofub message containing the variable where the result will be stored. The only purpose of this function is to store the type information of _repMsg.
References std::endl().
The documentation for this class was generated from the following file:
ReqHandler.hh