Gazebo Msgs: gz::msgs Namespace Reference
Gazebo Msgs
API Reference
10.3.0
Index
List
Hierarchy
Members: All
Members: Functions
Members: Variables
Members: Typedefs
Members: Enumerations
Members: Enumerator
List
Members
Functions
Typedefs
Variables
Enumerations
Enumerator
gz::msgs Namespace Reference
Classes
class Factory
A factory that generates protobuf message based on a string type. This allows for global registration of messages via static initialization. If you don't need the singleton, consider using MessageFactory instead.
class MessageFactory
A factory that generates protobuf message based on a string type. This class will also try to load all Protobuf descriptors in paths provided in LoadDescriptors as well as the GZ_DESCRIPTOR_PATH environment variable.
class PointCloudPackedConstIterator
Same as a PointCloudPackedIterator but for const data.
class PointCloudPackedIterator
Class that can iterate over a PointCloudPacked message.
Functions
gz::math::AxisAlignedBox Convert (const AxisAlignedBox &_msg)
Boolean Convert (const bool &_data)
bool Convert (const Boolean &_msg)
gz::math::Color Convert (const Color &_msg)
Double Convert (const double &_data)
double Convert (const Double &_msg)
Float Convert (const float &_data)
float Convert (const Float &_msg)
AxisAlignedBox Convert (const gz::math::AxisAlignedBox &_data)
Color Convert (const gz::math::Color &_data)
Inertial Convert (const gz::math::Inertiald &_data)
Inertial Convert (const gz::math::MassMatrix3d &_data)
PlaneGeom Convert (const gz::math::Planed &_data)
Pose Convert (const gz::math::Pose3d &_data)
Quaternion Convert (const gz::math::Quaterniond &_data)
SphericalCoordinates Convert (const gz::math::SphericalCoordinates &_data)
Vector2d Convert (const gz::math::Vector2d &_data)
Vector3d Convert (const gz::math::Vector3d &_data)
gz::math::Inertiald Convert (const Inertial &_msg)
int32_t Convert (const Int32 &_msg)
Int32 Convert (const int32_t &_data)
int64_t Convert (const Int64 &_msg)
Int64 Convert (const int64_t &_data)
math::SphericalCoordinates::CoordinateType Convert (const msgs::SphericalCoordinatesType &_sc)
gz::math::Planed Convert (const PlaneGeom &_msg)
gz::math::Pose3d Convert (const Pose &_msg)
gz::math::Quaterniond Convert (const Quaternion &_msg)
gz::math::SphericalCoordinates Convert (const SphericalCoordinates &_msg)
Time Convert (const std::chrono::steady_clock::duration &_data)
StringMsg Convert (const std::string &_data)
std::string Convert (const StringMsg &_msg)
std::chrono::steady_clock::duration Convert (const Time &_msg)
uint32_t Convert (const UInt32 &_msg)
UInt32 Convert (const uint32_t &_data)
uint64_t Convert (const UInt64 &_msg)
UInt64 Convert (const uint64_t &_data)
gz::math::Vector2d Convert (const Vector2d &_msg)
gz::math::Vector3d Convert (const Vector3d &_msg)
msgs::SphericalCoordinatesType ConvertCoord (const math::SphericalCoordinates::CoordinateType &_sc)
std::string ConvertDiscoveryType (const msgs::Discovery::Type &_type)
msgs::Discovery::Type ConvertDiscoveryType (const std::string &_str)
bool ConvertFuelMetadata (const msgs::FuelMetadata &_meta, std::string &_modelConfigStr)
bool ConvertFuelMetadata (const std::string &_modelConfigStr, msgs::FuelMetadata &_meta)
std::string ConvertGeometryType (const msgs::Geometry::Type _type)
msgs::Geometry::Type ConvertGeometryType (const std::string &_str)
std::string ConvertJointType (const msgs::Joint::Type &_type)
msgs::Joint::Type ConvertJointType (const std::string &_str)
std::string ConvertPixelFormatType (const msgs::PixelFormatType &_t)
msgs::PixelFormatType ConvertPixelFormatType (const std::string &_str)
std::string ConvertShaderType (const msgs::Material::ShaderType &_type)
msgs::Material::ShaderType ConvertShaderType (const std::string &_str)
std::string getInstallPrefix ()
getInstallPrefix return the install prefix of the library i.e. CMAKE_INSTALL_PREFIX unless the library has been moved
void InitPointCloudPacked (msgs::PointCloudPacked &_msg, const std::string &_frameId, bool _memoryAligned, const std::vector< std::pair< std::string, msgs::PointCloudPacked::Field::DataType >> &_fields)
void Set (AxisAlignedBox *_msg, const gz::math::AxisAlignedBox &_data)
void Set (bool *_data, const Boolean &_msg)
void Set (Boolean *_msg, const bool &_data)
void Set (Color *_msg, const gz::math::Color &_data)
void Set (double *_data, const Double &_msg)
void Set (Double *_msg, const double &_data)
void Set (float *_data, const Float &_msg)
void Set (Float *_msg, const float &_data)
void Set (gz::math::AxisAlignedBox *_data, const AxisAlignedBox &_msg)
void Set (gz::math::Color *_data, const Color &_msg)
void Set (gz::math::Inertiald *_data, const Inertial &_msg)
void Set (gz::math::MassMatrix3d *_data, const Inertial &_msg)
void Set (gz::math::Planed *_data, const PlaneGeom &_msg)
void Set (gz::math::Pose3d *_data, const Pose &_msg)
void Set (gz::math::Quaterniond *_data, const Quaternion &_msg)
void Set (gz::math::SphericalCoordinates *_data, const SphericalCoordinates &_msg)
void Set (gz::math::Vector2d *_data, const Vector2d &_msg)
void Set (gz::math::Vector3d *_data, const Vector3d &_msg)
void Set (Inertial *_msg, const gz::math::Inertiald &_data)
void Set (Inertial *_msg, const gz::math::MassMatrix3d &_data)
void Set (Int32 *_msg, const int32_t &_data)
void Set (int32_t *_data, const Int32 &_msg)
void Set (Int64 *_msg, const int64_t &_data)
void Set (int64_t *_data, const Int64 &_msg)
void Set (PlaneGeom *_msg, const gz::math::Planed &_data)
void Set (Pose *_msg, const gz::math::Pose3d &_data)
void Set (Quaternion *_msg, const gz::math::Quaterniond &_data)
void Set (SphericalCoordinates *_msg, const gz::math::SphericalCoordinates &_data)
void Set (std::chrono::steady_clock::duration *_data, const Time &_msg)
void Set (std::string *_data, const StringMsg &_msg)
void Set (StringMsg *_msg, const char *_data)
void Set (StringMsg *_msg, const std::string &_data)
void Set (Time *_msg, const std::chrono::steady_clock::duration &_data)
void Set (UInt32 *_msg, const uint32_t &_data)
void Set (uint32_t *_data, const UInt32 &_msg)
void Set (UInt64 *_msg, const uint64_t &_data)
void Set (uint64_t *_data, const UInt64 &_msg)
void Set (Vector2d *_msg, const gz::math::Vector2d &_data)
void Set (Vector3d *_msg, const gz::math::Vector3d &_data)
int sizeOfPointField (PointCloudPacked::Field::DataType _dataType)
Return the size of a datatype (which is an enum of PointCloudPacked::Field) in bytes.
std::string ToString (const msgs::Discovery::Type &_t)
Function Documentation
Convert() [1/38]
gz::math::AxisAlignedBox gz::msgs::Convert (const AxisAlignedBox & _msg) inline
References Set().
Convert() [2/38]
Boolean gz::msgs::Convert (const bool & _data) inline
References Set().
Convert() [3/38]
bool gz::msgs::Convert (const Boolean & _msg) inline
References Set().
Convert() [4/38]
gz::math::Color gz::msgs::Convert (const Color & _msg) inline
References Set().
Convert() [5/38]
Double gz::msgs::Convert (const double & _data) inline
References Set().
Convert() [6/38]
double gz::msgs::Convert (const Double & _msg) inline
References Set().
Convert() [7/38]
Float gz::msgs::Convert (const float & _data) inline
References Set().
Convert() [8/38]
float gz::msgs::Convert (const Float & _msg) inline
References Set().
Convert() [9/38]
AxisAlignedBox gz::msgs::Convert (const gz::math::AxisAlignedBox & _data) inline
References Set().
Referenced by Set().
Convert() [10/38]
Color gz::msgs::Convert (const gz::math::Color & _data) inline
References Set().
Convert() [11/38]
Inertial gz::msgs::Convert (const gz::math::Inertiald & _data) inline
References Set().
Convert() [12/38]
Inertial gz::msgs::Convert (const gz::math::MassMatrix3d & _data) inline
References Set().
Convert() [13/38]
PlaneGeom gz::msgs::Convert (const gz::math::Planed & _data) inline
References Set().
Convert() [14/38]
Pose gz::msgs::Convert (const gz::math::Pose3d & _data) inline
References Set().
Convert() [15/38]
Quaternion gz::msgs::Convert (const gz::math::Quaterniond & _data) inline
References Set().
Convert() [16/38]
SphericalCoordinates gz::msgs::Convert (const gz::math::SphericalCoordinates & _data) inline
References Set().
Convert() [17/38]
Vector2d gz::msgs::Convert (const gz::math::Vector2d & _data) inline
References Set().
Convert() [18/38]
Vector3d gz::msgs::Convert (const gz::math::Vector3d & _data) inline
References Set().
Convert() [19/38]
gz::math::Inertiald gz::msgs::Convert (const Inertial & _msg) inline
References Set().
Convert() [20/38]
int32_t gz::msgs::Convert (const Int32 & _msg) inline
References Set().
Convert() [21/38]
Int32 gz::msgs::Convert (const int32_t & _data) inline
References Set().
Convert() [22/38]
int64_t gz::msgs::Convert (const Int64 & _msg) inline
References Set().
Convert() [23/38]
Int64 gz::msgs::Convert (const int64_t & _data) inline
References Set().
Convert() [24/38]
math::SphericalCoordinates::CoordinateType gz::msgs::Convert (const msgs::SphericalCoordinatesType & _sc) inline
References std::endl().
Convert() [25/38]
gz::math::Planed gz::msgs::Convert (const PlaneGeom & _msg) inline
References Set().
Convert() [26/38]
gz::math::Pose3d gz::msgs::Convert (const Pose & _msg) inline
References Set().
Convert() [27/38]
gz::math::Quaterniond gz::msgs::Convert (const Quaternion & _msg) inline
References Set().
Convert() [28/38]
gz::math::SphericalCoordinates gz::msgs::Convert (const SphericalCoordinates & _msg) inline
References Set().
Convert() [29/38]
Time gz::msgs::Convert (const std::chrono::steady_clock::duration & _data) inline
References Set().
Convert() [30/38]
StringMsg gz::msgs::Convert (const std::string & _data) inline
References Set().
Convert() [31/38]
std::string gz::msgs::Convert (const StringMsg & _msg) inline
References Set().
Convert() [32/38]
std::chrono::steady_clock::duration gz::msgs::Convert (const Time & _msg) inline
References Set().
Convert() [33/38]
uint32_t gz::msgs::Convert (const UInt32 & _msg) inline
References Set().
Convert() [34/38]
UInt32 gz::msgs::Convert (const uint32_t & _data) inline
References Set().
Convert() [35/38]
uint64_t gz::msgs::Convert (const UInt64 & _msg) inline
References Set().
Convert() [36/38]
UInt64 gz::msgs::Convert (const uint64_t & _data) inline
References Set().
Convert() [37/38]
gz::math::Vector2d gz::msgs::Convert (const Vector2d & _msg) inline
References Set().
Convert() [38/38]
gz::math::Vector3d gz::msgs::Convert (const Vector3d & _msg) inline
References Set().
ConvertCoord()
msgs::SphericalCoordinatesType gz::msgs::ConvertCoord (const math::SphericalCoordinates::CoordinateType & _sc) inline
References std::endl().
ConvertDiscoveryType() [1/2]
std::string gz::msgs::ConvertDiscoveryType (const msgs::Discovery::Type & _type) inline
ConvertDiscoveryType() [2/2]
msgs::Discovery::Type gz::msgs::ConvertDiscoveryType (const std::string & _str) inline
References std::endl().
Referenced by ToString().
ConvertFuelMetadata() [1/2]
bool gz::msgs::ConvertFuelMetadata (const msgs::FuelMetadata & _meta, std::string & _modelConfigStr) inline
References ostringstream::str().
ConvertFuelMetadata() [2/2]
bool gz::msgs::ConvertFuelMetadata (const std::string & _modelConfigStr, msgs::FuelMetadata & _meta) inline
References SemanticVersion::Build(), string::c_str(), string::erase(), std::find_if(), SemanticVersion::Major(), SemanticVersion::Minor(), SemanticVersion::Patch(), SemanticVersion::Prerelease(), and std::stoi().
ConvertGeometryType() [1/2]
std::string gz::msgs::ConvertGeometryType (const msgs::Geometry::Type _type) inline
References std::endl().
ConvertGeometryType() [2/2]
msgs::Geometry::Type gz::msgs::ConvertGeometryType (const std::string & _str) inline
References std::endl().
ConvertJointType() [1/2]
std::string gz::msgs::ConvertJointType (const msgs::Joint::Type & _type) inline
References std::endl().
ConvertJointType() [2/2]
msgs::Joint::Type gz::msgs::ConvertJointType (const std::string & _str) inline
References std::endl().
ConvertPixelFormatType() [1/2]
std::string gz::msgs::ConvertPixelFormatType (const msgs::PixelFormatType & _t) inline
ConvertPixelFormatType() [2/2]
msgs::PixelFormatType gz::msgs::ConvertPixelFormatType (const std::string & _str) inline
ConvertShaderType() [1/2]
std::string gz::msgs::ConvertShaderType (const msgs::Material::ShaderType & _type) inline
References std::endl().
ConvertShaderType() [2/2]
msgs::Material::ShaderType gz::msgs::ConvertShaderType (const std::string & _str) inline
References std::endl().
getInstallPrefix()
std::string gz::msgs::getInstallPrefix ()
getInstallPrefix return the install prefix of the library i.e. CMAKE_INSTALL_PREFIX unless the library has been moved
InitPointCloudPacked()
void gz::msgs::InitPointCloudPacked (msgs::PointCloudPacked & _msg, const std::string & _frameId, bool _memoryAligned, const std::vector< std::pair< std::string, msgs::PointCloudPacked::Field::DataType >> & _fields) inline
References gz::math::roundUpMultiple().
Set() [1/39]
void gz::msgs::Set (AxisAlignedBox * _msg, const gz::math::AxisAlignedBox & _data) inline
References AxisAlignedBox::Max(), and AxisAlignedBox::Min().
Referenced by Convert(), and Set().
Set() [2/39]
void gz::msgs::Set (bool * _data, const Boolean & _msg) inline
Set() [3/39]
void gz::msgs::Set (Boolean * _msg, const bool & _data) inline
Set() [4/39]
void gz::msgs::Set (Color * _msg, const gz::math::Color & _data) inline
References Color::A(), Color::B(), Color::G(), and Color::R().
Set() [5/39]
void gz::msgs::Set (double * _data, const Double & _msg) inline
Set() [6/39]
void gz::msgs::Set (Double * _msg, const double & _data) inline
Set() [7/39]
void gz::msgs::Set (float * _data, const Float & _msg) inline
Set() [8/39]
void gz::msgs::Set (Float * _msg, const float & _data) inline
Set() [9/39]
void gz::msgs::Set (gz::math::AxisAlignedBox * _data, const AxisAlignedBox & _msg) inline
References AxisAlignedBox::Max(), AxisAlignedBox::Min(), and Set().
Set() [10/39]
void gz::msgs::Set (gz::math::Color * _data, const Color & _msg) inline
References Color::Set().
Set() [11/39]
void gz::msgs::Set (gz::math::Inertiald * _data, const Inertial & _msg) inline
References Inertial< class >::MassMatrix(), Inertial< class >::Pose(), Set(), Inertial< class >::SetFluidAddedMass(), Inertial< class >::SetMassMatrix(), and Inertial< class >::SetPose().
Set() [12/39]
void gz::msgs::Set (gz::math::MassMatrix3d * _data, const Inertial & _msg) inline
References MassMatrix3< class >::SetIxx(), MassMatrix3< class >::SetIxy(), MassMatrix3< class >::SetIxz(), MassMatrix3< class >::SetIyy(), MassMatrix3< class >::SetIyz(), MassMatrix3< class >::SetIzz(), and MassMatrix3< class >::SetMass().
Set() [13/39]
void gz::msgs::Set (gz::math::Planed * _data, const PlaneGeom & _msg) inline
References Convert(), and Plane< class >::Set().
Set() [14/39]
void gz::msgs::Set (gz::math::Pose3d * _data, const Pose & _msg) inline
References Convert(), and Pose3< class >::Set().
Set() [15/39]
void gz::msgs::Set (gz::math::Quaterniond * _data, const Quaternion & _msg) inline
References Quaternion< class >::Set().
Set() [16/39]
void gz::msgs::Set (gz::math::SphericalCoordinates * _data, const SphericalCoordinates & _msg) inline
References SphericalCoordinates::CUSTOM_SURFACE, SphericalCoordinates::EARTH_WGS84, std::endl(), SphericalCoordinates::MOON_SCS, SphericalCoordinates::SetElevationReference(), SphericalCoordinates::SetHeadingOffset(), SphericalCoordinates::SetLatitudeReference(), SphericalCoordinates::SetLongitudeReference(), and SphericalCoordinates::SetSurface().
Set() [17/39]
void gz::msgs::Set (gz::math::Vector2d * _data, const Vector2d & _msg) inline
References Vector2< class >::Set().
Set() [18/39]
void gz::msgs::Set (gz::math::Vector3d * _data, const Vector3d & _msg) inline
References Vector3< class >::Set().
Set() [19/39]
void gz::msgs::Set (Inertial * _msg, const gz::math::Inertiald & _data) inline
References Inertial< class >::FluidAddedMass(), Inertial< class >::MassMatrix(), Inertial< class >::Pose(), and Set().
Set() [20/39]
void gz::msgs::Set (Inertial * _msg, const gz::math::MassMatrix3d & _data) inline
References MassMatrix3< class >::Ixx(), MassMatrix3< class >::Ixy(), MassMatrix3< class >::Ixz(), MassMatrix3< class >::Iyy(), MassMatrix3< class >::Iyz(), MassMatrix3< class >::Izz(), and MassMatrix3< class >::Mass().
Set() [21/39]
void gz::msgs::Set (Int32 * _msg, const int32_t & _data) inline
Set() [22/39]
void gz::msgs::Set (int32_t * _data, const Int32 & _msg) inline
Set() [23/39]
void gz::msgs::Set (Int64 * _msg, const int64_t & _data) inline
Set() [24/39]
void gz::msgs::Set (int64_t * _data, const Int64 & _msg) inline
Set() [25/39]
void gz::msgs::Set (PlaneGeom * _msg, const gz::math::Planed & _data) inline
References Plane< class >::Normal(), Plane< class >::Offset(), Set(), and Plane< class >::Size().
Set() [26/39]
void gz::msgs::Set (Pose * _msg, const gz::math::Pose3d & _data) inline
References Pose3< class >::Pos(), Pose3< class >::Rot(), and Set().
Set() [27/39]
void gz::msgs::Set (Quaternion * _msg, const gz::math::Quaterniond & _data) inline
References Quaternion< class >::W(), Quaternion< class >::X(), Quaternion< class >::Y(), and Quaternion< class >::Z().
Set() [28/39]
void gz::msgs::Set (SphericalCoordinates * _msg, const gz::math::SphericalCoordinates & _data) inline
References SphericalCoordinates::CUSTOM_SURFACE, Angle::Degree(), SphericalCoordinates::EARTH_WGS84, SphericalCoordinates::ElevationReference(), std::endl(), SphericalCoordinates::HeadingOffset(), SphericalCoordinates::LatitudeReference(), SphericalCoordinates::LongitudeReference(), SphericalCoordinates::MOON_SCS, SphericalCoordinates::Surface(), SphericalCoordinates::SurfaceAxisEquatorial(), and SphericalCoordinates::SurfaceAxisPolar().
Set() [29/39]
void gz::msgs::Set (std::chrono::steady_clock::duration * _data, const Time & _msg) inline
Set() [30/39]
void gz::msgs::Set (std::string * _data, const StringMsg & _msg) inline
References string::data().
Set() [31/39]
void gz::msgs::Set (StringMsg * _msg, const char * _data) inline
Set() [32/39]
void gz::msgs::Set (StringMsg * _msg, const std::string & _data) inline
Set() [33/39]
void gz::msgs::Set (Time * _msg, const std::chrono::steady_clock::duration & _data) inline
References gz::math::durationToSecNsec().
Set() [34/39]
void gz::msgs::Set (UInt32 * _msg, const uint32_t & _data) inline
Set() [35/39]
void gz::msgs::Set (uint32_t * _data, const UInt32 & _msg) inline
Set() [36/39]
void gz::msgs::Set (UInt64 * _msg, const uint64_t & _data) inline
Set() [37/39]
void gz::msgs::Set (uint64_t * _data, const UInt64 & _msg) inline
Set() [38/39]
void gz::msgs::Set (Vector2d * _msg, const gz::math::Vector2d & _data) inline
References Vector2< class >::X(), and Vector2< class >::Y().
Set() [39/39]
void gz::msgs::Set (Vector3d * _msg, const gz::math::Vector3d & _data) inline
References Vector3< class >::X(), Vector3< class >::Y(), and Vector3< class >::Z().
sizeOfPointField()
int gz::msgs::sizeOfPointField (PointCloudPacked::Field::DataType _dataType) inline
Return the size of a datatype (which is an enum of PointCloudPacked::Field) in bytes.
Parameters
[in] _dataType One of the enums of PointCloudPacked::Field
Returns
Size in bytes. Returns -1 if the type is unknown.
References std::endl().
ToString()
std::string gz::msgs::ToString (const msgs::Discovery::Type & _t) inline
References ConvertDiscoveryType().