name: "Pull Request Labeler"
on:
  schedule:
    - cron: '*/20 * * * *'
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: ignition-tooling/periodic-labeler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_MAPPINGS_FILE: .github/labeler.yml
